[사다리 게임] 무민 미션 제출합니다.
woowacourse/java-ladder pull request #1
Opened 2019-05-15 08:50 UTC by green4469

2019-05-16 08:40 UTC, gracefulBrown requested changes
안녕하세요~ 리뷰를 맡은 브라운 입니다 :)
일등으로 리뷰를 요청해주셨네요 대단하십니다ㅎㅎ
전반적으로 잘 구현해주셨어요! Direction enum을 이용해 position변경을 하는 알고리즘이 인상 깊어요ㅎㅎ

Line의 경우는 컬렉션을 잘 랩핑해주셨는데
이와 비슷하게 Player와 Reward도 Line처럼 구현할 수 없는지 고민을 한번 해 보시는 걸 추천드려요
참고로 "일급컬렉션" 이라는 키워드로 찾아보시면 도움이 될 것 같아요

진행 간 질문이 있으면 편하게 DM 해주세요(혹은 직접 찾아주셔도 좋아요)
화이팅 입니다!!

2019-05-16 08:40 UTC, gracefulBrown commented on src/main/java/ladder/controller/LadderGame.java
> +        ladder.goDown(players);
goDown의 결과로 players의 각 player의 position이 변경 되는 방법도 좋지만
goDown의 리턴타입을 Result 객체로 받아서 outputview에서 출력을 정의 하는 방법도 고려해보면 좋을 것 같습니다 :)
이렇게 할 경우 몇가지의 장점이 있는데 장점에 대해서 한번 고민해보시는 걸 추천드려요 ㅎㅎ

2019-05-16 08:40 UTC, gracefulBrown commented on src/main/java/ladder/domain/Ladder.java
> +    static List<Player> goDown(final List<Line> lines, final List<Player> players) {
goDown 메소드를 static으로 선언한 이유가 있나요?

lines는 ladder 내부 변수이기 때문에 파라미터로 받아 올 필요가 없어서
결국 불필요한 메서드(37 라인)가 없어 질 수 있을 것 같아서요 ^^;;

2019-05-16 08:40 UTC, gracefulBrown commented on src/main/java/ladder/domain/Ladder.java
> +    public List<Player> goDown(List<Player> players) {
goDown은 Ladder의 메소드기 때문에
해당 메서드의 의미는 Ladder가 goDown한다는 의미로 받아드릴 수 있을 것 같아요.
아래에 goDownOneLine같은 메서드도 있는데 메서드를 좀 더 고민해보는 것은 어떨까요?

(Player도 goDown이고 Ladder도 goDown이고 해서 조금 혼동이 오네요 @_@)

2019-05-16 08:40 UTC, gracefulBrown commented on src/main/java/ladder/controller/LadderGame.java
> +    static boolean isOverLengthLimit(boolean isFound, final String reward) {
```
static boolean isOverLengthLimit(final String reward) {
        return reward.length() > MAX_REWARD_LENGTH || reward.length() < MIN_REWARD_LENGTH;
}
```
로 줄여볼 수 있을 것 같아요 ^^

그리고 Reward라는 객체를 두고 Rewards라는 객체를 만들게 되면 이 로직은 Rewards에 포함 될 수 있을 것 같아요~

2019-05-16 08:40 UTC, gracefulBrown commented on src/main/java/ladder/controller/LadderGame.java
> +    private static boolean validateRewardsLength(final List<String> rewards) {
입력받은 reward의 글자수가 지정한 max보다 넘는지, min보다 낮은지 값체크하는 메서드인가요? 
현재 이 메서드는 의도와는 무관하게 마지막 reward만 체크를 하고 있는 것 같아요! 확인한번 해주세요~

2019-05-20 06:09 UTC, green4469 commented on src/main/java/ladder/controller/LadderGame.java
> +        ladder.goDown(players);
goDown의 결과로 player의 position이 변경되는 것이 아니라 변경된 position을 갖는 새로운 Players 객체를 생성하여 반환하도록 구현을 변경했습니다.

``` java
    public Players goDown(Line line) {
        final List<Player> movedPlayers = new ArrayList<>();
        for (Player player : players) {
            movedPlayers.add(player.moveOn(line));
        }
        return new Players(movedPlayers);
    }
```

goDown()의 결과로 Result 객체를 받아오는 것의 장점에 대해서는 아직 잘 모르겠습니다. ㅠㅠ

현재 저의 구현은 **사다리 게임 진행**과 **결과 생성**이 다음과 같이 분리되어 있습니다.

1. 사다리 게임 로직을 담당하는 Engine 객체가 존재하고 이 객체가 Ladder 와 Players 를 인자로 받아서 사다리 게임 진행 후 position이 변경된 Players 를 반환합니다.

2. 이 반환된 Players 와 사용자로부터 입력받은 Rewards 를 이용하여 QueryProcessor 가 Results 를 생성하고 인스턴스변수로 갖습니다. QueryProcessor는 사용자로부터 PlayerName을 입력받고 결과를 반환해주는 객체입니다.

goDown의 결과로 Results 객체가 반환된다면, 사다리 게임 로직과 결과 생성이라는 서로 다른 책임이 결합된다고 생각하여 이와 같이 구현하였습니다. 

goDown이 Results 객체를 반환하도록 구현한다면 어떠한 장점이 있는지 가르쳐주시면 감사하겠습니다!

2019-05-20 06:15 UTC, green4469 commented on src/main/java/ladder/domain/Ladder.java
> +    static List<Player> goDown(final List<Line> lines, final List<Player> players) {
말씀하신 부분이 맞습니다. ㅠ

단순히 테스트 코드를 작성하기 위해 static으로 구현하였던 것으로 기억합니다. 그때는 TDD를 적용하는 방법 자체를 잘못 이해해서 괴상한 구현을 하고 말았습니다.

인스턴스 메서드로 변경하였고, Ladder 클래스에서 Players 클래스로 goDown 의 위치를 옮겼습니다.  (Players 객체는 player 리스트를 갖는 일급컬렉션입니다.)

또한, goDown의 책임을 분리하여 Engine, Ladder, Players 객체에 할당하였습니다. 
- Engine.java
``` java
    /**
     * 사다리를 타고 내려가 위치가 변화된 플레이어들을 반환하는 메소드
     */
    public Players playLadderGame() {
        while (ladder.hasNextLine()) {
            players = players.goDown(ladder.getNextLine());
        }
        ladder.endIteration();
        return players;
    }
```
- Ladder.java
``` java
    public boolean hasNextLine() {
        return index < lines.size();
    }

    public Line getNextLine() {
        return lines.get(index++);
    }

    public void endIteration() {
        this.index = 0;
    }
```
- Players.java
``` java
    public Players goDown(Line line) {
        final List<Player> movedPlayers = new ArrayList<>();
        for (Player player : players) {
            movedPlayers.add(player.moveOn(line));
        }
        return new Players(movedPlayers);
    }
```

2019-05-20 06:31 UTC, green4469 commented on src/main/java/ladder/domain/Ladder.java
> +    public List<Player> goDown(List<Player> players) {
실제로 goDown 을 하는 주체는 Players 이기 때문에, Ladder 에서 Players 로 메서드를 옮겼습니다!

2019-05-20 06:32 UTC, green4469 commented on src/main/java/ladder/controller/LadderGame.java
> +    static boolean isOverLengthLimit(boolean isFound, final String reward) {
브라운의 조언에 따라 Reward 객체와 Rewards 일급 컬렉션을 만들고 길이 검증 코드를 Reward에 포함시켰습니다! 감사합니다.

2019-05-20 06:36 UTC, green4469 commented on src/main/java/ladder/controller/LadderGame.java
> +    private static boolean validateRewardsLength(final List<String> rewards) {
원래 의도는 위의 isOverLengthLimit 메서드와 함께 써서 "rewards 안에 길이 제한을 초과하는 reward 가 하나라도 존재하는 지" 체크하는 메서드였습니다만... 괴상하게 짠 코드라 저도 나중에 이해가 안되더라구요...

그래서 Reward 객체 안으로 로직을 옮겼습니다!

p.s.
금요일에 포비의 강의를 듣고 깊은 뉘우침과 함께 코드를 갈아엎었습니다... 일을 두번이나 하게 만들어서 죄송해요 브라운 ㅠㅠ

조언해주신 부분 최대한 반영하려고 노력했습니다. 감사합니다!

2019-05-20 08:17 UTC, gracefulBrown commented on src/main/java/ladder/controller/LadderGame.java
> +        ladder.goDown(players);
```goDown의 리턴타입이 없이 파라미터로 전달 된 값이 변경됨``` vs ```goDown의 결과를 리턴으로 받음```을 비교하는 내용 맞나요?

우선 파라미터로 전달 된 값을 변경 하는 경우 그 의도를 추론하기가 어려울 것 같아요.
그리고 테스트 코드를 구현하는 경우에도 좋을 것 같아요ㅎㅎ

2019-05-20 09:13 UTC, gracefulBrown approved these changes
정말 코드를 갈아엎으셨군요 ㄷㄷ
그래도 피드백 드린 내용 반영을 잘 해주신 것 같아요 👍 
추가적인 피드백 몇가지 남기니 참고해주시면 좋을 것 같습니다~

2019-05-20 09:13 UTC, gracefulBrown commented on src/main/java/ladder/domain/Line.java
> +    private final List<Point> points;
일급컬렉션 시도 👍

2019-05-20 09:13 UTC, gracefulBrown commented on src/main/java/ladder/domain/Players.java
> +    public static int NUM_OF_PLAYERS;
public final 변수를 사용한 특별한 이유가 있나요?
만약 Players에서 players의 수를 알고 싶은 경우 players.size()를 리턴하는 메서드를 사용하는게 좀 더 좋을 것 같습니다.

2019-05-20 09:13 UTC, gracefulBrown commented on src/main/java/ladder/domain/Engine.java
> +            players = players.goDown(ladder.getNextLine());
Ladder는 Line의 일급컬렉션의 역할을 하고 있다고 할 수 있는데 그렇다면 line에 접근하는 반복문을 Engin이 아닌 Ladder에 위치하는것은 어떨까요?
외부인 Engin의 메서드에서 접근하는 것 보다 Line을 가지고 있는 Ladder에 위치하는것이 좀 더 좋을 것 같은데 어떻게 생각하시나요?

2019-05-21 07:08 UTC, merged