[1단계 - 사다리 생성] 모디(전제희) 미션 제출합니다
woowacourse/java-ladder pull request #100
Opened 2023-02-16 07:24 UTC by jaehee329

안녕하세요!

시간 내어 코드 리뷰해주셔서 정말 감사합니다.

과제를 해결하면서 아래의 궁금증이 생겨 여쭤보고 싶습니다.

* * *
이차원의 사다리를 표현하며 enum 또한 활용하기 위해 좌표마다 `Point`를 가지고 있도록 설계했습니다.
이것으로 `Point`의 List에 해당하는 일급 컬렉션은 `Line`, `Line`의 List에 해당하는 일급 컬렉션이 비로소 Ladder가 되었습니다.

`Ladder`를 위와 같이 구성하여 얻을 수 있는 이점은 `List<List<Point>`와 같은 이해하기 어려운 형태로 표현하지 않을 수 있다는 점입니다.
그러나 제 설계에서는 결국 `Ladder`를 출력하기 위해 `Line`에서는 `Point`의 List를,  
`Ladder`에서는 `Point`의 이중 리스트를 반환하며 다시 중첩된 리스트를 컨트롤러에서 처리하고 있습니다.

결과적으로 설계가 복잡해진만큼의 이점을 취하지 못하는 듯 한데 어떻게 개선할 수 있을지 궁금합니다. 감사합니다!

2023-02-16 11:49 UTC, begaonnuri requested changes
안녕하세요 모디!

TDD로 진행하는 미션이라 쉽지 않으셨을텐데 잘 구현해주셨네요 💯 
몇가지 리뷰 남겨드렸는데 확인해주세요!

질문주신 부분은 코멘트로 남기겠습니다.

2023-02-16 11:49 UTC, begaonnuri commented on docs/README.md
> +    - [ ] 실행 결과를 출력한다.
기능 목록을 상세하게 작성해주셨네요 👍🏻 

하지만 리뷰하는 입장에서 기능 구현이 덜 된건지 착각할 여지가 있을것같아요. 1단계, 2단계를 구분해주세요!

2023-02-16 11:49 UTC, begaonnuri commented on src/main/java/controller/LadderController.java
> +		return participants;
이런 경우 participants가 변경될여지가 있지 않을까요?

객체를 만든 후에 값을 변경하는 것이 아니라 생성자를 통해 names를 받고 안에서 객체를 만들어주면 어떨까요?

2023-02-16 11:49 UTC, begaonnuri commented on src/main/java/controller/LadderController.java
> +		}
적절한 예외처리 👍🏻

2023-02-16 11:49 UTC, begaonnuri commented on src/main/java/controller/LadderController.java
> +	private LadderWidth participatnsNum2LadderWidth(final int participantsNum) {
메서드는 객체의 행위이기 때문에 동사로 시작하는 것이 읽기 좋은 코드입니다 - [클린코드 2장](https://otrodevym.tistory.com/entry/%ED%81%B4%EB%A6%B0-%EC%BD%94%EB%93%9C-2%EC%9E%A5#%EB%A9%94%EC%84%9C%EB%93%9C-%EC%9D%B4%EB%A6%84)

2023-02-16 11:49 UTC, begaonnuri commented on src/main/java/controller/LadderController.java
> +	private LadderWidth participatnsNum2LadderWidth(final int participantsNum) {
final을 붙였을때 어떤 점이 좋게 느껴지셨나요? (바꾸라는 뜻 아님)

2023-02-16 11:49 UTC, begaonnuri commented on src/main/java/domain/Ladder.java
> +	List<Line> lines;
멤버 변수는 반드시 외부의 접근을 제어하는 것이 좋습니다!

2023-02-16 11:49 UTC, begaonnuri commented on src/main/java/domain/LadderBuilder.java
> +	public Ladder build(LadderHeight ladderHeight, LadderWidth ladderWidth, PointGenerator pointGenerator){
함수 인자로 final을 지정한 것도 보이고 지정하지 않으신것도 보이는데 지정하는 기준이 있었을까요?

2023-02-16 11:49 UTC, begaonnuri commented on src/main/java/view/InputView.java
> +	}
참가자 수는 2명 이상이어야 한다는 것은 비즈니스 로직이 아닐까요?

2023-02-16 11:49 UTC, begaonnuri commented on src/main/java/domain/LadderHeight.java
> +}
LadderHeight에선 따로 로직이 존재하지 않는데 값 객체로 만드신 이유가 있을까요?

2023-02-16 11:49 UTC, begaonnuri commented on src/main/java/domain/Ladder.java
> +		return points;
도메인에서 이 부분까지 해줄 필요가 있을까요? 보여주는 형태가 변경된다면 이 코드가 쓸모없어지지 않을까요?

2023-02-16 11:53 UTC, begaonnuri commented
> Ladder를 위와 같이 구성하여 얻을 수 있는 이점은 List<List<Point>와 같은 이해하기 어려운 형태로 표현하지 않을 수 있다는 점입니다.

2차원 컬렉션을 쓰지 않았다면 해당 장점은 사라질것같은데 일급 컬렉션의 다른 장점들은 어떤것들이 있을까요?

https://jojoldu.tistory.com/412 링크를 참고해보시고 다음 리뷰 요청주실때 더 얘기해봐요 😊

2023-02-18 14:34 UTC, jaehee329 commented on docs/README.md
> +    - [ ] 실행 결과를 출력한다.
구현하며 마지막에 신경써서 목록을 관리하지 못했네요 ㅠㅠ 잊지 않고 관리하도록 하겠습니다!

2023-02-18 14:35 UTC, jaehee329 commented on src/main/java/controller/LadderController.java
> +		return participants;
맞는 말씀입니다! 객체지향적으로 기능할 수 있도록 고민해서 설계하겠습니다

2023-02-18 15:26 UTC, jaehee329 commented on src/main/java/controller/LadderController.java
> +	private LadderWidth participatnsNum2LadderWidth(final int participantsNum) {
표면적으로는 입력받은 변수의 재할당을 막는 것이지만,  
아직까지는 대부분의 경우 다른 사람이 코드를 보았을 때 해당 값을 재할당할 의도가 없음을 전달하는 효과가 더 크다고 생각합니다.  
당장은 생성자 혹은 메서드에 final 키워드를 모두 붙여두었는데 경우에 따라 정말 후자의 의도가 필요한 상황에서만 사용하는 것도 좋은 방법이라고는 생각합니다.<br>
실무에서 주로 고려되는 정책이나 이유가 특별히 더 있다면 알려주시면 고민해보겠습니다!

2023-02-18 15:44 UTC, jaehee329 commented on src/main/java/domain/LadderBuilder.java
> +	public Ladder build(LadderHeight ladderHeight, LadderWidth ladderWidth, PointGenerator pointGenerator){
현 과제에서는 인자를 재할당할 일이 없어 일관되게 final을 붙여왔는데 해당 부분에서는 단순 실수로 누락되었습니다!

2023-02-18 16:21 UTC, jaehee329 commented on src/main/java/view/InputView.java
> +	}
맞는 말씀입니다! 해당 부분은 Participants로 옮겼습니다.

2023-02-19 02:53 UTC, jaehee329 commented on src/main/java/domain/LadderHeight.java
> +}
말씀대로 해당 객체에서는 과제 요구사항과 별개로 높이에 대한 기준을 스스로 정하지 않는 한 현재는 로직이 없을 듯합니다.
요구사항에서 모든 원시값을 포장하라는 조건이 있어 값 객체로 변환하게 되었는데 해당 객체에서 처리할만한 로직이 있을까요?

2023-02-19 02:57 UTC, jaehee329 commented on src/main/java/domain/Ladder.java
> +		return points;
설계 과정에서 불만족스러웠지만 더 나은 방향이 떠오르지 않았었습니다.  
현재는 Ladder는 Line만을 의존하도록 개선하였습니다!

2023-02-19 03:17 UTC, jaehee329 commented
안녕하세요, 주신 코멘트를 바탕으로 오래 고민하다 보니 시간이 많이 소요되었습니다.
처음 설계에서는 Ladder가 이중 리스트라는 사실을 어떤 클래스에서 알고 있어야 하는지를 가장 고민했습니다.  
'컨트롤러는 알아도 될 듯 하나 출력 뷰도 Ladder의 구조를 알아도 되나?'에서 가장 고민을 많이 했습니다.  

주신 리뷰를 보고 고민하여 이전에는 Ladder가 해당 사실을 알도록 하여 get 관련 메서드로 이중 리스트를 반환하던 형태에서,
OutputView가 Ladder 자체를 입력받아 알아서 내부의 get() 들을 이중으로 풀어내도록 하는 것이 맞다는 결론을 내었습니다.

다만 아직 의문인 부분이 있는데,  
출력부에서 도메인 객체를 통째로 넘겨받아도 괜찮을까요? 물론 수정은 불가하도록 설계하였지만 앞으로 기능이 증가해도 이러한 형태를 유지해도 될지 의문입니다.
아직 저는 사용하지 않았지만 레이어에서 별도로 DTO를 통해 데이터를 넘기는 것으로 알고있는데, 현 과제에서 사용하기에는 코치님들이나 리뷰어분들이 너무 과하다고 하신다는 것을 들었습니다. 물론 규모가 커지면 당연히 데이터 전달용 객체가 필요하겠지만, 그러한 객체를 사용하는 시점에 대한 판단 기준이 무엇인지 잘 모르겠습니다.<br>
또한 추가적인 의문점으로, 이번 과제부터 모든 원시값을 포장하며 도메인 패키지에 속하는 클래스들이 매우 늘어났는데, 추가로 패키지를 분리할 필요가 있을까요? 이 또한 아직 경험이 적어 일반적으로는 어느 수준으로 세분화하는지 잘 모르겠습니다.

아직 전반적인 설계에 대해 통찰이 부족하여 드는 의문이 많은데, 공부할 만한 자료나 경험을 조금 공유해주시면 감사하겠습니다!

2023-02-19 06:59 UTC, begaonnuri commented on src/main/java/controller/LadderController.java
> +	private LadderWidth participatnsNum2LadderWidth(final int participantsNum) {
> 표면적으로는 입력받은 변수의 재할당을 막는 것이지만,
아직까지는 대부분의 경우 다른 사람이 코드를 보았을 때 해당 값을 재할당할 의도가 없음을 전달하는 효과가 더 크다고 생각합니다.

좋은 접근이네요! 👍🏻 

> 당장은 생성자 혹은 메서드에 final 키워드를 모두 붙여두었는데 경우에 따라 정말 후자의 의도가 필요한 상황에서만 사용하는 것도 좋은 방법이라고는 생각합니다.

아마 대부분의 상황에서 후자처럼 막는것이 필요할거에요. 인자에 새로운 값을 할당해서 로직을 이어나가는것이 대부분의 경우 좋은 패턴이 아니기 때문에 컨벤션으로 지정해 전체적으로 final로 막기도 한답니다.

더 나아가서 자바라는 언어가 언어 차원에서 불변을 지원하지 않기 때문에 이것을 보완하는 장치로 사용하기도 해요. 하지만 매번 final을 다는것이 번거롭기도 하죠. 그래서 이 부분은 팀이나 프로젝트에 따라 컨벤션으로 지정하기도, 지정하지 않기도 합니다.

2023-02-19 07:01 UTC, begaonnuri commented on src/main/java/domain/LadderBuilder.java
> +	public Ladder build(LadderHeight ladderHeight, LadderWidth ladderWidth, PointGenerator pointGenerator){
붙이기로 했다면 전부 붙이는 것이 좋습니다. 일관성이 깨진다면 [깨진 유리창의 법칙](https://ko.wikipedia.org/wiki/%EA%B9%A8%EC%A7%84_%EC%9C%A0%EB%A6%AC%EC%B0%BD_%EC%9D%B4%EB%A1%A0)이 적용되기 쉬울것같아요.

2023-02-19 07:38 UTC, begaonnuri commented on src/main/java/controller/LadderController.java
> +			.collect(Collectors.toList());
모디가 정한 Controller의 책임은 어디까지인가요? 이 부분도 Participants의 생성자에서 처리해보면 어떨까요?

2023-02-19 07:38 UTC, begaonnuri commented on src/main/java/controller/LadderController.java
> +	private LadderWidth getWidthFromParticipantsNum(final int participantsNum) {
적절하게 잘 변경해주셨네요 👍🏻 추가적으로 `FromParticipantsNum` 에 대한 부분은 IDE가 지원해주기때문에 파라미터 이름이나 타입으로 표현하기도 한답니다

2023-02-19 07:38 UTC, begaonnuri commented on src/main/java/domain/LadderHeight.java
> +}
앗 모든 원시값을 포장하라는 요구사항을 제가 놓쳤었네요😅 추가로 사다리가 만들어지는 최소 높이를 검증할 수도 있을것같아요!

2023-02-19 07:40 UTC, begaonnuri commented on src/main/java/domain/Ladder.java
> +		return points;
개선 잘해주셨네요 👍🏻  뷰를 위한 출력 로직이 도메인에 있다보니 콘솔에서 출력 형태가 변하거나 웹으로 뷰가 변경되면 도메인의 코드에 변경이 생길텐데 이 개선을 통해 해소될것같네요!

2023-02-19 07:46 UTC, begaonnuri requested changes
안녕하세요 모디!

리뷰 드린 내용에 대해 고민도 많이 하시고 잘 반영해주셨네요 👍🏻 

지금도 충분히 잘해주셨지만 몇가지 변경사항 추가로 남겼으니 한번 더 확인해주세요~! 질문 주신 부분은 코멘트로 남기겠습니다.

2023-02-19 07:46 UTC, begaonnuri commented on src/main/java/domain/Participants.java
> +		}
도메인 검증 👍🏻

2023-02-19 07:48 UTC, begaonnuri commented
안녕하세요, 주신 코멘트를 바탕으로 오래 고민하다 보니 시간이 많이 소요되었습니다.
처음 설계에서는 Ladder가 이중 리스트라는 사실을 어떤 클래스에서 알고 있어야 하는지를 가장 고민했습니다.
'컨트롤러는 알아도 될 듯 하나 출력 뷰도 Ladder의 구조를 알아도 되나?'에서 가장 고민을 많이 했습니다.

주신 리뷰를 보고 고민하여 이전에는 Ladder가 해당 사실을 알도록 하여 get 관련 메서드로 이중 리스트를 반환하던 형태에서,
OutputView가 Ladder 자체를 입력받아 알아서 내부의 get() 들을 이중으로 풀어내도록 하는 것이 맞다는 결론을 내었습니다.

다만 아직 의문인 부분이 있는데,
출력부에서 도메인 객체를 통째로 넘겨받아도 괜찮을까요? 물론 수정은 불가하도록 설계하였지만 앞으로 기능이 증가해도 이러한 형태를 유지해도 될지 의문입니다.
아직 저는 사용하지 않았지만 레이어에서 별도로 DTO를 통해 데이터를 넘기는 것으로 알고있는데, 현 과제에서 사용하기에는 코치님들이나 리뷰어분들이 너무 과하다고 하신다는 것을 들었습니다. 물론 규모가 커지면 당연히 데이터 전달용 객체가 필요하겠지만, 그러한 객체를 사용하는 시점에 대한 판단 기준이 무엇인지 잘 모르겠습니다.

또한 추가적인 의문점으로, 이번 과제부터 모든 원시값을 포장하며 도메인 패키지에 속하는 클래스들이 매우 늘어났는데, 추가로 패키지를 분리할 필요가 있을까요? 이 또한 아직 경험이 적어 일반적으로는 어느 수준으로 세분화하는지 잘 모르겠습니다.

아직 전반적인 설계에 대해 통찰이 부족하여 드는 의문이 많은데, 공부할 만한 자료나 경험을 조금 공유해주시면 감사하겠습니다!

> OutputView가 Ladder 자체를 입력받아 알아서 내부의 get() 들을 이중으로 풀어내도록 하는 것이 맞다는 결론을 내었습니다.

### 1
고민의 방향이 좋네요!

2023-02-19 08:08 UTC, begaonnuri commented
> '컨트롤러는 알아도 될 듯 하나 출력 뷰도 Ladder의 구조를 알아도 되나?'에서 가장 고민을 많이 했습니다.

고민의 방향이 좋네요 👍🏻 

> OutputView가 Ladder 자체를 입력받아 알아서 내부의 get() 들을 이중으로 풀어내도록 하는 것이 맞다는 결론을 내었습니다.

사다리 미션처럼 작은 규모에선 모디가 생각한 방향이 적절하다고 생각들어요! 저도 모디의 생각에 동감합니다. 다만 규모가 좀 더 커지거나 도메인의 변경사항을 조금 더 제한하고 싶은 경우 말씀해주신것처럼 DTO라는 개념을 사용하기도합니다!

> 물론 규모가 커지면 당연히 데이터 전달용 객체가 필요하겠지만, 그러한 객체를 사용하는 시점에 대한 판단 기준이 무엇인지 잘 모르겠습니다.

판단 기준은 주관적인 영역이긴 합니다. 사다리게임 View에서 도메인을 참조하고 있고, 도메인에서 변경사항이 있을때 View를 얼마나 수정해야할까요? 많아봐야 한 두개의 클래스에 지나지 않을것같아요. 그리고 저희 둘은 모두 사다리게임이 2단계에서 더이상 추가 요구사항이 없을거란것을 알고있죠.

하지만 프로젝트를 진행한다고 가정하고, 규모가 점점 커져서 도메인의 변경사항으로 인해 뷰를 너무 많이 수정하게 되면 DTO가 필요하게 될거에요. 이 시점에 적용하는것이 이론적으론 가장 좋죠. 하지만 프로젝트같은 경우 요구사항이 점점 커질것을 알고 직, 간접적인 경험으로 알기 때문에 DTO를 작은 규모에서도 미리 만들기도 합니다. 하지만 이것도 더 자세히들어가면 **어떤 계층을 둘 것인지**, **어떤 계층마다 DTO를 둘 것인지**와 같은 고민이 선행되기도 해요. 이 부분에 대해선 지금 학습하는걸 추천드리지 않기 때문에 이런 고민도 하는구나~ 정도로 넘어가셔도 좋을것같아요! 이 부분에 대해선 웹을 학습하시면서 더 자세히 알아보실거에요😊

> 또한 추가적인 의문점으로, 이번 과제부터 모든 원시값을 포장하며 도메인 패키지에 속하는 클래스들이 매우 늘어났는데, 추가로 패키지를 분리할 필요가 있을까요? 이 또한 아직 경험이 적어 일반적으로는 어느 수준으로 세분화하는지 잘 모르겠습니다.

지금 규모에선 연관된 개념으로 패키지를 묶기도 하지만 더 나아가선 외부에서 접근을 어떻게 제어할지같은 고민을 하기도 합니다. 그리고 도메인 별로도 분리할 수도 있고 추후에 학습하시겠지만 계층에 따라 분리할 수도 있습니다! (테크코스에서 학습과정을 따라가는데 지장 없다는 가정 하에) 테코브러리에 있는 객체지향 관련 책을 학습해보셔도 좋을것같아요!

2023-02-19 08:59 UTC, jaehee329 commented on src/main/java/domain/LadderHeight.java
> +}
원래 InputView에서 모두 처리했었는데 말씀을 듣고 보니 정수인지 확인하는 로직 정도만 View에서 진행하고  
최소, 최대 높이에 대한 검증은 현재 객체에서 하는 게 좋겠네요! 수정했습니다~

2023-02-19 09:31 UTC, jaehee329 commented on src/main/java/controller/LadderController.java
> +			.collect(Collectors.toList());
첫 설계에서 'Participants를 포장된 원시값인 ParticipantName의 일급 컬렉션으로 구상하며 ParticipantName이 String이라는 사실을 알아도 될까?' 라는 고민을 했었습니다.  
말씀을 듣고 보니 Controller보다는 Participants에서 해당 사실을 알고 있는 게 더 자연스러울 듯 하네요! 수정하였습니다.

2023-02-19 09:32 UTC, jaehee329 commented
주신 피드백 덕분에 부족한 부분 조금 더 수정해보았습니다!  
감사합니다!

2023-02-19 09:39 UTC, begaonnuri approved these changes
처음보다 코드가 정말 많이 개선되었네요 모디!

1단계는 여기서 머지하겠습니다. 고생많으셨어요😊

2023-02-19 09:39 UTC, merged