[1단계 - 사다리 생성] 준팍(박준현) 미션 제출합니다.
woowacourse/java-ladder pull request #102
Opened 2023-02-16 07:26 UTC by junpakPark

안녕하세요 또링! 
이번 1단계 미션을 같이하게 될 준팍(박준현)과 에단(김석호) 입니다.

이번 미션 간 목표는 아래와 같습니다!
* SRP원칙을 지킨다.
* 객체의 책임과 권한 적절하게 분배한다.
* 모든 변수명에 final 붙인다. (당연히 메서드 파라미터에도 final을 붙인다.)
* 모든 원시값과 문자열을 포장한다.
* 일급 컬렉션을 쓴다.

미션 코드의 부족한 점, 수정했으면 좋겠는 점 아낌없이 피드백 해주셨으면 좋겠습니다.
잘 부탁드립니다. 감사합니다!

2023-02-18 04:04 UTC, jnsorn requested changes
안녕하세요, 준팍! 1단계 잘 구현해주셨네요.
커밋을 보니 TDD로 잘 진행해주신 것 같아요. 메서드 분리도 잘 해주셨구요. 👍 
같이 얘기 나눠보면 좋을 부분에 코멘트 남겨두었으니 확인해보시고 다시 요청 주세요!

아, 그리고 사진과 같이 아무 가로선도 없는 상황이 종종 발생하는데 의도하신게 맞을까요?
<img width="451" alt="image" src="https://user-images.githubusercontent.com/31095063/219830278-f0be7420-c188-4166-a52e-2109d30c0800.png">

2023-02-18 04:04 UTC, jnsorn commented on README.md
> + 정답은? 클라이언트에게 다시 여쭤본다. (임의 해석은 하지 않는다.)
어떤 부분인지 정확히 모르겠지만 좋은 말이네요ㅎㅎ 

> 임의 해석은 하지 않는다.

2023-02-18 04:04 UTC, jnsorn commented on src/main/java/laddergame/controller/GameController.java
> +        final Ladder ladder = readHeightWithRetry(names);
메서드명에 retry라는 구체적인 구현 방법이 들어가야 할까요? 😃

2023-02-18 04:04 UTC, jnsorn commented on src/main/java/laddergame/domain/Ladder.java
> +    }
```suggestion
    public List<Line> getLadder() {
        return Collections.unmodifiableList(lines);
    }
```

`toUnmodifiableList` 👍
`toList`가 아닌 `toUnmodifiableList`를 사용하면 어떤 장점이 있을까요?

2023-02-18 04:04 UTC, jnsorn commented on src/main/java/laddergame/domain/Ladder.java
> +    }
메세지도 `MIN_HEIGHT`를 이용해서 작성하면 나중에 `MIN_HEIGHT`가 변경 되었을 때 메세지를 수정하지 않아도 될 것 같아요.

2023-02-18 04:04 UTC, jnsorn commented on src/main/java/laddergame/domain/Line.java
> +    private final List<Boolean> statuses;
status는 너무 추상적인 네이밍인데요, 더 명확한 용어는 없을까요?

2023-02-18 04:04 UTC, jnsorn commented on src/main/java/laddergame/domain/Line.java
> +    }
> 사다리 타기가 정상적으로 동작하려면 라인이 겹치지 않도록 해야 한다.


요구사항준수 💯

2023-02-18 04:04 UTC, jnsorn commented on src/main/java/laddergame/domain/Line.java
> +        }
status가 0개여서 사다리를 만들 수 없는 상황인데, 메세지는 Player에 대해 이야기하고 있어요. 
예외상황에 대한 메세지가 정확할까요?

2023-02-18 04:04 UTC, jnsorn commented on src/main/java/laddergame/domain/PickStrategy.java
> +}
`@FunctionalInterface` 👍

2023-02-18 04:04 UTC, jnsorn commented on src/main/java/laddergame/domain/RandomBooleanPicker.java
> +            random = SecureRandom.getInstanceStrong();
SecureRandom 사용 👍

2023-02-18 04:04 UTC, jnsorn commented on src/main/java/laddergame/domain/RandomBooleanPicker.java
> +            throw new IllegalStateException("랜덤 객체를 생성할 수 없습니다.");
호출 메서드에서 명시한 예외를 처리해주셨네요 💯
다만 예외를 따로 출력하고 있는데, 출력하는 이유가 있을까요?

2023-02-18 04:04 UTC, jnsorn commented on src/main/java/laddergame/view/InputView.java
> +    private static final BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(System.in));
scanner 대신 BufferedReader를 사용한 이유가 있을까요?

2023-02-18 04:04 UTC, jnsorn commented on src/main/java/laddergame/view/InputView.java
> +        }
예외 상황 세분화하셨군요! 👏🏻

2023-02-18 04:04 UTC, jnsorn commented on src/main/java/laddergame/view/OutputView.java
> +        System.out.println(System.lineSeparator() + "실행결과" + System.lineSeparator());
`System.lineSeparator()` 👍

2023-02-18 04:04 UTC, jnsorn commented on src/main/java/laddergame/view/OutputView.java
> +            return HORIZONTAL_LINE.ladderElement.repeat(maxNameLength) + VERTICAL_LINE.ladderElement;
의미있는 변수로 만들어 가독성을 높일 수 있을 것 같아요.

2023-02-18 04:04 UTC, jnsorn commented on src/test/java/laddergame/domain/LineTest.java
> +        }
예외메세지까지 비교해서 더 정확한 테스트를 해보는 건 어떨까요?

2023-02-18 04:04 UTC, jnsorn commented on src/test/java/laddergame/domain/TestBooleanPicker.java
> +public class TestBooleanPicker implements PickStrategy {
테스트용 Picker 👍

2023-02-18 04:04 UTC, jnsorn commented on src/test/java/laddergame/domain/LineTest.java
> +        }
```suggestion
        void givenLine_thenCreateBooleanList() {
            //given
            final List<Boolean> statuses = List.of(true, false, false);
            
            //when
            final Line line = Line.of(statuses.size(), new TestBooleanPicker(statuses));

            //then
            assertThat(line)
                    .extracting("statuses")
                    .isEqualTo(List.of(true, false));
        }
```

2023-02-18 04:04 UTC, jnsorn commented on src/main/java/laddergame/domain/Name.java
> +        this.name = name.trim();
Name에서 전달받은 값을 가공(trim)하고 있어요. 괜찮을까요?

2023-02-18 04:04 UTC, jnsorn commented on src/main/java/laddergame/domain/RandomBooleanPicker.java
> +public class RandomBooleanPicker implements PickStrategy {
네이밍에 타입이 명시되어있네요. 이렇게 네이밍하신 이유가 있을까요?

2023-02-18 04:04 UTC, jnsorn commented on src/main/java/laddergame/domain/Line.java
> +    private final PickStrategy strategy;
Line이 PickStrategy를 멤버로 갖고 있네요. 왜 이렇게 구현하셨는지 궁금해요~! 🧐

2023-02-18 04:04 UTC, jnsorn commented on src/main/java/laddergame/domain/Names.java
> +    private final List<Name> names;
```suggestion
    private static final int MIN_NUMBER_OF_PLAYERS = 2;
    private static final int HALF = 2;
    
    private final List<Name> names;
```

2023-02-18 04:04 UTC, jnsorn commented on src/main/java/laddergame/domain/Line.java
> +    private List<Boolean> createStatuses(int numberOfStatus) {
전반적으로 final이 붙어있는걸 보면 여기는 실수로 빼먹으신거 같네요~!
전반적으로 final을 사용하여 선언하신 이유도 궁금합니다 :)

2023-02-18 04:21 UTC, junpakPark commented on README.md
> + 정답은? 클라이언트에게 다시 여쭤본다. (임의 해석은 하지 않는다.)
"5자 기준으로 출력하기 때문에 사다리 폭도 넓어져야한다"
해당 부분의 의미가 이름의 길이에 따라 사다리가 동적으로 넓어져야한다는 의미인지,
사다리 폭의 길이가 최소 5자 이상이어야한다는 의미인지 헷갈렸어요!

이런 문제에 대해 저희가 임의 판단을 하기보다는 
요청을 준 클라이언트에게 직접 물어보는게 더 좋은 방법이라고 생각하지만,

현재 미션에서는 해당 방법을 적용하기 어려우니
저와 페어가 임의로 "이름의 길이에 따라 사다리 폭이 동적으로 변화한다"고 
해석했음을 의미하는 내용이었습니당!

저랑 페어만 알아볼 수 있게끔 너무 축약해서 적었네요ㅠㅠ

2023-02-18 06:38 UTC, junpakPark commented on src/main/java/laddergame/domain/Line.java
> +    private final PickStrategy strategy;
PickStrategy를 외부에서 주입받는 식으로 진행하게 된다면, 
PickStrategy가 위치한 곳에서 일급 컬렉션의 내부에 위치한 Line 사이에 존재한 모든 객체들이 
PickStrategy를 주입받아야 하는 식으로 구현하는 방법만 떠올랐습니다.

Ladder 등 사이에 존재하는 객체들이 PickStrategy를 알 필요가 없다면
굳이 주입 받지 않는 게 좋다고 생각해서 Line 객체만 PickStrategy를 멤버로 갖고 있게끔 구현했습니다.

2023-02-18 06:40 UTC, junpakPark commented on src/main/java/laddergame/domain/Line.java
> +    private final List<Boolean> statuses;
선이 있는 상태인지 없는 상태인지 표현하기 위해서 status라는 네이밍을 썼는데요,
있는 상태는 존재한다는 의미니, existence로 네이밍 하는 게 
처음 코드를 보는 분들도 이해할 수 있는 네이밍이라는 생각이 드네요!

2023-02-18 06:46 UTC, junpakPark commented on src/main/java/laddergame/domain/Line.java
> +    private List<Boolean> createStatuses(int numberOfStatus) {
입력된 변수가 메서드 내부에서 임의로 재할당 되는 것을 막기 위해 
모든 변수와 메서드의 파라미터들에 final을 사용하였습니다.
변수의 값이 변경된다면 새롭게 변수로 선언해 의미를 더 명확히 하는 것이  
예측하기 쉬운 코드를 작성하는데 도움이 되기 때문입니다.

2023-02-18 06:48 UTC, junpakPark commented on src/main/java/laddergame/domain/RandomBooleanPicker.java
> +public class RandomBooleanPicker implements PickStrategy {
해당 코드를 처음 보는 사람이 리턴값을 예측하기 쉽도록 타입명을 명시하였습니다!

2023-02-18 06:52 UTC, junpakPark commented on src/main/java/laddergame/view/InputView.java
> +    private static final BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(System.in));
콘솔 게임에서 입력이 느리다면 사용자가 답답하지 않을까 해서
 scanner보다 속도가 빠른 BufferedReader를 사용해봤어요!

2023-02-18 06:59 UTC, junpakPark commented on src/main/java/laddergame/domain/Name.java
> +        this.name = name.trim();
곰곰히 생각해보니 생성자 내부에서 가공하는 것이 
저랑 페어가 파라미터에 final 선언한 이유와 대치된다는 생각이 드네요!

외부에서 trim한 값을 받는 것이 더 좋을 것 같아요!

2023-02-18 07:21 UTC, junpakPark commented on src/main/java/laddergame/domain/Ladder.java
> +    }
`toUnmodifiableList()` 메서드는 `toList()`메서드와 달리 
반환된 List 객체를 수정불가능하게끔 만들어주고, 
만약 수정을 하게된다면 `UnsupportedOperationException` 예외를 발생시키기 때문에,

Ladder 안의 Line들이 의도치 않게 변경되는 상항을 예방해줄 수 있습니당!

2023-02-18 07:44 UTC, junpakPark commented on src/main/java/laddergame/controller/GameController.java
> +        final Ladder ladder = readHeightWithRetry(names);
메서드명에서 오류 발생 시 재입력을 받는다는 내용을 인지할 수 있어야 
해당 코드를 처음 보는 사람이 재입력 관련 로직을 찾기에 쉬울 거란 생각이 들었어요!

또링은 혹시 어떠한 이유에서 이 질문을 주셨는지 여쭤봐도 될까요?

2023-02-18 07:51 UTC, junpakPark commented on src/main/java/laddergame/domain/RandomBooleanPicker.java
> +            throw new IllegalStateException("랜덤 객체를 생성할 수 없습니다.");
예외 발생 때문에 게임이 종료되는 상황을 막기 위해 
예외 되던지기를 사용했어요!

새로 던진 예외를 Controller에서 catch해서 
잘못된 부분부터 다시 게임을 진행하는 것이 
게이머가 게임을 할 때 더 편리할 것이라고 생각했습니당!

2023-02-18 07:55 UTC, junpakPark commented on src/main/java/laddergame/domain/Line.java
> +        }
`status`라는 변수명이 맘에 들지 않아서 메시지 작성에 어려움을 겪다가 `Player`로 표현해버렸네요 ㅠ
`status의 갯수는 1보다 작을 수 없습니다` 이런 식으로 표현하는 것이 더 좋을 것 같아요!

2023-02-18 09:57 UTC, junpakPark commented
안녕하세요 또링!  

질문 주신 내용에 대해 리팩터링 진행하거나, 
생각을 정리해서 댓글로 남겼습니다! 

사다리 게임 중 가로선이 전혀 안생기는 경우에 관한 질문은 
답변을 남길 곳이 마땅치 않아 여기에 남기겠습니다!  

해당 상황에 대해 제출 전에 이미 인지하고 있었고,
의도적으로 별다른 조치를 취하지 않은 것이 맞습니다!

가로선이 발생하지 않는 상황이 랜덤으로 나타나기에,
 이 역시 게임의 한 부분이라고 생각했기 때문입니다. 

하지만 또링의 질문을 듣고, 개발자의 입장이 아닌 게이머의 입장에서 생각해보니, 
이런 의도에 대한 사전 설명 없이 가로선이 나타나지 않으면 
당황할 수 있겠다는 생각이 드네요!

개인적으로는 게임 시작 전에 해당 내용을 공지하는 식으로 처리하는 걸 선호하는 편인데, 
해당 방식 대신, 한 층(Line)에 가로선이 최소 하나 이상 발생하는 로직 추가했습니다.

하지만 이 방법 역시 4명이상이 게임을 할 경우, 가로선이 전혀 연결되지 않을 가능성을 
완전 배제하지는 못한다는 단점이 역시 발생합니다.
더 세련된 방법에 대해서 조금 더 고민해보겠습니다.

꼼꼼한 리뷰 감사합니다 또링! 

덕분에 깊은 고민 없이 프로그래밍했던 사항에 대해
다시 한번 되짚어볼 수 있는 기회를 가질 수 있었어요! ㅎㅎ

이번 피드백도 잘 부탁드립니다!!

2023-02-19 00:48 UTC, junpakPark commented on src/main/java/laddergame/domain/RandomBooleanPicker.java
> +            throw new IllegalStateException("랜덤 객체를 생성할 수 없습니다.");
습관처럼 try-catch 후, 예외 메시지를 출력해버렸네요..
콘솔 게임이 아니라면 로그로써 활용될 수 있겠으나, 콘솔 게임에서는 유저의 혼란을 가중 시킬 수 있다는 점에서 제거 하는 게 더 좋을 것 같습니다!

2023-02-19 15:00 UTC, jnsorn requested changes
안녕하세요 준팍! 질문에 자세히 답변 남겨주셔서 준팍의 구현의도를 더 잘 이해할 수 있었습니다 👍 
고민해보면 좋을 부분에 코멘트 남겼는데 확인해주시고, 다시 요청 주세요!
이번주도 화이팅입니다. 😎

2023-02-19 15:00 UTC, jnsorn commented on src/main/java/laddergame/controller/GameController.java
> +        final Ladder ladder = readHeightWithRetry(names);
메서드 이름으로 재입력을 인지할 수 있도록 retry를 넣어 명명하신거군요 ㅎㅎ

저는 생각이 살짝 다른데요, 게임 흐름을 관리하는 process()에서는 사용자로부터 이름을 입력받는다와 같은 정보만 있어도 충분하다는 생각이에요. 

'오류 발생 시 재입력'이라는 것은 입력 정책에 대한 세부 구현사항이라 생각하는데, 구현은 자주 바뀌는 부분이라 메서드명은 구현방식에 크게 의존하지 않도록 작성하는 걸 선호합니다. 즉, 메서드를 통해 입력받는 행위를 추상화시켜 외부로부터 내부 로직을 감추는 것이죠. 준팍이 말한 재입력 관련 로직을 파악하거나 수정해야 하는 경우는, 어차피 입력과 관련된 메서드를 살펴볼테니 굳이 이름으료 표현하지 않아도 괜찮을 것 같아요.

2023-02-19 15:00 UTC, jnsorn commented on src/main/java/laddergame/domain/Line.java
> +    private final PickStrategy strategy;
제가 준팍의 말을 제대로 이해했는지 모르겠네요 😶
Line이 PickStrategy를 굳이 멤버로 갖고 있지 않아도 될 것 같다는 의견이었습니다~! 
발판을 만들 때(createLineStatus()) 인자로 넘겨줘도 충분할 것 같아요 ㅎㅎ

2023-02-19 15:00 UTC, jnsorn commented on src/main/java/laddergame/domain/RandomBooleanPicker.java
> +public class RandomBooleanPicker implements PickStrategy {
이것도 위에 retry 네이밍과 관련해 말씀드린 이유와 일맥상통하는데요, Boolean이라는 것은 해당 클래스의 책임이 아닌 코드 구현와 관련된 용어이기 때문에 네이밍시에는 지양하는게 좋다고 생각합니다. 네이밍은 해당 코드를 요약하기보다, 어떤 역할과 책임을 수행하는지에 초점을 맞추면 좋을 것 같아요. Name을 StringName이라고 하지 않는 것 처럼요!

2023-02-19 15:00 UTC, jnsorn commented on src/main/java/laddergame/domain/Line.java
> +    private final List<Boolean> statuses;
네 ㅎㅎ 보통 boolean 타입의 변수는 is, has와 같은 동사/조동사로 시작하니 참고해주세요!

2023-02-19 15:00 UTC, jnsorn commented on src/main/java/laddergame/domain/Line.java
> +    private static final int ABSENCE_OF_TRUE = 1;
어떤 상수인지 와닿지 않는데 더 좋은 이름이 없을까요~? 
true라는 값 대신, 도메인 용어(ex. 발판, 브릿지)를 사용하여 네이밍하면 가독성이 올라갈 것 같아요 ㅎㅎ

2023-02-19 15:00 UTC, jnsorn commented on src/main/java/laddergame/domain/Ladder.java
> +    public Ladder(final int height, final int numberOfPlayers) {
(참고) 
```suggestion
    public Ladder(final int height, final int playerCount) {
```
와 같이 간단하게 표현해도 좋을 것 같아요 ㅎㅎ 개인적으로 변수명에 of가 들어가면 잘 안읽히더라구요.

2023-02-19 15:00 UTC, jnsorn commented on src/main/java/laddergame/domain/Ladder.java
> +    public Ladder(final int height, final int numberOfPlayers) {
> 모든 원시 값과 문자열을 포장한다

`height`도 포장해볼까요?

2023-02-19 15:00 UTC, jnsorn commented on src/main/java/laddergame/domain/Line.java
> +    }
리팩터링도 TDD로 구현해주세요 :-) 
현재 새로 추가된 요구사항에 대한 테스트가 없네요. 

> 각 라인에 대해 발판은 하나 이상 존재한다.

2023-02-19 15:00 UTC, jnsorn commented on src/main/java/laddergame/view/InputView.java
> +    private static final BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(System.in));
네 좋습니다 ㅎㅎ 컨벤션 상 아래가 맞겠네요
```suggestion
    private static final BufferedReader BUFFERED_READER = new BufferedReader(new InputStreamReader(System.in));
```

2023-02-19 15:00 UTC, jnsorn commented on src/main/java/laddergame/view/OutputView.java
> +
OutputView를 enum으로 선언하신 이유가 궁금해요!

2023-02-19 15:00 UTC, jnsorn commented on src/main/java/laddergame/domain/Names.java
> +    }
view가 변경되면 해당 메서드도 변경될 것 같은데요 Names의 역할이 맞을까요?

2023-02-19 15:00 UTC, jnsorn commented on src/main/java/laddergame/domain/Line.java
> +    }
List<Boolean> line에 true만 존재하는 경우에도 사다리 발판을 다시 생성하는데, 의도한 로직이 맞을까요?

2023-02-20 00:30 UTC, junpakPark commented on src/main/java/laddergame/domain/Line.java
> +    }
네 의도한 로직이 맞습니다! 

발판의 갯수가 1 초과일때, true만 존재하는 경우는
발판이 처음부터 끝까지 모두 이어져있다는 의미로,

> 사다리 타기가 정상적으로 동작하려면 라인이 겹치지 않도록 해야 한다.

위의 요구사항에 어긋나기 때문입니다!

2023-02-20 09:02 UTC, junpakPark commented on src/main/java/laddergame/domain/Names.java
> +    }
Names는 첫번째 이름의 길이만 리턴해주고, 필요한 숫자로 변환하는 작업의 역할은 OutputView에서 맡아주는 게 좋을 것 같습니다!

2023-02-20 09:03 UTC, junpakPark commented on src/main/java/laddergame/view/OutputView.java
> +
enum의 요소를 사용하는 곳이 OutputView 밖에 없기 때문에 바로 사용하고자 enum으로 선언했었습니다!
하지만 OutputView의 역할과 책임을 생각해봤을 때 따로 분리해주는 게 더 자연스러울 것 같네요...

2023-02-20 09:16 UTC, junpakPark commented
안녕하세요 또링! 

질문 주신 내용에 대해 리팩터링 진행 완료하였습니다 ㅎㅎ

특히 네이밍 관련 조언 덕분에 객체들의 책임과 권한에 대해서
다시 한번 고민해보고, 원시값 포장이 왜 필요한지에 대해서도 이해할 수 있었습니다.

꼼꼼한 리뷰 감사합니다 또링! 
이번 피드백도 잘 부탁드립니다!!

2023-02-21 04:07 UTC, jnsorn commented on src/main/java/laddergame/domain/Floor.java
> +public class Floor {
https://github.com/woowacourse/java-ladder/pull/102#discussion_r1111240184

> 어떤 상수인지 와닿지 않는데 더 좋은 이름이 없을까요~?
> true라는 값 대신, 도메인 용어(ex. 발판, 브릿지)를 사용하여 네이밍하면 가독성이 올라갈 것 같아요 ㅎㅎ

제가 이 리뷰를 남긴건 상수 네이밍때문이었습니다 ㅎㅎ 
`private static final int ABSENCE_OF_TRUE = 1;`
true의 필수 개수라기 보다는, 최소 발판 개수와 같은 의미가 더 이해하기 쉬울거라 생각해서요.

Line을 Floor로 수정해주셨는데, 원래 이름이 맞지 않나 싶네요.
Line이 Floor들로 이루어진것이지, Floor가 Floor들로 이루어진게 아니라 생각해서요. 
준팍 의견도 들려주시면 좋을 것 같아요.

2023-02-21 04:07 UTC, jnsorn commented on src/main/java/laddergame/domain/Link.java
> +    ;
Link라는 용어가 등장했네요
연결에 대한 속성을 enum으로 관리! 👍

2023-02-21 04:07 UTC, jnsorn commented on src/main/java/laddergame/domain/Link.java
> +    ;
다만 커밋 로그를 보아하니, 이 부분도 TDD로 리팩터링이 진행되진 않았네요 ㅠㅠ 
이번 미션이 TDD를 경험하는것이니만큼 테스트는 필수적으로 작성해주시고, 최대한 TDD로 진행해주세요!

2023-02-21 04:07 UTC, jnsorn commented on src/main/java/laddergame/view/OutputFormat.java
> +public enum OutputFormat {
OutputFormat보다는 사다리에 대한 포멧들이니 LadderElement정도로 표현하면 어떨까요?

2023-02-21 04:07 UTC, jnsorn commented on src/main/java/laddergame/domain/Line.java
> +    }
오 그 상황까지 고려하신거군요! 👍 

그렇다면 가독성을 위해 말씀해주신 조건을 변수로 빼서 판단하는건 어떨까요? 

`new HashSet<>(floor).size()`

위 코드로 검증하고자하는 조건을 모두 검증할 수는 있지만, 코드를 읽는 입장에서는 무엇을 검증하고자 하는지 파악하기 어려워요. 

1. 발판이 존재하지 않는 경우
2. 모든 높이에 발판이 존재하는 경우

2023-02-21 04:11 UTC, jnsorn commented on src/main/java/laddergame/domain/LinkPicker.java
> +public class LinkPicker implements PickStrategy {
유독 네이밍에 대한 리뷰를 많이 달게 되네요 ㅎㅎ 네이밍은 개인의 취향에 의해 많이 갈리는 부분이라, 참고만 해주세요!! :) 
```suggestion
public class RandomLinkGenerator implements LinkGenerator {
```
발판(링크)을 생성하는 전략에 대한 객체이니, 위와 같은 이름은 어떨까요?
어떤 역할을 하는 인터페이스인지, 또 어떤 방식의 구현체인지 이해하기 좋을 것 같네요.

2023-02-21 04:13 UTC, jnsorn commented on src/main/java/laddergame/domain/Ladder.java
> +        this.lines = createLadder(height.getHeight(), numberOfPlayers);
Ladder를 생성할때도 Height객체로 받는게 좋지 않을까요~? 
원시값을 포장했는데, 값만 전달한다면 포장한 의미가 없어질 것 같아요.
실제 사용시에만 꺼내 쓰면 값 포장을 쓰는 목적에도 부합할 것 같네요. 😃

2023-02-21 04:15 UTC, jnsorn approved these changes
안녕하세요 준팍! 피드백 잘 반영해주셨어요. 👍 
특히 Link를 의미있는 객체로 만들어주어 코드가 더 깔끔해진것 같아요.
몇 가지 코멘트를 더 남기긴했는데, 다음 단계에서 같이 확인해주세요.
1단계 요구사항은 충족한 것 같아 머지하겠습니다.
2단계에서 만나요! 🪜🪜🪜

2023-02-21 04:16 UTC, merged

2023-02-21 04:27 UTC, junpakPark commented on src/main/java/laddergame/domain/Floor.java
> +public class Floor {
Floor를 저는 층수를 나타내기 위해서 표현했는데,
바닥이란 뜻도 있어서 의도 전달이 잘 안된 것 같습니다

더 좋은 네이밍 고민해보겠습니다!!