[1단계  - 사다리 생성] 제나(위예나) 미션 제출합니다.
woowacourse/java-ladder pull request #105
Opened 2023-02-16 07:32 UTC by yenawee

안녕하세요 ! ☺️

사다리 미션 리뷰요청 드립니다.
이번 미션을 진행하면서 중점을 뒀던 부분은 TDD 였는데 페어와 저희가 과연 TDD 를 하고 있는게 맞나(..?) 하는 의문을 계속 가지며 미션을 진행했던 거 같아요!

프로그래밍을 하면서는 분명 궁금했던 점들이 많았는데 구현을 끝내고 리뷰 요청을 드리려니 궁금했던 점들이 기억이 잘 나지가 않습니다 ㅠㅠ 시간 안에 요청드리기 위해서 궁금점들이 잘 정리가 되면 코멘트로 추가하도록 하겠습니다 . 

감사합니다 !

2023-02-16 07:41 UTC, include42 commented
안녕하세요 제나! 만나서 반갑습니다.
이번에 리뷰를 맡게 된 리뷰어 카프카입니다.

리뷰는 오늘 저녁 11시~12시 사이에 진행 예정입니다. (중간에 일정이 있어서 조금 늦어지네요)
혹시 더 늦어지게 되면 전달드리겠습니다.
- 그 사이 혹시 궁금한 점 있다면 코멘트 남겨주세요 😄 

미션 진행하시느라 고생 많으셨습니다. 👍

2023-02-16 15:56 UTC, include42 requested changes
안녕하세요, 제나! 리뷰어 카프카입니다.
말씀드린 것보다 리뷰가 조금 늦어졌네요. 😢 

코드 잘 구현해 주셨습니다. 테스트 코드를 분류별로 꼼꼼하게 잘 짜주신 부분이 인상적이었습니다. 💯 
몇몇 궁금한 부분과 수정이 필요한 부분에 대해 코멘트 남겨두었습니다.
추가로 궁금한 사항이 생기면 코멘트 혹은 dm 부탁드립니다.

2023-02-16 15:56 UTC, include42 commented on src/main/java/Application.java
> +                new LadderGameController(new InputView(), new OutputView(), new RandomTrueOrFalseGenerator());
오, 여기서 필요한 클래스들을 주입해 줬네요!
이부분은 취향이 갈릴수도 있을것같은데, 저는 좋다고 생각합니다.

2023-02-16 15:56 UTC, include42 commented on src/main/java/controller/LadderGameController.java
> +            outputView.printErrormessage(e.getMessage());
여기서 예외처리를 해줘도 좋지만, 입력을 받는 부분을 별도 메소드로 나눈 뒤 거기서 catch를 해주면 어떨까요?
그러면 구현하기에 따라 잘못된 값을 입력해도 다시 입력을 받을 수 있지 않을까요?
이부분을 어떻게 구현할지 고민해보면 좋겠습니다.

2023-02-16 15:56 UTC, include42 commented on src/main/java/controller/LadderGameController.java
> +        while (height.isPossibleCount()) {
여기서 height를 구현한 것은 getter를 쓰지 않고 보다 도메인에 맞게 구현하려고 한 부분으로 이해됩니다.
다만 이렇게 되면 계속 height에 minus를 해줘야하는데, 이게 올바른 동작일까요?
이부분은 getter를 받아 for로 반복하도록 구현하는게 오히려 직관적일수도 있다고 생각합니다.

2023-02-16 15:56 UTC, include42 commented on src/main/java/controller/LadderGameController.java
> +        while (height.isPossibleCount()) {
추가로, Ladder의 생성자에 players와 height를 넣어서 생성해주면 여기서 List<Line>을 만들 필요가 없을 것 같네요.
이 부분이 가능할지 고민해서, 가능하다면 수정해주면 좋겠습니다.

2023-02-16 15:56 UTC, include42 commented on src/main/java/domain/Line.java
> +            points.add(correctOverLapPoints(points.get(count - 1), trueOrFalseGenerator.generate()));
반복문 순회를 0부터 하면 -1을 해줄 필요가 없을듯한데, 0번지를 미리 추가해주고 마지막에 지우는 탓에 로직이 복잡해졌네요.
`correctOverLapPoints` 를 더 간단하게 개선할 수는 없을까요? 
예를 들어 0번지를 미리 generator에서 나온 값을 바탕으로 만들어두고 1번지부터 순회할 수도 있을 것이고, 그러면 remove가 필요하지 않을 듯도 하네요. 이 부분은 페어와 논의를 해보고, 최대한 직관적인 방향으로 수정해보길 권해요.

2023-02-16 15:56 UTC, include42 commented on src/main/java/domain/Way.java
> +    MAXNAMELENGTH1(1, "-", " "),
상수를 5개 만든게 비효율적으로 보입니다.
String.repeat 메소드를 통해 반복을 해줄 수 있으니, 해당 메소드를 활용할 수 있겠네요.
혹은 클래스 내에 int를 인자로 받아 길이에 맞는 다리를 출력해주는 메소드를 추가할수도 있고요.

2023-02-16 15:56 UTC, include42 commented on src/main/java/laddervalidate/HeightValidator.java
> +public class HeightValidator {
Validator들을 꼼꼼하게 잘 만들어 준 부분이 인상적이었습니다. 💯

2023-02-16 15:56 UTC, include42 commented on src/main/java/laddervalidate/HeightValidator.java
> +        if (!Pattern.matches("^[0-9]*$", height)) {
정규식 패턴은 위에 상수로 정의할 수 있겠죠?
그리고 정규식의 경우, 저는 Validator에서 사용하는걸 좋아하는 편이지만 상황에 따라서는 사용하지 않기도 해요.
만약 팀이 정규식에 익숙하지 않다면 코드리뷰에서 오류를 걸러낼 수 없고, 직관적으로 이해하기 어려울 수 있으니까요.
이부분은 페어와 합의가 된 부분일테니 유지하되, 앞으로 프로젝트를 진행할때 정규식을 쓰는 것에 대해 많이 논의해보길 권합니다.

2023-02-16 15:56 UTC, include42 commented on src/main/java/laddervalidate/PlayerNameValidator.java
> +    }
`PlayerNameValidator.validate` 메소드를 만들고 그 안에서 이 메소드들을 순차적으로 호출하면 어떨까요?
현재 구조대로면, 아래의 문제가 추후 생길 수 있습니다.
 - 새로운 검증 조건이 생기면 `PlayerNameValidator`를 쓰는 모든 클래스에 해당 메소드를 추가해야 함
 - `PlayerNameValidator`를 사용하는 클래스에서 원하는 순서대로 검증을 수행하지 않을 수 있음

2023-02-16 15:56 UTC, include42 commented on src/main/java/view/InputView.java
> +        System.out.println(NAME_INPUT_REQUEST);
InputView에서 입력을 받는 과정에 출력이 필요하므로, 이렇게 사용한 점은 좋다고 생각합니다.
다만 OutputView가 별개로 존재하기 때문에, Controller에서 OutputView를 호출해 필요한 텍스트를 출력하는게 더 좋을수도 있어요.
이부분은 페어와 논의해보고, 더 좋다고 생각하는 방향으로 진행하면 좋겠습니다. 
저도 정답이 없다고 생각하는 부분이라, 리뷰를 하면서도 이 부분에 대해서는 가능성을 열어두고 싶네요.

2023-02-16 15:56 UTC, include42 commented on src/main/java/view/OutputView.java
> +    private String changeFormat(Line line, int maxPlayerNameLength) {
플레이어의 최대 이름길이에 맞게 길이가 수정되도록 구현해주신 부분 매우 좋습니다.
다만 아래의 maxPlayerNameLength - 1 부분이 아쉽네요.
해당 값을 메소드 내에서 변수로 선언해주면 어떨까요? 적절한 이름으로 선언해주면 의미가 분명해지겠네요.

2023-02-16 15:56 UTC, include42 commented on src/test/java/LineTest.java
> +    class Creat {
클래스명에 오타가 났네요 😄 
그리고 이렇게 분류별로 클래스를 나눠 테스트한 부분 좋았습니다. 💯 
간단한 테스트라면 오버엔지니어링일수도 있지만, 아래의 다른 테스트를 보니 분류가 명확하게 된다고 느껴지네요.

2023-02-16 15:56 UTC, include42 commented on src/test/java/LineTest.java
> +}
code에 endline이 있는 경우도 있고 없는 경우도 있네요.
저는 endline을 코드에 넣어주는 편인데, 서버 개발에서는 해당 부분이 상관이 없어 아예 넣지 않는 경우도 있습니다.
취향의 문제이므로 수정을 요하지는 않고요, 다만 이에 대해 왜 git에서 표시를 해주는지 학습해보면 좋겠습니다. 👍

2023-02-16 15:56 UTC, include42 commented on src/test/java/PlayerTest.java
> +    class playerCount {
이부분은 테스트가 직관적이여서, 꼭 수정할 필요는 없습니다.
다만, 성공 케이스와 실패 케이스를 나눠서 parameterizedTest로 구현해도 좋겠다는 생각이 드네요.

추가로, 실패 케이스에 0이나 그 이하의 경우에 대해도 추가하면 어떨까요?

2023-02-20 07:48 UTC, yenawee commented on src/main/java/controller/LadderGameController.java
> +            outputView.printErrormessage(e.getMessage());
userName 과 height 입력 받는 부분을 각각 분리하여 에러 발생 시 재입력을 하게 했습니다. 우선 재귀로 구현했는데 stackoverflow 발생 위험이 있지만 사용자 입력이 stackoverflow가 일어날만큼 오류를 발생시키면서 입력하지 않을 거라 생각했고(지금 생각해보니 사용자는 예측할 수 없는데 수정 필요성이 보입니다....😓)  더 나은 방법을 생각해서 2단계 구현하면서 적용해볼 생각입니다 .

2023-02-20 08:15 UTC, yenawee commented on src/main/java/controller/LadderGameController.java
> +        while (height.isPossibleCount()) {
- Height 를 구현한 것은 원시값을 최대한 포장해줘야 한다는 요구사항을 맞추려고 int 인 height를 포장해준 클래스를 생성해줬습니다 ! 
이번 리팩토링을 하면서 height 에 final 을 붙여 불변객체로 만들고 minus 하는 부분을 아래 Position 의 decrease() 처럼 
```
class Position {
  private final int value;
  
  public Position increase() {
    return new Position(value + 1);
  }
  
  public Position decrease() {
    return new Position(value - 1);
  }
}
```

이런 식으로 수정하려 했는데 제 코드에서는 Height 생성자가 String 을 매개변수로 받아서 유효성 검증까지 하는 방식으로 구현해서 이런 식으로 수정이 어려웠습니다ㅠ 카프카 리뷰대로 저도 getter로 받는게 더 직관적일 거라 생각되지만 height 관련한 일은 다 Height가 처리하도록 하고 싶은 맘이 있어서 고민이 됩니다..

- Ladder 생성자로 players, height 를 받아 Ladder 객체 생성되게끔 수정했습니다 !
이번 과제를 하면서 공부했던 것 중에 하나가 일급 컬렉션이었는데 생성자가
```
public Ladder(List<Line> lines){
  this.lines = lines;
}

```
에서 밑에 처럼 매개변수를 받아서 생성되어도 일급 컬렉션이 될까요 ?? 제 생각으로는 Ladder 클래스에 lines 말고는 다른 멤버 변수가 없으니 일급 컬렉션인 거 같은데 공부하면서 찾아본 자료들은 위 코드처럼 setter 형식으로 생성자가 구현되어 있는 경우가 많아서.. 헷갈립니다 😥

```
public Ladder(Players players, Height height, TrueOrFalseGenerator trueOrFalseGenerator) {
        int count = height.getHeight();
        while (count-- > 0) {
            Line line = new Line(players.getPlayersCount(), trueOrFalseGenerator);
            lines.add(line);
        }
    }
```

2023-02-20 08:20 UTC, yenawee commented on src/main/java/domain/Line.java
> +            points.add(correctOverLapPoints(points.get(count - 1), trueOrFalseGenerator.generate()));
0 부터 순회 돌리면서 correctOverLapPoints 에서 points 의 길이가 0 일때만 따로 예외처리를 해주었습니다..!

2023-02-20 08:22 UTC, yenawee commented on src/main/java/domain/Way.java
> +    MAXNAMELENGTH1(1, "-", " "),
enum 을 사용하는 것이 요구사항인데 사용할 곳을 못찾아서 억지로 사용한 부분이었습니다 ㅠㅠ 
해당 enum 은 지우고 true, false 와 "-", " " 을 묶는 LadderStep 이라는 enum을 생성해서 boolean 값에 맞는 사다리 step 문자를 가져와서 String.repeat()를 사용해서 다리를 출력해주는 방식으로 수정했습니다

2023-02-20 08:27 UTC, yenawee commented on src/main/java/laddervalidate/HeightValidator.java
> +        if (!Pattern.matches("^[0-9]*$", height)) {
해당 정규식과 매칭되는지 확인하지 않아도 Integer.parseInt 에서 number 패턴이 아니면 예외를 처리해준다고 판단하여 해당 메소드는 삭제하였습니다. 
```
 try {
            int heightNumber = Integer.parseInt(height);
            if (heightNumber <= 0) {
                throw new IllegalArgumentException(NOT_POSITIVE_ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException(NOT_POSITIVE_ERROR_MESSAGE);
     }
```

이런 식으로 height 예외 처리를 하였는데 에러 메세지를 제가 원하는 대로 출력하고 싶어서 NumberFormatException 을 받았을 때 다시 IllegalArgumentException 을 던져줬는데 이런 식으로 에러를 redirection(?) 해도 괜찮을까요 ??

2023-02-20 08:30 UTC, yenawee commented on src/main/java/laddervalidate/PlayerNameValidator.java
> +    }
input 과 domain 에서 둘 다 예외처리를 하려고 validator 클래스들을 만들어주었는데 코드를 보면서 다시 생각해보니 Players, Height 는 각각 멤버 변수 하나만 가지고 있는 일급컬렉션으로 기능이 가능할 거 같아 객체를 생성할 때 생성자에서 validate 해주는 식으로 코드를 리팩토링 하였습니다.
이에 따라서 input 클래스와 players, height 각각에서 validator 객체를 생성할 필요가 없다는 점이 이점으로 보입니다.

2023-02-20 08:32 UTC, yenawee commented on src/main/java/view/InputView.java
> +        System.out.println(NAME_INPUT_REQUEST);
저는 출력에 관한 책임은 다 OutputView 가 가지고 있는 것을 선호해서 입력 요청 메세지도 Controller 에서 Outputview 를 호출하는 방식으로 리팩토링했습니다

2023-02-20 08:33 UTC, yenawee commented on src/main/java/view/OutputView.java
> +    private String changeFormat(Line line, int maxPlayerNameLength) {
이름 앞에 blank 길이를 나타내는 변수라서 preBlankLength 라는 변수명으로 선언하였습니다

2023-02-20 08:37 UTC, yenawee commented on src/test/java/LineTest.java
> +}
페어 인텔리제이에 eof 설정이 안되어있었어서 설정 변경추천해줬습니다  🤣

2023-02-20 08:52 UTC, yenawee commented on src/test/java/PlayerTest.java
> +    class playerCount {
오.. 인자를 List<String> 으로 받아서 parameterizedTest 를 활용할 수 있나(?) 생각했었는데 방법을 찾아서 적용해봤습니다 ..! 코드 중복도 줄고 훨씬 보기 깔끔해졌습니다 감사합니다!!

2023-02-20 09:16 UTC, yenawee commented
안녕하세요 카프카 ! 
꼼꼼한 리뷰 감사드립니다 🙇‍♀️

리뷰 주신대로 수정해봤는데 아직 미진한 점이 남아있네요..

아직 의존성이나 일급컬렉션, 불변 객체 같은 개념이 잘 안 잡혀서 아리송하지만..
이번에도 많은 조언 부탁드려요 !!

2023-02-20 14:06 UTC, include42 commented on src/main/java/controller/LadderGameController.java
> +            outputView.printErrormessage(e.getMessage());
사용자는 예측할 수 없다 라는 생각 넘 바람직합니다 💯 
물론 이 프로젝트에서는 재귀 구현 정도로 충분하지만, 고민해서 더 좋은 방법을 찾을 수 있다면 좋겠습니다. 💪

2023-02-20 14:16 UTC, include42 commented on src/main/java/controller/LadderGameController.java
> +        while (height.isPossibleCount()) {
이렇게 고민하는 모습 좋습니다. 우테코 미션은 클린 코드의 원칙을 극한으로 적용해 보는 것이므로, 이렇게 고민해보는것도 의미가 있다고 생각합니다.
다만 getter 사용을 고려해보라고 이야기한 이유는, 현재 수정된 increase/decrease 방식 역시 직관적이지 않기 때문입니다. 만약 팀에 새로운 팀원이 와서 코드 작업을 함께 한다면, 왜 반복을 위해 높이가 -1씩 되어야 하는지 설명할 수 있을까요? 그것이 가능할 정도까지 논리를 다듬어보거나, 혹은 새로운 방법을 찾아야 한다고 생각합니다.
예를 들어, height에 isOver(이름은 생각난대로 지은 겁니다) 라는 메소드가 있어서, for문의 반복자 i가 들어올때마다 그 값이 value를 넘는지 검사하면 어떨까요? 해당 메소드가 for문의 두번째 조건 인자라면 어떨지 고민해보세요.

그리고 일급 컬렉션에 대해서도, 왜 내가 일급 컬렉션을 쓰는지에 대해 고민해 봐야 합니다.
제가 일급 컬렉션을 쓰는 이유는, collection에 대한 조작을 막고 정해진 작업만을 수행할 수 있도록 감싸고자 입니다. (예를 들어, 멋대로 컨트롤러나 서비스에서 List<Line>에 add나 delete를 하는걸 막고 싶으므로!)
그렇기 때문에 저는 저 원칙이 지켜지는 하에서는 어느정도 유연하게 생각하는 편입니다. 생성자가 매개변수를 바탕으로 내용을 생성하더라도, 해당 클래스는 컬렉션을 포장하는 일급 컬렉션으로서의 역할을 한다고 생각합니다.
물론 제 생각이 정답은 아니므로, 이번 미션 과정에서 제나만의 일급 컬렉션 사용 이유를 찾아야 합니다. 만약 그 이유를 바탕으로 생각할 때 마지막 예시 코드와 같은 형태가 잘못되었다고 생각하면, 그때는 사용을 지양하면 됩니다. (물론 그리고 이 자신만의 철학은, 다른 사람의 의견을 경청하는 과정을 통해 유연하게 변할 수 있어야 합니다.)

마지막으로 한가지 코멘트. 예시 코드긴 하지만... `while(count-- > 0) ` 은 좋은 코드가 아닙니다. 증감 연산자는 보는 사람에게 연산 순서에 대한 혼동을 줄 수 있고, while문보다는 for문이 더 명확하게 시작/끝 조건을 보여줍니다.

2023-02-20 14:20 UTC, include42 commented on src/main/java/laddervalidate/HeightValidator.java
> +        if (!Pattern.matches("^[0-9]*$", height)) {
좋은 판단이네요. 꼼꼼한 확인이었습니다. 💯 
그리고 예외를 라우팅(?)하는 것은 문제가 없습니다.
다만 이야기해주신 대로, `에러 메시지를 원하는대로 출력`한 것이 옳은지만 고민하면 됩니다.

사람에 따라서는 정해진 메시지 + IllegalArgumentException을 전달하면 충분히 에러를 잘 전달한 것이라고 생각할수도 있고, 반대로 NumberFormatException만 전달해도 에러 상황을 명확히 전달하는 것이라고 생각할 수 있습니다.

저는 제나가 한 방식도 괜찮다고 생각합니다. 다만 이에 대해 페어와 2단계 진행하면서 논의를 해보길 바랍니다. 😄

2023-02-20 14:42 UTC, include42 approved these changes
안녕하세요 제나, 리뷰어 카프카입니다.

저번 리뷰때 변경 요청사항이 많았는데, 고민하면서 코드 개선을 잘해주셨습니다.
질문주신 내용도 좋아서 저도 함께 고민해 볼 수 있었습니다.

코드에 몇몇 수정해야 할 사항이 있으나, 전반적인 구조는 충분히 잘 구현해 주신것으로 생각됩니다. 이번 레벨은 approve 하겠습니다.

다음 레벨때 다시 뵙겠습니다! 고생 많으셨습니다 😄

2023-02-20 14:42 UTC, include42 commented on README.md
> +## 예외 처리
저번 리뷰때 언급을 못한 것 같은데, 이번 미션 진행하시면서 명세 문서를 잘 써주셨어요 💯 
기능 목록과 예외 처리가 따로 분리되어서 진행하면서도 좋았을 거라는 생각이 드네요.

2023-02-20 14:42 UTC, include42 commented on src/main/java/laddergame/domain/Height.java
> +            int heightNumber = Integer.parseInt(height);
유효성 검증을 각 객체에 위임해 주었네요.
이 부분은 장점도 있고, 단점도 있으리라 생각되어요. 일단 이번 미션에는 이 방향을 유지해 보고,
앞으로 미션 진행하면서 validator의 사용에 대해 페어들과 많은 논의를 해보기를 바랍니다.

그와는 별개로, 이번 미션에 depth 조건이 있었던 것 같은데,
본 메서드에서 depth가 좀 깊게 들어가네요. 이 부분은 level2때 개선해두면 좋겠습니다.

2023-02-20 14:42 UTC, include42 commented on src/main/java/laddergame/domain/Ladder.java
> +            while (count-- > 0) {
앞선 리뷰에서 코멘트를 따로 남기기도 했는데, 이러한 구문은 좋지 않습니다.
1. 증감 연산자는 연산 우선순위를 고려해야 하며 상황에 따라 직관적이지 않습니다.
2. while문 안에 조건을 넣어두면, 정확히 얼마나 순회하는지 읽는 사람이 추가로 계산해봐야 합니다.

저라면 더 직관적으로 for문을 쓰거나 할 것 같은데...이 부분은 level2 진행할 때에 수정 고려해보기를 바랍니다.

2023-02-20 14:42 UTC, include42 commented on src/test/java/laddergame/domain/LineTest.java
> +    class Creat {
이름 수정 부탁드립니다 😄

2023-02-20 14:42 UTC, include42 commented on src/test/java/laddergame/domain/LadderTest.java
> +                new LineTest.testTrueOrFalseGenerator(new ArrayList<>(Arrays.asList(true, false, true, false))));
이 부분에 수정이 필요합니다. 
LineTest 내에서만 사용하는 것이라면 상관없지만, 다른 테스트에서도 사용한다면 해당 테스트용 개체를 별도의 파일로 분리해주세요.

2023-02-20 14:42 UTC, include42 commented on src/test/java/laddergame/domain/LadderTest.java
> +                new LineTest.testTrueOrFalseGenerator(new ArrayList<>(Arrays.asList(true, false, true, false))));
그리고 제가 로컬에서 돌려봤을때엔 LadderTest에서 테스트가 실패하네요.
실패 로그는 LineTest에서 나는데 실패한 테스트는 LadderTest여서 당황했기 때문에, 별도로 수정을 요청드렸습니다.

테스트 코드가 다른 테스트 코드를 참조하면 안되는 이유가 무엇일지, 고민해보면 좋을 것으로 생각됩니다 👍

2023-02-20 14:42 UTC, include42 commented on src/test/java/laddergame/domain/PlayersTest.java
> +    private static Stream<Arguments> provideFailPlayerNames() {
methodSource로 구현 잘해주셨네요 💯

2023-02-20 14:44 UTC, include42 commented
아, 그리고 리뷰 마치고 보니 그사이 커밋이 있었네요!
원래는 리뷰 시작 전에 예정 시간 코멘트를 미리 드리는데, 
오늘은 퇴근 후 가능할 것으로 무난히 생각해서 따로 코멘트를 드리지 못했습니다.

다음 리뷰때에는 제가 요청 확인하는대로, 언제쯤 가능할지 간단하게 코멘트 남겨드릴게요 😄

2023-02-20 14:46 UTC, merged

2023-02-23 15:28 UTC, yenawee commented on README.md
> +## 예외 처리
감사합니다 !

2023-02-23 15:28 UTC, yenawee commented on src/main/java/laddergame/domain/Height.java
> +            int heightNumber = Integer.parseInt(height);
indent 1 이하로 모두 수정했습니다 !!

2023-02-23 15:29 UTC, yenawee commented on src/main/java/laddergame/domain/Ladder.java
> +            while (count-- > 0) {
for 문으로 수정했습니다 !! 별개로 반복문을 없애려다보니 재귀가 더 생겨버리네요... 다른 크루들은 재귀 없이도 잘 구현하시던데 얼른 배워야겠습니다..😵

2023-02-23 15:30 UTC, yenawee commented on src/test/java/laddergame/domain/LadderTest.java
> +                new LineTest.testTrueOrFalseGenerator(new ArrayList<>(Arrays.asList(true, false, true, false))));
TestTrueFalseGenerator 별도 클래스 분리했습니다