[1단계 - 사다리 생성] 디노(신종화) 미션 제출합니다.
woowacourse/java-ladder pull request #108
Opened 2023-02-16 07:37 UTC by jjongwa

2023-02-17 08:40 UTC, ksy90101 commented on src/main/java/domain/Height.java
> +    }
Input이라고 적혀 있다 보니, 입력값을 검증하는 느낌이라, 객체에선 실제 객체 상태를 검증해야 한다고 생각합니다. 따라서 상태 검증을 하는것 처럼 나타내보면 어떨까요?

2023-02-17 08:41 UTC, ksy90101 commented on src/main/java/domain/Line.java
> +        RandomNumberGenerator randomNumberGenerator = new RandomNumberGenerator();
랜덤값을 여기서 생성하면, 이 메서드는 테스트 하기가 어려워질거에요.

자동차 경주게임에서 배웠듯이, 상위로 뺴서 제어해보면 어떨까요?

2023-02-17 08:42 UTC, ksy90101 commented on src/main/java/domain/PointStatus.java
> +    }
view로 변환하는 코드가 여기 잇는게 맞을까요?
view로 변환하는 Contverter와 같은 친구를 만들어서 처리해도 좋을거 같아요.

2023-02-17 08:43 UTC, ksy90101 commented on src/main/java/domain/PointStatus.java
> +                .orElse(BLANK)
foint가 다른 경우에는 에러를 발생시켜야 하지 않을까요?
예상하지 못한 값이 들어온것이니깐요.

2023-02-17 08:44 UTC, ksy90101 commented on src/main/java/domain/Users.java
> +        }
Stream을 이용해서 처리할수 있지 않을까요? 대표적으로 map이 잇죠!

2023-02-17 08:44 UTC, ksy90101 commented on src/main/java/utils/FixedNumberGenerator.java
> +public class FixedNumberGenerator implements NumberGenerator {
👍

2023-02-17 08:45 UTC, ksy90101 commented on src/main/java/utils/RandomNumberGenerator.java
> +        Random random = new Random();
굳이 Rondom() 인스턴스를 호출할 떄 마다 생성할 필요가 있을까요?
상수로 정의해두고 재사용해보면 어떨까요?

2023-02-17 08:45 UTC, ksy90101 commented on src/main/java/validate/InputVerifier.java
> +        if (!heightInput.matches("^[0-9]*$")) {
정규표현식을 상수로 만들어 두면 좋겠네요~

2023-02-17 08:51 UTC, ksy90101 commented on src/main/java/domain/PointStatus.java
> +    public static String printStatus(boolean point, int width) {
여기에 대한 테스트 코드가 없는거 같네요 :)

2023-02-17 08:52 UTC, ksy90101 commented on src/main/java/validate/InputVerifier.java
> +    public int validateHeightInput(String heightInput) {
이건 안쓰이는거 같네요?

2023-02-17 08:53 UTC, ksy90101 commented on src/main/java/controller/LadderGameController.java
> +        while (ladderHeight-- > 0) {
전위연산자나 후위연산자를 사용하면 더 코드가 잘 안 읽혀지는거 같아요. (개인적인 의견.)
따라서 정확히 연산자를 사용하는것을 더 권장하긴 합니다 :)

2023-02-17 08:55 UTC, ksy90101 requested changes
디노 안녕하세요 리뷰어 럿고 입니다 :)
사다리 1단계 하시느라 고생 많으셨습니다 💯 
간단한 피드백을 남겼으니, 확인부탁드려요~

질문은 언제든 환영입니다!!

2023-02-17 12:54 UTC, jjongwa commented on src/main/java/validate/InputVerifier.java
> +    public int validateHeightInput(String heightInput) {
리팩터링때 InputVerifier에 있는 기능들을 다른 클래스로 옮기고 난 후 삭제한다는 걸 놓쳤습니다.. 삭제 완료했습니다!

2023-02-17 12:58 UTC, jjongwa commented on src/main/java/controller/LadderGameController.java
> +        while (ladderHeight-- > 0) {
지난 미션 리뷰에서 for문을 사용했을 때 굳이 변수 하나를 더 만드는 것 보다 while을 활용한 현재와 같은 방식을 추천 받았는데, 럿고의 의견대로 코드의 가독성 측면에서는 아쉬울 수도 있다는 생각이 들었습니다. 이 부분은 페어와 다시 한 번 얘기해 보겠습니다.!

2023-02-17 12:59 UTC, jjongwa commented on src/main/java/validate/InputVerifier.java
> +        if (!heightInput.matches("^[0-9]*$")) {
이부분도 InputVerifier 삭제하면서 처리했습니다!

2023-02-17 13:24 UTC, jjongwa commented on src/main/java/domain/PointStatus.java
> +                .orElse(BLANK)
Enum에서 stream을 사용해 조건에 해당하는 문자열을 받아오는 로직에 대한 이해가 아직 부족한 것 같아요. 

저희가 의도했던 방식은 단순하게 (boolean)point 값이 true이면 가로줄이 필요한 부분이라 "-----" 문자열을 반환하고 false이면 "     " 과 같은 공백 문자열을 반환한다는 느낌이었는데, 혹시 해당 로직을 조금 더 간단하게 처리할 수 있는 방법에 대해 힌트를 받을 수 있을까요..?

2023-02-17 13:30 UTC, jjongwa commented on src/main/java/domain/PointStatus.java
> +    }
이 부분에 대해서도 페어와 이야기를 진행해 봤습니다!
저는 지난 미션에서 입력 값에 대한 형식 변환 또는 상태 변환 함수들을 Converter 클래스를 만들어 모아 놓는 방식을 사용하였고 망고는 그러지 않았는데, 얘기를 하며 현재 크기의 미션에서 굳이 몇 개 없는 변환 로직을 클래스까지 따로 만들어서 관리하는 것이 효율적일까 하는 생각에 분리하지 않는 쪽을 선택했습니다.! 

럿고 의견 공유해 망고와 다시 얘기해 보겠습니다!

2023-02-18 01:46 UTC, jjongwa commented on src/main/java/domain/Users.java
> +        }
와우 그렇겠네요.. 변경했습니다..!

2023-02-18 01:54 UTC, jjongwa commented on src/main/java/domain/PointStatus.java
> +    public static String printStatus(boolean point, int width) {
함수 이름을 print로 작성해 출력문 -> 굳이 테스트 필요할 필요 없다 
의 의식의 흐름으로 진행된 것 같습니다..!

주어진 조건에 따라 의도했던 문자열이 반환되는지 확인하는 테스트를 추가했습니다!

2023-02-18 03:00 UTC, jjongwa commented on src/main/java/domain/Height.java
> +    }
럿고의 의견을 제가 제대로 이해한 건지 모르겠습니다.

우선 validateHeightFormat은 Input에서 String 형태의 입력값을 받아 숫자인지 확인하는 입력값에 대한 검증 함수이고,  통과하면 convertHeightInput을 통해 Int형으로 변환하는 순서입니다.

Height라는 도메인 내에서는 해당 객체에 대한 검증이 이루어져야 하는데 입력값 자체에 대한 함수가 존재하는 상황이어서 어색하다는 뜻으로 이해하면 될까요..?

2023-02-19 06:55 UTC, ksy90101 commented on src/main/java/domain/Height.java
> +    }
일단 이름이 Input인게 어색한거 같아요.
객체에 상태가 들어올때는 이미 객체의 상태에 맞게 들어와야 하는데요.
예를들어 숫자를 Converter하는것은 이미 객체가 생성되었을때 이미 숫자여야 한다는 의미였어요.

2023-02-19 06:55 UTC, ksy90101 commented on src/main/java/domain/PointStatus.java
> +                .orElse(BLANK)
제가 말하는건 지금 예를들어 Boolean이니 상관없지만, String인 경우에 다른 값이 들어올수도 있어서 그렇습니다.
그러나 다른 값이 들어왔을때 빈값을 보여준느것이 정책이라면 빈값도 맞는거 같아요.
이건 정책에 대한 문제인듯 하네요.

2023-02-19 06:57 UTC, ksy90101 commented on src/main/java/domain/PointStatus.java
> +    public static String printStatus(boolean point, int width) {
View와 관련된 테스트여도 값을 리턴하는것이기 때문에 테스트 코드를 작성하는것이 좋습니다.
백엔드라고 해서 View와 관련된 코드가 없는게 아니거든요.

예를들면 저희 회사 같은 경우에 탈퇴계정이나 휴면계정인 경우에 이름을 `-` 이걸로 내보내준다. 라는 정책이 있고 프론트에서 처리하면 해당 이름이 노출되기 때문에 백엔드에서 내려줍니다. 이런 경우처럼 View와 관련된 코드는 들어갈수 있고 그거에 대한 테스트 코드에 대한 대응은 중요할거 같아요!

2023-02-19 06:59 UTC, ksy90101 commented on src/main/java/controller/LadderGameController.java
> +        while (ladderHeight-- > 0) {
사람마다 보는 관점이 다르기 때문에, 참고만 부탁드려요.

2023-02-19 07:00 UTC, ksy90101 commented on src/main/java/domain/Line.java
> +    private boolean isContinuousTrue(List<Boolean> points, int index, RandomNumberGenerator randomNumberGenerator) {
뒤에 True는 어떤 의미를 나타내나요?
Boolean인 경우에 is가 붙어있기 때문에 True, False와 같은 단어를 사용할 필요가 없어보이는데요 ㅠㅠ

2023-02-19 07:00 UTC, ksy90101 approved these changes
디노 안녕하세요 :)
피드백 적용하시느라 고생하셨습니다 💯 
2단계도 아직 남았으니, 1단계는 여기서 이만 머지할게요~
2단계도 파이팅하세요~

2023-02-19 07:02 UTC, merged

2023-02-20 06:49 UTC, jjongwa commented on src/main/java/domain/Line.java
> +    private boolean isContinuousTrue(List<Boolean> points, int index, RandomNumberGenerator randomNumberGenerator) {
Boolean값 True가 연속으로 나오는지 여부를 판단하는 함수여서 저렇게 작명했는데 오해의 여지가 있어 보입니다.. 다른 함수명을 한번 생각해 보겠습니다!

2023-02-20 06:51 UTC, jjongwa commented on src/main/java/domain/Height.java
> +    }
럿고의 의견을 들어보니 굳이 String으로 높이를 입력받고 검증을 하기보다 nextInt함수를 통해 바로 Int값을 입력 받아와야겠다는 생각이 들었습니다. ! 다음 스텝에서 변경해 보겠습니다!