[1단계 - 사다리 생성] 엔초(권예진) 미션 제출합니다.
woowacourse/java-ladder pull request #115
Opened 2023-02-16 07:53 UTC by kwonyj1022

안녕하세요 또링! 리뷰 잘 부탁드립니다.

코드 보시기 전에 혹시 헷갈릴 수 있어서 미리 말씀드립니다.
사다리 이음새 부분을 뭐라고 명칭을 정할지 모르겠어서 고민하다가, 기능 요구사항에 예시로 있던 Line 객체 코드에 point라는 단어가 사용되었길래 저희도 point라는 단어를 사용했습니다..!

|-----|        |
|        |-----|

이렇게 생긴 사다리가 있다고 했을 때 '-----' 와 '          ' 부분을 point라고 한 것입니다.

프로그래밍을 진행하면서 궁금한 점이 있습니다.

1. validate의 적절한 위치가 고민이 됩니다.
현재 사다리 높이에 대한 검증을 InputView와 LadderMaker 두 곳에서 진행하고 있습니다.
일단, 결국 입력을 받았을 때 걸러져야 할 예외이므로 InputView에서 validate를 했습니다. 미래의 나 또는 다른 사람이 validate를 수정하게 되었을 때도 InputView에 가장 있을법하니 InputView 먼저 살펴보게될 것이기 때문에 이 위치가 맞다고 생각합니다.

사다리의 높이 검증을 InputView에서 했는데도 LadderMaker에서도 한 이유는 
InputView에서 받은 값이 아닌, 원래 의도와 다른 곳에서 임의의 값으로 객체를 생성했는데 그 값이 height의 조건에 맞지 않는 값이라고 했을 때, 객체 안에 validate가 없다면 해당 객체는 사용이 불가능한 객체가 될 것입니다. 그래서 객체 안에도 넣었습니다.

그런데 이렇게 두 군데에 넣는다면 나중에 수정하게 될 때 먼저 보이는 쪽만 수정해버리면 같은 값에 대한 검증 메서드가 서로 다르게 될 수 있기 때문에 위험할 것 같습니다.

'InputView'와 '입력받은 값을 사용하는 객체' 중 어디에 validate를 구현하는 것이 옳은지 궁금합니다. 

2. 상수를 private로 선언할지, public으로 선언할지 고민이 됩니다.
현재 저희는 상수를 private로 선언해서 객체마다 상수를 갖게 됩니다.
그렇기 때문에 예를 들어 사다리 높이의 최소값을 나타내는 MIN_HEIGHT의 경우 InputView에서도 사용하고 LadderMaker에서도 사용합니다.

처음에는 public으로 하고 MIN_HEIGHT의 경우 LadderMaker에 좀 더 적합한 상수이므로 LadderMaker에 구현해놓고, InputView에서는 LadderMaker.MIN_HEIGHT 이런식으로 가져오려고 했는데, 이렇게 하면 InputView가 LadderMaker에 의존하게 되는 것이 아닐까 하는 생각에 분리하게 되었습니다. 그런데, 분리하게되면 MIN_HEIGHT를 수정하려면 두 군데 다 수정해야하 하는 문제점이 있습니다.

상수를 public으로 사용하는 것과 private로 사용하는 것 중 어느것이 더 좋은 방법인가요?

3. 
PointJudge 객체의 canMake() 메서드의 경우 static 메서드입니다. 다리를 만들지 말지 판단을 하기 위한 메서드인데, 처음에는 Line 객체에 구현했다가 Line 객체의 책임이 너무 많은 것 같아 분리하였습니다. 따라서 굳이 PointJudge 객체를 생성하지 않고 메서드를 사용하기 위해 static을 사용하였습니다. static 메서드를 이런 상황에서 사용하는 것이 적절한지 궁금합니다.

리뷰 감사드립니다!

2023-02-18 05:33 UTC, jnsorn requested changes
안녕하세요, 엔초! 리뷰가 많이 늦어졌네요. 🥲
사다리게임 잘 구현해주셨어요! 특히, 커밋을 보니 TDD로 잘 구현해주신 것 같아요. ㅎㅎ
수정해보면 좋을 부분에 코멘트 남겨두었으니, 확인해보시고 다시 리뷰 요청주세요!
궁금한 건 언제든 편히 DM 주시구요! 행복한 주말 보내세요. 😃

2023-02-18 05:33 UTC, jnsorn commented on README.md
> +### 기능 목록
> 사다리 이음새 부분을 뭐라고 명칭을 정할지 모르겠어서 고민하다가, 기능 요구사항에 예시로 있던 Line 객체 코드에 point라는 단어가 사용되었길래 저희도 point라는 단어를 사용했습니다..!

자세한 설명 고마워요 👍 덕분에 의미 파악하는 시간을 줄일 수 있었어요! 
용어가 애매해서 설명이 필요하다 느껴진다면 PR외에도 Readme나 해당 클래스 주석으로 남길 수 있을 것 같아요. 이 PR에 들어오지 않는 이상, 엔초의 프로젝트를 구경온 사람들은 의미 파악이 힘들 수 있으니요 ㅎㅎ 사실 부연설명 없이 읽히는 코드가 짱이긴 하지만 그건 어려우니.. 😃

사다리게임이니 사다리라는 물체로 생각했을때, 이음새는 `발판`이라고도 표현할 수 있을 것 같아요. 혹은 선과 선 사이를 이어주는 `브릿지`와 같은 용어도 생각나네요. 이 중에 마음에 드시는 게 있다면 변경하시고, 여전히 Point가 더 낫다고 생각하시면 그대로 두셔도 좋습니다!

2023-02-18 05:33 UTC, jnsorn commented on src/main/java/controller/LadderController.java
> +    }
가독성있게 개행을 잘 해주셨네요. 👍

2023-02-18 05:33 UTC, jnsorn commented on src/main/java/controller/LadderController.java
> +    }
Players의 생성을 Players가 하도록 하면 어떨까요?

2023-02-18 05:33 UTC, jnsorn commented on src/main/java/domain/generator/BooleanGenerator.java
> +}
`@FunctionalInterface`에 대해 알아볼까요?
https://tecoble.techcourse.co.kr/post/2020-07-17-Functional-Interface/

2023-02-18 05:33 UTC, jnsorn commented on src/main/java/domain/ladder/Ladder.java
> +    }
`unmodifiableList`을 사용하신 이유가 궁금해요! 😄

2023-02-18 05:33 UTC, jnsorn commented on src/main/java/domain/generator/RandomBooleanGenerator.java
> +public class RandomBooleanGenerator implements BooleanGenerator {
이름이 추상적이에요. 해당 클래스가 어떤 일을 하는지는 알 수 있지만, 사다리게임이라는 도메인 내에서 어떤 역할을 수행하는지 추측하기 어려워요. 도메인 용어를 사용해서 해당 객체의 역할이 잘 드러나도록 이름을 수정해볼까요?

2023-02-18 05:33 UTC, jnsorn commented on src/main/java/utils/ErrorMessage.java
> +    POINT_NOT_FOUND_ERROR("일치하는 포인트 객체가 존재하지 않습니다.");
에러메세지를 한 곳에서 관리하면 어떤 장단점이 있을까요?

2023-02-18 05:33 UTC, jnsorn commented on src/main/java/utils/Log.java
> +}
Log를 직접 구현하셨군요 😃👏🏻
Log를 따로 사용하신 이유가 궁금해요 ㅎㅎ

2023-02-18 05:33 UTC, jnsorn commented on src/main/java/domain/ladder/PointJudge.java
> +    }
```suggestion
    public static boolean canMake(List<Boolean> points, boolean flag, int index) {
        if (flag) {
            return isFirstIndexOrLeftEmpty(points, index);
        }
        return false;
    }
```

2023-02-18 05:33 UTC, jnsorn commented on src/main/java/domain/ladder/LadderMaker.java
> +    }
> 모든 원시 값과 문자열을 포장한다

`height`를 포장해볼까요?

2023-02-18 05:33 UTC, jnsorn commented on src/main/java/domain/ladder/Line.java
> +    }
> 모든 원시 값과 문자열을 포장한다

`pointSize`를 포장해볼까요?

2023-02-18 05:33 UTC, jnsorn commented on src/main/java/domain/ladder/Point.java
> +    FALSE(false, "     ");
사다리 게임의 출력 형태가 변경된다면 domain 클래스에도 영향을 끼칠 것 같아요. 
도메인으로부터 View와 관련된 로직을 분리해볼까요?

2023-02-18 05:33 UTC, jnsorn commented on src/main/java/domain/ladder/Ladder.java
> +package domain.ladder;
도메인 패키지도 잘 분리해주셨네요 👍

2023-02-18 05:33 UTC, jnsorn commented on src/main/java/domain/ladder/PointJudge.java
> +    }
첫 번째 라인인지 검사하는 로직과 옆의 라인과 Point가 겹치는지 검사하는 로직이 한 곳에 존재해요.
분리하면 가독성이 더 높아질 것 같아요~!

2023-02-18 05:33 UTC, jnsorn commented on src/test/java/domain/ladder/LadderMakerTest.java
> +    }
경계값만 테스트해도 충분해보여요. 
같은 의미의 테스트들이 중복되면 복잡도를 증가시킵니다.

2023-02-18 05:33 UTC, jnsorn commented on src/test/java/domain/ladder/LadderMakerTest.java
> +    }
예외메세지까지 비교해서 정확한 테스트를 하셨군요 👏🏻

2023-02-18 05:33 UTC, jnsorn commented on src/test/java/domain/ladder/LineTest.java
> +    class MockBooleanGenerator implements BooleanGenerator {
클래스 파일을 분리해도 좋을 것 같은데, 내부에 구현하신 이유가 있을까요?~

2023-02-18 05:33 UTC, jnsorn commented on src/test/java/domain/ladder/PointJudgeTest.java
> +    }
DisplayName은 테스트코드를 그대로 해석하는 느낌이에요. 
어떤 상황을 테스트하는 건지 도메인 용어를 사용하여 작성해보면 어떨까요?
ex. 옆 라인에 같은 높이의 브릿지가 존재하면 브릿지를 생성할 수 없다.

2023-02-18 05:33 UTC, jnsorn commented on src/main/java/domain/ladder/LadderMaker.java
> +    }
PR 본문에 작성해주신 1,2번 질문은 이 코멘트를 반영하고 다시 이야기 나눠보시죠!

2023-02-18 05:33 UTC, jnsorn commented on src/main/java/domain/ladder/LadderMaker.java
> +    }
추가로, 원시값을 포장하면서 느낀 장단점도 같이 공유주실 수 있을까요? 😃

2023-02-18 05:33 UTC, jnsorn commented on src/main/java/domain/ladder/PointJudge.java
> +    public static boolean canMake(List<Boolean> points, boolean flag, int index) {
> PointJudge 객체의 canMake() 메서드의 경우 static 메서드입니다. 다리를 만들지 말지 판단을 하기 위한 메서드인데, 처음에는 Line 객체에 구현했다가 Line 객체의 책임이 너무 많은 것 같아 분리하였습니다. 따라서 굳이 PointJudge 객체를 생성하지 않고 메서드를 사용하기 위해 static을 사용하였습니다. static 메서드를 이런 상황에서 사용하는 것이 적절한지 궁금합니다.

- 엔초가 생각하는 Line의 책임은 무엇인지 궁금해요. 😎
- 추가로, static 메서드에 대해서는 [이 글](https://tecoble.techcourse.co.kr/post/2020-07-16-static-method/)을 읽어보면 좋을 것 같아요.

2023-02-19 17:17 UTC, kwonyj1022 commented on src/main/java/domain/ladder/Ladder.java
> +    }
List의 경우 주소값을 공유하기 때문에 만약 getLines()를 통해 받은 리스트를 수정하게 되면 원본 리스트도 수정됩니다. 이 정도 규모의 작은 프로그램에서는 큰 필요가 없겠지만, 혹시 모를 값의 변경을 방지하기 위해 사용하였습니다!

2023-02-19 17:21 UTC, kwonyj1022 commented on src/main/java/utils/ErrorMessage.java
> +    POINT_NOT_FOUND_ERROR("일치하는 포인트 객체가 존재하지 않습니다.");
장점은,
에러 메세지를 수정하게 될 때 찾기 쉽습니다.
같은 에러 메세지를 여러 클래스에서 사용할 경우, 각 클래스마다 에러메세지를 넣어준다면 수정이 필요할 때 실수가 발생할 수 있습니다.

단점은,
에러메세지를 사용하는 클래스에 직접 타이핑 되어있을 때보다 가독성이 떨어지게 됩니다.

2023-02-19 17:23 UTC, kwonyj1022 commented on src/main/java/utils/Log.java
> +}
엄청난 이유가 있는 것은 아니고, 에러 메시지 출력 형식을 지정하기 위해서 사용하였습니다!
컨트롤러에서 에러메시지 출력을 하게 되는데, 그 출력 형식을 만드는 것은 컨트롤러의 역할이 아니라고 생각했기 때문에 분리하였습니다.

2023-02-19 17:25 UTC, kwonyj1022 commented on src/main/java/domain/ladder/LadderMaker.java
> +    }
Height 클래스를 만들고 Height 객체 생성 시 validate를 하도록 하였더니, 기존처럼 InputView와 LadderMaker 두 곳에서 Validate할 필요가 없어졌습니다!

2023-02-19 17:29 UTC, kwonyj1022 commented on src/test/java/domain/ladder/LineTest.java
> +    class MockBooleanGenerator implements BooleanGenerator {
Mock클래스의 경우 LineTest를 위해 구현한 것이고 LineTest에서만 사용되기 때문에 굳이 분리할 필요가 없겠다고 생각했습니다.
Mock클래스는 도메인과 상관 없는 클래스라 파일로 노출시키지 않고 싶었고, test 폴더에는 테스트 클래스만 존재하는 것이 보기 좋다고 생각했습니다.

2023-02-19 17:38 UTC, kwonyj1022 commented on src/main/java/domain/ladder/Line.java
> +    }
point 라는 용어를 bridge로 변경한 관계로, pointSize 는 bridgeSize로, creatPoints() 메서드는 createBridges() 메서드로 지칭하겠습니다.
브릿지를 만들 때 인자로 받는 personCount의 경우 players의 사이즈를 입력받기 때문에, players에서 player 수를 검증한 이상, 굳이 브릿지개수를 또 검증할 필요가 없다고 생각해서 bridgeSize를 검증하는 로직을 삭제하였습니다.
궁금한 점은, bridgeSize의 경우 personCount에 의존하는 숫자일 뿐인데도 포장할 필요가 있는지 궁금합니다.
createBridges() 메서드에서 bridgeSize를 정의하는 부분은 for문의 가독성을 높이기 위해 분리한 것이고 for문을 아래와 같이 작성한다면 필요가 없는 변수입니다.
`for (int index = 0; index < personCount - 1; index++)`

bridgeSize를 검증하는 메서드가 없는 상태에서 굳이 bridgeSize를 포장할 필요가 있는 것인지 궁금합니다.

2023-02-19 17:50 UTC, kwonyj1022 commented on src/main/java/domain/ladder/PointJudge.java
> +    public static boolean canMake(List<Boolean> points, boolean flag, int index) {
처음에 제가 생각하는 Line의 책임은, 랜덤으로 다리를 만들지 말지 결정해서 한 층의 사다리를 완성하되, 가로로 라인이 겹치지 않는 것입니다. 이대로라면 랜덤값도 뽑고, 그 값을 기준으로 bridge를 만들 수 있을지 없을지 판단(가로 라인이 겹치는지 판단)도 해야 하는데, 그러면 너무 책임이 많아지니, 랜덤값을 뽑는 역할과, bridge를 만들 수 있는지 없는지 판단하는 역할을 분리하기로 한 것입니다.
그 결과, 현재 Line의 책임은 랜덤값을 뽑고, 뽑은 랜덤값과 지금까지 만든 line을 BridgeJudge로 보내서 BridgeJudge의 응답에 맞는 값을 line에 추가하는 것입니다.

2023-02-21 05:30 UTC, jnsorn commented
추가로, 미션 요구사항에 아래와 같은 요구사항이 있는데요, 

> Java Enum을 적용한다.

예외메세지를 제외하고 어디에 enum을 적용해보면 좋을지 고민해볼까요~? 😎

2023-02-21 05:31 UTC, jnsorn approved these changes
안녕하세요 엔초! 피드백 반영 잘 해주셨어요. 
TDD로 잘 구현해주신 것 같네요. 😎
코멘트 남겨두었는데, 다음단계 진행하면서 같이 반영해주세요!
2단계에서 만나요~! 🪜🪜🪜

2023-02-21 05:31 UTC, jnsorn commented on src/main/java/domain/ladder/LadderMaker.java
> +    private final BooleanGenerator randomBridgeGenerator = () -> new Random().nextBoolean();
`@FunctionalInterface` 를 붙이라는 의미가, 사용하는 곳마다 정의해서 사용하자는 건 아니었어요! 

혹시 엔초는 왜 `@FunctionalInterface`로 선언하셨는지 말씀해주실 수 있나요? 
(물론 제가 리뷰로 드리긴했지만, 왜 피드백을 적용하셨는지 궁금해요!)

2023-02-21 05:31 UTC, jnsorn commented on src/test/java/domain/ladder/BridgeJudgeTest.java
> +    @DisplayName("랜덤값이 true가 나와 다리를 생성하려고 할 때, 가장 왼쪽의 다리이면 다리를 생성할 수 있다.")
테스트만 읽어봐도 요구사항을 알 수 있겠네요! 👍

2023-02-21 05:31 UTC, jnsorn commented on src/main/java/domain/ladder/Height.java
> +public class Height {
의미있는 값을 객체로 포장해주셨네요 👍

2023-02-21 05:31 UTC, jnsorn commented on src/main/java/utils/ErrorMessage.java
> +    POINT_NOT_FOUND_ERROR("일치하는 포인트 객체가 존재하지 않습니다.");
엔초 생각을 자세히 말해주어서 고마워요. 👍 저도 제 의견을 말해보자면, 에러메세지는 관련있는 클래스에서 관리하자라는 생각이에요. (물론 제 생각일뿐 정답이 아닌건 아시죠?)

> 에러 메세지를 수정하게 될 때 찾기 쉽습니다.

에러 메세지가 100개, 1000개로 늘어나도 찾기 쉬울까요? 이름에 대한 메세지는 이름 도메인에서 찾는게 더 쉽지 않을까요?

> 같은 에러 메세지를 여러 클래스에서 사용할 경우, 각 클래스마다 에러메세지를 넣어준다면 수정이 필요할 때 실수가 발생할 수 있습니다.

같은 예외 메시지가 다른 곳에서 중복된다면 동일한 로직이 여기저기 흩어져 있다는 신호일 수 있어요.

그 외에도 아래와 같은 장점때문에 저는 에러메세지를 관련있는 클래스에서 관리하고 있습니다.

- 예외 메세지를 예외 로직과 함께 두면 가독성이 올라간다.
- 특정 예외상황에 대한 로직들을 한 곳에서 관리할 수 있다.
- 도메인 규칙이 변경된 경우, 해당 도메인 규칙을 관리하는 곳에서만 코드가 변경되면 된다. (ex. 이름 조건이 변경되었다면 Name클래스만 변경)

2023-02-21 05:31 UTC, jnsorn commented on src/main/java/domain/ladder/Line.java
> +    }
의견 말해줘서 고마워요 엔초~! 

기존에 bridgeSize를 검증하는 로직이 있어, 값을 포장해서 사용하면 관련 로직끼리 응집도를 높일 수 있다는 생각으로 리뷰 드렸어요!😃
지금 상태에서는 변수로 빼서 의미만 부여해도 충분할 것 같네요! ㅎㅎ

2023-02-21 05:31 UTC, jnsorn commented on src/main/java/domain/ladder/BridgeJudge.java
> +            return isFirstLine(index) || isLeftEmpty(bridges, index);
가독성이 좋아졌네요~!

2023-02-21 05:32 UTC, jnsorn commented
추가로, 미션 요구사항에 아래와 같은 요구사항이 있는데요,

Java Enum을 적용한다.

예외메세지를 제외하고 어디에 enum을 적용해보면 좋을지 고민해볼까요~? 😎

2023-02-21 05:32 UTC, merged

2023-02-24 07:15 UTC, kwonyj1022 commented on src/main/java/domain/ladder/LadderMaker.java
> +    private final BooleanGenerator randomBridgeGenerator = () -> new Random().nextBoolean();
리뷰를 받고 `@FunctionalInterface`에 대해 공부해봤는데, `@FunctionalInterface`를 선언하면 해당 인터페이스가 추상메서드를 한 개만 가질 수 있다는 것을 알게 되었습니다. 그래서 이 인터페이스가 한 개의 추상메서드를 가지고 있다는 정보를 주기 위해 붙였습니다. 그리고, 사용하는 곳에서 정의한 이유는, 처음에 `BooleanGenerator`를 구현하는 `RandomBooleanGenerator` 클래스가 에서 오버라이드한 `geterate()` 메서드가 한 줄 짜리 간단한 일을 하는데, 굳이 클래스를 새로 만들어야 할까 하는 생각이 들어 없앴고, 해당 구현체가 필요한 공간에서 직접 정의하는 방법으로 바꾼 것입니다!