[1단계 - 사다리 생성] 여우(조승현) 미션 제출합니다.
woowacourse/java-ladder pull request #139
Opened 2023-02-16 08:37 UTC by BackFoxx

좋은 파트너를 만나 정말 즐겁게 토론하며 프로젝트를 완성할 수 있었습니다 감사합니다 🙌🏻

파트너와 함께 논의하면서 생긴 궁금증이 몇 가지 있어 질문을 남겨요 !

* 원시값을 포장하여 사용하라는 요구사항을 지키기 위해 거의 모든 도메인 관련 값을 포장했지만,

2023-02-16 09:23 UTC, boorownie requested changes
안녕하세요 여우~ 땜빵 리뷰를 맡은 브라운입니다.
사다리 미션 1단계 구현 잘 해주셨고요~
더 생각해보기 좋은 질문으로 코멘트 남겨놓았으니 고민해보시고
반영할 것 있으면 반영하시고 질문 있으면 질문 주세요~

2023-02-16 09:23 UTC, boorownie commented on src/main/java/Application.java
> +        LadderGameController game = new LadderGameController();
LadderGameController를 직접 생성해서 객체를 만들어 주셨네요!
객체 생성 없이 static을 이용해서 run을 수행할 수 도 있었을텐데 객체를 생성하게 한 이유가 있을까요?

2023-02-16 09:23 UTC, boorownie commented on src/main/java/controller/LadderGameController.java
> +    }
간결한 run 메서드 👍 
가독성이 좋아서 프로그램의 흐름을 이해하기 쉽네요!

2023-02-16 09:23 UTC, boorownie commented on src/main/java/controller/LadderGameController.java
> +
다른 메서드의 줄바꿈 컨벤션과 다른 것 같아요! 컨벤션을 확인해주세요

2023-02-16 09:23 UTC, boorownie commented on src/main/java/controller/LadderGameController.java
> +        OutputView.printResult(new GameDto(names, ladder));
GameDto의 역할은 무엇인가요?
GameDto 객체를 보니 출력에 도움을 주는 메서드들이 있는 것 같은데
그렇다면 출력 로직을 캡슐화 하기 위한 객체일까요?

만약 Controller <--> View 사이의 데이터를 주고 받는 역할이라면
names와 ladder만 넘겨주고 View에서 GameDto를 만들어서 활용하는 방법은 어떨까요?
이렇게 할 경우 Controller는 DTO에 의존하지 않게 설계할 수 있을 것 같아서요~

GameDto의 역할에 대해서 고민해보세요~

2023-02-16 09:23 UTC, boorownie commented on src/main/java/controller/LadderGameController.java
> +            return new Names(Name.of(InputView.getNames()));
아래와 같이 하는 경우와는 어떤 차이가 있나요?
```suggestion
            return Names.of(InputView.getNames());
```

2023-02-16 09:23 UTC, boorownie commented on src/main/java/domain/FootStep.java
> +    }
toString을 재정의해주는 이유는 무엇인가요?

2023-02-16 09:23 UTC, boorownie commented on src/main/java/domain/Ladder.java
> +//        }
불필요한 주석은 제거해주세요

2023-02-16 09:23 UTC, boorownie commented on src/main/java/domain/Ladder.java
> +    }
객체 주입을 통한 랜덤 요소 분리 👍

2023-02-16 09:23 UTC, boorownie commented on src/test/java/domain/HeightTest.java
> +    @DisplayName("생성될 떼")
```suggestion
    @DisplayName("생성될 때")
```

2023-02-16 09:23 UTC, boorownie commented on src/test/java/domain/HeightTest.java
> +                    .hasMessage("사다리 길이는 2에서 10사이여야 합니다.");
단위 테스트 검증 시 메시지까지 검증하는것과 예외 발생 여부만 검증하는 것 중 메시지 까지 검증하는 방법으로 구현해주셨는데요~
각각의 장단점은 무엇이며 어떠한 부분을 중요하게 생각해서 선택하신건지 궁금해요~

2023-02-16 09:23 UTC, boorownie commented on src/test/java/domain/LadderTest.java
> +    @Nested
`@Nested` 활용 👍

2023-02-16 09:23 UTC, boorownie commented on src/test/java/domain/LadderTest.java
> +        @DisplayName(" 원하는 모양대로 만들 수 있다.")
이 설명은 무엇을 위한 설명인가요?

2023-02-16 09:23 UTC, boorownie commented on src/test/java/domain/LineTest.java
> +        @DisplayName(" 있는 디딤돌이면 지금 다리는 디딤돌이 생성되는 것이 허용되지 않는다.")
ㅋㅋㅋ 그냥 궁금한건데 띄어쓰기를 메서드에 앞에 주셨는데
클래스 뒤에 두시면 중복제거가 될 수 있지 않을까요?ㅋㅋ
다른 `@DisplayName`과도 컨벤션을 맞추면 좋을 것 같아요.

2023-02-16 09:28 UTC, gracefulBrown requested changes
안녕하세요 여우~ 땜빵 리뷰를 맡은 브라운입니다.
사다리 미션 1단계 구현 잘 해주셨고요~
더 생각해보기 좋은 질문으로 코멘트 남겨놓았으니 고민해보시고
반영할 것 있으면 반영하시고 질문 있으면 질문 주세요~

원시값이 필요한 상황에서도 getter 메소드를 사용하지 않고 객체 내부를 보호하는 방법이 있을까요?
-> 내부의 값이 필요해서 접근하는 건 나쁜게 아닙니다. 다만 조금 이상하다는 생각이 든다면 객체 설계를 다시해야하는 건 아닐지를 고민해볼 수 있는 포인트긴 해요. getter를 많이 사용해야한다면 어쩌면 불필요하게 객체를 분리한 건 아닌가 생각해보시면 좋겠네요.

어떤 객체의 행동에 대해 테스트코드를 작성하는데, 그 행동의 결과를 조회할 수 없는 경우에는 테스트를 어떻게 진행하야 할 지 막막해요.
-> 단위 테스트 작성 방식은 행동의 결과 조회, 즉 상태 변화를 검증하는 것 외에 행위를 검증하는 방법도 있습니다. 하지만 지금은 굳이 학습하시는 걸 추천드리지 않아서 여기까지만 키워드를 드리겠습니다.

2023-02-16 11:38 UTC, BackFoxx commented on src/main/java/Application.java
> +        LadderGameController game = new LadderGameController();
LadderGameController의 run() 메소드를 호출하여 작업을 수행할 때,
사다리 객체를 만들 때 인자로 BooleanGenerator의 구현체를 주입해요.

```
public class LadderGameController {

    public void run() {
        ...
        Ladder ladder = buildLadder(names, height);
        ...
    }

    private Ladder buildLadder(final Names names, final Height height) {
        Ladder ladder = new Ladder(new RandomBooleanGenerator());
        ladder.build(height, names.count());
        return ladder;
    }
```
이번에 제출한 pr에서는 시간이 부족해서 
RandomBooleanGenerator라는 무작위 boolean 값을 생성하는 클래스를 
controller 안에서 만들어 필요한 곳에 주입하는 코드가 나왔는데,

사실 제가 의도한 코드는 아래처럼 BooleanGenerator의 구현체를 컨트롤러 외부에서 주입받아 사용하게 하고,

```
public class LadderGameController {

    private final BooleanGenerator booleanGenerator;

    public LadderGameController(BooleanGenerator booleanGenerator) {
        this.booleanGenerator = booleanGenerator;
    }

    public void run() {
        ...
        Ladder ladder = buildLadder(names, height);
        ...
    }

    private Ladder buildLadder(final Names names, final Height height) {
        Ladder ladder = new Ladder(new RandomBooleanGenerator());
        ladder.build(height, names.count());
        return ladder;
    }
```

BooleanGenerator의 적절한 구현체를 Application에서 주입하도록 구현하면
```
public class Application {
    public static void main(final String[] args) {
        LadderGameController game = new LadderGameController(new NeMamDeRoGenerator());
        game.run();
    }
}
```
테스트하기 어려운 랜덤값이 아니라 내맘대로 값을 생성할 수 있는 구현체를 주입할 수도 있으니,
나중에 컨트롤러를 테스트하는 코드를 작성할 때에도 유용하지 않겠느냐는 생각을 했어요.

생성자를 통한 외부 주입이 가능하려면 컨트롤러의 정적 메소드를 호출하는 방식보다
컨트롤러의 인스턴드를 생성하고 run 메소드를 호출하는 방식으로 설계하는 것이 좋겠다 판단했습니다. ;)

BooleanGenerator가 하드코딩된 현재 코드에서는 
'컨트롤러의 인스턴스를 굳이 왜 만들었지'라는 의문이 충분히 드실 만 하다 생각해요!

2023-02-17 05:41 UTC, BackFoxx commented on src/main/java/controller/LadderGameController.java
> +        OutputView.printResult(new GameDto(names, ladder));
코멘트를 보고, 컨트롤러에서 뷰로 names와 ladder를 넘겨주면 뷰에서 dto를 만들어 사용하는 방식으로 시도를 해보았습니다.

작업을 하다가 문득, 
'2개의 도메인 객체가 컨트롤러로부터 인자로 넘어와서 이미 뷰에서 그 객체를 사용할 수 있게 되었는데, 
이제 와서 dto를 만드는 게 무슨 소용이지?' 라는 생각이 들었어요.

그러다보니 dto의 존재 이유에 의문이 들었고,
결과적으로 'dto 자체가 필요하지 않겠구나' 라는 생각에 도달했습니다.
그래서 리팩토링한 코드에서는 메시지 생성에 필요한 List<List<Boolean>> 등의 값을 
도메인 객체의 메소드를 직접 호출해 가져와 사용하는 것으로 바꾸고, Dto 객체들을 전부 삭제했습니다.
dto를 사용할 때보다 오히려 가독성이 더 좋아진 느낌이에요! ;)

2023-02-17 05:46 UTC, BackFoxx commented on src/main/java/controller/LadderGameController.java
> +            return new Names(Name.of(InputView.getNames()));
제안해주신 방식이 더 가독성 좋은 것 같아요! 사실 생성자를 통한 객체 생성과 정적 팩토리 메소드를 통한 객체 생성 방식이 통일되어 있지 않아서 리팩토링 대상이었는데, 짚어주셔서 감사합니다! 이번 리팩토링 작업에서 통일할 생각이에요.

2023-02-17 05:58 UTC, BackFoxx commented on src/test/java/domain/HeightTest.java
> +                    .hasMessage("사다리 길이는 2에서 10사이여야 합니다.");
하나의 작업에서 여러 가지의 검증 작업(문자열의 길이, 소문자인 지, 공백 포함인 지 등)이 이루어지는 경우,
발생하는 예외의 종류는 같은 IllegalArgumentException이지만
예외가 발생하는 이유는 우리가 의도한 것과 다른 이유로도 발생할 수 있습니다.

따라서 '어떤 이유로 IllegalArgumentException이 발생했다' 를 구분할 수 있게 해주는 것이
예외 클래스 생성자의 인자로 들어가는 예외 메시지이고,
이 예외 메시지를 테스트 대상에 포함함으로써
우리가 의도한 이유대로 원하는 예외가 발생한 것이 맞는 지를 검증할 수가 있습니다 !

2023-02-17 06:01 UTC, BackFoxx commented on src/test/java/domain/LadderTest.java
> +        @DisplayName(" 원하는 모양대로 만들 수 있다.")
Ladder 객체의 build 메소드를 호출할 때, 사다리의 높이와 넓이 값을 넘겨줌으로써
우리가 의도한 높이와 넓이대로 사다리가 만들어진다는 것을 나타내고 싶었습니다.
그래서 높이, 넓이, 생성된 사다리 칸의 총 개수를 테스트하는 테스트케이스들을 하나로 묶어
'원하는 모양대로 만들 수 있다' 라는 이름으로 지었습니다! 해당 의도를 표현하는 더 좋은 문장이 있을 지 고민해 보겠습니다.

2023-02-17 06:02 UTC, BackFoxx commented on src/test/java/domain/LineTest.java
> +        @DisplayName(" 있는 디딤돌이면 지금 다리는 디딤돌이 생성되는 것이 허용되지 않는다.")
ㅋㅋㅌㅋ아무래도 서로 자주 교대하면서 네이밍 컨벤션이 꼬인 것 같아요! 깔끔하게 통일하겠습니다.

2023-02-17 09:43 UTC, BackFoxx commented on src/main/java/domain/FootStep.java
> +    }
디버깅시 객체 상태를 파악하기 쉽게 하기 위해 오버라이딩 했습니다!
제 페어는 디버깅 경험이 없으셔서, 같이 디버깅하면서 toString으로 만든 메시지를 보면서 같이 공부했습니다.

2023-02-18 06:22 UTC, gracefulBrown commented on src/test/java/domain/HeightTest.java
> +                    .hasMessage("사다리 길이는 2에서 10사이여야 합니다.");
테스트를 작성 할 때 꼼꼼하게 검증하는 것이 좋을 수 있지만 반대로 깨지기 쉬운 테스트가 될 수 도 있습니다. 에러 종류 보다는 에러 메시지가 도 디테일한 검증을 하는 것이라고 볼 수 있는데 이 역시 상대적으로 깨지기 쉬운 테스트라 할 수 있습니다.

만약에 코멘트 남겨주신 것 처럼 여러 상황이 있는데 상황에 따라 다른 예외가 발생해야하는 경우 Exception을 다르게 지정해주는 방법도 있습니다.

2023-02-18 06:28 UTC, gracefulBrown approved these changes
피드백 반영 확인했습니다!
코드 구현을 잘 하시고 피드백 반영도 잘 하시네요
코멘트에 대해 깊은 고민과 그 흐적을 잘 남겨주셔서 감사합니다.
이어서 다음 단계 미션 진행해주세요~

2023-02-18 06:28 UTC, gracefulBrown commented on src/main/java/Application.java
> +        LadderGameController game = new LadderGameController(new RandomBooleanGenerator());
👍

2023-02-18 06:28 UTC, gracefulBrown commented on src/main/java/util/MessageGenerator.java
> +public class MessageGenerator {
메시지 출력에 대한 책임을 위임받은 객체 도출 👍

2023-02-18 06:28 UTC, gracefulBrown commented on src/main/java/util/MessageGenerator.java
> +        StringBuilder stringBuilder = new StringBuilder();
과할 수 있지만 StringBuilder를 상속받은 객체를 만든다면 MessageGenerator 처럼 유틸성 클래스가 아닌 행위와 상태를 가진 온전한 객체가 될 수 있을 것 같네요 :)

2023-02-18 06:28 UTC, gracefulBrown commented on src/main/java/util/MessageGenerator.java
> +        StringBuilder stringBuilder = new StringBuilder();
과할 수 있지만 StringBuilder를 상속받은 객체를 만든다면 MessageGenerator 처럼 유틸성 클래스가 아닌 행위와 상태를 가진 온전한 객체가 될 수 있을 것 같네요 :)

2023-02-18 06:28 UTC, gracefulBrown commented on src/main/java/domain/Names.java
> +    public static Names of(final List<Name> names) {
👍

2023-02-18 06:28 UTC, merged

2023-02-18 06:32 UTC, BackFoxx commented on src/test/java/domain/HeightTest.java
> +                    .hasMessage("사다리 길이는 2에서 10사이여야 합니다.");
앗 그렇다면 구현 코드에서 예외 메시지들을 상수로 선언한 다음,
테스트코드의 hasMessage(INVALID_VALUE_EXCEPTION_MESSAGE) 처럼 안에 해당 상수를 인자로 담아 검증하는 방법에 대해서는 어떻게 생각하시나요?

구현 코드의 메시지가 변경되더라도 테스트에 영향이 미치지 않으므로 비교적 안전하지 않을까 생각합니다!

2023-02-18 06:34 UTC, BackFoxx commented on src/test/java/domain/HeightTest.java
> +                    .hasMessage("사다리 길이는 2에서 10사이여야 합니다.");
코치님의 조언처럼 상황에 알맞게 IllegalArgumentException을 상속한 예외 클래스를 만들어 사용하면 어떨까 생각하다가도, 예외 클래스가 너무 많아지는 건 아닐까하는 걱정이 듭니다.

2023-02-18 06:35 UTC, gracefulBrown commented on src/test/java/domain/HeightTest.java
> +                    .hasMessage("사다리 길이는 2에서 10사이여야 합니다.");
그것도 좋은 방법이라고 생각합니다.
프로덕션 코드의 변경으로 인해 테스트가 깨지는 경우를 우려한 것인데
말씀하신 방법대로 하면 덜 깨지기 쉬운 테스트가 될 것 같네요 :)

2023-02-19 03:39 UTC, BackFoxx commented on src/main/java/util/MessageGenerator.java
> +        StringBuilder stringBuilder = new StringBuilder();
Line 객체가 StringBuilder를 상속하게 만든 후에 
Line.generateMessage() 같은 메소드를 통해 사다리 모양을 가져오라는 뜻으로 생각하면 될까요?

일단 StringBuilder가 final class 라서 상속이 안되어요 •́︿•̀ ..
다른 방법을 사용해서 어찌어찌 MessageGenerator의 로직을 Line 객체의 행위로 만들었다고 해도,

사다리의 모양은 뷰와 관련한 작업인데
이 작업이 도메인 객체의 행위에 들어가버리면
도메인 객체가 뷰에 의존하는 것이 되는 건 아닌지 걱정되어요! 코치님의 의견이 궁금합니다. ;)