[사다리 게임] 코맥 미션 제출합니다.
woowacourse/java-ladder pull request #14
Opened 2019-05-17 06:33 UTC by CODEMCD

2019-05-18 00:30 UTC, ssosso requested changes
안녕하세요, 성범님:) 두 번째 리뷰어 장소현입니다.
고민을 많이 하신 것이 느껴집니다. 좋습니다 👍 
제 피드백은 무조건 수용하지 않으셔도 되고 의심되시거나 궁금한 점이 있으시면 언제든 말씀주셔야 합니다.
성범님의 의견을 언제든 듣고 이야기할 준비가 되어 있습니다.
피드백드리오니 확인 부탁드리며, 코드 사이사이 newline이 간간히 들어가 있는데 정리 부탁드립니다:)
잘 부탁드립니다.

2019-05-18 00:30 UTC, ssosso commented on src/main/java/textcalculator/TextCalculator.java
> +        if (text.charAt(0) == '/' && text.charAt(1) == '/' && text.charAt(3) == 10) {
정규식을 사용해보는 것이 어떨까요~?

2019-05-18 00:30 UTC, ssosso commented on src/main/java/ladder/LadderMain.java
> +    private static OutputView outputView;
InputView와 OutputView를 LadderMain의 변수로 선언하지 않고 InputView와 OutputView의 메서드들을 static 메서드로 변경해 보면 어떨까요~?

2019-05-18 00:30 UTC, ssosso commented on src/main/java/ladder/LadderMain.java
> +
과한 newline은 지양합니다.

2019-05-18 00:30 UTC, ssosso commented on src/main/java/ladder/LadderMain.java
> +            ladder.make();
ladder.make() 메서드를 별도로 호출하지 않고 Ladder 인스턴스를 생성할 때 바로 ladder 내부에서 make가 호출되면 어떨까요~?

2019-05-18 00:30 UTC, ssosso commented on src/main/java/ladder/domain/LadderRewards.java
> +//        Arrays.asList(text.split(",")).
불필요한 주석 제거

2019-05-18 00:30 UTC, ssosso commented on src/main/java/ladder/domain/LadderRewards.java
> +        rewards = Arrays.stream(text.split(","))
`","` 상수로 변경

2019-05-18 00:30 UTC, ssosso commented on src/main/java/ladder/domain/LadderRewards.java
> +        rewards = Arrays.stream(text.split(","))
text split은 view에서 진행하는 것이 어떨까요~?

2019-05-18 00:30 UTC, ssosso commented on src/main/java/ladder/domain/RandomGenerator.java
> +    int number() {
접근제어자가 default인 것은 의도하신 건가요~?

2019-05-18 00:30 UTC, ssosso commented on src/main/java/ladder/domain/Players.java
> +        List<String> names = Arrays.asList(inputName.split(","));
split은 view에서 하는 것이 어떨까요~?

2019-05-18 00:30 UTC, ssosso commented on src/main/java/ladder/domain/RandomGenerator.java
> +    }
RandomGenerator인데 테스트를 위해서 직접 numbers를 받을 수 있는 생성자를 만드신 것으로 이해했습니다. 좋습니다:)
조금 더 나아가서 Generator라는 인터페이스를 만들고 이를 구현한 RandomGenerator와 CustomGenerator(가칭)를 만들어 사용하는 것은 어떨까요~? RandomGenerator를 가지고 있는 모든 다른 객체들에 원하는 Generator를 넘겨 확장성있게 동작하도록 하면 어떨까요~?

2019-05-18 00:30 UTC, ssosso commented on src/main/java/ladder/domain/LadderRow.java
> +        return randomGenerator.number() == LadderRules.RANDOM_DRAW.number();
LadderRules에 number가 동일한지의 여부를 확인할 수 있는 메서드를 만드는 것은 어떨까요~?

2019-05-19 05:46 UTC, CODEMCD commented on src/main/java/textcalculator/TextCalculator.java
> +        if (text.charAt(0) == '/' && text.charAt(1) == '/' && text.charAt(3) == 10) {
정규식을 사용하여 변경하였습니다!

2019-05-19 06:18 UTC, CODEMCD commented on src/main/java/ladder/LadderMain.java
> +    private static OutputView outputView;
static 메서드를 사용하여 InputView와 OutputView를 구현하는 것으로 변경하였습니다. 그 결과 LadderMain의 필드가 줄어들었고, 여러 곳에서 View 인스턴스를 생성하여 호출하였는데 이를 생성하지 않고 쉽게 호출할 수 있었습니다. 한 가지 궁금한 점은 static 메서드는 객체지향설계에서 최대한 사용하지 않는 것이 좋다고 알고 있습니다. 하지만 View를 구현할 때는 지난 미션에서도 그렇고 대부분 static 메서드를 사용하는 것을 보았습니다. 이 부분은 View관련 로직은 유틸리티 메소드처럼 여러 곳에서 자주 호출되기 때문이라고 생각할 수 있을까요? 아니면 다른 이유가 있는 지 궁금합니다!

2019-05-19 06:19 UTC, CODEMCD commented on src/main/java/ladder/LadderMain.java
> +
newline 을 삭제하였습니다!

2019-05-20 01:02 UTC, CODEMCD commented on src/main/java/ladder/domain/RandomGenerator.java
> +    int number() {
리팩토링 과정에서 위 메서드가 같은 패키지에서만 사용한다는 것으로 판단하고 default 접근 제어자로 변경하였습니다. 현재에는 Generator 클래스에 변화가 생겨 이름을 generate()로 변경되었고, public 접근 제어자를 사용하였습니다. 이는 Generator 클래스들은 util 패키지로 분류하여 어디서든 사용할 수 있다고 판단하였습니다.

2019-05-20 01:02 UTC, CODEMCD commented on src/main/java/ladder/domain/LadderRewards.java
> +//        Arrays.asList(text.split(",")).
주석 제거하였습니다!

2019-05-20 01:04 UTC, CODEMCD commented on src/main/java/ladder/domain/LadderRewards.java
> +        rewards = Arrays.stream(text.split(","))
리뷰어님의 말씀을 듣고 split은 View에 관한 로직으로 생각되어 InputView로 옮겼습니다. 그에 따라 ```","``` 도 같이 옮겨졌으며, InputView에서 상수로 변경하였습니다.

2019-05-20 01:04 UTC, CODEMCD commented on src/main/java/ladder/domain/Players.java
> +        List<String> names = Arrays.asList(inputName.split(","));
InputView로 split()을 옮겼습니다!

2019-05-20 01:09 UTC, CODEMCD commented on src/main/java/ladder/domain/RandomGenerator.java
> +    }
리뷰어님의 말씀을 듣고 다시 RandomGenerator 클래스를 보았을 때 실제 사다리 게임에서 사용하는 랜덤 생성 기능과 테스트 코드에서 입력받는 기능이 함께 있다고 생각되었습니다. 이를 나누기 위해 Generator 인터페이스를 만들고 공통으로 사용하는 number() 메서드(현재, generate())를 추출하였고 각 클래스가 구현하도록 하였습니다.

이로 인해 코드가 좀 더 이해하기 쉬워졌고, 필요에 따라 여러 Generator를 만들어 사용할 수 있다고 생각하였습니다.

2019-05-20 01:12 UTC, CODEMCD commented on src/main/java/ladder/domain/LadderRow.java
> +        return randomGenerator.number() == LadderRules.RANDOM_DRAW.number();
사다리를 만드는 것은 사다리 규칙에 따라 만들기 때문에 LadderRules에 있는 것이 더 적합하다고 생각하였습니다. 또한, 위 코드에서도 LadderRules에서 상수를 가지고 로직을 판단하는데, 이보다 LadderRules에서 바로 판단하는 것이 더 효율적이라고 생각하였습니다.

2019-05-20 01:18 UTC, CODEMCD commented on src/main/java/ladder/LadderMain.java
> +            ladder.make();
Ladder 클래스는 사다리를 만드는 책임을 가지는 클래스로 설계하였습니다. 이를 make()메서드를 호출하여 사다리를 만드는 것은 지금보면 불필요한 메서드라고 생각하였습니다.

2019-05-20 01:59 UTC, CODEMCD commented
피드백을 반영하며 리팩토링을 하면서 Main을 수정하였습니다. 사다리 게임에서 입력을 받으며 Player, Reward, Height 등을 만드는 것을 CreateController 클래스로 분리하였습니다. Height 클래스는 사다리 높이를 입력받으면서 유효성을 검사하기 위해 클래스로 분리하였습니다. 기존에 높이 입력에 대한 유효성 검사는 Ladder 클래스에 있었지만 다시 생각해보면서 Ladder를 만들 때는 높이와 폭이 정상적인 것이 보장되어야 한다고 생각하였습니다.

2019-05-20 13:14 UTC, ssosso commented on src/main/java/textcalculator/TextCalculator.java
> +        if (text.charAt(0) == '/' && text.charAt(1) == '/' && text.charAt(3) == 10) {
",|:"는 상수화 하면 좋을 것 같습니다.

2019-05-20 13:27 UTC, ssosso commented on src/main/java/ladder/LadderMain.java
> +    private static OutputView outputView;
static에 대해서는 여러가지 의견이 있습니다. 절대적으로 무엇이 좋다고 할 수는 없지만, static 메서드나 변수를 무분별하게 습관적으로 사용하는 것은 저도 좋지 않다고 생각합니다. 다만 View라는 객체를 보았을 때 굳이 매번 생성하지 않아도 되고 특정한 상태를 가지지 않아도 될 것으로 판단했기 때문에 static 메서드로의 변경을 권해드렸으며, 다시 반대로 생각해보면 scanner를 인스턴스 변수로 가지는 inputView 클래스를 만들어 인스턴스를 생성해 사용할 수 있다면 그것 또한 좋은 방향이라고 생각합니다.

2019-05-20 13:36 UTC, ssosso requested changes
좋습니다 👍 여러가지 좋은 시도들이 있었고 성범님 또한 어떤 것들을 느끼셨는지 이야기해주시면서 정리가 되신 것 같습니다:) Height를 만드신 시도는 아주 좋습니다. 성범님이 객체를 분리해내는 것에 능력이 한 단계 성장하셨다는 생각이 듭니다. 다만 이에 대한 테스트가 누락이 되어 있는데 확인 해주시면 좋을 것 같습니다. CreateController는 조금 더 좋은 클래스명이 있을까요~? 어떤 것이 좋을까요?

2019-05-21 07:39 UTC, ssosso approved these changes
merge 하겠습니다.
마지막 살짝 피드백을 더 드리자면 LadderRules는 enum이기 때문에 Rules 보다 Rule로 클래스명을 정하는 것이 어떨까 하며, 이에 대한 테스트도 있으면 좋을 것 같습니다.
고생하셨습니다:)

2019-05-21 07:39 UTC, merged

2019-05-21 08:52 UTC, CODEMCD commented
상세한 피드백 감사드립니다!!