[2단계 - 사다리 게임 실행] 로이스(원태연) 미션 제출합니다.
woowacourse/java-ladder pull request #154
Opened 2023-02-20 11:58 UTC by TaeyeonRoyce

안녕하세요, 로이스입니다.
2단계에서는 기능 구현 뿐만 아니라, View 영역과 도메인 영역을 분리하도록 노력하였습니다.
Formatter라는 클래스를 만들어서 출력 형식을 만들 수 있도록 분리하였는데, 좋은 방법인지 잘 모르겠습니다.

추가적으로 궁금했던점은 이전과 동일하게 코멘트로 남겨두겠습니다..!

2023-02-20 12:06 UTC, TaeyeonRoyce commented on src/main/java/domain/ladder/Ladder.java
>                  .forEach(it -> lines.add(Line.fromHeight(height)));
IntStream이 가독성이 안좋다는 의견을 들었었습니다!
완태는 어떻게 생각하시나요?

대체하면 for문을 사용할 수 있을 것 같습니다.
```java
for (int i = 0; i <= width < i++) {
    lines.add(Line.fromHeight(height));
}
```

2023-02-20 12:06 UTC, TaeyeonRoyce commented on src/main/java/util/formatter/LadderContentConsoleViewFormatter.java
> +    }
다양한 글자 크기에 대응 하여 사다리 출력형식을 유지할 수 있도록 공백을 활용하여 가운데 정렬하는 메서드입니다.
로직이 다소 이해하기 어려워 주석을 추가하였습니다

2023-02-21 18:30 UTC, wannte commented on src/main/java/domain/ladder/Ladder.java
>                  .forEach(it -> lines.add(Line.fromHeight(height)));
지금 이 상황에서 봤을 때에는, for loop 가 더 직관적인것 같습니다!

2023-02-21 19:01 UTC, wannte requested changes
안녕하세요 로이스!

이번에도 미션 빠르게 잘 구현해주셨네요!

특히 세밀하게 남긴 커밋 메시지가 읽기 쉽고 인상적이었습니다!

몇 가지 커멘트 및 고민 포인트 남겨두었는데 확인해보시고 다시 리뷰 요청주세요! 🙏

2023-02-21 19:01 UTC, wannte commented on src/test/java/domain/ResultContentTest.java
> +    }
꾸준히 테스트를 짜며 로직을 쳐내는 게 쉽지 않은데, 👍

2023-02-21 19:01 UTC, wannte commented on src/main/java/controller/LadderGameController.java
> +        String playerNamesInput = inputView.requestPlayerNames();
List<String> 을 받으면 어떨까요? 그럼 view 가 domain 에 의존하지 않으면서도 코드가 깔끔해질 것 같네요!

2023-02-21 19:01 UTC, wannte commented on src/main/java/domain/LadderGame.java
> +    }
Player가 Result를 가지고 있는 구조와 그렇지 않은 구조의 장단점에 대해서 고민해보면 좋을 것 같아요!

현재 구조 vs (예를 들어: Player 가 가지지 않고 Ladder.getResult(int startAt) returns int resultAt )

저는 각자 장단점이 있을 것이라 생각해요

2023-02-21 19:01 UTC, wannte commented on src/main/java/domain/ladder/Ladder.java
> +    }
(이미 많이 고민해서 결론낸 결과물 같지만, 혹시나 해서 남겨보는 고민 포인트)

Ladder가 (Players, ResultContents) 를 가지고 있을 때와 없을 때의 장단점을 고민해봐도 좋을 것 같아요!

2023-02-21 19:01 UTC, wannte commented on src/main/java/util/formatter/LadderConsoleViewFormatter.java
> +public class LadderConsoleViewFormatter {
Formatter 걸 두고 view 를 정말 깔끔하게 관리해주셨네요! 💯 

view를 읽기 너무 편해진 것 같아요! 

현재 package는 util로 분리해뒀는데, 이 formatter 로직은 view에만 적용될 것이라 생각하는데, view 에 두는 것은 어떨까요? (weak opinion)

2023-02-21 19:01 UTC, wannte commented on src/main/java/util/formatter/LadderContentConsoleViewFormatter.java
> +     * @return format
주석까지.. 최곱니다 👍

2023-02-22 00:14 UTC, TaeyeonRoyce commented on src/main/java/controller/LadderGameController.java
> +        String playerNamesInput = inputView.requestPlayerNames();
`inputView.requestPlayerNames()` 에서 메서드네임 때문에 의존한다고 판단하신걸까요?
현재 도메인은 모른체 순수 입력값을 `String`으로 반환하기때문에 의존하지 않는다고 생각했습니다!

2023-02-22 00:36 UTC, TaeyeonRoyce commented on src/main/java/domain/LadderGame.java
> +    }
우선 제가 생각하는 현재 구조의 장단점에 대해서 말씀드릴게요.
장점으로는 게임이 진행 된 후, `Player`는 사다리 게임의 결과를 `Result` 가지기에 조회에 용이다하는 점입니다. 프로그램의 기능 중에 `Player`의 결과를 반복 조회하는 기능에 대해 용이하게 사용이 가능하다고 생각합니다. 단점으로는 `Player`가 가지는 `Result`에 대해 지연 초기화(?)(lazyinit)가 발생한다는 점 입니다. 결국 null 로 값을 가지다가 수정하는 메서드(setter)가 필요하고, 게임 결과의 불변성을 잃을 수 있기 때문입니다.

이러한 단점은, 완태가 제안한 방식으로 'Result'를 소유하지 않으면서 해결이 가능합니다. 단점이라 한다면, 자주 발생하는 `[결과 조회]`에 대해 매번 `[사다리를 타는]` 로직을 수행해야 한다는 점 입니다.

결국, `Player`는 불변한 상태만 소유하여 안전성을 높이거나 이를 포기하고 자주 사용 되는 기능에 대해 성능을 끌어올리는 선택으로 이어질 것 같습니다. 현재 프로그램에서는 성능적인 부분을 선택하는게 큰 메리트는 없어보이긴 합니다.

완태의 생각도 비슷할까요?

2023-02-22 00:37 UTC, TaeyeonRoyce commented on src/main/java/util/formatter/LadderConsoleViewFormatter.java
> +public class LadderConsoleViewFormatter {
weak opinion에 대해 강하게 공감합니다. 현재 formatter의 역할도 console view에 종속적이라 생각해서요!

2023-02-22 00:46 UTC, TaeyeonRoyce commented on src/main/java/domain/ladder/Ladder.java
> +    }
기능을 추가하면서 관성적으로 `Ladder`가 `Players`, `ResultContents`를 추가적으로 소유하도록 생각했었습니다. 그렇게 추가해보니 `Ladder`가 5개의 필드를 가지더라구요. 그래서 분리를 고민했고, `LadderGame`을 추가했습니다.

`사다리`는 정말 `사다리`만 구성 되어있길 원했고, '게임'에서 해당 '사다리'를 사용하도록 분리하는게 자연스럽더라구요.

\+ 제 짧은 생각으로는 어떤 단점이 발견되는지 잘 모르겠습니다...

2023-02-22 01:10 UTC, wannte commented on src/main/java/controller/LadderGameController.java
> +        String playerNamesInput = inputView.requestPlayerNames();
이 부분만 quick 하게 남기면,

커밋내역을 봤을 때, 로이스님이 `그럼 view 가 domain 에 의존하지 않게` 고민을 많이 하신 거 같더라고요!

그 관점을 유지한채 코드가 깔끔해지는 방법으로 피드백 드린 부분이었습니다! (이 리뷰만 봤을 때에는 헷갈리네요..!)

2023-02-22 03:11 UTC, TaeyeonRoyce commented on src/main/java/controller/LadderGameController.java
> +        String playerNamesInput = inputView.requestPlayerNames();
아 이해했습니다. 현재 "p1,p2,p3"에 대해 `[구분자로 분리하여 PlayerNames 생성]` 이라는 역할 자체도 사실 Domain이 view의 형식을 알고 있는 것 처럼 보이는것 같네요.

게임 참가자의 입력 형식이 어떻게 들어오는지는 View의 영역(View마다 다를 수 있음)이라 생각하고, Domain인 PlayerNames는 그걸 모르게 `List<String>` 타입으로 생성되는게 더 유연성을 챙길 수 있을 것 같네요! 좋은 의견 감사드립니다.🙇‍♂️

2023-02-24 04:28 UTC, wannte commented on src/main/java/domain/LadderGame.java
> +    }
넵! ㅎㅎ 로이스가 말하는 부분에 동의하는 부분입니다!

> 매번 [사다리를 타는] 로직을 수행

이 부분에 대해서는 충분히 최적화를 진행할 수도 있을 것이라 생각해요
한 번 조회를 한다면, 그 결과를 기억해둘 수도 있지 않을까? 의 관점에서 의견 남겨봐요

2023-02-24 04:35 UTC, wannte commented on src/main/java/domain/ladder/Ladder.java
> +    }
넵! 도메인간의 강한 결합을 갖지 않게 index?를 통해서 그 연관관계를 끊는 방법을 사용했다 생각하고, 매우 좋은 방법이라 생각해요!

단점이라고 생각할 만한 부분은, Player, ResultContents, Ladder 는 그 갯수가 서로 같아야 한다는 강한 불변식을 가지고 있는데, 이 부분의 관리를 강제할 수가 없는 부분을 들을 수 있을 것 같아요. 만약 Ladder가 Player, ResultContents 를 가지고 있다면 생성 시점에 이를 방어할 수 있는 로직을 둘 수 있을 것 같고요!

2023-02-24 05:14 UTC, wannte approved these changes
안녕하세요 로이스!

제가 리뷰 요청을 놓쳤어서,, 2차 리뷰가 늦어졌네요!

관련해서 질문 주신 부분 답변 확인 부탁드리고요! 이미 너무나 잘 구현되어 있어 이만 머지하겠습니다.

추가 질문 있으시면 언제든 DM 주세요~

2023-02-24 05:14 UTC, merged