[2단계 - 사다리 게임 실행] 지토(김지민) 미션 제출합니다.
woowacourse/java-ladder pull request #158
Opened 2023-02-21 06:38 UTC by apptie

안녕하세요, 배럴!
피드백 주신 부분 참고해서 2단계 미션을 진행했습니다.
밑에 리펙토링 내용과 질문 내용을 정리했습니다.
다시 한 번 리뷰 잘 부탁드립니다!

---

## 리펙토링 

#### 일급 컬렉션이 의미를 가질 수 있도록 변경
이전에는 일급 컬렉션에 getter만 있는 경우가 많았습니다.
그래서 일단 일급 컬렉션이 주입받은, 관리하고자 하는 컬렉션에 대한 검증 로직을 추가했습니다.
이후 2단계 미션을 진행하며 Ladder를 제외한 나머지 일급 컬렉션은 컬렉션 관리와는 별도의 기능을 갖도록 진행했습니다.

#### 프록시 패턴 삭제
말씀해주신대로 InvocationHandler에서 InvocationTargetException.getCause()의 null 체크와 사용자 관련 예외인 IllegalArgumentException만을 처리하도록 변경했습니다. 
이 과정에서 제가 오버 엔지니어링을 적용했다고 느꼈습니다.
이후 2단계 미션을 진행하며 기능을 추가하는데 Controller가 상태를 가지게 되어 Controller까지 변경되는 경우가 너무 많아, 이를 해결할 수 있는 방법을 고려하다 찾지 못하고 프록시 패턴을 삭제하고 요구사항에 존재하지 않던 오류 발생 시 재입력 부분을 삭제했습니다.
앞으로는 주어진 미션에 집중하고 정말 시간이 남고 여유로우면 새로운 시도를 해봐야겠다고 느꼈습니다...

#### Custom Exception 삭제
하나의 예외 상황에 대해 하나의 Custom Exception을 적용하다보니 너무 많아지게 되어 생산성이 떨어진다는 느낌을 받았습니다.
하나의 도메인에 대한 전체적인 Custom Exception을 만드는 것을 고려했으나, 이 또한 생산성이 떨어질 것 같다고 느껴 자바에서 제공해주는 Exception을 사용하고, 그에 대한 예외 메세지는 하드 코딩을 하는 식으로 변경했습니다.

#### View와 관련된 부분은 View에서 처리하도록 변경
Path가 가지고 있던 View 관련 로그를 OutputView로 변경했습니다.

#### Controller가 View를 제외한 다른 상태를 가지지 못하도록 변경
이전에는 InputView, OutputView를 제외하고도 mappings, LadderMaker에 대한 상태를 가지고 있어 이전의 LadderStatus의 상태가 추가된다거나 LadderMaker에 변경이 생긴 경우 Controller도 동시에 변경을 해야 했습니다.
이러한 문제를 최대한 방지하기 위해 Controller가 View를 제외한 다른 상태를 가지지 못하도록 변경했습니다.

#### 문서 최신화
말씀해주신대로 용어(클래스)가 어떤 역할인지 간략하게 정리했고, Flow Chart를 추가했습니다.

---

## 질문

#### 정적 팩토리 메소드 사용
생성 과정이 복잡한 LadderGame이나 인자로 받는 값이 상태를 초기화할 때 직접적으로 관련이 없는 LadderResults의 경우 생성자보다는 정적 팩토리 메소드가 좋겠다고 판단해 적용했습니다.
다만 처음 사용하는 정적 팩토리 메소드이다보니 제가 판단한 근거가 타당한지 판단이 잘 되지 않는 상태라서, 이 부분에 대해 조언을 부탁드리고 싶습니다.

#### 예외 처리 방식
현재 사용자가 입력한 내용과 관련있는 부분은 IllegalArgumentException, initLadder()를 호출하지 않은 상태에서 findLadder를 호출하거나 하는 개발과 관련된 부분은 IllegalStateException으로 분리한 상태입니다.
그래서 사용자 입력 관련은 Controller에서 예외를 처리하고 OutputView에서 예외 메세지를 출력하도록 했고, IllegalStateException은 Controller를 호출하는 LadderApplication에서 예외를 처리하고 바로 sout으로 콘솔에 출력하도록 했습니다.
이럴 때 사용하는 예외가 IllegalStateException이 맞는지, 그리고 이런 식으로 사용자 관련 예외와 개발 관련 예외를 분리하는 건 어떤지 평가를  부탁드리고 싶습니다.

#### 사다리 게임 진행 시 진행 상황을 의미하는 Position(원시값)을 감쌀지 여부
현재 LadderGame.playLadderGame(int position, Ladder ladder)에서 사다리 게임을 진행하는데, 여기서 Position의 경우 사다리의 높이를 고려할 필요가 없고, 진행할 때 마다 값이 변경되야 하므로 포장하지 않고 원시값을 그대로 사용하고, Position의 이동 경로에 따라 변경되는 값을 Direction이라는 enum으로 처리했었습니다.
이러한 상황에서 지금 구현한 방식보다는 Position을 포장한 클래스를 추가하고 Direction에서 수행하는 로직을 합치는게 좋은지 잘 판단이 되지 않습니다...이 부분에 대해서 조언을 부탁드리고 싶습니다.

감사합니다!

2023-02-22 10:53 UTC, knae11 commented
1. 이유에 동의합니다~
2. IllegalStateException 설명을 읽어보니 `Signals that a method has been invoked at an illegal or inappropriate time. In other words, the Java environment or Java application is not in an appropriate state for the requested operation.` 부적절한 시점에 호출될 때 발생하는 예외라고 하니 잘 이해하고 있는 듯 하네요. 하지만 IllegalStateException이 발생한다고 애플리케이션이 끝나버리기 보단 계속 운영될 수 있도록 하는건 어떨까요?
3. 수직으로의 이동은 한방향으로만 일어나고 있기 때문에 Direction으로의 가로축이동으로 처리해도 충분해 보입니다!

2023-02-22 10:54 UTC, knae11 requested changes
안녕하세요. 지토! 굉장히 꼼꼼한 성격이신것 같네요! 테스트도 다양하게 작성해주셨구요 👏👏👏👏👏

몇가지 코멘트를 남겨보았습니다~~~ :)

2023-02-22 10:54 UTC, knae11 commented on src/main/java/LadderApplication.java
> +        } catch (IllegalStateException e) {
잘못된 입력에 대해서는 그대로 애플리케이션 실행이 멈추는데요. 인지하고 있는 ERROR에도 동작하게 만들어주면 어떨까요~?

2023-02-22 10:54 UTC, knae11 commented on src/main/java/view/InputView.java
>          return Arrays.stream(names.split(DELIMITER))
trim을 사용하여 공백처리도 해주면 사용성이 조금 더 높아지겠어요!

2023-02-22 10:54 UTC, knae11 commented on src/test/java/model/LadderResultsTest.java
> +        @ParameterizedTest
`ParameterizedTest(name = "" )`의 name 속성을 이용하면 테스트 이름을 더 효과적으로 표현할 수도 있어요~!

2023-02-22 10:54 UTC, knae11 commented on src/main/java/model/LadderGame.java
> +    public LadderGame(Names names, LadderResults gameResults) {
생성을 정적팩터리메서드로만 사용하고 있다면 private 하게 만들어줄 수 있겠네요!

2023-02-22 10:54 UTC, knae11 commented on src/main/java/model/LadderGameCommand.java
> +    DEFAULT_COMMAND("all");
DEFAULT_COMMAND 라는 네이밍이 모호하게 느껴지네요

2023-02-22 10:54 UTC, knae11 commented on src/main/java/controller/LadderController.java
> +        return new Names(names);
이런 로직은 Names가 할 수 있지도 않을까요?

2023-02-22 10:54 UTC, knae11 commented on src/main/java/controller/LadderController.java
> +        return LadderResults.of(ladderResults, totalParticipantSize);
마찬가지로 LadderResults가 초기화 해줄 수도 있겠네요!

2023-02-22 10:54 UTC, knae11 commented on src/main/java/model/LadderGame.java
> +public class LadderGame {
LadderGame이 여러 도메인 객체들을 조합하여 비지니스 로직을 처리하고 있다고 생각이 드는데요. Controller에 도메인객체가 최대한 노출되지 않게 LadderGame 안에서 로직을 구성하는 방안으로 리팩터링 해보는건 어떨까요~?

2023-02-22 10:54 UTC, knae11 commented on src/main/java/model/LadderGame.java
> +        LadderResults gameResults = ladderResults.calculateGameResult(gameResult);
결과대로 재구성해서 LadderResults 객체를 다시 만들어 주는군요! 위에서 파라미터로 받은 객체와 약간 혼란스러울 수도 있겠어요! 로직을 다 파악하기 전에는 결과대로 정렬되어있는지 알기 어렵겠어요.

2023-02-22 10:54 UTC, knae11 commented on src/main/java/model/LadderMaker.java
> +    public void initLadder(Height height, int totalParticipantSize) {
초기화 하는 로직도 Ladder가 가지고 있는건 어떻게 생각하세요? 작성해주신 이유와 같이 정적 팩토리 메서드를 사용하면 Ladder에서도 초기화가 가능할 것 같은데요.

2023-02-22 10:55 UTC, knae11 commented on src/main/java/LadderApplication.java
> +        } catch (IllegalStateException e) {
![image](https://user-images.githubusercontent.com/66905013/220600128-c63cd1ee-7b0d-4730-bfd2-ae213bc79c2f.png)
공백등으로 이름이 일치하지 않을 경우에 그대로 멈춰버리네요ㅠ

2023-02-22 10:57 UTC, knae11 commented
- LadderGame이 도메인 객체를 조합하여 비지니스 로직을 구성하고 있어보이는데요. Controller단에 최대한 도메인 객체가 노출되지 않도록 LadderGame 안으로 넣어보는 건 어떨까요?
- 정적팩터리메서드를 사용하여 일급컬렉션에서 생성의 책임도 같이 가져가보는건 어떻게 생각하세요~?

2023-02-22 14:13 UTC, apptie commented on src/main/java/LadderApplication.java
> +        } catch (IllegalStateException e) {
> 잘못된 입력에 대해서는 그대로 애플리케이션 실행이 멈추는데요. 인지하고 있는 ERROR에도 동작하게 만들어주면 어떨까요~?

한 번 시도해 보겠습니다!

2023-02-22 14:14 UTC, apptie commented on src/main/java/view/InputView.java
>          return Arrays.stream(names.split(DELIMITER))
> 공백등으로 이름이 일치하지 않을 경우에 그대로 멈춰버리네요ㅠ
> trim을 사용하여 공백처리도 해주면 사용성이 조금 더 높아지겠어요!

이 부분은 전혀 고려하지 못한 부분이었습니다.
사용성...당연히 누군가는 이 기능을 사용해야 할 테니 중요한 요소일텐데 피드백을 해주시고 나서야 인지하게 되네요..ㅜㅜ
감사합니다!

2023-02-22 14:15 UTC, apptie commented on src/test/java/model/LadderResultsTest.java
> +        @ParameterizedTest
리펙토링 때 활용해 보도록 하겠습니다. 감사합니다!

2023-02-22 14:19 UTC, apptie commented on src/main/java/model/LadderGame.java
> +    public LadderGame(Names names, LadderResults gameResults) {
PR 요청하고 뒤늦게 확인해 수정하긴 했었는데 들켰네요 ㅜㅜ 
[476c21e](https://github.com/woowacourse/java-ladder/pull/158/commits/476c21e1b1cac51bf4804a6ef2a82e7d8076ed56) 해당 커밋에 처리해놓기는 했습니다..ㅎㅎ;

2023-02-22 14:20 UTC, apptie commented on src/main/java/model/LadderGameCommand.java
> +    DEFAULT_COMMAND("all");
확실히 이름을 통해 알 수 있는 정보가 없네요...
해당 커맨드가 사다리 게임의 모든 참가자의 결과를 출력하라는 커맨드이며, 이후 애플리케이션이 종료된다는 사실을 알 수 있도록 변경해보도록 하겠습니다! 감사합니다!

2023-02-22 14:26 UTC, apptie commented on src/main/java/controller/LadderController.java
> +        return LadderResults.of(ladderResults, totalParticipantSize);
> 이런 로직은 Names가 할 수 있지도 않을까요?
> 마찬가지로 LadderResults가 초기화 해줄 수도 있겠네요!

지금은 일급 컬렉션이 관리할 컬렉션을 주입받기 때문에 조금 더 유연하겠지만, 외부에서 주입하는 만큼 의존적이 될 수 밖에 없고, 컬렉션 내부에 관리하고 있는 도메인 정보에 대해서도 외부에 노출되겠네요..
피드백 해 주신 대로 리펙토링을 해보도록 하겠습니다! 감사합니다!

2023-02-22 14:28 UTC, apptie commented on src/main/java/model/LadderGame.java
> +public class LadderGame {
이 부분은 전혀 고려하지 못했습니다.
제가 이해한게 맞을진 모르겠지만...LadderGame을 Service 계층 같은 대리자로 Controller는 LadderGame에만 의존하고 나머지 도메인 정보들은 모두 LadderGame에 숨기는 방식으로 리펙토링을 진행해보겠습니다! 감사합니다!

2023-02-22 14:34 UTC, apptie commented on src/main/java/model/LadderGame.java
> +        LadderResults gameResults = ladderResults.calculateGameResult(gameResult);
미리 만들어놓은 LadderResults를 재사용해볼 겸 로직을 작성했는데, 말씀해주신 대로 좀 이해하기 어려운 코드가 된 것 같습니다...

DTO로 사용했던 GameResult를 도메인으로 변경시키고, 이를 관리하는 일급 컬렉션을 추가해 조금 더 읽기 쉽게 표현해보도록 하겠습니다! 감사합니다!

2023-02-22 14:35 UTC, apptie commented on src/main/java/model/LadderMaker.java
> +    public void initLadder(Height height, int totalParticipantSize) {
이 부분은...왜 놓쳤는지 이해가 되지 않네요 ㅎㅎ; 피드백 주신대로 리펙토링 하도록 하겠습니다!

2023-02-22 15:00 UTC, apptie commented
> LadderGame이 도메인 객체를 조합하여 비지니스 로직을 구성하고 있어보이는데요. Controller단에 최대한 도메인 객체가 노출되지 않도록 LadderGame 안으로 넣어보는 건 어떨까요?

Controller가 최대한 도메인과 관련된 로직이나 의존성 없이 LadderGame(Service가 될 거 같은 후보..?)에 최대한 숨겨 Controller가 도메인의 변경 사항에 최대한 영향을 받지 않도록 리펙토링 해 보겠습니다!

> 정적팩터리메서드를 사용하여 일급컬렉션에서 생성의 책임도 같이 가져가보는건 어떻게 생각하세요~?

외부에서 주입하는 대신 정적 팩토리 메소드를 사용하면 외부에서 일급 컬렉션이 관리하는 요소에 대한 의존성을 줄여 기존보다 독립적으로 사용할 수 있을 것 같고, 생성자에서 관리할 컬렉션을 생성하지 않고 분리하다 보니 더 직관적이고 테스트하기 조금 더 용이할 것 같습니다!
일급 컬렉션과 관련된 내용도 피드백 해 주신 대로 리펙토링 해보도록 하겠습니다!

2023-02-24 08:35 UTC, apptie commented
안녕하세요, 배럴!
피드백 주신 부분 참고해서 리펙토링을 진행했습니다.
이전과 동일하게 리펙토링 한 부분을 밑에 정리했습니다.
리뷰 잘 부탁드립니다!

---

## 리펙토링

### 일급 컬렉션 생성 시 외부에서 관리할 컬렉션을 주입받지 않고 정적 팩토리 메소드에서 관리할 컬렉션을 생성하도록 변경
LadderMaker에서 관리할 컬렉션을 모두 생성해 주입하던 방식에서 컬렉션을 생성하기 위한 정보를 정적 팩토리 메소드에 주입해 일급 컬렉션 내부에서 관리할 컬렉션을 생성하도록 변경했습니다.

복잡한 컬렉션을 생성하는 로직을 LadderMaker에서 각각의 일급 컬렉션으로 옮기다보니 LadderMaker의 책임이 사라져서 결과적으로는 LadderMaker를 삭제했습니다.

### Controller에서 도메인 관련 의존성을 삭제하고 LadderGame에서 도메인을 관리하도록 변경
Controller에서 도메인에 의존하고 있던 부분을 모두 삭제하고, LadderGame에서 도메인을 관리하도록 변경했습니다.

그리고 LadderGame에서 Controller로 반환할 때 최대한 원시값이나 컬렉션을 반환하려고 했고, 부득이한 경우에는 DTO를 통해 최대한 도메인이 노출되지 않도록 했습니다.

### 사용자 편의성 고려
말씀해주신대로 사용성을 위해 입력한 문자열에 대해 trim()을 적용했습니다.

### IllegalArgumentException 발생 시 로직 재실행

사용자가 입력한 내용에 대해서만 예외 발생 시 로직을 재실행하도록 변경했습니다.

---

감사합니다!

2023-02-26 06:11 UTC, knae11 commented
지토 충분히 아래 내용을 잘 구현해 주신 것으로 보여 Merge 하겠습니다! 👏💯👏
- 일급컬렉션
- 원시값 포장
- 도메인이 노출되지 않도록 역할을 나누기
- 나아가서 핸들링처리 및 테스트

2023-02-26 06:11 UTC, knae11 approved these changes

2023-02-26 06:11 UTC, merged