[2단계 - 사다리 게임 실행] 무민(박무현) 미션 제출합니다.
woowacourse/java-ladder pull request #162
Opened 2023-02-21 14:10 UTC by parkmuhyeun

안녕하세요 터틀!!
오랜만이에요.. 1단계 때 따뜻한 피드백 감사합니다. 이번 2단계도 잘 부탁드려요.

우선 2단계를 진행하기전 아래와 같은 상황을 반영하고 시작했습니다.
- 불필요한 테스트 제거(1단계 때 리뷰 받은)
  - 생성자 테스트 제거
  - generate 테스트 제거
- 입력 예외 처리 순서 변경
  - 원래는 이름에서 예외가 터져도 바로 발생하지 않고 사다리 높이 입력을 받고 나서야 터졌습니다!
  - 지금은 이름을 입력받을 때 바로 터지도록 수정해놨습니다.
-  클래스명 수정
  - Person -> Player, Persons -> Player
- hasMessage() 추가
- 1명 예외 처리

그리고나서 이제 2단계를 구현하다가 든 생각인데 이제 객체가 많이 생성되고 있고 이들간에 긴밀한 협력이 이뤄지고 있는데 이때가 Service가 도입 될 타이밍인가? 이런생각이 들었습니다. 하지만 생각만 한 저에게 회초리를 내려주세요..

그리고 뭔가 고쳐야될 부분이 많은 것 같은 찜찜한 기분으로 뭔가 제출하는데 그 이유는 지금 머리에 과부하가 온 저에게는 잘 보이지 않습니다..
날카로운 피드백과 매서운 회초리 부탁드려요.. ~~그래도 가끔은 당근도 조금 주시면... 감사하겠읍니다.~~

남은기간이 꽤 되기 때문에 열심히 리팩토링하는데 시간 쏟아보겠습니다!! 🙇🙇🙇

2023-02-22 15:07 UTC, begaonnuri requested changes
안녕하세요 무민!

어려운 요구사항이었을텐데도 빠르게 미션을 완성해주셨네요 💯 
정신없이 리뷰하고 보니 채찍만 남긴것같지만.. 뒤늦게 많은 당근 드리겠습니다 🥕 🥕 🥕 🥕 
몇가지 리뷰 남겼으니 확인 부탁드릴게요!

리뷰가 이해안되거나 궁금하신 부분 생기시면 편하게 DM주세요!

2023-02-22 15:07 UTC, begaonnuri commented on src/main/java/controller/LadderGameController.java
>          Ladder ladder = new Ladder(height, names.size(), generator);
결과(`Results`)는 사다리게임 진행을 통해 도출되어야 하는게 아닐까요?

컨트롤러가 Model과 View의 상호작용 뿐만 아니라 게임 진행까지 진행하고 있는것같아요. 무민이 의도한 Controller의 역할은 무엇인가요?

2023-02-22 15:07 UTC, begaonnuri commented on src/main/java/controller/LadderGameController.java
>          Ladder ladder = new Ladder(height, names.size(), generator);
플레이어 이름을 입력받은 다음 객체를 만들었다면 이후엔 객체간 협력을 통해 로직이 진행하도록 하면 어떨까요?

만든 객체가 아니라 입력받은 `names`를 통해 진행하는 로직이 많아보여요. `names.size()`가 그 트리거입니다!

2023-02-22 15:07 UTC, begaonnuri commented on src/main/java/domain/Player.java
> +        return results.getResult(currentPosition);
Position 클래스를 만들었다면 값을 `꺼내서` 계산하는 것이 아니라 Position 클래스와 상호작용을 통해 계산해보는건 어떨까요?

2023-02-22 15:07 UTC, begaonnuri commented on src/main/java/domain/Players.java
> +    }
불필요한 static이네요! 정적 팩터리 메서드를 시도했었나요?😁

2023-02-22 15:07 UTC, begaonnuri commented on src/main/java/domain/Players.java
> +    }
getter는 클래스 하단에 위치하는것이 좋습니다!

2023-02-22 15:07 UTC, begaonnuri commented on src/main/java/domain/Players.java
> +                .filter(player -> player.getName().equals(name))
지금은 `player.gerName()`이 `Name.getName()`인 String을 반환해서 equals가 제대로 동작할텐데요,

만약에 `player.gerName()`이 Name 객체를 반환한다면 이 결과는 어떻게될까요? 그리고 이것을 어떻게 방지할 수 있을까요?

2023-02-22 15:07 UTC, begaonnuri commented on src/main/java/view/InputView.java
> +        System.out.println("\n" + LADDER_HEIGHT_INPUT_NOTICE);
`LADDER_HEIGHT_INPUT_NOTICE` 상수 값 맨 앞에 `\n`을 추가하면 더 깔끔해지지 않을까요?

2023-02-22 15:07 UTC, begaonnuri commented on src/main/java/view/InputView.java
> +        return readInput();
`scanner.nextLine();`을 두번 하게 되는데 의도한 동작일까요?

코드를 작성한 무민도 헷갈리셨다면 `scanner.nextLine()`를 메서드로 분리한게 과한 분리라는 신호일 수 있을것같아요.

2023-02-22 15:07 UTC, begaonnuri commented on src/main/java/view/OutputView.java
> +    private static void appendNewLine(List<Line> lines, StringBuilder builder, int index) {
마찬가지로 불필요한 static이군요!

2023-02-22 15:07 UTC, begaonnuri commented on src/test/java/domain/LadderTest.java
> +                .hasMessage("[ERROR] 사다리 높이는 1이상이어야 합니다.");
기존에 `isInstanceOf`로만 테스트를 작성하셨다가 `hasMessage`를 추가하신 이유는 무엇인가요?

각각 어떤 장단점이 있었나요?

2023-02-22 15:07 UTC, begaonnuri commented on src/test/java/domain/LadderTest.java
> +                .hasMessage("[ERROR] 사다리 높이는 1이상이어야 합니다.");
그리고 이런 경우라면 객체의 상수를 package-private으로 변경하고 참조하면 어떨까요?

2023-02-22 15:07 UTC, begaonnuri commented on src/test/java/domain/PlayerTest.java
> +    @DisplayName("결과가 잘 나오는지 확인")
`잘`을 더 풀어서 적어보면 어떨까요?

2023-02-22 15:07 UTC, begaonnuri commented on src/test/java/techcourse/jcf/mission/ListStudy.java
> +    public void arrayList() {
학습테스트를 야무지게 작성해주셨군요 👍🏻

2023-02-23 02:50 UTC, parkmuhyeun commented on src/main/java/domain/Players.java
> +    }
아닙니다! 메서드 추출 단축키를 사용했었는데 자동으로 static이 붙은거 같아요ㅠㅜ

직접 테스트 해보니깐 static과 관련된 코드를 추출할 때는 static이 붙는거 같네요. 
앞으로는 더 주의 깊게 보며 사용하겠습니다!~!

2023-02-23 02:53 UTC, parkmuhyeun commented on src/main/java/domain/Players.java
> +    }
혹시 왜 getter는 클래스 하단에 위치하는게 좋은지 알 수 있을까요!? 
어차피 getter는 당연히 로직이 뻔하니깐 제일 아래 두는 걸까요?

2023-02-23 04:19 UTC, parkmuhyeun commented on src/test/java/domain/LadderTest.java
> +                .hasMessage("[ERROR] 사다리 높이는 1이상이어야 합니다.");
hasMessage를 추가적으로 적어준 건 메시지까지 확인함으로 써 더 정확한 테스트를 하기 위해 추가했습니다!

2023-02-23 04:34 UTC, parkmuhyeun commented on src/main/java/view/InputView.java
> +        return readInput();
이 부분은 앞에서 nextInt()로 받아서 버퍼에 enter가 남아있어서 비운 것이였는데 깔끔하게 앞에서 nextLine()으로 받게해서 제거했습니다!

2023-02-23 08:26 UTC, parkmuhyeun commented on src/test/java/domain/LadderTest.java
> +                .hasMessage("[ERROR] 사다리 높이는 1이상이어야 합니다.");
여기서는 메시지를 재활용하기 위해 package-private 접근자로 바꾸는거 맞을까요!?
실제로도 package-private를 많이 쓰는지 궁금합니다!

2023-02-23 14:59 UTC, parkmuhyeun commented on src/main/java/controller/LadderGameController.java
>          Ladder ladder = new Ladder(height, names.size(), generator);
지금까지 짤 때는 각 객체나 Controller의 역활을 망각하고 짠거 같아 많이 반성중입니다..! 앞으로는 역활에 대해 더욱 신중하게 생각해보고 코드를 짜겠습니다!

2023-02-23 15:16 UTC, parkmuhyeun commented
안녕하세요 터틀..! 막 대공사를 끝내고 난 뒤라 정신이 없네요..ㅋㅋㅋㅋ

이번에 대공사를 진행하면서 아.. 설계가 정말 중요하구나라는 걸 다시 한번 깨닫게 되는 시간이였습니다.. 그래도 이번에 많은 걸 깨닫게 된거 같아 기분이 매우 좋네요..!! 앞으로 각 객체의 역활을 잘 생각해보면서 짜보겠습니다.

이번에 각 객체(Ladder, Player, Result)끼리의 의존성을 없애는데 중점으로 로직들을 다시 구현했습니다.
그래서 현재 결과값을 얻기까지 Flow는 다음과 같이 변하게 되었습니다!
- player의 첫 position을 알아내
- ladder에게 position을 넘기면 이동 후 lastPosition 반환
- lastPosition을 이용해 result 출력

그리고 이전의 피드백은 다음과 같이 반영했습니다~
- static 제거
  - 메서드 추출 단축키를 사용했었는데 자동으로 static이 붙은거 같아요ㅠㅜ
  - 직접 테스트 해보니깐 static과 관련된 코드를 추출할 때는 static이 붙는거 같네요.
  - 앞으로는 더 주의 깊게 보며 사용하겠습니다!
- getter 하단으로 이동
  - 혹시 왜 getter는 클래스 하단에 위치하는게 좋은지 알 수 있을까요!?
  - 어차피 getter는 당연히 로직이 뻔하니깐 제일 아래 두는 걸까요? 
- LADDER_HEIGHT_INPUT_NOTICE와 개행 합치기
- 중복 scanner.nextLine() 제거
  - 이 부분은 앞에서 nextInt()로 받아서 버퍼에 enter가 남아있어서 비운 것이였는데 깔끔하게 앞에서 nextLine()으로 받게해서 제거했습니다!
- package-private 적용 
  - 여기서는 메시지를 재활용하기 위해 package-private 접근자로 바꾸는거 맞을까요!?
  - 실제로도 package-private를 많이 쓰는지 궁금합니다!

2023-02-24 11:43 UTC, begaonnuri commented on src/main/java/domain/Players.java
> +    }
클래스를 작성하는 것이 아니라 참조하는 경우 가장 관심있는 정보는 나에게 제공하는 public API일거에요. (잘 공감이 안된다면 우리가 자바 라이브러리 String, Integer 클래스를 보는 경우를 생각해보세요!) 생성자와 정적 팩터리 메서드를 제외하곤 이 메서드가 가장 위에 존재하는게 좋다고 생각해요. 그리고 같은 이유로 getter, setter 등과 같은 메서드나 Object 메서드를 오버라이드한 경우엔 하단에 위치시키는게 좋다고 생각합니다! 

이 부분은 컨벤션이라기 보단 암묵적 합의 정도인것같아요. 무민의 생각은 어떠신가요?

https://dodop-blog.tistory.com/277 이것도 한번 읽어보세요 😊

2023-02-24 11:44 UTC, begaonnuri commented on src/main/java/view/InputView.java
> +        return readInput();
이런 경우엔 `scanner.reset()`을 사용해서 클리어하는것도 좋을것같아요!

2023-02-24 11:47 UTC, begaonnuri commented on src/test/java/domain/LadderTest.java
> +                .hasMessage("[ERROR] 사다리 높이는 1이상이어야 합니다.");
상수를 추출한것은 하드코딩된 값을 더 잘 표현하기 위한 이유도 있지만 재사용성을 늘리는 이유도 있다고 생각해요. 

테스트코드는 일반적으로 test 디렉토리에 같은 패키지경로에 위치하기도 하고, public으로 열어줄 이유가 없다면 private 단계 바로 위의 접근제어자인 package-private을 사용 안할 이유가 없어보여요!

2023-02-24 11:48 UTC, begaonnuri commented on src/test/java/domain/LadderTest.java
> +                .hasMessage("[ERROR] 사다리 높이는 1이상이어야 합니다.");
> 실제로도 package-private를 많이 쓰는지 궁금합니다!

사실 이런 경우엔 메시지를 지정하기보단 커스텀한 Exception을 지정해서 테스트하는 경우가 더 많은것같아요

2023-02-24 12:16 UTC, begaonnuri requested changes
코드가 정말 많이 개선됐네요 무민! 고민을 많이 하신게 느껴집니다 💯 
몇 가지 리뷰 남겼으니 한번 더 확인해주세요!
(접혀있어서 확인 안하신 리뷰도 있던데 다시한번 확인해주세요 🥲)
질문주신 부분은 추가로 코멘트 달았습니다.

매번 코멘트로 변경 내용을 Summary 해주시는 덕분에 리뷰가 편하네요 ㅎㅎ 🙇🏻‍♂️

2023-02-24 12:16 UTC, begaonnuri commented on src/main/java/controller/LadderGameController.java
> +        if (targetPlayer.equals(ALL_PLAYER)) {
`플레이어의 이름이 all과 같지 않아야 한다`는 비즈니스 로직이 아닐까요? 적절한 책임을 갖는 객체로 이동시켜보면 어떨까요?

2023-02-24 12:16 UTC, begaonnuri commented on src/main/java/controller/LadderGameController.java
>              return;
[요구사항](https://techcourse.woowahan.com/s/96wouxOM/ls/VL9Z2dxm)엔 지속적으로 결과 출력을 묻고있는데 여기선 애플리케이션이 종료되어버리네요😥

2023-02-24 12:16 UTC, begaonnuri commented on src/main/java/controller/LadderGameController.java
> +        players.validateTargetPlayer(targetPlayer);
위 리뷰에서 적절한 객체로 이동한다면 이 부분도 Controller가 아니라 해당 객체에서 처리할 수 있지 않을까요?

2023-02-24 12:16 UTC, begaonnuri commented on src/main/java/controller/LadderGameController.java
> +        outputView.printPlayerResult(results.getResult(lastPosition));
의도적으로 View와 Model의 결합도를 낮추려는 시도가 좋네요 👍🏻  (아니라면 머쓱..)

2023-02-24 12:16 UTC, begaonnuri commented on src/main/java/domain/Ladder.java
> +        if (direction == Direction.LEFT) {
Enum이더라도 꺼내서 비교하기보단 객체에 메시지를 던져보는건 어떨까요?

2023-02-24 12:16 UTC, begaonnuri commented on src/main/java/domain/Player.java
>  public class Player {
Player의 책임이 대폭 축소됐군요 👍🏻

2023-02-24 12:41 UTC, parkmuhyeun commented on src/main/java/domain/Players.java
> +    }
진짜 좋은거 같아요!! 
실제로 들어와서는 외부에서 주로 사용하는 로직 관련 메서드를 주로 보지 getter나 setter를 보지 않으니까요!! 
감사합니다.

2023-02-24 12:42 UTC, parkmuhyeun commented on src/main/java/view/InputView.java
> +        return readInput();
오 이런게 있었다니.. 감사합니다!

2023-02-24 12:44 UTC, parkmuhyeun commented on src/test/java/domain/LadderTest.java
> +                .hasMessage("[ERROR] 사다리 높이는 1이상이어야 합니다.");
오호... 앞으로 미션을 진행할 때 package-private도 적용해봐야겠군요!! 감사합니다.

2023-02-24 12:49 UTC, parkmuhyeun commented on src/main/java/domain/Players.java
> +                .filter(player -> player.getName().equals(name))
Name 객체를 반환한다면 현재 equals가 재정의 되어 있지 않기 때문에 객체의 참조를 비교해 원하는대로 동작하지 않을 것 같아요!
그래서 방지하려면 equals 와 hashCode를 재정의 해주면 될 것 같습니당!
이것두 수정해서 반영하겠습니다.

2023-02-24 17:00 UTC, parkmuhyeun commented on src/main/java/controller/LadderGameController.java
> +        outputView.printPlayerResult(results.getResult(lastPosition));
히히 그런걸로 해주세요..ㅋㅋㅋㅋ!!   :)

2023-02-24 17:05 UTC, parkmuhyeun commented
안녕하세용 터틀!

다음은 이전에 안 달은 코멘트 입니다!
```
지금은 player.gerName()이 Name.getName()인 String을 반환해서 equals가 제대로 동작할텐데요,
만약에 player.gerName()이 Name 객체를 반환한다면 이 결과는 어떻게될까요? 그리고 이것을 어떻게 방지할 수 있을까요?
```


Name 객체를 반환한다면 현재 equals가 재정의 되어 있지 않기 때문에 객체의 참조를 비교해 원하는대로 동작하지 않을 것 같아요!
그래서 방지하려면 equals 와 hashCode를 재정의 해주면 될 것 같습니당!

그리고 이번에 반영한 피드백은 다음과 같습니다.
- 적절한 책임을 갖는 객체로 이동(results로 이동 시켰습니다!)
- 지속적으로 결과 출력할 수 있도록 추가(all을 입력할 때 까지 계속 출력할 수 있습니다~)
- Direction 꺼내서 비교 -> 객체 메시지 전달

2023-02-26 13:17 UTC, begaonnuri requested changes
리뷰 잘 반영해주셨네요 무민! 👍🏻 
몇가지 리뷰 남겼으니 한번 더 확인해주세요~

2023-02-26 13:17 UTC, begaonnuri commented on src/main/java/controller/LadderGameController.java
> +    private static List<String> getResults(Players players, Results results, Ladder ladder, String targetPlayer) {
불필요한 static이군요😅

2023-02-26 13:17 UTC, begaonnuri commented on src/main/java/controller/LadderGameController.java
> +        if (finalResults.size() != SINGLE_SIZE) {
이 부분 역시 도메인 로직이 아닐까요? 결과를 `getResults` 메서드에서 List<String>을 반환하는 것이 아니라 도메인 객체를 반환해서 이 부분을 메시지를 던지는 형태로 변경해보면 어떨까요?

2023-02-26 13:17 UTC, begaonnuri commented on src/main/java/domain/Command.java
> +}
콘솔이 아닌 웹 형태에서도 Command가 유지될까요? 그렇다면 Command는 어떤 패키지에 위치하는것이 좋을까요?

2023-02-26 13:17 UTC, begaonnuri commented on src/main/java/domain/Ladder.java
> +    }
stream API에 익숙하시지 않다면 이 부분을 stream API를 활용해 변경해보면 어떨까요?

그리고 stream API를 활용하면 어떤 점이 좋을까요? (너무 어렵다면 우선 활용만 해보세요!)

2023-02-26 13:17 UTC, begaonnuri commented on src/main/java/domain/Results.java
> +        List<String> results = new ArrayList<>();
이 results 컬렉션에 add해야되어서 아래 메서드에 계속 인자를 넘겨주게 되네요.

로직 중간에 다른 리스트가 인자로 넘어가거나 순서가 변경된다면 기대하는 동작이 이루어지지 않을 수도 있을것같아요.

리스트를 생성하고 add 하는 것이 아니라 새로운 ArrayList를 반환하도록 변경해보는건 어떨까요? 이 부분도 stream API를 활용하면 조금 더 깔끔해질 수 있지만 익숙하지 않다면 굳이 stream을 사용하지 않으셔도 됩니다!

2023-02-26 13:17 UTC, begaonnuri commented on src/main/java/domain/Player.java
> +        return getName().equals(name);
Name 객체에 메시지를 던지는 형식으로 변경해보면 어떨까요?

2023-02-26 13:17 UTC, begaonnuri commented on src/main/java/domain/Players.java
> +    public int getTargetPlayerPosition(String targetPlayer) {
사용하지 않는 메서드군요

2023-02-26 13:17 UTC, begaonnuri commented on src/test/java/domain/LadderTest.java
> +                .hasMessage("[ERROR] 사다리 높이는 1이상이어야 합니다.");
Custum Exception으로 처리해보는 것도 좋을것같아요 👍🏻

2023-02-26 13:17 UTC, begaonnuri commented on src/main/java/domain/Result.java
> +public class Result {
값 객체라면 equals와 hashCode를 재정의하는건 어떨까요?

2023-02-26 15:20 UTC, parkmuhyeun commented on src/main/java/domain/Ladder.java
> +    }
코드가 간결해져 가독성이 좋아질거 같아요!!

2023-02-26 15:23 UTC, parkmuhyeun commented
안녕하세요 터틀...
많이 부족한 저 때문에 고생이 많으십니다..!!
덕분에 엄청나게 많이 배워가고 있어요... 정말 감사합니다 🙇🙇🙇

### 적용한 피드백

우선 이번에 적용한 피드백은 다음과 같습니다!
- 불필요한 static, 메서드 제거
- SINGLE_SIZE 확인하는지 확인하는 로직 -> 도메인으로 이동
- Command 패키지 이동
- Stream 적용
  - 덕분에 Stream에 대해 더 공부해본 거 같고 앞으로는 더 적극적으로 사용해보겠습니다!
- isTargetPlayer 수정
- Result equals, hashCoode 재정의

그리고 다음과 같은 궁금한 점이 생겼습니다!

### Custom Exception

Custom Exception을 만든다고 해도 따로 그 에러에 대한 특별한 처리를 해주는 것이 없어 지금 표준 예외로도 충분히 뜻을 전할 수 있을 것 같아 사용하지 않았는데 터틀의 생각은 어떤가요?

### Equals, HashCode

현재 Result는 비교하는 코드가 없지만 앞으로 어떻게 될지 모르니 equals와 hashCode를 재정의 해 추가해 주는게 맞을까요? 그렇다면 값 객체는 처음 생성할 때부터 같이 equals와 hashCode를 재정의 해주는게 좋을까요!?

2023-02-26 15:44 UTC, begaonnuri approved these changes
처음에 비해 코드가 많이 개선됐네요 무민! 👍🏻 
이번 미션은 여기서 머지하도록 하겠습니다! 추가로 코멘트 남긴 부분만 한번 더 확인해주세요. 고생하셨어요!😊

2023-02-26 15:44 UTC, begaonnuri commented on src/main/java/domain/Results.java
> +        if (targetPlayer.equals(ALL_PLAYER)) {
다음과 같은 형태로도 사용하는데 이유가 무엇이고 어떤 점이 좋을까요?
```suggestion
        if (ALL_PLAYER.equals(targetPlayer)) {
```

2023-02-26 15:44 UTC, begaonnuri commented on src/main/java/domain/Results.java
> +            return new Results(allPlayerResult.size(), allPlayerResult);
count를 별도로 받는 이유가 있을까요?

2023-02-26 15:44 UTC, begaonnuri commented on src/main/java/domain/Results.java
> +        return Objects.equals(results, results1.results);
컬렉션에선 대부분 `AbstractXXX`(여기선 `AbstractList`) 클래스에서 equals를 재정의하고 이와 동일하기 때문에 굳이 재정의할 필요가 없습니다. 

[이펙티브자바 아이템 10](https://velog.io/@lychee/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%EC%9E%90%EB%B0%94-%EC%95%84%EC%9D%B4%ED%85%9C-10.-equals%EB%8A%94-%EC%9D%BC%EB%B0%98-%EA%B7%9C%EC%95%BD%EC%9D%84-%EC%A7%80%EC%BC%9C-%EC%9E%AC%EC%A0%95%EC%9D%98-%ED%95%98%EB%9D%BC) 글도 가볍게 읽어보시고 너무 어렵게 느껴지신다면 무시해주세요!

2023-02-26 15:44 UTC, begaonnuri commented on src/main/java/domain/Result.java
> +
이 부분도 테스트가 필요하지 않을까요?

2023-02-26 15:44 UTC, merged

2023-02-26 15:55 UTC, begaonnuri commented
### Custom Exception

맞습니다! 하지만 IlegalArgumentException과 예외 메시지가 아닌, 커스텀 예외로도 처리할 수 있다는 것을 말씀드리고싶었어요😊

### equals, hashCode

일반적으론 무민의 말이 맞고, 더 나아가선  Entity, VO 구분 등 식별자를 갖는 객체인지 판단이 필요한데 지금은 어려운 내용일 수 있습니다! 현재는 원시값 포장 객체엔 적용하는것이 좋다 정도로 알고계시면 좋을것같네요!

2023-02-26 16:01 UTC, parkmuhyeun commented
ㅠㅠ 주말에도 늦은시간까지 피드백에 답변까지.. 감사합니다...!!
덕분에 많이 배웠고, 많은 생각을 할 수 있게 되었습니다.

앞으로 미션할 때 적용해볼게 많이 생겨 벌써부터 설레네요.. 감사합니다~

2023-02-27 02:12 UTC, parkmuhyeun commented on src/main/java/domain/Results.java
> +            return new Results(allPlayerResult.size(), allPlayerResult);
Results를 반환하려 하다보니 Results를 만들려는 현재 생성자에서 count가 필요하다보니 억지로 넣어줬는데 그렇다면 이경우에는 size 확인이 필요없으니 List<String> 만 받는 생성자를 새로 하나 생성해주는게 좋은지 궁금합니다!

2023-02-27 02:40 UTC, parkmuhyeun commented on src/main/java/domain/Results.java
> +        return Objects.equals(results, results1.results);
```java
    @Test
    @DisplayName("targetPlayer에 all이 입력되면 참여자 결과 모두 반환")
    void getAllFinalResults() {
        Results results = new Results(3, List.of("꽝", "5000", "3000"));

        assertThat(results.getFinalResults(List.of("a", "b", "c"), List.of(1, 0, 2), "all"))
                .isEqualTo(new Results(3, List.of("5000", "꽝", "3000")));
    }

    @Test
    @DisplayName("targetPlayer에 참여자 이름이 입력되면 해당 참여자 결과만 반환")
    void getSingleFinalResults() {
        Results results = new Results(3, List.of("꽝", "5000", "3000"));

        assertThat(results.getFinalResults(List.of("a", "b", "c"), List.of(1, 0, 2), "a"))
                .isEqualTo(new Results(1, List.of("5000")));
    }
```

현재 위의 테스트에서 Results 객체를 비교하고 있는데 여기서 equals와 hashCode를 없애면 제대로 동작 안하지 않나요?

2023-02-27 02:50 UTC, parkmuhyeun commented on src/main/java/domain/Results.java
> +        if (targetPlayer.equals(ALL_PLAYER)) {
NullPointerException을 방지할 수 있어 실수를 줄일 수 있는 좋은 방법 같아요!!