[2단계 - 사다리 게임 실행] 누누(송은우) 미션 제출합니다.
woowacourse/java-ladder pull request #167
Opened 2023-02-22 05:23 UTC by be-student

안녕하세요 누누입니다
2주차 미션 구현을 해보았는데요
리뷰를 부탁드립니다!

2023-02-23 15:58 UTC, ohjoohyung requested changes
안녕하세요 누누!
2단계 미션 재밌게 잘 구현해주셨네요. 👍👍
의존 관계에 대한 부분은 코드에 따로 코멘트 남겼습니다.
이외에도 코멘트 남긴게 있으니 한번 확인 부탁드릴게요.
수고하셨습니다!
그리고 질문에 대한 답변입니다.
- 테스트를 어디까지 작성하면 좋을지도 궁금합니다
  - 이게 지금 단계에서 정말 고민이 되는 부분일거예요. 의존 관계가 얽히다보면 그저 패스만 해주는 부분에서도 테스트를 작성하는게 맞나? 싶을 때가 있으니까요. 
  결론부터 말씀드리면 지금은 최대한 작성해보시길 추천드립니다. 그리고 왜 작성하는게 좋을지에 대해서도 생각해보시면 좋을 것 같아요.
  만약에 요구사항이 변경되어 단순 의존 객체를 호출하는 부분에 다른 비즈니스 로직이 추가된다면? 테스트가 미리 작성되어 있다면 이걸 체크할 수 있지 않을까? 이런 점들을 생각해볼 수 있지 않을까요~?

2023-02-23 15:58 UTC, ohjoohyung commented on src/main/java/ladder/domain/Rows.java
> +            throw new IllegalArgumentException("높이는 " + MINIMUM_HEIGHT + "보다 커댜 합니다");
```suggestion
            throw new IllegalArgumentException("높이는 " + MINIMUM_HEIGHT + "보다 커야 합니다");
```
👍

2023-02-23 15:58 UTC, ohjoohyung commented on src/test/java/ladder/domain/PlayersTest.java
> +        ;
```suggestion
        assertThatThrownBy(() -> new Players(null))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("이름이 null 입니다");
```
👍

2023-02-23 15:58 UTC, ohjoohyung commented on src/main/java/ladder/controller/LadderController.java
> +    private Rows inputLines(Players players) {
inputRows가 맞지 않을까요!

2023-02-23 15:58 UTC, ohjoohyung commented on src/main/java/ladder/controller/LadderController.java
> +        if (targetPlayerName.equals(ALL_PLAYER)) {
```suggestion
        if (ALL_PLAYER.equals(targetPlayerName)) {
```
이렇게 비교하면 null pointer exception을 방지할 수 있습니다ㅎㅎ

2023-02-23 15:58 UTC, ohjoohyung commented on src/main/java/ladder/controller/LadderController.java
>      }
지금 runnable.run()에서는 printResult 메서드가 수행되는데 이 메서드에서 예외가 발생하면 메시지와 함께 프로그램이 종료됩니다.
의도하신걸까요? 다른 입력 값 받는 부분은 전부 retry 처리를 해주셨길래 여쭤봅니다

2023-02-23 15:58 UTC, ohjoohyung commented on src/main/java/ladder/domain/ItemName.java
> +
```suggestion

```
👍

2023-02-23 15:58 UTC, ohjoohyung commented on src/main/java/ladder/domain/Items.java
> +        }
생성자에서 너무 많은 것을 해주고 있다는 생각이 드네요?
itemNames는 split한 상태로 받아도 괜찮지 않을까요?

2023-02-23 15:58 UTC, ohjoohyung commented on src/main/java/ladder/domain/LadderGame.java
> +    }
List<List<String>>으로 반환하도록 구현하신 이유가 있으실까요? 🤔
다른 자료구조는 없을까요?

2023-02-23 15:58 UTC, ohjoohyung commented on src/main/java/ladder/domain/LadderGame.java
> +    }
구현하기 나름이겠지만 rows가 players를 꼭 알아야 할 이유가 있을까요? 🤔
단순히 인덱스 (누누가 구현한 미션에서는 Position) 로도 충분히 사다리 타기를 수행할 수 있지 않을까요?

2023-02-23 15:58 UTC, ohjoohyung commented on src/main/java/ladder/domain/PlayerName.java
> +        }
사람 이름을 all로 입력했을 때를 대비하셨군요 👍

2023-02-23 15:58 UTC, ohjoohyung commented on src/main/java/ladder/domain/Players.java
> +        validatePlayerCount();
여기도 위 Items 피드백과 동일합니다

2023-02-23 15:58 UTC, ohjoohyung commented on src/main/java/ladder/domain/Players.java
> +                .filter(player -> player.getName().equals(playerName))
player의 name을 가져와서 비교하는 것보다 player에게 직접 물어보는 것은 어떨까요?

2023-02-23 15:58 UTC, ohjoohyung commented on src/main/java/ladder/domain/Position.java
> +    }
캐싱을 고려해주셨네요 👍

2023-02-23 15:58 UTC, ohjoohyung commented on src/main/java/ladder/domain/Position.java
> +        }
map.get을 두번 사용하는 것보다 get하고 null 체크를 해주는 방식이면 한번만 사용할 수 있을 것 같은데 어떠신가요?

2023-02-23 15:58 UTC, ohjoohyung commented on src/main/java/ladder/domain/Row.java
> +                .collect(Collectors.toUnmodifiableList());
이 메서드 이름이 toDto가 맞을까요?
그리고 스트림은 연산마다 개행을 해주면 가독성에 도움이 됩니다!

2023-02-23 15:58 UTC, ohjoohyung commented on src/main/java/ladder/view/InputView.java
> +    private static final String NEXT_LINE = System.lineSeparator();
👍👍

2023-02-23 15:58 UTC, ohjoohyung commented on src/main/java/ladder/view/ResultView.java
>      }
<img width="236" alt="스크린샷 2023-02-23 오후 12 09 57" src="https://user-images.githubusercontent.com/62014888/220948911-1fcaad09-6576-4c57-90f9-2724b9d83fed.png">
이렇게 출력되는데 개행이 더 들어간 것 같아요!

2023-02-23 15:58 UTC, ohjoohyung commented on src/test/java/ladder/domain/RowTest.java
> +        assertThat(player.getPosition()).isEqualTo(position.moveLeft());
```java
@Test
void test() {
// given

// when

// then
}
```
give, when, then으로 나눠서 테스트를 작성해주시면 더 깔끔하게 작성할 수 있습니다.
그리고 이렇게 테스트마다 데이터 세팅이 완전히 일치하지 않는 경우는 BeforeEach를 사용하기 보다는 각 테스트의 given 영역에서 세팅해주는게 좋을 것 같아요. 꼭 인스턴스 변수로 선언할 이유도 없고요!

2023-02-23 15:58 UTC, ohjoohyung commented on src/test/java/ladder/domain/StepTest.java
> +    }
비즈니스 로직이 없는 단순 getter에 대한 테스트는 꼭 작성하진 않아도 될 것 같아요!

2023-02-23 15:58 UTC, ohjoohyung commented on src/main/java/ladder/controller/LadderController.java
> +            var result = ladderGame.getAllPlayerNamesWithResultNames();
var을 사용해주셨네요? 사용하신 이유를 알려줄 수 있을까요?

2023-02-24 01:58 UTC, be-student commented on src/main/java/ladder/domain/Rows.java
> +            throw new IllegalArgumentException("높이는 " + MINIMUM_HEIGHT + "보다 커댜 합니다");
감사합니다
테스트에서도 그냥 복사만 했던 것 같요

2023-02-24 02:01 UTC, be-student commented on src/test/java/ladder/domain/PlayersTest.java
> +        ;
이걸 보고서 style 관련된 세팅을 알아봤는데요
혹시 추가로 추천해주실만한 세팅이 있으신가요?

파일 끝에 줄바꿈 관련 세팅
1. Remove traling blank lines at the end of saved files
파일 끝에 줄바꿈이 2번 되는 상황 방지
2. Ensure every saved file ends with a line break
파일 끝에 무조건 줄바꿈이 있도록 하는 설정

3. remove unnecessary semicolon
위와 같은 의미 없는 세미콜론 제거

4. Chained method calls wrap always
stream 사용시 자동 개행 

여기서 추가로 뭔가 더 추천해주실만한 세팅이 있으신지가 궁금합니다

2023-02-24 02:02 UTC, be-student commented on src/main/java/ladder/controller/LadderController.java
> +    private Rows inputLines(Players players) {
감사합니다!

2023-02-24 02:03 UTC, be-student commented on src/main/java/ladder/controller/LadderController.java
> +        if (targetPlayerName.equals(ALL_PLAYER)) {
확실히 있는 부분에 대해서 체크가 가능하기에 안정적으로 검증이 되겠네요 감사합니다

2023-02-24 02:04 UTC, be-student commented on src/main/java/ladder/domain/ItemName.java
> +
감사합니다!

2023-02-24 02:12 UTC, be-student commented on src/main/java/ladder/domain/Row.java
> +                .collect(Collectors.toUnmodifiableList());
앗 바깥에서 getRow()로 수정하고, 여기서 변경하는 것을 까먹었네요 감사합니다

2023-02-24 02:35 UTC, be-student commented on src/main/java/ladder/domain/Position.java
> +        }
아하 그렇게 변경하겠습다

2023-02-24 02:36 UTC, be-student commented on src/main/java/ladder/controller/LadderController.java
>      }
아하... 그렇네요 변경해두겠습니다!

2023-02-24 02:39 UTC, be-student commented on src/main/java/ladder/domain/Items.java
> +        }
저번 리뷰에서 나왔던 것과 비슷한 내용인데요
저번 리뷰어분은 , 를 기준으로 나누는 것 자체도 View 레이어에서 알 필요가 없이, 그냥 null 체크 정도 까지만 하는 것이 좋다고 하셨던 것 같았는데요

항상 고민인 부분이었는데요 바꾸고 비교하니 생성자에 로직이 줄어드는 것이 좋아보이네요
 앞으로 split 정도까지는 view 에서 하도록 하겠습다

2023-02-24 02:52 UTC, be-student commented on src/main/java/ladder/view/ResultView.java
>      }
Next Line 분리하다가 이걸 놓쳤던 것 같네요 감사합니다

2023-02-24 03:13 UTC, be-student commented on src/main/java/ladder/domain/LadderGame.java
> +    }
Map 형태가 조금 더 깔끔해보이긴 한 것 같아요 map 형태로 바꾸겠습다

2023-02-24 03:14 UTC, be-student commented on src/main/java/ladder/domain/LadderGame.java
> +    }
그런 것 같아보이네요 이런 방향으로 변경해보도록 하겠습니다

2023-02-24 03:14 UTC, be-student commented on src/main/java/ladder/domain/Players.java
> +        validatePlayerCount();
여기도 동일하게 InputView 에서 Split 까지는 하도록 변경해보겠습니다

2023-02-24 03:17 UTC, be-student commented on src/main/java/ladder/domain/Players.java
> +                .filter(player -> player.getName().equals(playerName))
그렇네요 그렇게 변경해보도록 하다

2023-02-26 02:48 UTC, be-student commented on src/test/java/ladder/domain/RowTest.java
> +        assertThat(player.getPosition()).isEqualTo(position.moveLeft());
감사합니다!

2023-02-26 02:48 UTC, be-student commented on src/test/java/ladder/domain/StepTest.java
> +    }
아하 그렇군요 빼도록 할게요

2023-02-26 02:49 UTC, be-student commented on src/main/java/ladder/controller/LadderController.java
> +            var result = ladderGame.getAllPlayerNamesWithResultNames();
계속 고민이었어요
저 타입 같은 경우에는 바로 전달만 되기에, 굳이 알아야 할까? 라는 생각이 들었던 것 같습니다
그래서 그냥 var로 했던 것 같아요

2023-02-26 03:13 UTC, be-student commented
안녕하세요 오즈 이렇게 리뷰 요청을 드리게 되어서 먼저 죄송하다는 말을 드려야 할 것 같은데요

저번에 나왔던 구조들을 거의 대부분 변경하게 된 것 같은데요

이렇게 바꿔보게 된 이유는, 생각보다 각 클래스가 가지고 있는 책임이 너무 애매하고, 어떤 부분이 문제인지에 대해서도 잘 감이 안 오는 상황이었습니다
이런 문제들을 해결하기 처음부터 다시 재설계를 하는 과정을 거쳤는데요


- Dto 나, LadderGame 같은 클라이언트와, 도메인이 동시에 알아야 하는 경우에 패키지가 너무 애매하게 느껴집니다. 어디에 두어야 할까요?
- 이런 식으로 구조를 나누어 보는 것도 괜찮은 것 같긴 하지만, 너무 오버엔지니어링인 느낌이 들긴 하는데요 혹시 어떻게 생각하시는지 궁금합니다
- 한 패키지 안에 너무 많은 클래스가 존재하게 되는 것 같은데요 이런 경우에는 어떻게 해야할까요?
  이를 해결하기 위해서 ladder, player, item 같은 패키지를 두고, 관리하려고 했지만, 공통 의존성이 있는 부분이 있어서 하지 못했는데요 어떤 방식으로 패키지를 분리하는 것이 좋을지 궁금합니다
- Item 클래스의 책임이 너무 애매해지는 느낌이 있는데요. 이런 경우에도 이 클래스를 두는 쪽이 좋아보이시나요?
사실상 2개의 클래스를 관리하는 자료구조 느낌이 나는 것 같아서요

2023-02-26 12:47 UTC, ohjoohyung requested changes
안녕하세요 누누!
수정을 많이 해주셨네요. 고민한 흔적이 보입니다 👍
몇가지 코멘트랑 질문에 대한 답변 남겼어요.
이 부분 확인 부탁드릴게요.
수고하셨습니다. 

- Dto 나, LadderGame 같은 클라이언트와, 도메인이 동시에 알아야 하는 경우에 패키지가 너무 애매하게 느껴집니다. 어디에 두어야 할까요?
  - 말씀해주신 클라이언트는 MVC 기준으로 봤을 때 controller라고 보면 될까요, view라고 보면 될까요?
  클라이언트라는 패키지에 controller도 있고 view도 있는 것 같아서요. 
  우선 dto가 만약 view로 전달되는 객체라면 도메인이 dto를 알고 있지 않아도 된다고 봐요. dto로 전환은 도메인이 아닌 다른 영역에서 진행해주는 거죠. 도메인에서 전환을 시켜주면 view랑의 결합도가 높아지게 되지 않을까요?
  LadderGame은 도메인이고 현재 코드로 보았을 때 controller에서만 사용되는 것 같아요. 이는 전혀 문제없는 것을 보여요. controller는 domain, view를 모두 알고 있고 이를 중재하는 역할을 하니까요.
  
- 이런 식으로 구조를 나누어 보는 것도 괜찮은 것 같긴 하지만, 너무 오버엔지니어링인 느낌이 들긴 하는데요 혹시 어떻게 생각하시는지 궁금합니다
  - 누누는 어떤 부분에서 그렇게 느끼셨나요? 제 생각에는 일부 오버 엔지니어링인 부분이 존재하긴 해요. 그런 부분에는 코멘트를 남겼으니 확인 부탁드릴게요.
   
- 한 패키지 안에 너무 많은 클래스가 존재하게 되는 것 같은데요 이런 경우에는 어떻게 해야할까요?
이를 해결하기 위해서 ladder, player, item 같은 패키지를 두고, 관리하려고 했지만, 공통 의존성이 있는 부분이 있어서 하지 못했는데요 어떤 방식으로 패키지를 분리하는 것이 좋을지 궁금합니다
  - 클래스가 점점 더 늘어나일부 관련 있는 도메인끼리 패키지를 만들면 될 것 같아요 (ex Item, ItemName 을 item으로). 공통으로 사용되는 객체의 경우 그 수가 많다면 따로 묶고 아니라면 그냥 두어도 괜찮을 것 같고요. 공통 의존성이 있는 것은 크게 문제가 되진 않을 것 같아요. 다만 양방향으로 의존되어 사이클이 생기는 경우는 최대한 피해야 하는 것이 좋은데 이런 부분은 지금 당장 고민하진 말고 추후에 고민해봐도 좋을 것 같습니다.
  
- Item 클래스의 책임이 너무 애매해지는 느낌이 있는데요. 이런 경우에도 이 클래스를 두는 쪽이 좋아보이시나요?
  - 이런 점을 고민해볼 수 있기 때문에 최대한 원시값이나 문자열을 포장하라는 요구사항이 있는 것 같아요. 저 또한 지금 당장 봤을 때는 Item에서 name을 string으로 들고 있어도 크게 문제 없을 것 같아요. 만약 요구사항이 추가되어 비즈니스 로직이 추가된다면 그때 ItemName을 따로 분리해서 이름에 대한 검증을 ItemName에게 위임할 수 있겠죠. 계속해서 미션을 진행하며 분리하는게 좋을지, 이 역할을 어떤 객체가 맡는게 좋을지를 고민해보셨으면 합니다.

2023-02-26 12:47 UTC, ohjoohyung commented on src/main/java/ladder/client/LadderGameClient.java
> +public class LadderGameClient {
이 클래스는 어떤 역할을 한다고 보면 될까요?
MVC 기준으로 컨트롤러 역할이라고 보면 될까요? 
client라고 패키지명을 지어주셨는데 그 이유를 한번 말씀해주실 수 있을까요? 🤔

2023-02-26 12:47 UTC, ohjoohyung commented on src/main/java/ladder/client/LadderGameClient.java
> +        OutputView.printLadder(ladderGame.getLadderInfo());
OutputView만 static method로 구성한 이유가 있을까요?

2023-02-26 12:47 UTC, ohjoohyung commented on src/main/java/ladder/client/view/InputView.java
> +public class InputView implements AutoCloseable {
Scanner의 경우 파일을 읽거나 한 경우가 아니라 사용자의 입력이라면 닫아줄 필요 없을 것 같아요.
게다가 System.in으로 생성한 Scanner의 경우 close하면 주의할 점도 있는 것 같은데요.
여기 문서 한번 참고해주세요!
https://coderanch.com/wiki/678613/Don-close-Scanner-tied-System

2023-02-26 12:47 UTC, ohjoohyung commented on src/main/java/ladder/domain/Ladder.java
> +        validateMinimumSize(width, height);
width, height에 대한 검증이 이 정적 팩토리 메서드에 있으면 어떤 상황이 발생할 수 있을까요?
다른 정적 팩토리 메서드를 추가한다고 생각하면 거기도 마찬가지로 검증 로직을 넣어야하지 않을까요?
개인적으로 정상적인 객체가 만들어지기 위한 필수 검증은 생성자에 있어야하지 않나 생각합니다.

2023-02-26 12:47 UTC, ohjoohyung commented on src/main/java/ladder/domain/LadderGame.java
> +    private final LadderRepository ladderRepository;
Repository를 사용하신 이유가 궁금합니다. 🤔
Repository가 무엇이라고 생각하시나요?

2023-02-26 12:47 UTC, ohjoohyung commented on src/main/java/ladder/domain/LadderGame.java
> +    public PlayerResultDto calculateResult() {
LadderGame은 도메인인데 view로 보내는 dto랑 결합되어 있으면 어떤 상황이 생길 수 있을까요?

2023-02-26 12:47 UTC, ohjoohyung commented on src/main/java/ladder/domain/Point.java
> +        return connected ? RIGHT : NONE;
> 3항 연산자를 쓰지 않는다.

라는 요구사항도 있습니다. 요구사항 한번 확인 부탁드릴게요. 😄

2023-02-26 12:47 UTC, ohjoohyung commented on src/main/java/ladder/domain/Position.java
> +        validateMinimumIndex(index);
여기도 위 Ladder 피드백하고 같습니다.

2023-02-26 12:47 UTC, ohjoohyung commented on src/main/java/ladder/domain/RowGenerator.java
> +class RowGenerator {
RowGenerator를 만들어 point 리스트에 대한 생성을 분리한 이유가 있을까요?
RowGenerator인데 Row를 생성하는게 아니라 처음 보는 사람이 헷갈릴 수 있을 것 같아요.
그리고 개인적으로 point 리스트는 Row가 가지고 있는 필드 값인데 이러한 생성과 관련된 부분은 Row가 알고 있어도 무방하다고 봐요.
굳이 이렇게 클래스로 분리해 static 메서드로 가지고 있을 필요는 없을 것 같아 말씀드립니다.

2023-02-26 12:47 UTC, ohjoohyung commented on src/test/java/ladder/client/view/InputViewTest.java
> +class InputViewTest {
InputView, OutputView 대한 테스트를 진행해주셨네요 👍
고민을 많이 하셨을 것 같은데요.
다만

> 모든 기능을 TDD로 구현해 단위 테스트가 존재해야 한다. 단, UI(System.out, System.in) 로직은 제외

라는 요구사항이 있어요. 
작성해주시는 것은 좋은데 꼭 작성하진 않으셔도 될 것 같아서 말씀드립니다

2023-02-26 12:47 UTC, ohjoohyung commented on src/test/java/ladder/domain/ItemNameTest.java
> +@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
한글로 테스트명 출력을 위해 이렇게 작성하는 것과
`@DisplayName`을 사용하는 것 중 어떤게 더 사용하기 좋았던 것 같나요?
단순 질문이니 편히 답해주셔도 괜찮습니다ㅎㅎ

2023-02-26 12:47 UTC, ohjoohyung commented on src/test/java/ladder/domain/PointTest.java
> +        assertThat(Point.LEFT.move(Position.valueOf(1))).isEqualTo(Position.valueOf(0));
테스트 전반적으로 말씀드리자면 검증 부분을 작성할 때 메서드 체이닝 부분 (여기선 isEqualTo) 은 개행을 해주는 것이 가독성에 도움이 됩니다.

2023-02-26 12:47 UTC, ohjoohyung commented on src/test/java/ladder/domain/RowTest.java
> +    }
아무런 검증이 없는 테스트인 것 같아요.
assertj 메서드로 검증이 있는 테스트 작성 부탁드릴게요.

2023-02-26 12:56 UTC, be-student commented on src/test/java/ladder/domain/PointTest.java
> +        assertThat(Point.LEFT.move(Position.valueOf(1))).isEqualTo(Position.valueOf(0));
아하 저 부분도 개행을 해줘야 되는지 몰랐어요 감사합니다

2023-02-26 13:25 UTC, be-student commented on src/test/java/ladder/domain/ItemNameTest.java
> +@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
저는 현재 작성하는 방향이 좋았는데요 
```Java
@SuppressWarnings({"NonAsciiCharacters", "SpellCheckingInspection"})
@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
```
이 부분을 그냥 자동 완성으로 시켜두면 되다보니 
메서드명을 또 지어야 되는 과정이 없어져서 훨씬 좋았던 것 같아요

2023-02-26 13:34 UTC, be-student commented on src/test/java/ladder/domain/RowTest.java
> +    }
아 맞다 이 부분 질문을 남기고 싶었는데요
예외가 발생하게 되면 테스트가 깨지는 것으로 알고 있는데요 assertThatCode().doesNotThrowAnyException() 메서드를 통해서 검증하는 것이 중요할지가 궁금합니다
메서드 명으로 예외가 발생하지 않는다는 부분이 있고, 실제로 어디서 깨졌는지, displayName으로 확인할 수 있어보여서요

2023-02-26 13:35 UTC, be-student commented on src/test/java/ladder/client/view/InputViewTest.java
> +class InputViewTest {
저번에도 리팩토링을 거치다보니, 개행을 빼먹었던 부분이 기억에 남더라고요 그때 이후에 view 에서 출력하는 메시지들도 검증해주면 좋겠다는 생각을 하게 되었어요
감사합니다!

2023-02-26 13:36 UTC, be-student commented on src/main/java/ladder/domain/Point.java
> +        return connected ? RIGHT : NONE;
으악... 진짜 전혀 상상도 못 했어요 너무 습관처럼 작성했던 것 같네요 수정했습니다!

2023-02-26 13:45 UTC, be-student commented on src/main/java/ladder/client/LadderGameClient.java
> +        OutputView.printLadder(ladderGame.getLadderInfo());
개행을 까먹었던 것 같은 부분을 막기 위해서 view 에 대한 테스트 코드도 작성하려고 했었는데요, InputView 의 경우에는, Scanner 테스트마다 변경되어야 되기에, Scanner를 생성자를 통해서 받도록 하였는데요. 그러다보니 static으로 작성할 이유가 없었던 것 같고요
OutputView 에 대해서는 이와 같은 부분이 없어서, static을 그대로 유지했었는데요
확실히 전체적인 통일성을 고려했을 때, OutputView 에도 static을 제거하는 방향으로 변경해보겠습니다

2023-02-26 13:55 UTC, be-student commented on src/main/java/ladder/client/LadderGameClient.java
> +public class LadderGameClient {
처음 생각했던 구조는
```mermaid
graph TD
server --> domain
server --> repository
client --> view
common --> LadderInfoDto
common --> PlayerResultDto
common --> LadderGameInterface
```
이런 느낌으로 만들어보려고 했었습니다
common 쪽에서는 dto나, 공통으로 의존해야 하는 LadderGame interface를 두려고 했었는데요

그러다가 interface를 두는 이유나, common 패키지가 존재해야 한다는 부분이 너무 과도하게 느껴졌습니다

2023-02-26 14:11 UTC, be-student commented on src/main/java/ladder/client/view/InputView.java
> +public class InputView implements AutoCloseable {
아하 감사합니다 저런 부분은 진짜 처음 들어봤어요

2023-02-26 14:16 UTC, be-student commented on src/main/java/ladder/domain/RowGenerator.java
> +class RowGenerator {
감사합니다
이 부분에 대해서 고민이 있었는데요 tdd로 작성하다보니 생겼던 부분인 것 같은데요
생성하는 과정에서 tdd 사이클을 지키다보면 생성시키는 로직에 대한 테스트가 있어야 하고, 하지만 내부에 대한 데이터는 아직 getter가 없기에 가져올 방법이 없어서 외부로 분리한 결과가 나왔던 것 같습니다
이런 부분 같은 경우에 tdd 사이클을 지키면서, 진행할 방법이 있나요?
그냥 범위에 따라 예외가 발생하는지 여부만 검증하면 될까요?

2023-02-26 14:18 UTC, be-student commented on src/main/java/ladder/domain/Ladder.java
> +        validateMinimumSize(width, height);
검증 로직에 대한 부분을 생각해보면, 사실상 정적 팩토리 메서드는 아무 기능없이 그냥 호출해주는 방향으로 바뀌는 부분이 맞겠네요
생성자에서 너무 많은 역할을 하는 것 같아서 이렇게 분리하였는데요 그렇다면 정적 팩토리 메서드를 사용하는 확실한 이유가 없어보이기도 하네요 그런 방식으로 변경해보겠습니다

2023-02-26 14:19 UTC, be-student commented on src/main/java/ladder/domain/LadderGame.java
> +    public PlayerResultDto calculateResult() {
view와 직접적으로 결합하고 있네요 데이터 타입이 사다리의 다리만 받고 싶을 경우에는 같이 변경되는 문제가 그대로 발생하겠네요 수정해보겠습니다!

2023-02-26 14:21 UTC, be-student commented on src/main/java/ladder/domain/Position.java
> +        validateMinimumIndex(index);
여기는 위의 Ladder와 다르게 캐싱을 해야되기때문에, 정적팩토리는 유지하고, 검증 작업은 전부 생성자에서 처리하도록 바꿔보도록 하겠습니다! 좋은 피드백 감사합니다

2023-02-26 14:45 UTC, be-student commented on src/main/java/ladder/domain/LadderGame.java
> +    private final LadderRepository ladderRepository;
[처음 생각했던 구조 ](https://github.com/woowacourse/java-ladder/pull/167#discussion_r1118090462)에서 봤을 때
처음에 server와, client 가 있을 때, 각각의 생명주기와 별개로 데이터들을 더 오래 유지하는 것이 목적이었는데요
다시 호출해도, 처음 client 가 호출했던 데이터들을 계속 가지고 있는 느낌으로 사용해보고 싶었습니다

여기서는 잘 나타나지 않았던 것 같지만
Repository는 기존 어플리케이션과 다른 생명주기를 가진 데이터를 관리하는 계층이라고 생각합니다

이 부분이 개인적으로 가장 오버엔지니어링이라고 느껴졌던 부분 같았습니다
Repository 를 사용하지 않았다면 Ladder, Players, Items 을 인스턴스 변수로 관리했었을 것 같습니다

2023-02-27 08:51 UTC, be-student commented
안녕하세요 오즈

피드백 주신 부분들은 최대한 반영해보려고 했는데요

몇가지 궁금한 점이 아직 남아 있어서 이렇게 여쭤보게 되었습니다
1. 처음 생각했던 패키지 구조를 아래 pr을 통해서 확인하실 수 있을 것 같은데요
https://github.com/be-student/java-ladder/pull/1
혹시 이런 구조는 어떻게 생각하시는지 궁금합니다
마지막 커밋에서 패키지 구조만을 변경했어요

2. 코멘트에도 남아있겠지만, RowGenerator 같은 클래스가 없는 상태로, 아직 getter를 둘지 말지 여부가 정해지지 않았다면 tdd 사이클에서 어떻게 해야할 것인지가 궁금합니다

3. 아무 예외가 발생하지 않았을 경우 그냥 통과하는 테스트 케이스 같은 경우에, 여기서 검증하는 코드가 필요한지가 궁금합니다. 메서드 명에서 충분하게 예외_발생_안함 이라는 느낌의 내용을 넣었을 때를 기준으로 생각한다면요

2023-03-01 08:15 UTC, ohjoohyung approved these changes
안녕하세요 누누!
피드백 잘 반영해주셨고 미션 고생하셨습니다.
질문에 대한 답변 코멘트로 남길테니 한번 확인해주세요.
다음 미션도 화이팅입니다!

2023-03-01 08:15 UTC, ohjoohyung commented on src/main/java/ladder/domain/LadderGameController.java
> +public class LadderGameController implements LadderGame {
도메인 객체라고 생각되는데 Controller가 붙여져있네요.
Controller를 붙여주신 이유가 있을까요? 🤔

2023-03-01 08:15 UTC, ohjoohyung commented on src/main/java/ladder/domain/Row.java
>          }
else를 사용하지 않는 것도 요구사항입니다!

2023-03-01 08:17 UTC, ohjoohyung commented on src/main/java/ladder/client/LadderGameClient.java
> +public class LadderGameClient {
우선 LadderGame에 대한 도메인 스펙을 Interface로 정의한 것은 크게 문제될 것은 없다고 생각하나 이걸 common 패키지에 둘 필요는 없다고 생각해요. dto도 마찬가지로 common이라는 패키지에 둘 필요는 없고요.
common이라는 패키지는 설명이 없으면 어떤 것들이 모여있는지 모호해지는 네이밍이라고 생각이 들어요.

그리고 컨트롤러를 꼭 붙일 필요는 없겠죠. 다만 MVC 패턴으로 미션을 구현해주셨고 일반적으로 Controller라고 사용하고 있기에 주석이나 다른 방법으로 설명을 해주어야 한다고 생각해요. 지금 미션은 혼자하니 괜찮겠지만 다른 개발자랑 같이 작업을 한다고 생각했을 때 충분히 헷갈릴 수 있을 것 같아서요.

2023-03-01 08:18 UTC, ohjoohyung commented on src/main/java/ladder/domain/LadderGame.java
> +    private final LadderRepository ladderRepository;
네네. repository를 사용하지 않고 LadderGame에서 인스턴스 변수로 관리해도 무방할 것 같아요.
지금 미션 요구사항으로 봤을 때 데이터 생명주기를 따로 관리해야할 이유가 있을까 싶기도 합니다.

2023-03-01 08:18 UTC, ohjoohyung commented on src/main/java/ladder/domain/RowGenerator.java
> +class RowGenerator {
질문해주신 의도가 `tdd로 테스트하면서 생성한 객체에 대한 검증을 할 때 getter가 없는 경우 어떤 방법으로 테스트할 수 있을까?`
에 대한 것이 맞을까요?
그게 맞다면 저는 getter를 추가해도 무방하겠다 싶으면 추가해서 검증할 것 같아요.
최대한 getter 추가를 뒤로 미루는 것은 맞지만 판단했을 때 getter가 있어도 큰 이슈가 없겠다 싶으면 추가하는거죠. 대신 이 경우는 Row의  point 리스트에 데이터 추가를 방지하기 위해 방어적 복사를 하여 데이터를 반환해주고요.
만약 테스트할 객체가 값 객체라면 getter를 사용하기 보다는 객체 자체를 비교하는 방법으로 테스트를 해볼 거 같네요.

2023-03-01 08:19 UTC, ohjoohyung commented on src/test/java/ladder/domain/RowTest.java
> +    }
저는 개인적으로 테스트에서 아무런 검증을 하지 않으면 의미가 사라지지 않을까라는 생각을 하고 있어요.
예외가 발생하면 발생한다, 발생하지 않으면 발생하지 않고 적절하게 값을 가지고 있는지를 테스트 해주겠죠.
doesNotThrowAnyException() 보다는 생성된 Row의 필드를 검증하는 방향으로 테스트를 작성하는게 좋을 것 같아요.

그리고 말씀해주신 것처럼 doesNotThrowAnyException()를 사용하지 않아도 예외 발생하면 한번에 파악을 할 순 있어요.
대신 doesNotThrowAnyException()를 사용하면 예외가 발생할 때 조금 더 명시적인 예외 메시지가 나와 왜 테스트가 깨졌는지를 파악하기 쉬울 것 같아요.

2023-03-01 08:26 UTC, ohjoohyung commented
질문에 대한 답변 드릴게요.

1. 우선 위 코드에도 코멘트 남겼는데 LadderGameInterface는 LadderGame 도메인에 대한 스펙이 있는 인터페이스라고 생각되는데 common이라는 패키지에 있을 이유가 없다고 생각해요. 또한 정말로 common 패키지를 만들 필요가 있을까에 대해서도 생각해보셨으면 해요. 
position 하나만 있는데 굳이 만들 필요는 없지 않을까 라는 생각이 들기도 합니다. 
그리고 common이라는 네이밍 자체가 되게 모호한 느낌이다 보니 다른 개발자 입장에서 이해하기 힘들 수도 있고요.
3. 코드에 코멘트 남겼으니 확인 부탁드릴게요.
4. 위와 동일합니다.
5. 아뇨. 필드 값을 넘겨주는 것 자체는 결합이 높진 않다고 봅니다. 단순 도메인에서 값을 넘겨주는 것일뿐 view의 요구사항이 변경된다고 domain에도 크게 영향을 받지 않을 거라고 생각이 들어서요.
6. 정확히 어떤 부분을 말씀해주시는지 모르겠지만, domain에서 view로 데이터를 넘길 때 말씀해주시는 걸까요? 🤔
지금은 domain, view 간의 결합도가 생기면 어떤 상황이 발생할지 정도만 알고 넘어가고 굳이 dto로 바꿔줄 필요는 없다고 생각합니다.

미션을 정말 잘 구현해주셨는데 개인적인 생각으로 현재 미션 요구사항, 규모에 비해 많은 부분을 생각해주신거지 않나 싶어요. 
레벨1 미션 동안은 서버, 클라이언트, repository 등에 대해 깊이 생각하지 않아도 되며, 객체지향, TDD, 클린코드, 기본적인 MVC 패턴 등에 집중을 하며 공부해주셔도 충분하다고 생각됩니다. 
레벨2로 넘어가면 충분히 이런 부분에 대해 생각하실 기회가 있을테니 그때 고민하셔도 괜찮다고 생각해요. 😄

2023-03-01 08:26 UTC, merged

2023-03-01 08:29 UTC, be-student commented on src/main/java/ladder/client/LadderGameClient.java
> +public class LadderGameClient {
정말 감사합니다

2023-03-01 08:31 UTC, be-student commented on src/main/java/ladder/domain/LadderGame.java
> +    private final LadderRepository ladderRepository;
좋은 방향으로 피드백을 듣고 바꾸게 된 것 같네요 감사합니다!

2023-03-01 08:31 UTC, be-student commented on src/main/java/ladder/domain/RowGenerator.java
> +class RowGenerator {
감사합니다 고민이 하나 줄어든 것 같아요

2023-03-01 08:32 UTC, be-student commented on src/test/java/ladder/domain/RowTest.java
> +    }
아하 메시지를 직접 본다는 차이는 분명하게 있겠네요 그 부분까지는 몰랐던 것 같아요 감사합니다

2023-03-01 08:32 UTC, be-student commented on src/main/java/ladder/domain/Row.java
>          }
헉... 자꾸 놓치는 부분이 생기네요 감사합니다

2023-03-01 08:34 UTC, be-student commented on src/main/java/ladder/domain/LadderGameController.java
> +public class LadderGameController implements LadderGame {
확실히 mvc 의 controller 가 너무 강력하게 기억에 남았던 것 같아요 습관처럼 붙혔던 것 같네요
controller 로 적으니 오히려 헷갈려서 차라리 이럴 거면 LadderGameImpl 같은 느낌으로 바꾸기만해도 나았겠네요

2023-03-02 15:28 UTC, be-student commented
감사합니다 오즈 진짜 툭하면 엎어와서 진짜 리뷰하시느라 힘드셨을텐데 끝까지 잘 봐주셔서 너무 재밌었어요!
리뷰어가 되어주셔서 감사합니다

2023-03-02 17:13 UTC, ohjoohyung commented
> 감사합니다 오즈 진짜 툭하면 엎어와서 진짜 리뷰하시느라 힘드셨을텐데 끝까지 잘 봐주셔서 너무 재밌었어요! 리뷰어가 되어주셔서 감사합니다

아닙니다. 고민 많이 하고 구현해주신 것 같던데 저도 리뷰하면서 즐거웠습니다 😄
남은 미션도 잘하시길 응원하겠습니다. 화이팅입니다!