[2단계- 사다리 게임 실행] 홍실(홍혁준) 미션 제출합니다.
woowacourse/java-ladder pull request #169
Opened 2023-02-22 06:24 UTC by hong-sile

안녕하세요. 다니 1단계 리뷰 감사했습니다.
1단계 리뷰해주신 부분에 대한 답은 [여기](https://github.com/woowacourse/java-ladder/pull/71#discussion_r1112722599)에 남겨두었어요!!

이번 미션을 진행하면서도 고민한 것이 있어요. 아래에 남겨둘게요.

# 구현 방법

## 사다리 게임 실행 구현 방법
저는 이번 미션에서 중요하게 생각한 건 "유저들의 사다리 게임 실행을 어떻게 구현할까?' 였고, 아래와 같은 방식을 떠올렸습니다.

### Users가 상태(위치)를 갖고 있지만, 사다리 게임 실행 이후에 해당 상태(위치)가 변하지 않는다.
1. 이 방법은 사다리 게임 실행을 n번해도 동일한 결과를 얻을 수 있습니다.(n번 사다리 게임을 실행시켜도 됩니다.)
2. 현 사다리 게임에서 결과를 n번 출력하기 때문에 다음과 같은 방식으로 구현할 수 있습니다.
    1. 사다리 게임 실행 로직을 돌린 후 반환 된 결과를 어딘가에 저장하여, 요청할 때마다 저장된 값을 반환한다.
    -> 해당 방식을 이용하면, 사다리 게임 실행 로직은 1번 돌리지만, 저장하기 위해 메모리를 잡아먹습니다.
    2. 결과를 요청할 때마다, 사다리 게임 실행 로직을 돌린다.
    -> 해당 방식을 이용하면, 결과를 저장하기 위해 메모리를 쓰지 않지만, 메서드를 반복적으로 실행하기 때문에, 추가적인 비용이 든다.
3. 위치에 대한 불변성이 유지됩니다.

### Users가 상태(위치)를 갖고 있고, 사다리 게임 실행 이후 해당 상태(위치)를 변화시킨다.
1. 이 방법은 사다리 게임 실행을 단 1회만 해야 합니다. (2번째부턴 Users의 위치가 초기와 동일하지 않기에)
2. 사다리 게임 실행 후, Users의 상태가 실행결과에 맞게 변하였기 때문에, 사다리 게임 실행을 추가적으로 할 필요도, 추가적인 저장공간도 필요하지 않습니다.
3. 위치에 대한 불변성이 깨집니다.

위 두 가지 방법 중 저는 아래 방법(Users의 상태를 변화시키는 방법)을 사용하였습니다.
해당 방법을 선택한 이유 중 가장 큰 이유는 현 코드에서 크게 기능을 추가할 필요가 없기 때문입니다.
현재 프로젝트에서 사다리 게임을 n번 실행시킬 이유도 없고, 생성된 결과만 반복적으로 반환하면 되기에 상태를 변화시키는 2번을 선택하였습니다.

## 상태(위치에 대한 관리)
또 이번 미션에서 가장 중요한 부분은 위치라고 생각했어요. 위치를 이용하여 값을 구하기 때문에 어떻게 관리할지 고민을 하였고 아래와 같은 방법을 떠올렸습니다.

### User(그리고 Prize)내부에 Position 필드 추가
1. User가 상태(위치)에 대한 정보를 가지고 있다.
2. Position 클래스를 정의하여 상태에 대한 정보를 감쌀 수 있다.(원시값 포장)
3. Position 클래스를 정의하였기에, 상품을 저장하는 Prizes에도 해당 값을 이용하여, 좀 더 안정적(?)으로 로직을 짤 수 있다.
(추후 이용하는 메서드들에서 int값이 아닌 position값으로 소통할 수 있다는 의미입니다.)

### Users에서 List형태로 User를 저장하고 있으므로, 순서에 대한 의미가 암묵적으로 포함되어 있다고 판단하여, List의 순서를 이용
1. Users가 상태(위치)에 대한 정보를 가지고 있는다.
2. 따로 위치에 대한 정보를 포장하지 않는다. 단순히 List의 index로만 생각한다.
3. 위치를 포장하는 클래스가 없기 때문에, 실제로 Prizes와 Users가 협력할 때 상태에 대한 정보를 순수한 int값으로 소통한다.

저는 아래 방법을 사용했습니다. 사실 처음에는 위 방식(Position 필드를 추가)하여 사용하는 방식으로 구현하다, Users 또는 Prizes에서 List형식으로 저장하기에 이미 내포되어 있는 값을 정의한다는 느낌이 들어 중간에 Position과 관련된 로직을 전부 날렸습니다.[405666](https://github.com/woowacourse/java-ladder/commit/4056665701fe17909e6b21305ab3466026910bb7)(TDD로 열심히 짠 로직들...) 

List가 순서를 내포하고 있기에 이 값을 이용해서 로직을 짠 건 만족스럽습니다. 하지만, Users와 Prizes가 협력을 할 때 위치에 대한 정보를 int값으로 소통하는게 내심 마음에 들지 않기도 합니다. 
그럼, 단순히 int값을 감싸는 position이라는 클래스를 정의하고, 협력할때만(Users에서 Przies에 메시지를 보낼 때 또는 그 반대) 사용하도록(메서드 반환값 또는 파라미터) 쓰기 위해 객체를 정의해도 될까요? 아니면 이것도 과하게 프로그래밍 하는 것일까요?

## view영역으로 domain을 넘길 때

### domain 객체 형태 그대로 넘긴다.
1. 코드가 간결해진다.
2. 각각의 메서드의 의미가 명확해진다.(파라미터로 해당 메서드가 어떤일을 하는지 명확하게 알 수 있다.)
3. domain이 변화 될 때 view의 코드도 수정해야 한다.
4. 추후 개발자 도구같은 것들로 도메인이 어떤 식으로 구성되어있는지 들킬 위험이있다.(이것도 오버엔지니어링일까요?)

### domain 객체에서 일반적인 자료형(Collection framework, primitive type)들로 변환하여 넘긴다.
1. controller에서 변환을 해야하기에 추가적인 로직이 필요하다.
2. 각각의 메서드의 의미가 불명확해질 수 있다.(파라미터 또는 반환 타입으로 메서드가 하는일에 대해 추정하기 어렵다)
3. domain이 변화되어도 view의 코드를 수정할 필요는 없다.
4. 필요한 값들만 넘기기 때문에, 보안적인 면에서 문제가 생길 여지가 없다.

지금 이 글을 작성하고 다시 코드를 보는데 위 고민점과 별개의 문제를 찾았습니다.
저는 domain에서 view로 결과 값을 Map으로 반환합니다. 하지만 Map의 기능인 put과 get을 사용하지는 않고 있네요. 단순히 두가지의 값을 묶은 형태라는 이유로 Map을 사용하고 있습니다. 
분명 맘에 들지 않습니다. map객체로 사용하고 있지만, map을 단순히 데이터 수송 목적으로만 쓰니까요.
user의 이름과 prize의 이름을 저장하는 result와 같은 클래스를 정의하여 사용할까? 라는 생각도 들긴 합니다.

지금 위에 있는 의문점 두 개를 작성하고, 코드를 보다가 아래 내용에 대한 의문이 또 들어서 떠오른 생각들을 PR 메세지에 추가합니다. 
아마 이거 보내고, List 부가 미션 한 후에 Map 대신 결과 값을 나르는 새로운 객체를 정의할 것 같긴 하네요,
지금 현재 해당 질문에 대한 제 생각은 **최대한 할 수 있으면 일반적인 자료형으로 데이터를 수송하고, 만약 일반적인 자료형들로 데이터를 수송하지 못할 경우, 필요한 데이터만을 갖는 클래스를 정의하여 넘긴다.**입니다.

쓰다보니 정말 메시지가 길어지네요. 이번에도 가감없이, 명확한 답보단 질문으로 답해주시면 감사하겠습니다!!
아 그리고, 리뷰 정말 감사하게 생각하고 있어요!! 많은 도움이 됩니다!!

2023-02-24 18:50 UTC, da-nyee commented
> 사다리 게임 실행 구현 방법

#### Users가 상태(위치)를 갖고 있고, 사다리 게임 실행 이후에 해당 상태(위치)가 변하지 않는 경우

1. 사다리 게임은 초기에 딱 1번만 실행하고, 결과를 캐싱
`사다리 게임 실행 로직을 돌린 후 반환된 결과를 어딘가에 저장`, `저장하기 위해 메모리를 잡아먹는다`라고 적어주셨는데, 요건 캐싱을 의미하네요! 홍실이 생각하신대로 사다리 게임의 결과를 캐싱하면 메모리 공간을 사용하게 돼요. 만약 게임 결과를 조회하는 트래픽이 엄청 많다면, 캐싱은 유용하게 사용될 거예요. 예를 들어, 1) 사다리 게임에 100,000명이 참여했고 2) 각 유저가 자신의 결과가 궁금해서 게임 결과를 최소 1번씩 조회한다고 가정해볼게요. 이때 게임 결과가 캐싱되어 있지 않다면, 사다리 게임을 몇 번 실행해도 결과가 똑같은데, 각 유저의 게임 결과 조회를 위해 사다리 게임을 최소 100,000번 실행해야 돼요. 결국 캐싱 비용보다 사다리 게임 실행 비용이 더 클 것 같아요. 현 애플리케이션은 트래픽이 적어서 캐싱을 적용하는 건 오버 엔지니어링이지만, 애플리케이션이 점차 발전해서 조회 트래픽이 매우 커진다면, 캐싱은 좋은 솔루션 중 하나가 되겠네요.

2. 사다리 게임을 매번 실행
캐싱 비용이 사다리 게임 실행 비용보다 높다면, 요 방식이 비용 절감 측면에서 더 효율적이겠네요.

#### Users가 상태(위치)를 갖고 있고, 사다리 게임 실행 이후에 해당 상태(위치)가 변하는 경우

`현재 프로젝트에서 사다리 게임을 n번 실행시킬 이유도 없고, 생성된 결과를 반복적으로 반환하면 된다`라고 하셨는데, 저도 동일하게 생각해요!
이렇게 만들었을 때, 따로 문제가 될 만한 건 없어 보여요. 미션 요구사항에 맞는 적절한 방법을 선택하셨네요 👍

2023-02-24 18:52 UTC, da-nyee commented
> 사다리 게임 실행 구현 방법

#### Users가 상태(위치)를 갖고 있고, 사다리 게임 실행 이후에 해당 상태(위치)가 변하지 않는 경우

1. 사다리 게임은 초기에 딱 1번만 실행하고, 결과를 캐싱
`사다리 게임 실행 로직을 돌린 후 반환된 결과를 어딘가에 저장`하고 `저장하기 위해 메모리를 잡아먹는다`라고 하셨는데, 요건 캐싱을 의미하네요!
홍실이 적어주신대로 사다리 게임의 결과를 캐싱하면 메모리 공간을 사용하게 돼요.
캐싱은 메모리를 쓰긴 하지만, 게임 결과를 조회하는 트래픽이 엄청 많다면 유용하게 사용될 수 있어요.
예를 들어, 1) 사다리 게임에 100,000명이 참여했고 2) 각 유저가 자신의 결과가 궁금해서 게임 결과를 최소 1번씩 조회한다고 가정해볼게요.
이때 게임 결과가 캐싱되어 있지 않다면, 사다리 게임을 몇 번 실행해도 결과가 똑같은데, 각 유저의 게임 결과 조회를 위해 사다리 게임을 최소 100,000번 실행해야 돼요.
결국 캐싱 비용보다 사다리 게임 실행 비용이 더 커질 수 있어요.
현재 애플리케이션은 트래픽이 적어서 캐싱까지 적용하는 건 오버 엔지니어링이지만, 점차 발전해서 조회 트래픽이 매우 커진다면 캐싱은 좋은 솔루션 중 하나가 될 것 같아요.

2. 사다리 게임을 매번 실행
캐싱 비용이 사다리 게임 실행 비용보다 높다면, 요 방식이 비용 절감 측면에서 더 효율적이겠네요.

#### Users가 상태(위치)를 갖고 있고, 사다리 게임 실행 이후에 해당 상태(위치)가 변하는 경우

`현재 프로젝트에서 사다리 게임을 n번 실행시킬 이유도 없고, 생성된 결과를 반복적으로 반환하면 된다`라고 하셨는데, 저도 동일하게 생각해요!
이렇게 만들었을 때 따로 문제 될 만한 건 없어 보여요.
미션 요구사항에 맞는 적절한 방법을 선택하셨네요 👍

2023-02-24 18:57 UTC, da-nyee commented
> 상태(위치에 대한 관리)

저는 지금 방식도 좋아요! 근데 요번 미션의 요구사항 중에 `모든 원시값과 문자열을 포장한다`가 있어서 공부할 겸 포장해봐도 좋을 것 같아요.

2023-02-24 19:19 UTC, da-nyee commented
> view 영역으로 domain 값을 넘길 때

결론부터 말씀드리자면 view에 domain을 그대로 넘기는 건 지양하면 좋겠어요.
이유는 홍실이 한번 생각해보세요 ㅎㅎ

힌트) MVC 패턴, 아키텍처, 코드 유지보수

2023-02-24 19:22 UTC, da-nyee commented
> 상태(위치에 대한 관리)

저는 지금 방식도 좋아요!
근데 요번 미션의 요구사항 중에 `모든 원시값과 문자열을 포장한다`가 있어서 공부할 겸 포장해봐도 좋을 것 같아요.

2023-02-24 19:22 UTC, da-nyee commented
> view 영역으로 domain 값을 넘길 때

결론부터 말씀드리자면 view에 domain을 그대로 넘기는 건 지양하면 좋겠어요.
이유는 홍실이 한번 생각해보세요 ㅎㅎ

힌트) MVC 패턴, 아키텍처, 코드 유지보수

2023-02-24 20:18 UTC, da-nyee requested changes
안녕하세요 홍실 !
다니입니다 🙌
늦은 리뷰 양해해주셔서 감사합니다 ㅠㅠ

1단계에 이어 2단계도 잘해주셨어요 👍👍👍
코드리뷰 몇 개 남겼는데 확인 부탁드려요!
질문에 대한 답변은 코멘트에 있습니당

혹시 궁금한 점이 있으면 언제든지 코멘트나 슬랙 DM 주세요 🙇‍♀️

2023-02-24 20:18 UTC, da-nyee commented on src/main/java/domain/user/User.java
> +        if (name.equals(Users.ALL_USERS)) {
name이 null이면 어떤 일이 발생할까요?

2023-02-24 20:18 UTC, da-nyee commented on src/main/java/domain/user/Users.java
> +        if (userNames.stream().distinct().count() != userNames.size()) {
stream을 잘 사용하시는군요 👍

2023-02-24 20:18 UTC, da-nyee commented on src/main/java/domain/user/Users.java
> +    public List<String> getUserNames() {
요기도 stream을 활용해보는 건 어떨까요?

힌트) map

2023-02-24 20:18 UTC, da-nyee commented on src/main/java/domain/user/Users.java
> +        if (userName.equals(ALL_USERS)) {
userName이 null이면 어떤 일이 발생할까요?

2023-02-24 20:18 UTC, da-nyee commented on src/main/java/domain/user/Users.java
> +                .findFirst();
findFirst()와 findAny()는 어떤 차이가 있을까요?

2023-02-24 20:18 UTC, da-nyee commented on src/main/java/LadderController.java
> +        while (true) {
지금은 사다리 게임을 강제 종료하지 않는 이상 영원히 안 끝날 것 같아요.
종료 조건을 추가해볼까요?

2023-02-24 20:18 UTC, da-nyee commented on src/main/java/domain/user/Users.java
> +        linkedIndexes.forEach(index -> Collections.swap(users, index, index + 1));
인덱스 기반으로 게임 결과를 구하니까 swap을 사용할 수 있군요?
구현 방식이 재밌네요 ㅎㅎ

2023-02-24 20:18 UTC, da-nyee commented on src/test/java/domain/LadderTest.java
> +    테스트하는 사다리의 형태
주석 👍

2023-02-24 20:18 UTC, da-nyee commented on src/test/java/domain/LadderTest.java
> +        final Users users = new Users(List.of("홍실", "다니", "썬샷"));
ㅋㅋㅋㅋ 저도 게임에 끼워주셨군요

2023-02-24 20:18 UTC, da-nyee commented on src/test/java/domain/UsersTest.java
> +        final Map<String, String> prizeAndUserName = users.getPrizeAndUserName("다니", prizes);
> map 사용

map도 괜찮고, 아니면 홍실 말씀대로 객체를 하나 생성해도 좋겠네요

2023-02-24 20:18 UTC, da-nyee commented on src/test/java/domain/UserTest.java
> +                .hasMessage(ErrorMessage.USER_NAME_BLANK_EXCEPTION.getMessage());
에러 메시지까지 검증 👍

2023-02-24 20:18 UTC, da-nyee commented on src/test/java/techcourse/jcf/mission/SimpleArrayListTest.java
> +        String[] array = {"홍실", "다니", "준팍", "에단", "로지", "애쉬", "디투", "블랙캣", "네오", "왼손"};
곳곳에 다니가 있어서 테스트 보는 재미가 있네요 😌

2023-02-25 11:21 UTC, hong-sile commented on src/main/java/domain/user/Users.java
> +                .findFirst();
findFirst와 findAny 모두 조건에 맞는 하나의 값을 반환한다는 공통점이 있지만,
findFirst는 무조건 순서상 앞의 값을 findAny는 순서에 관계없이 값을 반환한다는 특징이 있어요.

여기서 일치하는 것이 하나 뿐이라 로직상은 전혀 문제가 없지만 findFirst는 findAny+(맨 앞의 순서)라는 의미를 내포하고 있어서, 뜻만 놓고 보면, findAny가 좀 더 적절해보이긴 하네요.

2023-02-25 11:22 UTC, hong-sile commented on src/main/java/domain/user/Users.java
> +        linkedIndexes.forEach(index -> Collections.swap(users, index, index + 1));
핳 원래는 User가 position을 갖고 있고 그 position을 swap하는 방식으로 구현하다가,

구현 도중, index로 가능할 것 같아서 다시 틀었어요. 잘 바꾼 것 같아요.

2023-02-25 12:11 UTC, hong-sile commented on src/main/java/domain/user/User.java
> +        if (name.equals(Users.ALL_USERS)) {
validateName에서 name이 null이면 NPE가 터질 것 같아요.

하지만, 저는 User가 null을 받는 상황이 나오지 않을 것 같아서 null을 체크하지 않았어요.
현재 User는 InputView에서 넘어온 값들로 생성되요.
하지만 현 상태에서 InputView는 콘솔에서 입력을 받고 있는 상황이고, 콘솔에서 입력을 읽을 때 ""와 같은 공백을 반환할지언정, null을 반환하지는 않는 것으로 알고 있어요.
(혹시 ctrl+d와 같은 것이 null을 반환할까 확인해보았지만 그 경우 NoSuchElementException이 발생하여 프로그램이 종료되었어요).

만약에 프로그래머가 `new User(null)`와 같은 코드를 작성한다면, 이 경우는 체크하지 못할 것 같긴 해요.
근데, 그런 케이스를 고려한다면? 모든 코드에서 null체크를 해야 할 것 같다는 생각이 들어요.
굳이 생성자가 아니어도, reference type을 파라미터로 받는 모든 메서드에서 null을 넣을 수 있으니까요.
만약 모든 refernce type을 사용할 때마다 null을 체크한다면 프로그램에 부하가 많이 갈 것 같아요.

결론적으로 저는 제 코드에서 null이 생성되어 넘어갈만한 요소가 없다고 생각하여 null체크를 하지 않았어요.
**만약 null을 반환할지도 모르는 메서드(ex : 외부 API)를 사용한다면 무조건 체크**해야 한다는 것에 대해 동의합니다.
하지만 그렇지 않은 경우에 체크하는 것은 과하다는 느낌이 있어요.

혹시 현 프로그램에서 NPE가 터질만한 요소가 있을까요? null은 항상 조심히 다뤄지는 친구기에, 제가 null이 발생할만한 곳을 찾지 못했나? 싶기도 하네요

2023-02-25 12:14 UTC, hong-sile commented on src/main/java/LadderController.java
> +        while (true) {
저는 ctrl + c와 같은 커맨드로 종료되게 할 생각이었는데, 

명시되지 않은 프로그램 외부 입력에 의해 프로그램의 종료가 결정되는 것은 잘못되었다는 생각이 드네요.
새로운 특정 문자열을 받을 때 종료하는 방법도 있겠지만, 그 특정 문자열이 들어오지 않는다면 프로그램이 계속 살아있을 수도 있기에, 단순하게 실행결과를 5번 입력하면 종료하게 수정하였습니다.

2023-02-25 12:16 UTC, hong-sile commented on src/test/java/domain/UsersTest.java
> +        final Map<String, String> prizeAndUserName = users.getPrizeAndUserName("다니", prizes);
map이 좋지 못하다고 생각하였는데, 리팩터링 하려다보니, map만 한게 또 없네요 ㅎㅎ...
keyset으로 순회하며 map의 데이터를 조회하여, 출력하면 좀 더 의미가 명확하기도 하고요.

새로운 객체를 정의하게 되어도, 크게 별 다르게 바뀌진 않을 것 같아요. map으로 유지할 것 같아요

2023-02-25 12:29 UTC, hong-sile commented on src/main/java/view/OutputView.java
> +        final String prizeName = userNameAndPrizes.values().stream().findFirst().get();
현재 현 코드에서 이 부분이 조금 마음에 걸립니다. optional인데 get을 했으니까요.
하지만 저 메서드가 호출되려면 무조건 userNameAndPrizes의 size가 1이기에, Optional.get()을 사용했다고해서, 
null을 반환할 것 같진 않습니다.

그러나 printResult에서가 아닌 다른 코드에서 호출되는 경우엔 null이 반환 될 수도 있겠죠.
이런 경우에 Optional.isEmpty메서드로 확인을 하거나 orElseThrow로 예외처리를 해야할까요?

2023-02-25 12:34 UTC, hong-sile commented on src/main/java/domain/user/User.java
> +        if (name.equals(Users.ALL_USERS)) {
> validateName에서 name이 null이면 NPE가 터질 것 같아요.
> 
> 하지만, 저는 User가 null을 받는 상황이 나오지 않을 것 같아서 null을 체크하지 않았어요. 현재 User는 InputView에서 넘어온 값들로 생성되요. 하지만 현 상태에서 InputView는 콘솔에서 입력을 받고 있는 상황이고, 콘솔에서 입력을 읽을 때 ""와 같은 공백을 반환할지언정, null을 반환하지는 않는 것으로 알고 있어요.(buffer를 직접적으로 건들지 않으면 null이 발생하지 않는 것으로 알고있어요, 혹시 ctrl+d와 같은 것이 null을 반환할까 확인해보았지만 그 경우 NoSuchElementException이 발생하여 프로그램이 종료되었으니, validateName에 null이 들어가는 경우는 아닌 것 같아요).
> 
> 만약에 프로그래머가 `new User(null)`와 같은 코드를 작성한다면, 이 경우는 체크하지 못할 것 같긴 해요. 근데, 그런 케이스를 고려한다면? 모든 코드에서 null체크를 해야 할 것 같다는 생각이 들어요. 굳이 생성자가 아니어도, reference type을 파라미터로 받는 모든 메서드에서 null을 넣을 수 있으니까요. 만약 모든 refernce type을 사용할 때마다 null을 체크한다면 프로그램에 부하가 많이 갈 것 같아요.
> 
> 결론적으로 저는 제 코드에서 null이 생성되어 넘어갈만한 요소가 없다고 생각하여 null체크를 하지 않았어요. **만약 null을 반환할지도 모르는 메서드(ex : 외부 API)를 사용한다면 무조건 체크**해야 한다는 것에 대해 동의합니다. 하지만 그렇지 않은 경우에 체크하는 것은 과하다는 느낌이 있어요.
> 
> 혹시 현 프로그램에서 NPE가 터질만한 요소가 있을까요? null은 항상 조심히 다뤄지는 친구기에, 제가 null이 발생할만한 곳을 찾지 못했나? 싶기도 하네요

이 질문도 이전 질문과 동일한 답밖에 생각이 나지 않네요. 제가 무언가 놓치는게 있을까요?

2023-02-25 12:35 UTC, hong-sile commented on src/main/java/domain/user/Users.java
> +        if (userName.equals(ALL_USERS)) {
> validateName에서 name이 null이면 NPE가 터질 것 같아요.
> 
> 하지만, 저는 User가 null을 받는 상황이 나오지 않을 것 같아서 null을 체크하지 않았어요. 현재 User는 InputView에서 넘어온 값들로 생성되요. 하지만 현 상태에서 InputView는 콘솔에서 입력을 받고 있는 상황이고, 콘솔에서 입력을 읽을 때 ""와 같은 공백을 반환할지언정, null을 반환하지는 않는 것으로 알고 있어요. (buffer를 직접적으로 건들지 않으면 null이 발생하지 않는 것으로 알고있어요, 혹시 ctrl+d와 같은 것이 null을 반환할까 확인해보았지만 그 경우 NoSuchElementException이 발생하여 프로그램이 종료되었으니, validateName에 null이 들어가는 경우는 아닌 것 같아요).
> 
> 만약에 프로그래머가 `new User(null)`와 같은 코드를 작성한다면, 이 경우는 체크하지 못할 것 같긴 해요. 근데, 그런 케이스를 고려한다면? 모든 코드에서 null체크를 해야 할 것 같다는 생각이 들어요. 굳이 생성자가 아니어도, reference type을 파라미터로 받는 모든 메서드에서 null을 넣을 수 있으니까요. 만약 모든 refernce type을 사용할 때마다 null을 체크한다면 프로그램에 부하가 많이 갈 것 같아요.
> 
> 결론적으로 저는 제 코드에서 null이 생성되어 넘어갈만한 요소가 없다고 생각하여 null체크를 하지 않았어요. **만약 null을 반환할지도 모르는 메서드(ex : 외부 API)를 사용한다면 무조건 체크**해야 한다는 것에 대해 동의합니다. 하지만 그렇지 않은 경우에 체크하는 것은 과하다는 느낌이 있어요.
> 
> 혹시 현 프로그램에서 NPE가 터질만한 요소가 있을까요? null은 항상 조심히 다뤄지는 친구기에, 제가 null이 발생할만한 곳을 찾지 못했나? 싶기도 하네요


이 질문도 이전 질문과 동일한 답밖에 생각이 나지 않네요. 제가 무언가 놓치는게 있을까요?

2023-02-25 12:57 UTC, hong-sile commented
> > 상태(위치에 대한 관리)
> 
> 저는 지금 방식도 좋아요! 근데 요번 미션의 요구사항 중에 `모든 원시값과 문자열을 포장한다`가 있어서 공부할 겸 포장해봐도 좋을 것 같아요.

넵, 위치에 대한 값을 Position으로 포장했습니다. 보다 보니 해당 요구사항 조건에 맞추려면, height나 personCount도 포장해야 할 것 같아 두 값도 포장해봤습니다.

2023-02-25 13:04 UTC, hong-sile commented on src/main/java/view/OutputView.java
> +        final String prizeName = userNameAndPrizes.values().stream().findFirst().get();
라고 썼는데 확실히 글을 쓰고보니까, 체크해주는 게 나을 것 같네요.
제가 아닌 다른 사람이랑 협업할 때 "유저가 하나일때만 써야한다는 의도를 코드만 보고 이해할 수 있나?" 라고 물었을 때 100% 그렇다고 답을 못하겠어요. 중복 체크일 수 있어도, 체크하는게 나을 것 같아요.

2023-02-25 13:06 UTC, hong-sile commented on src/main/java/view/OutputView.java
> +    public void printLadders(final List<String> renderedLadder) {
> > view 영역으로 domain 값을 넘길 때
> 
> 결론부터 말씀드리자면 view에 domain을 그대로 넘기는 건 지양하면 좋겠어요. 이유는 홍실이 한번 생각해보세요 ㅎㅎ
> 
> 힌트) MVC 패턴, 아키텍처, 코드 유지보수

지금은 간단하지만, 기본적으로 domain 객체는 복잡하기 때문에, view가 해당 객체를 가지고 출력을 하려고 하면, view의 코드가 더 복잡해지는 일이 일어날 것 같네요
그리고 mvc패턴에서는 view에서 domain에 의존해도 된다고는 하지만, 의존성이 존재하면 하나를 변경할 시 다른 하나도 영향을 받기 때문에 좋지 못한 것 같아요.

원래 outputView에서 List<Line>을 받고, 이를 string형식으로 변환하여 출력하였는데,
controller에서 변환시켜, 넘겨주는 방식으로 수정했습니다. 이게 더 나은 것 같아요.

2023-02-27 06:00 UTC, hong-sile commented on src/main/java/domain/user/User.java
> +        if (name.equals(Users.ALL_USERS)) {
아... Users.ALL_USERS.equals(name)을 의미하셨던 거군요...(맞나요?)

질문의도가 null체크인줄 알고, 코멘트를 남겼는데, 

Users.ALL_USERS.equals(name) 은 name이 null이어도 false
name.equals(Users.ALL_USERS) 은 name이 null이면 npe

새로운 걸 배워갑니다..

2023-02-27 06:00 UTC, hong-sile commented on src/main/java/domain/user/Users.java
> +        if (userName.equals(ALL_USERS)) {
> 아... Users.ALL_USERS.equals(name)을 의미하셨던 거군요...(맞나요?)
> 
> 질문의도가 null체크인줄 알고, 코멘트를 남겼는데,
> 
> Users.ALL_USERS.equals(name) 은 name이 null이어도 false name.equals(Users.ALL_USERS) 은 name이 null이면 npe
> 
> 새로운 걸 배워갑니다..

이 내용이 맞나요?

2023-02-27 13:06 UTC, hong-sile commented on src/main/java/domain/user/Users.java
> +                .findFirst();
추가적으로 최근에 stream을 학습하다가 parallelStream에 대해서도 알게 되었어요.

단일 스레드에선 두 개 모두 동일한 결과를 반환하겠지만,
멀티 스레드에서는 findFirst와 findAny의 결과가 달라질 수도 있어요(조건에 맞는 값이 두 가지 이상이라면)
그 상황에서는 확실히 findAny가 더 빠를 것 같아요.

2023-02-27 17:36 UTC, da-nyee commented on src/main/java/domain/user/User.java
> +        if (name.equals(Users.ALL_USERS)) {
> 아... Users.ALL_USERS.equals(name)을 의미하셨던 거군요...(맞나요?)

맞아요 ㅎㅎ
현재는 콘솔 프로그램이라 홍실 말씀대로 name에 null이 들어갈 일이 없을 것 같긴 한데,
평소에 안전하게 코딩하는 습관을 길러두면 좋으니까 남긴 코멘트였어요!
동등 비교할 때 순서를 조금만 주의해서 작성하면 불필요한 NPE를 방지할 수 있어요.

2023-02-27 17:41 UTC, da-nyee commented on src/main/java/domain/user/Users.java
> +        if (userName.equals(ALL_USERS)) {
넵 ㅎㅎ

2023-02-27 17:52 UTC, da-nyee commented on src/main/java/domain/user/Users.java
> +                .findFirst();
제대로 공부하셨군요 👍👍👍

2023-02-27 17:56 UTC, da-nyee commented on src/main/java/domain/user/Users.java
> +                .findFirst();
정확해요 제대로 공부하셨군요 👍👍👍

2023-02-27 18:44 UTC, da-nyee commented on src/main/java/view/OutputView.java
> +        final String prizeName = userNameAndPrizes.values().stream().findFirst().get();
오 저는 orElseThrow()로 예외 처리를 했으면 좋겠어요.
지금은 printOneUsersPrize()가 printResult()에서만 쓰이지만, 나중에 요구사항이 변경되거나 했을 때 다른 곳에서도 쓰일 수 있어요.
이때 userNameAndPrize의 사이즈가 0이 될 수도 있고, 그럼 findFirst().get()이 Optional.empty().get()이 되어서 홍실의 의도대로 코드가 작동하지 않을 수 있어요.
요런 상황을 사전에 예방하기 위해 Optional.get()보다 Optional.orElseThrow()로 예외를 던지면 좋을 것 같아요 ㅎㅎ

2023-02-27 18:46 UTC, da-nyee commented on src/main/java/view/OutputView.java
> +        final String prizeName = userNameAndPrizes.values().stream().findFirst().get();
오 저는 orElseThrow()로 예외 처리를 했으면 좋겠어요.
지금은 printOneUsersPrize()가 printResult()에서만 쓰이지만, (예를 들어) 나중에 요구사항이 변경되었을 때 다른 곳에서도 쓰일 수 있어요.
이때 userNameAndPrize의 사이즈가 0이 될 수도 있고, 그럼 findFirst().get()이 Optional.empty().get()이 되어서 홍실의 의도대로 코드가 작동하지 않을 수 있어요.
요런 상황을 사전에 예방하기 위해 Optional.get()보다 Optional.orElseThrow()로 예외를 던지면 좋을 것 같아요 ㅎㅎ

2023-02-27 18:47 UTC, da-nyee commented on src/main/java/view/OutputView.java
> +        final String prizeName = userNameAndPrizes.values().stream().findFirst().get();
오 저는 orElseThrow()로 예외 처리를 했으면 좋겠어요.
지금은 printOneUsersPrize()가 printResult()에서만 쓰이지만, (예를 들어) 나중에 요구사항이 변경되었을 때 다른 곳에서도 쓰일 수 있어요. 이때 userNameAndPrize의 사이즈가 0이 될 수도 있고, 그럼 findFirst().get()이 Optional.empty().get()이 되어서 홍실의 의도대로 코드가 작동하지 않을 수 있어요.
요런 상황을 사전에 예방하기 위해 Optional.get()보다 Optional.orElseThrow()로 예외를 던지면 좋을 것 같아요 ㅎㅎ

2023-02-27 18:47 UTC, da-nyee commented on src/main/java/view/OutputView.java
> +        final String prizeName = userNameAndPrizes.values().stream().findFirst().get();
오 저는 orElseThrow()로 예외 처리를 했으면 좋겠어요.
지금은 printOneUsersPrize()가 printResult()에서만 쓰이지만, (예를 들어) 나중에 요구사항이 변경되었을 때 다른 곳에서도 쓰일 수 있어요.
이때 userNameAndPrize의 사이즈가 0이 될 수도 있고, 그럼 findFirst().get()이 Optional.empty().get()이 되어서 홍실의 의도대로 코드가 작동하지 않을 수 있어요.
이런 상황을 사전에 예방하기 위해 Optional.get()보다 Optional.orElseThrow()로 예외를 던지면 좋을 것 같아요 ㅎㅎ

2023-02-27 18:48 UTC, da-nyee commented on src/main/java/view/OutputView.java
> +        final String prizeName = userNameAndPrizes.values().stream().findFirst().get();
오 저는 orElseThrow()로 예외 처리를 했으면 좋겠어요.
지금은 printOneUsersPrize()가 printResult()에서만 쓰이지만, (예를 들어) 나중에 요구사항이 변경되었을 때 다른 곳에서도 쓰일 수 있어요. 이때 userNameAndPrize의 사이즈가 0이 될 수도 있고, 그럼 findFirst().get()이 Optional.empty().get()이 되어서 홍실의 의도대로 코드가 작동하지 않을 수 있어요.
이런 상황을 사전에 예방하기 위해 Optional.get()보다 Optional.orElseThrow()로 예외를 던지면 좋을 것 같아요 ㅎㅎ

2023-02-27 19:08 UTC, da-nyee approved these changes
홍실~~ 다니입니다 🙌

피드백 반영 잘해주셨네요 👍👍👍
질문이랑 의견 공유 많이 해주셔서 리뷰하는 과정이 재밌었어요 ㅎㅎ
일부 코멘트에 답변 남겼는데, 추가 반영은 홍실의 자율에 맡길게요.

이번 미션은 이 정도면 될 것 같아 여기서 머지하겠습니다.
약 2주간 사다리 만드시느라 수고 많으셨어요!
다음 블랙잭도 파이팅하시구, 남은 우테코 생활 알차게 보내세요 🫶

2023-02-27 19:08 UTC, da-nyee commented on src/main/java/LadderController.java
> +        while (tryCount++ < MAX_TRY_COUNT) {
👍

2023-02-27 19:08 UTC, da-nyee commented on src/main/java/LadderController.java
> +        while (tryCount++ < MAX_TRY_COUNT) {
```suggestion
        int tryCount = 0;
        final Users users = generateUsers();
        final Ladder ladder = generateLadder(users);
        final Prizes prizes = generatePrizes(users);
        
        printGenerateLadderResult(ladder, users, prizes);
        
        ladder.playLadderGame(users);
        
        while (tryCount++ < MAX_TRY_COUNT) {
```

메서드 내부의 적절한 개행은 코드 가독성을 높여줍니다 !

2023-02-27 19:08 UTC, merged