[2단계 - 사다리 게임 실행] 루카(백경환) 미션 제출합니다.
woowacourse/java-ladder pull request #182
Opened 2023-02-22 11:56 UTC by dooboocookie

에단, 안녕하세요!!
백엔드 5기 루카입니다😃
지난번 1단계에 이어 `사다리 게임 실행하여 결과를 출력`하는 내용 구현하여 2단계 진행하였습니다.

# 질문

## 1. Players의 역할
- Players는 참여자의 목록을 갖고있는 객체입니다.
- 결과 출력 시, 출력원하는 참여자를 입력받게 됩니다.
- 이를 관리하기 위하여 현재 참여하고 있는 players 객체에서 출력해야하는 `targetPlayers`를 반환하는 기능을 추가하였습니다.
- 근데 여기서 약간의 고민이 있습니다.
  - Players는 참여자들을 저장하는 객체인데, `결과를 확인하고자 하는 Player들`을 Players 객체로 만드는 것이 어떤지 궁금합니다.
  - `참여자들`과 `결과 확인할 참여자들`의 속성이 매우 비슷해서, `A참여자`와 `B참여자`가 둘 다 `Player`의 객체인거처럼 `Players`의 다른 객체로 생각하고, 구현했습니다.
 [코드 링크](https://github.com/dooboocookie/java-ladder/blob/13dcba7adf849962726f36be36cc92f5bf2697f7/src/main/java/ladder/domain/player/Players.java#L44)

## 2. GameResult 정적 팩토리 메소드
- GameResult는 필드로 `Map<Player, Reward>`를 갖습니다.
- GameResult를 생성할때, `참여자들`, `사다리`, `보상들`을 받아서, `어떤 참여자가 어떤 보상`인지 맵에 저장해서 필드로 갖고 있습니다.
- 여기서 여러가지 고민이 있습니다.
  - GameResult를 생성할 때 다른 도메인을 3개나 필요로 한다는 것
  - GameResult를 생성할 때 너무 큰일을 한다는 것
- 위와 같은 고민으로 처음에는 빈 Map을 필드로 생성하고, 나중에 필요한 Player에 대해서만 Reward만 저장한 값을 갖게할까 했는데, 그럼 그 객체가 갖는 값을 나중에 set하는 느낌이 있어서, 원래대로 유지하고 있습니다. 이에 대해서 어떻게 생각하시는지 궁금합니다.
[코드 링크](https://github.com/dooboocookie/java-ladder/blob/13dcba7adf849962726f36be36cc92f5bf2697f7/src/main/java/ladder/domain/reward/GameResult.java#L20)

## 3. Map<Player, Reward>
- GameResult에 결과를 담기 위해 Player를 key로하는 Map을 필드를 갖고 있는데, 이에 대해서 어떻게 생각하시는 지 궁금합니다.
  - Player의 Hashcode, equals를 재정의해서 이러한 형식의 Map을 쓰는 것이 맞을 지 의문이 있습니다.
  - Player의 Name을 받아와서 String을 키 값으로 쓰는 것이 의미가 불분명해 보일까봐 도메인 객체 자체를 키값으로 하는 것으로 결정했습니다.
[코드 링크](https://github.com/dooboocookie/java-ladder/blob/13dcba7adf849962726f36be36cc92f5bf2697f7/src/main/java/ladder/domain/reward/GameResult.java#L14)

## 4. 컨트롤러에 대한 통합테스트
- 앞 전에 조언 주셨던 내용을 토대로 Input과 Result에 대해서 Mock객체를 만들고 그를 통해서 통합테스트를 진행해보았습니다.
- 근데 과정이 약간 복잡해지면서, 통합테스트 또한 내용이 많아지고 복잡해졌습니다.
- 그래서 머리로 구상한 시나리오에 대해서는 테스트를 진행했는데, 테스트가 잘되고 있다는 확신은 들지 않는데, 통합테스트를 잘 짜는 방법에 대해서 조언 부탁 드립니다..😭
[코드 링크](https://github.com/dooboocookie/java-ladder/blob/13dcba7adf849962726f36be36cc92f5bf2697f7/src/test/java/ladder/controller/LadderControllerTest.java#L25)

## 5. Rewards의 검증
- Rewards는 먼저 입력이 되었던 Players에 의해서 갯수가 결정이 됩니다. 그래서 나중에 Rewards를 만들 때 개수가 잘못 입력되면 예외를 발생시켜야 합니다.
- Rewards 내부에서 검증을 하다보니 Controller에서 객체를 만들 때 Players의 요소 개수를 넣어줍니다. 
- 검증에만 필요한 값을 생성 로직에 파라미터로 넘겨주는 것이 옳은 것인지 확신이 들지 않습니다. 이부분에 대해서 조언 부탁 드립니다..
[코드 링크](https://github.com/dooboocookie/java-ladder/blob/13dcba7adf849962726f36be36cc92f5bf2697f7/src/main/java/ladder/domain/reward/Rewards.java#L13)

---
앞 전에 주셨던 리뷰를 토대로 구현해보았는데, 
이번에도 리뷰 부탁드리겠습니다!!

감사합니다🙇‍♂️

2023-02-23 09:59 UTC, Laterality requested changes
안녕하세요 루카, 에단입니다 👋 

2단계도 잘 구현해주셨어요. 이번엔 골치아픈(?) 피드백을 드릴 게 없네요.

컨벤션 위주로 간단한 코멘트 남겨드렸어요. 확인 부탁드려요 :)

## Q&A

1. `Players`의 역할
    정답이 없는 문제네요. `Player`를 중심으로 생각한다면 게임 내에서 참여자가 됐다가 게임이 끝난 뒤에는 결과를 가지면서 수상자가 될 수도 있겠네요. 반면에 "사다리 게임"과 "결과"를 중심으로 생각한다면 사다리 게임 내에 존재하는 참여자와 게임의 결과에 속한 참여자가 나눠질 수도 있고요. 도메인을 어떻게 바라보고 어떤 역할과 책임을 부여할지는 루카의 판단에 맡길게요.
2. `GameResult` 정적 팩토리 메서드
    이상적인 `GameResult`의 생성 방법(코드)은 어때야 한다고 생각하시나요? 만약 지금의 생성자에서 처리를 덜어낸다면 이 처리 로직은 어디로 가는 것이 적절할까요?
4. `Map<Player, Reward>`
    어떤 점에서 의문이 생기셨나요?
5. 컨트롤러에 대한 통합 테스트
    a. 테스트도 코드입니다. 코드가 읽고 유지보수하기 복잡해지고 있다면 어떻게 해야 할까요?
    b. 코드와는 별개로 테스트 케이스를 정리하는 게 필요할 수 있겠네요. 흔히 사용하는 게 "given-when-then" 패턴이니, 여기에 맞춰 시나리오를 정리해보시면 어떨까요?
6. `Rewards`의 검증
    검증에만 사용하는 값을 인자로 넘기고 있다면 잘못된 위치에서 검증하고 있다는 신호일 수도 있어보여요. 2의 답변처럼, 만약 이 검증 로직을 `Rewards` 생성자 외부로 옮긴다면 어디에 두면 좋을까요?

2023-02-23 09:59 UTC, Laterality commented on src/main/java/ladder/controller/LadderController.java
> +    private void endOfGame(Players players, Ladder ladder, Rewards rewards) {
별도의 반환값이 없는 메서드라면 메서드명에는 동사를 사용하면 어떨까요?

2023-02-23 09:59 UTC, Laterality commented on src/main/java/ladder/domain/player/Players.java
> +        return players;
내부의 리스트를 그대로 반환하면 외부에서 리스트를 변형할 수 있게 되는데, 문제 없을까요?

2023-02-23 09:59 UTC, Laterality commented on src/main/java/ladder/domain/reward/Continue.java
> +package ladder.domain.reward;
이 enum은 도메인에서 필요한 요소일까요?

2023-02-23 09:59 UTC, Laterality commented on src/test/java/ladder/domain/player/NameTest.java
> +        @DisplayName("길이는  1 이상 5 이하일 떄 정상 작동한다. 영어 = 길이 1, 한글 = 길이 2")
영어도, 한글도 아닌 문자(e.g. 공백, 특수문자, 제어문자(개행, 탭 등), 이모지)는 어떻게 처리될까요? 😈

2023-02-23 09:59 UTC, Laterality commented on src/test/java/ladder/domain/reward/RewardTest.java
> +        Reward reward =new Reward(inputReward);
코드를 작성한 뒤 포매팅하는 습관을 들이시면 좋아요. 파일을 저장하거나 커밋할 때 포매팅을 수행하는 도구들을 활용해볼 수도 있습니다.

2023-02-23 09:59 UTC, Laterality commented on src/test/java/techcourse/jcf/mission/test/SimpleArrayListTest.java
> +        assertThat(list.size()).isEqualTo(2); // 값이 삭제 됐는지 확인한다.
서로 다른 기능에 대한 테스트는 별개의 테스트 메서드로 분리하면 어떨까요?

2023-02-26 06:53 UTC, dooboocookie commented on src/main/java/ladder/domain/player/Players.java
> +        return players;
리스트의 Player는 불변 객체이므로 , 깊은 복사를 해서 내보내주기보단, `Collections.unmodifiableList()`로 처리 하였습니다. `Rewards`쪽도 마찬가지로 처리하였습니다.

2023-02-26 07:04 UTC, dooboocookie commented on src/test/java/ladder/domain/player/NameTest.java
> +        @DisplayName("길이는  1 이상 5 이하일 떄 정상 작동한다. 영어 = 길이 1, 한글 = 길이 2")
InputView에 영어, 숫자, 공백, 한글 만 받도록 검증 로직 추가하였습니다!!

2023-02-26 07:06 UTC, dooboocookie commented on src/test/java/techcourse/jcf/mission/test/SimpleArrayListTest.java
> +        assertThat(list.size()).isEqualTo(2); // 값이 삭제 됐는지 확인한다.
사실 이 부분은 아직 어떻게 해야될지 모르겠습니다. 
controller에서 외부에서 호출하는 기능은 run()하나이고 그 내부에선 순차적으로 일련의 과정들이 일어납니다. 

만약 플레이어 이름을 받는 과정을 안하고 보상을 받는 과정만 테스트 한다면 예외가 발생할 것입니다.

이미 도메인에 대해서 각각의 단위 테스트는 있으므로 컨트롤러까지 기능별로 나눠야하는지 잘모르겠습니다.

만약 다 나눠야한다면 `이름을 입력 받는 과정`,`보상 목록 입력 받는 과정`,`사다리 타는 과정 `, `...` 이런것들을 controller에서 각각 public 메서드로 다 분리해야될까요?

2023-02-26 07:20 UTC, dooboocookie commented on src/test/java/ladder/domain/reward/RewardTest.java
> +        Reward reward =new Reward(inputReward);
앗... 습관 들이도록 하겠습니다 🙀

2023-02-26 08:11 UTC, dooboocookie commented on src/main/java/ladder/controller/LadderController.java
> +    private void endOfGame(Players players, Ladder ladder, Rewards rewards) {
사실 이부분은 컨트롤러의 run() 메소드가 길어서 분리를 시킨건데, 
컨트롤러 테스트가 복잡해지는 이유와 마찬가지로 run()이라는 메소드에서 이렇게 많은 일을 해도 되는지 모르겠습니다.. 

일단 말씀해주신대로 조회를 하는 메소드가 아니니 동사로 메소드명 바꾸었습니다!!

2023-02-26 08:13 UTC, dooboocookie commented on src/main/java/ladder/domain/reward/Continue.java
> +package ladder.domain.reward;
일단 다시 결과를 조회할지 말지 하는 부분도 어딘가에서 관리가 되어야한다고 생각해서 enum으로 뺐습니다.

하지만, 다시 생각해보니 이는 도메인에 필요한 것이 아닌 프로그램 실행 순서나, 출력에 관련된 부분이라 생각이 들어서 검증은 뷰로 뺴고 계속할지에 대한 판다는 확실 컨트롤러가 하도록 변경하였습니다.

2023-02-26 09:34 UTC, dooboocookie commented
안녕하세요, 에단!!
이번 피드백도 정말 감사합니다!!

> 1. Players의 역할
정답이 없는 문제네요. Player를 중심으로 생각한다면 게임 내에서 참여자가 됐다가 게임이 끝난 뒤에는 결과를 가지면서 수상자가 될 수도 있겠네요. 반면에 "사다리 게임"과 "결과"를 중심으로 생각한다면 사다리 게임 내에 존재하는 참여자와 게임의 결과에 속한 참여자가 나눠질 수도 있고요. 도메인을 어떻게 바라보고 어떤 역할과 책임을 부여할지는 루카의 판단에 맡길게요.

이 내용은 고민을 해봤는데, Players는 애초에 참여자 목록을 생각하고 만든 도메인이라 참여자가 1명이면 안된다든지 하는 검증을 갖게 됩니다.
그래서 결과 출력을 원하는 이름 목록을 받으면 그를 GameResult에 던져줘서 그안에 있는 목록을 가져오도록 했습니다.

> 2. GameResult 정적 팩토리 메서드
  이상적인 GameResult의 생성 방법(코드)은 어때야 한다고 생각하시나요? 만약 지금의 생성자에서 처리를 덜어낸다면 이 처리 로직은 어디로 가는 것이 적절할까요?

>  5. Rewards의 검증
검증에만 사용하는 값을 인자로 넘기고 있다면 잘못된 위치에서 검증하고 있다는 신호일 수도 있어보여요. 2의 답변처럼, 만약 이 검증 로직을 Rewards 생성자 외부로 옮긴다면 어디에 두면 좋을까요?

아직 이 부분에 대해서 확신이 들지 않습니다. 제 생각엔 만약 생성자의 처리를 덜어낸다면, 이 모든 도메인들을 관리하는 `서비스계층`이 있어야될 것 같습니다. 
근데, 제가 최초에 이 프로그램 설계할 때, 규모가 작은 만큼 DTO나 서비스는 없이 진행하려고 설계하였습니다. 현재같은 상황에서 이를 컨트롤러에서 검증하는 것은 아닌 것 같아 일단 그대로 유지하려합니다.

> 3. Map<Player, Reward>
어떤 점에서 의문이 생기셨나요?

Player 객체 자체를 키값으로 쓰는 것이 맞을지에 대한 의문이었습니다. 
`Player : Reward`의 짝을 가진 내용이 List로 있어야될 것 같다는 생각이 들어서였습니다. 
그래서 고민하다가 Player와 Reward를 필드로 갖는 어떤 `PlayerResult`와 같은 클래스를 만들고 `List<PlayerResult>`를 GameResult로 만들까 생각했었습니다.
근데 고민을 하다가 Player도 불변객체고 이름이 고유하다는 확신이 들어서 현재 상태를 유지하기로 했습니다.

> 4. 컨트롤러에 대한 통합 테스트
a. 테스트도 코드입니다. 코드가 읽고 유지보수하기 복잡해지고 있다면 어떻게 해야 할까요?
b. 코드와는 별개로 테스트 케이스를 정리하는 게 필요할 수 있겠네요. 흔히 사용하는 게 "given-when-then" 패턴이니, 여기에 맞춰 시나리오를 정리해보시면 어떨까요?

이 내용에 대해서는 위에 코멘트 주신 내용에 답변을 단 내용처럼 감이 전혀 오지 않습니다.

---

이번엔 추가적으로 Direction을 enum으로 만들어서 이동한 위치를 반환하도록 하는 기능을 추가하였습니다.

이 과정에서 Position이라는 int를 감싸는 래퍼 클래스를 만들어야될지 의문이였습니다. 
Position은 그 자체가 어떠한 책임도 지지 못합니다. 
있다면 0 이하로 떨어질 수 없는 것인데, 그게 Position한테 중요하지 않은 것 같습니다. 
최대값은 플레이어 수에 의해 결정되므로 이에 대한 책임도 Position이 질 수 없습니다.
그리고 Position은 어디에 필드로 존재하는 값도 아니고, 사다리를 타는 기능에 반환값으로 사용 되게 됩니다. 
그래서 따로 래퍼 클래스로 묶지 않았습니다.

---

혹시 에단 실례가 안된다면, 제 `질문 방식`에 대해서 조언을 해주실 수 있을까요?
저는 아직 많이 부족하고 공부해야 합니다.
근데 이 미션을 진행하며 들었던 의문이 대부분 여전히 그대로 유지되고 있는 상황입니다.
제가 어떤 부분에 대해서 질문을 하면 에단은 항상 제 의견을 물으셨고, 저는 그를 고민했고, 제가 이전에 생각했던 선택지 중 좀 더 나아보이는 것을 선택했습니다.
근데 저는 이 때 많이 불안함을 느꼈습니다. 정답이란건 없겠지만 더 나은 선택지가 있을까? 뭘 더 공부해야되는거지? 이런 의문이 계속 들었습니다..
혹시 제가 이번 미션 진행하면서 개선해야되는 태도나 생각이 있었다면 말씀해주시면 정말 감사하겠습니다 😭😭😭😭😭

---
이번에도 긴 글 읽어주셔서 정말 감사합니다!!🙇‍♂️🙇‍♂️🙇‍♂️

2023-02-26 15:16 UTC, Laterality approved these changes
안녕하세요 루카.

까다로운 피드백들이 있었을텐데, 잘 반영해주셨어요 👍 

이번 미션은 이만 머지하도록 할게요.

고생 많으셨습니다 :)

## Q&A

1. 테스트에 관해서는 관련 코멘트를 참고해주세요.
2. `Players`를 맵의 키로 쓸 것인지에 관해서는, "해당 데이터(`Player` - `Reward` 쌍)를 어떤 자료 구조로 만드는 것이 사용하기에 용이한가?"라는 질문으로 요약할 수 있겠네요. 맵과 리스트의 차이점과 둘 중 어느 자료구조가 요구사항에 더 적합한지 고민해보고 선택하시면 되겠어요.
3. 생성자의 처리를 덜어내서 별도의 서비스나 다른 도메인이 필요할 수도 있다면 생성자의 역할을 다시 정의하는 것도 고려해볼 수 있겠네요. 예를 들면 `Rewards`가 `Player`의 목록을 함께 받아 참여자와 결과 간의 연결까지 가지면 어떨까요(e.g. `Rewards.rewardOf(Player)`?
4. 질문 방식에 관해
    a. 코멘트를 많이 남겨드려서 느끼셨겠지만, 저는 대부분의 경우에 정답을 제시하기보다는 계속 질문을 드렸어요. 의도는 두 가지였는데요.
         i. 학습이 주 목적인 상황에서는 단순히 정답을 알고 외우듯이 학습하는 것보다 어떤 것이 정답인지 판별하는 사고를 갖추는 게 더 중요하다고 생각해요.
         ii. 누군가 답을 제시해주기만 해서는 이런 사고가 일어나기 어렵다고 생각했기 때문에 스스로 고민하고 답을 찾도록 질문을 던져드렸어요.
    b. 다만 이렇게 사고하고 학습하는 과정이 일어나기 위해 최소한의 다른 지식이 필요한 경우도 있습니다. 저는 루카에게 어느정도의 "최소한의 지식"이 필요한지 모르기 때문에 제 질문에 불안함이나 답답함을 느끼셨다면 아마 이 이유 때문이었을 거라고 생각해요. 이때가 적당한 힌트와 같은 도움이 필요한 타이밍일 테고요.
    c. 스스로 고민하는 것도 학습에서 중요한 부분이지만 혼자 고민해서 도저지 답을 찾지 못했을 때 적당한 시점에 도움을 요청하는 것도 효과적인 학습에 필요하다고 생각합니다. 코치님들이나 저와 같은 리뷰어를 적극적으로 활용하세요. 해치지 않습니다 :)
    d. 답을 정하는 것에 두려움을 느끼지는 않으셨으면 좋겠어요. 그 답이 옳든 틀리든(더 정확하게는 더 많은 사람 혹은 더 적은 사람이 지지하든) 누군가에게 답을 내린 과정을 충분히 설명할 수 있다면 충분히 의미있다고 생각합니다. 답을 내리면서 놓친 부분이 있다면 거기서 배울 수 있는 기회이기도 하고요.

혹시 이번 미션에서 아직 해소되지 않은 질문들이 있다면 언제든 편하게 DM 주세요 :)

2023-02-26 15:16 UTC, Laterality commented on src/test/java/techcourse/jcf/mission/test/SimpleArrayListTest.java
> +        assertThat(list.size()).isEqualTo(2); // 값이 삭제 됐는지 확인한다.
Note: 테스트에 관해서는 의견이 나뉘는 영역이라 다소 개인적인 생각을 담았어요. 절대적인 기준은 아니니 참고만 해주세요.

이 테스트 부분을 말씀하신 게 맞는지 모르겠지만, 테스트는 과정보다 결과에 집중하시는 것이 좋습니다.

1. 과정에 의존하는 테스트는 깨지기 쉽습니다. 일반적으로 테스트 대상의 수행 "과정"을 검증한다는 것은 클라이언트 역할을 하는 테스트에서 테스트 대상에 대해 요구사항 이상으로 너무 많은 것을 알고 있다는 것을 암시하기도 합니다. 결과적으로는 테스트 대상의 변경에 취약한 테스트가 되기 십상이고요. 여기서 클라이언트가 알고 있어야 할 만한 것은 입출력의 순서와 내용(입력값과 실행 결과) 정도 뿐이겠네요.
2. 종류를 불문하고 테스트 대상에 요구되는 것(=기능)이 있다면 이상적으로는 테스트하는 것이 옳다고 생각해요. 말씀하신 컨트롤러의 예에서는 컨트롤러가 외부에 노출하는 것은 `run`이라는 기능(메서드) 하나뿐이니 테스트 클래스에서는 이 메서드의 실행 결과를 어떻게 검증해야 할 지 고민해봐야겠네요. 반환값이 있다면 이를 확인하거나 의존성으로 주입한 클래스의 객체의 상태를 확인하는 방법 등이 있을 수 있어요. 현재 `LadderControllerTest`와 비슷한 구조라고 볼 수 있겠네요.

테스트, 특히 단위 테스트는 너무 복잡하게 생각하실 필요 없습니다. 테스트 대상이 "주어진 입력(혹은 어떤 조건)에서 의도한 대로 동작하는지를 검증한다"라는 방식으로 접근해보세요. 단, 여기서 "동작"이란 테스트 대상의 내부에서 벌어지는 일이 아닌 외부에서 관측 가능한 현상들(반환값, 의존성의 상태 변경 등)을 의미합니다.

2023-02-26 15:16 UTC, Laterality commented on src/main/java/ladder/controller/LadderController.java
> +    private void endOfGame(Players players, Ladder ladder, Rewards rewards) {
컨트롤러에서 너무 많은 일을 하고 있다는 느낌이 든다면 리팩터링이 필요하다는 신호일 수도 있겠네요.

2023-02-26 15:16 UTC, Laterality commented on src/main/java/ladder/domain/ladder/Ladder.java
> +
메서드 사이는 한 줄 씩만 띄워주세요.

2023-02-26 15:16 UTC, Laterality commented on src/main/java/ladder/domain/reward/GameResult.java
> +    private static final String ALL_TARGET_PLAYERS = "all";
`Name`에도 같은 상수 문자열이 선언돼 있던데, 필요한 중복일까요?

2023-02-26 15:16 UTC, merged