[2단계 - 사다리 게임 실행] 바론(이소민) 미션 제출합니다.
woowacourse/java-ladder pull request #189
Opened 2023-02-22 14:16 UTC by somsom13

안녕하세요, 디디! 😸  우아한 테크코스 5기 바론입니다 ㅎㅎ

1단계에 이어서 2단계를 통해 "사다리 게임의 이동 및 결과 출력 로직" 을 구현하게 되었습니다. 
구현하는 과정에서, 1단계 코드와 변화가 생긴 부분도 있고 새롭게 추가된 기능들도 많이 생겼습니다.

이번 미션에서는 "어떤 객체가 책임을 가져야 하는가" 에 대해서 가장 고민을 많이 했던 것 같습니다. 고민하는 과정에서, 물론 정확한 정답이라는 건 없겠지만 디디의 의견을 여쭤보고 싶은 부분이 몇 가지 있었습니다. (제가 어떤 부분을 고민했고, 어떤 생각을 했는 지를 말씀드리면서 여쭤보는 것이 나을 것이라 생각해서 모두 작성하다 보니 질문이 너무 길어졌습니다. 죄송합니다 😢 )

---

### 인스턴스 변수 판단 기준
사다리 게임을 미션을 진행하면서 게임을 총괄하는 LadderGame 객체를 생성했습니다. 
저는 LadderGame 은 인스턴스 변수로 “하나의 사다리 게임이 구성되기 위해 필요한 필수적인 요소들” 을 가져야 한다고 생각하여 **사다리, 참여자, 그리고 당첨 결과 후보**를 인스턴스 변수로 두었습니다. 
위 3가지 요소 만을 인스턴스 변수로 두어도, 객체 지향 생활 체조 원칙 중 하나인 “인스턴스 변수는 3개 이상 두지 않는다” 라는 조건을 벗어나게 됩니다.

이러한 상황에서 모든 사용자의 이동 결과를 계산한 후에, 이동 결과를 담고 있는 Map을 저장하는 방법에 대해 의문이 들었습니다. 

앞에서 말씀드렸 듯, 제가 지금까지 판단했던 인스턴스 변수의 기준은 “해당 객체가 완성되기 위해서는 반드시 가지고 있어야 하는 필수 요소” 들 입니다. 사다리 게임의 결과 (사람 이름 - 결과 Map) 은 ‘게임을 수행한 후 얻어내는 결과’ 이기 때문에 인스턴스 변수로 가지기 보다는, 연산을 한 후 바로 controller 로 결과 Map 을 반환해 주는 것이 적합하다고 판단했습니다.

하지만 이후 “입력으로 받은 사용자 이름에 따라 결과 값을 뽑아오는 기능”을 LadderGame 에서 수행하게 되면서 결국 controller 가 받은 Map 을 다시 LadderGame 에 파라미터로 넘겨주게 되었습니다. LadderGame 에서 인스턴스 변수로 가지고 있었다면 굳이 다시 넘겨줄 필요가  없었을 것이라는 생각이 들어서 “인스턴스 변수를 결정하는 기준이 무엇인가” 에 대한 의문이 들었습니다. 혹시 디디 만의 기준이 있다면 의견을 여쭤보고 싶습니다! 

---

### 재입력 기능으로 인한 컨트롤러 라인 증가
이번 미션에서는 1단계에서 페어와 함께 논의하며 재입력 기능을 구현했었습니다. 2단계 에서 입력을 받아야 하는 상황이 증가하고, 무엇보다도 기존의 재귀 함수를 while 문 내의 try-catch 로 변경하면서 인덴트를 하나 까지만 사용하는 기준을 따르다 보니 메소드를 계속해서 분리하였습니다. 이에 따라 컨트롤러에서  재입력과 관련된 로직이 증가하면서  컨트롤러의 라인 수가 늘어났습니다. 

메소드의 분리로 인한 코드 라인 증가도 “컨트롤러의 책임이 제대로 분리되지 않은 것” 이라고 생각할 수 있는 것인지 궁금합니다! (재귀와 관련된 로직을 따로 분리하는 것이 더 좋을지 고민이 들었습니다)

---

### 사용자가 "all 또는 특정 사용자의 단독 이름 만으로 결과를 요청할 수 있다" 라는 요구 사항에 부합하는지는 누가 검증해야 하는가

특정 도메인에 종속적인 조건은 해당 도메인을 생성하는 과정에서 검증했으나, 이 요구 사항은 어디에서 검증하는 것이 적합할지 결정하기 쉽지 않았습니다 😢 

제가 생각했던 위치 별 검증은 다음과 같습니다. 

1. controller 에서의 검증
→ 특정 도메인에 종속적이지 않고, “잘못된 값을 입력했을 경우 재입력을 받아야 하는 구조” 이기 때문에 controller 에서 수행하는 것이 적합하다. 
2. LadderGame 에서의 검증
→ “all 또는 한 명의 사용자 이름만 입력 가능하다” 라는 조건은 “구현하는 사다리 게임이 가지는 특정한 조건” 이기 때문에 사다리 게임을 의미하는 객체에서 검증하는 것이 적합하다. 
3. Map<Person, WinningResult> 를 감싸는 일급 컬렉션에서의 검증
→ Map 을 감싸는 일급 컬렉션을 생성하게 된다면, “request (찾을 사용자의 이름) 에 따른 결과를 반환하는 것”도 해당 객체 내의 메소드에서 수행되는 것이 맞다고 생각했습니다. 그래서 이 경우, 찾을 이름을 입력 받았을 때 객체 내에서 우선 해당 이름이 Map 에 있는지, 또는 ‘all’ 인지를 검증한 후 예외를 던지는 방법을 생각했습니다.

이번 구현에서 선택한 방법은 2번 ‘LadderGame 에서의 검증’ 이었습니다. 주어진 조건이 “해당 사다리 게임이 가지는 조건” 이라고 판단했기에 LadderGame 에서 값을 반환함과 동시에 검증이 이루어지도록 구현했습니다. 

여러 크루들과 “적합한 검증 위치 “에 대해 이야기를 나누어 보았지만, 모두 다른 의견을 가지고 있었고 결국 ‘자신의 생각에 맞는 검증 방식을 사용하자’ 라는 결론이 나왔습니다.

물론 정확한 정답은 없겠지만, 이에 대한 디디의 의견을 여쭤보고 싶습니다 :)

---

### 사다리 이동의 책임

2단계의 핵심 기능인 “각 사용자의 사다리 이동 결과 계산”의 책임을 누가 가져야 하는가 에 대한 고민입니다. 2단계 미션을 진행하면서 가장 많은 시간을 투자한 부분인 것 같습니다.

우선, 저는 ‘사용자가 처음의 위치에서 사다리를 통해 도착 위치를 찾는 것’ 은 “사다리 게임이 동작 시켜야 하는 로직” 이라고 생각했습니다. 이에 처음에는 LadderGame 에서 ladder에서 사다리 형태를 가져와 모든 사람의 최종 도착지를 찾는 방식으로 구현했었습니다. 

하지만, LadderGame 의 라인 수가 지나치게 길어지면서 “이 복잡한 모든 과정을 LadderGame 이 혼자 감당하는게 과연 맞는 걸까?” 라는 고민이 생겼습니다. 

이에 LadderGame 이 자신이 인스턴스 변수로 가지고 있는 Ladder 에게 “이 index (처음 시작 위치) 가 최종적으로 도달할 수 있는 위치를 찾아줘!” 라는 메세지를 보내고 Ladder 는 각 Line 에게 “이번 라인에서 이 위치가 갈 수 있는 방향을 찾아줘!” 라는 메세지를 보내도록 하여 LadderGame 은 명령을 내리고 최종 결과를 가공하여 “사용자의 이름 - 당첨 결과” 를 매핑하는 Map 만을 생성하도록 구성하였습니다.

하지만 이 방법은 결국 “사다리라는 하나의 객체에게 사람을 이동 시켜 달라고 요청하게 되는 것” 이 아닌가 싶습니다. 사다리는 현실 세계에 비유했을 때 일종의 사물인데, 과연 사다리에게 사람을 이동 시켜 달라고 이야기 하는 게 맞는 일인지 의문이 듭니다. (최대한 이동 이라는 단어가 아닌, 위치를 찾아 달라 라는 표현을 쓰기 위해 메소드 명을 변경했지만 아직도 이게 좋은 방법인지는 모르겠습니다 ㅎㅎ)

다른 크루들과 이야기를 나누어 보았을 때, 지난 번 미션인 자동차 경주에서 자동차에게 move 명령을 내렸던 것 처럼, 이번 사다리 게임에서도 이동해야 하는 것은 Person (사람 객체) 가 아닌가 라는 의견도 들었습니다. 즉 Person 이 position 값을 가지게 되고, Persons 에게 Ladder 객체를 넘겨 "이 다리를 타고 이동해라!" 라고 명령하게 되는 방식이라고 생각합니다.

디디님은 사다리 이동의 책임을 누가 가지는 것이 맞다고 생각하시는지 의견을 여쭤보고 싶었습니다!

---

긴 질문 읽어주셔서 감사합니다!!  1단계 리뷰 덕분에 팩토리 메소드 사용을 비롯해 새로운 개념을 공부하고, 적용할 수 있었습니다. 2단계 리뷰도 잘 부탁드리겠습니다! 😄 

감사합니다 :)

2023-02-23 15:36 UTC, fucct requested changes
안녕하세요 바론. 

질문주신부분에 대해선 모두 코멘트 달아놓았습니다.
마지막 질문에 대한 제 의견을 드리자면, 모든 역할에 대한 책임은, 그걸 갖고있는 객체의 책임이라고 생각합니다. RacingCar에서 move가 Car의 책임이였던거는, Car가 position을 갖고 있었기 때문이죠.

그렇다면 이번 LadderGame에선 **이동** 이라는게 있을까요? 사다리게임이 진행되는 것은, 어떤 역할인지 고민해보시면 좋을것 같아요.

2023-02-23 15:36 UTC, fucct commented on src/main/java/domain/LadderGame.java
> +    private final WinningEntry winningEntry;
첫번째 질문에 대해 제 의견을 말씀드릴게요.

LadderGame이 인스턴스 변수를 너무 많이 갖는다는건, 하는 일이 너무 많다는 의미일 수 있습니다.
개인적인 생각으로, LadderGame이라는 객체가 만들어진 이유는 아마 사다리 게임 어플리케이션이 하는 일을 모두 모아두는 하나의 단위를 만들고 싶어서 라고 생각합니다. (혹은 이유도 모른채 대부분의 크루들이 만들기 때문일수도 있다고 생각해요.)
LadderGame이 나쁘다는건 아니고, LadderGame이 하는 일이 많다면 Ladder와 Line처럼 클래스를 분리할 수 있습니다. 예를 들면 WinningEntry가 Ladder의 인스턴스 변수로 포함될 수 있겠죠.

2023-02-23 15:36 UTC, fucct commented on src/main/java/domain/LadderGame.java
> +    public Map<String, String> pickResultForTarget(Map<String, String> results, String target) {
"입력으로 받은 사용자 이름에 따라 결과 값을 뽑아오는 기능"이 누구의 책임인지 다시 한번 생각해볼 수 있을것 같아요.  이게 정말 비즈니스의 역할인지, 아니면 우리가 play를 통해 응답한 View 모델을 통해 수행할 수 있는 역할인지요.

2023-02-23 15:36 UTC, fucct commented on src/main/java/controller/LadderController.java
> +        printGameResult(ladderGame.play());
printLadder안에 플레이어, 사다리, 결과후보 까지 다 들어있는것 같아요. 메서드를 명확히 분리해보면 좋을것 같습니다.

2023-02-23 15:36 UTC, fucct commented on src/main/java/controller/LadderController.java
> +        outputView.printLadder(ladderGame.getAllPlayers(), ladderGame.getLadder(), ladderGame.getWinningEntries(),
LadderGame의 결과를 통신할때는 원시값을 주고받는데, 요청값을 통신할때는 도메인 객체를 주고받고 있네요. 도메인 객체 생성의 책임이 Controller일까요?

2023-02-23 15:36 UTC, fucct commented on src/main/java/controller/LadderController.java
> +            List<Person> personNames = Arrays.stream(inputView.requestNames().split(DELIMITER))
질문주신 부분에 대한 답을 드리자면, 재입력 기능이 컨트롤러의 책임일지 고민해보시면 좋을것 같습니다. 물론 재입력 로직때문에 라인이 증가하는게, 책임이 분리되지 않은것과는 별개의 문제라고 생각합니다 :)

2023-02-23 15:36 UTC, fucct commented on src/main/java/domain/LadderGame.java
> +        throw new IllegalArgumentException(ErrorCode.WRONG_RESULT_TARGET.getMessage());
세번째 질문의 답변을 드리자면, 우선 이 기능이 LadderGame의 책임인지 고려해보시면 좋을것 같아요.
 
이미 우리가 play를 통해 내려준 결과를 통해 이 행위를 충분히 할 수 있을것 같아요. 그렇다면 View의 책임이 될 수 있겠죠.
만약 이 책임이 LadderGame의 역할이라고 생각하신다면, LadderGame이 All을 직접 분기를 통해 결과를 출력하기보단, Controller 레벨에서 All or 이름에 대해 서로 다른 메서드를 호출하면 검증기준이 좀 더 잘 보이실 것 같아요.

2023-02-23 15:36 UTC, fucct commented on src/main/java/type/LadderElementInformation.java
> +public enum LadderElementInformation {
이 값이 굳이 enum으로 분리되어야 한지 궁금합니다. 또한 네이밍도 너무 모호합니다. Info, Data 같은 네이밍은 기피하시는게 좋아요.

2023-02-24 08:21 UTC, somsom13 commented on src/main/java/domain/LadderGame.java
> +    private final WinningEntry winningEntry;
안녕하세요 디디!
좋은 리뷰 감사합니다 😄 

말씀해주신 대로 LadderGame 의 인스턴스 변수를 줄일 수 있는 방법에 대해서 고민해보았는데요,
제가 작성한 코드를 살펴보니 LadderGame 에서 하는 일은
1. Persons 와 WinningEntry 를 controller 로 부터 주입 받고 Ladder 를 팩토리 메소드를 통해 사다리 게임 생성과 동시에 제작
2. 각 참여자 별로 당첨 결과를 매핑 
> 사다리에서 이동 가능한 최종 위치를 찾는 일은 ladder 에게 메세지를 보냄으로써 수행,
요청에 따라 단일 결과 또는 전체 결과를 반환하는 작업은 controller 로 옮겼습니다!
3. 인스턴스 변수로 가지고 있는 Persons, WinningEntry, Ladder 의 값을 원시값으로 풀어서 controller 에게 전달

이 3가지 일인 것 같습니다. 

LadderGame이 하는 주요 작업은 2번인 "당첨 결과 매핑" 뿐이어서  Persons, Ladder, WinningEntry 모두 LadderGame 이 인스턴스 변수로 가지고 있을 필요 없이 `play()` 메소드에서 파라미터로 전달 받을 수 있는 값이라는 생각이 들었습니다. 

이 방법으로 변경하게 된다면, 결국 각 도메인들을 controller 에서 생성한 후 지역 변수로 가지고 있게 되기 때문에 https://github.com/woowacourse/java-ladder/pull/189#discussion_r1115840101 
으로 남겨주신 코멘트와 연관되는 내용인 것 같습니다. 

또한, LadderGame이 각 도메인을 인스턴스 변수로 가지고 있지 않게 된다면  LadderGame 에서 사다리의 구조, 참여자, 결과 후보를 원시값으로 풀어서 반환하는 3번 작업이 사라지게 되고

이렇게 될 경우, 도메인을 outputView 에 그대로 넘겨서 view 에서 도메인 내부의 값을 가져와 출력하는 방법과 
각 도메인의 `getter` 를 원시값으로 푼 값을 반환하도록 구성하는 방법 중 하나를 선택할 수 있을 것 같습니다. 하지만 개인적인 생각으로는 도메인을 뷰에 바로 노출시키는 것이 괜찮은지 의문이 듭니다...!

이런 방식으로 인스턴스 변수를 줄이는 것이 괜찮을지, 디디가 생각하셨던 다른 방향이 있는지 여쭤보고 싶습니다. 감사합니다! 😄

2023-02-24 08:29 UTC, somsom13 commented on src/main/java/domain/LadderGame.java
> +    public Map<String, String> pickResultForTarget(Map<String, String> results, String target) {
controller 가 입력을 검증하면서 `play()` 메소드로 받아온 Map을 사용해 입력에 따른 결과를 반환하도록 수정했습니다!

2023-02-24 08:31 UTC, somsom13 commented on src/main/java/controller/LadderController.java
> +        printGameResult(ladderGame.play());
리뷰를 보고 메서드를 분리해봤는데, 
![image](https://user-images.githubusercontent.com/70891072/221130174-27609614-1b44-4f79-ad3c-e9f55ce5971d.png)

위의 사진 처럼 **다리의 길이를 결정하는 값인 bridgeSize** 가 중복되어 전달이 됩니다 ㅠㅠ 

그래도 메서드를 분리하는 것이 더 그 의미가 명확해질까요??

2023-02-24 08:33 UTC, somsom13 commented on src/main/java/controller/LadderController.java
> +        outputView.printLadder(ladderGame.getAllPlayers(), ladderGame.getLadder(), ladderGame.getWinningEntries(),
도메인 객체를 생성하면서 생성자 내부의 `validate` 메소드로 입력값을 함께 검증하게 되기 때문에, 입력을 받는 즉시 도메인을 생성하는 것이 맞다고 생각했습니다!

혹시 디디가 전해주고 싶었던 다른 의미가 있다면, 코멘트 남겨주시면 다시 한 번 생각해 보겠습니다...!!

2023-02-24 08:34 UTC, somsom13 commented on src/main/java/controller/LadderController.java
> +            List<Person> personNames = Arrays.stream(inputView.requestNames().split(DELIMITER))
템플릿 콜백 패턴을 통해서 "중복되는 로직을 핵심 로직에서 분리" 할 수 있다는 사실을 알게 되어서 예외가 발생할 경우, 재입력 받는 로직을 템플릿으로 분리해 보았습니다!

2023-02-24 08:34 UTC, somsom13 commented on src/main/java/domain/LadderGame.java
> +        throw new IllegalArgumentException(ErrorCode.WRONG_RESULT_TARGET.getMessage());
https://github.com/woowacourse/java-ladder/pull/189#discussion_r1115832918 에 남겼던 답변과 동일하게 controller 로 책임을 넘겨보았습니다!

2023-02-24 08:36 UTC, somsom13 commented on src/main/java/type/LadderElementInformation.java
> +public enum LadderElementInformation {
`사다리 게임 참여자의 이름 글자 수가 1글자 ~ 5글자 여야 한다` 라는 조건에 맞춰서 사다리 게임의 결과도 1글자 ~ 5글자 사이여야 한다고 생각해서 해당 조건을 관리하기 위한 enum 을 생성했었습니다.

 enum에 이름을 붙이면서도 '명확한 이름을 붙이기가 어렵다' 라는 생각을 했었는데, enum의 사용 이유가 불명확해서 그랬던게 아닌가 싶습니다ㅎㅎ 
WinningResult 와 Person 의 개별 상수로 처리하였습니다!

2023-02-24 15:16 UTC, somsom13 commented
안녕하세요, 디디! 
2단계에서도 좋은 리뷰 남겨주셔서 정말 감사합니다 ㅎㅎ 😄 

앞서 DM으로 연락 드렸던 것 처럼, 도무지 감이 잡히질 않는다 싶은 부분은 코멘트로 저의 생각과 함께, 디디의 의견을 한 번 더 여쭤봐도 되겠냐는 질문을 남겼습니다!

그 외에 나름대로의 답을 내리고, 수정할 수 있는 부분은 수정해 보았는데 이번에 드리는 요청에서는 변경 사항이 많이 보이지 않는 것 같습니다. (다음 PR 요청을 드릴 때 개선할 수 있을 것 같은 부분과 추가 수정이 필요한 부분은 더 수정해서 요청 드리도록 하겠습니다...!!) 

그리고 https://github.com/woowacourse/java-ladder/pull/189#pullrequestreview-1311516739 으로 남겨주신 답변에 대해 저의 의견을 남기는 것을 깜빡 잊어서 뒤늦게 추가 코멘트 올립니다. 죄송합니다 😢 

우선, 코멘트로 남겨주신 `LadderGame에 이동이라는 것이 있을까?` 라는 질문에 대해 나름대로 생각을 해보았고,  **직접 이동한다** 라는 개념보다는 **도착할 수 있는 위치를 찾는다** (저는 지도에 표시된 경로를 보고 도착지까지의 길을 찾는 것과 유사한 이미지로 생각했습니다.) 라는 의미로 표현하는 것이 더 적합하다는 결론을 내렸습니다. 

이는 자동차 경주 미션과 다르게, 사다리 게임의 경우에는 한 사람이 사다리를 통해 "최종 목적지까지 한 번에 이동을 지속하기 때문" 입니다. 

자동차 경주 미션에서는 차가 한 번 움직이고 나면 다른 차들이 모두 이동을 완료할 때 까지 기다린 후, 다시 자신의 차례가 돌아왔을 때 다음 이동을 할 수 있었습니다. 즉, 이전 턴에서 차 자신의 어떤 위치에 있었는지를 상태로 기억해 둘 필요가 있었던 것입니다. 

이와 유사하게 사다리 게임에서 `Person` 이 `position` 을 가지게 한다면, 이는 참여자가 자신의 위치 상태를 가지고 있어야 하는 경우라고 생각합니다. 하지만, 앞서 말씀드렸 듯이 한 번에 도착지까지 경로를 따라 계속해서 이어나가기 때문에 **Person이 자신의 위치 상태를 가지고 있어야 할 필요가 없다** 라고 판단했습니다. 

그렇기에 사다리 게임의 실행은 사람의 직접적인 이동 보다는, 지도와 유사하게 경로를 보고 도착지를 찾는 것과 유사하다는 나름대로의 결론을 내렸습니다. 

혹시 제가 놓치고 있는 부분이 있거나, 더 좋은 의견이 있다면 다시 한 번 생각해 보겠습니다!

감사합니다 😻

2023-02-25 11:34 UTC, fucct commented on src/main/java/controller/LadderController.java
> +        printGameResult(ladderGame.play());
bridgeSize가 정확히 어떤걸의미하는지 모르겠지만, 만약 메서드에 필요하다면 중복해서 사용해도 괜찮다고 생각합니다 :) 
메서드를 가독성을 위해 private메서드로 분리하는것 처럼, 파라미터도 중복을 피하기 위해 메서드를 합치기보단, 가독성을 위해 분리하는게  좋지 않을까요?

2023-02-25 11:36 UTC, fucct commented on src/main/java/controller/LadderController.java
> +        outputView.printLadder(ladderGame.getAllPlayers(), ladderGame.getLadder(), ladderGame.getWinningEntries(),
아~ 제가 드리려고 했던 피드백은, LadderGame이 원시값을 받아서 Persons, WinningEntry, Ladder와 같은 **도메인 객체 생성 책임**을 한곳에서 담당하면 좋겠다는 것이였습니다. Ladder는 LadderGame이 생성하고있고, Persons와 WinningEntry는 Controller가 생성하고 있다면, 도메인 생성에 대한 책임이 여러 Layer가 나눠갖고 있다는 생각이 들어서요!

2023-02-25 11:38 UTC, fucct commented on src/main/java/type/LadderElementInformation.java
> +public enum LadderElementInformation {
👍

2023-02-25 11:39 UTC, fucct commented on src/main/java/domain/LadderGame.java
> +        throw new IllegalArgumentException(ErrorCode.WRONG_RESULT_TARGET.getMessage());
좋습니다!

2023-02-25 11:40 UTC, fucct commented on src/main/java/domain/LadderGame.java
> +    private final WinningEntry winningEntry;
이 피드백을 드린 이유를 약간 설명하자면...

LadderGame이라는 객체를 정의하는것에 대해 한번 고민해볼 필요가 있어요. 이녀석은 도메인이라고 하기엔, 여러 도메인을 종합적으로 이용해서 게임을 진행시키는 역할을 하긴 하지만 자체적으로 도메인 역할을 하지는 않고, View라고 하기엔 직접 View와 맞닿아 있지 않죠.
심지어 이번 사다리 게임 미션은 게임의 진행이라는 개념이 없고, Ladder 생성과 동시에 게임이 종료되는 미션이였습니다. 
이러한 View와 Domain의 중간정도에 위치하는 객체를 정의할때 바론께서 고민해보셨으면 좋을것 같아서 드렸던 리뷰입니다.

1. 이 객체가 정말로 필요한지?
2. 만약 이 객체가 필요하다면, 어떤 역할을 가져야하고, 어떠한 역할을 가지지 않아야 하는지?

이 두 가지를 고민해보시면 앞으로 드시는 고민들을 해결해보시면 좋을 것 같아요.
예를 들면 바론께서 말씀하신것처럼 모두 지역변수로 만들어 버린다면, LadderGame이 없이 Controller에서 그 역할을 해도 괜찮겠죠?
LadderGame이 있어야 된다고 생각하신다면, 바론께서 작성해주신 형태로 작성해주셔도 크게 문제가 없을거라고 생각합니다 :) (인스턴스 변수가 3개 이상이라고 무조건 리팩토링 대상이 되는건 아니라고 생각해주세요)
좀 더 디테일한 부분이 궁금하시다면 언제든 코멘트 주세요! 😊

2023-02-25 11:40 UTC, fucct commented on src/main/java/domain/LadderGame.java
> +    public Map<String, String> pickResultForTarget(Map<String, String> results, String target) {
👍

2023-02-25 11:41 UTC, fucct approved these changes
안녕하세요 바론!

2023-02-25 11:45 UTC, merged

2023-02-26 07:51 UTC, somsom13 commented on src/main/java/domain/LadderGame.java
> +    private final WinningEntry winningEntry;
안녕하세요 디디! 
남겨주신 피드백을 찰떡 같이 흡수하지 못했다는 아쉬움이 조금 남아서... 😂  위 코멘트를 기반으로 다시 생각해 보았습니다!

우선 제가 LadderGame 을 만든 이유는 
> 사다리 게임은 "하나의 게임" 이라고 생각했고, 사다리의 이동이라는 별도의 기능이 존재한다고 생각했기 때문에 게임의 흐름과 속성을 총괄하는 객체가 반드시 존재해야 한다고 생각했기 때문이었습니다..! 
(사실 지금 와서 생각해보면, RacingCarGame 객체가 있었던 것 처럼 게임은 그 본체 객체가 존재해야 한다는 무의식적인 고정관념을 가지고 있었기 때문일 수도 있겠네요 ㅎㅎ)

피드백으로 남겨주신 내용들 중, "사다리 게임에는 **이동**이라는 개념이 없다" , "이번 미션은 사다리를 생성하기만 하면 끝인 미션" 의 의미에 대해서 다시 생각해보면서
> **사다리는 만들어지자마자 각 참여자의 index에 따른 도착지 index가 정해지기 때문에** 이동이라는 개념이 없으며, 사다리를 생성하는게 전부인 미션이다!

라고 이해했는데, 제가 올바르게 이해한 것이 맞는지 궁금합니다! ㅎㅎ

이렇게 생각하게 된다면 지금의 제 코드 방식인 
1. Persons, Ladder, WinningEntry 를 모두 생성한 뒤
2. 나중에 `play()` 를 통해 사다리 이동을 실행시킨다

의 흐름이 아닌,

**Persons, Ladder, WinningEntry 를 만듦과 동시에 결과를 찾고, 사용자가 요청하는 것에 따라 이미 저장된 결과를 반환만 해주자!**

라는 흐름으로 변경할 수 있을 것 같습니다. 그러면 LadderGame의 유일한 역할이라고 볼 수 있는 `play()` 의 의미가 없어지는 것 같은데, 그렇기 때문에 디디께서 `LadderGame이 꼭 필요한 객체가 맞는지 고민해보라` 는 조언을 주셨던게 아닌가 싶습니다. 

1. Controller 에서 각 도메인들을 지역변수로 가지게 한다
2. Ladder가 Persons, WinningEntry 를 속성으로 가지게 한다

위의 두 가지 방법 중 하나를 선택해볼 수 있을 것 같습니다. 

그리고 마지막으로 `만약 LadderGame을 지우지 않는다면, 어떤 계층에 속한다고 이해할 수 있을까?` 를 고민해 보았는데요, 
LadderGame은 사다리를 구성하는 도메인들에게 서로 명령을 보내고, 그 결과를 조합하는 역할 이 전부이고 특히 **내부적으로 가지는 속성을 특별히 가공하거나 변경 하는 일이 없기 때문에**  도메인 보다는 서비스에 더 적합하지 않나 싶습니다. 

저는 서비스를 컨트롤러의 무게를 덜어주기 위해 "여러 도메인들의 결과를 조합하는 비즈니스 로직을 따로 분리해주는 것" 으로 생각하여 이런 결론을 내렸는데, 사실 아직도 도메인과 서비스의 정확한 차이가 헷갈려서 올바른 결정이라는 확신이 서지는 않습니다 ㅠ.ㅠ 디디께서 정의하시는 서비스, 도메인이 무엇인지도 한 번 의견을 여쭤보고 싶습니다..!

긴 답변 읽어 주셔서 감사합니다 😃  디디 덕분에 여러 가지로 생각을 많이 해보고, 조금이나마 성장할 수 있었던 것 같습니다 ㅎㅎ 감사합니다!

2023-02-26 07:56 UTC, somsom13 commented on src/main/java/controller/LadderController.java
> +        outputView.printLadder(ladderGame.getAllPlayers(), ladderGame.getLadder(), ladderGame.getWinningEntries(),
도메인 생성의 책임이 여러 Layer 에 분포되어 있다는 걸 생각지도 못했습니다 ㅠㅠ 감사합니다!!

![image](https://user-images.githubusercontent.com/70891072/221398822-37b197ca-3ecf-45bc-b240-42b45e732dc2.png)

저는 사다리 미션을 구현할 때 위의 이미지를 생각하고 구현했는데요,
Persons, WinningEntry 는 사용자가 입력한 값을 토대로 "외부에서 생성 해준다" 라고 생각하여 controller 에서 생성하여 LadderGame에 주입하고 Ladder의 경우에는 "사다리 시작" 을 선택한 후에야 게임이 활성화 되면서 사다리가 만들어진다고 생각하여 LadderGame의 내부에서 만들기로 결정했던 것 같습니다. 

그런데 디디의 리뷰를 보고, 이렇게 되면 도메인 객체들 중 일부는 컨트롤러에서 그리고 일부는 도메인에서 만들어지기 때문에 객체 생성의 책임이 말 그대로 사방팔방으로 퍼져버린 다는 것을 알게 되었습니다 ㅠㅠ 
정말 미처 생각지도 못한 문제점을 찾게 되었네요 리뷰 정말 감사합니다!!! 

한 Layer에서 모든 도메인의 생성을 담당하도록 분리해보도록 하겠습니다 😄

2023-02-26 12:48 UTC, fucct commented on src/main/java/domain/LadderGame.java
> +    private final WinningEntry winningEntry;
우선 제가 전달드린 피드백을 올바르게 이해하신것 같아요.

말씀하신것처럼 LadderGame은 **서비스** 레이어 개념이라고 생각했고, 현재 애플리케이션 요구사항에 서비스 레이어가 필요한지에 대해 한번 고민해보셨으면 하는 마음으로 피드백을 드렸습니다.
아직은 배우지 않았지만 앞으로 컨트롤러 - 서비스 - 도메인 과 같은 레이어드 아키텍쳐를 배우면서, 의심 혹은 고민없이 레이어를 나누는 경우가 많습니다. 해당 아키텍처가 주어진 요구사항에 적합한지, 지금 내 요구사항에 적합한 아키텍처가 어떤건지 고민해보셨으면 좋겠습니다. 

서비스의 기준은 사람마다 다르겠지만 도메인-View의 변환계층이라고 생각합니다. 입력으로 받은 원시값들을 도메인으로 바꿔주고, 각 도메인을 조합하여 비즈니스를 실행하고, 실행된 비즈니스의 결과를 다시 View로 변경해주는 역할을 담당한다고 생각합니다 :) 바론이 만들어주신 LadderGame의 역할과 유사하죠?

앞으로도 LadderGame과 같은 중간단계 객체를 만드실때는, 항상 스스로 기준을 가지고 만드셔야 한다는점을 기억해주시면 좋겠습니다