[2단계 - 사다리 생성] 주디(오은비) 미션 제출합니다.
woowacourse/java-ladder pull request #202
Opened 2023-02-23 07:13 UTC by eunbii0213

조앤, 안녕하세요! 주디입니다😊
사다리 생성 2단계 제출합니다!

사다리를 통해 결과값을 구하는 방법은 3가지가 있을 것 같아요.
1. 실제 사다리게임처럼, 각각의 Player가 사다리 타기(bfs/dfs와 유사하게 direction 설정)
2. swap 이용하기 (건널 수 있으면 그 자리의 player 2명이 자리바꾸기)
3. 자리값 이용하기(오른쪽 건널 수 있으면 자리값 +1, 왼쪽을 건널 수 있으면 -1)

저는 그 중에 2번을 선택했습니다! 
(사실 1번으로 시작하다가 저의 역량 부족이란 이슈가 발생했어요🥲 코드가 너무 더러워지길래 2번으로 재빨리 갈아탔습니다..ㅎㅎ)

그리고 [1단계](https://github.com/woowacourse/java-ladder/pull/77)에서 대댓글로 질문도 남겨놓았는데 확인 부탁드려요! 

그리구 꼭 말씀 드리고 싶었는데... 제가 느끼기로는 조앤이 단순히 "답은 A니까 A로 짜세요"라고 피드백을 주지않잖아요. 전 이 부분이 되게 좋았어요! 조앤이 한 번 물음을 던짐으로서 한 번 더 생각해보게 되고 "저는 이렇게 생각하는데 리뷰어님의 생각은 어때요?" >> "저는 이렇게 생각해요~ 생각하면서 이런 포인트들을  고민해보세요~" 라는 흐름을 타니까 다양한 인사이트를 얻을 수 있었어요! ㅎㅎㅎ 감사합니다🙇‍♂️ 감사하다는 말 꼭 전해드리고 싶어서 이렇게 작성하게 되었어요.

이번 리뷰도 잘 부탁드립니다🐰🍀

2023-02-23 10:53 UTC, seovalue requested changes
README도 없고... 추가하신 도메인에 대한 테스트도 없어요 주디!!!!!!!!!! 흑흑
그리고 사다리 게임이 정상적으로 동작하지 않아요..ㅠㅠ 
게임이 정상 동작하도록 수정 후 다시 리뷰 요청 부탁드릴게요~

추가로 STEP 1에서 남겨주신 질문에 대한 답변 링크 여기에두 남겨둬요! 
[InputView 할당 관련 질문](https://github.com/woowacourse/java-ladder/pull/77#discussion_r1115495900)
[PlayerNames 및 System.exit() 관련 질문](https://github.com/woowacourse/java-ladder/pull/77#discussion_r1115500333)

2023-02-23 10:53 UTC, seovalue commented on src/main/java/domain/Rewards.java
> +    private static final String REWARDS_SIZE_ERROR_MESSAGE = "[ERROR] 플레이어 수에 맞는 실행 결과를 입력해주세요.";
<img width="547" alt="Screenshot 2023-02-23 at 19 47 28" src="https://user-images.githubusercontent.com/48412963/220885553-feaa4462-2d41-44ef-bbab-06e54f9a3644.png">
플레이어 수를 몇 명으로 계산한 걸까요..................

2023-02-23 10:53 UTC, seovalue commented on src/main/java/view/OutputView.java
> +    public static final String LADDER_RESULT_GUIDE_MESSAGE = "\n" + "사다리 결과" + "\n";
1단계 요구사항이었던 것 같은데ㅎㅎ 사람 이름을 5자 기준으로 출력하면 너비가 같아야할 것 같은데 너비가 달라요!
<img width="557" alt="Screenshot 2023-02-23 at 19 49 20" src="https://user-images.githubusercontent.com/48412963/220885958-7516d677-be44-4d40-a9bd-1f1f38f097f7.png">

그리고 결과의 경우에는 일일이 조회하는 경우에는 계속 조회할 수 있도록 하고, all을 입력해서 전체 결과를 조회하는 경우에만 게임을 종료하는 건 어떨까요? 👀  요건 제안이니 선택적으로 적용해주세요!

2023-02-23 10:53 UTC, seovalue commented on src/main/java/view/OutputView.java
> +    public static final String REWARD_GUIDE_MESSAGE = "\n" + "실행 결과";
<img width="580" alt="Screenshot 2023-02-23 at 19 50 46" src="https://user-images.githubusercontent.com/48412963/220886228-e09f1709-4735-4093-8448-44e3f96c3ff1.png">

실행 결과에 대해 b가 c이고, c가 a여야하는데 프로그램이 정상적으로 동작하지 않아요.

2023-02-23 10:57 UTC, eunbii0213 commented on src/main/java/domain/Rewards.java
> +    private static final String REWARDS_SIZE_ERROR_MESSAGE = "[ERROR] 플레이어 수에 맞는 실행 결과를 입력해주세요.";
오마이갓;;;;;; 테스트 코드 작성과 기능목록 작성을 완전히 까먹고 냅다 구현만 해버렸네요. 게다가 제대로 작동하지도 않네요...? 제가 콘솔에 테스트했던 건... 운으로 맞았나보네요.....따흐흑... 다시 고쳐보겠습니다..흑흑

2023-02-23 13:42 UTC, eunbii0213 commented on src/main/java/domain/Rewards.java
> +    private static final String REWARDS_SIZE_ERROR_MESSAGE = "[ERROR] 플레이어 수에 맞는 실행 결과를 입력해주세요.";
분명히 공백입력시 예외처리하는 기능을 만들었는데 왜 동작하지 않는 건지 알아봤어요!
String.split()을 사용할 경우, 중간에 있는 공백값 
`a,b,,c`
는 공백으로 인식하지만 끝에 오는
`a,b,,`
는 a,b만 인식하고 뒤의 공백은 데이터가 없기 때문에 값으로 인식을 하지 않는다는 걸 알았어요! 따라서 
` return List.of(playerName.split(DELIMITER, -1));`
로 바꿔주겠습니다!!

2023-02-23 13:45 UTC, eunbii0213 commented on src/main/java/view/OutputView.java
> +    public static final String LADDER_RESULT_GUIDE_MESSAGE = "\n" + "사다리 결과" + "\n";
이름과 이름사이에 공백이 하나 더 추가되더라구요!! 모두 5칸으로 설정되고 중간중간 공백을 추가하는 것보다
- 첫번째 플레이어 : 5칸
- 마지막 플레이어: 5칸
- 나머지 플레이어: 6칸(5칸+공백 1칸 포함)
이렇게 설정하는 게 간편할 것 같아서 format을 다르게 잡았어요! 

모두 포맷을 같게하고 중간에 공백을 추가하는 방향이 나을까요?!

2023-02-23 14:24 UTC, eunbii0213 commented on src/main/java/view/OutputView.java
> +    public static final String REWARD_GUIDE_MESSAGE = "\n" + "실행 결과";
전.. 바본가봐요..원인을 찾았어요.. 리팩터링 하는 과정에서  복붙 실수했던 거였어요..
사다리 게임을 1번 해야하는데 2번 하고 있었던 거죠 ㅜㅜ 
제가 꼼꼼히 확인했어야했는데.. 분명 제출하기 전에 한 번 더 확인했는데도 이런 실수를... 조앤도 황당하셨겠어요.. 죄송해요 ㅜ

2023-02-23 17:28 UTC, eunbii0213 commented
안녕하세요, 조앤! 좋은 아침(?)입니다.
어제 조앤의 리뷰를 보고 정말 깜짝 놀랐어요.
다시 한 번 확인도 했는데.. 왜 발견하지 못했는지 😭 조급함에 시간에 쫓기듯 구현해서 많은 걸 놓친 것 같아요. TDD, 기능목록까지 잊어버리고.. 
급할 수록 돌아가라는 말이 있듯이, 같은 실수를 반복하지 않도록 노력해야겠어요.

조앤도 엉망진창인 코드 보고 당황스러웠을 것 같아요. 번거롭게 해드려서 죄송해요..ㅠㅠ
조앤에게도 죄송하고, 스스로에 대한 당황 + 어이없음 + 실망감이 합쳐져서.. 잠이 안 오더라구요. 그래서 저녁부터 후다닥 고쳐봤어요.

이번에는 레벨2에서 피드백 주셨던 내용과 더불어 1레벨에서 피드백 주셨던 내용들도 고쳐봤어요!
- domain 내부에 있는 inputView 빼내기 (Controller로 검증 로직 빼내기, domain은 예외만 던져주고 그 후는 모르게 만들었어요)
- validate 후에 class변수들 할당하기 
- 기능 목록 작성
- 테스트 코드 작성
- 사다리 게임 올바르게 동작하게 만들기
- 플레이어 이름(+실행 결과) 공백 입력시 예외처리

이번 리뷰 요청은 진짜입니다...! 잘 부탁드려요 😂

2023-02-24 16:30 UTC, seovalue commented on src/main/java/view/OutputView.java
> +    public static final String LADDER_RESULT_GUIDE_MESSAGE = "\n" + "사다리 결과" + "\n";
포맷은 그대로 가져가셔도 좋을 것 같은데 첫번째 참가자 a만 가장 5칸 중 가장 앞에 위치하고 나머지 b,c는 5칸의 마지막에 위치해서 UI가 깨져보이는 것 같아요.

2023-02-24 16:52 UTC, seovalue requested changes
안녕하세요 주디~ 조앤이에요ㅎㅎ
밤늦게까지 추가 작업을 해주셨군요ㅠㅠ 고생 많으셨어용ㅎㅎ 이제 잘 되네요~
몇 가지 코멘트 남겨두었는데 확인해보시구 다시 리뷰 요청 부탁드려요!!

2023-02-24 16:52 UTC, seovalue commented on docs/README.md
> +- [△] TDD 적용 연습해보기!
ㅋㅋㅋㅋㅋㅋㅋㅋ 세모 어떻게 그리신거죠?? 신기하다

2023-02-24 16:52 UTC, seovalue commented on docs/README.md
> +- [x] all이 입력될 수 없다
README 굳굳ㅎㅎ

2023-02-24 16:52 UTC, seovalue commented on src/main/java/LadderGame/LadderGame.java
> +    public void ladderGame() {
궁금한 건데 LadderGame이라는 객체의 이름과 같은 이름을 갖도록 메서드명을 지정하신 이유가 있나요??

2023-02-24 16:52 UTC, seovalue commented on src/main/java/domain/Ladder.java
> +    public void getRewardsForPlayers(Rewards rewards) {
안혼동되고 오히려 더 이해가 잘되어요! 👍  괜히 어려운 용어 쓰는 것보다 가독성 좋게 간단한 용어를 사용하는게 더 좋아보여요ㅎㅎ

2023-02-24 16:52 UTC, seovalue commented on src/main/java/domain/Ladder.java
> +        for (int Playerindex = 0; Playerindex < line.getLine().size(); Playerindex++) {
사소한 거지만 `line.getLineSize()` 와 같이 합칠 수 있는건 합쳐보는 건 어떨까요? 최대한 `.`하나로 실행될 수 있도록요! 그리고 Playerindex가 `playerIndex`와 같이 되어야 자바에서 지향하는 변수 컨벤션을 지킬 수 있을 것 같아요~

2023-02-24 16:52 UTC, seovalue commented on src/main/java/domain/Player.java
> +    public void setReward(Reward reward) {
setter를 사용하셔서 구현한 이유가 있나요?! setter가 열려있다면 사실상 reward 멤버 변수는 public인 것과 마찬가지라고 생각이 들어요! setter를 사용하게 된다면 Player 내의 reward 값을 외부에서도 변경할 수 있기 때문에 변경한 의도를 파악하기 힘들고, 객체의 일관성을 유지하기 어려워요.
setter를 사용하지 않고 구현하려면 어떻게 할 수 있을까요? 🤔

2023-02-24 16:52 UTC, seovalue commented on src/main/java/domain/PlayerNames.java
> +        this.playerNames = new ArrayList<>();
```
this.playerNames = createPlayerNames(playerNames);

    private List<PlayerName> createPlayerNames(List<String> playerNames) {
        return playerNames.stream().map(PlayerName::new).collect(Collectors.toList());
    }```

으악!! 깃허브에서 코드치는거 너무 불편해요

2023-02-24 16:52 UTC, seovalue commented on src/main/java/domain/PlayerNames.java
> +        validatePlayerName(playerNames);
👍 👍  알려드린대로 쏙쏙 반영하여주시니 기분이 좋아용

2023-02-24 16:52 UTC, seovalue commented on src/main/java/view/OutputView.java
> +            }
요구사항에 다음과 같은 것이 있어요~
* indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.
* 예를 들어 while문 안에 if문이 있으면 들여쓰기는 2이다.

2023-02-24 16:52 UTC, seovalue commented on src/main/java/view/OutputView.java
> +        for (int i = 0; i < rewardsRewards.size(); i++) {
요기도 마찬가지예요~

* indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.
* 예를 들어 while문 안에 if문이 있으면 들여쓰기는 2이다.

2023-02-24 16:52 UTC, seovalue commented on src/main/java/view/OutputView.java
> +    public static final String LADDER_RESULT_GUIDE_MESSAGE = "\n" + "사다리 결과" + "\n";
https://github.com/woowacourse/java-ladder/pull/202/files#r1115717942
> 예시 출력 보니까 이름과 이름사이에 공백이 하나 더 추가되더라구요!! 모두 5칸으로 설정하고 중간중간 공백을 추가하는 것보다
> 
> * 첫번째 플레이어 : 5칸
> * 마지막 플레이어: 5칸
> * 나머지 플레이어: 6칸(5칸+공백 1칸 포함)
>   이렇게 설정하는 게 간편할 것 같아서 format을 다르게 잡았어요!
> 
> 모두 포맷을 같게하고 중간에 공백을 추가하는 방향이 나을까요?



포맷은 그대로 가져가셔도 좋을 것 같은데 첫번째 참가자 a만 가장 5칸 중 가장 앞에 위치하고 나머지 b,c는 5칸의 마지막에 위치해서 UI가 깨져보이는 것 같아요.

2023-02-24 16:52 UTC, seovalue commented on src/main/java/view/OutputView.java
> +    public static final String LADDER_RESULT_GUIDE_MESSAGE = "\n" + "사다리 결과" + "\n";
포맷은 그대로 가져가셔도 좋을 것 같은데 첫번째 참가자 a만 가장 5칸 중 가장 앞에 위치하고 나머지 b,c는 5칸의 마지막에 위치해서 UI가 깨져보이는 것 같아요.

2023-02-25 06:51 UTC, eunbii0213 commented on src/main/java/view/OutputView.java
> +    public static final String LADDER_RESULT_GUIDE_MESSAGE = "\n" + "사다리 결과" + "\n";
아앗 그 뜻이었군요!! 제가 이 부분을 놓친 것 같아요!
첫 번째 플레이어도 "-5%s"로 바꿔주겠습니다!😆

+ 고치고 보니 굳이 첫 번째, 마지막으로 나누지 않아도 될 것 같더라구요! 
`String FIRST_FORMAT = "5%s"
String LAST_FORMAT = "%5s"`
에서
`String FIRST_OR_LAST_FORMAT = "5%s"`
로 변경했습니다! 

그리고
isFirst(), isLast()같은 메서드들도 isFirstOrLast()로 합쳤어요!

2023-02-25 06:57 UTC, eunbii0213 commented on docs/README.md
> +- [△] TDD 적용 연습해보기!
ㅎㅎㅎ 세모 특수문자 검색해서 복붙 했어요😆 TDD를 제대로 수행해내지 못했으므로 세모쳤습니다 🥺

2023-02-25 06:58 UTC, eunbii0213 commented on docs/README.md
> +- [x] all이 입력될 수 없다
^ㅅ^ ㅎㅎㅎ 칭찬 감사해요~ 더 열심히 하고 싶어져요!!!

2023-02-25 07:00 UTC, eunbii0213 commented on src/main/java/LadderGame/LadderGame.java
> +    public void ladderGame() {
처음에 작성할 때는 가장 바깥에 있는 함수가 ladderGame의 역할을 하고 있으니 ladderGame으로 지었어요! 그러다보니 객체 이름과 같아졌네요🤔

이 부분이 찜찜해서 start라는 이름으로 바꿔주었습니다! 
호출할 때 LadderGame.start()가 되면 조금 더 직관적이지 않을까란 생각으로요! 조앤의 생각은 어떠세요? 더 좋은 아이디어가 있으면 공유해주세요😆

2023-02-25 07:53 UTC, eunbii0213 commented on src/main/java/domain/Ladder.java
> +        for (int Playerindex = 0; Playerindex < line.getLine().size(); Playerindex++) {
`line.getLineSize()`처럼 .이 하나가 나오도록 수정하니 코드가 훨씬 간결해질 수 있었어요!! 이렇게 또 하나 얻고 갑니다.. 감사합니다 🏋🏻‍♂️ 

+ 종종 변수명 컨벤션을 실수하네요 ㅜ 더 유의하도록 하겠습니다!

2023-02-25 08:28 UTC, eunbii0213 commented on src/main/java/domain/Player.java
> +    public void setReward(Reward reward) {
Reward는 Player가 가지고 있어야한다 생각했어요. 하지만  사다리 게임을 진행한 후에나 Reward를 할당하더라구요. 그래서 setter를 사용하게 된 것 같습니다 ㅜㅜ

setter 사용을 피하기위해 결국 Player에서 Reward를 뺐어요. 굳이 Player가 Reward를 가지지 않고 있어도 playerIndex만으로도 어떤 Player가 어떤 Reward를 가지는지는 알 수 있는 거더라구요.

하지만 여전히 찝찝해요. Player가 Reward를 가지고 있어야 하는 게 아닐까...하구요. Player가 Reward를 가지면서, setter를 사용하지 않고도 Reward를 나중에 할당할 수 있는 방법엔 뭐가 있을까요?

사다리 게임이 끝나고 새로운 생성자로 새로운 Player를 return 해주는 방식일까요? 
`public Player(String name, Reward reward) {
    this.name = name;
    this.reward = reward;
}

public Player createPlayerWithReward(Player player, Reward reward){
    new Player(player.getName(), reward);
}
`
이렇게 하고 Players에 든 Player들도 다 바꿔주는 방식이요! 흠.. 이것도 변경가능성이 있어보이기도 하구 코드가 더 복잡해지는 것 같기도해요.. 🥲 어렵네요. 어떤 게 더 효율적인 방법일까요?

2023-02-25 08:34 UTC, eunbii0213 commented on src/main/java/domain/PlayerNames.java
> +        this.playerNames = new ArrayList<>();
저도 이부분 코드 짜면서 new ArrayList<>(); 부분이 "이렇게 해줘야할까.. 매우 세련되지 않네.." 싶었는데! 이런 방법이 있었군요!! 감사합니다 🔥🔥🔥

2023-02-25 08:40 UTC, eunbii0213 commented on src/main/java/domain/PlayerNames.java
> +        validatePlayerName(playerNames);
ㅎㅎㅎ 2단계 머지되면 저번에 말씀주신 all 입력되면 종료되게끔 하는 것도 반영하고 싶어요~!

2023-02-25 08:46 UTC, eunbii0213 commented on src/main/java/domain/PlayerNames.java
> +        this.playerNames = new ArrayList<>();
추가로 Rewards도 비슷한 구조길래 Stream 이용해서 바로 return해줄 수 있도록 변경했어요!!

2023-02-25 08:56 UTC, eunbii0213 commented
안녕하세요, 조앤!
화창한 토요일이네요😊
조앤도 주말엔 쉬고 싶으실텐데, 이렇게 요청 드려서 한편으로는 죄송하기도하네요..ㅜㅜ 시간이 조금 더 있었다면 그냥 월요일에 리뷰 요청 드렸을텐데.. 다음에 만날 땐 제가 더더욱 강해져서 주말엔 쉬게 해드릴게요 !!!!🔥🔥🔥

2023-02-25 12:30 UTC, seovalue commented on src/main/java/LadderGame/LadderGame.java
> +    public void ladderGame() {
start()가 훨씬 직관적인 것 같아요! 사다리게임을 시작한다. 는 의미를 나타내는 것 같아요~~!

2023-02-25 12:42 UTC, seovalue approved these changes
안녕하세요 주디! 주말에도 열일하시는군용 👍  
코드에 대해서는 더 이상 크게 코멘트 드릴 부분은 없는 것 같아요~ 다만 확인했으면 좋을 부분이 두 가지 있어서 코멘트로 달아두었는데, 꼭꼭 확인해보시길 바라요!ㅎㅎ 주디의 의견이 궁금한 부분도 있어서..ㅎㅎ 코멘트 남겨주시면 저도 확인해볼게요!

추가로 이번 미션을 진행하면서 주디가 주디의 의견을 많이 들려주셨던 것 같아요. 이러한 부분들, 꼭 모두 기록해두시길 바라요!ㅎㅎ 나중에 주디가 어떻게 성장하셨는지, 그 땐 어떤 고민들을 했었는지 확인하기 좋으실거예요. 고생 많으셨어요~~! 내일은 푹 쉬세요!

2023-02-25 12:42 UTC, seovalue commented on src/main/java/view/InputView.java
> +    private static void printPlayerNameInputGuideMessage() {
유틸클래스로 변경하셨군요!

2023-02-25 12:42 UTC, seovalue commented on src/main/java/domain/Player.java
> +        return this.name.equals(input);
String과 PlayerName 객체를 비교하고 있어요!! 
`'equals' between objects of inconvertible types 'PlayerName' and 'String'`

2023-02-25 12:42 UTC, seovalue commented on src/main/java/domain/Player.java
> +    public void setReward(Reward reward) {
현재 Reward가 실행 결과를 나타내는데, 플레이어가 실행 결과를 가져야한다고 생각하신 이유가 무엇인가요? 👀 
실행결과는 플레이어와는 별개의 생명주기를 갖는 것 같아요. 플레이어는 단순히 게임에 참가한 사람을 나타내고, 실행결과는 플레이어들의 결과를 담고 있긴 하지만 이후에 플레이어들의 결과가 아닌 다른 값도 충분히 담을 수 있다고 생각해요. 한가지 예시를 들어보자면 주문과 배송이 있다고 해 볼게요. 배송이라는 것은 주문이 이루어져야 배송이 발생한다고 생각할 수 있어요. 그럼 주문이라는 객체가 배송까지 가져야할까요? 이 부분에 대해서 주디는 어떻게 생각하시나요~? 
저는 우선 지금처럼 별도로 가져가는 게 더 좋아보여요 👍

2023-02-25 12:42 UTC, merged

2023-02-25 12:50 UTC, eunbii0213 commented on src/main/java/view/InputView.java
> +    private static void printPlayerNameInputGuideMessage() {
네! 각 클래스마다 계속 객체를 생성해주는 게 찜찜하더라구요 🥲 저번에 조앤이 말씀해주셨던 것 처럼, 입/출력만 담당하는 view는 어떠한 상태를 가진다거나 하는 건 없어서 유틸클래스로 변경하였습니다!

2023-02-25 12:54 UTC, eunbii0213 commented on src/main/java/domain/Player.java
> +        return this.name.equals(input);
헉 그렇네요! 짚어주셔서 감사합니다! 빠르게 수정했어요 ㅎㅎ

2023-02-25 13:02 UTC, eunbii0213 commented
> 현재 Reward가 실행 결과를 나타내는데, 플레이어가 실행 결과를 가져야한다고 생각하신 이유가 무엇인가요? 👀
실행결과는 플레이어와는 별개의 생명주기를 갖는 것 같아요. 플레이어는 단순히 게임에 참가한 사람을 나타내고, 실행결과는 플레이어들의 결과를 담고 있긴 하지만 이후에 플레이어들의 결과가 아닌 다른 값도 충분히 담을 수 있다고 생각해요. 한가지 예시를 들어보자면 주문과 배송이 있다고 해 볼게요. 배송이라는 것은 주문이 이루어져야 배송이 발생한다고 생각할 수 있어요. 그럼 주문이라는 객체가 배송까지 가져야할까요? 이 부분에 대해서 주디는 어떻게 생각하시나요~?
저는 우선 지금처럼 별도로 가져가는 게 더 좋아보여요 👍

전 어떤 생각이였냐면.. Player와 Reward가 사다리게임을 통해 서로 연결되는 구조라 생각했어요! 
지금은 한 Player가 LadderGame을 통해 특정한 Reward를 가지는 형태잖아요! 그래서 Player가 Reward를 가져야한다고 생각했어요! 사다리게임을 통해 Reward가 Player에게 가는 느낌이랄까요??
게임의 결과는 얼마든지 바뀔 수 있으니 그래서 setter를 쓴 것 같아요. 같은 의미로 final도 그래서 주지 않았던 거구요! 

그런데 조앤의 의견을 들어보니, 마치 주문과 배송처럼 주문과 배송이 연관이 있다고 꼭 주문이 배송을 알아야할까??란 생각도 들어요🤔... Player와 Reward가 사다리게임을 통해 연결되어있다고 해서, 꼭 Player가 알아야하는걸까요..?흐음.. 저는 상품 수령처럼 연결되어있다고 생각하긴하는데 조앤처럼 분리되어야한다고 생각할 수도 있을 것 같아요! 이 주제에 대해 스터디원들하고 토론해보고싶네요 ㅎㅎㅎ

2023-02-25 13:05 UTC, eunbii0213 commented
와아🎉🎉🎉🎉🎉
merge 해주셨군요!! 감사합니다 ㅎㅎㅎ 기뻐요!! 
스스로에게 주는 상으로 게임을 조금 해야겠네요(?) ㅎㅎ
그리고 merge 됐으니 조앤이 제안해주셨던  "all이 입력되면 게임 종료"를 구현해볼까 해요 😆

배움은 언제나 새롭고 재밌네요! 고마웠어요 조앤! 
조앤이 제 생각을 많이 여쭤봐주셔서 같이 의견 나누는 게 제일 재밌었고 그 과정에서 많이 배운 것 같아요! 우리 또 만나요 🫶