[2단계 - 사다리 게임 실행] 코코닥(이승용) 미션 제출합니다.
woowacourse/java-ladder pull request #209
Opened 2023-02-23 08:32 UTC by kokodak

안녕하세요 파즈! 개인적으로 이번 미션이 좀 어려워서 객체 분리나 역할, 책임이 잘 나누어졌는지 판단하기가 어렵네요.

이번에는  `LadderGame` 클래스를 만들어서, 사다리 게임의 결과를 구하는 책임을 부여해봤습니다.
사다리 게임의 결과는 `LadderGameResult`에 저장하도록 했고, Map 자료구조를 사용했습니다.
사다리를 내려가는 기능은 `move()` 메서드를 통해 구현했는데, 출발 인덱스를 파라미터에 넣어주면 도착 인덱스를 뱉어주는 방식으로 구현해봤습니다.

리뷰 감사합니다! 이번에도 리팩터링 열심히 진행해보겠습니다.

2023-02-23 17:29 UTC, Be-poz requested changes
안녕하세요 코코닥! 2차 미션 제출 수고하셨습니다. 크게 바꿀 건 없는 것 같은데요, 일단 코멘트 달아놨으니 한 번 확인해주세요! 😆

2023-02-23 17:29 UTC, Be-poz commented on src/main/java/controller/Controller.java
> +        OutputView.printResult(users, results, ladder);
Result의 의미가 모호해져서 이제 메서드의 이름을 변경해야 될 것 같습니다. ``printLadderGameResult`` 처럼 조금 더 구체적으로 변경되면 좋을 것 같습니다!

2023-02-23 17:29 UTC, Be-poz commented on src/main/java/domain/LadderGame.java
> +    }
``isRight``, ``isLeft``는 prefix로 ``is`` 를 붙였는데 해당 boolean return method에는 안붙인 이유가 따로 있나요?  
통일되지 않아서 혼동을 할 수 있는 포인트인 것 같습니다.

2023-02-23 17:29 UTC, Be-poz commented on src/main/java/controller/Controller.java
> +        ladderGame.play();
사실상 이 때에 사다리 게임을 시작하는 것인데, move 등을 하여 결과추출은 31번 라인 ``LadderGame`` 객체 생성 시에 모두 끝난 상황입니다. ``play`` 가 play가 아닌 것 같습니다. 단순히 현재 진행 여부만 true로 바꿔주는 역할 밖에 못하고 있는 것 같은데요, 생성된 사다리 정보를 print 할 때에 ``사다리 결과`` 라고 print가 되는데 이 결과가 생성된 사다리의 결과의 의미로 봐야할지 아니면 그냥 게임 자체의 결과로 봐야 할지에 따라 갈릴 것 같습니다.  

1. 생성된 사다리의 결과로 보았을 때에는 ``LadderGame`` 객체 생성 시 바로 게임이 이루어지지 않도록 하며, ``play`` 호출 시에 이루어 질 수 있도록 변경. 이 경우에 ``LadderGame`` 내부 필드인 ``private final LadderGameResult ladderGameResult;``는 final을 떼야겠죠. 아마 이 final 때문에 생성자에서 게임까지 다 해버리게 만드신 것 같은 느낌이 드는데요, 이 경우에는 과감히 쳐내야 할 것 같네요.  

2. 게임 자체의 결과로 보았을 때에는, ``play`` 메서드의 이름 변경이 필요할 것 같습니다. 


+) 요번 코코닥 피드백 할 거리가 크게 없어서 1번으로 한 번 진행해보시면 좋을 것 같습니다.

2023-02-23 17:29 UTC, Be-poz commented on src/main/java/domain/LadderGame.java
> +        ladderGameResult = getLadderGameResult(users.getSize(), ladder.getLadderRows().size());
``ladder.getLadderRows().size()`` Ladder 내부에 size 한 번에 리턴해주는 메서드를 생성해도 괜찮을 것 같네요

2023-02-23 17:29 UTC, Be-poz commented on src/main/java/domain/LadderGameResult.java
> +        this.ladderGameResult = ladderGameResult;
방어적 복사를 하면 좋을 것 같습니다~!

2023-02-23 17:29 UTC, Be-poz commented on src/main/java/domain/Users.java
> +                .filter(user -> user.getName().equals(name))
일어날 일은 아니긴 한데, 이런 경우에 위쪽에 ``filter(Objects.nonNull)`` 로 확실하게 해주기도 합니다.

2023-02-23 17:29 UTC, Be-poz commented on src/main/java/domain/Users.java
> +                .findFirst()
``findFirst()``와 ``findAny()`` 의 차이점을 알고 계실까요 ?

2023-02-23 17:29 UTC, Be-poz commented on src/main/java/domain/LadderRow.java
> +    private static final int NOT_EXIST = -100;
-100 선정 기준이 뭐였는지 그냥 단순하게 궁금해서 듣고 싶습니다!  처음에는 -1로 하셨었더라구요

2023-02-23 17:29 UTC, Be-poz commented on src/main/java/domain/Result.java
> +public class Result {
생성된 사다리 결과를 출력할 때에도 printResult, 참가자의 사다리 게임 결과는 LadderGameResult 처럼 Result 라는 말이 굉장히 혼동을 주는 것 같습니다. 차라리 Reward 였으면 조금 나았을 것 같기도 하고요.. 좋은 적절한 이름을 코코닥이 선정해서 변경해주세요~!

2023-02-24 08:02 UTC, kokodak commented on src/main/java/domain/LadderRow.java
> +    private static final int NOT_EXIST = -100;
아 `-1`에서 `-100`으로 변경하게 된 이유는 OutOfBounds 예외 처리때문이었습니다.
만약 0번 인덱스(맨 왼쪽)에서 출발한다고 가정했을 때, 맨 왼쪽 주변에 라인이 존재하지 않으면 `-1`을 뱉게 했었는데요, 이렇게 되면 `isLeft()`의 반환값이 `0 == (-1) + 1`가 되면서 인덱스의 값이 음수가 될 수 있더라구요. 그래서 사실 `-2` 정도면 충분하지만, "절대 나올 수 없는 수" 라는 의미를 강조하기 위해 값을 뻥튀기 시켰습니다.

2023-02-26 11:32 UTC, kokodak commented on src/main/java/domain/LadderGame.java
> +    }
제가 컨벤션을 놓쳤던 것 같습니다.. 다시 통일성 있게 수정했습니다!

2023-02-26 11:54 UTC, kokodak commented on src/main/java/controller/Controller.java
> +        ladderGame.play();
저도 `play()` 메서드를 만들 때 메서드의 이름이 로직과 좀 다른 것 같아서 고민을 했던 것 같아요. 파즈가 보신대로 `final`을 떼야한다는 것 때문에 결국엔 생성자에서 다 처리를 하게 만들었었는데, 확실히 게임의 결과를 만드는 건 `play()` 메서드의 역할인 것 같네요.

추가적으로 궁금한 것이 있는데요! 어떤 내부 필드의 값을 후천적으로 lazy 하게 주게 되면, `final` 키워드를 붙이지 못하고, getter 시에 null의 위험이 있을 것 같은데, 이런 경우는 대부분 안티 패턴에 속하나요? 따라서 차후에 개선해야 할 요소라고 보는게 맞을까요? 아니면 "상황에 따라 그렇게 해야할 수도 있다" 정도일까요?

2023-02-26 11:55 UTC, kokodak commented on src/main/java/domain/Users.java
> +                .filter(user -> user.getName().equals(name))
이런게 있는줄 몰랐네요. 나중에 계속 써보겠습니다!!

2023-02-26 12:08 UTC, kokodak commented on src/main/java/domain/Users.java
> +                .findFirst()
제가 알기로는 `filter`에 걸린 남은 요소들이 복수개 있을 때, `findFirst()`는 맨 처음 요소를 반환하고, `findAny()`는 순서에 상관없이 아무거나 반환하는 것으로 알고 있습니다!

2023-02-26 12:36 UTC, kokodak commented
안녕하세요 파즈!
리뷰해주신 내용을 토대로 리팩터링을 진행해봤습니다.
이번에 리팩터링을 하면서 궁금한 점은 다음과 같습니다!

- `Rewards`가 `Users`에 간접적으로 의존
제 코드에서는 `Rewards` 생성자에 파라미터로 `userCount` 라는 정수값을 받게 되어있는데요, 이런 값을 받게 된 이유는 `User`의 수와 `Reward`의 수가 같아야 한다는 도메인 로직때문이었습니다. 여기서 걸리는 것은, `Rewards`가 생성되려면 `User`의 수를 알고 있어야 한다는 점인데요, `Users`를 파라미터로 직접 받진 않지만, 결국 간접적으로라도 검증만을 위한 의존성이 생긴다는 점이었습니다. 특히나, 그저 입력을 받는 순서가 더 빠르다는 이유로 `Users`는 `Reward`의 개수를 몰라도 되고, `Rewards`는 `User`의 수를 알아야 한다는 점이 이상하게 느껴졌는데, 혹시 이런 문제를 해결할 수 있는 방법이 있을까요?

- VO 사용?
저는 `OutputView`에서 파라미터로 객체를 받고 있는데요, 사실 객체를 가져오는 이유는 getter 사용이 전부인데, 마음만 먹으면 View단에서 원본 객체를 이용해 특정 도메인 로직을 실행시킬 수도 있다는 점이 마음에 걸렸습니다. 이런 경우에는 단순히 정보 전달용(getter만 있는) VO 객체를 따로 만들어서 View에 던져주는게 훨씬 나을까요? 아니면 이것도 오버엔지니어링이 될 수 있는 부분일까요?

- Map을 사용하는 필드 네이밍
이건 좀 사소한 것인데, Map 자료구조를 사용하는 필드 네이밍이 개인적으로 좀 어려웠습니다. 예를 들면 List의 경우, 보통 List 원소 이름의 복수 형태로 네이밍을 하게 되는데, Map도 이러한 네이밍 컨벤션같은게 있을까요?

리뷰해주셔서 고맙습니다 파즈!

2023-02-26 14:57 UTC, Be-poz commented on src/main/java/controller/Controller.java
> +        ladderGame.play();
상황에 따라 그렇게 해야할 수도 있다 입니다. getter 시 null이 걱정되신다면 빈 기본생성자를 만들어 기본생성자를 통해 할당해주고 이후에 내부 값들을 채워주는 메서드를 사용하는 방식으로 할 수도 있을 것 같고, getter 메서드 또는 호출 메서드에서 null 체크를 할 수도 있을것 같습니다.  
``LadderGameResult``의 경우에는 게임 시작 전에는 결과가 없는게 맞으므로 게임 전에는 결과가 비어있는 상태로 있어도 된다고 생각합니다. null이 아니라 size가 0인 map을 할당해놓는 등 여러 방법을 통해서요.

2023-02-26 15:27 UTC, Be-poz commented
안녕하세요 코코닥 리팩토링 잘 봤습니다!  

> 제 코드에서는 Rewards 생성자에 파라미터로 userCount 라는 정수값을 받게 되어있는데요, 이런 값을 받게 된 이유는 User의 수와 Reward의 수가 같아야 한다는 도메인 로직때문이었습니다. 여기서 걸리는 것은, Rewards가 생성되려면 User의 수를 알고 있어야 한다는 점인데요, Users를 파라미터로 직접 받진 않지만, 결국 간접적으로라도 검증만을 위한 의존성이 생긴다는 점이었습니다. 특히나, 그저 입력을 받는 순서가 더 빠르다는 이유로 Users는 Reward의 개수를 몰라도 되고, Rewards는 Users의 수를 알아야 한다는 점이 이상하게 느껴졌는데, 혹시 이런 문제를 해결할 수 있는 방법이 있을까요?

현재 ``Rewards``의 생성자 파라미터로 Users의 size를 넘겨주고 계셔서 고민이신 것 같습니다. 그렇다면 입력된 이름의 개수를 변수에 저장해두고 이 값을 파라미터로 넘기는 방식은 이상하게 느껴지시나요 아니면 정상적으로 느껴지시나요 ?  
Users는 Reward의 개수를 몰라도 된다고 하지만 Users는 입력된 이름을 알아야하고, Rewards도 결국 입력된 이름의 개수를 알아야 합니다.  
결국 두 클래스 모두 입력된 값에 대한 정보는 알아야 된다는 거죠. Users가 Reward의 개수를 몰라도 되고 Rewards는 Users의 수를 알아야 된다랑 조금 핀트가 다른 것 같다고 느껴집니다.  

<Br/>
> 저는 OutputView에서 파라미터로 객체를 받고 있는데요, 사실 객체를 가져오는 이유는 getter 사용이 전부인데, 마음만 먹으면 View단에서 원본 객체를 이용해 특정 도메인 로직을 실행시킬 수도 있다는 점이 마음에 걸렸습니다. 이런 경우에는 단순히 정보 전달용(getter만 있는) VO 객체를 따로 만들어서 View에 던져주는게 훨씬 나을까요? 아니면 이것도 오버엔지니어링이 될 수 있는 부분일까요?

좋은 질문입니다. 이러한 이유 때문에 보통 도메인을 그대로 넘기는 방식은 지양해야 합니다. 이럴 때에 정보 전달을 위한 DTO 객체를 생성해서 view에 던져주는게 일반적이고 오버엔지니어링이 아닙니다. view 담당 클래스의 특정 메서드에서 필요한 값은 한정적인데 갖가지 정보가 담긴 도메인을 던지는 것은 굉장히 불필요한 일이고 위험합니다. 따라서 필요한 값만 매핑 후 던져줍니다. 아마 이후 미션에 해당 내용에 대해서 접할 기회가 있을 것입니다.  

<Br/>
> 이건 좀 사소한 것인데, Map 자료구조를 사용하는 필드 네이밍이 개인적으로 좀 어려웠습니다. 예를 들면 List의 경우, 보통 List 원소 이름의 복수 형태로 네이밍을 하게 되는데, Map도 이러한 네이밍 컨벤션같은게 있을까요?  

저는 해당 map의 정보를 그냥 풀어서 씁니다. 이외에도 valueByKey 이런 형식으로 쓰는 분들도 계시고 keyAndValueMap, valueWithKeyMap 이렇게 사용하시는 경우도 봤네요. 크게 컨벤션이 정해져 있지는 않습니다.

2023-02-26 15:28 UTC, Be-poz requested changes
코코닥 피드백 잘 확인했습니다. 추가적으로 코멘트 달아놓았으니깐 확인해주세요!

2023-02-26 15:28 UTC, Be-poz commented on src/main/java/domain/LadderGameResult.java
> +        return ladderGameResult;
5b0f1dc39186d40d31e84b4e1fa9334f442ee84b  

현재 상태로는 바깥에서 getter 호출 후 한 User의 Reward 값을 변경하면 ``LadderGamerResult``의 Reward도 변경이 되겠군요.

2023-02-27 08:21 UTC, kokodak commented on src/main/java/domain/LadderGameResult.java
> +        return ladderGameResult;
아.. 생성자에서 `Map.copyOf`를 쓰고 있어서 별 문제 없거니 하고 넘어갔었는데, 다른 생성자에서는 이런 과정이 없다는 걸 놓치고 있었네요. `unmodifiableMap`으로 감싸서 반환하도록 수정하였습니다!

2023-02-27 08:40 UTC, kokodak commented
DTO도 적용해보고 싶었는데, 6시까지 다 못할 것 같아서 리팩터링을 다 수행하지는 못한 것 같네요.. 그래도 피드백 남겨주신 것들 잘 봤습니다!

`Rewards` 생성자 같은 경우는, `Users` 생성자처럼 사람 수나 결과 수를 파라미터로 아예 받지 않도록 만들고 싶었습니다.
`public Rewards(final List<Reward> rewards)` 같은 느낌으로요! 뭔가 입력 받는 순서때문에 파라미터가 하나 더 생긴 느낌이라 마음에 걸렸던 것 같습니다. 이건 제가 좀 더 생각해봐야겠네요.

좋은 피드백 주셔서 감사합니다 파즈!

2023-02-28 10:47 UTC, Be-poz approved these changes
안녕하세요 코코닥! 마지막 커밋 하나 추가해주신것 확인했습니다.  
완료된 코멘트들은 모두 resolve conversation을 눌렀는데요, 하나 제가 마지막으로 단 코멘트를 코코닥이 확인했는지 안했는지 불확실해서 남겨뒀습니다!  

제가 알기로는 마지막 리뷰 요청은 2차 미션 자체에 대한 리뷰 요청이고 한 번 요청한 이후에 진행되는 리뷰 핑퐁들은 시간과 상관없는 것으로 알고 있습니다 ! 다음번 미션 때 참고하시면 좋을 것 같습니다 !  

남으신 고민 잘 생각하셔서 얻을 수 있기를 기원합니다! 사다리 게임 수고하셨습니다. 블랙잭도 화이팅입니다!

2023-02-28 10:47 UTC, merged