[2단계 - 사다리 게임 실행] 호이(이건호) 미션 제출합니다.
woowacourse/java-ladder pull request #215
Opened 2023-02-23 11:31 UTC by This2sho

안녕하세요 로운! 호이입니다. 😄  

2단계 미션 완료하였습니다. 잘부탁드립니다!

미션을 하면서 어려웠던점이 "index 대신 객체로 관리한다." 이 부분을 어떻게 해야할 지 모르겠습니다. 
이번 미션에서 `Person`의 위치값으로 `Position`을 사용하였는데, 하다보니 index를 사용하는 것과 차이점을 모르겠습니다.

2023-02-24 10:02 UTC, lowoon requested changes
반가워요 호이! 2단계도 잘 부탁해요 😄 
몇 가지 코멘트 남겼으니 확인해주세요ㅎㅎ
궁금한 점이 생기면 언제든지 DM 혹은 댓글남겨주세요 ^-^

2023-02-24 10:02 UTC, lowoon commented on src/main/java/domain/Position.java
> +        return new Position(value - 1);
Integer처럼 사용이 되고 있는데 다음위치, 이전위치를 반환하도록 할 수 있지 않을까요??  
index를 사용하는 것과 차이를 모르겠다고 했는데요. 이전위치와 다음위치를 객체에게 물어봄으로써 위치에 대한 모든 것들을 위임할 수 있지 않을까요??  
지금처럼 index는 따로 사용하면서 Position을 person에서만 사용한다면 의미가 있을까요??  
만약 좌표라는 위치라면 어떻게 될까요??

2023-02-24 10:02 UTC, lowoon commented on src/main/java/domain/Position.java
> +    public Position plus(Position position) {
테스트에서만 사용되는데요.  
테스트에서만 사용되는 코드가 production코드에 있어도 될까요??

2023-02-24 10:02 UTC, lowoon commented on src/main/java/controller/LadderController.java
> +        Prizes prizes = repeat(() -> prizesRequest(people.getCount()));
이전 https://github.com/woowacourse/java-ladder/pull/93#discussion_r1111703266 에서 controller를 제거하는 것을 추천 드렸는데요.
만약 유지한다고 하면 view가 controller에 있는 것이 맞을까요??
view를 통해 들어오는 입력을 요청이라고 볼 수 있지 않을까요??
controller를 제거해 본다면 아래의 형식을 참고해보면 좋을것 같아요~
```java
names = InputView.receiveNames();
LadderGame ladderGame = new LadderGame(names);

height = InputView.receiveHeght();
result = ladderGame.createLadder(height);

OutputView.showResult(result);
```

2023-02-24 10:02 UTC, lowoon commented on src/main/java/controller/LadderController.java
> +        String personName = repeat(inputView::readPersonName);
String만 반복으로 받는 것이라면 inputview에 있는것이 맞지 않을까요??

2023-02-24 10:02 UTC, lowoon commented on src/main/java/domain/Line.java
> +        return widthIndex >= 1 && movements.get(widthIndex - 1);
최대, 최소는 Position에서 관리할 수 있지 않을까요??
position이 있다면 Map의 형태인 key, value로 관리할 수 있을 것 같구요.  
boolean에 따라 이동과 관련된 것은 ShiftType에서 관리할 수도 있지 않을까 싶어요

2023-02-24 10:02 UTC, lowoon commented on src/main/java/domain/People.java
> +        return new ArrayList<>(people);
`Collections.unmodifiableList(people)`도 가능할 텐데요.  
어떤 차이가 있을까요??

2023-02-24 10:02 UTC, lowoon commented on src/main/java/domain/LadderResults.java
> +    private final List<LadderResult> results;
Map 하나로 관리할 수도 있지 않을까요??

2023-02-24 10:02 UTC, lowoon commented on src/main/java/domain/LadderGame.java
> +    public LadderResults searchResult(String personName) {
결과를 매번 요청하는 것 같은데요.
전체 결과를 outputview에 전달하고 outputivew에서 입력받은 값에 따라 다르게 보여줄 수도 있지 않을까요?

2023-02-24 10:02 UTC, lowoon commented on src/main/java/domain/Person.java
> +            moveRight();
타입에 따라 이동하는 것을 ShiftType에서 관리할 수도 있지 않을까요??

2023-02-24 10:02 UTC, lowoon commented on src/main/java/domain/Line.java
> +    public boolean canGoRight(int widthIndex) {
추가된 메서드에 대해 테스트가 없는 것 같아요

2023-02-25 04:55 UTC, This2sho commented on src/main/java/domain/Position.java
> +    public Position plus(Position position) {
앗. 나중에 사용할 거라고 생각하고 만든 기능인데, 이렇게 설계를 하면 안되겠군요...

2023-02-27 02:38 UTC, This2sho commented on src/main/java/domain/Person.java
> +            moveRight();
Enum에 필드로 함수형 인터페이스를 넣는 방법이 익숙하지 않아서 사용하지 못했는데
확실히 가동성도 좋고 보기도 이쁜거 같습니다

2023-02-27 02:43 UTC, This2sho commented on src/main/java/domain/People.java
> +        return new ArrayList<>(people);
생각해보니 `People`을 `deepCopy`한다고 `Person`도 `deepCopy` 되는게 아니였습니다..
수정하였습니다!

2023-02-27 03:31 UTC, This2sho commented on src/main/java/domain/LadderResults.java
> +    private final List<LadderResult> results;
'all'을 입력했을 때 입력받은 순서대로 출력을 하여서
List를 제일 먼저 떠올렸던거 같습니다.

수정하였습니다!

2023-02-27 03:42 UTC, This2sho commented on src/main/java/controller/LadderController.java
> +        Prizes prizes = repeat(() -> prizesRequest(people.getCount()));
생각해보니 컨트롤러가 view를 알고 있다는게 아닌거 같습니다.
참고하여서 컨트롤러를 제거하였습니다.

2023-02-27 05:11 UTC, This2sho commented on src/main/java/domain/LadderGame.java
> +    public LadderResults searchResult(String personName) {
결과를 한번만 요청하고 결과에 따라 다르게 출력하도록 수정하였습니다.

2023-02-27 06:02 UTC, This2sho commented on src/main/java/domain/Position.java
> +        return new Position(value - 1);
죄송합니다.. 아직 리뷰어님이 말씀하신 방법을 어떻게 구현해야하는지 잘이해가 되지 않습니다 ㅠㅠ
실례가 안된다면 예시를 보여주실수있을까요 ...?

2023-02-27 06:10 UTC, This2sho commented on src/main/java/domain/Line.java
> +    public boolean canGoRight(int widthIndex) {
앗.. 바로 추가하였습니다!

2023-02-28 03:50 UTC, lowoon commented on src/main/java/domain/Position.java
> +        return new Position(value - 1);
Line에서 `List<Boolean>`로 값이 관리되고 있고, game에서 move를 할때고 value를 꺼내서 로직이 진행되는데 Position 객체가 있다면 해당 객체를 활용할 수 있지 않을까요?? 
예시 : `Map<Position, Boolean>`

2023-02-28 03:56 UTC, lowoon approved these changes
안녕하세요 호이!😄
코멘트에 대한 답변으로 수정했다고 하는데 반영이 되어 있지 않은 것 같아요!
push를 누락하신게 아닌가 생각이 드네요 😭 
마지막 리뷰요청이라 그만 체스 미션을 마무리하도록 할게요!
추가로 간단한 코멘트만 남겼으니 확인 부탁드려요.
미션은 끝났지만 궁금한점 있으면 DM이나 코멘트로 남겨주세요!

1, 2단계 호이 미션 수고하셨습니다!

2023-02-28 03:56 UTC, lowoon commented on src/main/java/controller/LadderController.java
> +        Prizes prizes = repeat(() -> prizesRequest(people.getCount()));
제거가 되지 않았네요

2023-02-28 03:56 UTC, lowoon commented on src/main/java/domain/ShiftType.java
> +    LEFT, RIGHT, NO
`Function`으로 type에 맞게 새로운 position을 return하는 메서드를 가지도록 할 수 있을 것 같아요!

2023-02-28 03:56 UTC, lowoon commented on src/main/java/domain/LadderResults.java
> +    private final List<LadderResult> results;
수정이 안되어서 어떻게 적용이 되었는지 모르겟는데요!  
우선 제가 말씀드린 방법은 LadderResult와 LadderResults를 없애도 `Map<String, String>`을 사용하는 방식이였습니다!

2023-02-28 03:56 UTC, lowoon commented on src/main/java/domain/Prizes.java
> +        prizes.forEach(this::validatePrizeName);
개인적인 의견입니다~ 참고만 해주시면 될 것 같아요!
forEach는 주로 js에서 로직을 돌 때 사용되고 서버에서는 출력할 때 주로 사용하는 것 같습니다~
https://tecoble.techcourse.co.kr/post/2020-05-14-foreach-vs-forloop/

2023-02-28 03:57 UTC, merged

2023-02-28 04:25 UTC, This2sho commented
아.. 죄송합니다 로컬에서 새로운 'feedback' 이란 브랜치를 새로 만들어서 진행하다가 merge를 못했네요.. ㅠㅠ