[2단계 - 사다리 게임 실행] 땡칠(박성철) 미션 제출합니다.
woowacourse/java-ladder pull request #229
Opened 2023-02-24 01:39 UTC by 0chil

구현보다 어떻게 개선할지 고민하는 시간이 길었는데, 고민한 시간만큼 개선되지는 않은 것 같습니다.
장고 끝에 악수를 두었을 수도 있으니 아주 직설적!인 리뷰 부탁드립니다.

2023-02-24 06:40 UTC, 0chil commented on src/main/java/domain/Position.java
> +    }
from, to 를 인자로 받는 대신 이런 메서드를 만들면 어떨까요?

2023-02-24 06:40 UTC, 0chil commented on src/main/java/domain/Line.java
> +    }
이 코드는 사다리 구성요소 개수의 차이에서 발생하는데, 현재는 코드에 그 내용이 잘 녹아있지 않아서 마음에 들지 않습니다 ㅠㅠ
![image](https://user-images.githubusercontent.com/39221443/221102919-4d5566f6-05cc-43e5-a468-418dfa6bdbc0.png)
어떻게 둘의 차이를 코드에 잘 녹여낼지 고민해보았지만 아직도 해결하지 못했습니다..

2023-02-24 06:40 UTC, 0chil commented on src/main/java/view/SearchTarget.java
> +}
"all"이라는 키워드 자체가 입출력에 관련된, '명령어'에 가까운 키워드라고 생각해서 이를 해석하기 위한 객체와 로직을 view 패키지에 두었습니다.
이런 객체를 만들어도 문제 없을까요?

2023-02-25 14:48 UTC, Hyeon9mak requested changes
안녕하세요 땡칠~ 리뷰가 많이 늦었어요 🙏 
사다리 타기 게임 2단계 미션도 고생 많으셨어요.

함께 더 고민해보고 싶은 부분에 코멘트 남겼습니다!
아래는 질문 주신 부분들에 대한 제 생각이에요.

> 읽기 좋은 코드가 이해하기도, 고치기도 좋다고 생각하기 때문입니다.
“line, position을 움직여” 보다 “position, line을 따라가”가 더 말이 맞다고 생각해요
Line을 따라가는 행위의 주체가 Position이기 때문입니다.

아, 저는 너~~~~~~~~~~~~~~~~~무 좋은 이유라고 생각해요.
사실 객체지향은 모두가 알고 있는 일반적인 지식을 유지보수가 용이한 형태로 만드는, 공감대를 만드는 행위라고 생각해요. 그래서 line 이 position 에 따라 움직이기보다 position 이 line 에 따라 움직이게 바꿀 수 있다면 그렇게 하는게 사람이 코드를 읽고 머리 속으로 그림을 그려보는데 인지하는데 더 도움이 될거 같아요.

> 하지만 점점 더 복잡해지는 것 같은데요..
이런 고민을 하게 된 이유가 어쩌면 설계가 잘못되어서? 혹은 값 포장을 너무 이른 시기에 해버려서? 일수도 있다고 생각이 드는데, 현구막은 이런 상황에 도달하면 어떻게 헤쳐나가시나요?

고민이 너무 깊어져서 고도로 추상화를 하다보면 점점 읽기 어렵고 복잡한 코드가 완성되죠. 그럼 후회가 되고 '안하느니만 못한데... 괜히 했나?' 라는 생각이 드는게 맞습니다. 그런데 중요하게 짚어봐야할 건 우리가 객체지향을 왜 도입하는지에요. 우리는 읽기 좋은 코드, 예술적은 코드를 짜기 위해 객체지향을 고수하는게 아닌거 같아요. 요구사항의 변화가 일어났을 때 변경 해야할 파일의 개수가 적은, 개발자가 인지해야할 범위가 좁은, 유지보수 하기 쉬운 코드를 작성하기 위함인거 같아요.

땡칠은 처음 자바코드를 접하셨을 때가 기억나시나요? 저는 c 로 절차지향 코드만 짜다가 자바코드를 처음 접했을 때의 막막함을 잊지 못합니다. "도대체 코드가 왜 여기서 끝나?", "쟤는 저만큼 긴데 얘는 왜 이거 밖에 없어?" 너무 복잡하고 어려웠어요. 객체지향 코드는 원래 읽기 어렵습니다. 인간 사고의 흐름대로 주욱 따라가는 절차지향과 다르게 조금 동작하고 다른 객체에 넘기고, 또 다른 객체에 넘기고... 그런데 처음 읽기가 어려울 뿐 한번 머리 속에 구조가 잡히고 나면 그 후엔 오히려 탐색이 더 쉬워지는 효과가 생기죠. 전체를 다 읽을 필요 없이 중요한 부분만 읽으면 된다는 걸 알게 되니까요. (마치 인덱스 구조처럼)

"사타리 타기 게임은 이런 부분에서 자주 변경이 발생할 것이고, 나는 이 부분의 유지보수성을 끌어올리기 위해 읽기 쉬운 코드를 작성했어. 그런데 그러다 보니 다른 부분의 복잡도가 높아진거 같아.." 라면 응원하고 싶어요.
 "나는 읽기 쉬운 코드를 만들고 있었어. 그런데 (무아지경에 빠져) 만들다보니 어느 순간 의도와 다르게 복잡도가 함께 증가하기 시작했어." 라면 혹시나 공학이 아닌 예술을 하고 있는 건 아닌지 되짚어보시면 좋을 것 같아요.

궁금하신 점 언제든지 DM, 코멘트 남겨주세요 🙇‍♂️

2023-02-25 14:48 UTC, Hyeon9mak commented on README.md
사다리에 대한 제약사항이 보충되었군용 👍

2023-02-25 14:48 UTC, Hyeon9mak commented on README.md
> +- [x] 어떤 방향으로 움직인다.
코드상에서 사용되는 객체명과 실제 사물의 명칭이 혼용된 것 같은데 통일되면 어떨까요?

2023-02-25 14:48 UTC, Hyeon9mak commented on src/main/java/domain/Ladder.java
> +    }
if 키워드 사이에 들어간 `!` 는 잘 보이지 않는 편이라, `isNotWidthEven` 이나 `isWidthOdd` 로 표현해주면 어떨까요?

2023-02-25 14:48 UTC, Hyeon9mak commented on src/main/java/domain/LadderGame.java
> +    }
상품은 참가자, 사다리와 다르게 일급으로 포장하지 않은 이유가 있을까요?

2023-02-25 14:48 UTC, Hyeon9mak commented on src/main/java/domain/LadderGame.java
> +    }
에러 메세지가 빠진 것 같아요 😉

2023-02-25 14:48 UTC, Hyeon9mak commented on src/main/java/domain/Line.java
> +    }
당장 떠오르는 방법은 `EXIST` 또는 `EMPTY` 로 이루어진 List 컬렉션을 좌우개념을 가진 값 객체 List 컬렉션으로 대체해보면 되지 않을까 싶어요.

```java
public class Pole {
    private final Bridge left;
    private final Bridge right;
    
    public Pole(Bridge left, Bridge right) {
        this.left = left;
        this.right = right;
    }
}
```

마음에 들지 않는 이유가 무엇일까요?

2023-02-25 14:48 UTC, Hyeon9mak commented on src/main/java/domain/Participants.java
> +    }
일급 컬렉션 아주 기똥차게 쓰시네요 💯

2023-02-25 14:48 UTC, Hyeon9mak commented on src/main/java/domain/Position.java
> +    }
오.. package private 접근제한자 활용 👍

2023-02-25 14:48 UTC, Hyeon9mak commented on src/main/java/domain/Position.java
> +    }
무슨 말씀이신지 잘 모르겠네요 😵 조금 더 자세한 설명 부탁드릴게요.

2023-02-25 14:48 UTC, Hyeon9mak commented on src/main/java/engine/LadderEngine.java
> +    }
`LadderEngine` 에서 `Map<String, String>` 형태로 반환하는 건 어떤 형태로 결과를 출력할지 `LadderEngine`이 모두 인지하고 있다는 것 아닐까요? 출력 형태가 변경되면 앞으로 `LadderEngine`도 영향을 받을 것 같아요.

2023-02-25 14:48 UTC, Hyeon9mak commented on src/main/java/view/SearchTarget.java
> +}
저는 "all" 키워드에 대해 따로 명세화하여 클래스로 분리한 것에 대해 너무 훌륭하다고 생각합니다. 다만 그게 `SearchTarget` 이라는 명칭으로 사용자의 이름과 함께 쓰일 내용인지는 잘 모르겠어요. 

보통 "사용자가 입력할 수 있는 명령어들은 뭐가 있지?" 라는 생각으로 `ALL` 명령어를 찾지 않을까 싶어요. 명령어를 모아둔 enum class 라던지...

> 어떤 데이터를 물어봤을 때 누가 대답하는게 좋을거 같아 라고 사람들이 비슷한 이해를 가지는게 진짜 ‘정보’다. 
**객체지향은 모두가 알고 있는 일반적인 지식으로 유지보수가 용이하게 만드는 것. 공감대를 만드는 행위다.**

2023-02-25 14:48 UTC, Hyeon9mak commented on src/test/java/domain/LadderGameTest.java
> +    void 참가자_수_경품_수가_같아야한다() {
오. 메서드 명칭을 이렇게 사용하면 꼭 `@DisplayName`이 없어도 되죠. 대신 아래처럼 IDE 의 도움을 받기는 힘들다는 단점도 존재는 하는 것 같아요.

<img width="469" alt="image" src="https://user-images.githubusercontent.com/37354145/221362136-eed9ca2c-f9ca-4ecb-8095-88b6f9abb2f1.png">

2023-02-27 06:36 UTC, 0chil commented on src/main/java/domain/Position.java
> +    }
설명이 부족했네요 😅
```java
    public boolean isInRangeOf(int fromInclusive, int toExclusive) {
        return fromInclusive <= position && position < toExclusive;
    }
```
vs
```java
    public boolean isInRangeOf(Collection<?> collection) {
        return 0 <= position && position < collection.size();
    }
```
이런 얘기였습니다!

2023-02-27 06:38 UTC, 0chil commented on src/main/java/domain/Line.java
> +    }
제 코드를 처음 보는 사람이 
"왜 왼쪽 다리는 position.left()에서 가져오고, 오른쪽다리는 position 에서 바로 가져오지?"
이런 의문을 가질 수 있을 것 같아요.
그리고 저는 이 의문을 해소해주기 위해 제 사다리가 어떤 구조를 가지고 있는지 하나하나 설명해야 할 것 같습니다.

2023-02-27 06:46 UTC, 0chil commented on README.md
> +- [x] 어떤 방향으로 움직인다.
하나로 통일하는 편이 좋을 것 같네요. 연상을 쉽게 할 수 있도록 사물 명칭으로 바꿔보겠습니다!

2023-02-27 06:48 UTC, 0chil commented on src/main/java/domain/Ladder.java
> +    }
이 `!` 가 때에 따라서는 엄청 중요한 휴먼 에러를 야기할수도 있겠네요..!
그렇게 고쳐보겠습니다!

2023-02-27 12:06 UTC, 0chil commented on src/main/java/domain/LadderGame.java
> +    }
앗.. 추가했습니다!

2023-02-27 12:20 UTC, 0chil commented on src/main/java/domain/Participants.java
> +    }
어떤 측면에서 잘 사용했다고 느끼셨는지 여쭤봐도 될까요?
무의식적으로 짠 코드라서 어떤 측면이 좋았는지 알면 좋은 피드백이 될 것 같습니다.

2023-02-27 13:25 UTC, 0chil commented on src/main/java/domain/LadderGame.java
> +    }
상품 일급 컬렉션이 가지는 역할이 딱히 없다고 생각해서 포장하지 않았습니다.
하지만 
- 특정 위치의 상품을 조회하는 역할
  - `String getPrizeAt(Position position)`
- 특정 크기를 가지는지 확인하는 역할
  - `prizes.size() != participantsCount`

을 부여해 LadderGame의 역할을 더 명확하게 할 수 있는 장점이 있는 것 같아 일급 컬렉션으로 포장해보겠습니다.

2023-02-27 13:48 UTC, 0chil commented on src/test/java/domain/LadderGameTest.java
> +    void 참가자_수_경품_수가_같아야한다() {
이렇게 테스트를 만들면 `@DisplayName`을 작성하는 귀찮음..을 배제할 수 있다는 장점이 있지만
테스트 이름을 바꾸기 어렵거나, IDE에서 읽기 어렵다는 단점도 있을 수 있을 것 같습니다!
Parameterized Test는 특히 보기가 어려울 것 같아 name을 적용해 보았습니다.

2023-03-01 16:26 UTC, 0chil commented on src/main/java/view/SearchTarget.java
> +}
해당 부분은 다음과 같이 enum 으로 분리하여 상수 취급해 개선해 보았습니다.

```java
public enum Command {

    ALL("all");
    
    // ...

    public static boolean isAll(String input) {
        if (isNotCommand(input)) {
            return false;
        }
        return ALL.hasCommand(input);
    }
    // ...
}
```


```java
public class SearchTarget {

    // ...

    public boolean isAll() {
        return Command.isAll(target);
    }
    // ...
}
```

2023-03-01 16:55 UTC, 0chil commented on src/main/java/engine/LadderEngine.java
> +    }
출력 형태를 인지하지 않게 하기 위해 2가지를 적용해보았는데요,
- `Result` 라는 DTO 객체에 이를 출력 형태로 변환할 책임을 넘겼고,
- for-each loop에 `var` 키워드를 사용하여 형태를 자동으로 유추하도록 해보았습니다.

```java
    private List<Result> getResults(LadderGame ladderGame, SearchTarget searchTarget) {
        if (searchTarget.isAll()) {
            return getAllResultsOf(ladderGame);
        }
        String searchTargetName = searchTarget.getName();
        Result result = new Result(searchTargetName, ladderGame.findPrizeFor(searchTargetName));
        return List.of(result);
    }

    private List<Result> getAllResultsOf(LadderGame ladderGame) {
        List<Result> results = new ArrayList<>();
        for (var name : ladderGame.getParticipantNames()) {
            Result result = new Result(name, ladderGame.findPrizeFor(name));
            results.add(result);
        }
        return results;
    }
```

2023-03-01 17:04 UTC, 0chil commented
안녕하세요 현구막, 마지막 리뷰 요청이 많이 늦어서 죄송합니다! 이번 미션에서 쉽게 결정하기 힘든 고민들이 많았어요. 
하고 있는건 맞는지 신경쓰이셨을 것 같아요 😅

우선 현구막이 질문하신 부분을 나누어 링크해보았습니다.

## 질문에 답하고 반영한 커멘트

- 왼쪽 다리는 `position.left()`, 오른쪽 다리는 `position` 이 마음에 들지 않았던 이유?

[https://github.com/woowacourse/java-ladder/pull/229#discussion_r1118335267](https://github.com/woowacourse/java-ladder/pull/229#discussion_r1118335267)

- 기능 목록에 객체명과 사물명이 혼용되었음

[https://github.com/woowacourse/java-ladder/pull/229#discussion_r1117927129](https://github.com/woowacourse/java-ladder/pull/229#discussion_r1117927129)

- if 키워드 사이에 들어간 `!`

[https://github.com/woowacourse/java-ladder/pull/229#discussion_r1117927337](https://github.com/woowacourse/java-ladder/pull/229#discussion_r1117927337)

- “all” 키워드를 클래스로 표현

[https://github.com/woowacourse/java-ladder/pull/229#discussion_r1117931397](https://github.com/woowacourse/java-ladder/pull/229#discussion_r1117931397)

- `LadderEngine` 이 `Map<String,String>` 으로 반환하면, 출력 형식을 인지하고 있는 것이다.

[https://github.com/woowacourse/java-ladder/pull/229#discussion_r1117930935](https://github.com/woowacourse/java-ladder/pull/229#discussion_r1117930935)

- 상품은 참가자, 사다리와 다르게 일급으로 포장하지 않은 이유?

[https://github.com/woowacourse/java-ladder/pull/229#discussion_r1118731818](https://github.com/woowacourse/java-ladder/pull/229#discussion_r1118731818)

- `@DisplayName`은 없어도 되지만..

[https://github.com/woowacourse/java-ladder/pull/229#discussion_r1117931572](https://github.com/woowacourse/java-ladder/pull/229#discussion_r1117931572)

## 다시 질문한 커멘트

- from, to 를 인자로 받는 대신 이런 메서드를 만들면 어떨까요?

[https://github.com/woowacourse/java-ladder/pull/229#discussion_r1118333918](https://github.com/woowacourse/java-ladder/pull/229#discussion_r1118333918)

- 일급 컬렉션을 어떤 측면에서 잘 사용했다고 느끼셨는지 질문!

[https://github.com/woowacourse/java-ladder/pull/229#discussion_r1118664622](https://github.com/woowacourse/java-ladder/pull/229#discussion_r1118664622)

## 커멘트를 읽고
### 반성한 점

> 모두가 알고 있는 일반적인 지식으로 유지보수가 용이하게 만드는 것
> 

이 말이 여러 고민에 많이 와닿았습니다. 이렇게 하기 위해 객체지향을 도입한 것이겠죠.

> 그런데 중요하게 짚어봐야할 건 우리가 객체지향을 왜 도입하는지에요. 우리는 읽기 좋은 코드, 예술적은 코드를 짜기 위해 객체지향을 고수하는게 아닌거 같아요. 요구사항의 변화가 일어났을 때 변경 해야할 파일의 개수가 적은, 개발자가 인지해야할 범위가 좁은, 유지보수 하기 쉬운 코드를 작성하기 위함인거 같아요.
> 

> "나는 읽기 쉬운 코드를 만들고 있었어. 그런데 (무아지경에 빠져) 만들다보니 어느 순간 의도와 다르게 복잡도가 함께 증가하기 시작했어." 라면 혹시나 공학이 아닌 예술을 하고 있는 건 아닌지 되짚어보시면 좋을 것 같아요.
> 

남겨주신 커멘트를 보고 "정신차려!" 하는 느낌이라 감사했습니다.
사실 `코드 == 글`도 아니고 항상 문법, 어순까지 맞게 읽혀야 하는 건 아닌것 같아요. 

어떤 개념을 읽기 쉽게 표현하고자 필요 이상으로 복잡해질 필요도 없는 것 같구요!

왜 객체지향을 쓰고, 추상화를 더 잘하기 위해 무엇을 고려해야할지 고민하면서 ‘객체지향의 사실과 오해’를 더 읽어봐야겠습니다.

> 혹시나 공학이 아닌 예술을 하고 있는 건 아닌지
> 

뜨끔했습니다. 무엇이 우선인지, 무엇을 위해 코드를 잘 작성하고 싶은 것인지 다시 생각하게 되었습니다.

솔직하게 얘기하면 https://github.com/woowacourse/java-ladder/pull/229#discussion_r1118335267 때문에 ‘연결점, Point’ 라는 개념도 구현했었는데,

<img src="https://user-images.githubusercontent.com/39221443/222209964-a8ebd02b-a2ae-442f-ac30-803365f31f53.png" width="300">

“과연 이 표현 하나를 이해시키기 위해 이렇게까지 복잡해져야 하는것인가?” → X

“정말 더 쉽게 이해되는 것이 맞는가?” → X

“정말 유지보수가 더 쉬워지는 것이 맞는가?” → X

“공학을 하고 있는 것이 맞는가?” → X

자문을 해보고, 아니라고 생각해 처음 리뷰 요청드렸던 상태로 돌아가 리뷰를 마저 반영했습니다.

어쩌면 극단적인 시도를 해보면서 무엇이 중요한 것인지 좀 느낀 것 같습니다.

### 감사한 점

제 고민이나 질문이 추상적이기도 하고, 구체적으로 표현하지 못해서 어쩌면 불친절한 질문들로 보였을 것 같아요.
그러나 현구막의 세심한 리뷰와 혜안 덕에 소중한 고민들을 해볼 수 있었습니다.
앞으로 질문을 더 잘하기 위해 노력하고, 무언가에 빠져들 때 "이걸 왜 하고 있을까?", "내가 정말 하려는 것이 뭘까?" 고민해보겠습니다.

감사합니다.

2023-03-02 07:50 UTC, Hyeon9mak commented on src/main/java/domain/Position.java
> +    }
외부에서 읽을 때 `position.isInRangeOf(bridges)` 로 읽히는군요. 😮 👍 "너 여기 포함되니?" 묻는 것 같아 멋있어요. 그런데 파라미터로 `Collections<?>` 타입을 사용하신 것에 대해 2가지 고민이 생깁니다.

1. `Collection<?>` 타입으로 넘어오는 데이터에서 위치정보에 대한 값을 음수로도 표기한다면 의도한대로 동작하지 않을 것 같아요.
2. `Position` 객체는 사다리 타기에 귀속된 도메인 같은데요, `isInRangeOf()` 메서드가 다른 방법으로 재사용 될 가능성이 얼마나 높을까요? 굳이 `Collection<?>` 타입일 필요가 있을까요?

2번 고민에 대해서는 제 생각을 공유해볼게요.

## 1. 개발자 의식의 흐름 관련
대부분 (저를 포함한) 개발자들은 저명한 라이브러리나 프레임워크가 제공하는 기능이 아니고서야 기존에 다른 개발자가 만들어둔 기능을 확인하고 사용하기보다, 자신이 이해하고 있는 컨텍스트를 기반으로 비슷하지만 다른 이름을 가진 메서드를 새로 만들어서 개발하는 걸 선호하더라구요. (사실 선호한다기보단 확인할 시간이 없고, 이해하고 사용할 시간이 없기 때문인거 같아요. 😅) 

긴급하게 일정에 맞춰 개발하다가 요구사항이 변경되어 메서드를 변경해야할 일이 생기면, 기존에 다른 코드들이 해당 메서드를 사용중이므로 함부러 리팩터링도 어렵구요. 그래서 완전히 동일하게 동작하더라도 컨텍스트가 다르다면 완전히 다른 이름의 메서드를 만드는 쪽입니다. 중복 코드를 줄여서 얻는 코스트보다 개발자가 컨텍스트를 고려하고 이해하고 신경쓰는 코스트가 훨씬 높은 세상이니까요.

## 2. 넓은 의미의 객체와 좁은 의미의 객체
이건 회원가입 도메인을 예시로 들면 더 좋을 것 같아요.

회원을 뜻하는 `Member` 객체를 영속화하는 서비스 클래스 `MemberCreateService` 입니다. 최초로 만들어진 의도는 회원가입 기능을 위해서고 앞으로도 `Member` 객체 영속화와 관련된 내용은 모두 `MemberCreateService` 가 처리할 예정이에요. 때문에 아래와 같이 패키지 구조를 갖추고 있었어요.

<img width="291" alt="image" src="https://user-images.githubusercontent.com/37354145/222360581-696e3a1a-063e-49a3-b8df-3223ac7a33f8.png">

아마 코드는 아래와 같겠죠.

```java
public class MemberCreateService {

    private final MemberRepository memberRepository;

    public MemberCreateService(MemberRepository memberRepository) {
        this.memberRepository = memberRepository;
    }

    public void create() {
        // 회원가입 로직
    }
}
```

그 상태에서 CX 팀 요구사항이 인입됩니다.
"회원가입을 어려워하시는 분들이 계셔서, 어드민에서 직접 회원가입 후 계정 발급을 해드릴 수 있을까요?"

```java
public class MemberCreateService {

    private final MemberRepository memberRepository;

    public MemberCreateService(MemberRepository memberRepository) {
        this.memberRepository = memberRepository;
    }

    public void create() {
        // 회원가입 로직
    }
    
    public void createByAdmin() {
        // 어드민 회원가입 로직
    }
}
```

또 하나의 요구사항이 인입됩니다.
"QA 편의를 위해 시스템에서 미리 회원계정을 발급해두면 어떨까요?"

```java
public class MemberCreateService {

    private final MemberRepository memberRepository;

    public MemberCreateService(MemberRepository memberRepository) {
        this.memberRepository = memberRepository;
    }

    public void create() {
        // 회원가입 로직
    }

    public void createByAdmin() {
        // 어드민 회원가입 로직
    }
    
    public void createBySystem() {
        // 자동 회원가입 로직
    }
}
```

간결한 예시지만, 각 회원가입을 위한 private 메서드, 다른 객체 의존 등이 추가되면 `MemberCreateService` 는 벌써부터 한 눈에 읽기 어려운 클래스가 되죠. 게다가 각각의 로직을 수정하려 할 때 똑같이 `MemberCreateService` 클래스 파일을 수정해야합니다. SRP 원칙이 깨지고, 동시에 두 명의 개발자가 `MemberCreateService` 를 건드리면 Merge Conflict 위험도가 높아집니다. 가장 중요한건 동료개발자가 "사용자에 의한 회원가입 로직을 찾고싶어!" 라고 할 때 `member.service.MemberCreateService` 라는 경로만으로는 확신을 갖고 찾기 어려워요. `MemberCreateService` 의 기능 범위가 너무 넓기 때문이에요.

이걸 좁은 범위의 클래스로 쪼개면 아래와 같이 될 것 같아요.

<img width="282" alt="image" src="https://user-images.githubusercontent.com/37354145/222363233-f6d4cc52-6522-4680-b146-496ab849dda3.png">

결론은 `Collection<?>` 타입을 파라미터로 받는 부분이 `Position`이 단순히 사다리 타기 게임의 포지션을 넘어서 더 넓은 의미의 포지션이 되기 위해 준비하는 형태가 아닌지, 꼭 그럴 필요가 있는지 질문 드리고 싶었어요.

2023-03-02 07:57 UTC, Hyeon9mak commented on src/main/java/domain/LadderGame.java
> +    }
아하! 땡칠의 의도가 가장 중요하지만 제가 읽었을 때 '얘는 계층구조가 왜 다르지? 뭔가 조금 더 특별히 관리되나?' 라는 생각이 들어서 질문드렸어요 😄

2023-03-02 08:02 UTC, Hyeon9mak commented on src/main/java/domain/Participants.java
> +    }
저는 일급 컬렉션이 "컬렉션이 컬렉션 그 이상의 역할을 수행하려고 할 때 일급 컬렉션을 쓰면 좋다." 라고 생각해요. 여기서 그 이상의 역할이란 '컬렉션이 비즈니스 로직에 핏한 무언가를 해내려고 할 때', '그러다 보니 컬렉션을 다루는 로직이 복잡해질 때' 입니다.

'컬렉션이 비즈니스 로직에 핏한 무언가를 해내려고 할 때'는 여러가지가 있겠지만 가장 간단한 예시로는, 메서드로 네이밍을 부여하는 건데요.

```java
List<Person> people;
people.size();

People people;
people.count();
```

이런 식으로 컬렉션이 비즈니스에 핏한 형태로 역할을 수행해줄 수 있겠죠.

'컬렉션을 다루는 로직이 복잡해질 때'는 땡칠이 `findPositionOf`, `findBy` 와 같은 메서드로 동작을 포장해주신게 좋은 예시 같아요. 그렇지 않았다면 해당 메서드들이 `List<Participant> participants`를 사용하는 모든 곳에서 필요했을테니까요.

2023-03-02 08:08 UTC, Hyeon9mak commented on src/main/java/engine/LadderEngine.java
> +    }
- 적절한 부분에 DTO 활용 👍 
- 음.. 🤔 `ladderGame.getParticipantNames()` 로 반환되는 타입이 `List<String>` 으로 확정되고, 사용되는 `Result` 도 `String` 을 필요로 하는데 굳이 `var` 로 변동 가능성이 있음을 표현할 필요가 있을까요? 오히려 출처와 사용처 모두 `String` 이므로 `name` 또한 `String` 을 사용해서 타입 안정성을 확보하는게 더 낫지 않을까요?

2023-03-02 08:11 UTC, Hyeon9mak commented on src/test/java/domain/LadderGameTest.java
> +    void 참가자_수_경품_수가_같아야한다() {
자연스럽게 다음 코멘트로 알려드리려했는데.. 제 즐거움을 앗아가셨군요.. 😄 👍

2023-03-02 08:14 UTC, Hyeon9mak commented on src/test/java/domain/LadderGameTest.java
> +    void 참가자_수_경품_수가_같아야한다() {
https://velog.io/@max9106/IntelliJ-Live-Template 요런것도 있습니다 👍

2023-03-02 08:31 UTC, Hyeon9mak requested changes
안녕하세요 땡칠~ PR 에 관련된 알림을 받고 있었어서 잘하고 계신다고 생각중이었어요 💪 😄 

다른 크루들 코드 리뷰를 하다가 발견한 재밌는 엣지 케이스가 있는데요! 
요것도 해결 후 다시 리뷰요청 주시면 좋겠습니다 😄 

<img width="581" alt="image" src="https://user-images.githubusercontent.com/37354145/222370935-f7f32ba0-1734-4508-b0f0-e32142f63101.png">

아래는 코멘트들에 대한 답변이에요.

- https://github.com/woowacourse/java-ladder/pull/229#discussion_r1122709373
- https://github.com/woowacourse/java-ladder/pull/229#discussion_r1122715529
- https://github.com/woowacourse/java-ladder/pull/229#discussion_r1122719616
- https://github.com/woowacourse/java-ladder/pull/229#discussion_r1122725729
- https://github.com/woowacourse/java-ladder/pull/229#discussion_r1122728531

> 처음 리뷰 요청드렸던 상태로 돌아가 리뷰를 마저 반영했습니다.
어쩌면 극단적인 시도를 해보면서 무엇이 중요한 것인지 좀 느낀 것 같습니다.

이런저런 시도를 하시면서 발생되는 작업량이 적지 않았을텐데, 지치지 않고 끝까지 해내시는 모습 너무 멋지고 저도 배웁니다! 💪 

땡칠이 하시는 고민들이 제가 하던 고민들과  굉장히 유사한거 같아서 요즘 제가 하고 있는 생각을 솔직하게 공유드렸어요. 그래도 적당히 유지보수 하기 쉬운 코드를 후루룩 짜고, 크루들과 친목을 다지는데 시간을 쓰는게 객체지향의 최종목표라는 걸 잊지 않으셨으면 좋겠어요 😄 👍

궁금하신 점 언제든지 코멘트, DM 남겨주세요~ 🙇‍♂️

2023-03-02 08:31 UTC, Hyeon9mak commented on src/main/java/constant/Command.java
> +    }
"all" 입력을 통해 명령을 전달하는 `Command` 클래스는 `ALL` 이라는 명령을 통해 프로그램의 흐름을 통제하는 녀석으로 보여요.

"all" 입력을 중심으로 생각한다면 `view`에 가깝고, `ALL` 상수를 중심으로 생각한다면 `engine`에 가깝게 느껴지는데, 땡칠은 '상수' 라는 패키지를 만든 이유가 있을까요? (땡칠의 생각을 묻는 질문)

2023-03-02 08:31 UTC, Hyeon9mak commented on src/main/java/domain/Ladder.java
> +
`Generator`들은 결국 사다리타기 게임 규칙에 맞게 도메인을 생성하는 역할을 가진 것 같아요. 별개로 `generator` 라는 패키지로 분리된 배경이 있을까요?

2023-03-04 06:30 UTC, 0chil commented on src/test/java/domain/LadderGameTest.java
> +    void 참가자_수_경품_수가_같아야한다() {
ㅎㅎㅎ 아쉽네요🥲
Live Template을 활용할 곳이 많을 것 같아요. preset만 사용가능한 줄 알았는데 커스텀이 되다니,..
`org.junit.jupiter.api.DisplayNameGenerator`라는 클래스도 발견해서 이것들을 잘 조합해 사용하면 테스트 코드 작성에만 집중 할 수 있을 것 같습니다. 👍

2023-03-04 06:37 UTC, 0chil commented on src/main/java/domain/Participants.java
> +    }
>  '컬렉션이 비즈니스 로직에 핏한 무언가를 해내려고 할 때', '그러다 보니 컬렉션을 다루는 로직이 복잡해질 때' 

절로 고개가 끄덕끄덕x5 하는 기준인 것 같습니다. 
블랙잭 미션에서도 다시 이런 방식을 사용했는데, '참가자' 클래스에 이름으로 조회하는 행위를 함께 포장한 점이 마음에 들어 사용하게 되었습니다.

2023-03-04 08:01 UTC, 0chil commented on src/main/java/engine/LadderEngine.java
> +    }
> 음.. 🤔 ladderGame.getParticipantNames() 로 반환되는 타입이 List<String> 으로 확정되고, 사용되는 Result 도 String 을 필요로 하는데 굳이 var 로 변동 가능성이 있음을 표현할 필요가 있을까요? 오히려 출처와 사용처 모두 String 이므로 name 또한 String 을 사용해서 타입 안정성을 확보하는게 더 낫지 않을까요?

### 잘못 생각한 점
'어떤 형태로 결과를 출력할지 LadderEngine이 모두 인지한다' 측면에서 접근했는데,
`String`으로 한다면 여전히 알고 있게 된다고 잘못 생각했습니다.😅 
이건 도메인에서 온 타입이기 때문에 `LadderEngine`이 출력 형식을 알게되는 상황은 아닐 것 같습니다!

### 타입 안정성 측면
`var`는 와일드카드 `?`와 달리 컴파일 타임에 타입이 이미 결정되기 때문에 형 안정성에 문제가 없다고 생각하고 있어요.
그리고 코드 차원의 유연성을 높여 관리 포인트를 줄여주는 효과가 있다고 생각하고 있습니다.

`var`는 '지역 변수 타입 추론' 이므로, 다른 메서드(인자)나 클래스로 추론이 전파되지 않는 것으로 알고 있습니다.
따라서 `Result` 생성자가 받는 타입이 바뀌거나, 
<img width="554" alt="image" src="https://user-images.githubusercontent.com/39221443/222881977-01f274f4-1ce9-4aab-bc70-27b2dc488e3f.png">

`ladderGame.getPartiticpantNames()`의 반환형이 바뀌어 `List<Object>`로 추론하는 상황이 되어도,
아래처럼 컴파일이 불가한 상황이 되어 형 안정성에는 문제가 없다고 생각이 듭니다.
<img width="549" alt="image" src="https://user-images.githubusercontent.com/39221443/222882448-b6485fa2-36fc-4e91-8258-c3e7a4fc438d.png">

### 결론, 코드를 보는 입장에서..
`var`로 추론한 변수를 가지고 다른 일을 하게 된다면, 인간이 어떤 타입인지 한번에 추론하기가 어려운 점이 조금 불편합니다.😂
```java
    private List<Result> getAllResultsOf(LadderGame ladderGame) {
        List<Result> results = new ArrayList<>();
        for (var name : ladderGame.getParticipantNames()) {
            name.repeat(1234);
            name.doSomething();
            Result result = new Result(name, ladderGame.findPrizeFor(name));
            results.add(result);
        }
        return results;
    }
```
그래서 저는 결국 이 메서드에서 `var`를 사용하지 않기로 결정했습니다.

2023-03-04 08:12 UTC, 0chil commented on src/main/java/domain/Position.java
> +    }
> Collection<?> 타입으로 넘어오는 데이터에서 위치정보에 대한 값을 음수로도 표기한다면 의도한대로 동작하지 않을 것 같아요.

`Collection<?>` 타입으로 넘어오는 데이터에서 사용하는 값/메서드는 `collection.size()` 밖에 없고,
`Position::isInRangeOf()` 메서드 안의 `position`은 인스턴스 변수이므로 괜찮을 것 같아요.
`collection`에서 가져온 데이터의 `position`을 사용한다고 오해하신 것이 아닐까 싶습니다 😅
그만큼 일반적이지 못한 형태인 것 같기도 합니다.🥲

> Position 객체는 사다리 타기에 귀속된 도메인 같은데요, isInRangeOf() 메서드가 다른 방법으로 재사용 될 가능성이 얼마나 높을까요? 굳이 Collection<?> 타입일 필요가 있을까요?
1.
2.

최근 읽고 있는 책 'Good code, Bad code'과 대비되는 내용이라서 인상깊었어요. 이미 다른 개발자가 구현한 내용을 다시 구현하지 말라는 내용이 있었는데, 항상 그래야 하는 것은 아닐 수도 있겠다는 생각이 들었습니다. 
다른 개발자의 코드를 이해하고 사용하는 코스트도 있고, 다른 개발자의 코드가 어떻게 변할지 확실치 않은데 의존하기 어려울 수도 있겠다고 생각했습니다.
또 정확히 같은 행위라도 컨텍스트가 다르면 다른 메서드가 될 수도 있을 것 같습니다.

또 `Position`이 더 넓은 의미의 객체가 되기 위해 준비할 필요가 전혀 없는 것 같습니다.
그래서 `Collection<?>` 타입을 파라미터로 받는 것이 현재 `Position`의 역할에 어울리지 못한다는 생각이 듭니다. 
그저 지금 본연의 역할에만 충실하면 좋겠다는 생각이 들어 인자로 `int from`, `int to`를 받도록 수정해보겠습니다!

2023-03-04 09:18 UTC, 0chil commented on src/main/java/constant/Command.java
> +    }
'명령어' 는 view 패키지에 가까운 키워드라고 느끼고 있는데, "all" 이라는 문자열 자체는 상수라고 생각했습니다.
또한 `Command` enum은 상수 "all"을 위한 열거형이므로 '상수'라는 패키지로 분리했습니다.

나중에 다른 명령어가 생긴다면 그 또한 view에 가까울 것 같은데, 그 때문에 `Command`가 view에 있어도 괜찮을 것 같긴 합니다.

2023-03-04 09:27 UTC, 0chil commented on src/main/java/domain/Ladder.java
> +
따로 의도를 가지고 `generator` 패키지로 분리된 것은 아닙니다.
도메인을 생성하는 클래스들이니, domain 패키지 안으로 들어가도 좋을 것 같아 그렇게 수정하였습니다

2023-03-04 09:59 UTC, 0chil commented
안녕하세요 현구막! 땡칠입니다. 리뷰를 반영하고, 재밌는 엣지케이스도 반영해보았습니다.

### 엣지 케이스
> <img width="491" alt="image" src="https://user-images.githubusercontent.com/39221443/222892342-b70ce791-4806-476d-927a-ac3ebf539ca6.png">

전에 생각해봤던 내용이라 저항없이 view에 관련 검증을 추가했습니다🤣

### 고민해보고 반영한 피드백
- `isInRangeOf(Collection<?> collection)` - `IsInBetween(int from, int to)`로 수정
  [https://github.com/woowacourse/java-ladder/pull/229#discussion_r1125417586](https://github.com/woowacourse/java-ladder/pull/229#discussion_r1125417586)

- `var` 사용 관련 - `var` 제거
  [https://github.com/woowacourse/java-ladder/pull/229#discussion_r1125416530](https://github.com/woowacourse/java-ladder/pull/229#discussion_r1125416530)

### 간단한 질문 하나
> if 키워드 사이에 들어간 ! 는 잘 보이지 않는 편이라, isNotWidthEven 이나 isWidthOdd 로 표현해주면 어떨까요?

이 피드백 이후로 if 뒤에는 `!` 붙이는 것을 피하고 있는데요, 만약 긍정과 부정이 모두 어딘가에서 쓰인다면 어떻게 해야 좋을까요?
`Command`를 예로 들면,
```java
if (isCommand(input)) {
   doSomething();
}
```
```java
if (!isCommand(input)) {
   doSomethingElse();
}
```
메서드를 두 개 만들어야 할까요!! 🥲
```java
    public static boolean isCommand(String input) {
        return Arrays.stream(values())
                .anyMatch(command -> command.hasCommand(input));
    }

    public static boolean isNotCommand(String input) {
        return Arrays.stream(values())
                .noneMatch(command -> command.hasCommand(input));
    }
```

2023-03-04 13:24 UTC, Hyeon9mak commented on src/main/java/domain/Position.java
> +    }
> Position::isInRangeOf() 메서드 안의 position은 인스턴스 변수이므로 괜찮을 것 같아요.

아하, 제가 말씀드린 음수표기는 `Position` 의 좌표에 관한 이야기였어요. 

<img width="622" alt="image" src="https://user-images.githubusercontent.com/37354145/222904188-f4403683-1ed4-4aab-93c4-0301997bb287.png">

혹시 제가 잘못 이해한걸까요? 🙏 🥲 

> 최근 읽고 있는 책 'Good code, Bad code'과 대비되는 내용이라서 인상깊었어요. 

항상 긍정적으로 받아주셔서 감사합니다 😄 🙇‍♂️ 
덕분에 더욱 여러가지 이야기를 할 수 있는 것 같아요!

2023-03-04 13:29 UTC, Hyeon9mak commented on src/main/java/engine/LadderEngine.java
> +    }
오........ 자바에서 `var` 가 타입안정성는 별개라는 걸 전혀 몰랐습니다!!! 덕분에 또 배웁니다 🙏 🙇‍♂️

2023-03-04 13:38 UTC, Hyeon9mak approved these changes
땡칠~ 마지막까지 너무 고생 많으셨어요!!

아래는 추가 코멘트입니다.

- https://github.com/woowacourse/java-ladder/pull/229#discussion_r1125466604
- https://github.com/woowacourse/java-ladder/pull/229#discussion_r1125468897

>  if 뒤에는 ! 붙이는 것을 피하고 있는데요, 만약 긍정과 부정이 모두 어딘가에서 쓰인다면 어떻게 해야 좋을까요? 메서드를 두 개 만들어야 할까요!! 🥲

네! 저는 그렇게 생각합니다. 각각이 필요하다는 건 각각이 다른 곳에서 다른 의미로 쓰인다는거니까요~

제가 더 많이 배운 리뷰였던거 같아요 😄 👍 너무너무 즐거웠습니다.
남은 과정도 화이팅입니다! 💪

2023-03-04 13:38 UTC, merged