[2단계 - 사다리 실행] 홍고(홍여진) 미션 제출합니다.
woowacourse/java-ladder pull request #236
Opened 2023-02-24 11:10 UTC by hgo641

안녕하세요, 솔라! 홍고입니다. 😀😀

사다리 게임 step2 제출합니다. 이번에도 잘부탁드립니다!! 🙇‍♀️🙇‍♂️🥰

## 코드 설명

* `LadderGenerator`

> 세로선 사이에 최소 하나의 발판(가로선)이 존재하는 랜덤 사다리를 생성합니다. step1에서는 완전히 랜덤으로 발판을 생성해, 사이에 발판이 하나도 없는 사다리가 생성되기도 했습니다. 게임의 퀄리티를 높이기 위해 세로선 사이에 최소 하나의 발판이 존재하게 수정했습니다.

```java
public Ladder generateLadder() {
        List<Row> rows = generateNoStepRows(); // 발판이 하나도 없는 사다리를 생성
        addStepBetweenAllColumn(rows); // 모든 세로선사이에 하나의 발판을 랜덤으로 생성
        for (Row row : rows) {
            addRandomSteps(row); // 위에서 생성한 다리에서 발판을 랜덤으로 추가
        }
        return new Ladder(rows);
    }
```

<br/>

* `Ladder`

> 사다리의 유효성 검사를 수행하고, 사다리의 한 시작점에서 갈 수 있는 도착점을 구합니다.

```java
public class Ladder {
	...
        
    public List<Integer> getAllEndPosition() { // 첫 번째 시작점부터 차례대로 도달할 수 있는 도착점 리스트를 반환합니다
        List<Integer> endPositions = new ArrayList<>();
        for (int startPosition = 0; startPosition <= getLadderWidth(); startPosition++) {
            endPositions.add(getEndPosition(startPosition));
        }
        return endPositions;
    }
}
```

* `LadderGame`

> 사다리 게임을 실행하고 게임 결과를 반환합니다

```java
public class LadderGame {
 	...
    private void runGame(Players players, Prizes prizes, Ladder ladder) {
        List<Integer> orders = ladder.getAllEndPosition();
        Prizes orderedPrizes = prizes.getOrderedPrizes(orders);
        players.setPrizes(orderedPrizes);
    }
}
```

> Players의 순서는 시작점의 순서와 일치하기에, 첫 번째 시작점부터 차례대로 도달할 수 있는 도착점 리스트를 가지고 각 Player들이 얻을 수 있는 Prize를 세팅했습니다.

2023-02-26 04:09 UTC, solarsalt requested changes
홍고 2단계 미션도 TDD를 지키고, 필요한 테스트들을 잘 구현해주셨습니다.
1단계부터 한결같이 작은 단위로 메소드를 유지하는 코딩 스타일이 매우 읽기에 좋아요 👍 

2단계에서 필수적으로 수정해보면 좋을 사항이 2가지 있어서, request changes 요청합니다.
나머지 코멘트들은 선택적으로 봐주시면 됩니다!

1. 테스트 코드 중 실패하는 테스트가 2개 있습니다. 확인해주세요~
2. 홍고가 질문해주신 내용의 LadderGame 클래스의 `executeResultCommand` 리팩토링과
LadderGame 클래스를 좀 더 분리할 수 있는 지에 초점을 맞춰서 리팩토링을 시도해보는 경험을 해보면 좋을 것 같습니다.

2023-02-26 04:09 UTC, solarsalt commented on README.md
> +  - [x] "all", "end"라는 이름은 사용할 수 없다.
좋은 예외처리네요 👍

2023-02-26 04:09 UTC, solarsalt commented on README.md
> +- [x] 사다리 상품 입력받기
- 요구사항의 '실행 결과를 입력하세요' 에서의 '실행 결과'를 그대로 쓰지않고, 좀더 자연스러운 **'사다리 상품'** 이라는 단어로 으로 정의했다는 것이 멋집니다! 도메인 요구사항을 분석해서 자기 언어로 표현했다는 과정이 느껴졌어요.
- 코드에서 사용할 변수(Prize)와 도메인 언어('사다리 상품')를 일치 시켰다는 것도 💯 만점 드리고 싶습니다. 개발자가 코드 외적으로 신경써야할 중요한 부분중에 하나거든요!

- 제 경험에서는 현실에서 일할 때 처음 설계하고 구현할 때 이 작업에 큰 공을 들입니다 :) 초기에 정해진 용어로 계속 통용되는 경우가 많아서, 애초에 비개발자인 협업자와도 통일된 용어를 사용하는 방향으로 정하려고 합니다.

2023-02-26 04:09 UTC, solarsalt commented on src/test/java/ladder/domain/WidthTest.java
> +    @DisplayName("너비는 1미만이면 예외던지기")
테스트가 실패합니다. 확인부탁드려요 :)

2023-02-26 04:09 UTC, solarsalt commented on src/test/java/ladder/domain/RowTest.java
>      public void 생성_fail_width사이즈() {
테스트가 실패합니다. 확인부탁드려요~

2023-02-26 04:09 UTC, solarsalt commented on src/main/java/ladder/controller/LadderGame.java
> +            inputResultCommand(players, ResultCommand.from(inputView.inputPlayerForResult()));
새롭게 추가된 각 메소드들이 해당 클래스 내에서 
작은 단위로 잘 분리 되어서 로직 흐름을 이해하기 쉬웠습니다!

아쉬운 점은 기능 추가로 구현이 늘어나다보니, LadderGame 클래스가 뚱뚱해졌네요.
많은 private method를 보유한 클래스가 되버렸는데, step1가 비교하면 상당히 뚱뚱한 클래스가 된 것 같아요. 

이제 LadderGame를 분리해야할 시점인지 고민해보면 어떨까요?

2023-02-26 04:09 UTC, solarsalt commented on src/main/java/ladder/view/InputView.java
> +        return List.of(names.split(NAME_DELIMITER));
사소한 것이지만, 이름이 아니라 상품을 입력받을때의 delimiter도 ','라서 공유하게 되니,
과거에 지어둔 이름이 rename을 고려해야할 수도 있겠네요~
NAME_DELIMITER => 플레이어 이름을 위한 delimiter로 오해될 수 있을 것 같습니다.

2023-02-26 04:09 UTC, solarsalt commented on src/main/java/ladder/domain/Name.java
> +    }
혹시 이 메소드에서 의도하신 바가, String의 isBlank() 와 동일한 기능일까요?
제가 의도를 잘못 알았거나
내장메소드를 활용하지 않으신 이유가 따로 있다면, 설명 부탁드려요 :) 

ref
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#isBlank()

2023-02-26 04:09 UTC, solarsalt commented on src/main/java/ladder/view/InputView.java
> +    private static final String RESULT_COMMAND_INPUT_MESSAGE = "결과를 보고 싶은 사람은?";
FYI.
프로그래밍 요구사항은 만족했지만, 유저에게 전달되는 부분에 대한 고민인데요.
유저가 '결과를 보고싶은 사람은?' 문장만 봤을때는,
all을 입력할수 있다는 걸 인지하기 어려울 것 같아요. 

우리는 학습을 위한 프로그래밍에 집중하고 있어서 minor한 영역이지만, 실제로 일하실 때는
백엔드개발자여도(=프론트엔드 개발자 아니어도!) 내가 구현한 코드가 
최종 유저(end user)에게 어떻게 전달되는 지에 대한 고민은 반드시 해야합니다!

저라면 아래 정도로 처리할 것 같습니다~
`결과를 보고싶은 사람은? 
(all 또는 게임참여자 이름을 입력하세요.)`

2023-02-26 04:09 UTC, solarsalt commented on src/main/java/ladder/controller/LadderGame.java
> +    private void executeResultCommand(Players players, ResultCommand resultCommand) {
> if문으로 구현하니 커맨드가 늘어나면 코드 길이도 늘어나는 단점이 있어, enum객체에서 함수형 인터페이스를 사용해 커맨드를 if문으로 구분하지않고도, resultCommand.execute()와 같이 일괄적으로 각 커맨드에 맞는 로직을 실행하고 싶습니다.
> 
> 그런데 ALL과 PLAYER의 경우 로직을 실행하는데 매개변수로 Players객체가 필요하고, End의 경우는 아무런 매개변수가 필요하지않아 함수형 인터페이스로 작성하는데 실패했습니다.
> 
> 혹시 매개변수가 다르지만 메소드를 일괄적으로 적용할 수 있는 방법이 있을까요?

@hgo641 홍고가, 이 메소드에서 뭔가 code smell을 느끼고, 리팩토링 해보려는 시도를 하고 계시네요!!!!!
이번 미션에서 꼭 얻고 가셔야할 경험이라서 이것으로 미션을 완료했다고 봐도 될 것 같아요ㅋㅋㅋ👍🏻👍🏻👍🏻 
'리팩토링을 아직 못했는데, 미션완료라고?' 라는 생각이 들수도 있지만, 
요구사항에 하라고 해서 리팩토링 하는 것이 아니라
복잡한 요구사항 로직을 1차 구현하고 나서 
스스로 리팩토링 포인트를 찾아가는 단계는 엄청난 차이입니다!!!

만약 이번 단계에서 리팩토링에 실패하더라도 괜찮아요! 이 이슈는 미해결 문제로 남아서, 다음 과제를 하더라도 홍고는 아마 이 미해결문제가 머릿속 한켠에 남아 좋은 해결방안이 없을 지 계속 고민하는 마법(~~이라쓰고 저주라고 읽는...~~)에 걸리실겁니다!

먼저, 홍고가 질문해 주신 내용을 정리해봤습니다. 제가 잘못 이해한게 있다면, 알려주세요~
- 홍고가 느낀 문제 : 'if문으로 구현하니 커맨드가 늘어나면 코드 길이도 늘어나는게 문제'
- 문제 해결 방식 : ResultCommand enum 클래스에서 resultCommand.execute()와 같이 일괄적으로 각 커맨드에 맞는 로직을 실행하고 싶다.

**리팩토링을 돕기위한 질문들**
- 지금 ResultCommand의 케이스는 3개인데, 현재 갯수로도 문제가 될 만큼 많은가? 앞으로 케이스가 얼만큼 늘어날 것으로 예상했기에 문제가 된다고 생각한 것인지? (예상 확장 시나리오나, 시나리오 갯수가 있었는지?)
- switch는 요구사항에서 지양하라고 했는데, 그러면 대체 swtich의 사용은 언제 할 수 있는가? switch무조건 나쁜 것인가? 어떤 상황에서 switch가 적합한가? 의심해보자
- `enum 클래스에서 resultCommand.execute()와 같이 일괄적으로 각 커맨드에 맞는 로직을 실행` 해결방식이 이 문제를 해결하는 최적의 방안인가?
- 현재의 메소드에서 각 분기마다 공통적으로 하는 일이 무엇인가? 
  - 제가 파악하기로는 ResultCommand에 따라서, 결과 텍스트를 print해서 보여준다는 공통점이 있다고 파악했습니다. 그외 공통점은 못 찾았어요.
  - `resultCommand.execute()` 라는 메소드가 있다면 이름만 봐서는 resultCommand가 무엇인지에 따라서 제각각 전혀 다른 일을 할 가능성이 있다고 추측됩니다. 하는일이 달라지니 필연적으로 로직처리에 필요한 매개변수도 다른 것이 나쁜 상황이 아니라, 자연스럽게 느껴집니다. 
  - 현재의 메소드는 ResultCommand를 '실행한다'는 공통점이 있다는 시각으로 묶여있지만, 케이스마다 하는일을 살펴보면 크게 2가지네요. 1.종료메시지 보여주기 2.상품보여주기 그렇다면, 1과 2가 애초에 같은 레이어에 있는 것이 자연스러운지도 다시 고민이 되기도 하네요.🧐 더 많은 고민은 코드오너에게 맡기겠습니다!
- 현재의 메소드는 ResultCommand를 주인공으로 보는 관점인데, 반대로 기존 객체가 (ex. players )주인공이 되어 같은 로직을 수행하는 것도 가능할까? 아니면 새로운 객체를 생성해서 이 책임을 맡겨보는 것이 더 적절할까? 
- 위의 모든 고민들을 먼저 해본 뒤에도 **매개변수가 다르지만 메소드를 일괄적으로 적용할 수 있는 방법**  을 찾아내 해결해야겠다면, 디자인 패턴 중 하나인 'Strategy Pattern'에 관해서 찾아보면 도움이 될 것 같습니다. 
- ref: https://tecoble.techcourse.co.kr/post/2021-10-04-strategy-command-pattern/
- https://interviewsansar.com/shape-interface-implementation-java-exercise/

2023-02-26 16:57 UTC, hgo641 commented on src/main/java/ladder/domain/Name.java
> +    }
네 동일한 기능이 맞습니다 ㅠㅠ isBlank()라는 메소드의 존재를 몰랐어서 set을 활용해 구현했었습니다. 기능을 구현하기 전에 미리 동일한 기능을 하는 내장메소드가 있는지 잘 찾아봐야겠군요...ㅠㅠ 감사합니다!

2023-02-26 18:20 UTC, hgo641 commented
안녕하세요 솔라! 이번에도 정성스러운 피드백을 해주셔서 정말 감사합니다! 🙇‍♀️🙇‍♂️❤

## 변경된 부분

### 실패하는 테스트 코드 수정
솔라가 말씀해주신 실패하는 테스트 코드를 수정했습니다. 실패하는 테스트 코드를 올려서 부끄럽습니다.ㅠㅠ 확인해주셔서 감사합니다!

* `WidthTest`에서 "너비가 1미만일 경우 예외던지기" 테스트는 `Width`를 생성할 때 넣는 1이상인 매개변수를 넣어 실패했습니다. 1미만인 매개변수로 수정하여 해결했습니다.


* `RowTest`에서 "width가 player수 - 1이 아니면 예외가 발생" 테스트는 `Row`가 Width의 크기와 Players의 크기를 비교하는 책임을 맡는 것이 이상하다 생각해 `Row`의 유효성 검사 로직을 삭제하면서 테스트 코드도 함께 삭제했습니다.


### `LadderGame`을  분리
솔라가 조언해주셨듯이  `LadderGame`이 맡은 역할이 많다고 생각해 클래스를 분리했습니다.

* 기존의 `LadderGame` 클래스 이름을 `LadderGameController`로 변경한 뒤, 사다리 게임을 실행하고, `Players`와 `Prizes` 크기가 동일한지 검사하는 역할을 `LadderGame`으로 옮겼습니다.

* 사용자로부터 데이터를 입력받는 역할을 `InputController`로 옮겼습니다.

* 사용자에게 결과를 출력하는 역할을 `ResultController`로 옮겼습니다. 

감사합니다!! 😀😀

2023-02-27 06:21 UTC, solarsalt commented on src/main/java/ladder/controller/LadderGameController.java
> +            runGame(ladderGame);
```suggestion
            ladderGame.run();
```
public 메소드라서 run()을 바로 호출할 수도 있는데, private 으로 한 번 더 랩핑하신 이유가 있을까요?

2023-02-27 06:21 UTC, solarsalt commented on src/main/java/ladder/controller/LadderGameController.java
> +    }
repeatResultCommand(LadderGame ladderGame, ResultCommand resultCommand) 메소드와
executeResultCommand(LadderGame ladderGame, ResultCommand resultCommand) 메소드에서 
사용하는 매개변수가 같아서, 새로운 객체를 만들어 2개의 메소드를 담당하는 역할을 위임하는 것도 가능할 것 같습니다~

LadderGameController의 run() 메소드에서 호출하는 private method가 적어지는 방향으로 고민해보다가,
위의 방식도 가능할 것 같아서 코멘트 남겼습니다!

2023-02-27 08:12 UTC, solarsalt approved these changes
홍고 2단계 미션 하느라 고생많으셨습니다👍 👍 👍 
2단계 미션에서 배우고 익히신 것들을 3단계 미션에서 실컷 활용하시길 바래요!

2023-02-27 08:12 UTC, merged