[2단계 - 사다리 게임 실행] 라온(문채원) 미션 제출합니다.
woowacourse/java-ladder pull request #237
Opened 2023-02-24 13:02 UTC by mcodnjs

2023-02-25 01:36 UTC, mcodnjs commented on src/main/java/laddergame/controller/LadderGameController.java
> +        printLadderGameResult(result);
[이전 1단계](https://github.com/woowacourse/java-ladder/pull/127#discussion_r1109714301)에서 Player, Ladder 등을 생성하였던 `LadderGame`에 있던 `setter`의 역할을 제거하였습니다.
setter의 역할을 제거하면서 Player, Ladder, Prize 등을 모두 컨트롤러에서 생성하게 되었는데, **게임을 제어하기 위한 목적인 컨트롤러가 결국 `LadderGame`의 역할까지 담당하고 있는 것 같습니다** .. 제가 생각하기에 **컨트롤러라는 이름을 가진 클래스가 이러한 역할들을 하고 있는 것이 어색하게 느껴지는데** (LadderGame이라는 클래스가 존재해서 어색하게 느껴지는 걸까요 .. ?), 경험이 부족하다보니 이러한 구조가 괜찮은지 잘 모르겠습니다. 빙봉의 의견을 듣고 싶습니다!!!

2023-02-25 01:57 UTC, mcodnjs commented on src/main/java/laddergame/domain/LadderGame.java
> +    public LadderGame(Players players, Ladder ladder, Prizes prizes) {
[앞서 언급한 커멘트](https://github.com/woowacourse/java-ladder/pull/237/files#r1117842453)와 같은 구조가 되면서 **2) `LadderGame`의 역할이 `getter`밖에 남지 않게 되었습니다** 😅 그럼 LadderGame의 역할이 없어지고 제거해도 된다고 생각하는데 .. **만약 LadderGame을 살려둔다면 게임을 진행하고 그 결과를 반환하는 역할**(현재 Result 생성자의 역할)을 두어야할지 잘 모르겠습니다 ㅠㅠ 어떤 부분을 더 생각해야 결정을 내릴 수 있을까요 ?

2023-02-25 16:50 UTC, aegis1920 requested changes
안녕하세요 라온! 빙봉입니다 🙂

어려운 2단계 구현하시느라 고생많으셨어요! 👍
질문에 대한 답변과 약간의 피드백 남겨드렸으니 확인부탁드려요!

질문은 언제나 환영이니 언제든 DM주세요~

2023-02-25 16:50 UTC, aegis1920 commented on src/main/java/laddergame/domain/Prize.java
> +    private final String prize;
공백 한 칸 띄워주세요!

2023-02-25 16:50 UTC, aegis1920 commented on src/main/java/laddergame/util/RandomBooleanGenerator.java
> +public class RandomBooleanGenerator implements PointGenerator {
PointGenerator가 아닌 BooleanGenerator가 되어야 하지 않을까요?

2023-02-25 16:50 UTC, aegis1920 commented on src/main/java/laddergame/domain/Line.java
> +        int playerCount = points.size() + 1;
- 생성자쪽에서는 this.points로 this를 붙여주셨는데 이쪽과 getLIne()쪽에는 안 붙여주셨네요. 일관성있게 맞춰주면 좋지 않을까요?
- `points.size() + 1`을 해주고 canMoveRight 안에서 다시 - 1을 해주는 이유가 있을까요?
  - points.size()만 전달해줘도 되지 않을까요?
  - playerCount 보다 더 어울리는 변수명은 없을까요?

2023-02-25 16:50 UTC, aegis1920 commented on src/main/java/laddergame/controller/LadderGameController.java
> +        printLadderGameResult(result);
> setter의 역할을 제거하면서 Player, Ladder, Prize 등을 모두 컨트롤러에서 생성하게 되었는데, 게임을 제어하기 위한 목적인 컨트롤러가 결국 LadderGame의 역할까지 담당하고 있는 것 같습니다 .. 제가 생각하기에 컨트롤러라는 이름을 가진 클래스가 이러한 역할들을 하고 있는 것이 어색하게 느껴지는데 (LadderGame이라는 클래스가 존재해서 어색하게 느껴지는 걸까요 .. ?

- Controller와 LadderGame의 역할이 정확히 무엇인지 파악할 필요가 있다고 생각합니다. 🙂 
- 일단, Application에서 실행 시, Controller에서 run() 메서드만 호출하고 끝나는데요. Controller의 역할을 다시 한 번 살펴보면 좋을 것 같습니다. ([링크](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller))
  - 개인적으로 지금 상황에서 controller.run()은 controller의 역할이 아닌 흔히 스프링부트에서 이야기하는 SpringBootApplication.run() 에 더 가깝다고 생각합니다.
- 사실 좀 더 객체지향적으로 만들어본다면 사용자 입력을 바탕으로 player를 생성하고 prize를 생성하고 사다리 높이를 생성하는 역할은 아예 생성하는 역할만 담당하는 클래스로 따로 분리할 수 있을 것 같습니다. 다만 이 부분은 너무 오버엔지니어링이라고 생각해요. 현재 상황에서는 Controller에서 생성해도 된다고 생각합니다.
- LadderGame은 어떤 역할일까요? 현재 사다리 게임 클래스의 역할은 단순히 사다리 게임의 필요한 데이터(player, prize 등등)를 모아둔 DTO 정도로 해석됩니다. 사다리 게임 어플리케이션에서 사다리 게임이라는 클래스는 어떤 역할을 해야할 지 고민해보셔도 좋을 것 같아요. 필요없다면 지우는 것도 방법이고요. 단어만 봤을 때는 전체를 어우르는 느낌도 들고 어플리케이션을 run()했을 때 game.play(), game.exit() 이런 정도로 생각하게 되네요.

2023-02-25 16:50 UTC, aegis1920 commented on src/main/java/laddergame/domain/LadderGame.java
> +    public LadderGame(Players players, Ladder ladder, Prizes prizes) {
앞서 언급한 코멘트의 답변과 같이 LadderGame의 역할에 대해서 고민해보셨으면 좋겠어요. 현재 LadderGame은 단순 DTO 역할만 해주고 있다고 생각이 듭니다. 사다리 게임 어플리케이션을 개발하는데 사다리 게임 클래스는 어떤 역할일까요? 전체를 관통하는 느낌이 들지 않나요? 굳이 살려둘 필요가 없다면 지워도 됩니다.

2023-02-25 18:06 UTC, mcodnjs commented on src/main/java/laddergame/domain/LadderGame.java
> +    public LadderGame(Players players, Ladder ladder, Prizes prizes) {
> 전체를 관통하는 느낌

이 말이 와닿았습니다.

2023-02-26 11:53 UTC, mcodnjs reviewed
안녕하세요 빙봉! 리뷰 남겨주신 부분 모두 수정하여 반영하였습니다!

Controller와 LadderGame에 대한 부분은 `Controller의 도메인 생성은 어색하지 않으며, LadderGame의 객체는 삭제하는 방향`으로 수정하였습니다! 

황금 같은 주말에 리뷰 감사드립니다 🙇‍♂️

2023-02-26 11:53 UTC, mcodnjs commented on src/main/java/laddergame/domain/Line.java
> +        int playerCount = points.size() + 1;
> 생성자쪽에서는 this.points로 this를 붙여주셨는데 이쪽과 getLIne()쪽에는 안 붙여주셨네요. 일관성있게 맞춰주면 좋지 않을까요?

생성자에서는 보통 파라미터를 멤버 변수와 동일한 이름을 사용하는데, 이를 구분하고자 this를 붙이는 것이 습관화 되었습니다. 생성자를 제외한 다른 메서드에서는 동일한 이름을 사용하는 경우가 적어 따로 구분하지 않았던 것 같습니다. IDE가 구분해주지 않는다면 해석에 불편함을 느낄 여지가 있다고 생각하긴 하지만 ,, 생성자를 제외한 모든 메서드에 this를 붙이는 것이 조금은 어색하게 느껴지네요 ㅎㅎ.. 그만큼 습관화되었던 것 같습니다. 빙봉은 this 키워드를 사용한다면 모든 메서드에 this 키워드를 붙이는 편인가요 ?!

2023-02-26 11:53 UTC, mcodnjs commented on src/main/java/laddergame/util/RandomBooleanGenerator.java
> +public class RandomBooleanGenerator implements PointGenerator {
헉 수정하였습니다 !

2023-02-26 11:53 UTC, mcodnjs commented on src/main/java/laddergame/controller/LadderGameController.java
> +        printLadderGameResult(result);
객체의 역할과 책임 너무 어렵네요 ㅠㅠ 

> 아예 생성하는 역할만 담당하는 클래스로 따로 분리할 수 있을 것 같습니다

이 부분에 동의합니다! 다만 저도 오버엔지니어링이라고 생각하기 때문에, **컨트롤러에서 생성하도록 두는 것이 좋을 것 같습니다.** LadderGame의 역할에 의존하고 있다보니 컨트롤러에서 생성하게 둔 것이 어색하게 느껴진 것 같습니다! 답변 감사합니다 🙇‍♂️ (LadderGame에 대한 부분은 LadderGame 클래스에 답변 남겼습니다!)

2023-02-26 11:53 UTC, mcodnjs commented on src/main/java/laddergame/domain/LadderGame.java
> +    public LadderGame(Players players, Ladder ladder, Prizes prizes) {
> LadderGame의 역할

- 입력받은 도메인 생성
- 사다리 게임 시작 (play)

LadderGame이 가질 수 있는 역할은 위 두 가지라고 생각하였습니다.
다만, 제가 구현한 방식은 `Player가 위치를 이동하는 형태`가 아닌 `생성된 ladder에 맞춰서 결과값만 반환해주는 형태` 입니다. 자동차 경주와 같이 플레이어가 한 칸씩 움직이는 형태였다면, RacingCarGame이라는 객체의 play와 같은 역할이 명확하다고 생각하는데, 사다리 게임의 경우 의미있는 역할이라고 생각되지 않네요! (player가 position을 line마다 움직이는 형태였다면 LadderGame 객체가 play, movePlayer 등의 역할로서 player를 움직이는 것이 괜찮다고 생각합니다.)

> LadderGame이 필요한가 ?

- ~~입력받은 도메인 생성~~  --> 컨트롤러에서 입력 받은대로 도메인 생성
- ~~사다리 게임 시작 (play)~~ --> 생성된 사다리에 따른 결과값 반환 (Result의 역할)

LadderGame이 가질 수 있는 역할이 위와 같이 정리가 될 것 같고, DTO의 역할로서의 LadderGame은 필요하지 않다고 생각하기 때문에, LadderGame 클래스는 지우도록 하겠습니다!

2023-02-26 11:53 UTC, mcodnjs commented on src/main/java/laddergame/domain/Line.java
> +        int playerCount = points.size() + 1;
> points.size() + 1을 해주고 canMoveRight 안에서 다시 - 1을 해주는 이유가 있을까요?

확인하지 못하였습니다. point의 사이즈가 플레이어 수보다 1 작고, 배열의 인덱스는 0부터 시작하여 1 작은 것 때문에 이런 연산이 나왔는데, 결국엔 points.size()가 되네요 ㅎㅎ.. **어떤 역할을 위해 이 변수가 필요한지 생각하면서 `maxPosition`과 `minPosition`으로 정리해봤습니다!**

2023-02-26 13:27 UTC, aegis1920 commented on src/main/java/laddergame/domain/LadderGame.java
> +    public LadderGame(Players players, Ladder ladder, Prizes prizes) {
논리적으로 라온의 생각을 잘 설명해주셨네요. 👍

2023-02-26 13:36 UTC, aegis1920 commented on src/main/java/laddergame/domain/Line.java
> +        int playerCount = points.size() + 1;
> IDE가 구분해주지 않는다면 해석에 불편함을 느낄 여지가 있다고 생각하긴 하지만 ,, 생성자를 제외한 모든 메서드에 this를 붙이는 것이 조금은 어색하게 느껴지네요 ㅎㅎ.. 그만큼 습관화되었던 것 같습니다. 빙봉은 this 키워드를 사용한다면 모든 메서드에 this 키워드를 붙이는 편인가요 ?!

네, 저라면 붙였을 것 같고 그 이유는 가급적 모든 상황에서 의존을 줄이는 게 좋다고 생각해서입니다. `IDE가 구분해주지 않는다면 해석에 불편함을 느낄 여지가 있다고 생각하긴 하지만` 이렇게 말씀해주셨다면 불편함을 느낄 여지조차 없게 만드는 게 더 나은 상황이 아닐까요?ㅎㅎ

> 어떤 역할을 위해 이 변수가 필요한지 생각하면서 maxPosition과 minPosition으로 정리해봤습니다!

👍

2023-02-26 13:52 UTC, aegis1920 approved these changes
안녕하세요 라온! 빙봉입니다 🙂

바쁜 와중에도 사다리 게임 구현하느라 고생 정말 많으셨습니다! 👍  
기존 코드리뷰에 대한 코멘트는 남겨드렸고 TDD나 클래스 분리, 리펙토링 등등 충분히 잘 해주셔서 이번 미션은 여기서 머지하겠습니다.

다음 미션도 파이팅하세요!!

2023-02-26 13:52 UTC, merged

2023-02-27 06:00 UTC, mcodnjs commented on src/main/java/laddergame/domain/Line.java
> +        int playerCount = points.size() + 1;
> 불편함을 느낄 여지조차 없게 만드는 게 더 나은 상황이 아닐까요?ㅎㅎ

넵 맞습니다 ㅎㅎ .. 좋은 의견 감사드립니다 ~!