[2단계 - 사다리 게임 실행] 마코(이규성) 미션 제출합니다.
woowacourse/java-ladder pull request #239
Opened 2023-02-25 07:13 UTC by aak2075

안녕하세요 파즈!
그동안 잘 지내셨나요?

이번 2단계를 진행하는데 많이 어려웠네요.
고민에 따라서 설계가 계속 바뀌어서 TDD로 작성하기 너무 번거로웠습니다. 코드를 여러 번 삭제하고 수정하다가 시간적 압박에 의해 마지막 쯤에는 TDD를 포기하고 진행했네요.

이번 리뷰도 잘 부탁드립니다! 😄 

## 궁금한 점

### 원시값 포장

`원시값 포장과 해제를 어디에서 해야하는가?`에 대한 고민이 정말 많았습니다.

1. 뷰에서 원시값을 포장해서 컨트롤러에 넘겨주면 뷰가 도메인에 의존하게 되고 도메인이 변경되면 뷰도 변경해야 하기 때문에 좋지 않은 것 같습니다.
2. 컨트롤러에서 원시값을 포장하게 되면 컨트롤러의 책임이 너무 커지는 것 같다는 생각이 듭니다.
3. 그렇다고 해서 도메인내에서 사용할 때만 포장하고 해제하게 되면 포장의 의미가 없어진다고 생각했습니다.

이 고민에 대해서 어떻게 생각하시나요?

### 반복 동작에 대한 처리

요구사항에서는 `결과를 보고 싶은 사람은?` 문구를 출력하며 반복해서 결과를 보여주는 반복 동작을 하고 있습니다.
이에 대한 처리를 Controller의 `repeatViewResult()` 메서드에서 담당하도록 구현했습니다.

해당 동작을 하는 메서드를 재귀 호출하는 방식으로 쉽게 해결 가능하지만 스택 프레임에 여러 값들을 저장하는 과정에서 오버헤드가 크게 일어나 스택 오버플로우가 발생할 수 있습니다.

while문으로 해결하기 위해서는 아래와 같은 방법으로 하고 싶은데 depth가 2가 되어버려서 요구사항에 어긋납니다.

```java
private void repeatViewResult(final LadderGame ladderGame) {
        while (true) {
            InputRepeatableDTO inputRepeatableDTO = inputView.inputResultViewersName(ladderGame.allPlayersName());
            if (!inputRepeatableDTO.isRepeatable()) {
                break;
            }
            Names viewers = inputRepeatableDTO.getNames();
            Results viewResult = ladderGame.resultsByNames(viewers);

            outputView.printGameResult(viewers, viewResult);
        }
    }
```
다음과 같은 방식으로 하게 되면 `ladderGame.resultsByNames()` 에서 이름에 해당하는 player를 가져올 때 이름에 해당하는 player가 없어서 exception을 발생하게 됩니다. 정상적인 종료가 아니기 때문에 좋은 방법은 아닌 것 같습니다.

```java
private void repeatViewResult(final LadderGame ladderGame) {
        InputRepeatableDTO inputRepeatableDTO = InputRepeatableDTO.repeatable(new Names(Collections.emptyList()));
        while (!inputRepeatableDTO.isRepeatable()) {
            inputRepeatableDTO = inputView.inputResultViewersName(ladderGame.allPlayersName());
            Names viewers = inputRepeatableDTO.getNames();
            Results viewResult = ladderGame.resultsByNames(viewers);

            outputView.printGameResult(viewers, viewResult);    
        }
    }
```

현재 소스에 반영되어 있는 방법도 while로 하긴 했지만 결국에 while로 함수를 반복 호출하는 거라 재귀랑 똑같다고 생각합니다... 결국 해결을 못했는데
이에 대해서 어떻게 생각하시나요?

2023-02-25 15:51 UTC, Be-poz commented
안녕하세요 마코 아주 열심히 진행하셨군요! 수고하셨습니다! 그 다음 블랙잭 미션은 수월하니깐 다시 TDD 한 번 힘내보시면 좋을 것 같습니다!  



질문에 대한 답을 해보겠습니다.  

### 원시값 포장

개인적으로 저는 Input에 관련된 클래스에는 도메인과 그리고 도메인에서 사용되는 검증로직을 아예 두지 않고 단순히 입력값만 받습니다. 마코 말대로 도메인 변경에 대해서 사이드 이펙트를 받기도 하고, 도메인의  검증과 생성에 대한 역할은 Input 이라는 클래스와 맡지 않다고 생각하기 때문입니다. 컨트롤러가 커지는 것을 고민하셨는데요, 컨트롤러에서 가지고 있어야할 클래스에 대한 생성이 컨트롤러 코드에 추가되는 것은 저는 상관없다고 생각합니다.  

다만,  

```java
class Person {
  final Age age;
  
  public Person(final Age age) {
    this.age = age;
  }
}
```

위와 같이 Person 내부에 또 다른 포장객체가 있고 컨트롤러에서 Age를 만든 후 Person에 넘기는 방식이 아니라, 입력받은 값 그 자체를 도메인 생성자로 넘기고 그곳에서 포장을 해주는 방식을 취할 것 같네요. 이 과정 속에서 검증로직이 추가된다면 해당 포장객체를 가지고 있는 클래스 내부에서 검증이 이루어지고 예외가 던져지던가 해야한다고 생각합니다.  

포장의 의미라는 것에 대해 다시 한 번 생각해봐야 될 것 같은데요, 포장을 하는 이유가 애초에 무엇일까요? 해당 객체의 역할을  클래스를 하나 더 생성해서 그곳에 모아주기 위함이라고 생각합니다. 도메인 내에서 포장을 하고 해체하고 그것은 다른 고민이고, 포장 객체의 존재 의의 자체는 조금 더 상세한 캡슐화이기 때문에 조금 다른 개념이라고 생각합니다.  

Input, 그리고 포장의 위치 이런 것들은 사실 답이 없고 위에 말씀드린 것들은 단순히 제 생각입니다. 저는 제가 생각하기에 저 방식이 타당하다고 생각하고 있기 때문에 저렇게 짜고는 합니다. 마코는 최종적으로 어떤 결론을 내리게 될 것인지 매우 궁금하네요.  

<Br/>

### 반복 동작에 대한 처리

while로 동작하는 것은 저는 괜찮다고 생각합니다. 고민이신게 중간에 해당하는 player가 없어서 exception으로 프로그램 종료가 되는 것이 고민이신거죠 ?? 그러면 없는 player의 이름이 입력되면 그냥 error message를 대신 출력하게끔 변경하면 되지 않나요? ``outputView.printGameResult``  호출할 때에 viewers와 results 말고 해당 입력 결과 메세지 출력을 위한 dto를 하나 만들면 생각할 거리가 조금 더 줄어들 수 있을 것 같아요.

그리고 enum 으로 quit, all과 같은 특수 커맨드를 생성해두면 더 좋을 것 같습니다.

2023-02-25 15:51 UTC, Be-poz commented
안녕하세요 마코 아주 열심히 진행하셨군요! 수고하셨습니다! 그 다음 블랙잭 미션은 수월하니깐 다시 TDD 한 번 힘내보시면 좋을 것 같습니다!  



질문에 대한 답을 해보겠습니다.  

### 원시값 포장

개인적으로 저는 Input에 관련된 클래스에는 도메인과 그리고 도메인에서 사용되는 검증로직을 아예 두지 않고 단순히 입력값만 받습니다. 마코 말대로 도메인 변경에 대해서 사이드 이펙트를 받기도 하고, 도메인의  검증과 생성에 대한 역할은 Input 이라는 클래스와 맡지 않다고 생각하기 때문입니다. 컨트롤러가 커지는 것을 고민하셨는데요, 컨트롤러에서 가지고 있어야할 클래스에 대한 생성이 컨트롤러 코드에 추가되는 것은 저는 상관없다고 생각합니다.  

다만,  

```java
class Person {
  final Age age;
  
  public Person(final Age age) {
    this.age = age;
  }
}
```

위와 같이 Person 내부에 또 다른 포장객체가 있고 컨트롤러에서 Age를 만든 후 Person에 넘기는 방식이 아니라, 입력받은 값 그 자체를 도메인 생성자로 넘기고 그곳에서 포장을 해주는 방식을 취할 것 같네요. 이 과정 속에서 검증로직이 추가된다면 해당 포장객체를 가지고 있는 클래스 내부에서 검증이 이루어지고 예외가 던져지던가 해야한다고 생각합니다.  

포장의 의미라는 것에 대해 다시 한 번 생각해봐야 될 것 같은데요, 포장을 하는 이유가 애초에 무엇일까요? 해당 객체의 역할을  클래스를 하나 더 생성해서 그곳에 모아주기 위함이라고 생각합니다. 도메인 내에서 포장을 하고 해체하고 그것은 다른 고민이고, 포장 객체의 존재 의의 자체는 조금 더 상세한 캡슐화이기 때문에 조금 다른 개념이라고 생각합니다.  

Input, 그리고 포장의 위치 이런 것들은 사실 답이 없고 위에 말씀드린 것들은 단순히 제 생각입니다. 저는 제가 생각하기에 저 방식이 타당하다고 생각하고 있기 때문에 저렇게 짜고는 합니다. 마코는 최종적으로 어떤 결론을 내리게 될 것인지 매우 궁금하네요.  

<Br/>

### 반복 동작에 대한 처리

while로 동작하는 것은 저는 괜찮다고 생각합니다. 고민이신게 중간에 해당하는 player가 없어서 exception으로 프로그램 종료가 되는 것이 고민이신거죠 ?? 그러면 없는 player의 이름이 입력되면 그냥 error message를 대신 출력하게끔 변경하면 되지 않나요? ``outputView.printGameResult``  호출할 때에 viewers와 results 말고 해당 입력 결과 메세지 출력을 위한 dto를 하나 만들면 생각할 거리가 조금 더 줄어들 수 있을 것 같아요.

그리고 enum 으로 quit, all과 같은 특수 커맨드를 생성해두면 더 좋을 것 같습니다.

2023-02-25 15:53 UTC, Be-poz requested changes
안녕하세요 마코 2단계 수고하셨습니다!  
질문에 대한 답은 코멘트 따로 달아놨으니 확인해주세요!  
코멘트 드릴게 딱히 없습니다.  굉장히 깔끔하게 잘 하신 것 같습니다. 질문에 대한 답이 해결이 되면 그때 바로 머지하도록 하겠습니다. 수고하셨습니다.

2023-02-25 15:53 UTC, Be-poz commented on src/main/java/controller/LadderController.java
> +        Ladder ladder = inputView.inputLadder(ladderMaker, inputNames.size());
InputView 에서 도메인까지 생성하게끔 변경된 것은 어떤 생각들을 가지고 변경하셨는지 듣고 싶습니다.

2023-02-25 15:53 UTC, Be-poz commented on src/main/java/validator/dto/InputRepeatableDTO.java
> +    public static InputRepeatableDTO Unrepeatable(final Names data) {
네이밍이 . . !! 👀

2023-02-27 02:06 UTC, aak2075 commented on src/main/java/controller/LadderController.java
> +        Ladder ladder = inputView.inputLadder(ladderMaker, inputNames.size());
먼저 질문 드렸던 원시값 포장에 대한 고민을 하면서 컨트롤러가 책임이 많아 보여서 책임을 넘기다 보니 이런 상황이 발생했네요. mvc 모델이란 무엇인가 다시 생각을 해본 결과 도메인은 컨트롤러가 생성하고, 뷰는 도메인을 의존하지 않도록 변경했습니다.

```java
List<String> inputNames = inputView.inputNames();
List<String> inputResult = inputView.inputResults();

Ladder ladder = initLadder(inputNames.size());
```

2023-02-27 05:16 UTC, aak2075 commented on src/main/java/validator/dto/InputRepeatableDTO.java
> +    public static InputRepeatableDTO Unrepeatable(final Names data) {
미처 발견하지 못했군요....! 👀

2023-02-27 07:28 UTC, aak2075 commented
안녕하세요!
파즈의 리뷰 덕분에 생각이 어느 정도 정립된 것 같습니다.

> 포장의 의미라는 것에 대해 다시 한 번 생각해봐야 될 것 같은데요, 포장을 하는 이유가 애초에 무엇일까요? 해당 객체의 역할을 클래스를 하나 더 생성해서 그곳에 모아주기 위함이라고 생각합니다. 

여러 고민들을 하면서 포장의 이유를 잘 생각하지 못했던 것 같아요. 무조건 포장을 해야 한다는 생각에 뷰에서 도메인을 생성하게 되었고, 입력에서도 도메인의 검증 로직을 거치기도 하고 문제가 많았네요. 

> while로 동작하는 것은 저는 괜찮다고 생각합니다. 고민이신게 중간에 해당하는 player가 없어서 exception으로 프로그램 종료가 되는 것이 고민이신거죠 ?? 그러면 없는 player의 이름이 입력되면 그냥 error message를 대신 출력하게끔 변경하면 되지 않나요? outputView.printGameResult 호출할 때에 viewers와 results 말고 해당 입력 결과 메세지 출력을 위한 dto를 하나 만들면 생각할 거리가 조금 더 줄어들 수 있을 것 같아요.

뷰에서 도메인을 생성했던 것이 여기에서도 문제였습니다. exception처리를 view에서 해야 했는데 player가 없어서 excepition이 발생하는 것은 뷰의 로직이 아니여서 고민이었습니다. 책임을 다시 분리하고 LadderGame에서 해당 player가 없으면 exception을 발생시키도록 변경했습니다.

기존에 사용했던 dto는 반복문을 제어하기 위해 억지로 사용했던 느낌이었습니다.
` viewers와 results 말고 해당 입력 결과 메세지 출력을 위한 dto`는 data로 viewers와 results를 갖는 dto를 말씀 하신게 맞을까요?
viewers와 results를 갖는 dto를 만들어서 적용했더니 이를 통해 반복문 제어도 쉽고, all과 같은 특수 커맨드에 의한 행동도 쉽게 정의할 수 있었습니다. 코드 자체도 훨씬 깔끔해졌고요.

> 그리고 enum 으로 quit, all과 같은 특수 커맨드를 생성해두면 더 좋을 것 같습니다.

정말 좋은 의견입니다! 😄 

---

이번 스텝에서 꼭 하고 싶었던 것이 **내 의견으로 리뷰어를 반박해보자!** 이었는데 수긍만 해버렸네요.
다음번 미션에서는 더 확실한 스스로의 기준을 세우는 것을 목표로 열심히 해보겠습니다!
이번에도 리뷰 정말 감사합니다.

2023-02-28 10:36 UTC, Be-poz approved these changes
마코 코드 반영된 것 잘 봤습니다. 사소한 하나의 피드백이지만 그것으로 인해 꽤나 많은 코드 수정이 있고 번거로우셨을텐데 잘 마무리 해주신 것 같네요!  

> 이번 스텝에서 꼭 하고 싶었던 것이 내 의견으로 리뷰어를 반박해보자! 이었는데 수긍만 해버렸네요.

라고 하셨지만, 제가 느끼기에는 마코만의 생각이 있고 그 생각들을 조금씩 발전시켜나가고 계신다는 느낌을 받았습니다. 코드도 정말 좋아서 2차 미션 코멘트 드릴 것도 별로 없었구요!  

네 dto는 해당 클래스의 정보를 담고있게끔 하면 어떨까요? 라는 의미가 맞습니다! 잘해주셨네요 ! 

이번 미션도 수고하셨고 다짐하신 것 처럼 본인만의 기준이 잘 세워지셨으면 좋겠습니다. 수고하셨습니다!

2023-02-28 10:36 UTC, merged