[1단계 - 사다리 생성] 아루(이동훈) 미션 제출합니다.
woowacourse/java-ladder pull request #251
Opened 2024-02-21 09:03 UTC by donghoony

안녕하세요 스티치! 6기 아루입니다. 반가워요 😊
이번 페어 프로그래밍은 굉장히 빠르게 진행되었어요. 둘 사이에 코드를 작성할 때 서로 이견이 거의 없었고 생각이 비슷했어요. 코드가 금방 작성되었지만, 그만큼 리팩터링할 것이 많이 보여서 고민도 많이 했고, 우리 둘이 잘못 생각하고 있으면 어쩌지? 라는 생각도 하게 되었습니다. 또 다른 사람의 눈으로 코드를 바라보면 어떤 의견이 나오게 될지 궁금해요. 많은 리뷰를 주고받으면서 코드에 대한 주관을 확실히 하고 싶습니다. 도움 주셔서 고맙습니다!

코드를 작성하면서 생긴 고민과 질문들을 함께 적어두겠습니다. 생각해볼 만한 것들에는 답변으로 질문을 주셔도 괜찮습니다. 잘 부탁드립니다!

### Enum은 어디에서 사용하면 좋을까요?
프로그래밍 요구사항에서 Enum을 사용하라는 요구사항이 있었지만, 어디에서 사용해야 할 지 필요성을 느끼지 못해 이번 코드리뷰를 위한 구현에서는 사용하지 않았습니다. 어떻게든 사용하라고 한다면 에러 메시지를 나타내거나, 출력 형식을 위한 Enum을 사용하게 될 것 같은데요. 그렇게 되면 너무 Enum 사용을 위한, 미션의 요구사항에 끼워맞추는 듯한 느낌이 들었어요.
Enum은 비슷한 곳에서 쓰이는 상수들에게 이름을 지어주는 것으로 이해했습니다. 프리코스의 로또 미션에서과 같은 경우 당첨과 관련해서 묶을 수 있는 속성이 있어서 사용하는 타당성에 대해 곧바로 이해했지만, 사다리 게임에서는 아직 고개를 끄덕일 만한 이유를 찾지 못했어요. 

### Random 테스트를 위한 `BooleanGenerator` 구현체 속 `BooleanGenerator`
현재 가로줄(한 층)에서 두 사다리를 잇는 방법을, `Boolean`을 받아내는 `generator`의 값에 따라 판별합니다. 기존에는 구현체 내부에서 요구사항 충족을 위해 이전에 `true`라면 반드시 `false`를 리턴하게끔 하고, 랜덤을 직접 사용했었어요. 하지만 이를 테스트하기 위해 다시 해당 랜덤값을 `BooleanGenerator`를 사용해 받아오게 했습니다. `BooleanGenerator`를 구현하는 구현체 내부에 `BooleanGenerator`를 넣어 테스트를 할 수 있게 되었지만, 이와 같은 구조는 처음 보는 상황이라 제대로 작성했는지에 대한 의문이 듭니다.

### 인터페이스 구현체와의 의존성
리팩터링 도중, `LadderBooleanGenerator`의 로직 때문에 다음과 같은 문제점이 발생하는 것을 확인했습니다.

 > 한 줄의 마지막 공간이 채워졌을 때, 다음 줄의 첫 공간은 채워질 수 있다. 
 > 하지만, 두 번 연속 `true`를 반환하지 않게 로직을 작성했기 때문에 항상 비어있게 된다

이를 해결하고자 다음과 같은 생각을 하게 되었어요.
- 구현체 내부에서 상태를 변경하는 메서드를 열면 된다.
- 하지만 그렇게 되는 경우, `HorizontalLine` 객체에서 초기화해줄 방법을 찾아야 하는데, `BooleanGenerator` 인터페이스를 파라미터로 받기 때문에 불가능하다.
- 매번 새로 생성하게 하면 된다. 하지만 이 경우 각 층마다 새로운 객체가 생성된다는 오버헤드와, `HorizontalLine`에서 `BooleanGenerator`를 받되, `Random::nextBoolean`을 받도록 해야 한다. (기존에는 `LadderBooleanGenerator`를 받아오게 했습니다.)
이 경우 위에서 설명한 구현체 속 인터페이스에 대한 혼란이 발생하게 되었어요. 이런 구조를 지양해야 하는 것일까요?

```java
// HorizontalLine.java

// 기존
public void createCrossingLines(BooleanGenerator generator) {  
    ladderConnections.clear();  
  
    Stream.generate(generator::generate)  
            .limit(playerCount - 1)  
            .forEach(ladderConnections::add);  
}
// 현재
public void createCrossingLines(BooleanGenerator generator) {  
    ladderConnections.clear();  
    
    LadderBooleanGenerator ladderGenerator = new LadderBooleanGenerator(generator);  
    Stream.generate(ladderGenerator::generate)  
            .limit(playerCount - 1)  
            .forEach(ladderConnections::add);  
}
```

### `List<HorizontalLineStatus>` 을 반환해주는 것은 적절할까?
출력을 위해 한 층의 정보를 가져와야 할 필요가 있었습니다. 두 사다리를 잇는 경우를 `List<Boolean>`으로 관리했는데요, *wrapper class*의 경우 불변이고, 이를 `HorizontalLineStatus`로 감싸 주었어요.
모든 사다리 정보를 가져올 때, 위 객체들을 `.toUnmodifiableList()`로 반환하므로 `List<HorizontalLineStatus>` 자체로 반환해도 괜찮다고 생각했어요. (물론 `HorizontalLineStatus` 또한 *record*이기 때문에 가져올 수 있습니다. 변경할 수 없도록 하는 것이 가장 중요한 점이었어요.)
결국 *getter*를 다른 말로 작성한 것이지만, 이렇게 작성하는 것이 위 설명으로 타당하게 설득할 수 있을 지 궁금합니다.

이외에도 테스트 작성, 객체의 책임 분리, MVC에 대해서 페어와 많은 이야기를 했습니다. 다양한 관점으로 코드에 대해서 말씀해주시면 페어와 다시 고민해보겠습니다. 고맙습니다!

2024-02-22 14:38 UTC, lxxjn0 requested changes
안녕하세요 아루, 이번에 리뷰를 진행하게 된 스티치입니다 :)

먼저 코드를 너무 잘 작성해주신 것 같아요 👍🏼 정말 미션의 요구사항에 맞게 너무 과하지도, 부족하지도 않은 코드를 작성해주셔서 리뷰하기도 너무 편했고 피드백 드릴 부분도 잘 보였던 것 같습니다.

1단계는 간단한 구현 미션으로 보여서 가볍게 피드백 남겨봤습니다. 한번 확인하고 피드백 반영 부탁드릴게요. 그리고 노파심에 드리는 말씀으로는 페어의 리뷰와 저의 리뷰가 조금 다르거나 의견이 상충되는 부분이 있을 수도 있어요. 그렇기에 페어의 리뷰는 참고 정도로 하고 저희들의 리뷰를 기반으로 피드백 반영해주시면 좋을 것 같습니다 :)

그리고 남겨주신 질문에 대한 답변입니다.
---
### Enum의 사용

만약 아루가 아직 Enum을 활용할만한 부분이 보이지 않았다면 쓰지 않는게 맞을 것 같습니다. 저도 아루의 코드를 보면서 굳이 Enum이 필요하다는 생각은 들지 않았어요. 앞으로 리뷰 진행해나가면서 enum으로 개선할 부분이 보인다면 그때 같이 이야기해보면 좋을 것 같아요 :)

### List<HorizontalLineStatus>의 반환

사실 출력에서 단순한 조회로 사용한다면 그냥 이름을 getter로 사용해도 괜찮을 것 같습니다. status 객체를 상태값의 저장으로만 사용하고 그 외의 데이터 가공이 없다고 한다면 너무 많은 고려를 하지 않고 간단하게 사용하셔도 괜찮을 것 같아요.

### Boolean Generator

이 부분은 저의 의견을 코멘트로 남겨두었는데 한번 확인 부탁드릴게요.

2024-02-22 14:38 UTC, lxxjn0 commented on README.md
> +## 페어와 지킨 컨벤션
페어 프로그래밍을 잘 하기 위한 좋은 방법인 것 같네요 👍🏼

2024-02-22 14:38 UTC, lxxjn0 commented on README.md
> +# 요구사항 분석
요구사항 분석 및 기능 구현 목록도 잘 작성하였고 커밋도 꼼꼼하게 잘 작성하셨네요 👍🏼

2024-02-22 14:38 UTC, lxxjn0 commented on src/main/java/LadderMain.java
> +        InputView inputView = new InputView(consoleReader);
이 부분에 대한 의견은 페어의 리뷰어와 동일하네요. 만든 것이 잘못된 코드는 아니지만 꼭 필요한 코드는 아닌 것 같아 간결하게 InputView 내부에서 입력 메서드를 처리해도 충분할 것 같습니다 :)

2024-02-22 14:38 UTC, lxxjn0 commented on src/main/java/generator/LadderFloorGenerator.java
> +public class LadderFloorGenerator implements FloorGenerator {
저는 FloorGenerator 인터페이스의 존재와 해당 인터페이스에 대한 구현의 문제보다는 LadderFloorGenrator 객체 사용 방향이 오히려 더 어색하게 느껴지는 것 같습니다. 

FloorGenerator는 층(가로줄) 생성을 위한 인터페이스로 보입니다. 그렇다면 랜덤하게 층을 생성하는 Generator가 있을 수 있고 순차적으로 번갈라가며 층을 생성하는 Generator도 있을 수 있을 것 같습니다(가정). 그런 경우 인터페이스의 구현체에 따라 생성 전략이 달라지고 그에 따른 구현체 이름이 설정되는 것이 자연스러울 것 같습니다. 

그런데 지금 사다라 층 생성자인 LadderFloorGenerator는 어떠한 booleanSupplier가 들어오는 지에 따라서 무한정 변할 수 있는 클래스로 보입니다. 그리고 사실상 FloorGenerator나 LadderFloorGenerator는 이름상 약간의 구체화(사다리)가 들어갔다는 것 말고는 같은 이름 같습니다.

층을 '어떠한 방법으로 생성하는 객체' 보다는 층을 '어떠한 방법으로도 생성할 수 있는 객체'라는 느낌에 가깝다고 할까요? 구현체에서 명확한 생성 방향이 드러나도록 이름을 짓고 사용하는 것이 오히려 더 프로그램에서의 생성 객체 역할과 책임을 드러내기 좋을 것 같습니다. 예시로 지금의 상황이라면 RandomFloorGenerator가 될 수 있을 것 같고요.

2024-02-22 14:38 UTC, lxxjn0 commented on src/main/java/game/LadderGame.java
> +    }
[질문] 만약 계속해서 예외가 발생하면서 무한재귀에 걸리게 된다면 어떤 문제가 발생할 수 있을까요?

2024-02-22 14:38 UTC, lxxjn0 commented on src/main/java/domain/Ladder.java
> +    }
[제안] 정적 팩토리 메서드를 사용하였네요. 이번에 정적 팩토리 메서드 뿐만 아니라 팩토리 메서드나 팩토리 패턴에 대해서도 한번 알아보시면 좋을 것 같아요. 그리고 해당 메서드를 조금 더 이름에 맞게 바꿔봐도 좋을 것 같습니다.

2024-02-22 14:38 UTC, lxxjn0 commented on src/main/java/domain/HorizontalLine.java
> +    private final int playerCount;
해당 필드가 없어도 이 객체를 만들 수 있지 않을까요? 결국 사용하는 값은 floor 필드로 보이는데 생성의 방식만 달리 한다면 충분히 가능할 것 같습니다!

2024-02-22 14:38 UTC, lxxjn0 commented on src/main/java/game/LadderGame.java
> +    }
[제안] 해당 코드를 보면 view에서 domain 객체를 생성하고 있습니다. 물론 의존의 방향이 잘못된 것은 아니지만 view에서 굳이 domain을 알도록 할 필요는 없을 것 같아요. view와 domain 사이의 의존을 조금 더 줄여보는 것은 어떨까요?

2024-02-22 14:38 UTC, lxxjn0 commented on src/main/java/domain/Name.java
> +    }
[의견] validateName 메서드를 나눈 이유가 깔끔한 코드를 작성하려고 한 것이 아닌가 싶습니다. 개인적으로는 굳이 메서드로 나눌 필요가 있나하는 생각이 듭니다. 단순히 validateNameLength와 validateNamePattern을 호출하는 코드가 있어도 가독성적인 측면에서 문제가 되지 않을 것 같아서요.

2024-02-22 14:38 UTC, lxxjn0 commented on src/main/java/domain/HorizontalLineStatus.java
> +public record HorizontalLineStatus(List<Boolean> placedStatuses) {
[질문] 해당 클래스가 과연 domain으로 관리되는 것이 맞을까요? 실제로 비즈니스 로직 중 어떠한 도메인으로 볼 수 있을까요?

2024-02-22 14:38 UTC, lxxjn0 commented on src/main/java/domain/LadderHeight.java
> +public record LadderHeight(int value) {
[의견] 개인적으로 LadderHeight와 Name 클래스가 도메인으로 관리되어야 하는가에 대해 약간 고민이 되는 것 같습니다. 실제로 코드 상에서 사용되는 모습을 보면 이 값이 도메인의 영역으로 관리되는 것보단 입력값에 대한 유효성 검증 객체로 사용된 이후 getter를 통해서만 활용되고 있어요.

어떻게 보면 입력값에 대한 유효성 검증 객체 정도의 느낌이 들기도 하고요. 아루의 생각은 어떠한가요?

2024-02-23 02:31 UTC, donghoony commented on src/main/java/generator/LadderFloorGenerator.java
> +public class LadderFloorGenerator implements FloorGenerator {
고맙습니다 스티치..! 조금 더 편하게 생각할 수 있는 방법이 있는 것 같아 한 층에서 생성을 담당하도록 변경했어요. 추후에 다른 요구사항이 들어오면 그때 구체화하면 되겠다! 라는 생각이 들어 `generator` 패키지를 과감하게 삭제합니다.

2024-02-23 02:36 UTC, donghoony commented on src/main/java/game/LadderGame.java
> +    }
`StackOverflow` 문제가 발생하는 것은 알고는 있었지만, 원래 `while`문으로 감싸는 것을 indent 제한 때문에 재귀로 바꾸게 되었어요. 

고민을 많이 해도 인덴트와 성능을 동시에 챙기는 것이 어렵네요.. 더 고민해보겠습니다

2024-02-23 02:36 UTC, donghoony commented on src/main/java/domain/HorizontalLine.java
> +    private final int playerCount;
`HorizontalLine`에서는 행의 패턴을 만드는 데에 집중하고, `Names`와 같은 일급 컬렉션에서 이를 검증하면 좋을 것 같네요!

2024-02-23 02:37 UTC, donghoony commented on src/main/java/domain/Name.java
> +    }
이번 TDD 사이클을 다시 한번 돌아보고 있는데요, TDD의 장점이 과한 코드 작성 (Overengineering)을 방지하는 점에서 큰 메리트가 있는 것 같습니다.

아직 예전의 습관을 버리지 못해 가독성을 챙긴다고 작성한 코드지만 되려 눈의 움직임이 더 필요한 코드가 되었네요, 수정하겠습니다

2024-02-23 02:41 UTC, donghoony commented on src/main/java/domain/HorizontalLineStatus.java
> +public record HorizontalLineStatus(List<Boolean> placedStatuses) {
제가 MVC 패턴에는 익숙하지 않아서 **객체의 책임과 관심사**에 대해서 계속해서 상기하며 코드를 작성하고 있습니다.

MVC에서의 패키지 형태는 model(domain), view, controller(LadderGame) 정도로 되는 것 같은데, 해당 패키지는 각 레이어 간 정보 전달이 목적이라 셋 중에는 도메인의 성격이 강하다고 느꼈어요.

그런데 사실 도메인은 도메인 로직 (비즈니스 로직이겠죠?)을 가지는 클래스들이 주를 이루는데, 이런 정보를 담는 객체들은 붕 뜨는 느낌이 들기도 합니다.

`어떠한 도메인` 이라는 것을 조금 더 설명해주시면 제 의견을 더할 수 있을 것 같아요. 고맙습니다 😊

2024-02-23 02:45 UTC, donghoony commented on src/main/java/domain/LadderHeight.java
> +public record LadderHeight(int value) {
요구사항의 **원시값 포장**에 대해서 생각을 해 보았습니다. 아직 새로 잡힌 생각이 코드에는 담기지 않아 리팩터링을 추가로 진행할 예정이예요.

원시값 포장은 값에 이름을 붙여 주는 역할도 있지만, 추가로 타입 의존성을 제거한다는 이점을 가진다고 생각했습니다. 해당 값을 필요로 하는 여러 메서드들이 존재할 텐데, 타입을 바꿔야하는 순간에는 그 메서드들의 파라미터 타입도 모두 바꿔줘야 하기 때문이에요.

다만 포장을 하는 경우에는 타입과 무관하게, 해당 Wrapper class에서만 수정사항을 처리하면 된다고 보았습니다. 이렇게 되면 모든 메서드에서 wrapper class로만 받아서 처리할 수 있고, 타입 의존성을 제거해 보다 유연하게 유지보수가 가능하겠네요.

원시값을 포장하고, 해당 wrapper class가 역할을 가지도록 수정하면 좋을 것 같습니다. 단순 `getter`만 사용해서 현재 코드에는 포장하는 의미가 없어 보이네요 🙄

2024-02-23 05:29 UTC, donghoony commented on src/main/java/game/LadderGame.java
> +    }
View에서는 원시값을 다루도록 의존성을 제거하는 편이 훨씬 낫겠네요. 조립은 Controller(Game)에서 하는 게 더 자연스럽습니다. 수정합니다!

2024-02-23 05:29 UTC, donghoony commented on src/main/java/domain/LadderHeight.java
> +public record LadderHeight(int value) {
`LadderHeight` 포장 클래스를 추가합니다.

2024-02-23 14:59 UTC, donghoony commented on src/main/java/game/LadderGame.java
> +    }
`Stream.iterate`를 활용한 `LooperFunction`을 도입해 해결합니다. 고민을 많이 해서 원하는 결과를 얻어낸 것이 좋네요! 하지만 클래스가 좀 무거워 보여서 고민입니다.

블로그에 생각의 흐름도 적어 보았어요.
https://blog.hoony.me/2024/02/23/retry-on-exception-with-less-indentation/

2024-02-23 15:27 UTC, donghoony commented on src/main/java/domain/Ladder.java
> +    }
공부할 거리 고맙습니다! 팩토리 메서드/패턴에 대해서 알아보았습니다만, 현재 이 구조에서는 사용하기 적합하지 않다고 판단했어요. 추가적인 랜덤 로직이 필요하다면 그 때 추가해도 늦지 않을 것이라고 생각합니다.

나아가 해당 네이밍 컨벤션이 `플레이어와 높이를 가지는 사다리를 생성한다`라는 의미로 `of`를 쓰는 것이 적절하다고 생각했었는데, 어떤 부분에서 어색하게 느끼셨는지 궁금해요!

2024-02-23 15:28 UTC, donghoony commented on src/main/java/domain/Ladder.java
> +    }
https://en.wikipedia.org/wiki/Factory_method_pattern
를 확인했습니다.

2024-02-23 15:36 UTC, donghoony commented
안녕하세요 스티치! 리뷰를 주신 지 조금 지났지만 이제야 다시 리뷰를 요청합니다..! 그동안 코드에 많은 변화가 있었어요.
[브랜치](https://github.com/donghoony/woowacourse-level-1-ladder/tree/tdd)를 하나 더 만들어서 코드를 다시 엎고(...) TDD 사이클을 철저하게 지키면서 코드를 짜 보았는데요, 과하게 구조를 생각한 코드 작성이 배제된다는 점이 정말 마음에 들었어요. 큰 구조를 먼저 생각하지 않으니 구현 시간도 훨씬 짧아졌고요.

남겨주신 대부분의 의견은 답변을 남긴 뒤 반영하여 `resolve conversation` 처리를 해 두었습니다. 다만 제 생각과 충돌했던 몇 가지 의견은 닫지 않고, 추가로 질문을 남겨 두었으니 확인해주시면 감사하겠습니다.

### 변동사항
이번에 큰 변동사항은 네이밍, `generator`의 삭제입니다. 사다리의 한 줄이 이전에 놓았는지 여부를 확인하도록 하고, 외부에서 주는 `true/false` 값을 통해 계산하도록 했어요. 이렇게 구현하니 한 줄을 설계하는 인터페이스가 필요없게 되었습니다.

나아가 조금 더 나은 네이밍을 위해 `Pattern`이라는 네이밍을 사용했어요. 사다리를 놓고/놓지 않고를 하나의 패턴으로 보았습니다. 디자인 패턴과는 의미가 다른데, 혼란이 될 수 있으려나요?

오버플로우의 위험성을 생각해 해당 부분을 개선하면서 인덴트 1을 지키는 방법에 대해서 오늘 하루종일 고민하게 되었습니다. `Stream`을 주욱 공부하면서 무한 스트림을 알게 되었고, 이를 활용해 적용했습니다. 프리코스 때부터 고민했던 내용이 잘 해결돼 [블로그](https://blog.hoony.me/2024/02/23/retry-on-exception-with-less-indentation/)에도 글을 정리해 보았어요. 다만 클래스가 조금 무거운 감이 있어 괜찮을지에 대한 걱정은 덜지 못했습니다. `Optional`과 `while`을 사용한 다른 크루들의 코드도 구경했었는데, 그렇게 하는 게 나았으려나 싶네요 😁

이번 구현 사항에서 조금 더 생각해봄직한 부분들을 간지럽혀 주시면 확인해 보고 고민해보겠습니다! 좋은 주말 되세요!

2024-02-24 14:34 UTC, lxxjn0 commented on src/main/java/domain/Ladder.java
> +    }
엇, 메서드 이름은 제가 다른 곳에 남길 리뷰를 여기 작성해뒀나보네요 ㅠㅠ

2024-02-24 14:38 UTC, lxxjn0 commented on src/main/java/domain/HorizontalLineStatus.java
> +public record HorizontalLineStatus(List<Boolean> placedStatuses) {
도메인은 비즈니스에서 관심의 영역을 보통 말합니다. 예를 들어 지금 사다리라는 비즈니스를 표현하기 위한 Ladder가 그런 예시 중 하나입니다. 

해당 객체는 실제 사다리의 어떠한 상태를 기록하고 이를 출력하기 위한 객체로 보입니다. 이 객체가 없더라도 view에 출력하는 것은 가능하나, 도메인 로직이 view와 연관을 가지는 것을 끊기 위해 작성된 객체입니다. 흔히 DTO라고 불리우는 객체로 볼 수 있을 것 같은데 이러한 객체는 도메인의 영역보다는 controller나 view 쪽에 더 적절한 객체라고 생각해요. 실제 비즈니스의 관심 영역을 표현하는 객체가 아닌 도메인 객체의 view 의존성을 끊기 위한 연결 객체이니깐요.

DTO에 대해 한번 공부해보시는 것도 도움이 될 것 같습니다.

2024-02-24 14:57 UTC, lxxjn0 approved these changes
아루 피드백 반영하시느라 수고하셨습니다.

이번 단계는 오래 잡고있을 이유는 없을 것 같아 간단한 피드백만 남겨드렸고 이후 2단계 진행하면서 추가적인 리뷰를 진행해도 될 것 같아요.

그리고 코드 전반적으로 이름에 대해 조금 더 고민해보면 좋을 것 같아요. 단순히 value라는 이름은 너무 보편적이고 명확하지 않아서 코드에서 값의 의미나 의도를 드러내기에 어려운 이름이라 생각합니다. 그 외적으로도 이름을 선택할 때는 이 코드의 맥락을 모르는 사람이 봐도 이해가 갈 수 있도록 작성하는 것이 좋을 것 같고요. 이 부분을 한번 생각해보시면 좋을 것 같습니다.

하지만 이보다 더 드리고 싶은 말씀이 있습니다. 

이번 코드를 보면 사용자의 입력을 다시 반복해서 받는 부분에 많은 공을 들이신 것 같습니다. 사실 아루 뿐만이 아니라 다른 리뷰이들의 코드에서도 공통적으로 이 부분에 대한 노력과 다양한 기술과 언어적 기교를 넣으면서 코드를 작성하는 것 같았습니다. 

그런데 '사용자의 입력이 적절하지 않을 경우 재입력을 받는다'라는 요구사항이 이번 미션에 있었나요? 중요한 것보다는 중요하지 않은 것에 너무 많은 노력과 집중을 하시는 것 같아요. 이번 단계는 TDD를 잘 하는 것과 이어서 객체의 분리, 어떻게 하면 도메인 로직을 코드로 더 적절하게 옮길 수 있는지가 가장 중요한 부분이라 생각합니다. 

요구사항에 존재하지도 않을 뿐더러, 만약 존재한다고 하더라도 중요하다고 생각되지 않는 부분에 너무 많은 관심을 가지는 것이 안타깝다는 생각이 들었습니다.

2단계를 진행할 때에는 지금 레벨1에서 어떤 것을 배워야 하는지에 대해 한번 더 생각하고 그 부분에 초점을 맞춰서 코드를 작성해보시는 것이 더 좋은 방향이 아닐까 생각합니다.

2024-02-24 14:57 UTC, lxxjn0 commented on src/main/java/LadderMain.java
> +        InputView inputView = new InputView(scanner::nextLine);
Scanner가 InputView에서만 사용될 것 같은데 InputView 내에서 생성해 관리하는 것이 어떨까요?

2024-02-24 14:57 UTC, lxxjn0 commented on src/main/java/domain/ladder/Ladder.java
> +    }
해당 로직을 보면 생성자를 호출하는 것과 정적 팩토리 메서드를 호출하는 것이 전혀 차이가 나지 않습니다. 그렇다면 이 두 메서드를 분리한 이유가 무엇일까요?

2024-02-24 14:57 UTC, lxxjn0 commented on src/main/java/domain/ladder/LadderHeight.java
>      }
[제안] 사다리의 높이에 대한 확인 메서드인데 길이라는 단어를 쓰는 것이 어색한 것 같습니다. 파라미터도 마찬가지로 높이와 같은 맥락의 이름을 사용하는 것은 어떨까요?

추가로 메서드 명이 약간 헛갈리는 것 같은데 matches라던지 isSameHeight 처럼 단순한 이름을 사용해보는 것도 좋을 것 같습니다.

2024-02-24 14:57 UTC, lxxjn0 commented on src/main/java/domain/ladder/LadderRow.java
> +    public void createPattern(BooleanSupplier supplier) {
파라미터 이름을 좀 더 명확하게 지어보는 것은 어떨까요? 단순히 supplier라는 이름은 이 매개변수가 어떠한 역할이나 동작을 하는 값인지 전혀 유추가 되지 않을 것 같습니다.

2024-02-24 14:57 UTC, lxxjn0 commented on src/main/java/util/LoopFunction.java
> +    }
setter의 사용을 지양하는 것이 좋지 않을까요?

2024-02-24 14:57 UTC, lxxjn0 commented on src/main/java/domain/ladder/LadderRowPattern.java
> +public record LadderRowPattern(List<Boolean> rowPattern) {
해당 클래스 명을 보면 어떠한 역할을 하는 객체인지 유추가 잘 되지 않는 것 같아요. 좀 더 단순하고 명확한 이름을 고민해봐도 좋을 것 같습니다.

2024-02-24 14:57 UTC, merged

2024-02-25 07:27 UTC, donghoony commented on src/main/java/domain/ladder/Ladder.java
> +    }
`of` 네이밍이 단순한 `new Ladder` 생성자보다 조금 더 정확한 의미를 전달한다고 생각했어요.

2024-02-25 07:46 UTC, donghoony commented on src/main/java/domain/ladder/LadderRowPattern.java
> +public record LadderRowPattern(List<Boolean> rowPattern) {
`Pattern`이 역시 의미 전달에 좋은 단어는 아니었던 것 같네요. 고민해보겠습니다.

2024-02-25 07:46 UTC, donghoony commented on src/main/java/LadderMain.java
> +        InputView inputView = new InputView(scanner::nextLine);
외부 라이브러리와 의존되는 것이 별로라고 생각이 들어서 의존성을 끊어내는 데에 집중했습니다만, _지금 당장_ 인터페이스를 구현해서 의존성을 떼어내야 할 필요가 있는가? 에 대해서는 확실한 대답을 하지 못하겠네요.
사실 해당 부분을 테스트를 위해 만들었다고 생각했는데, 다시 생각해 보면 `Integer.parseInt`와 같은 이미 검증된 외부 라이브러리를 테스트하고 있다는 생각이 들었습니다.

2024-02-25 07:46 UTC, donghoony commented on src/main/java/LadderMain.java
> +        InputView inputView = new InputView(scanner::nextLine);
해당 부분 테스트를 삭제합니다!

2024-02-25 07:58 UTC, donghoony commented on src/main/java/util/LoopFunction.java
> +    }
해당 부분은 요구사항에 없는 내용이라 삭제합니다.

2024-02-25 08:22 UTC, donghoony commented on src/main/java/domain/ladder/LadderRowPattern.java
> +public record LadderRowPattern(List<Boolean> rowPattern) {
레이어 간 데이터 교환을 목적으로 하므로, `Dto`를 붙입니다.

2024-02-25 08:26 UTC, donghoony commented on src/main/java/util/LoopFunction.java
> +    }
요구사항에 없었던 내용을 삭제합니다. 크게 필요하지 않았던 내용으로 리뷰하는 데 불편함을 드려 죄송하네요 😶

2024-02-25 08:26 UTC, donghoony commented on src/main/java/domain/ladder/LadderRow.java
> +    public void createPattern(BooleanSupplier supplier) {
`patternGenerator`로 변경합니다.

2024-02-25 08:37 UTC, donghoony commented on src/main/java/domain/ladder/LadderHeight.java
>      }
`isSameHeightAs`로 수정합니다! 파라미터도 `height`으로 변경해 보다 명확히 했습니다.