[1단계 - 사다리 생성] 상돌(이상진) 미션 제출합니다.
woowacourse/java-ladder pull request #252
Opened 2024-02-21 10:48 UTC by pricelees

안녕하세요! 저는 6기 상돌(이상진) 이라고 합니다.😄

제 페어와 코드를 작성하는 관점이 너무 비슷해서, 이번 미션은 생각보다 빠르게 진행되었다는 생각이 들어요. 
하지만 한편으로는, **서로 다른 의견을 가지고 이야기해보는 시간이 부족**했다는 생각도 들었고, 그래서 리뷰를 통해 다른 다양한 관점을 들어보고 싶습니다. 몇몇 궁금했던 것들은 질문을 남겨두었습니다. 잘 부탁드립니다!🙏🏻

**인터페이스의 구현체마다 생성자를 다르게 지정해도 될까요?**
`LadderFloorGenerator` 클래스는 생성할때 `BooleanSupplier`를 입력받습니다. 이렇게 구현해서 기존의 문제를 해결할 수는 있었지만, **구현체마다 생성 방법이 달라질 수 있다**는 생각이 들기도 해요. 이것에 대한 의견을 들어보고 싶습니다!

**Enum을 꼭 사용해야 할까요?** 
우선 Enum을 사용하지 않고 구현했고, 리팩터링 할 때는 요구사항에 있는 `Enum을 적용한다`를 반영하려고 했어요. 하지만 Enum을 만들어야할 필요성을 찾지 못했습니다 ㅠ `사다리 모양`과 관련된 상수를 분리할까? 라고 생각했으나, Enum으로 분리했을 때의 장점을 찾지 못했고 오히려 요구사항을 만족하기 위해 맞추는 느낌이 들어 결과적으로는 적용하지 않았습니다. Enum의 사용 기준은 어떻게 잡아야 할지에 대한 의견을 들어보고 싶어요!

**View에서 Name과 LadderHeight를 사용해도 될까요?**
`InputView`와 `OutputView` 클래스에서, 이름과 관련된 `Name`과 사다리의 높이인 `LadderHeight`를 사용하고 있어요. 저희는 Name과 LadderHeight는 별도의 로직이 없는 포장용 객체이므로 View에서 이용해도 된다는 생각이었는데, 동시에 View가 도메인을 받는 느낌도 들기도 해요. 리뷰어님께서는 어떻게 생각하시나요?

2024-02-21 14:30 UTC, choijy1705 requested changes
안녕하세요 상돌!
빠르게 미션 구현해주셨네요!
질문에 답변과 피드백을 남기다보니 코멘트가 좀 많아졌네요
확인부탁드립니다!🙏

2024-02-21 14:30 UTC, choijy1705 commented on src/main/java/LadderMain.java
> +        ladderGame.play();
Controller는 따로 없는건가요?
자동차 게임 미션때 mvc를 떠올려보면 좋을것 같네요!

2024-02-21 14:30 UTC, choijy1705 commented on src/main/java/view/ConsoleReader.java
> +public class ConsoleReader implements Reader {
해당 클래스를 만든 이유가 궁금합니다?
필요한 클래스일까요??

2024-02-21 14:30 UTC, choijy1705 commented on src/main/java/domain/Ladder.java
> +    }
불필요한 메서드 분리일것 같아요🤔
생성자 안에서 처리하면 안될까요?

2024-02-21 14:30 UTC, choijy1705 commented on src/main/java/domain/Ladder.java
> +    private final List<HorizontalLine> lines = new ArrayList<>();
생성자에서 초기화 해주세요

2024-02-21 14:30 UTC, choijy1705 commented on src/main/java/domain/HorizontalLine.java
> +    private final List<Boolean> floor = new ArrayList<>();
생성자에 초기화해주세요!

2024-02-21 14:30 UTC, choijy1705 commented on src/main/java/game/LadderGame.java
> +public class LadderGame {
이 클래스를 컨트롤러로 생각하고 작성하신건가요?
그렇다면 Controller라는걸 명시하는 네이밍이면 좋을것 같아요!

2024-02-21 14:30 UTC, choijy1705 commented on src/main/java/LadderMain.java
> +        LadderGame ladderGame = new LadderGame(inputView, outputView, floorGenerator);
generator를 여기서 부터 생성해서 처리할 필요가 있을까요??

2024-02-21 14:30 UTC, choijy1705 commented on src/main/java/domain/HorizontalLineStatus.java
> +public record HorizontalLineStatus(List<Boolean> placedStatuses) {
이 클래스는 어떤 역할인가요??

2024-02-21 14:30 UTC, choijy1705 commented on src/main/java/generator/FloorGenerator.java
> +public interface FloorGenerator {
인터페이스의 필요성을 잘 모르겠습니다!

2024-02-21 14:30 UTC, choijy1705 commented on src/main/java/generator/LadderFloorGenerator.java
> +    public LadderFloorGenerator(BooleanSupplier supplier) {
> 인터페이스의 구현체마다 생성자를 다르게 지정해도 될까요?

구현체의 생성자는 다를 수 있죠!
여기서는 인터페이스의 필요성에 대해서 고민해봐야할 것 같습니다!
상돌은 어떤점에서 인터페이스의 필요성을 느끼셨을까요??

2024-02-21 14:30 UTC, choijy1705 commented on src/main/java/view/Reader.java
> +public interface Reader {
왜 필요한가요??🤔🤔

2024-02-21 14:30 UTC, choijy1705 commented on src/test/java/domain/HorizontalLineTest.java
> +    @ValueSource(ints = {2, 3, 4, 5, 6, 7, 8, 9, 10})
경계값만 테스트해보면 좋을것 같아요
실제 실무에서는 테스트도 비용입니다!!
최소한으로 필요한 정보만 테스트하도록 짜는것도 중요합니다🙏

2024-02-21 14:30 UTC, choijy1705 commented on src/main/java/view/OutputView.java
> +    public void printNames(List<Name> names) {
> View에서 Name과 LadderHeight를 사용해도 될까요?
name과 ladderHeight모두 도메인이라서 mvc의 취지에는 벗어나는것일것 같네요!

2024-02-21 14:30 UTC, choijy1705 commented on src/test/java/domain/LadderHeightTest.java
> +    @ValueSource(ints = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10})
valueSource등등 반복적으로 테스트할 필요가 있을까요??
한번만 테스트해도 될걸 10번 반복하고 있게되네요 지금은!

2024-02-21 14:30 UTC, choijy1705 commented on src/test/java/game/LadderGameTest.java
> +                );
요구사항이 조금만 변해도
변경을 해야하는 테스트가 아닐까요??😭

2024-02-21 14:30 UTC, choijy1705 commented on src/main/java/domain/HorizontalLine.java
> +    private final List<Boolean> floor = new ArrayList<>();
> Enum을 꼭 사용해야 할까요?

필요성을 느끼지 않으셨다면 저도 꼭 따라야할 필요는 없을것 같아요!
요구사항의 의도는 정확히 모르겠지만
제 생각에는 boolean으로 표현한 부분을 의미있게 enum으로 표시할 수 있을것 같네요
boolean 보다는 사다리의 다리가 있고 없고를 더 잘 표현할 수 있지 않을까요??

2024-02-21 14:30 UTC, choijy1705 commented on src/main/java/domain/HorizontalLine.java
> +public class HorizontalLine {
수평보다 수직의 의미인 라인 아닌가요??

2024-02-22 06:44 UTC, pricelees reviewed
안녕하세요!

말씀해주신 피드백은 페어와 함께 많은 고민을 해봤고, 우선 커멘트에 대한 답변을 드립니다!
코드 수정은 페어의 리뷰가 오면 같이 반영해서 진행하겠습니다. 

꼼꼼하게 봐주셔서 정말 감사드립니다!!

2024-02-22 06:44 UTC, pricelees commented on src/main/java/LadderMain.java
> +        ladderGame.play();
> Controller는 따로 없는건가요? 자동차 게임 미션때 mvc를 떠올려보면 좋을것 같네요!

>이 클래스를 컨트롤러로 생각하고 작성하신건가요?
>그렇다면 Controller라는걸 명시하는 네이밍이면 좋을것 같아요!

MVC 구조이면 **컨트롤러 역할을 맡는 클래스엔 Controller 접미사를 붙여야 할까요**?

저희가 구현하는 과정에서는 `LadderGameController`보단 `LadderGame`으로 작명하는 것이 **게임을 진행하는 의도를 더 잘 나타낸다는 생각**이었어요. 

그런데 다르게 생각해보니 `LadderGameController`가 게임의 진행을 설명하기에 부족하지 않다는 생각이 들었고,  `Controller`를 붙이는게 `View`와 `Domain`을 이용하는 것을 더 명시적으로 나타낼 수 있다는 생각이 들기도 하네요. 영이님께서는 후자의 의견으로 말씀하신 것일까요?

2024-02-22 06:44 UTC, pricelees commented on src/main/java/domain/HorizontalLine.java
> +public class HorizontalLine {
> 수평보다 수직의 의미인 라인 아닌가요??

전체 사다리를 **여러개의 수평인 층**으로 나누었고, 여기서 `HorizontalLine`은 한 개의 층을 나타냅니다..ㅎㅎ

2024-02-22 06:44 UTC, pricelees commented on src/main/java/domain/HorizontalLine.java
> +    private final List<Boolean> floor = new ArrayList<>();
> > Enum을 꼭 사용해야 할까요?
> 
> 필요성을 느끼지 않으셨다면 저도 꼭 따라야할 필요는 없을것 같아요! 요구사항의 의도는 정확히 모르겠지만 제 생각에는 boolean으로 표현한 부분을 의미있게 enum으로 표시할 수 있을것 같네요 boolean 보다는 사다리의 다리가 있고 없고를 더 잘 표현할 수 있지 않을까요??

정말 좋은 아이디어 같습니다..ㅎㅎ 한번 잘 반영해보겠습니다. 감사합니다!👏

2024-02-22 06:44 UTC, pricelees commented on src/main/java/domain/HorizontalLineStatus.java
> +public record HorizontalLineStatus(List<Boolean> placedStatuses) {
> 이 클래스는 어떤 역할인가요??

**사다리의 한 층의 연결 정보**를 저장하고, 도메인과 뷰 간의 데이터 전달에 사용되고 있습니다!

2024-02-22 06:44 UTC, pricelees commented on src/main/java/domain/Ladder.java
> +    }
> 불필요한 메서드 분리일것 같아요🤔 생성자 안에서 처리하면 안될까요?

만약 `생성자에서 처리해야할 로직이 여러개`라면 분리를 하는게 좋겠지만, 지금 상황에서는 말씀하신 것처럼 **생성자 안에서 처리**하는게 더 좋다는 생각이 들었어요. for문 안의 로직이 복잡한 로직도 아니니깐요!

2024-02-22 06:44 UTC, pricelees commented on src/main/java/generator/FloorGenerator.java
> +public interface FloorGenerator {
> 인터페이스의 필요성을 잘 모르겠습니다!

이 인터페이스의 구현 클래스인 `LadderFloorGenerator`에서 `BooleanSupplier`를 받아 사용하는 구조이니, 지우는게 더 좋겠네요..!! 감사합니다!

2024-02-22 06:44 UTC, pricelees commented on src/main/java/generator/LadderFloorGenerator.java
> +    public LadderFloorGenerator(BooleanSupplier supplier) {
> > 인터페이스의 구현체마다 생성자를 다르게 지정해도 될까요?
> 
> 구현체의 생성자는 다를 수 있죠! 여기서는 인터페이스의 필요성에 대해서 고민해봐야할 것 같습니다! 상돌은 어떤점에서 인터페이스의 필요성을 느끼셨을까요??

초기에 구현했던 방식은 `LadderFloorGenerator`에서 `BooleanSupplier`를 사용하지 않는 방식이었어요. 
하지만 이 방법대로 하니 예외가 발생했고, 수정하는 과정에서 `BooleanSupplier`를 입력받도록 하니 이 부분에선 `FloorGenerator` 인터페이스가 필요하지 않겠다는 생각이 들었습니다..ㅎㅎ

2024-02-22 06:44 UTC, pricelees commented on src/main/java/view/ConsoleReader.java
> +public class ConsoleReader implements Reader {
> 해당 클래스를 만든 이유가 궁금합니다? 필요한 클래스일까요??

`InputView`에서 `Reader`를 입력받도록 하여, 테스트를 용이하게 진행하기 위함이었습니다.
그런데 생각해보니, 테스트에선 `ConsoleReader`를 사용하지 않기도 하고, `LadderMain`에서 InputView의 생성을 다음과 같이 수정하면 `ConsoleReader`가 필요하지 않다는 생각이 들었습니다. 이 방법에 대해서 의견을 부탁드리고 싶습니다!👍

```java
Scanner scanner = new Scanner(System.in);
InputView inputView = new InputView(scanner::readLine);
```

2024-02-22 06:44 UTC, pricelees commented on src/main/java/view/OutputView.java
> +    public void printNames(List<Name> names) {
> > View에서 Name과 LadderHeight를 사용해도 될까요?
> > name과 ladderHeight모두 도메인이라서 mvc의 취지에는 벗어나는것일것 같네요!

만약 View에서 `Name`과 `LadderHeight`를 없애려면, 컨트롤러에서 `Name`과 `LadderHeight` 를 한번 더 파싱해서 뷰에 전달해야 합니다. 저희가 생각한 것은, `Name`과 `LadderHeight`는 비즈니스 로직이 없는 단순 Value Object 형태이기에 이것을 View에서 제거하기 위해 컨트롤러에서 값을 다시 파싱해서 넘겼을 때의 장점이 크지 않다고 생각했습니다. 이 상황에서 View에서 `Name`과 `LadderHeight`를 제거할 만큼의 장점이 있을까요?🙏🏻

2024-02-22 06:44 UTC, pricelees commented on src/main/java/view/Reader.java
> +public interface Reader {
> 왜 필요한가요??🤔🤔

Reader를 InputView에서 사용하도록 하여, 테스트할 때 사용하기 위함이었습니다😀😀

2024-02-22 06:44 UTC, pricelees commented on src/test/java/domain/HorizontalLineTest.java
> +    @ValueSource(ints = {2, 3, 4, 5, 6, 7, 8, 9, 10})
> 경계값만 테스트해보면 좋을것 같아요 실제 실무에서는 테스트도 비용입니다!! 최소한으로 필요한 정보만 테스트하도록 짜는것도 중요합니다🙏

테스트 범위가 크지 않으니 모두 넣어보는 것도 좋을거라는 생각이었는데, 불필요했다는 생각이 드네요. 감사합니다!!👍

2024-02-22 06:44 UTC, pricelees commented on src/test/java/game/LadderGameTest.java
> +                );
> 요구사항이 조금만 변해도 변경을 해야하는 테스트가 아닐까요??😭

이 테스트가 요구사항에 의존이 있긴 하지만, 이 의존의 문제는 요구사항이 변경되었을 때 생각해봐도 될 것이라는 생각이었습니다..ㅎㅎ 어디까지 생각해야할지가 항상 큰 고민이긴 한 것 같아요😢

2024-02-23 10:49 UTC, pricelees commented on src/main/java/LadderMain.java
> +        LadderGame ladderGame = new LadderGame(inputView, outputView, floorGenerator);
> generator를 여기서 부터 생성해서 처리할 필요가 있을까요??

`LadderFloorGenerator`를 Ladder에 넣어주는 것도 좋을 것 같습니다! 이 부분은 조금 더 고민해보겠습니다 ㅎㅎ

2024-02-23 16:04 UTC, choijy1705 approved these changes
상돌 피드백 반영 잘해주셨네요!👍
이번 단계는 머지하겠습니다!
추가 피드백은 다음단계  진행하면서 반영해주세요!

2024-02-23 16:04 UTC, choijy1705 commented on src/main/java/domain/HorizontalLineStatus.java
> +public record HorizontalLineStatus(List<Boolean> placedStatuses) {
데이터 전달에 쓰이면 DTO로 명명하는게 어떨까요?

2024-02-23 16:04 UTC, choijy1705 commented on src/main/java/domain/Ladder.java
> +		lines = new ArrayList<>();
```suggestion
		this.lines = new ArrayList<>();
```

2024-02-23 16:04 UTC, choijy1705 commented on src/main/java/domain/Ladder.java
> +    }
stream을 활용하면 더 간단히 표현할 수도 있겠네요

2024-02-23 16:04 UTC, choijy1705 commented on src/main/java/view/ConsoleReader.java
> +public class ConsoleReader implements Reader {
scanner를 꼭 생성자로 주입안해도 되지 않을까요?
inputView에서만 쓰이니 inputView 내부적으로 scanner 를 생성하는게 더 명확하게 코드를 표현할 수 있을것 같습니다!

2024-02-23 16:04 UTC, choijy1705 commented on src/main/java/view/OutputView.java
> +    public void printNames(List<Name> names) {
Name과 LadderHeight을 비즈니스 로직이 없는 단순 VO라고 생각하셨다면
원시값 포장을 할 필요가 있을까도 고민해보면 좋을것 같습니다!
요구사항이라서 쓰셨다고하면 할말이없지만...

2024-02-23 16:04 UTC, choijy1705 commented on src/main/java/view/Reader.java
> +public interface Reader {
참고로 테스트를 위한 코드는 최대한 작성하지 않는것이 좋다고 생각합니다!

2024-02-23 16:04 UTC, choijy1705 commented on src/test/java/game/LadderGameTest.java
> +                );
이런게 한두개씩 쌓이면
리팩토링을 할 수 없는 지경에 이릅니다...😭

2024-02-23 16:04 UTC, choijy1705 commented on src/main/java/generator/LadderFloorGenerator.java
> +	private final BooleanSupplier supplier;
이런 util도 있군요...
범용적으로 사용하는 방법은 아닌것 같은데
조금 더 일반적으로 사용하는 방법으로 이 클래스를 변경할 수 있을까요??

2024-02-23 16:04 UTC, choijy1705 commented on src/main/java/LadderMain.java
> +        ladderGame.play();
꼭 붙여야 한다기보다
MVC 구조는 결국 다른 사람도 쉽게 이해할 수 있도록 하나의 규칙을 정해놓은거죠!
그러니 다른 사람들은 당연히 Controller가 있겠거니 하고 코드를 보는데 
찾을 수 없으니 명확하게 전달 안될 가능성이 크다고 봅니다

2024-02-23 16:04 UTC, merged