[1단계 - 사다리 생성] 커비(이현지) 미션 제출합니다.
woowacourse/java-ladder pull request #262
Opened 2024-02-22 05:31 UTC by skylar1220

2024-02-23 02:53 UTC, summerlunaa requested changes
커비 안녕하세요~ 리뷰어 파랑입니다 🐳

이제 두 번째 미션이네요!! TDD 방식으로 잘 진행해주셨습니다 👍
리뷰 남겼으니 확인부탁드립니다.

수고하셨습니다~ 👏

2024-02-23 02:53 UTC, summerlunaa commented on src/main/java/Controller/LadderGame.java
> +        final Carpenter carpenter = hireCarpenter(height, players);
ㅎㅎ 목수라는 표현이 귀엽군요 하지만 명확한 네이밍은 아닌 것 같습니다. 좀 더 직관적인 이름으로 변경해보는 건 어떨까요?
Carpenter 내부의 필드명과 메서드명도 마찬가지입니다.

2024-02-23 02:53 UTC, summerlunaa commented on src/main/java/Application.java
> +        LadderGame ladderGame = new LadderGame(InputView.of(new Reader(), printer), OutputView.from(printer));
```suggestion
        Printer printer = new Printer();
        Reader reader = new Reader();
        LadderGame ladderGame = new LadderGame(InputView.of(reader, printer), OutputView.from(printer));
```
reader도 변수 추출을 해봅시다.

2024-02-23 02:53 UTC, summerlunaa commented on src/main/java/Controller/LadderGame.java
> +    }
getXXX라는 네이밍은 주로 필드 값을 그대로 가져올 때 많이 사용하고 있어요. 여기에서는 player들을 입력받아 가져오고 있으니 이 역할에 맞는 이름으로 바꿔보는 건 어떨까요?

2024-02-23 02:53 UTC, summerlunaa commented on src/main/java/domain/BooleanGenerator.java
> +public interface BooleanGenerator {
단순 true/false 생성기라면 인터페이스로 추상화해줄 필요까지 있을까요?
사다리를 만드는 방식 자체를 추상화하는 것이 더 적절해보여요. 그럼 인터페이스명도 LadderBridgeGenerator와 같이 변경될 것이고, Generator의 역할과 책임도 단순 boolean 값 생성이 아닌 Bridge를 만들어 주는 역할로 더 풍부해질 것 같습니다.

2024-02-23 02:53 UTC, summerlunaa commented on src/main/java/domain/Height.java
> +    }
`isBiggerThan` 메서드 입장에서 넘어오는 파라미터가 buildHeight인지 알 필요가 있을까요? 변수명에 불필요한 맥락이 담겨있지는 않은지 고민해봅시다.
**다른 곳에도 비슷한 경우가 있으니 전체적으로 점검 부탁드립니다.**

2024-02-23 02:53 UTC, summerlunaa commented on src/main/java/domain/Ladder.java
> +    }
메서드에도 일반적인 순서가 있는데요, 주로 아래와 같은 순서로 작성합니다!

1. 생성자
2. 정적 팩토리 메서드
3. 메서드(접근자 기준이 아닌 기능 및 역할별로 분류하여 작성)
4. getter, setter
5. 기본 메서드(toString, equals 등)

**다른 곳에도 비슷한 경우가 있으니 전체적으로 점검 부탁드립니다.**

2024-02-23 02:53 UTC, summerlunaa commented on src/main/java/domain/Ladder.java
> +    public int hashCode() {
equals와 hashCode는 왜 오버라이딩 하셨나요? 오버라이딩한 곳도 있고 아닌 곳도 있던데 기준이 궁금합니다.

2024-02-23 02:53 UTC, summerlunaa commented on src/main/java/domain/Line.java
> +    }
Ladder와 Line 클래스를 보니 마땅한 역할이 없어 보이는데 커비는 어떻게 생각하나요?
이렇게 된 이유가 무엇일까요? 클래스를 과하게 분리한 것은 아닌지 고민해봅시다. Ladder와 Line에 있어야할 역할과 책임이 어디로 사라졌나요? 어떤 클래스가 들고 있나요?

2024-02-23 02:53 UTC, summerlunaa commented on src/main/java/domain/PlayerCount.java
> +    }
정적 팩토리 메서드는 어떤 경우에 사용하고 있나요?
`from`의 경우 일반 생성자와 중복되네요. `fromPlayers`도 필요한가요? 🤔
더 나아가서 굳이 PlayerCount가 필요한 클래스인지 고민해봅시다. Players로도 충분하지 않을까요?

2024-02-23 02:53 UTC, summerlunaa commented on src/main/java/dto/HeightRequest.java
> +    }
DTO를 사용하셨군요!

- DTO는 왜 사용하셨나요? DTO의 역할이 무엇인가요?
- DTO를 사용했을 때의 단점은 무엇일까요?

DTO를 생성하고 관리하는 비용까지 고려하여 이번 미션에서도 DTO가 꼭 필요한지 생각해보면 좋을 것 같습니다.

2024-02-23 02:53 UTC, summerlunaa commented on src/main/java/domain/Height.java
> +    }
높이를 값객체로 만드셨네요 👍

2024-02-23 02:53 UTC, summerlunaa commented on src/main/java/domain/Players.java
> +    }
불변 리스트로 반환 👍

2024-02-23 02:53 UTC, summerlunaa commented on src/main/java/view/printer/Printer.java
> +public class Printer {
마지막에 입력기와 출력기를 분리하셨군요! 이 부분도 어떤점에서 분리하게 되었는지 궁금합니다 ㅎㅎ

2024-02-23 02:53 UTC, summerlunaa commented on src/test/java/CarpenterTest.java
> +                .hasSize(4);
이미 getter가 있는데 extracting을 쓰시는 이유가 있나요?
extracting의 경우 리플렉션으로 필드에 접근합니다. 때문에 필드명을 잘못 넣더라고 컴파일 오류가 발생하지 않습니다. 가능한 이미 존재하는 getter를 잘 활용해보면 어떨까요?

2024-02-23 02:53 UTC, summerlunaa commented on src/test/java/HeightTest.java
> +    @DisplayName("다리 높이에 0을 입력하면 예외가 발생한다.")
0인 경우 예외인가요 0 이하인 경우 예외인가요? 조건을 명확히 적어주면 더 좋을 것 같아요.
경계값에 대한 테스트는 좋습니다 👍

2024-02-23 02:53 UTC, summerlunaa commented on src/test/java/WoodWorkMachineTest.java
> +    private static class FalseBooleanGenerator implements BooleanGenerator {
FalseBooleanGenerator는 여기, TrueGenerator는 별도 클래스로 있네요 👀

2024-02-23 02:53 UTC, summerlunaa commented on src/main/java/domain/Point.java
> +    private final Step step;
이미 Step이 있는데 Step과 비교해서 Point는 어떤 역할과 책임을 가진 객체인가요? 필요한가요?

2024-02-23 02:53 UTC, summerlunaa commented on README.md
질문 주신 부분들은 여기서 답변할게요!

>1. 일반 메서드의 파라미터와 로컬 변수도 final을 붙이는 것의 장점이 더 클까?

이론적으로는 변경이 불필요한 모든 곳에 final 키워드를 붙이는 것이 좋겠죠~ 커비가 생각한 기준도 충분히 이해 되구요!
다만 `final 키워드를 쓰긴 쓰는데 특정한 곳에서만 쓴다`라는 원칙이 꾸준히 지켜질 수 있을지는 의문입니다.
코드를 작성할 때 가독성, 변수명 등을 고려하는 이유가 이 코드를 함께 읽고 쓰는 다른 개발자를 위함인데, final 키워드를 어디에서는 쓰고 어디에서는 쓰지 않는다는 원칙을 본인 스스로도, 함께 개발하는 모든 개발자들도 꾸준히 지킬 수 있을까요? 
모든 곳에 final 키워드를 붙이는 것도 굉장히 어려운 일인데 커비가 생각하는 기준을 따르기는 더더욱 어려워보입니다.

>2. 재입력 처리의 책임이 컨트롤러가 담당해도 괜찮을지

컨트롤러가 어떤 책임을 가져야한다고 생각하나요? 별도의 클래스로 책임을 분리한다면 어떤 장단점이 있을까요?

> 3. 만들었던 테스트 메서드들이 private이 되어 지워지게 되는 상황

TTD 사이클은 아래와 같습니다.
- 실패하는 테스트를 구현한다.
- 테스트가 성공하도록 프로덕션 코드를 구현한다.
- 프로덕션 코드와 테스트 코드를 리팩토링한다.

이런 점에서 보면 기존에 만들었던 테스트 코드가 이후에 구현한 프로덕션 코드에 의해 수정되거나 삭제되는 것은 당연한 현상으로 보입니다~

> 4. 어쩔 수 없이 프로덕션 코드 먼저 작성

일반적인 상황에서는 TDD가 어렵다면 프로덕션 코드 먼저 작성해도 큰 문제 없다고 생각합니다. 다만 지금은 TDD를 익히고 공부하는 과정이니 극단적으로 TDD를 적용해 보는 것도 방법이라고 생각해요 :) 
예시로 들어주신 상황이었다면 인터페이스와 테스트용 구현체를 먼저 만들고 테스트를 작성할 수도 있었을 것 같네요!

> 5. 테스트를 위한 오버 엔지니어링일까?

맥락에 따라 달라질 듯 합니다. 
테스트가 반드시 필요해 보이지 않다면 오버엔지니어링으로 판단하고 인터페이스를 구현하지 않을 수도 있구요,
다른 형식의 Generator가 추가될 일이 없어 보여도 이 로직은 너무 중요해서 테스트를 반드시 해야한다면 쉬운 테스트를 위해 인터페이스를 추가할 수도 있겠죠~ 

> 6. RandomStepGenerator를 분리해줘야할까?

우리는 정확한 미래를 알 수가 없습니다. 현재는 요구사항이 명시되어 있지만 현실에서는 언제 어떤 요구사항이 주어질지 정확히 예상하기는 어렵죠.
모든 정책을 하나하나 분리하고 추상화한다면 어떤 새로운 요구사항이 들어와도 쉽게 수정할 수는 있겠으나, 코드가 복잡해지고 그만큼 유지보수도 어려워집니다. 반대로 확장성을 전혀 고려하지 않는다면 새로운 요구사항이 들어올 때마다 많은 클래스에 영향을 주겠죠.
이 사이의 적절한 협의점을 찾는 게 중요하다고 생각합니다. 이번 커비의 코드는 어떤 것 같나요?
클래스 분리에 대해 위에서도 리뷰 남겼는데요, 한번 고민해보시고 리뷰 반영 부탁드리겠습니다 ㅎㅎ

2024-02-23 04:21 UTC, skylar1220 commented on src/main/java/domain/Line.java
> +    }
이렇게 된 이유는 Ladder와 Line의 각 생성 책임이 Carpenter와 WoodworkMachine에게 분리되었기 때문인데요!

## Line이 스스로 생성하는 경우
```java
public class Line2 {
    private final List<Point> points;

    public Line2(final List<Point> points) {
        this.points = points;
    }

    public static Line of(PlayerCount playerCount, RandomBooleanGenerator randomBooleanGenerator) {
        return new Line(makeLine(playerCount, randomBooleanGenerator));
    }

    public static List<Point> makeLine(PlayerCount playerCount, RandomBooleanGenerator randomBooleanGenerator) {
        List<Point> points = new ArrayList<>();

        for (int index = 0; isInCountRange(playerCount, index); index++) {
            points.add(makePoint(index, points, randomBooleanGenerator));
        }
        return points;
    }

    private static Point makePoint(int index, List<Point> points, RandomBooleanGenerator randomBooleanGenerator) {
        if (hasBeforeStep(index, points) || isLastPoint(index)) {
            return new Point(Step.EMPTY);
        }
        Step step = Step.from(randomBooleanGenerator.generate());
        return new Point(step);
    }

}
```
### 장점
- 클래스가 분리되지 않아서 클래스의 수가 줄어든다. 프로그램이 간단해짐.

### 단점
- 클래스를 분리했다면 Line을 만들 때 필요한 변수들을 파라미터로 넘겨줘야해서 파라미터 갯수가 늘어남
- makeLine()과 같은 중요하고 복잡한 로직이 부생성자 부분에서 일어나게 된다.

## Line의 생성을 WoodworkMachine에게 분리하는 경우
```java
public class WoodWorkMachine {
    private final BooleanGenerator randomBooleanGenerator;
    private final PlayerCount playerCount;

    public WoodWorkMachine(final PlayerCount playerCount, final BooleanGenerator randomBooleanGenerator) {
        this.playerCount = playerCount;
        this.randomBooleanGenerator = randomBooleanGenerator;
    }

    public Line makeLine() {
        List<Point> points = new ArrayList<>();

        int index = 0;
        while (isInCountRange(playerCount, points.size())) {
            points.add(makePoint(index, points));
            index++;
        }

        return new Line(points);
    }
}
```
### 장점
- Line의 생성 책임을 분리해줄 수 있음
- Line을 만들 때 필요한 객체들을 필드로 등록하여 사용함으로써, 메서드가 주고받는 파라미터가 줄어든다.

### 단점
- 과도한 책임 분리
- 클래스 수가 늘어난다.

이런 각 장,단점이 있다고 생각하는데 이번에는 최대한 책임을 분리해보는 방식으로 진행해보고자 Line의 생성을 WoodworkMachine에게 분리하는 방법을 사용했던 것 같습니다! 파랑이 생각하시기엔 어떤 부분에서 생성 책임을 분리하는 것의 단점이 더 크다고 느끼시는지 궁금합니다! 혹시 저희가 생각한 장,단점 이외에 고려해야하는 부분이 더 있을까요?

2024-02-23 04:38 UTC, skylar1220 commented on src/main/java/Controller/LadderGame.java
> +    }
그렇네요! readPlayers로 바꿔보겠습니다!

2024-02-23 04:50 UTC, skylar1220 commented on src/main/java/domain/Point.java
> +    private final Step step;
너무 분절해서 생각했네요..! Step enum만으로 대체가 가능할 것 같습니다!

2024-02-23 06:41 UTC, skylar1220 commented on src/main/java/Application.java
> +        LadderGame ladderGame = new LadderGame(InputView.of(new Reader(), printer), OutputView.from(printer));
`new Reader()`가 한번만 쓰이기 때문에 인라인으로 해주었는데 혹시 가독성이 많이 떨어진다고 느껴질까요?

2024-02-23 06:49 UTC, skylar1220 commented on src/main/java/domain/BooleanGenerator.java
> +public interface BooleanGenerator {
말씀하신대로 StepGenerator로 바꿔주면 역할이 풍부해지고, 또 랜덤 구현 방식이 바뀌어도 이 클래스 내에서만 수정을 해주면 되겠다는 생각이 드네요!!

```java
public class RandomStepGenerator implements StepGenerator {
    @Override
    public Step generate() {
        Random random = new Random();
        return Step.from(random.nextBoolean());
    }
}
```

2024-02-23 07:07 UTC, skylar1220 commented on src/main/java/domain/Height.java
> +    }
`변수명에 불필요한 맥락이 담기지 않게하는 것` 놓치고 있던 부분이네요! 전반적으로 수정하겠습니다!

2024-02-23 07:48 UTC, skylar1220 commented on src/main/java/domain/Ladder.java
> +    }
저는 아래와 같은 순서가 일반적인 순서라고 생각했는데 달랐군요!

> 1. 생성자
> 2. 정적 팩토리 메서드
> 3. 메서드: **public 메서드가 가장 위**, 이후부터는 연관되어 호출된 메서드를 가깝게 배치
> 4. 기본 메서드(toString, equals 등)
> 5. getter, setter

파랑이 제시한 순서를 보고 이 '일반적인' 순서라는 것도 관례이기 때문이 아닌 하나하나의 이유가 있을 것이라는 생각이 들어서 
파랑이 제시한 순서로 이유를 고민 해보았는데요.

**1,2번**은 객체 생성을 위한 초기화 과정이 포함되어있으므로 가장 상단에 있어야겠지라는 생각에 공감이 됩니다!
**5번** 기본 메서드는 굳이 내부를 보지 않아도 기대하는 역할이 명확하기에 중요도가 떨어져 가장 아래에 있고,
**4번** getter, setter의 경우도 객체의 필드를 반환할 것이라는 기대 역할이 비교적 명확하기에 가장 아래보다는 하나 위에 있다는 생각이 듭니다!

그 중, 특히 **3번**을 왜 다르게 이해하고 있었을까를 가장 고민해보았는데요.

코드를 읽을 때 public 메서드는 외부에서 호출되는 메서드이기에 외부에서 해당 메서드를 찾기 위해 이 클래스를 열 것이고 찾기 쉽게하기 위해서 상단에 몰아넣어야 찾기 쉽겠다는 생각을 했던 것 같아요.

하지만 다시 생각해보니, 현대에 IDE로 코드 혹은 문서를 확인할 때 클래스를 직접 열어서 메서드를 찾기보다는, cmd+b등의 방식으로 특정 메서드를 확인하고 그 메서드에서 호출하는 연관된 다른 메서드들이 바로 아래에 배치되어 쭉 읽는 것이 더 읽기 편하다는 생각이 들어 기능, 역할별로 분류하는 것이 더 효율적이겠다고 생각이 바뀌게 되었습니다.

제가 이해한 방향에서 잘못 추측한 부분이 있다면 알려주시면 감사하겠습니다😀

2024-02-23 07:51 UTC, skylar1220 commented on src/main/java/domain/Ladder.java
> +    public int hashCode() {
테스트에서 isEqualTo로 확인하는 경우 해당되는 객체들에 오버라이딩하자! 가 기준이었는데요.
Ladder는 테스트 수정 과정에서 equals 오버라이딩이 필요없어졌는데 제거하지 않았네요😅 수정하겠습니다!

2024-02-23 10:35 UTC, skylar1220 commented on src/main/java/view/printer/Printer.java
> +public class Printer {
마지막에 분리한 것도 예리하게 보셨군요..ㅎㅎ

1. 리팩토링 과정에서 조금 더 책임 분리를 할 수 있지 않을까 생각했습니다.
예를 들어 InputView에서 System.out.printLine() 과 같은 출력을 하는 것을 출력에 대한 책임으로 보아서 Printer로 출력 책임을 분리해준 것이죠!

2. 또한 현재는 입력, 출력 형식이 지정되어있지 않아서 Scanner 등으로 선택해서 쓰고 있지만, 만약 Scanner가 아닌 BufferReader 등으로 입력 방식이 바뀌었을 때 한 곳에서 유지보수가 가능하다는 장점도 고려를 했습니다!

2024-02-23 10:38 UTC, skylar1220 commented on src/test/java/CarpenterTest.java
> +                .hasSize(4);
테스트만을 위해 getter를 생성하는 걸 최대한 지양하고 싶어서 대체할 수 있는 방법으로 사용해보았는데 
컴파일 오류를 잡지 못한다는 단점을 고려했을 때 어떤 쪽이 더 합리적일지 고민이 듭니다..!

2024-02-23 10:40 UTC, skylar1220 commented on src/test/java/HeightTest.java
> +    @DisplayName("다리 높이에 0을 입력하면 예외가 발생한다.")
DisplayName의 명확한 의미 전달에 좀 더 신경써야겠네요!

2024-02-23 10:42 UTC, hyeonji1220 commented on src/test/java/WoodWorkMachineTest.java
> +    private static class FalseBooleanGenerator implements BooleanGenerator {
FalseBooleanGenerator는 해당 테스트 클래스에서만 사용되어 이너클래스로 구현했고
TrueGenerator는 다른 테스트 클래스에서도 재사용되어 별도의 클래스로 분리해주었습니다!

2024-02-23 10:46 UTC, skylar1220 commented on src/main/java/dto/HeightRequest.java
> +    }
> DTO는 왜 사용하셨나요? DTO의 역할이 무엇인가요?

> DTO를 사용했을 때의 단점은 무엇일까요?

2024-02-23 11:23 UTC, skylar1220 commented on src/main/java/domain/PlayerCount.java
> +    }
> 정적 팩토리 메서드는 어떤 경우에 사용하고 있나요?

저는 정적 팩토리 메서드를 아래 두가지 경우에 사용하고 있는데요!
1. 객체를 생성하는 인자의 경우가 여러개일 경우 각 경우의 이름붙여 객체 생성을 해주기 위해
2. 생성자 초기화 전 변환 등의 로직을 거쳐야하는 경우 생성자를 가볍게 유지하기 위해

> from의 경우 일반 생성자와 중복되네요.

사실 from은 테스트를 위한 부생성자로, 테스트를 위한 코드 변경이라는 생각이 들었지만 일단 작성한 코드가 맞습니다😅
테스트만을 위한 코드는 유지보수의 문제도 있고, 프로덕션 코드 안에 프로그램 실제 실행과 관련 없는 코드가 존재한다는 점에서 삭제하는 것이 적절해보이네요!

> fromPlayers도 필요한가요? 🤔

players.getCount() 로직이 수행되어야하기 때문에 fromPlayers 부생성자를 생성해 그 안에서 players.getCount() 로직을 해줌으로써 생성자를 가볍게 유지하고자 했습니다!

> 더 나아가서 굳이 PlayerCount가 필요한 클래스인지 고민해봅시다. Players로도 충분하지 않을까요?

LineMaker에서 플레이어 수만큼 다리를 만드는 용도로 PlayerCount를 사용하고자 했는데요!
다리를 만드는데 Players 전체 정보가 필요하지는 않고, 참가자수만 알면 될 것 같다고 생각하여 생성하게 되었습니다.
int로 처리할 수도 있겠지만 원시값 포장을 하고자한 부분도 있습니다!

```java
    public LineMaker(final PlayerCount playerCount, final StepGenerator randomStepGenerator) {
        this.playerCount = playerCount;
        this.randomStepGenerator = randomStepGenerator;
    }
```

2024-02-23 13:43 UTC, hyeonji1220 commented
꼼꼼한 리뷰 감사합니다 파랑! 
고민을 하다가 애매하게 결론을 내린 부분들에 역시! 질문을 해주셔서 덕분에 다시 한 번 생각할 수 있었던 것 같아요😀
코멘트 남겨주신 부분에 저의 생각을 적어보았습니다~ 혹시 제 생각에서 놓친 점이 있으면 무람없이 알려주세요😉

2024-02-23 14:45 UTC, summerlunaa commented on src/main/java/Application.java
> +        LadderGame ladderGame = new LadderGame(InputView.of(new Reader(), printer), OutputView.from(printer));
아하 printer는 두 번 사용되는군요! 저라면 변수 추출을 해줄 것 같지만 취향의 영역으로 보이네요. 지금도 괜찮을 것 같습니다!

2024-02-23 14:49 UTC, summerlunaa commented on src/main/java/domain/Ladder.java
> +    }
너무 잘 정리해주셨네요 👍 
>cmd+b등의 방식으로 특정 메서드를 확인하기 때문에 상단에 public 메서드를 몰아넣지 않아도 되고, 또한 그 메서드에서 호출하는 연관된 다른 메서드들이 바로 아래에 배치되어 쭉 읽는 것이 더 읽기 편하다는 생각이 들어 기능, 역할별로 분류하는 것이 더 효율적이겠다

저도 이렇게 적어주신 의견에 동의합니다~

2024-02-23 15:07 UTC, summerlunaa commented on src/main/java/domain/Ladder.java
> +    public int hashCode() {
equals와 hashCode 오버라이딩이 필요한 경우를 다시 생각해보면 좋을 것 같아요.

https://mangkyu.tistory.com/101

equals와 hashCode는 동등성을 보장하기 위해 오버라이딩합니다. 
테스트를 고려하지 않고 생각해봅시다. 테스트는 equals와 hashCode를 오버라이딩하지 않고도 충분히 진행할 수 있어요.
equals와 hashCode를 오버라이딩한 객체들이 모두 '동등성'이 필요한가요?

2024-02-23 15:29 UTC, summerlunaa commented on src/main/java/domain/Line.java
> +    }
생성의 책임을 어떤 객체에 주느냐에 따라 발생하는 장단점을 잘 정리해주셨네요 👍 
생성 로직이 복잡하고 크다면 충분히 분리해줄 수도 있다고 생각해요. 다만 그만큼 코드를 하나의 클래스에서 한 번에 파악하기 어렵겠죠. 이 클래스가 어떻게 생성되는 거지? 하고 팩토리 클래스를 찾아가야 하구요.

WoodworkMachine에 생성의 책임을 분리한 코드도 나쁘다고 생각하진 않습니다. 하지만 현재 상황에서는 약간 과하다는 생각이 들어서 말씀드려봤어요 :)

2024-02-23 15:37 UTC, summerlunaa commented on src/main/java/dto/HeightRequest.java
> +    }
개인적으로 지금 정도 사이즈의 시스템에서 DTO를 도입했을 때 단점이 더 크게 느껴지네요. 저는 삭제하시길 권해드립니다~
현재 view에서 다른 비즈니스 로직을 추가하지 않고 getter만 사용한다면 값이 변경될 일도 없어보이고 View에서 객체를 생성하는 게 어색하다면 컨트롤러에서도 충분히 만들어줄 수 있을 것 같습니다.

2024-02-23 15:41 UTC, summerlunaa commented on src/main/java/view/printer/Printer.java
> +public class Printer {
[YAGNI 원칙](https://ko.wikipedia.org/wiki/YAGNI)을 아시나요?

`실제로 필요할 때 무조건 구현하되, 그저 필요할 것이라고 예상할 때에는 절대 구현하지 말라`

저는 이 말이 좋더라구요 ㅎ 추후 확장성 있게 리팩토링하는 것이 크게 어렵지 않다면, 객체 분리든 추상화든 DTO 사용이든 필요할 때 진행하는 편입니다. 이것저것 다 확장성을 고려하다 보면 오히려 가독성이 심각하게 떨어지고 유지보수도 어렵더라구요. 시간이 한 달만 지나면 제가 짠 코드도 읽기 어려운데요, 다른사람이 이해하기는 훨씬 더 어렵거든요.

2024-02-23 15:42 UTC, summerlunaa commented on src/test/java/CarpenterTest.java
> +                .hasSize(4);
이미 getter가 있지 않나요? 🤔

2024-02-23 15:43 UTC, summerlunaa commented on src/test/java/WoodWorkMachineTest.java
> +    private static class FalseBooleanGenerator implements BooleanGenerator {
한 군데 모여있는 게 클래스를 찾기 더 쉬울 것 같아요 :)

2024-02-23 15:58 UTC, summerlunaa requested changes
커비! 대부분의 리뷰들을 잘 반영해주셨네요 👏 

다만 추가적으로 의견을 드린 부분들이 있어 한번 더 고민해보시라고 RC 드립니다.

남겨주신 코멘트에도 다시 리뷰 달아드렸으니 확인해주세요. 조금만 더 파이팅!

2024-02-23 15:58 UTC, summerlunaa commented on src/main/java/domain/Ladder.java
> +    }
StepGenerator로 추상화한 김에 어떤 StepGenerator를 사용할지 받는 것도 좋겠네요~

2024-02-23 15:58 UTC, summerlunaa commented on src/main/java/domain/Line.java
> +    }
커비는 어떤 기준으로 메서드를 분리하나요? 메서드가 너무 많아서 계속 다음 메서드를 찾아가야 하네요.. 🥹
isInCountRange는 `playerCount.isBiggerThan(buildCount)`로 사용해도 충분히 이해가능할 것 같아요. 메서드명을 적절히 잘 지어두셔서요 :)

2024-02-23 15:58 UTC, summerlunaa commented on src/test/java/PlayersTest.java
> +import static org.assertj.core.api.Assertions.assertThatThrownBy;
사용하지 않는 임포트네요 👀

2024-02-23 16:03 UTC, summerlunaa commented on src/main/java/domain/BooleanGenerator.java
> +public interface BooleanGenerator {
바꿔주신 이름이 더 잘어울리긴 하지만 단순 네이밍 변경보다는 해당 클래스가 가진 역할과 책임을 조금 더 풍부하게 바꿔보면 어떨까~ 하는 의견이었습니다.

ex. 단순 true/false 랜덤 생성기에서 요구사항에 따라 Line(List<Step>)을 생성하는 객체로 수정 (단순 예시입니다)

2024-02-25 01:41 UTC, skylar1220 commented on src/main/java/dto/HeightRequest.java
> +    }
사실 반반이었던 것 같은데 파랑의 이야기를 듣고 프로그램 사이즈를 좀 더 우선 고려사항에 둘 필요가 있다는 생각이 드네요🤔 반영해보겠습니다!

2024-02-25 03:23 UTC, skylar1220 commented on src/main/java/domain/Line.java
> +    }
> 생성 로직이 복잡하고 크다면 충분히 분리해줄 수도 있다고 생각해요. 

생성 로직이 복잡한가?를 초점으로 다시 살펴보니 '그정도는 아니다'라고 느껴지네요😅

> 다만 그만큼 코드를 하나의 클래스에서 한 번에 파악하기 어렵겠죠. 이 클래스가 어떻게 생성되는 거지? 하고 팩토리 클래스를 찾아가야 하구요.

오히려 한번에 파악하기 어려워 찾아가는 리소스가 더 크다는 지점에 동의합니다! 반영해보겠습니다!

2024-02-25 03:29 UTC, skylar1220 commented on src/main/java/view/printer/Printer.java
> +public class Printer {
코드가 해당되는 부분이 많다고 느껴지네요😂
객체, 역할 분리에 초점을 맞추다보니 가독성과 유지보수를 우선 순위에서 내린 것 같다는 생각이 들어 종합적으로 고려해보아야겠습니다!

2024-02-25 04:41 UTC, skylar1220 commented on src/test/java/CarpenterTest.java
> +                .hasSize(4);
맞네요😅😅

2024-02-25 04:41 UTC, skylar1220 commented on src/test/java/WoodWorkMachineTest.java
> +    private static class FalseBooleanGenerator implements BooleanGenerator {
아하 클래스를 찾기 더 쉽다는 점도 고려대상이 될 수 있겠군요😀

2024-02-25 05:01 UTC, skylar1220 commented
또또 질문드리네요 파랑ㅎㅎ 생각을 해볼 수 있는 지점을 계속해서 알려주셔서 질문이 막막 생겨납니다😂

## 데이터 이동 방식 고민
DTO의 사용에 대해 고민하다 나머지 방식인 객체로 이동하는 것, 원시값으로 이동하는 것 까지해서 데이터 이동의  3가지 방식에 대해 제가 정리한 장,단점에서 근본적인 의문이 들었는데요!

### 1. 데이터가 객체로 전달되는게 원시값으로 전달되는 것보다 변경위험성이 낮다?

> inputView에서 컨트롤러 - Model 까지 입력값을 원시값으로 전송한다면 값의 변경이 쉬워 데이터의 안전성이 떨어지고,

는 이런 상황을 고려한 것이었는데요.

```java
public class LadderGame {
    public void run() {
        int height = inputView.inputHeight();
        height++;
        Ladder ladder = Ladder.create(height);
		}
}
```

하지만 그렇다면, `객체로 전달해주더라도 아래와 같이 값의 변경이 가능한 것 아닌가?` 하는 의문이 들었습니다.

```java
public class LadderGame {
    public void run() {
        Height height = inputView.inputHeight();
        height = new Height(3);
        Ladder ladder = Ladder.create(height);
		}
}
```

물론 억지스러운 상황이지만 발생할 수 있는데도, 원시값보다는 데이터의 안전성이 있다고 하는 이유에 대해서 고민을 해본 결론은,

int height로 받는 경우는 height + 1을 하지 말아야한다는 의도가 전달되지 않지만,
객체로 받게되면 이 데이터에 대해 new Height(3)과 같이 데이터 변경을 하지 않아야하는 값이라는 ‘의도’를 전달하는 것이기도 하기때문이다. 라고 내렸습니다!

혹시 제가 고려하지 못한 `데이터가 객체로 전달되는게 원시값으로 전달되는 것보다 변경위험성이 낮다`를 뒷받침하는 이유가 있을지 궁금합니다!

### 추가된 생각

이렇게 컨트롤러의 로컬 변수들에 final을 붙여주면 원시값도 height + 1을 하지 말아야한다는 의도가 전달되니 원시값 전달도 괜찮을 것 같다는 생각이 드네요!

```jsx
public class LadderGame {
    public void run() {
        final int height = inputView.inputHeight();
				// height++;
			  final Ladder ladder = Ladder.create(height);
		}
}
```

### 2. DTO, view에서는 getter 사용이 허용된다?

> 현재 view에서 다른 비즈니스 로직을 추가하지 않고 getter만 사용한다면 값이 변경될 일도 없어보이고
> 

이부분도 평소에 궁금했던 점인데요!

도메인 클래스들과 다르게 DTO와 view에서 getter 사용은 출력을 위한 값 등 순수 값 프로퍼티를 가져오기 위해서 허용하는 것이라고 알고있습니다!

하지만 `여전히 view와 DTO역시 getter를 이용해서 로직을 수행하는 위험성이 존재하는 것 아닌가?`하는 의문이 들었습니다!
이에 대해서는 ‘DTO와 view에서는 비즈니스 로직을 처리하지 않기로 했어!’하는 암묵적인 약속이 있기때문에 이러한 위험성에 대해 감안하고 넘어가는 걸까요?

2024-02-25 05:28 UTC, skylar1220 commented on src/main/java/domain/Line.java
> +    }
`나는 어떤 기준으로 메서드를 분리할까?` 생각해보니

신문처럼 코드를 쭉 읽을 때, 마주치는 코드가 어떤 상황을 이야기하는지 이해가 한번에 잘 가지 않는다고 느끼면 분리를 하는 것 같습니다.
```java
private static Step createStep(List<Step> steps, StepGenerator randomStepGenerator, PlayerCount playerCount) {
    if (hasBeforeStep(steps) || playerCount.isSameWith(steps.size() + 1)) {
        return Step.EMPTY;
    }
    return randomStepGenerator.generate();
}

```

`playerCount.isSameWith(steps.size() + 1` 부분을 `isLastStep()`로 분리하는 것처럼 말이죠.

하지만 이 기준에 의해서 너무 과도하게 분리한 것 같다는 생각이 해당 부분을 보고 듭니다!
그동안은 메서드 분리의 장점에 대해서만 생각했는데 다음 메서드를 계속 찾아가야한다는, 즉 가독성을 위한 것이었지만 가독성을 오히려 해칠 수도 있다는 생각이 드네요.

코드로 충분히 컨텍스트가 제공되는 부분에 메서드 분리를 과도하게 하지 않도록 경계해보아야겠습니다!

2024-02-25 06:09 UTC, skylar1220 commented on src/main/java/domain/Ladder.java
> +    public int hashCode() {
다시 생각해보니 테스트 값 비교에 편의상 필요하다면 equals와 hashCode를 오버라이딩한 경우가 자주 있었던 것 같네요. 그리고 그렇게 되면 동등성이 필요하지 않은 객체들이 동등하다고 판단이 되어 오류가 발생할 수도 있겠군요! equals와 hashCode를 남발하지 않는지 경계 역시 필요하겠습니다...!

현재 프로그램에서는 중복 참여자 검증을 위해 Player만 equals와 hashCode가 필요하겠네요!

2024-02-25 10:08 UTC, skylar1220 commented on src/main/java/domain/Ladder.java
> +    }
사실 이 StepGenerator를 어느 위치에서 생성해서 주입해주어야할지에 대해서도 고민이 많았는데요.

### 1. 사용하는 클래스보다 하나 상위의 클래스에서 생성, 주입
처음에는 Line에서 randomStepGenerator를 사용하는 경우,
컨트롤러가 아닌 Ladder의 createLines() 내에서 randomStepGenerator를 생성하고 Line으로 생성자 주입을 해주었는데요.
그 이유는 아래와 같았습니다.
1. 컨트롤러까지 randomGenerator를 알 필요가 있을까?
2. 컨트롤러에서 생성해 주입하면 Ladder에 생성자 주입을 하게되니 Ladder도 randomStepGenerator를 필드로 가져야하는데 Ladder가 randomStepGenerator를 필드로 가지고 있을 필요까지 있을까?


### 2. 컨트롤러에서 생성, 주입
하지만 만약 randomStepGenerator가 다른 구현체로 대체된다면? 
randomStepGenerator 생성 위치를 찾으려고 여기 저기 살펴야하는, 즉 찾기가 어렵겠다는 생각이 들었습니다.

그렇다면 찾기쉬우려면? `컨트롤러를 설정 파일처럼 생각하고 컨트롤러에 넣어주면 변경시에 찾기 쉽지 않을까?` 하는 생각이 들어 컨트롤러에서 생성해 주입해주는 것이 좋을 수 있겠다는 생각으로 바뀌게되었습니다!

### 고민되었던 점
하지만 컨트롤러에서 생성해서 넣어주면 거치게되는 Ladder…등의 클래스가 randomStepGenerator를 다 필드로 갖고있어야 하는 것이 걸렸습니다. 결론적으로는, 현재는 이중 배열 형식이라 그렇지 이렇게 일급컬렉션을 일급컬렉션이 계속해서 감싸는 형태가 아니라면 해당 부분도 크게 발생하지 않지 않을까? 하는 생각으로 감수할만하다고 결론을 내렸습니다!

혹시 저의 생각의 흐름에서 더 고려해야할 점이 있을지 궁금합니다!

2024-02-25 12:20 UTC, summerlunaa commented on src/main/java/domain/Ladder.java
> +    }
컨트롤러에서 StepGenerator를 생성해 주입했을 때 드는 의문점을 잘 정리해주셨군요! 대체 어디서부터 생성해주어야 하나.. 어려운 문제인 것 같습니다 😅
정리해주신 것처럼 두 방법의 장단점이 있는데요 이번 케이스에서는 사다리가 line들의 생성을 총괄한다는 점, 하나의 사다리에서는 모든 line들이 같은 정책을 가져야 한다는 점을 생각해서 Ladder를 생성할 때 StepGenerator를 받아도 어색하지 않다 생각했습니다 :)

2024-02-25 12:47 UTC, summerlunaa approved these changes
커비 리뷰 반영하신 부분들 확인했습니다 👍  

각 리뷰마다 고민을 많이 하신 흔적들이 보이네요. 정말 수고하셨습니다~

1단계는 여기서 머지하겠습니다. 🙇‍♀️

2024-02-25 12:47 UTC, summerlunaa commented on README.md
> 1. 데이터가 객체로 전달되는게 원시값으로 전달되는 것보다 변경위험성이 낮다?

말씀해주신 것처럼 쉽게 값을 변경해버리는 케이스를 막기 위해 계속 불변을 보장하려고 노력하는 거죠.
그 불변을 보장하는 방식이 final을 붙이는 게 될 수도 있고 객체로 한번 포장하는 게 될 수도 있는 거구요. 잘 정리해주셨습니다 👍 

> 2. DTO, view에서는 getter 사용이 허용된다?

DTO든 도메인이든 반드시 필요한 곳에서는 getter를 사용할 수 밖에 없습니다. 
view에서는 getter 사용 없이 데이터를 출력할 수 없으니 사용하는 것이고, DTO도 출력, 혹은 데이터 전달이 목적이니 getter를 사용할 수 밖에 없는 거죠. 
`도메인 클래스들과 다르게 DTO와 view에서 getter 사용은 출력을 위한 값 등 순수 값 프로퍼티를 가져오기 위해서 허용`한다는 게 어떤 의미인지 잘 모르겠습니다. 비즈니스 로직 처리를 처리하는 위험성?.. 과는 관련이 없어 보이네요 :-)
DTO에 관해서는 나중에, DTO가 정말 필요할 때 더 고민해보시는 걸 추천드립니다. 지금은 조금 이른 것 같네요 🤔

2024-02-25 12:48 UTC, merged