[1단계 - 사다리 생성] 잉크 미션 제출합니다.
woowacourse/java-ladder pull request #272
Opened 2024-02-22 06:50 UTC by yechop

안녕하세요 잉크입니다.

이번  페어 프로그래밍은 [리비](https://github.com/Libienz)와 진행했습니다.
저번 미션까지는 구현만 집중하며 진행했는데 이번 미션은 리비에게 의존성 주입, 매핑, 정적팩토리메서드 등등 많이 배우며 진행해서 제 능력을 훨씬 웃도는 결과물이 되었습니다.
제가 잘 학습하며 프로그래밍 했는지 검증하기 위해 다양한 질문 주시면 답해보고 싶습니다.

감사합니다!

2024-02-22 11:34 UTC, summerlunaa requested changes
잉크 안녕하세요~ 리뷰어 파랑입니다 🐳

이제 두 번째 미션이네요!! TDD 방식으로 잘 진행해주셨습니다 👍 
리뷰 남겼으니 확인부탁드립니다.

수고하셨습니다~ 👏

2024-02-22 11:34 UTC, summerlunaa commented on src/main/java/domain/Height.java
> +    }
파라미터로는 int를 받고 있는데 필드의 타입은 박싱타입이네요~ 혼용해서 사용한 이유가 있나요? 이렇게 사용하면 어떤 단점이 있을까요?

2024-02-22 11:34 UTC, summerlunaa commented on src/main/java/domain/Ladder.java
> +                .toList();
IntStream을 통해 다리를 만들어주고 있네요~ for문을 사용하는 것에 비해 어떤 장점이 있을까요?
가독성 측면에서는 어떤가요? 잉크의 의견이 궁금합니다.

2024-02-22 11:34 UTC, summerlunaa commented on src/main/java/domain/Ladder.java
> +        return List.copyOf(lines);
방어적 복사를 사용하셨네요~! 👍

2024-02-22 11:34 UTC, summerlunaa commented on src/main/java/domain/Name.java
> +        }
값객체도 잘 사용해주셨네요! 상수 사용과 이름에 대한 검증 좋습니다 👍

2024-02-22 11:34 UTC, summerlunaa commented on src/main/java/domain/Name.java
> +    }
equals와 hashCode를 함께 정의해주셨군요 👏

2024-02-22 11:34 UTC, summerlunaa commented on src/main/java/domain/NonContinuousLineGenerator.java
> +    }
메서드 순서 확인부탁드립니다. 추가로 private이 아닌 이유는 테스트 때문일까요?

2024-02-22 11:34 UTC, summerlunaa commented on src/main/java/domain/NonContinuousLineGenerator.java
> +    public RowLine generate(Integer personCount) {
여기서도 박싱타입을 사용하고 계시네요 👀

2024-02-22 11:34 UTC, summerlunaa commented on src/main/java/domain/RowLine.java
> +        return connections.get(index).equals(ConnectionStatus.CONNECTED);
```suggestion
        return connections.get(index).isConnect();
```
이미 만들어둔 메서드를 활용해봅시다

2024-02-22 11:34 UTC, summerlunaa commented on src/main/java/config/Config.java
> +public class Config {
클래스명이 Config네요~ 어떤걸 구성하는 클래스인지 바로 알 수 있을까요?
추가로 이 클래스는 어떤 의도로 만드신 건지도 궁금합니다.

2024-02-22 11:34 UTC, summerlunaa commented on src/main/java/controller/LadderGameController.java
> +                                RowLineGenerator rowLineGenerator) {
RowLineGenerator를 컨트롤러에서부터 받고 있네요.
LadderGameController가 RowLineGenerator를 필드로 갖고 있을 필요가 있는지 고민해봅시다.

2024-02-22 11:34 UTC, summerlunaa commented on src/main/java/controller/InputMapper.java
> +public class InputMapper {
전체적으로 이 클래스가 꼭 필요한가?라는 의문이 드는 클래스들이 보여요
- InputMapper는 InputView와 GameController로
- RandomElementSelector는 NonContinuousLineGenerator로
- MessageResolver는 ResultView로

로직이 이동되어도 문제 없어 보이는데요, 왜 이렇게 클래스를 나누게 되었는지 궁금합니다.
과도한 클래스 분리는 어떤 단점이 있을지 고민해봅시다. 저는 개인적으로 클래스가 많고 로직이 흩어져있어 코드를 읽기 어렵다고 느꼈습니다.

2024-02-22 11:34 UTC, summerlunaa commented on src/main/java/domain/ConnectionStatus.java
> +package domain;
도메인 패키지에 클래스가 많아서 연관된 클래스끼리 패키지로 묶으면 더 파악하기 쉬울 것 같습니다.

2024-02-22 11:34 UTC, summerlunaa commented on src/test/java/domain/ConnectionStatusTest.java
> +        Assertions.assertThat(getAllStatus()).containsAll(List.of(CONNECTED, DISCONNECTED));
무엇에 대한 테스트인가요? 꼭 필요한 테스트인지 고민해봅시다.
그리고 정적 임포트는 해당 값 혹은 메서드의 출처를 알기 어려워서 지양하는 편입니다.

2024-02-22 11:34 UTC, summerlunaa commented on src/test/java/domain/HeightTest.java
> +    @ValueSource(ints = {1, 2, 3})
경계값에 대한 테스트, 검증 성공/실패에 대한 테스트 좋습니다 👍

2024-02-22 11:34 UTC, summerlunaa commented on src/test/java/domain/RowLineTest.java
> +        assertThat(rowLine.hasRightConnection(2)).isTrue();
`hasRightConnection`은 테스트만을 위한 메서드네요 🤔 잉크는 테스트만을 위한 코드에 대해서 어떻게 생각하시나요?
그리고 여기서 확인하려는 부분은 무엇인가요? 꼭 필요한 테스트인지 고민해봅시다.

2024-02-22 11:34 UTC, summerlunaa commented on src/test/java/util/RandomElementSelectorTest.java
> +        assertThat(random).isIn(numbers);
이 테스트를 통해 `selectRandomElement`가 테스트가 되었다고 말할 수 있을까요?

2024-02-23 02:10 UTC, yechop commented on src/main/java/domain/Height.java
> +    }
Integer가 더 많은 기능이 있다고 생각하여 사용했는데 래퍼 타입이 메모리를 많이 차지하고 연산할 때 박싱하는 과정이 추가된다는 단점을 이번에 알게 되었습니다

2024-02-23 02:26 UTC, yechop commented on src/main/java/domain/Ladder.java
> +                .toList();
큰 고민 없이 for문 보다 stream이 가독성이 더 좋다고 생각해서 사용했습니다.
```.mapToObj(i -> rowLineGenerator.generate(personCount))``` 
여기서 i 를 사용하지 않기 때문에 좋지 않은 판단이었던 것 같습니다

2024-02-23 02:37 UTC, yechop commented on src/main/java/domain/NonContinuousLineGenerator.java
> +    }
TDD로 진행하면서 이전 값이 true 면 false를 반환하는 테스트를 먼저 작성해놨었고, 테스트해야 하는 부분이라고 생각하여 페어와 상의하여 default로 설정했습니다.
더 좋은 의견이 있으시면 듣고 싶습니다!

2024-02-23 02:54 UTC, yechop commented on src/main/java/config/Config.java
> +public class Config {
프로그램 초기 설정을 위해 만들었다고 생각했는데 페어와 상의해보니 지금 상황에선 생성자 외 별다른 의미가 없는것같아 필요 없다 결론 내렸습니다

2024-02-23 03:08 UTC, yechop commented on src/main/java/config/Config.java
> +public class Config {
초기 설정을 해주기 위해 만들었는데 RowLineGenerator 외 다른 클래스는 선택지가 없기 때문에 불필요하다 생각하여 config를 제거했습니다.

2024-02-23 03:09 UTC, yechop commented on src/main/java/controller/LadderGameController.java
> +                                RowLineGenerator rowLineGenerator) {
config를 제거하니 누가 생성해줘야 하는지 생각해보게 되어 사다리를 만들때 받을수 있도록 리팩토링 해보았습니다

2024-02-23 03:14 UTC, yechop commented on src/main/java/domain/Height.java
> +    }
추가로 null을 방어하는 목적으로 primitive 타입으로 사용하는 이점도 학습했습니다

2024-02-23 06:26 UTC, yechop commented on src/main/java/controller/InputMapper.java
> +public class InputMapper {
객체가 하는 일을 더 명확하게 분리하기 위해 만들었습니다.
피드백 주신대로 다 수정해봤더니 더 읽기 쉬워진 코드가 됐습니다.

2024-02-23 10:48 UTC, summerlunaa commented on src/main/java/domain/Ladder.java
> +                .toList();
넵 사실 for 문을 사용해도 i를 사용하지 않는 건 동일하긴 한데요, 왜 for문 대신 IntStream을 사용했는지 궁금했습니다 ㅎㅎ
어떤게 더 가독성이 좋은지는 개인마다 다르니까요!

2024-02-23 10:56 UTC, summerlunaa commented on src/main/java/domain/NonContinuousLineGenerator.java
> +    }
public으로 열려있는 메서드를 테스트해보는 것은 어떤가요? 확인해보니 `generate`에 대한 테스트는 아예 없네요 🥲

2024-02-23 10:59 UTC, summerlunaa commented on src/main/java/config/Config.java
> +public class Config {
초기 설정을 왜 Config 파일에 모아서 하셨는지 궁금하네요 🤔
추가로 같은 구현에 대한 [다른 리뷰어의 코멘트](https://github.com/woowacourse/java-ladder/pull/256#discussion_r1498923944)가 읽어보면 좋을 것 같아 가져왔습니다.

>이 코드가 어떤 확장성을 가져다주나요? 오히려 import한 객체명이 바뀔때마다 항상 git changed로 잡히는 불편함이 부각되는거 같습니다.
>
> 확장성 좋은 코드는 개발자의 꿈이지만, 객체지향 5원칙 SOLID 중 OCP (확장에는 열려있고 변경에는 닫혀있어야한다)에는 Crystal Ball Problem이라는 문제가 있습니다. 우리는 미래의 변경을 수정구를 보는 마법사처럼 모두 알 수 없듯이, 어떤 것이 확장될 지 미리 예측할 수 없다는 의미입니다.
> 
> 그런 의미에서 목적이 분명치 않은 확장성은 결국 확장성을 누리지 못함으로써 코드의 복잡성을 증대시키고, 코드의 유지보수성을 악화시킵니다.
> (과한 확장성을 조롱하는 의미에서 만들어진 [FizzBuzz Enterprise Edition](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition)이라는 레포지토리도 있습니다 ㅎ 4줄짜리 요구사항을 구현하기 위한 세상에서 제일 복잡한 코드입니다)
> 
> 개인적인 경험으론 확장성을 고려하지 않고 코드를 모두 구성한 후, 확장의 필요성이 분명한 경우에만 리팩토링하는게 도움이 되었고, 미리 예측했던 확장성이 기대대로 동작했던 경험은 거의 없었던 것 같습니다. (초보여서 그런것도 있을겁니다 ㅎ
> 
> 말이 길어졌지만 오히려 DI를 지원하는 클래스여서 좋아하는 개발자도 있을겁니다 🫶 다만 저는 확장성이 뛰어난 복잡한 코드보다 바로 이해되는 간단하고 쉬운 코드가 팀에게 더 좋은 코드라고 믿는 개발자 입장에서 의견드렸습니다

2024-02-23 11:01 UTC, summerlunaa commented on src/main/java/controller/InputMapper.java
> +public class InputMapper {
더 읽기 쉬워졌다니 다행입니다 😅 각자 스타일이 다르겠지만 개인적으로는 클래스가 너무 많이 나눠지면 읽기 힘들더라구요~

2024-02-23 11:15 UTC, summerlunaa approved these changes
리뷰 너무 잘 반영해주셨네요 👏 

1단계는 여기서 머지할게요! 

주말 잘 보내시고 2단계에서 또 파이팅 해봅시다 💪

2024-02-23 11:15 UTC, summerlunaa commented on README.md
HOXY 리팩토링도 TDD로 하셨나요? 👀

2024-02-23 11:15 UTC, merged

2024-02-23 14:27 UTC, yechop commented on src/main/java/domain/NonContinuousLineGenerator.java
> +    }
generate는 랜덤으로 생성하는 메소드를 포함하고 있어서 어떤 항목을 테스트해야 할지 모르겠습니다 😭 
반환하는 RowLine의 길이가 personCount - 1 이 맞는지만 확인하면 될까요??

2024-02-26 04:00 UTC, yechop commented on README.md
리팩토링은 TDD로 하지 않았습니다.
메서드의 원형이 바뀌는 경우에만 TDD로 리팩토링하면 될까요??