[1단계 - 사다리 생성] 안나(김민겸) 미션 제출합니다
woowacourse/java-ladder pull request #277
Opened 2024-02-22 07:13 UTC by Mingyum-Kim

안녕하세요 현구막 🙌
사다리 미션에서 리뷰이로 참여하게 된 안나입니다. 

## TDD에 대한 고찰 . . .
이번 미션에서는 TDD를 중점적으로 학습해보았습니다.
TDD가 처음이라 미숙한 면이 많았는데 특히 어려웠던 점은 요구사항 파악 후 바로 테스트 코드를 작성하는 것이었습니다. 
코치님 말씀으로는 `기능 명세 - 테스트 코드 작성 - 프로덕션 코드의 뼈대 작성 - 내부 구현` 의 프로세스로 TDD를 진행하라고 하시는데, 테스트 코드에서 바로 객체가 어떤 값을 반환할 지, 어떤 역할을 하는 지 정의하는 게 쉽지 않더라고요. 
TDD를 조금 더 편안하게 하기 위한 리뷰어님만의 팁이 있다면 전달해주시면 감사할 것 같아요. 

## PR point
추가로 몇 개의 질문이 있는데 리뷰 시 참고해주시면 감사하겠습니다!

### DTO에 뷰 로직이 들어가는 것 VS 뷰에서 복잡한 출력 로직을 구현하는 것
사다리 미션을 구현하면서 아래와 같이 사다리를 출력하고, 참여자의 이름을 적절한 공백과 함께 출력하는 것에 큰 난항을 겪었습니다. 

![image](https://github.com/woowacourse/java-ladder/assets/67851124/213c8578-c582-4dd1-8b35-fb6a54e0ec6d)

그래서 이 로직을 분리하기 위해 DTO를 만들고 사다리의 한 row를 담아 보내는 방법을 채택하였습니다.
```java
public class LineResponse {

    private final String value;

    public LineResponse(String value) {
        this.value = value;
    }

    public static LineResponse from(Line line) {
        StringBuilder result = new StringBuilder();
        result.append(LadderElement.COLUMN.getSymbol());
        for (int index = 0; index < line.size(); index++) {
            result.append(getElement(line.hasBridge(index)));
            result.append(LadderElement.COLUMN.getSymbol());
        }
        return new LineResponse(result.toString());
    }

    private static String getElement(boolean hasBridge) {
        if (hasBridge) {
            return LadderElement.ROW.getSymbol();
        }
        return LadderElement.EMPTY.getSymbol();
    }
}
```
복잡한 출력을 만드는 것을 DTO에 넘기니 OutputView가 깔끔해지기는 했지만, DTO가 이렇게 뷰와 관련된 로직을 가져도 되나? 와 같은 궁금증이 생겼습니다. 
그 다음으로 해본 시도는 view 패키지에 Formatter라는 클래스를 정의하고 이 복잡한 로직을 이동하는 것이었습니다. 
```java
public class Formatter {
    public String formatPlayers(List<String> names) {
        StringBuilder stringBuilder = new StringBuilder();
        String firstPlayer = names.get(0);

        stringBuilder.append(firstPlayer);
        stringBuilder.append(" ");

        for (String name : names.subList(1, names.size() - 1)) {
            stringBuilder.append(" ".repeat(6 - name.length()));
            stringBuilder.append(name);
        }

        String lastPlayer = names.get(names.size() - 1);

        stringBuilder.append(" ".repeat(5 - lastPlayer.length()));
        stringBuilder.append(lastPlayer);

        return stringBuilder.toString();
    }
}

// OutputView.class
    private void printPlayers(List<String> names) {
        String value = Formatter.formatPlayers(names);
        System.out.println(value);
    }
```
그러나 클래스만 분리하였을 뿐 실질적으로 OutputView의 책임이라는 것은 변하지 않았습니다. 
이렇게 복잡한 뷰 로직을 분산하는 것에 대해 여러 방법을 정의해보았는데, 현구막은 어떻게 하는 게 최선이었는가에 대한 의견이 궁금합니다!

### Random 테스트

```java
@RepeatedTest(10)
    @DisplayName("동일한 true 값을 가지지 않는지 확인")
    void overlapConnection() {
        //given
        Line line = new Line(4);
        List<Boolean> points = line.getPoints();
        //when
        boolean isOverlap = false;
        for (int i = 0; i < points.size() - 1; i++) {
            if (points.get(i) && points.get(i + 1)) {
                isOverlap = true;
            }
        }
        //then
        Assertions.assertThat(isOverlap).isFalse();
    }
```
사다리가 연속으로 두 개의 연결 선이 나오지 않음을 테스트하기 위해 위 테스트 메소드를 사용하였습니다. 10번 테스트하여 한 번이라도 연속 연결선이 나오면 Fail되는 테스트인데, 실제로는 실패되는 케이스임에도 우연히 통과될 수 있는 테스트 메소드라 완벽하지 않다고 판단하였습니다. 
랜덤 테스트를 반복 테스트 하는 것이 최선일 지에 대한 현구막의 의견이 궁금합니다. 아니면 다른 대안책으로 랜덤 생성에 대한 인터페이스를 구현하여 테스트용 랜덤 생성기를 따로 정의해아하는 걸까요?

감사합니다!

2024-02-23 06:19 UTC, Hyeon9mak requested changes
안녕하세요 안나, 사다리 미션을 함께할 현구막입니다. 🙇‍♂️ 

#### TDD 고찰

저는 큰 단위부터 작은 단위로 테스트 작성-개발, 테스트 작성-개발 과정을 반복하는 편인데요,
아는 것부터 우선적으로 테스트를 작성하고, 모르는 것에 대해 조금씩 테스트를 채워나가는 방법도 있는 것 같아요.
가령 "사다리는 콘솔 화면에 이런 모습들 보여주어야 하니까 이렇게 만들어야지." 일 때
우선 `Ladder` 에 대한 테스트 코드를 작성하고, 구현하고.
장대해진 코드를 조금씩 덜어내면서 세부적으로 `Line` 에 대한 테스트 코드를 작성하고, 구현하고...
일련의 과정을 반복할 수 있겠네요.

테스트 코드에서 바로 객체가 어떤 값을 반환할지, 어떤 역할을 하는지 정의하기 쉽지 않은 건
비즈니스에 대한 이해도가 부족할 때 어쩔 수 없이 발생하는 매우 자연스러운 경험 같아요.
(사실 비즈니스 이해도가 높은 상태라면 A부터 Z까지 모든 로직을 안정적으로 개발할 수 있으니까요.)
조금 불편하더라도 학습을 위해 연습하는 과정이라고 생각하시면 좋겠네요~

#### dto vs view

화면 표현을 위한 코드는 어쩔 수 없이 지저분해지는 것 같아요.
지금 작성해주신 코드도 충분히 가독성이 좋다고 생각하고 있습니다.

추후 콘솔이 아닌 웹 프로그램으로 변경할 때 
:`OutputView` 를 변경할 것이냐, `DTO` 를 변경할 것이냐?" 를 상상해보면... 
자연스럽게 답이 도출되겠네요 😄 

저는 view 에 표현되는 걸 선호합니다.
DTO(Data Transfer Object)는 이름의 뜻 그대로 계층간 데이터를 옮기는 것에만 집중해야한다고 생각해요.
"사다리 표현 정책을 변경해주세요." 라는 요구사항이 전달되었을 때, 
표현 로직이 DTO 클래스에 존재할거라고 예측하기 어려울 것 같아요.

#### random test

난수를 꼭 테스트 해야하는 건가요? 애초에 난수가 테스트 가능한걸까요?
실제로 테스트 해야하는 건 참/거짓이냐에 따라 달리 동작하는 대상이 아닐까요? 😉 

간단한 코멘트 몇 가지 남겼습니다.
궁금하신 점 언제든지 추가 질문 코멘트 남겨주세요.

2024-02-23 06:19 UTC, Hyeon9mak commented on docs/README.md
> +  - [x] 중복된 이름인 경우를 예외 처리한다.
구현 목록 정리 👍

2024-02-23 06:19 UTC, Hyeon9mak commented on src/main/java/controller/LadderController.java
> +    }
controller 가 model view 간 소통에만 집중하도록 잘 정리되어 있는 것 같네요 👍

2024-02-23 06:19 UTC, Hyeon9mak commented on src/main/java/model/Height.java
> +    }
접근제한을 명시하지 않은 이유가 있을까요? 👀

2024-02-23 06:19 UTC, Hyeon9mak commented on src/main/java/model/Height.java
> +
온전한 값 객체로 활용될 수 있도록 동등성을 명시해주는 것도 좋겠네요 👍 
원시값 포장과 값 객체는 서로 같을까요, 다를까요?

2024-02-23 06:19 UTC, Hyeon9mak commented on src/main/java/model/Ladder.java
> +    }
Height 처럼 Width 도 포장할 수 있겠어요 😄 👍

2024-02-23 06:19 UTC, Hyeon9mak commented on src/main/java/model/LadderElement.java
> +}
"사다리 표현을 `------` 대신 `===` 로 변경해주세요!"
"저희 이번에 웹 프로그램으로 변경하면서 사다리를 이미지로 표기할건데요, 각각의 이미지 경로를 나타내주실 수 있을까요?"

프로젝트를 처음 인수인계 받은 동료 개발자에게 위와 같은 요구사항이 전달되었을 때,
동료 개발자는 model 과 view 패키지 중 어떤 패키지를 먼저 열어보게 될까요?

2024-02-23 06:53 UTC, Mingyum-Kim commented on src/main/java/model/Height.java
> +    }
아니요 !... 페어 프로그래밍 과정에서 빠뜨렸던 것 같습니다.
수정하겠습니다!

2024-02-23 06:55 UTC, Mingyum-Kim commented on src/main/java/model/Ladder.java
> +    }
그러네요 .. ! 일관성이 떨어진 부분인 것 같습니다
지적 감사합니다!

2024-02-23 07:04 UTC, Mingyum-Kim commented on src/main/java/model/Height.java
> +
제가 두 개념을 분리하지 않고 이해하고 있었네요 😅

값 객체는 원시값 포장과 달리 동등성을 보장하고 불변 객체임을 알게 되었습니다.
먼저 원시값 포장은 원시 타입의 값을 의미가 있는 객체로 포장하는 것입니다. 그러나 이 객체가 VO(Value Object)로 불리기 위해서는 동등성, 불변을 보장해야합니다.

현구막이 말해준 것처럼 동등성을 명시해주어서 사다리 높이 객체를 VO로 만들어봐야겠네요 👍

2024-02-23 07:09 UTC, Mingyum-Kim commented on src/main/java/model/LadderElement.java
> +}
아무래도 저라면 view 패키지를 열어볼 것 같습니다.
그럼 해당 클래스를 view 패키지로 이동하는 게 좋겠습니다 !

2024-02-26 07:54 UTC, Mingyum-Kim reviewed
안녕하세요 현구막 😊

피드백을 바탕으로 제가 페어 프로그래밍 과정에서 많이 놓쳤다 생각한 부분을 추가로 리팩토링하여 보내드립니다. 객체를 추상화하고 가독성 높은 코드를 작성하는 것에 많은 중점을 두었어요.

가장 큰 부분은 `StepStatus`, 즉 사다리의 한 다리의 상태를 결정짓는 요소를 함수형 인터페이스에서 생성하도록 구현한 것입니다.

```java
@FunctionalInterface
public interface StepStatusGenerator {
    StepStatus generate(Step previous);
}
```
그리고 이를 사용하는 Step 객체는 아래와 같이 구현체를 넣어주고요. 
```java
// Step.class
    public static Step of(Step previous, StepStatusGenerator stepStatusGenerator) {
        return new Step(stepStatusGenerator.generate(previous));
    }
```
이렇게 구현해보았는데, Step이 StepStatusGenerator를 필드로 가지고 있어야 했나요? 정적 팩토리 메서드에서 일일이 구현체를 주입받는 것이 괜찮은 설계일까요?

추가로, 너무 과한 추상화라는 의견이 있을 수 있을 것 같아요!
이에 대한 현구막의 리뷰를 기다리겠습니다 😊

2024-02-26 11:17 UTC, Mingyum-Kim reviewed
현구막 ☺ 질문이 하나 더 있어 코멘트 추가로 남깁니다. 

현구막이 이전에 블로그에 쓴 글을 보고 궁금한 것이 생겼어요.

![image](https://github.com/woowacourse/java-ladder/assets/67851124/355f3007-1ea0-481c-a1d9-ecd21477a002)
https://hyeon9mak.github.io/TDD-and-unit-test-are-different/ 이 글의 위 부분을 보고, 테스트를 위해 랜덤 생성 역할을 분리하는 것이 괜찮은가? 에 대해 고민하게 되었습니다. 

이번 미션이 자동차 미션은 아니지만, 저는 무작위 숫자 생성 역할이 Car에게 있다고 판단하였거든요. 그래서 테스트를 위해 랜덤 생성 기능을 상위 레벨로 올리면서 `이게 맞나?`라고 생각하게 되었습니다.

마찬가지로 이번 사다리 미션에서도 사다리 생성에 대한 랜덤 생성 기능이 포함되어있어요. 저는 상위 레벨로 올리기 보다 **인터페이스를 구현하여 테스트가 용이하도록 변경하는 방법** 을 선택하였는데, 위 예시와 비슷하게 테스트를 위해 구현을 바꾸는 케이스가 될 것 같아요. 

테스트를 위해서 특정 객체와 협력하는 객체를 변경한다. 혹은 테스트를 위해서 내부 구현이 가능한 부분을 인터페이스로 분리한다. 
이러한 상황에 대해서 현구막의 의견도 궁금합니다. 😊

2024-02-27 08:33 UTC, Hyeon9mak requested changes
안녕하세요 안나! 리뷰가 늦었어요. 🙏 
VO 등을 적극 활용해주신 덕분에 코드 가독성이 많이 오른 것 같아요.
`StepStatusGenerator` 를 통해 분리하고자 하신 부분도 확인했습니다.

#### 랜덤 생성 역할을 분리하는 것

역할이란 무엇일까요? 안나가 생각하시는 역할이라는 단어의 의미는 무엇인가요?
역할을 고려하여 코드를 작성하면 어떤 형태로 코드를 작성하고, 
어떠한 기준으로 클래스 파일을 분리하게 되는지, 안나만의 생각을 공유해주세요.
이 답변을 해주시면 저도 더 자세한 이야기를 해볼게요 😄 👍 

#### 테스트를 위해 특정 로직을 객체로부터 분리한다.

코드를 분리하는 기준은 테스트 보다는 유지보수를 위해서가 가장 좋다고 생각하는데요,
(이 부분에 대해서는 윗 질문에 답변해주시면 추가로 설명할게요 😄)
랜덤의 경우엔 특수한 케이스기 때문에 테스트를 위해 분리할 수 밖에 없는거 같아요.

자동차 미션과 사다리 미션에서 대표적으로 랜덤파트를 분리하는 이유는
안나가 진짜로 검증해야하는 부분이 "previous 가 없다면 랜덤한 결과가 나온다." 이 아니라,
"previous 가 없다면 무조건 A 가 수행된다.", "previous 가 있다면 무조건 B 가 수행된다." 기 때문이겠죠?

즉, 랜덤 요소로 인해 비즈니스적으로 정말 확인해야할 부분을 놓치지 않기 위해서라고 생각해요.
이와 관련해서 확인해봐야하는 로직들에 대한 테스트 코드가 빠진 것 같아서 request changes 남깁니다.
궁금하신 점 추가 코멘트 남겨주세요!

2024-02-27 08:33 UTC, Hyeon9mak commented on src/main/java/view/Formatter.java
> +    }
👍 
코드가 다소 복잡하지만 화면을 그리기 위해선 어쩔 수 없겠네요.
그래도 view 패키지를 별개로 분리해둔 덕분에 "이건 어차피 화면을 그리기  위한 로직이니 자세히 들여다보지 않아도 되겠군." 이라고 인지하기 편하겠어요.

2024-02-27 08:33 UTC, Hyeon9mak commented on src/main/java/view/LadderElement.java
> +    EMPTY(" ".repeat(5));
소소하지만... 화면을 그리기 위한 공간이니 `"-".repeat(5)` 대신 `"-----"` 로 표현해도.. 🤣

2024-02-27 08:33 UTC, Hyeon9mak commented on src/main/java/model/ladder/Width.java
> +    }
동등성이 부여된 VO 👍

2024-02-27 08:33 UTC, Hyeon9mak commented on src/main/java/model/ladder/Line.java
> +        }
매번 새로운 `RandomStatusGenerator` 인스턴스를 생성해야하는 걸까요? 🤔

2024-02-27 08:33 UTC, Hyeon9mak commented on src/main/java/model/ladder/Step.java
> +    }
<img width="489" alt="image" src="https://github.com/woowacourse/java-ladder/assets/37354145/b7654785-cd3a-4e03-b918-38d8ada57670">

아마도 안나가 테스트하고 싶은 영역은 빨간색 박스 영역이 아닐까 싶어요.
관련한 테스트 코드가 포함되면 좋겠네요!
그런데... Random 을 이용하는 구간이 보여서 테스트가 가능할지 의문스러워요.
Random 을 이용하는 구간에 대해 한번 더 분리하거나, 현재 분리 위치가 잘못된 건 아닌지 고민해봐야겠네요!

2024-02-27 08:33 UTC, Hyeon9mak commented on src/main/java/model/ladder/RandomStatusGenerator.java
> +    }
매번 `Random` 인스턴스를 생성할 필요가 있을까요? 😉

2024-02-27 10:49 UTC, Mingyum-Kim commented on src/main/java/view/LadderElement.java
> +    EMPTY(" ".repeat(5));
아하  유지보수를 고려한 선택이었는데, 단순 출력에는 오히려 별도로 로직을 넣는 것보다 문자열 그대로 입력해주는 것이 더 나을 수도 있겠네요 😊
반영하겠습니다!

2024-02-27 11:02 UTC, Mingyum-Kim commented on src/main/java/model/ladder/Line.java
> +        }
우선 사다리의 다리 하나를 생성하는 주체가 Step이기 때문에, 이를 생성하는 전략 또한 Step이 알고 있어야 한다고 생각하였습니다. 
그래서 Step 이 생성될 때 전략이 포함된 객체와 협력되도록 하였고, 이에 따라 Step이 생성될 때마다 새로운 Generator 인스턴스를 생성하게 되었습니다.

Ladder 전체에 대한 Generator 전략을 선택할 수 있고, 다리 하나하나에 대해 선택할 수 있지만 저는 후자가 맞다고 판단하였습니다. 
혹시 현구막은 다른 의견일지 궁금합니다!

2024-02-27 11:33 UTC, Mingyum-Kim commented on src/main/java/model/ladder/Line.java
> +        }
우선 제가 생각한 두 가지 방법 중 후자에 대해 구현해보았으니, 전자(Ladder 전체에 대한 Generator 전략을 선택) 로 구현해보고 장단점을 비교해보았습니다. 

```java
// LadderController.class
Ladder ladder = Ladder.of(height, Width.from(players.size()), new RandomStatusGenerator());

// Ladder.class
 public static Ladder of(Height height, Width width, StepStatusGenerator generator) {
        List<Line> lines = new ArrayList<>();
        for (int index = 0; index < height.size(); index++) {
            lines.add(Line.from(width, generator));
        }
        return new Ladder(lines);
    }

// Line.class
    public static Line from(final Width width, final StepStatusGenerator generator) {
        List<Step> steps = new ArrayList<>();
        Step previous = Step.from(StepStatus.EMPTY);
        while (steps.size() < width.size()) {
            Step step = Step.of(previous, generator);
            steps.add(step);
            previous = step;
        }
        return new Line(steps);
    }

// Step.class
    public static Step of(Step previous, StepStatusGenerator stepStatusGenerator) {
        return new Step(stepStatusGenerator.generate(previous));
    }
```

가장 먼저 와닿은 단점은 _파라미터의 개수가 늘어난다_ 는 점이었습니다. 그리고 Step을 생성하는 책임을 가진 _객체와 StepGenerator가 로직 상 멀어져있다_ 는 점도 마음에 걸렸습니다.

그러나 크루들과 얘기해본 결과, **Controller에서 Generator 구현체를 생성하는 것이 맞다**는 판단을 내렸습니다. 
왜냐하면 객체 역할 부여의 모호함이나 파라미터의 증가보다 Generator 인스턴스를 NM개 생성하는 것이 비용 상 더 좋지 않다고 판단하였습니다. 또한, Step마다 서로 다른 전략을 가지고 있다는 요구사항이 없음에도 Generator를 Step마다 다르게 생성하는 것 또한 [오버 엔지니어링](https://ko.wikipedia.org/wiki/YAGNI) 이라고 생각하였습니다.

결과적으로 현구막이 의문을 제기한 부분에 대해 동의하게 되었고, 해당 부분 코드 수정하여 반영하겠습니다 ☺

2024-02-27 11:46 UTC, Mingyum-Kim commented on src/main/java/model/ladder/RandomStatusGenerator.java
> +    }
아니요 ! ! 없는 것 같습니다.
습관적으로 함수 안에서 사용하였는데, 생각해보니 여러 객체에서 공유 자원으로 사용해도 괜찮다고 판단됩니다. 
`private static final`로 선언하는 것으로 수정하겠습니다!

2024-02-27 11:59 UTC, Mingyum-Kim commented on src/main/java/model/ladder/Step.java
> +    }
현구막의 의견에 대해 백번 동의합니다 😅
제가 가독성이라는 이유만으로 Step을 생성할 때 처리하는 비즈니스적인 요구사항을 Generator에 넣었던 것 같아요.

이 코드는 Step에서 분기해야하는 게 맞다고 생각하고, 그렇게 분리하면 테스트가 가능해질 것이라고 생각됩니다! 감사합니다 !!

2024-02-27 12:47 UTC, Mingyum-Kim reviewed
안녕하세요 현구막 !

정성스러운 리뷰 감사합니다. 피드백 모두 반영하여 다시 코드 리뷰 요청 드려요.
많이 고민해서 현구막의 질문들에 대해 생각해보았어요. 

**랜덤 생성 역할을 분리하는 것**

> 역할이란 무엇일까요? 안나가 생각하시는 역할이라는 단어의 의미는 무엇인가요?

역할이란 객체가 다른 객체와의 협력하기 위해 수행해야 하는 책임이라고 생각해요. 모든 객체가 각자의 역할을 수행해서 애플리케이션의 목적을 달성할 수 있게 되죠. 예를 들어서 이번 미션의 `StepStatusGenerator`는 랜덤값을 생성해서 외부로 넘기는 역할을 합니다. 이와 협력하는 `Step`은 이 랜덤 값을 토대로 StepStatus를 생성할 수 있구요. 

> 역할을 고려하여 코드를 작성하면 어떤 형태로 코드를 작성하고, 어떠한 기준으로 클래스 파일을 분리하게 되는가? 

위에서 설명한 것처럼 역할은 객체 간의 협력을 위한 책임이니, 객체의 구체적인 행동을 먼저 정의하고 이를 기준으로 클래스를 분리할 것 같아요. 그리고 협력 관계에 있는 객체들은 서로 직접 참조 혹은 간접 참조를 통해 메시지를 주고 받게 됩니다. 
이렇게 이야기하고 나니 Generator와 Step은 더욱 가깝게 연결되어있어야 한다는 생각이 진해지네요. 앞서 피드백 답글에서 Generator 인터페이스의 구현체를 생성하는 코드는  _성능 상의 이유로_  Controller에 있어야 한다고 말씀드렸고, 그렇게 수정했어요 . 

그런데 이렇게 돌이켜보니 그렇게 구현하는 것이 Generator와 Step의 관계성이 옅어지는 것 같아 찝찝한 기분이 드네요. 

**테스트를 위해 특정 로직을 객체로부터 분리한다.**

이 부분에 대해서는 너무 공감합니다! 제가 객체의 역할을 잘 못 설정했었던 것 같아요. 값진 피드백 감사드려요. 

```java
    @DisplayName("이전에 생성된 다리와 겹쳐서 현재 위치의 다리가 연결되지 않는다.")
    @Test
    void previousOverlapTest() {
        // given
        Step previous = Step.from(StepStatus.CONNECTED);
        Step expected = Step.from(StepStatus.DISCONNECTED);

        // when
        Step step = Step.of(previous, new RandomStatusGenerator());

        // then
        Assertions.assertTrue(step.equals(expected));
    }
```

추가로, 위 함수에서 로직 상 랜덤 함수가 호출되지 않는 테스트 케이스에 대해서는 구현체에 그냥 RandomStatusGenerator 를 사용하였습니다. previous의 상태가 `CONNECTED`인 경우 바로 `DISCONNECTED`를 반환하기 때문이죠. 
이런 경우에는 테스트 코드 내에 Random을 호출할 수도 있는 구현체를 넣어도 괜찮을까요? 

감사합니다, 현구막 ! 
답변 기다릴게요 😊

2024-02-28 12:50 UTC, Hyeon9mak approved these changes
안녕하세요 안나! 피드백 잘 반영해주셨습니다.
간단한 코멘트 남겼으니 확인해주세요!

#### 객체의 역할

자세한 의견 공유 감사합니다!  덕분에 안나의 코드 작성 과정을 유추하고 이해할 수 있었어요.

저는 객체의 역할은 "개발자가 특정 로직을 가진 클래스 파일을 현실 세계에 비슷한 동작을 수행하는 사물에 빗대어 이름을 부여한 것" 이라고 생각해요.
가령 `Ladder` 같은 경우 그저 단순히 내부 boolean, int 값들을 변경하는 코드 덩어리일 뿐이지만
우리는 `Ladder` 이라는 이름을 읽고 사다리를 오르내리는 것과 비슷한 동작들을 상상할 수 있게 되겠죠.

객체의 책임은 "이 클래스 파일을 수정해야할 이유" 라고 생각하는데요,

"사다리 다리 수를 요청하면, +1을 더해서 응답해주세요."
"사다리 다리를 한번에 하나만 생성해주세요. 사용자 명령을 매번 받아서 추가할래요."

가령 위와 같은 요청에 매번 `Ladder` 가 영향을 받게 된다면, `Ladder` 는 벌써 가진 책임이 2개라고 볼 수 있겠네요.
그럼 동료 개발자와 동시에 요청을 하나씩 처리할 때, merge conflict 가 발생할 위험도가 높아지겠어요.
위와 같은 요청이 동시에 자주 전달된다면 클래스 파일을 하나씩 분리해볼 수 있겠어요.
그럼 클래스 파일이 수정될 이유(객체의 책임)가 하나씩으로 변경될 수 있겠죠!

요런 식으로 처음 개발할 때 뿐만 아니라, 유지보수 시점에서 객체의 역할과 책임을 어떻게 바라볼 수 있는지도 고민해보면 재밌겠습니다 😄 👍 

> Generator와 Step의 관계성이 옅어지는 것 같아 ...

공감합니다. 서로 의미있는 로직을 근처에 두는 것도 유지보수에 굉장히 중요한 부분이겠죠~
관련해서 개선해볼 수 있는 코멘트를 남겨두었습니다. 참고해주세요!

#### 테스트를 위한 분리

> ... 이런 경우에는 테스트 코드 내에 Random을 호출할 수도 있는 구현체를 넣어도 괜찮을까요?

넵! 안나가 테스트 코드를 작성한 이유는 결국 "내가 만든 제품이 정상적으로 수행되는가?" 를 검증하기 위함이므로, 오히려 더 좋은 방법이라고도 볼 수 있겠네요 😄 
다만 `RandomStatusGenerator` 의 로직에 변화가 생겼을 때 묵시적으로 테스트의 결과가 달라질 수 있음은 주의가 필요할 것 같아요. 🤔 
이런 부분도 고민해보시면 재밌겠네요!

다음 단계에서 뵙겠습니다 👍

2024-02-28 12:50 UTC, Hyeon9mak commented on src/main/java/view/LadderElement.java
> +
안나 말씀대로 반복문을 두면 수정할 때 무척 간단하겠네요! 👍 
각각 장단점이 있을 것 같으니, 판단하시기에 적절한 방법을 채택하면 좋겠어요.

2024-02-28 12:50 UTC, Hyeon9mak commented on src/main/java/controller/LadderController.java
> +}
안나 말씀대로 Ladder 에서 매번 파라미터로 `RandomStatusGenerator` 를 들고 다니는 모습이 유지보수에 좋지 않을 수도 있겠어요.
또한 controller 에서 `RandomStatusGenerator` 를 주입해주는 경우...
`RandomStatusGenerator` 가 아닌 다른 `Generator` 로 변경하고자 할 때,
비즈니스 로직과 전혀 관계없는 controller 의 코드에도 변경이 생기게 되겠네요 🤔 

`Ladder` 가 `StepStatusGenerator`를 멤버변수로 다루는 건 어떨까요? 
생성 파라미터로 `StepStatusGenerator` 구현체가 주어진다면 그것을 (ex. 테스트용)
주어지지 않을 경우 자체적으로 `RandomStatusGenerator` 를 할당한다면...?

2024-02-28 12:50 UTC, Hyeon9mak commented on src/test/java/model/ladder/StepTest.java
> +    }
인터페이스 덕분에 편리한 구현체 생성이 가능하군요 👍

2024-02-28 12:50 UTC, Hyeon9mak commented on src/test/java/model/ladder/StepTest.java
> +            // given
언제 다리가 생성되고 언제 다리가 생성되지 않는지 한눈에 보이네요 👍

2024-02-28 12:50 UTC, merged

2024-02-29 00:52 UTC, Mingyum-Kim commented on src/main/java/view/LadderElement.java
> +
네! 자주 변하는 요구사항과 자주 변하지 않는 요구사항이 따로 있을 테니 그 점을 고려해서 유지보수하기 좋은 코드를 짜야겠어요.

2024-02-29 01:42 UTC, Mingyum-Kim commented on src/main/java/controller/LadderController.java
> +}
저도 그 점을 고려했었는데, `Ladder`가 `List<Line>`을 래핑하는 일급 컬렉션이라고 생각하였고, 기타 멤버 변수가 추가되면 안될 것 같다고 생각했습니다 😥  -> 이 부분에 대해서는 어떻게 생각하시는 지 궁금합니다.
자동으로 `RandomStatusGenerator`를 추가하는 생성자를 추가하는 것도 좋은 방법인 것 같아요 !

2024-02-29 04:25 UTC, Mingyum-Kim commented on src/test/java/model/ladder/StepTest.java
> +    }
네 맞아요! 추상화를 해둔 덕에 제가 원하는 구현체를 마음대로 생성하고 바로 쓸 수 있는 게 장점인 것 같아요.