[1단계 - 사다리 생성] 폰드(권규택) 미션 제출합니다
woowacourse/java-ladder pull request #288
Opened 2024-02-22 07:52 UTC by tackyu

indent depth를 줄이기 위해 stream을 사용하는 것이 적절한 방법인지 궁금합니다.
그리고 Line 클래스가 헷갈리게 설계된 것은 아닌지 여쭙고 싶습니다.
감사합니다.

2024-02-23 13:38 UTC, Deocksoo requested changes
안녕하세요 폰드, 리뷰어 러너덕입니다.
전반적으로 좋은 이름을 지어주기 위해 고민하신 흔적이 많이 보이네요.
테스트도 꼼꼼하게 잘 작성해주신 것 같아요 👍 

다만 중간중간 코드의 의도가 모호해 보이는 부분들도 조금씩 있네요.
로버트 C 마틴의 [클린코드]에서 저자는 '코드는 읽는 사람에게 프로그래머가 단호하다는 인상을 줘야 한다'는 이야기를 해요. '단호하다는 인상을 줘야 한다'는 말은 곧 코드가 코드 자체로 그 의도를 명확하게 드러내야 한다는 뜻이겠죠. 네이밍과 타입을 잘 활용하면 코드의 의도를 보다 명확하게 드러낼 수 있어요.

테스트 주도적으로 미션을 잘 진행해주신 것 같아서, 이번에는 어떻게 하면 의도를 더 명확하게 드러낼 수 있을지 한 번 고민해보시면 좋을 것 같네요.
관련해서 코멘트 남겨두었으니, 확인 한 번 부탁드려요 :)

> indent depth를 줄이기 위해 stream을 사용하는 것이 적절한 방법인지 궁금합니다.

stream은 indent depth를 줄이기 위해 사용한다기보다는, 함수형 프로그래밍 스타일의 코드 작성을 위해서 사용하는 경우가 많죠. for loop를 사용하는 것에 비해 어떤 장점이 있을지 한 번 고민해보셔도 좋겠네요.

> 그리고 Line 클래스가 헷갈리게 설계된 것은 아닌지 여쭙고 싶습니다.

모호한 부분들은 리뷰 통해서 전달드렸어요.

2024-02-23 13:38 UTC, Deocksoo commented on src/main/java/domain/model/Person.java
> +        if (this.name.length() > 5) {
중요한 규칙을 담고 있는 숫자인 것 같은데, java convention에 따라 constant 처리하는 것은 어떤가요?

2024-02-23 13:38 UTC, Deocksoo commented on src/main/java/domain/model/Person.java
> +        this.name = name;
사소한 것이지만, 할당은 검증이 끝나고 나서 하는 것이 낫지 않을까요?

2024-02-23 13:38 UTC, Deocksoo commented on src/main/java/domain/model/People.java
> +        return Collections.unmodifiableList(participants);
굳이 감싸지 않아도 이미 unmodifiable 인것같네요 :)

2024-02-23 13:38 UTC, Deocksoo commented on src/main/java/domain/model/People.java
> +        if (size < 2) {
마찬가지로 도메인 규칙을 담고 있는 특별한 숫자일 것 같은데, java convention에 따라 constant 처리하면 어떤가요?

2024-02-23 13:38 UTC, Deocksoo commented on src/main/java/domain/model/People.java
> +        int size = inputNames.split(",").length;
`inputNames.split(",")`가 꽤 자주 등장하네요. 이름을 받는 input의 포멧이 달라지는 경우에(가령 구분자가 | 로 바뀐다던지) 도메인 객체인 People에서 영향을 받는 곳이 꽤 많겠어요. 코드상으로는 View와 잘 분리된 것처럼 보이지만, 실제로 논리적인 의존성은 남아있다고 볼 수 있겠네요. 

이 일을 하는 위치가 이 곳이 적당할지도 한 번 고민해보시면 좋겠네요. 이 도메인 객체가 하는 가장 중요한 역할은 무엇인가요? inputNames를 자르는 일을 여기저기서 하고 있는데, 이 도메인 객체가 하는 역할을 고려했을 때 그 일은 도메인 객체가 중요하게 관심가져야 할 일인가요?

2024-02-23 13:38 UTC, Deocksoo commented on src/main/java/controller/LadderController.java
> +        Ladder ladder = runWithHandler(() -> new Ladder(inputView.askLadderHeight(), people.numberOfParticipants()));
한 line에 너무 많은 정보가 들어가있네요.
line 한 줄에 많은 너무 많은 메서드 호출이 있는 경우에, 그 중 하나에서 에러가 발생하면 에러가 발생한 부분이 어디인지 헷갈릴 수도 있어요. 일반적으로 에러가 발생했을 때 보이는 stack trace에서는 `LadderController.java:24` 와 같이 에러가 발생한 라인 넘버까지 특정해서 알려주곤 하거든요.

거기에 더해 inputView 호출은 도메인 객체 생성과는 꽤 구분이 되어야하는 동작일 것 같은데, 조금 더 읽기 쉽게 line을 분리하는 것은 어떤가요?

2024-02-23 13:38 UTC, Deocksoo commented on src/main/java/domain/model/Line.java
> +    void draw(RuleGenerator generator, int personCount) {
1.  이 메서드가 하는 일을 조금 더 명확하게 밝혀주면 좋겠어요. 메서드가 하는 일은 이름을 통해서 드러낼 수도 있고, 리턴 타입을 통해 드러낼 수도 있죠. 무엇을 그리는 메서드인가요? 이 메서드가 하는 일은 실제로 뭔가를 그리는 일인가요? 

2. 약간 사소한 것일 수 있지만, 테스트 하기 위해 default 접근제어자를 사용했군요. production code에서 필요한 것이 아니라 테스트를 위한 접근제어인것 같은데, 메서드의 활용 의도가 달리 해석될 수도 있겠네요. 연습을 위해서라도 한 번 불필요한 접근제어 없이 테스트해보는 것은 어떤가요?

2024-02-23 13:38 UTC, Deocksoo commented on src/main/java/domain/model/Line.java
> +    public Direction showDirection(int position) {
이 메서드는 동작을 테스트해보기 위해 미리 만들어둔 메서드인가요?

2024-02-23 13:38 UTC, Deocksoo commented on src/main/java/view/ResultView.java
> +        int maxHorizontalLines =personCount-1;
자동 정렬 한 번 해주시면 좋겠네요 :)

2024-02-23 13:38 UTC, Deocksoo commented on src/main/java/domain/model/People.java
> +    public int numberOfParticipants() {
java naming convention을 지키도록 하는 이름을 지어주면 좋겠네요.
https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

2024-02-23 13:38 UTC, Deocksoo commented on src/main/java/domain/model/Ladder.java
> +            lines.add(new Line(new RuleGeneratorImpl(), personCount));
이 line도 하나의 line에 너무 많은 정보가 들어가있네요.

2024-02-23 13:38 UTC, Deocksoo commented on src/main/java/domain/model/Line.java
> +    public List<Integer> findHorizontalPosition() {
이 메서드도 이름만 보았을 때에는 뭔가 Horizontal상에서의 특정 position을 찾을것만 같은데, 한 line 전체에 대한 정보를 주는군요. 
조금 더 나은 이름은 없을까요~?

2024-02-23 13:38 UTC, Deocksoo commented on src/test/java/domain/model/LineTest.java
> +        for(int i=0;i<4;i++){
테스트코드도 코드에요!
이런 부분들도 자동정렬 한 번 쭉 맞춰주시면 좋겠네요.

2024-02-23 13:38 UTC, Deocksoo commented on src/main/java/domain/model/Line.java
> +    public boolean hasLeftConnectedLine(int position) {
이 메서드도 private 메서드에서만 사용하는 메서드네요.
왜 public 으로 열어두셨을까요~?

2024-02-25 04:07 UTC, tackyu commented on src/main/java/domain/model/People.java
> +        return Collections.unmodifiableList(participants);
Stream.toList()가 불변 객체를 반환해서인가요??

2024-02-25 13:38 UTC, Deocksoo commented on src/main/java/domain/model/People.java
> +        return Collections.unmodifiableList(participants);
맞아요. IDE에서 아래 스크린샷과 같이 간접적으로 알려주기도 하고, toList() 구현을 통해 직접 체크해볼수도 있죠.
![Screen Shot 2024-02-25 at 10 38 02 PM](https://github.com/woowacourse/java-ladder/assets/38533611/41908cc2-118d-48a9-bcb7-9a9bcc0ac064)

2024-02-26 07:45 UTC, tackyu commented on src/main/java/domain/model/People.java
> +        int size = inputNames.split(",").length;
Person 객체들을 생성하고 그 정보들을 갖고 있어야 할 것 같습니다.
말씀하신대로 이름들을 split하는 책임은 People 클래스가 갖기보다는 입력 뷰가 갖는 것이 적절할 것 같습니다.

2024-02-26 08:49 UTC, tackyu commented on src/main/java/controller/LadderController.java
> +        Ladder ladder = runWithHandler(() -> new Ladder(inputView.askLadderHeight(), people.numberOfParticipants()));
inputView 호출을 따로 메서드로 분리했는데 괜찮은 걸까요??

2024-02-26 09:38 UTC, tackyu commented on src/main/java/domain/model/Line.java
> +    void draw(RuleGenerator generator, int personCount) {
1. 사다리 한층을 만들어 준다는 의미로 makeLine으로 변경하였습니다.
2. 생성자에 해당 메서드를 넣게끔 설계를 바꿨어서 테스트 코드에 추가적으로 draw가 있는 것은 실수 인 것 같습니다. 
private으로 접근제어자를 변경하였습니다.
혹시 불필요한 접근제어 없이 테스트해보라는 말씀은 draw만을 위한 테스트코드를 만들어보라는 의미이신가요??

2024-02-26 09:41 UTC, tackyu commented on src/main/java/domain/model/Line.java
> +    public Direction showDirection(int position) {
방향을 알려주는 메서드가 향후에 필요할 것 같아 만들게 되었습니다.
1단계 미션에서는 사용되지 않는 메서드입니다😅

2024-02-26 09:45 UTC, tackyu commented on src/main/java/domain/model/People.java
> +    public int numberOfParticipants() {
감사합니다 동사로 변경해주었습니다!

2024-02-26 09:59 UTC, tackyu commented on src/main/java/domain/model/Line.java
> +    public List<Integer> findHorizontalPosition() {
findRightConnectedPositions로 수정하였는데 적절한지 모르겠습니다🥲

2024-02-26 10:09 UTC, tackyu commented on src/main/java/domain/model/Line.java
> +    public boolean hasLeftConnectedLine(int position) {
private으로 변경하였습니다 감사합니다!

2024-02-26 12:45 UTC, Deocksoo commented on src/main/java/controller/LadderController.java
> +        Ladder ladder = runWithHandler(() -> new Ladder(inputView.askLadderHeight(), people.numberOfParticipants()));
아래와 같은 형태의 분리를 의도했어요 :) 

```java
        String height = inputView.askLadderHeight();
        Supplier<Ladder> ladderSupplier = () -> new Ladder(height, people.getNumberOfParticipants());
        Ladder ladder = runWithHandler(ladderSupplier);
```

아니면 Ladder의 생성자에서 받는 타입을 조금 바꿔서 아래와 같이 해볼 수도 있겠죠

```java
        Height height = inputView.askLadderHeight();
        Supplier<Ladder> ladderSupplier = () -> new Ladder(height, people.getNumberOfParticipants());
        Ladder ladder = runWithHandler(ladderSupplier);
```

폰드가 읽어보기에는 어떤가요?

2024-02-26 13:39 UTC, Deocksoo commented on src/main/java/domain/model/Line.java
> +    void draw(RuleGenerator generator, int personCount) {
1. makeLine과 makeHorizontalLine은 무엇이 다른가요? 
makeLine 은 무슨 일을 하고, makeHorizontalLine은 무슨 일을 하나요?

2. 테스트를 위해 원래 private이었던 메서드를 불필요하게 열어 둔 것으로 생각했네요 :)
불필요한 접근제어 없이도 필요한 규칙들을 잘 검증해주시면 좋겠다는 의미로 남겼던 코멘트였어요.
그러면 이제 테스트를 한 번 생각해보죠. 
구현해주신 Line의 가장 중요한 역할 중 하나는 사다리 생성 규칙에 맞게 사다리가 잘 생성되도록 하는 것일거에요.
지금 그 규칙은 잘 검증되고 있나요?

2024-02-26 14:16 UTC, Deocksoo commented on src/main/java/domain/model/Line.java
> +    public List<Integer> findHorizontalPosition() {
좋은 이름 찾기가 쉽지 않죠 ㅎㅎ
저번 이름보다는 조금 더 나은 이름인 것 같지만, 여전히 조금은 찝찝해하고 계시는 것 같네요 :) 
이 메서드는 오른쪽으로 연결되어있는 position들만 찾아주는 메서드에요.
사실 point들은 왼쪽이나 오른쪽 양방향을 둘 다 가질 수 있는데, 굳이 오른쪽으로 연결된 position들만 찾은 것은 아마도 View에서 그려주기 위함이겠죠. 코드상으로는 View에 의존성이 없어보이지만, direction이 있으면 그려주고, 없으면 안 그려주려는 View 맥락이 여기까지 은근슬쩍 침투해있어요. 이 메서드를 이해하기 위해 알아야하는 맥락이 너무 많아져버렸네요. 

일단 모든 points를 반환하도록 하고, view에서 point가 이어져있는지 아닌지에 따라 어떻게 표현할지 결정하도록 하는 것은 어떤가요?
혹은 아얘 points를 반환하지 않고 showDirection 메서드만 활용해서 그려볼 수도 있겠네요.

2024-02-26 14:26 UTC, Deocksoo requested changes
안녕하세요 폰드, 리뷰어 러너덕입니다.
코드를 깔끔하게 정리하고, 또 깔끔하게 테스트하는 것이 생각보다 쉽지 않죠 :)
지난 번에 코멘트 드린 부분들을 잘 고민해주고 계신것 같아요 👍 
조금 더 고민해보시면 좋을 만한 부분들 몇 군데 코멘트 남겨두었으니 확인 한 번 부탁드려요.
이해하기 어려운 부분이 있으시면 편히 질문 주세요.

2024-02-27 05:32 UTC, tackyu commented on src/main/java/controller/LadderController.java
> +        Ladder ladder = runWithHandler(() -> new Ladder(inputView.askLadderHeight(), people.numberOfParticipants()));
분리하는 게 가독성이 더 좋은 것 같습니다.
그런데 위와 같이 수정한 경우, 잘못된 입력을 주었을 때 재입력을 받게 하는 처리는 어떻게 해야할지 고민됩니다.

2024-02-27 07:27 UTC, tackyu commented on src/main/java/domain/model/Line.java
> +    void draw(RuleGenerator generator, int personCount) {
1. makeLine은 사다리의 한 층을 만들어주는 메서드이고, makeHorizontalLine은 개별 point기준 우측으로 다리를 랜덤하게 만들어주는 역할을 합니다.
makeHorizontalLine을 connectToRight으로 변경하였습니다.

2. 다리가 모두 생성되는 경우와 모두 생성되지 않는 경우를 만들고 showDirection을 이용해 결과를 확인하는 테스트 코드를 추가했습니다.

추가적으로 point 마지막에 값이 할당되지 않아서 코드를 수정했습니다

2024-02-27 08:39 UTC, tackyu commented on src/main/java/domain/model/Line.java
> +    public List<Integer> findHorizontalPosition() {
맥락도 코드의 의존성을 판단하는 중요한 기준이 된다고 생각 못했습니다 감사합니다!
해당 코드는 삭제하여 뷰와 도메인간의 의존성을 줄이고자 했고, showDirection을 통해 사다리를 그려주도록 변경했습니다.

2024-02-27 12:32 UTC, Deocksoo commented on src/main/java/controller/LadderController.java
> +        Ladder ladder = runWithHandler(() -> new Ladder(inputView.askLadderHeight(), people.numberOfParticipants()));
아하! 이제 보니 handler.handle 은 반복 입력 처리도 하고있었군요.
이런 부분이 실제로 협업을 하다 보면 오류를 만들어낼 여지가 있는 부분이 되겠네요.
제가 별 생각 없이 변수를 분리해냈는데, 처음에 작성하셨을 때 의도하셨던 동작과 달라져버리고 말았어요.
의도를 보다 명확하게 드러내기 위해 다양한 시도들을 해볼 수 있겠네요.

1. 기존에 입력받던 방식을 유지하면서 의도를 더 명확하게 해보기
- runWithHandler의 이름을 더 명확하게 밝혀서 '잘못된 입력을 주었을 때 재입력을 받게 하는 처리도 한다'는 사실을 드러내기.
- 아래와 같이 Supplier 의 범위를 명확하게 블록으로 보여줄 수도 있겠네요.
```java
        Supplier<Ladder> ladderSupplier = () -> {
            String ladderHeight = inputView.askLadderHeight();
            return new Ladder(ladderHeight, people.getNumberOfParticipants());
        };
```
2. 의도를 제대로 드러낸 추상화가 아니라면, 과도하게 추상화하는 것보다 오히려 중복이 나아요. Supplier로 콜백을 넘기는 방식을 포기하고 재입력을 각 inputView에서 처리하는 것도 나쁘지 않은 방식이죠.
3. 재입력을 포기하고 그냥 예외를 던지는 것도 괜찮은 방법이에요. 사용자에게 올바른 메시지를 담은 예외를 던지면, 예외를 받은 사용자는 지침에 따라 재시도하겠죠.

작성하시고 싶은 방향을 정해서 한번 개선해보시면 좋은 연습이 되겠네요 :)

2024-02-27 15:43 UTC, Deocksoo approved these changes
안녕하세요 폰드, 리뷰어 러너덕입니다.
변경해주신 코드 잘 읽어보았어요. 이전보다 더 깔끔하고 읽기 좋은 코드가 되었네요 👍 
리뷰 반영하시느라 고생 많으셨어요.
이번 단계에서는 충분히 고민해주신 것 같아서, 다음 단계 계속 진행해주시면 될것같아요.
질문주신에도 부분 코멘트 남겨두었으니 나중에 확인 한 번 부탁드려요~

2024-02-27 15:43 UTC, merged

2024-02-28 08:31 UTC, tackyu commented on src/main/java/controller/LadderController.java
> +        Ladder ladder = runWithHandler(() -> new Ladder(inputView.askLadderHeight(), people.numberOfParticipants()));
감사합니다 2단계에 적용해보겠습니다!

2024-03-01 14:28 UTC, tackyu commented
옙 감사합니다!