[1단계 - 사다리 생성] 엘라(오숙현) 미션 제출합니다.
woowacourse/java-ladder pull request #293
Opened 2024-02-22 08:00 UTC by oshyun00

안녕하세요! 6기 엘라입니다. 사다리 생성 미션 제출합니다.
이번 미션은 릴리와 함께 진행하였습니다.

미션을 진행하면서 궁금했던점, 고민했던 부분은 아래와 같습니다.
페어와 같이 고민해보고 저희끼리 내린 결론에 대해서도 정리해보았습니다.
관련해서 리뷰어님의 의견이 있으시다면 공유해주시면 학습하는데 많은 도움이 될 것 같습니다! 감사합니다. ☺️
---
> TDD 연습을 위해 TDD Cycle에 따라 실패하는 테스트, 프로덕션 코드, 리팩토링으로 구분해서 커밋한다.
  - 구현 초기에는 TDD 방식은 처음이라 테스트코드 작성, 도메인 로직 작성, 리팩토링 각각 커밋을 진행했습니다.
    - 저희가 구현한 방식이 TDD cycle을 잘 준수했는지 궁금합니다.
  - 초반에는 TDD 방식을 제대로 하고 있는지 피드백 받기 위해 각각 커밋했으며 이후 기능 단위로 커밋을 진행했습니다.
  - 생성자 테스트는 어떻게 해야할지, 어느 범위까지 해야할지 고민했습니다.
    - 예외 발생 케이스에 대해서만 검증하는 방식으로 진행했습니다.

> DTO 생성을 어디서 해야할까
  - DTO 생성 로직이 컨트롤러에 들어가야할지, 모델에 들어가야할지 고민했습니다.
    - 우리의 결론: DTO는 데이터를 전달해주는 역할을 하므로 모델에서 생성해서 컨트롤러에 전달해준다.
    - 위치: Participants의 captureParticipantsName(), Ladder의 captureLayerSteps()

> View에서 어느정도 형태까지 변환해야할까
  - InputView에서 입력받은 String으로 그대로줄지, 아니면 기본적인 형태변환까지는 해주어도 될까
    - 우리의 결론: 도메인으로 변환하는것은 안되지만, 모델에 값을 전달하기 위한 최소한의 형태까지는 변경할 수 있다.
  - OutputView에서 전달받은 DTO를 순환하거나 값을 가져와서 출력하기 위한 로직이 들어가는게 맞는가
    - 우리의 결론: DTO가 데이터 전달을 위한것이라서 해당 데이터를 출력 형태로 변환하는것까지는 가능하다.

> StepExistenceGenerator 의 generate() 메서드를 static으로 작성
  - Layer를 생성할때마다 Random 객체를 새로 생성하는것이 불필요하다는 생각이 들어서 반복되는 로직을 바로 사용할 수 있도록 static으로 작성하였습니다.

> Test만을 위한 getter 메서드가 존재해도 될까
  - TDD 방식으로 코드를 구현하다보니 도메인에 getter 메서드를 사용하게 되었습니다.
  - 나중에 보니 getter가 테스트 코드에만 사용되고 있었습니다.
    - 우리의 결론: 테스트를 위해 도메인 로직이 변경되는것은 아니니 사용해도 괜찮다고 생각.

> 재귀함수 사용
  - 사용자가 입력을 잘못 입력했을때 재입력을 받는 과정을 구현하기 위해 재귀함수를 사용했습니다.
  - 재귀함수의 경우 스택오버플로우의 가능성도 있다고 들었는데, 실제 현업에서 사용이 되는 방식인지 궁금합니다.

2024-02-23 07:11 UTC, lxxjn0 requested changes
안녕하세요 엘라. 이번에 리뷰를 맡게 된 스티치입니다 :)

기능 구현 목록 문서부터 코드까지 많은 고민을 기울이고 정성을 들인 코드라는 것이 느껴졌어요! 이번 단계가 어려운 단계가 아니기에 간단한 피드백 정도만 남겨봤는데 한번 확인하고 피드백 반영 부탁드릴게요.

그리고 남겨주신 질문에 대한 답변을 남겨보도록 하겠습니다.
---
### TDD에 대해서

TDD가 개발 과정에서 드러나다보니 제가 파악하기가 어려운 것 같습니다. 커밋의 경우 동작하는 코드 단위가 되어야 한다고 생각하기에 더더욱 TDD 프로세스를 드러내기 어려운 것 같습니다. 하지만 미아가 배운 과정에 맞게 요구사항에 대한 테스트를 작성하고 그에 맞는 프로덕션 코드를 작성한다면 올바른 과정이 맞지 않을까 생각합니다.

앞서 말씀드린 것처럼 커밋은 동작하는 코드 단위가 되어야 한다고 생각합니다. 따라서 굳이 TDD 과정을 드러내기 위해 동작하지 않는 코드를 커밋하지 않으셔도 될 것 같아요.

생성자의 경우에 생성자에서 관리하는 유효성 검증 또는 로직이 있는 경우에 대해서만 테스트를 작성하셔도 충분할 것 같아요. 비즈니스 로직이 담긴 내용에 대해서 테스트를 한다는 개념으로 코드들을 바라봐주시면 좋을 것 같습니다.

### DTO 생성

DTO의 생성 위치는 도메인 또는 컨트롤러 어디여도 상관은 없습니다. 그러나 도메인에서 DTO를 의존하는 것은 적절하지 않은 방향이 될 수 있습니다. 출력 레이어의 변경으로 DTO가 변경될 때, 이 영향 범위가 도메인까지 도달할 수 있기 때문입니다. 이러한 의존성의 방향만 잘 고려한다면 생성의 위치는 중요하지 않을 것 같습니다.

### View 객체 생성 범위

이 부분은 엘라가 작성하신 내용이 적절한 것 같아 추가적인 코멘트는 없어도 될 것 같습니다 :)

### Test만을 위한 getter

이 부분은 약간 애매한 부분일 수 있습니다. 객체의 프로퍼티를 읽기 위한 getter의 존재는 OK입니다. 그런데 테스트만을 위한 메서드 생성이란 관점에서는 NO인 것 같습니다. 만약 테스트만을 위해 getter가 필요하다면 AssertJ의 다양한 기능을 통해서 해결할 수 있을 것 같습니다. 이 부분은 AssertJ가 제공해주는 메서드를 한번 찾아보면 도움이 될 수 있을 것 같습니다.

2024-02-23 07:11 UTC, lxxjn0 commented on README.md
> +## 용어 정의
개발자가 코드를 작성하다 보면 본인에게만 이해하기 쉬운 용어나 개념들을 쓰곤 합니다. 엘라가 작성해준 용어 정리는 이런 부분에서 코드를 읽는 사람으로 하여금 좋은 자료가 되는 것 같아요 👍🏼

2024-02-23 07:11 UTC, lxxjn0 commented on README.md
> +## 구현할 기능 목록
꼼꼼한 기능 구현 목록 작성이네요! 커밋도 적절한 단위로 잘 작성해주신 것 같습니다 :)

2024-02-23 07:11 UTC, lxxjn0 commented on src/main/java/controller/LadderController.java
> +    }
[답변] 재귀함수에 대한 답변은 여기에 달도록 하겠습니다. 지금처럼 작성된 재귀함수에서 계속된 예외가 발생한다면 함수 호출 스택은 끊임없이 쌓이게 되고 이는 메모리에 큰 영향을 미치게 됩니다. 재귀함수를 사용할 상황이 잘 나오지 않기도 하지만 굳이 사용하려고 하지도 않는 것 같습니다. 

만약 재귀함수를 사용하는 상황이더라도 탈출 조건이 포함된 꼬리재귀가 아닌 이상은 사용을 지양하는 것이 좋지 않을까 생각합니다.

2024-02-23 07:11 UTC, lxxjn0 commented on src/main/java/view/InputView.java
> +    }
숫자 입력 판단을 예외를 활용하여 깔끔하게 해결하였네요 👍🏼

2024-02-23 07:11 UTC, lxxjn0 commented on src/main/java/model/Participants.java
> +    private final List<Participant> participants;
자바 코딩 컨벤션을 확인해주세요.

2024-02-23 07:11 UTC, lxxjn0 commented on src/main/java/model/Participants.java
> +        this.participants = participants;
값 생성과 초기화를 한번에 진행해도 괜찮을 것 같습니다.

2024-02-23 07:11 UTC, lxxjn0 commented on src/main/java/model/Participant.java
> +        Objects.requireNonNull(name, "이름은 null일 수 없다.");
[제안] 해당 메서드의 문서를 한번 읽어보는 것도 좋을 것 같습니다. 그렇다면 이 메서드를 어떠한 용도로 사용하기 위해서 작성된 것인지 알 수 있을 것 같아요.

2024-02-23 07:11 UTC, lxxjn0 commented on src/main/java/model/Ladder.java
> +        }
생성 로직을 private 메서드로 분리하는 것도 가독성을 높이는 방법이 될 수 있을 것 같아요!

2024-02-23 07:11 UTC, lxxjn0 commented on src/main/java/model/Step.java
> +    NONE(false, "     ");
해당 객체는 출력과 연관이 깊어보여요. 이 객체를 도메인으로 관리하는 것이 적절한 방향일까요?

2024-02-23 07:11 UTC, lxxjn0 commented on src/main/java/model/Step.java
> +    }
null을 return하는 public 메서드는 위험성을 가질 수 있습니다. null을 반환하는 경우 어떠한 방법들을 사용해서 적당한 안전장치를 마련해줄 수 있을까요?

2024-02-23 07:11 UTC, lxxjn0 commented on src/main/java/model/dto/LayerSteps.java
> +public record LayerSteps(List<Step> steps) {
DTO 객체가 도메인에 위치하는 것이 맞을까요? DTO 객체에 대해서 한번 공부해보면 좋을 것 같아요.

2024-02-23 07:11 UTC, lxxjn0 commented on src/test/java/model/LadderTest.java
> +                () -> assertDoesNotThrow(() -> new Ladder(validHeight, numberOfParticipants))
AssertJ 라이브러리를 한번 찾아보고 적용해보는 것도 좋을 것 같습니다!

2024-02-24 00:36 UTC, oshyun00 commented on src/main/java/controller/LadderController.java
> +    }
답변 감사합니다! 재귀함수 사용에 대한 궁금증이 항상 있었습니다. 좀 더 찾아보니 자바의 경우 꼬리재귀 최적화를 지원하지 않는다는 특징도 있네요.🥲 이번 미션의 경우 indent가 1까지만 허용되고, 프로그램 규모 상 StackOverflow가 생길만큼의 잘못된입력이 없다는 전제 하에 while, try-catch문 대신 재귀를 사용하였습니다. 재귀를 쓰지 않는다면 재입력받는 로직만 따로 클래스를 분리해서 메서드를 분리해야할지, 재입력 받는 횟수 제한을 해야할지, 이 부분에 대해서는 아직 어떻게 해결하는것이 좋을지 방향이 잡히지 않아서 학습을 더 해봐야겠습니다!

2024-02-24 00:37 UTC, oshyun00 commented on src/main/java/model/Participants.java
> +    private final List<Participant> participants;
상수와 상수가 아닌 필드 사이 개행 추가하였습니다!

2024-02-24 00:37 UTC, oshyun00 commented on src/main/java/model/Participants.java
> +        this.participants = participants;
값 생성과 초기화를 별도로 해야하는 이유가 없었네요! 해당 부분 수정하였습니다. 감사합니다. (값생성/초기화를 별도로 진행하게되면 List<Participant>에 대한 데이터를 한번 저장하고, 그 주소값을 다시 가져와서 초기화에 사용하므로 불필요한 과정이 한번 더 수행되는것이라고 생각했는데, 이렇게 이해하면 맞을까요?)

2024-02-24 00:40 UTC, oshyun00 commented on src/main/java/model/Participant.java
> +        Objects.requireNonNull(name, "이름은 null일 수 없다.");
메서드의 설명을 찾아보니 “지정된 개체 참조가 null이 아닌지 확인하고 null인 경우 사용자 지정된 NullPointerException을 발생시킵니다. 이 메서드는 주로 아래에 설명(코드예시)된 것처럼 여러 매개 변수가 있는 메서드 및 생성자에서 매개 변수 유효성 검사를 수행하기 위해 설계되었습니다.”라고 되어있네요!
처음 사용할 때 리턴값이 있는 메서드를 단순한 Null 체크용으로 사용하는것이 적절한가? 에 대한 의문이 있었습니다. 실제 메서드 설명에서 제시하는 방식대로라면 아래와 같이 null 값 체크 후 인라인으로 사용할 수 있겠네요!

```
this.name = Objects.requireNonNull(name, “name must not be null");
```

그리고 추가로 두가지 궁금점이 생겼습니다.

1. Null 체크를 해야하는가? Participant의 name을 받아오기 위해 Scanner의 nextLine()을 사용하고 있습니다.
nextLine() 메서드 자체가 적절한 입력값이 없을 경우 null이 아닌 
NoSuchElementException을 던지고 있는데, 과연 null 체크가 필요한지 의문이 생겼습니다
-> 이미 null 확인이 되어있는것이라 생각해서 null 체크를 하지 않아도 될것같습니다. 하지만 코드 변경이나 혹시 모를 상황을 대비해 null 체크를 하는게 맞을까요?

2. (Null 체크를 한다는 가정하에) name의 경우 null 체크 뿐만아니라 공백, 길이와 같은 부분도 검증이 필요합니다. 따라서 this.name = Objects.requireNonNull(name, “name must not be null”)처럼 작성할 수 없고 다른 검증 로직이 추가되어야하는데요, 이 때 String nullCheckedName = Objects.requireNonNull(name)처럼 메서드를 통해 null 체크 후 다른 검증 로직을 수행해도 괜찮을까요? 혹은 해당 메서드를 쓰지 않고 다른 예외 케이스들처럼 조건문, 별도 검증 메서드 등으로 검증하는 방식이 나을지 고민됩니다.

2024-02-24 00:40 UTC, oshyun00 commented on src/main/java/model/Ladder.java
> +        }
별도 메서드로 표현해주면 코드 흐름을 간결하게 나타낼 수 있겠네요! 메서드 분리하였습니다. 피드백 감사합니다.

2024-02-24 00:40 UTC, oshyun00 commented on src/main/java/model/Step.java
> +    NONE(false, "     ");
Step은 사다리의 발판 자체를 의미하는 도메인이라고 생각했습니다. 발판이 있는지, 발판의 형태는 어떻게 생겼는지를 속성으로 담고있는 객체라고 생각하고 구현했습니다. 그래서 이와 관련된 기능들은 Step안에 작성하였습니다. enum으로 Step의 유무와 형태(output)를 다루었던 이유는, 혹시 나중에 다리 형태가 변경되거나 다리를 구분하는 방법이 변경되었을 때(ex. true/false가 아니라 1,2,3,4 처럼 특정값에 따라 다리 모양이 정해진다거나) 유연하게 대처할 수 있지 않을까 생각했기 때문입니다.

피드백을 보고 [만약 다리 형태가 바뀌었을 때 다른 개발자가 해당 부분을 수정해야 한다면 어느 코드를 먼저 열어볼까? -> view를 먼저 보게되지 않을까?] 하는 생각이 들기도 했습니다. 그래서 발판 유무에 따른 출력 형태를 Step이 갖지 않고 OutputView에서 판단하는 방식으로 수정해보기도 했습니다. 이 과정에서 “——“와 같은 다리 형태가 OutputView에서 상수로 관리되게 되었는데, 상수로 관리하는것보다 Step의 필드로 관리하는게 의미 전달이 더 명확할것같다고 생각했습니다.

결국, Step을 자체 속성을 가지고 해당 속성(output)을 알려주는 도메인으로 사용하였는데 이 부분에 대해서 어떻게 생각하시는지 궁금합니다. 출력과 관련된 기능들이면 가능한 OutputView에서 관리되는것이 더 나을까요?

2024-02-24 00:41 UTC, oshyun00 commented on src/main/java/model/Step.java
> +    }
null을 반환하는 메서드를 사용하는 코드에서 반환된 값이 null인지 여부를 매번 확인하고, 그 값이 null일때 수행해야할 로직을 별도로 작성해야할 것 같습니다.
혹은 null값 대신 이를 대체할 수 있는 객체 혹은 상수로 반환할수도 있을것같아요.
세번째 방법으로 null을 던지는 대신 예외를 던지도록 하고 해당 예외를 처리해줄수도 있습니다.
세번째 방법으로 코드를 수정해보았습니다. 제가 작성한 코드의 경우 해당 부분이 Ladder를 생성하는 과정에서 호출되고, Ladder를 생성하는 과정에서 IllegalArgumentException(적절하지 못한 인자를 메서드에 넘겼을때 발생)을 처리하고 있기 때문에 예외 처리가 가능하다고 생각했습니다.

2024-02-24 00:41 UTC, oshyun00 commented on src/main/java/model/dto/LayerSteps.java
> +public record LayerSteps(List<Step> steps) {
DTO는 계층간에 데이터를 주고받기위해 사용하는 객체라고 알고 있습니다. 이번 미션의 경우 “도메인(DTO로 포장) -> 컨트롤러(전달) -> View(DTO 사용)” 으로 여러 패키지에서 사용되고 있는데, 도메인(model)패키지 아래에 들어가면 view에서 model 패키지의 내용을 참조하게되네요!
처음에는 도메인에서 파생된 dto라고 생각해서 도메인의 하위 패키지에 넣었는데, 다시 생각해보니 도메인 로직을 갖지 않는 별도의 객체(패키지)라고 판단했습니다. 여러 패키지에서 사용될 경우 그 중 상위 패키지에 위치하는것이 맞다고 생각했어요. 그래서 model, view와 같은 상위 패키지로 이동하였습니다.

2024-02-24 00:43 UTC, oshyun00 commented on src/test/java/model/LadderTest.java
> +                () -> assertDoesNotThrow(() -> new Ladder(validHeight, numberOfParticipants))
TDD 방식으로 개발을 진행하면서 페어와 가장 먼저 고민했던 부분 중 하나가 “AssertJ를 사용할지, JUnit5를 사용할지’ 였습니다. 둘 다 테스트 코드를 위해 사용되는데 JUnit5는 테스트를 위한 프레임워크로 테스트 케이스 생성 및 실행에 사용되며, AssertJ는 테스트 결과를 검증하기 위한 라이브러리로 테스트코드 가독성을 위해 사용하는 도구로 알고있습니다!
처음 구현할때에는 테스트 작성이 아직 익숙하지 않아 JUnit5를 사용하며 테스트 코드 작성에 익숙해지고자 했었는데요, 피드백주신대로 AssertJ를 적용해보면서 가독성 향상부분도 생각해보고 연습해볼수 있었습니다!  말씀해주신것처럼 간단한 getter의 경우 extracting()으로 대체할수도 있겠더라구요. AssertJ가 제공하는 다른 메서드들도 더 학습해봐야겠어요. 감사합니다!☺️

2024-02-24 14:57 UTC, lxxjn0 commented on src/main/java/controller/LadderController.java
> +    }
이 부분은 제가 추가로 답변 달아두었습니다.

2024-02-24 14:58 UTC, lxxjn0 commented on src/main/java/model/Participants.java
> +        this.participants = participants;
사실 큰 문제가 되진 않지만 굳이 로컬 변수를 선언하면서 초기화 할 필요가 없어보여서 의견을 말씀드린 것이었습니다 ㅎㅎ

2024-02-24 15:02 UTC, lxxjn0 commented on src/main/java/model/Participant.java
> +        Objects.requireNonNull(name, "이름은 null일 수 없다.");
### 1번

public으로 열려있는 메서드는 언제나 어떤 값이 파라미터로 들어올 수 있다고 가정하고 작성을 해야합니다. 만약 null이 들어와도 로직 상에 문제가 없거나 비즈니스 상에도 충분히 그럴 수 있다면 상관없겠지만, 그런 상황이 아니라면 최대한 방어적으로 코드를 작성하는 것이 적절하다고 생각합니다.

### 2번

개인적인 생각을 먼저 말씀드리자면 

```java
if (name == null) {
    throw new IllegalArgumentException("...");
}
```

이처럼 간결하고 우리가 다 아는 기본적인 방식으로도 작성해도 되지 않을까요? 코드의 라인 수가 줄어든다고, 코드의 길이가 적다고 좋은 코드는 아니라고 생각합니다. 명확한 부분을 명확한 로직으로 보여주는 것이 더 좋은 코드가 아닐까요?

2024-02-24 15:11 UTC, lxxjn0 commented on src/main/java/model/Step.java
> +    NONE(false, "     ");
먼저 가장 기본적으로 생각을 해야하는 부분은 의존의 방향과 적절한 책임이라고 생각합니다. 말씀드린 것처럼 해당 로직은 출력 관련 비즈니스를 나타내고 있는 코드입니다. 그렇기에 출력과 관련된 부분과 함께 변경 범위가 관리되어야 하고 이는 곧 그에 맞는 패키지(여기선 view)에 위치해야 한다고 생각합니다.

만약 view가 갑자기 웹 페이지로 변경이 되었고 사다리가 3D의 형태로 표현된다고 했을 때 지금의 enum 코드의 output을 알려주는 도메인 로직이 의미가 있을까요? 만약 view의 방식에 따라 도메인이 변경된다면 그건 도메인을 적절히 규정하지 못해서 생긴 문제라고 생각합니다.

엘라가 사다리 발판은 꼭 도메인 객체로 관리가 되어야 한다고 생각한다면 이 도메인 객체에는 출력을 관리하지 않고 해당 객체를 참조하는 다른 곳(view)에서 출력을 관리하면 되지 않을까요?

```java
// domain
public enum Step {
    EXISTS(true),
    EMPTY(false)
    ;
}

// view
public enum StepSymbol {
    EXISTS(Step.EXISTS, "-----"),
    EMPTY(Step.EMPTY, "     ")
    ;
}
```

이런 코드가 예시가 될 수 있지 않을까 싶습니다.

결론은 가장 중요하게 생각해야 할 것은 코드가 적절한 위치에 적절한 레이어(domain, view 등)로 관리가 되고 있는가에 초점을 맞추는게 옳다고 생각합니다.

2024-02-24 15:11 UTC, lxxjn0 commented on src/main/java/model/Step.java
> +    }
좋은 접근인 것 같습니다. 추가로 이러한 부분에 대한 해결책으로 Optional이라는 방법이 있는데 이 방법도 한번 공부해보면 좋을 것 같습니다.

2024-02-24 15:14 UTC, lxxjn0 approved these changes
엘라, 피드백 반영하시느라 수고 많으셨습니다.

1단계 피드백을 적절히 잘 반영해주셔서 기존에 리뷰에 대한 추가적인 코멘트만 남겨두었습니다. 2단계 바로 이어서 진행해주시면 될 것 같아요!!

추가로 다른 크루에게 이야기한 내용을 같이 전달해주면 좋을 것 같아 말씀드립니다.

이번 코드를 보면 사용자의 입력을 다시 반복해서 받는 부분에 많은 공을 들이신 것 같습니다. 사실 아루 뿐만이 아니라 다른 리뷰이들의 코드에서도 공통적으로 이 부분에 대한 노력과 다양한 기술과 언어적 기교를 넣으면서 코드를 작성하는 것 같았습니다.

그런데 '사용자의 입력이 적절하지 않을 경우 재입력을 받는다'라는 요구사항이 이번 미션에 있었나요? 중요한 것보다는 중요하지 않은 것에 너무 많은 노력과 집중을 하시는 것 같아요. 이번 단계는 TDD를 잘 하는 것과 이어서 객체의 분리, 어떻게 하면 도메인 로직을 코드로 더 적절하게 옮길 수 있는지가 가장 중요한 부분이라 생각합니다.

요구사항에 존재하지도 않을 뿐더러, 만약 존재한다고 하더라도 중요하다고 생각되지 않는 부분에 너무 많은 관심을 가지는 것이 안타깝다는 생각이 들었습니다.

2단계를 진행할 때에는 지금 레벨1에서 어떤 것을 배워야 하는지에 대해 한번 더 생각하고 그 부분에 초점을 맞춰서 코드를 작성해보시는 것이 더 좋은 방향이 아닐까 생각합니다.

2024-02-24 15:14 UTC, merged