[1단계 - 사다리 생성] 프람(김민종) 미션 제출합니다.
woowacourse/java-ladder pull request #294
Opened 2024-02-22 08:02 UTC by koust6u

## 미션 이해

**사다리 게임에 참여하는 사람에 이름을 최대5글자까지 부여할 수 있다.**
>  5글자가 최대이기 때문에 결과를 출력 할때도 5글자를 기준으로 사다리의 행을 맞춰 출력해주었습니다.

**사다리를 출력할 때 사람 이름도 같이 출력한다.**
> 사다리를 출력할 때 사람 이름도 같이 출력하고 2단계 미션을 고려하여 중복된 이름은 허용하지 않도록 하였습니다.

**사람 이름은 쉼표(,)를 기준으로 구분한다.**
> (,)를 기준으로 구분하고 공백 이름은 허용하지 않았습니다.

사람 이름을 5자 기준으로 출력하기 때문에 사다리 폭도 넓어져야 한다.
>  5자에 맞춰 출력하기 위해 사다리의 폭은 (|-----|)로 고정하였습니다.

+ 사다리 타기가 정상적으로 동작하려면 라인이 겹치지 않도록 해야 한다.
> 말 그대로 (|-----|-----|) 와 같은 사다리는 생성이 되지 않도록 구현하였습니다.

<hr/> 

## 미션 중 고민 사항

미션을 진행하면서 가진 의문점과 의문에 대한 개인적인 생각을 정리해보았습니다.
더 좋은 해결책과 방향이 있다면 제시해 주시면 감사하겠습니다.!!

Q. Random한 값을 이용하는 로직에 대한 테스트는 어떻게 테스트하면 좋을까라는 고민을 하였습니다.

> 본 미션에서는 RuleGenerator라는 난수 생성과 난수를 통해 가로 라인을 만들지를 판단하는 역할의 인터페이스를 두었습니다. 그리고
> test위한 구현체와 프로덕션에서 사용할 구현체를 따로 구현하여 사용하였습니다.
> 이렇게 코드를 만들게 되면 테스트를 하면서 OCP를 지키며 테스트 코드도 작성할 수 있을 거 같았기 때문입니다.

Q. 별다른 로직이 없이 멤버 변수에 대한 초기화만 하는 경우의 생성자도 테스트해야하나?

> 여러 크루들과 토론을 해보아도 반/반으로 갈리는 주제였던 것 같습니다. 개인적으로는 있으면 
> 좋겠지만 초기화 상대만을 확인하기 위해 프로덕션 코드에 변경이 있다면 하지않아도 되지 않을까? 라는 느낌만 가지고 있습니다.

Q. 켄드 벡의 "테스트 주도 개발"을 읽어보니 메모장을 이용하여 todo 내용들을 사전에 정리하고 테스트 작성 및 구현을 하던데 
todo thing을 어떤 기준으로 정해주는 것이 편할까요? 이 부분이 굉장히 어려웠습니다.. ㅠㅠ

2024-02-22 14:39 UTC, jamie9504 reviewed
안녕하세요, 프람. 😄 리뷰어 제이미입니다.

생각해보면 좋을 부분 코멘트 남겨두었습니다.

> 추가된 요구 사항
> 모든 기능을 TDD로 구현해 단위 테스트가 존재해야 한다.

리팩터링시에도 TDD로 수정 부탁드려요!

답변에 대한 코멘트는 아래에 남겨둘께요.

---

> Q. Random한 값을 이용하는 로직에 대한 테스트는 어떻게 테스트하면 좋을까라는 고민을 하였습니다.
> 
> 본 미션에서는 RuleGenerator라는 난수 생성과 난수를 통해 가로 라인을 만들지를 판단하는 역할의 인터페이스를 두었습니다. 그리고
> test위한 구현체와 프로덕션에서 사용할 구현체를 따로 구현하여 사용하였습니다.
이렇게 코드를 만들게 되면 테스트를 하면서 OCP를 지키며 테스트 코드도 작성할 수 있을 거 같았기 때문입니다.

👍 이름만 조금 더 가다듬으면 좋을 것 같네요!
테스트를 했을 땐 어떠한 장점이 있었나요?

> Q. 별다른 로직이 없이 멤버 변수에 대한 초기화만 하는 경우의 생성자도 테스트해야하나?
> 
> 여러 크루들과 토론을 해보아도 반/반으로 갈리는 주제였던 것 같습니다. 개인적으로는 있으면
좋겠지만 초기화 상대만을 확인하기 위해 프로덕션 코드에 변경이 있다면 하지않아도 되지 않을까? 라는 느낌만 가지고 있습니다.

일단 생각한 방식대로 구현해보고, 모자라면 추가해보세요!
TDD를 익혀가는 과정이기 때문에 어떻게 해야한다! 보다는 프람의 생각대로 해보고 필요할 때 도입하는 것이 좋다고 생각해요.
그래야 테스트 하나를 하더라도 의미를 담을 수 있을 것이라 생각해요 :)

> 켄드 벡의 "테스트 주도 개발"을 읽어보니 메모장을 이용하여 todo 내용들을 사전에 정리하고 테스트 작성 및 구현을 하던데
> todo thing을 어떤 기준으로 정해주는 것이 편할까요? 이 부분이 굉장히 어려웠습니다.. ㅠㅠ

일단 미션과 미션 가이드에 맞춰서 해보는 것을 더 추천합니다.
TDD가 익숙해질 때쯤 고민해보는 게 더 의미가 있을지도 몰라요 😃

2024-02-22 14:39 UTC, jamie9504 commented on README.md
> +## 기능 요구사항
https://github.com/woowacourse/java-ladder/pull/294/commits/03c6fd6185302a076fd58a27510de36282cc5874

해당 요구사항 정리시, PR에 작성해주신 미션 이해 관련된 부분이 같이 정리되어 있었어도 좋았을 것 같아요.

기능 요구사항과 구현 목표의 차이는 무엇일까요?
같은 내용이 두 벌로 관리되는 경우 장/단점은 어떤 것이 있을까요?

2024-02-22 14:39 UTC, jamie9504 commented on src/test/java/domain/model/PersonTest.java
> +    void personNameTest() {
https://github.com/woowacourse/java-ladder/pull/294/commits/3f7962e57082265ff3e9d80b6f04a6dd5ae5858a

domain.model 패키지를 사용한 이유는 무엇인가요?

---

리뷰할 때는 TDD한 부분이 명확해보여서 좋지만, 이렇게 되면 Commit 단위로 보았을 때 Test가 실패하게 되겠죠?
Commit 단위는 어떻게 가져가는 것이 좋을지 고민해보면 좋을 것 같아요.

만약 누군가, 프람의 커밋을 체리픽으로 가져간다고 했을 때, 테스트만 가져가거나 프로덕트 코드만 가져갈 수도 있고
롤백을 했을 때도 애매한 포인트에 롤백을 할 수도 있겠죠?

---

`" 사람은 이름을 가진다."` 저는 불필요한 띄어쓰기, 개행은 없는 것이 좋다고 생각해요 😃 

---

Assertions.assertThat에서, Assertions를 static import하지 않은 이유가 있나요?

2024-02-22 14:39 UTC, jamie9504 commented on src/test/java/domain/model/LadderTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
https://github.com/woowacourse/java-ladder/pull/294/commits/98046e39dd0fbd28cdf94522c56303756a71ae8a

음수인가요?

2024-02-22 14:39 UTC, jamie9504 commented on src/main/java/utils/RandomGenerator.java
> +
https://github.com/woowacourse/java-ladder/pull/294/commits/8713be043bc18e625211e85f3f29e7c745c09be5

2️⃣ 칸 개행이네요!
의미가 따로 있는걸까요?

---

interface가 RandomGenerator이고, 구현체가 RandomGeneratorImpl이면 충분한 의미가 클래스명에 담긴걸까요?

2024-02-22 14:39 UTC, jamie9504 commented on src/test/java/domain/model/PeopleTest.java
> +    }
https://github.com/woowacourse/java-ladder/pull/294/commits/64e7a5ad5e832ce42220d801535302c82ca449a5

2명의 참가자일 때 성공한 테스트가 없는 상황에서, 요구사항은 2명 이상의 참가자들이 필요한 부분이지만
2명일 때도 예외를 발생시킨다면, 해당 테스트는 요구사항을 명확히 테스트할 수 있나요?

---

IllegalArgumentException와 IllegalStateException의 차이는 무엇이고
각각 해당 예외들을 선언해준 이유는 무엇인가요?

2024-02-22 14:39 UTC, jamie9504 commented on src/main/java/domain/model/People.java
> +    public People(String names) {
https://github.com/woowacourse/java-ladder/pull/294/commits/d788afb5e32b9fd0c938d051f9dabb3b54cc4790

필요한 개행은 해주세요 😄 

---

`,`의 경우 아래에 선언해주었는데, 상수로 선언하는 것과 어떤 차이가 있을까요?

---

클래스내 메서드는 어떠한 순서로 선언하는 것이 좋을지 알아보아요!

---

numberOfOrigin와 originNumber는 어떤 차이가 있나요?

2024-02-22 14:39 UTC, jamie9504 commented on src/test/java/domain/model/LineTest.java
> +        //when
https://github.com/woowacourse/java-ladder/pull/294/commits/b707abee02464c8ec0bcde1a3fee087ad2d4dc01

given, when, then 사이 개행을 넣어주면 조금 더 보기 좋아집니다.

커밋마다 코드 스타일(포맷)은 맞춰주세요!

2024-02-22 14:39 UTC, jamie9504 commented on src/main/java/domain/model/Line.java
> +    public boolean hasLeftConnectedLine(int index) {
https://github.com/woowacourse/java-ladder/pull/294/commits/fd141964db66123e4a0cff4e5b0e1063877f2f9c

테스트코드를 위해 접근제어자를 제어하는 경우 어떠한 장/단점이 있을까요?
만약 접근제어자를 수정하지 않고 테스트에서 확인하려고 한다면, 어떤 방법이 있을까요?

2024-02-22 14:39 UTC, jamie9504 commented on src/main/java/domain/model/Height.java
> +    int height;
https://github.com/woowacourse/java-ladder/pull/294/commits/0c474c8b6f2055cf6eb44bdc4abcb954541913e0

접근제어자는 바로바로 붙이는 습관을 들여야 어떠한 경우에도 놓치지 않을 수 있어요!

2024-02-22 14:39 UTC, jamie9504 commented on src/main/java/view/InputView.java
> +        System.out.println("\n최대 사다리 높이는 몇 개인가요?");
https://github.com/woowacourse/java-ladder/pull/294/commits/e437db87819843aa6c680deb5b2d96ca4b57456c

\n으로 개행시 어떤 문제가 있을 수 있을까요?

2024-02-22 14:39 UTC, jamie9504 commented on src/main/java/utils/Console.java
> +public class Console {
https://github.com/woowacourse/java-ladder/pull/294/commits/4a5db7d32b524e9b982e641befc084ae6b521caa

Console을 분리했을 때의 장점은 무엇인가요?

2024-02-22 14:39 UTC, jamie9504 commented on src/main/java/controller/LadderController.java
> +    public void make() {
https://github.com/woowacourse/java-ladder/pull/294/commits/7ed3104454cf4b6c997b0f61418ca3c579c4f000

해당 메서드명과 클래스명을 보았을 때, 어떠한 동작을 할 것이라고 짐작할 수 있나요?

Controller를 분리한 이유는 무엇이며, 생성시 InputView와 ResultView를 주입받는 이유는 무엇인가요?

2024-02-22 14:39 UTC, jamie9504 commented on src/main/java/domain/model/Direction.java
>      RIGHT,
https://github.com/woowacourse/java-ladder/pull/294/commits/7c093ba7ef6c0f620e81eb886ef4b0ffaff5c687

한번에 바꾸지 말고 커밋마다 코드를 깔끔하게 관리할 필요가 있습니다.
그 이유는 무엇이라고 생각하시나요?

2024-02-22 14:39 UTC, jamie9504 commented on src/main/java/domain/model/Ladder.java
> +import utils.RuleGeneratorImpl;
RuleGeneratorImpl, RuleGenerator 그리고 메서드의 시그니처만 보았을 때 어떤 것을 generator해줄지 알 수 있나요?

2024-02-22 14:40 UTC, jamie9504 requested changes
안녕하세요, 프람. 😄 리뷰어 제이미입니다.

생각해보면 좋을 부분 코멘트 남겨두었습니다.

> 추가된 요구 사항
> 모든 기능을 TDD로 구현해 단위 테스트가 존재해야 한다.

리팩터링시에도 TDD로 수정 부탁드려요!

답변에 대한 코멘트는 아래에 남겨둘께요.

---

> Q. Random한 값을 이용하는 로직에 대한 테스트는 어떻게 테스트하면 좋을까라는 고민을 하였습니다.
> 
> 본 미션에서는 RuleGenerator라는 난수 생성과 난수를 통해 가로 라인을 만들지를 판단하는 역할의 인터페이스를 두었습니다. 그리고
> test위한 구현체와 프로덕션에서 사용할 구현체를 따로 구현하여 사용하였습니다.
이렇게 코드를 만들게 되면 테스트를 하면서 OCP를 지키며 테스트 코드도 작성할 수 있을 거 같았기 때문입니다.

👍 이름만 조금 더 가다듬으면 좋을 것 같네요!
테스트를 했을 땐 어떠한 장점이 있었나요?

> Q. 별다른 로직이 없이 멤버 변수에 대한 초기화만 하는 경우의 생성자도 테스트해야하나?
> 
> 여러 크루들과 토론을 해보아도 반/반으로 갈리는 주제였던 것 같습니다. 개인적으로는 있으면
좋겠지만 초기화 상대만을 확인하기 위해 프로덕션 코드에 변경이 있다면 하지않아도 되지 않을까? 라는 느낌만 가지고 있습니다.

일단 생각한 방식대로 구현해보고, 모자라면 추가해보세요!
TDD를 익혀가는 과정이기 때문에 어떻게 해야한다! 보다는 프람의 생각대로 해보고 필요할 때 도입하는 것이 좋다고 생각해요.
그래야 테스트 하나를 하더라도 의미를 담을 수 있을 것이라 생각해요 :)

> 켄드 벡의 "테스트 주도 개발"을 읽어보니 메모장을 이용하여 todo 내용들을 사전에 정리하고 테스트 작성 및 구현을 하던데
> todo thing을 어떤 기준으로 정해주는 것이 편할까요? 이 부분이 굉장히 어려웠습니다.. ㅠㅠ

일단 미션과 미션 가이드에 맞춰서 해보는 것을 더 추천합니다.
TDD가 익숙해질 때쯤 고민해보는 게 더 의미가 있을지도 몰라요 😃

2024-02-24 14:39 UTC, koust6u commented on src/main/java/domain/model/Ladder.java
> +import utils.RuleGeneratorImpl;
**"RuleGenerator, RuleGeneratorImpl" 그리고 Method 시그니처만을 보고 어떤것을 Generator 해줄지 알 수 있나?**
> 알수가 없을 것 같습니다. 그래서 method의 이름은 isAboveThreshold로 변경하고 인자값으로 직접 Threshold를 받아오면 더 
> 명확 할 것같습니다.!
<hr/>

2024-02-24 14:40 UTC, koust6u commented on src/main/java/domain/model/Direction.java
>      RIGHT,
타인의 체리픽이나 롤백등을 하였을때도 고려해하기 때문이라고 생각합니다.

2024-02-24 14:40 UTC, koust6u commented on src/main/java/controller/LadderController.java
> +    public void make() {
**"LadderController.class"에서 make()는 명확하게 의미를 전달하였는가?**
> 매우 추상적인 던어로 보여 runLadderGame()으로 정정하였습니다.

<hr/>

**Controller를 분리한 이유는 무엇?**
> View,model을 분리하고 책임을 나누어주기 위해 Controller를 두었지만 
> 제이미의 질문을 곰곰히 생각해보니 본 
> 미션에서는 Controller가 불필요해 보인다는 생각도 듭니다!  

<hr/>

**"LadderController"에서 InputView 와 OutputView를 주입 받아 초기화한 이유는?**
> 미션을 진행하면서 전체적으로 추후 요구사항이 변경 되더라도 유연하게 대처하고자 하였습니다.
따라서 InputView와 OutputView 역시 추후에 View에 대한 요구사항의 변경이 있더라도 쉽게 대체할 수 있도록 하기위해
주입 받아 사용하도록 하였습니다.
<hr/>

2024-02-24 14:40 UTC, koust6u commented on src/main/java/utils/Console.java
> +public class Console {
**Console을 분리하였을 때의 장점은?**
> 이번 프로젝트에서 Console의 책임은 단순히 readLine 뿐이었습니다. 또한 InputView에서만 사용되고 있기 때문에 불필요한 사용이었다 생각합니다.
> 장점이라고 하면 사용할때 Scanner 인스턴스 생성 한번으로 제한하고 재사용하는 장점이 있다고 생각하여 사용하였습니다.
<hr/>

2024-02-24 14:40 UTC, koust6u commented on src/main/java/view/InputView.java
> +        System.out.println("\n최대 사다리 높이는 몇 개인가요?");
**개행 문자 "\n"을 사용하면 나타날 수 있는 문제점은?**
> 찾아보니 \n을 사용하니 운영체제에 따라 별도의 \r 등의 리턴문자가 붙여질 수 도 있어 다르게 적용된다는 것을 알았습니다.
> 따라서 System.lineSeparator() 를 사용하면 개행을 운영체제에 맞게 반환해줍니다.
> 또는 prinf("%n")을 사용하는 방법도 있다는 것을 알 수 있었습니다. 감사합니다!
<hr/>

2024-02-24 14:40 UTC, koust6u commented on src/main/java/domain/model/Height.java
> +    int height;
꼼꼼한 지적 감사합니다.

2024-02-24 14:40 UTC, koust6u commented on src/main/java/domain/model/Line.java
> +    public boolean hasLeftConnectedLine(int index) {
**테스트코드를 위해 접근제어자를 제어하는 경우 어떤 장/단점이 존재하나?**
> 접근제어자를 제어하는 경우 생길 수 있는 장/단점에 대해 주관적인 생각을 정리해보았습니다.
> 
> 장점: 높은 테스트 커버리지를 유지를 할 수 있습니다.
> 단점: 접근 제어자 수정으로 인해 프로덕션 코드에서의 캡슐화가 깨질 수 있습니다.
<hr/>

**만약 접근제어자를 수정하지 않고 테스트에서 확인하려고 한다면?**
> 방법 1: reflection을 통해 private 접근제어자 테스트 가능합니다.
> + 단점.1: 리플랙션 차제가 컴파일 에러를 유발하지 않으므로 유지보수에 어려움이 발생합니다. <br/>
>
> 방법 2: private 접근제어자를 커버하는 public method에 대한 테스트를 작성합니다.
<hr/>

2024-02-24 14:40 UTC, koust6u commented on src/test/java/domain/model/LineTest.java
> +        //when
**given, when, then 사이에 개행을 넣어주는 것이 좋음**
> 좋은 피드백 감사합니다🤗 앞으로도 반영하겠습니다.
<hr/>

2024-02-24 14:40 UTC, koust6u commented on src/main/java/domain/model/People.java
> +    public People(String names) {
**필요한 개행은 해야한다.**
> 꼼꼼히 짚어주셔서 감사합니다🤗
<hr/>

**"," 의 경우 아래에 선언해주었는데, 상수로 선언하는 것과 어떤 차이?**
> ,를 상수로 빼주어 구분자라는 것을 명확하게 표현할 수 있다고 생각합니다!
<hr/>

**class 내에서 어떠한 순서로 method를 선언해 주는 것이 좋을 지 알아보자.**
> 유독 컨벤션 위배를 많이 하여 google 컨벤션부터 알아보았습니다.
> Google java style guide: new methods are not just habitually added to the end of the class, as that would yield
> "chronological by date added" ordering, which is not a logical ordering.
> 
> Google java style Guide에 따르면 시간순 보다는 논리적인 순서로 method를 배치하라고 나옵니다. 
> 뿐만 아니라 Oracle 컨벤션 Guide 에서도 비슷한 내용이 등장하는 것을 찾을 수 있었습니다.
> 이러한 내용을 종합하였을 때 Method는 Scope 범위의 구분이나, 시간 순 구분이 아닌 논리적인 역할을 기준으로 나열하는 것을 권장한다는 것을 
> 알게되었습니다. 감사합니다 👍
<hr/>

**numberOfOrigin 과 originNumber는 어떤 차이가 있나?**
> 개인적인 생각으로는 numberOfOrigin은 특정 Collection이나 배열의 원소의 숫자를 의미하고
> originNumber는 로직을 거치기 전(바뀌기 전)의 숫자를 의마한다고 생각하여
> numberOfOrigin이라는 이름으로 변수를 생성하였습니다.
<hr/>

2024-02-24 14:40 UTC, koust6u commented on src/test/java/domain/model/PeopleTest.java
> +    }
참가자가 두 명 이상 일때 성공한 테스트 케이스의 작성도 필요함.
> 꼼꼼히 짚어주셔 감사합니다. 해당 테스트 작성했습니다.😃
<hr/>

**IllegalStateException 과 IllegalArgumentException의 차이는?**
> 두 Exception의 개념을 제대로 알지 못하고 혼용하여 사용하였습니다.
> 그래서 이번 제이미의 피디백을 기회로 확실히 짚고 넘어가기로 했습니다.
> 아래는 두 Exception에 대해 제가 이해한 내용입니다!
> 
> IllegalStateException: 메서드가 잘못되었거나 부적절한 시간에 호출되었음을 알리는 신호입니다. 
> 즉, 애플리케이션이 요청된 작업에 적합한 상태가 아닙니다.
> ex) 참가자 이름을 입력 받는 로직이 종료 된 이후에도 사용자가 이름을 입력을 받는 상태에 던질 수 있는 예외
> 
> IllegalArgumentException:  메서드가 부적절한 인자를 통과했음을 나타내기 위해 던집니다.
> ex) 사다리의 높으를 -1 과 같이 모순된 값을 입력 받는 상황에서 던질 수 있는 예외
<hr/>

2024-02-24 14:40 UTC, koust6u commented on src/main/java/utils/RandomGenerator.java
> +
**"RandomGenerator.java"에서 2칸 개행 이유**
> 다른 이유 없이 2칸을 개행했습니다. 꼼꼼하게 짚어주셔 감사합니다.😃 2줄 개행과 같은 일관성을 헤치는 개행을 수정하겠습니다.
<hr/>


**RandomGenerator.java 와 RandomGeneratorImpl에서 이름에서 충분한 의도를 담고 있는가?**
> RandomGenerator 보다 RandomNumberGenerator가 더욱 더 좋은 이름인것 같습니다.
<hr/>

2024-02-24 14:40 UTC, koust6u commented on src/test/java/domain/model/LadderTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
음수가 아닌 자연수가 맞는 표현이었습니다.😭

2024-02-24 14:40 UTC, koust6u commented on src/test/java/domain/model/PersonTest.java
> +    void personNameTest() {
**domain.model 패키지를 사용한 이유는?**
> domain과 model에 대한 개념 혼동이 있었습니다. 
<hr/>

**Commit 단위로 보았을 때 실패하는 test가 발생한다. Commit 단위를 어떻게 가져가야할까?**
> 네 이 부분에 대해 고민을 해보았는데요. 미션 2단계 부터는 "Commit하기 전 모든 테스트는 통과되어야한다"라는 원칙 아래에 진행하도록 하겠습니다.
<hr/>

**"PersonTest.java" "  사람은 이름을 가진다." 불필요한 띄어쓰기/개행 발생**
> 일관성을 지키며 불필요한 부분은 삭제토록 하겠습니다.
<hr/>

**Assertions.assertThat 을 static import 하지 않은 이유는?**
>별다른 의도 없이 코드의 일관성을 지켜야 한다는 부분을 간과했습니다.😭
<hr/>

2024-02-24 14:40 UTC, koust6u commented on README.md
> +## 기능 요구사항
기능 요구사항은 미션에서 요구한 요구사항을 정리 해둔 것입니다.
 반면 구현 목표는 구현해야할 기능들을 체크리스트로 만들어 확인하는 용도로 두었습니다.
 
 > "기능 요구사항" 과 "구현 목표"를 차이 두었을 때의 <br/> 
> 
> **장점**: 미션 진행자의 입장에서는 현재 구현한 기능들을 한 눈에 확인할 수 있습니다. <br/>
> 
> **단점1**: 미션 진행자 이외의 사람들이 보았을 때 혼동을 줄 수 있습니다. <br/>
> **단점2**: 요구사항 추가/변경 시에 수정 두 곳 모두 수정을 해주어야 합니다. <br/>

2024-02-24 14:40 UTC, koust6u commented
제이미 감사합니다! 전반적으로 매우 꼼꼼한 리뷰에 매우 감사한 마음을 가지고있습니다.😲

또 고민할 거리도 많이 주어서 학습에 매우 많은 도움이 되었습니다.!!!!

2024-02-25 02:49 UTC, jamie9504 requested changes
안녕하세요, 프람. 😄 리뷰어 제이미입니다.

주말에도 작업하셨군요 💪 

이미 잘 챙기고 계실 수 있지만, 적당한 휴식은 회복에 도움을 주므로
프람의 컨디션을 잘 챙겨주시면 좋을 것 같아요! 😃 

고민하면 좋을 부분들 코멘트로 추가로 남겨두었습니다.

Request Changes 요청을 받았다고, 남은 주말에 급하게 수정하지 않으셔도 됩니다.
우테코 미션기간 내에만 수정해주시면 되는 부분인 것을 참고해주세요.

2024-02-25 02:49 UTC, jamie9504 commented on README.md
> +## 기능 요구사항
https://github.com/woowacourse/java-ladder/pull/294/commits/5051653e51ada3cb44f565bc5e1b9d9ff4eb199e
> README 파일의 수정된 내용은 아래와 같다.
> 리뷰어가 이해하기 쉽게 주관저긍로 미션이해에 대한 내용 추가하였다.
>
> 기능 요구사항과 구현 목표 의미하는 바가 유사함으로 기능 요구사항에 대한 내용은 삭제하였다.

일단 배려 감사합니다 😉 

README는 지속적으로 관리가 되어야 하는 문서라고 생각하면 좋습니다.
그렇기 때문에, 자세하면 좋지만 너무 자세하면 관리하기가 어렵겠죠 😃 

또한 혼자하는 미션의 경우는 조금 더 자세해도 직접 관리하기 때문에 추후 관리가 용이한 반면
페어, 팀 등이 같이 짜는 코드의 경우 결국 다른 사람도 이에 대한 필요성을 느끼고 관리를 해야 하는 부분이기도 해요.
이 부분을 맞춰가는 과정도 나중엔 필요하긴 하겠지만, 그냥 이런 저런 가능성을 고민해보는 것도 좋겠네요!

2024-02-25 02:49 UTC, jamie9504 commented on src/test/java/domain/model/PersonTest.java
> +    void personNameTest() {
domain과 model 중 model을 택한 이유는 무엇인가요?

https://github.com/woowacourse/java-ladder/pull/294/commits/6c014c6464e06702f7556fdff831723e9c8f51c3#
또한 일부가 Assertions이 static import 되었는데요!
테스트 코드들이 많지 않으니 일관성있게 가져가는 것도 좋을 것 같네요 😃

2024-02-25 02:49 UTC, jamie9504 commented on src/main/java/utils/RandomGenerator.java
> +
RandomNumberGenerator (인터페이스)
RandomNumberGeneratorImpl (구현 클래스)

(-Impl이라는 네이밍이 나쁘다는 의미는 아닙니다.)
이 두 클래스명만 보았을 때, 인터페이스는 다른 의미로 구현될 수 없이 `-Impl`로만 구현될 것 같은 느낌이네요.
이 부분에 대해서는 어떻게 생각하시나요?
인터페이스에서 랜덤 넘버라는 정보를 담아야 할지 고민을 해보는 것도 재밌을 것 같네요.

2024-02-25 02:49 UTC, jamie9504 commented on src/main/java/domain/model/People.java
> +    public People(String names) {
numberOfOrigin = origin의 number
numberOrigin = origin number
(이 부분도 제 개인적 취향이 들어있을 수 있습니다.) 위 두 개는 그냥 조사 차이라고 느껴져서,
특정 collection이나 배열의 원소의 숫자라면 Collection이나 Array에서 사용하고 있는 `size`나 `length` 혹은 다른 단어가 더 직관적으로 보일 것 같다는 생각은 했습니다.

예를 들자면 프람of우테코6기(우테코6기의프람) / 우테코6기프람 정도로 느껴진 것 같아요.

---

아래의 메서드명이 numberOfParticipants인 것은 적절할까요?
메서드 명명규칙에 대해 찾아보는 것도 좋을 것 같아요.

2024-02-25 02:49 UTC, jamie9504 commented on src/main/java/domain/model/Line.java
> +    public boolean hasLeftConnectedLine(int index) {
> 단점: 접근 제어자 수정으로 인해 프로덕션 코드에서의 캡슐화가 깨질 수 있습니다.

이 부분에 대해서 조금 더 덧붙여보자면,
캡슐화가 깨지며 메서드가 외부로 노출되면 다른 클래스에서 해당 메서드를 호출할 수 있게 됩니다.

즉, 해당 클래스의 노출된 메서드는 외부에서 요청할 수 있는 일종의 "역할"이 되는 것이죠!
메서드마다 이게 적절한지도 고민해보면 좋을 것 같아요 😃 

https://github.com/woowacourse/java-ladder/pull/294/commits/873a5eb3d1def273365469c9a850cc119c7cd13b

접근제어자를 수정하지 않고 학습 테스트를 해보았는데요.
각각 어떠한 특징이 있었나요?

프람의 취향은 접근제어자를 제어하는 법과, 각각의 수정하지 않고 테스트하는 법들 중 어떤 방식인가요?

2024-02-25 02:49 UTC, jamie9504 commented on src/main/java/utils/Console.java
> +public class Console {
Console의 close 메서드는 사용되지 않고 있는데 생성한 이유는 무엇인가요?

> 장점이라고 하면 사용할때 Scanner 인스턴스 생성 한번으로 제한하고 재사용하는 장점이 있다고 생각하여 사용하였습니다.

이 부분은 InputView의 상수로 Scanner를 가져갔을 때와 어떤 차이가 있나요?

2024-02-25 02:49 UTC, jamie9504 commented on src/main/java/controller/LadderController.java
> +    public void make() {
Controller를 분리해도, 하지 않아도 무방하지만 사용시에는 명확한 장점이 있는지, 꼭 필요한지 고민해보는 것이 좋습니다.

> 따라서 InputView와 OutputView 역시 추후에 View에 대한 요구사항의 변경이 있더라도 쉽게 대체할 수 있도록 하기위해
주입 받아 사용하도록 하였습니다.

InputView와 OutputView의 요구사항이 어떻게 변경되면 이런 경우 어떻게 쉽게 대처가 가능한지 예시를 들어주실 수 있을까요?
View는 외부에서 주입받고 ExceptionHandler는 내부에서 생성하고 있는데 어떠한 차이가 있어서인지도 궁금하네요 :)

2024-02-25 02:49 UTC, jamie9504 commented on src/main/java/domain/model/Ladder.java
> +import utils.RuleGeneratorImpl;
https://github.com/woowacourse/java-ladder/pull/294/commits/31b1172e8389db6b37303e8bda725800c7a96463

그렇다면 RuleGenerator.isAboveThreshold() / RuleGeneratorImpl.isAboveThreshold()을 봤을 때는
어떤 동작을 할 것인지 직관적으로 와닿으셨나요?
해당 클래스명이 해당 메서드의 역할을 가지고 있는 것이 자연스러운가요?

2024-02-25 02:49 UTC, jamie9504 commented on src/test/java/model/PeopleTest.java
> +import model.People;
https://github.com/woowacourse/java-ladder/pull/294/commits/6b5aee4871039e932934af08caf59068067fed95

참고로 패키지를 정리할 때는 사용하지 않는 import에 대한 정리를 해주면 좋습니다.

수정할 때 product 코드와 test 코드의 패키지가 순간적으로 달라지면서, test 코드에서 import를 하게 되었네요!
(추후 커밋에서 이런 부분들은 제거됩니다.)

2024-02-25 02:49 UTC, jamie9504 commented on src/test/java/model/PeopleTest.java
> +    }
https://github.com/woowacourse/java-ladder/pull/294/commits/730702c943663c1274e325465245595869ae6ef4

오타일까요?
``` diff
- @DisplayName("최소 2명 미만의 이름이 입력될 경위 예외를 발생시킨다.")
+ @DisplayName("최소 2명 미만의 이름이 입력될 경우 예외를 발생시킨다.")
```

---

추가적으로 성공 Test의 경우 doesNotThrowAnyException()으로 생성자를 잘 검증했다고 할 수 있을까요?

2024-02-25 02:49 UTC, jamie9504 commented on src/main/java/model/People.java
> +            throw new IllegalArgumentException("중복된 이름은 허용하지 않습니다.");
https://github.com/woowacourse/java-ladder/pull/294/commits/6c014c6464e06702f7556fdff831723e9c8f51c3

고민해보면 좋은 부분이라고 생각해서 남겨봅니다.
IllegalStateException > IllegalArgumentException으로 발생 예외가 변경되었는데요.
이 부분은 refactor 즉, 리팩토링일까요? 😃

2024-02-25 02:49 UTC, jamie9504 commented on src/main/java/utils/Console.java
> +    public static final String NEW_LINE = System.lineSeparator();
https://github.com/woowacourse/java-ladder/pull/294/commits/aab67e6a1581892f2662b05f34323c664d3dc01a

이 위치에 선언된 이유는 무엇인가요!

2024-02-25 02:49 UTC, jamie9504 commented on src/main/java/Application.java
> +        LadderController ladderController=new LadderController(new ResultView(),new InputView());
코드 스타일 전반적으로 체크 부탁드려요~
(띄어쓰기가 안된 부분, 개행이 필요하지만 개행이 되지 않은 부분 등)

2024-02-25 02:49 UTC, jamie9504 commented on src/main/java/controller/LadderController.java
> +    }
ExceptionHandler은 exception.handler(callback)을 호출했을 때 어떠한 동작을 할 것이라고 추측될까요?
저는 뭔가 예외를 핸들링해줄 것 같은 느낌은 받지만 재호출을 할 것 같은 느낌이 들진 않기도 하네요.

그리고 ExceptionHandler 인스턴스의 handle 메서드는 해당 부분에서만 사용되는데, 이 부분은 왜 클래스로 분리한 것인가요?

2024-02-25 02:49 UTC, jamie9504 commented on src/main/java/model/Height.java
> +        validateNaturalNumber(heightText);
파라미터에 final을 붙이는 프람만의 기준은 무엇인가요?

parseInt를 validate 내부에서도 해주고 바깥에서도 해주고 있네요! 😃 

이렇게 int 외의 다른 부분을 입력했을 때 출력되는 예외 메시지는 프람의 예상에 있는 메시지인가요?
<img width="389" alt="image" src="https://github.com/woowacourse/java-ladder/assets/59511689/ee6314c1-d134-4ad7-abd0-ef0c2aa44d2c">

또한 이 부분도 고민해보면 좋을 부분인데요.
만약 기준이 1이상의 정수에서, 2이상의 정수가 된다면 validate 메서드는 어떤 부분을 수정해야 할까요?
매직 넘버(magic number)라는 키워드에 대해서 알아보는 것도 좋을 것 같아요 😃

2024-02-25 02:49 UTC, jamie9504 commented on src/main/java/model/Ladder.java
> +            lines.add(new Line(new RuleGeneratorImpl(), personCount));
new RuleGeneratorImpl()은 몇 번 생성될까요?
이렇게 구현한 부분은 예상된 구현인가요?

2024-02-25 02:49 UTC, jamie9504 commented on src/main/java/model/Ladder.java
> +        return Collections.unmodifiableList(lines);
unmodifiableList를 사용한 이유는 무엇인가요?

2024-02-25 02:49 UTC, jamie9504 commented on src/main/java/view/ResultView.java
> +    }
(stream이나 stringbuilder를 얼마나 능숙하게 쓰냐에 따라 가독성이 다를 순 있긴 하지만)
for문으로 단순하게 구현한 것에 비해 어떠한 장점이 있을까요?

``` java
    private void printNames(People people) {
        for (Person participant : people.getParticipants()) {
            String name = participant.getName();
            printNameInterval(name);
            System.out.print(name);
        }
        System.out.println();
    }

    private void printNameInterval(String name) {
        for (int i = 0; i < MAX_INTERVAL - name.length(); i++) {
            System.out.print(" ");
        }
    }
```

2024-02-26 08:24 UTC, koust6u commented on src/main/java/model/Ladder.java
> +            lines.add(new Line(new RuleGeneratorImpl(), personCount));
예상치 못했던 구현이었습니다. 
해당 new RuleGeneratorImpl()의 경우에는 불필요하게 입력된 높이만큼 생성되므로 따로 빼주어야하는 것이 바람직하다고 생각됩니다.

2024-02-26 08:25 UTC, koust6u commented on src/main/java/model/Ladder.java
> +        return Collections.unmodifiableList(lines);
한번 생성된 Ladder들의 가로라인들은 변경될 일이 없으므로 Collections의 unmodifiableList로 반환하도록 해주었습니다.
그런데 다시 코드를 보니 Line 객체 값을 변경할 수 있는 method자체가 없다보니 불필요해보인다는 생각이 듭니다.

2024-02-26 08:25 UTC, koust6u commented on src/main/java/view/ResultView.java
> +    }
리뷰님께서 작성해준 String을 사용한 for문의  코드가 가독성 측면에서 더 좋아보입니다.

단순히  Stream이 더  간결하기에 좋은 코드라 생각했습니다.
이렇게 코드로 비교하여 보니 가독성 측면에 좋아보입니다.

좋은 고민점을 던져주어 감사합니다!

사실 Stream과 for문을 어떨때 사용하는 것이 좋을지 고민을 꽤하고 있던터라 조금 고민이 풀렸습니다.

 감사합니다!!!

2024-02-26 08:25 UTC, koust6u commented on src/main/java/controller/LadderController.java
> +    }
말씀 주신것처럼 exception.hander(callback)이라는 내용만 보고는 예외를 처리하는 것은 맞으나 구추적으로어떤 역할인지 전혀 추측이 되지 않습니다. 해당 메서드의 시그니처도 조금 더 명시적을 수 있도록 수정하겠습니다! 

또한 말씀주신 내용을 보니 runWithHandler는 현시점에서는 과도한 추상화였다고 봅니다.!

2024-02-26 08:25 UTC, koust6u commented on src/main/java/Application.java
> +        LadderController ladderController=new LadderController(new ResultView(),new InputView());
다음부터 꼼꼼히 확인하겠습니다. 좋은 지적 감사합니다!!!

2024-02-26 08:26 UTC, koust6u commented on src/main/java/utils/Console.java
> +    public static final String NEW_LINE = System.lineSeparator();
처음 의도는 InputView와 ResultView 모두에서 사용되는 Console에 두자는 것이었습니다. 만약 제이미라면 어느 위치에 선언하는 것이 바람직하다고 보시나요?

2024-02-26 08:26 UTC, koust6u commented on src/main/java/model/People.java
> +            throw new IllegalArgumentException("중복된 이름은 허용하지 않습니다.");
단순히 사다리 게임의 기능이 변경된 것은 아니니 refactor라고 생각했지만 
발생 예외를 바꾸는 경우에는 해당 예외를 발생시키는 코드를 사용하는 코드의  변경을 불러일으킬 수 있다는 점에서 
기능변경으로 분류하고 fix로  하는 것이 맞다고 생각이 듭니다!

2024-02-26 08:26 UTC, koust6u commented on src/test/java/model/PeopleTest.java
> +    }
단지 예외를 던지지 않다는 것보다 생성된 People안의 참가자의 숫자를 대조하여 비교하는 것 등이 더욱 잘 검증될 것이라고 생각합니다!

2024-02-26 08:27 UTC, koust6u commented on src/test/java/model/PeopleTest.java
> +import model.People;
좋은 정보 감사합니다! 정말 꼼꼼하고 섬세하게 봐주셔서 다시 한번 감사드립니다!

2024-02-26 08:49 UTC, koust6u commented on src/test/java/domain/model/PersonTest.java
> +    void personNameTest() {
**domain과 model 중 model을 택한 이유는 무엇인가요?**

>  MVC 패턴을 적용하여 명시적으로 MODEL이라고 표현하고 싶었습니다.

**또한 일부가 Assertions이 static import 되었는데요!
테스트 코드들이 많지 않으니 일관성있게 가져가는 것도 좋을 것 같네요 😃**

> 습관이 들지 않아 반복하는거 같습니다. 꼼꼼하게 짚어주셔서 감사합니다!!

2024-02-26 08:49 UTC, koust6u commented on README.md
> +## 기능 요구사항
README 파일 작성이 어색하여 고민이 쌓여가고 있었는데 좋은 의견 감사합니다!

2024-02-26 09:00 UTC, koust6u commented on src/main/java/utils/RandomGenerator.java
> +
`-Impl` 이라는 네이밍은 통상적으로 구현체가 하나일때 사용한다는 것을 상기하게되었습니다. 말씀처럼 Impl보다는 용도에 따라 Test~Generator 등으로 책임을 명확히 하는 것이 맞아보입니다!

2024-02-26 09:32 UTC, koust6u commented on src/main/java/domain/model/People.java
> +    public People(String names) {
size나 length로 쓰면 더욱 직관적일거 같다는 의견에 완전 공감합니다! 
좋은 답변 감사드립니다 😁

<hr/>
numberOfParticipants라는 메서드명은 확실히 잘못된 것이 맞는것 같습니다.
다만 동사형태여야하는다는 관례를 두고 적절치 못하다고 말씀하신 것이라 이해했는데 맞을까요?

2024-02-26 09:38 UTC, koust6u commented on src/main/java/domain/model/Line.java
> +    public boolean hasLeftConnectedLine(int index) {
좋은 의견 너무 감사합니다!

접근제어자를 수정하지 않고 테스트하는 방법이 지금은 익숙치 않아 어렵지만 캡슐화를 유지할 수 있다는 관점에서 더욱 끌리는 것 같습니다!

2024-02-26 09:43 UTC, koust6u commented on src/main/java/utils/Console.java
> +public class Console {
**Console의 close 메서드는 사용되지 않고 있는데 생성한 이유는 무엇인가요?**
> 미션을 진행함에 있어 전반적으로 사용할 것을 예상하여 먼저 구현하는 잘못된 버릇이 나와버린 것 같습니다. 😭
 
<hr/>

**이 부분은 InputView의 상수로 Scanner를 가져갔을 때와 어떤 차이가 있나요?**
사실 상 같은 차이가 없다 생각합니다. 이 또한 과도한 추상화였다 생각합니다.

2024-02-26 09:52 UTC, koust6u commented on src/main/java/domain/model/Ladder.java
> +import utils.RuleGeneratorImpl;
코드를 제가 직접 짤 때는 생각하지 못했던 부분이 피드백을 받으면 받을 수록 많았다는 것을 깨닫습니다!!

전혀 직관적이지 못한것 같습니다.
위  RuleGenerator라는 인터페이스나 그 구현체는 하는 역할이 임계값을 가지고 그 값을 기준으로 true or false를 반환하는 것 만을 수행합니다.

이러한 역할을 고려한다면 ThresholdChecker 와 같은 이름이 더 직관적으로 보일 것 같습니다.

2024-02-26 10:13 UTC, koust6u commented on src/main/java/model/Height.java
> +        validateNaturalNumber(heightText);
**파라미터에 final을 붙이는 프람만의 기준은 무엇인가요?**

> 파라미터의 final을 붙이면 메서드내에서 파라미터에 재할당이 금지되어 안정성을 높여준다는 점을 최근을 알아 의식적으로 파라미터의 숫자가 많지 않다면 의식적으로 final을 붙여주려하였지만 본 미션에서는 그러지 못한 부분이 훨씬 많은 것같습니다! . 제이미는 어떤 기준으로 final을 붙이는지 궁금합니다!

<hr/>

** int 외의 다른 부분을 입력했을 때 출력되는 예외 메시지는 프람의 예상에 있는 메시지**
> 예상하지 못했습니다.😭 
이런 식으로 제가 작성한 Exception아닌 경우의 Error메세지를 바꾸고 싶다면 크게 2가지 방법이 떠오르는데요.
1. try catch문으로 감싸고 새로운 예외에 메세지를 넣고 던져주기

2. 정규식을 사용하여 직접 검증하기가 있습니다.

혹시 두 방법을 제외하고 더 좋은 방법이 있을지 의견을 구하고 싶습니다!


<hr/>
**매직 넘버(magic number)라는 키워드에 대해서 알아보는 것도 좋을 것 같아요**
> 좋은 지적 감사합니다. 이 부분에 있어 Height 뿐만 아니라 People에도 비슷한 수정할 점이 있어 같이 수정해두었습니다!

2024-02-26 10:51 UTC, koust6u commented on src/main/java/controller/LadderController.java
> +    public void make() {
**Controller를 분리해도, 하지 않아도 무방하지만 사용시에는 명확한 장점이 있는지, 꼭 필요한지 고민해보는 것이 좋습니다.** 

> 제이미가 해준 말씀을 이 말이 정말 정곡을 찌른 것 같습니다. 지난 주차 미션에서 MVC를 학습하여 단순히 학습한 내용을 적용해보자는 생각에 사용하였습니다. 
적용 할 것이 짠 코드에 필요한 부분인지 판단하는 것을 의식하고 고민해보겠습니다.👍
<hr/>

**View는 외부에서 주입받고 ExceptionHandler는 내부에서 생성하고 있는데 어떠한 차이가 있어서인지도 궁금하네요 ** 
> 혼동이 조금 있었습니다.  view들이 interface를 구현하는 형태로 착각하고 답변을 달았습니다. 😭

2024-02-26 12:14 UTC, koust6u commented
안녕하세요! 제이미 
주말 늦은 시간에 리뷰 요청을 보내도 디테일하게 부족한 부분을 잘 집어주셔서 감사합니다😃.!!

피드백을 받을수록 전반적으로 부족한 점이 많다는 점을 느낄 수 있었습니다. 
또 부족한 부분이나 의문점이 있다면 말씀해주세요.

이번에도 정말 감사합니다!!

2024-02-26 17:14 UTC, jamie9504 approved these changes
안녕하세요, 프람. 😄 리뷰어 제이미입니다.

코멘트 조금 남겨두었는데, 읽어보시고
바로 2단계 진행해주시면 될 것 같아요!

1단계에서 필요한 부분은 충족한 듯 하여 이만 Approve & Merge 합니다.
다음 단계도 화이팅입니다 💪

2024-02-26 17:14 UTC, jamie9504 commented on src/main/java/domain/model/People.java
> +    public People(String names) {
> numberOfParticipants라는 메서드명은 확실히 잘못된 것이 맞는것 같습니다. 다만 동사형태여야하는다는 관례를 두고 적절치 못하다고 말씀하신 것이라 이해했는데 맞을까요?

넵 👍

2024-02-26 17:14 UTC, jamie9504 commented on src/main/java/utils/Console.java
> +public class Console {
프로그램은 확장에는 열려있는 것은 좋다고 생각하지만
미리 확장한 코드를 작성하진 않아도 된다고 생각해요!

이런 부분을 생각하면서 짜다보면 어디까지가 적절한 구현인가에 대한 프람만의 기준이 생길 것 같아요 😄

2024-02-26 17:14 UTC, jamie9504 commented on src/main/java/controller/LadderController.java
> +    public void make() {
그렇다면, 현재는 Interface가 아닌 상태인데, 외부에서 생성한 뷰들을 주입받을 이유가 있을까요?

2024-02-26 17:14 UTC, jamie9504 commented on src/test/java/model/PeopleTest.java
> +    }
이 부분은 정답은 없습니다.
프람이 생각하는 "생성자"의 역할에 대한 검증을 해주면 좋을 것 같아요!

2024-02-26 17:14 UTC, jamie9504 commented on src/main/java/utils/Console.java
> +    public static final String NEW_LINE = System.lineSeparator();
코멘트가 너무 모호했었네요!
클래스 나의 상수와 멤버변수의 위치에 대한 부분이었습니다 ! 😃

2024-02-26 17:14 UTC, jamie9504 commented on src/main/java/Application.java
> +        LadderController ladderController=new LadderController(new ResultView(),new InputView());
코드 스타일이 코드 결과에 영향을 주는 건 아니지만,
뭔가띄어쓰기를제대로 하지 않는다던가
<br>

개행을 불필요하게많이하거나 필요한데하지않는 그런 느낌을 준달까요..!

마치 이 코멘트처럼요 :) 가독성을 떨어뜨리는거죠!
코드를 읽는 미래의 본인과 협업하는 개발자들의 능률을 올려주자구요!

2024-02-26 17:14 UTC, jamie9504 commented on src/main/java/model/Height.java
> +        validateNaturalNumber(heightText);
> 제이미는 어떤 기준으로 final을 붙이는지 궁금합니다!

전 우테코를 할 땐 주로, 파라미터에서는 final을 굳이 붙이지 않고, 페어와 암묵적으로 재할당하지 않는 방식을 사용했었는데요!
일관성이 있고, 본인 외 다른 개발자도 쉽게 이해할 수 있는 일관성을 가진다면 어떤 방식이던 OK입니다!

> 작성한 Exception아닌 경우의 Error메세지를 바꾸고 싶다면

일단 이 부분은 가장 첫번째로 할 수 있는 부분은 이미 프람이 예상한 상황에 대해 IllegalArgumentException을 발생시키듯 해당 예외에도 해당 예외를 발생시키는 것입니다.

프람이 예를 들어준 방법 두 가지의 장/단점을 예시를 두어 개 다음번 단계 진행하실 때 코멘트로 달아주시겠어요?
이 부분에 대해서는 더 생각해봐도 좋을 부분인 것 같아서요 😄

2024-02-26 17:14 UTC, jamie9504 commented on src/main/java/model/Ladder.java
> +        return Collections.unmodifiableList(lines);
추후에 클래스가 변경될 수 있으므로, List가 수정이 가능한 상태라면 unmodifiableList를 명시해주는 것도 좋은 방식이라곤 생각합니다.
다만 사용했을 때 필요해서 사용하는지, 무의식적으로 사용했는지 한 번쯤 생각해보면 좋을 것 같아서 해당 코멘트 남겼었습니다!

2024-02-26 17:14 UTC, jamie9504 commented on src/main/java/view/ResultView.java
> +    }
stream이 for문에 비해 가독성이 좋은 부분이 있는 것은 물론 동의합니다.

그렇지만 어떤 상황에서 어떻게 구현하는가에 따라 반대의 경우도 있다는 점은 생각해보면 좋은 부분인 것 같아요 😃

2024-02-26 17:15 UTC, merged