[1단계 - 사다리 생성] 무빈(김현중) 미션 제출합니다.
woowacourse/java-ladder pull request #295
Opened 2024-02-22 08:04 UTC by hjk0761

# java-ladder

사다리 타기 미션 저장소

## 우아한테크코스 코드리뷰

- [온라인 코드 리뷰 과정](https://github.com/woowacourse/woowacourse-docs/blob/master/maincourse/README.md)

## 요구사항 해석

- [x] 이름을 입력받는다.
  - [x] 이름은 1글자 이상 5글자 이하로 구성된다.
  - [x] 이름은 쉼표로 구분된다.
  - [x] 이름은 2명 이상 10명 이하로 구성된다.
  - [x] 이름은 영어 대소문자, 숫자, '-', '_'로 구성된다.
  - [x] 이름은 영어 대소문자를 구분한다.
  - [x] 👀 null, 빈 문자열은 예외로 처리한다.
  - [x] 재입력은 5회로 제한하고, 6회부터 비정상 종료한다.

- [x] 최대 사다리 높이를 입력받는다.
  - [x] 높이는 1 이상 50 이하로 구성된다.
  - [x] 👀 정수 외의 값을 입력하면 예외로 처리한다.
  - [x] 👀 null, 빈 문자열은 예외로 처리한다.
  - [x] 재입력은 5회로 제한하고, 6회부터 비정상 종료한다.

- [x] 사다리를 생성한다.
  - [x] 사다리는 라인의 리스트다.
  - [x] 라인은 사다리 게임의 한 가로줄을 의미한다.
  - [x] 각 라인은 boolean 의 리스트다.
    - [x] 라인의 각 좌표의 값이 true 이면 왼쪽 열과 이어지는 사다리가 있다.
    - [x] 라인의 각 좌표의 값이 false 이면 왼쪽 열과 이어지는 사다리가 없다.
  - [x] 각 라인의 첫 번째 값은 항상 false 이다.
  - [x] 라인의 각 값은 0~9 사이의 숫자에 의해 결정된다.
    - [x] 해당 숫자가 5 이상인 경우 true 이다.
  - [x] 단, 라인의 이전 인덱스의 값이 true 인 경우 false 이다.
  - [x] 라인은 출력을 위해 index 의 값을 반환한다.
  - [x] 사다리는 출력을 위해 게터를 통해 상태를 반환한다.

- [x] LadderString
  - [x] 사다리의 상태를 String으로 변환하는 클래스이다.

- [x] LineString
  - [x] Line의 상태를 String으로 변환하는 클래스이다.
 
- [x] 결과를 출력한다.
  - [x] 이름을 6칸에 맞게 앞에 공백을 채워 출력한다.
  - [x] 사다리를 출력한다
    - [x] 현재 좌표가 1이면 '-----|'을 출력한다.
    - [x] 현재 좌표가 0이면 '     |'을 출력한다.
  - [x] 사다리 출력은 enum으로 관리한다.

---

## 출력 예시
```
참여할 사람 이름을 입력하세요. (이름은 쉼표(,)로 구분하세요)
pobi,honux,crong,jk

최대 사다리 높이는 몇 개인가요?
5

실행결과

pobi  honux crong   jk
    |-----|     |-----|
    |     |-----|     |
    |-----|     |     |
    |     |-----|     |
    |-----|     |-----|
```

---

## 자바 코드 컨벤션을 지키면서 프로그래밍한다.
- 기본적으로 Java Style Guide을 원칙으로 한다.
- indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.
- 3항 연산자를 쓰지 않는다.
- else 예약어를 쓰지 않는다.
- 모든 기능을 TDD로 구현해 단위 테스트가 존재해야 한다. 단, UI(System.out, System.in) 로직은 제외
- 핵심 로직을 구현하는 코드와 UI를 담당하는 로직을 구분한다.
  - UI 로직을 InputView, ResultView와 같은 클래스를 추가해 분리한다.
- 함수(또는 메서드)의 길이가 10라인을 넘어가지 않도록 구현한다.
- 배열 대신 컬렉션을 사용한다.
- Java Enum을 적용한다.
- 모든 원시 값과 문자열을 포장한다
- 일급 컬렉션을 쓴다.

2024-02-22 15:10 UTC, JunHoPark93 requested changes
안녕하세요 무빈~
피드백 몇가지 남겼는데 전체적으로 확인부탁드려요.
지난번 미션에서 경험했던 원칙들이 이번미션에서 동일하게 적용됩니다.
궁금한점 있으시면 남겨주세요~

2024-02-22 15:10 UTC, JunHoPark93 commented on src/main/java/controller/LadderController.java
> +        }
메서드를 분리해보면 어떨까요?
아래 높이입력부분도 마찬가지입니다~

2024-02-22 15:10 UTC, JunHoPark93 commented on src/main/java/controller/LadderController.java
> +        for (int tryCount = 0; tryCount < 5 && names == null; tryCount++) {
5라는 숫자가 반복되고있네요

2024-02-22 15:10 UTC, JunHoPark93 commented on src/main/java/controller/LadderController.java
> +    private Height heigthInput() {
오타가 있네요 👀 
이단어는 저도 오타 많이 내는거같아요.

2024-02-22 15:10 UTC, JunHoPark93 commented on src/main/java/controller/LadderController.java
> +        }
null반환은 최대한 지양해주세요.

2024-02-22 15:10 UTC, JunHoPark93 commented on src/main/java/domain/LadderGame.java
> +
제한자 설정이 없는건 의도하신걸까요?

2024-02-22 15:10 UTC, JunHoPark93 commented on src/main/java/domain/LadderGame.java
> +        }
도메인쪽에 출력로직이 들어가있네요 역할을 분리해볼까요?

2024-02-22 15:10 UTC, JunHoPark93 commented on src/main/java/domain/Line.java
> +    }
메서드 길이를 줄여볼 수 있는 방법이 있을까요?

2024-02-22 15:10 UTC, JunHoPark93 commented on src/main/java/domain/Name.java
> +        if (inputName.length() < 1 || inputName.length() > 5) {
isEmpty()를 사용해보면 어떨까요?

2024-02-22 15:10 UTC, JunHoPark93 commented on src/main/java/domain/Name.java
> +//        그 외의 차이점이 있거나, 위의 코드를 사용해야 할 일이 있는지 궁금합니다. 물어보기
이 부분 질문 남겨주신거죠?
"위의 코드를 사용해야 할 일이 있는지"라는게 패턴 객체를 메서드 안에서 계속 생성해야할일이 있는지에 대한걸 물어보신걸까요?

2024-02-22 15:10 UTC, JunHoPark93 commented on src/main/java/util/CustomGenerator.java
> +public class CustomGenerator implements Generator{
컨벤션도 전체적으로 확인부탁드려요~
지난번 미션에서 지켰던 원칙들은 앞으로의 미션에서도 동일하게 적용됩니다.

2024-02-22 15:10 UTC, JunHoPark93 commented on src/main/java/util/CustomGenerator.java
> +public class CustomGenerator implements Generator{
테스트에서만 사용되는 클래스로보이는데 위치를 다시 확인해볼까요?

2024-02-23 10:52 UTC, hjk0761 commented on src/main/java/controller/LadderController.java
> +        for (int tryCount = 0; tryCount < 5 && names == null; tryCount++) {
메서드를 수정하면서 재 입력이 5회로 제한된다는 의미를 전하기 위해 상수로 분리하였습니다.

2024-02-23 10:53 UTC, hjk0761 commented on src/main/java/controller/LadderController.java
> +        }
null 객체를 사용하지 않게 바꾸면서 해당 메서드도 수정이 있었습니다!

2024-02-23 10:56 UTC, hjk0761 commented on src/main/java/controller/LadderController.java
> +        }
전체적으로 null 객체를 사용했던 이유가, 5회 동안 재입력을 받을 상황을 만들기 위해 Players 객체 혹은 Height 객체가 생성되지 않고 null인 경우를 잡아내려고 했었습니다.
하지만 null 을 지양해야 되는 이유에 대해 생각해보니 NPE가 생길 때에 어디서 예외가 발생했는지 잡기 어렵다는 것과, null 자체가 의미를 가지지 않기 때문이라고 생각했습니다.

이에 따라 5회 재입력이라는 로직을 해결할 수 있는 다른 방법으로 반복문을 돌거나 재귀함수를 사용하는 방법을 생각해 볼 수 있었고, 이에 따라 재귀함수로 바꾸고 재입력 횟수를 상수로 분리하면서 그 의미를 살리려고 해봤습니다!

혹시 재입력 횟수를 제한하는 방법에 더 좋은 방법이 있을지 궁금합니다.

2024-02-23 10:58 UTC, hjk0761 commented on src/main/java/domain/LadderGame.java
> +
전체적으로 기능 완성에 목표를 두고 성급하게 달리다 보니 이렇게 놓친 부분이 있던 것 같습니다
컨벤션이나 네이밍 등에서 신경을 많이 쓰지 못한 것 같아 리뷰어님께 완성되지 않은 코드를 보여드리게 된 것 같습니다.
지적해주셔서 감사드리고, 앞으로 이런 부분이 없도록 충분한 검토 이후에 제출할 수 있도록 하겠습니다! 감사합니다!

2024-02-23 11:03 UTC, hjk0761 commented on src/main/java/domain/LadderGame.java
> +        }
말씀 이후로 생각해보면서 출력하기 위한 형태를 만드는 과정이 도메인에 존재하는 것이 올바른 흐름이 아닌 것 같았습니다.
이를 위해 기존의 LineString, LadderString 처럼 결과를 만들기 위해 한 곳에서만 사용되던 클래스를 하나로 묶고, 출력 형태를 만드는 메서드도 옮겨 출력에 대한 책임을 분리할 수 있었습니다.

이에 대해 궁금한 점이 생겨서 질문 드립니다.
구현하면서 LineString, LadderString이 하던 일들이 private 메서드로 변경되면서 이들을 테스트하던 코드 또한 돌아갈 수 없게 되었습니다.
이 문제에 대해 두 가지를 생각해볼 수 있었는데,
1) 해당 메서드를 디폴트 접근제어자를 사용하여 테스트를 가능하게 한다. -> 테스트만을 위해 접근제어자를 풀어주는 방식이라 사용하지 않았습니다.
2) 상위 메서드인 getResult(상위는 fromLine -> fromLadder -> getResult 순으로 호출된다는 의미에서 사용하였습니다) 에서 해당 기능이 모두 테스트 되기 때문에 테스트할 필요가 없다. -> 그렇다면 출력과 관계되는 부분이라 단위 테스트가 필요 없는 부분인지에 대해 궁금해졌습니다.
혹시 위와 같은 경우에 클래스 설계를 잘못 한 것인지, 혹은 테스트가 필요 없는 부분인건지 궁금합니다!

2024-02-23 11:05 UTC, hjk0761 commented on src/main/java/domain/Line.java
> +    }
38~40 라인의 로직은 한 줄인데 가독성을 위해 분리해둔 부분입니다.
for 문 한 줄로 정리되는 로직이라 분리할 필요가 없다고 생각하고 구현한 부분이었는데,
혹시 말씀 주신 메서드 길이를 줄일 수 있는 방법이 무엇인지 여쭤봐도 괜찮을까요?

2024-02-23 11:06 UTC, hjk0761 commented on src/main/java/domain/Name.java
> +        if (inputName.length() < 1 || inputName.length() > 5) {
length() < 1 과 isEmpty()의 의미가 상동하다고 생각하지만, 전자를 사용한 이유가 validateLength를 의미하기 좋은 표현이라고 생각해서 였습니다.
혹시 isEmpty를 사용하는 것에 다른 이점이 있는지 궁금합니다!

2024-02-23 12:51 UTC, hjk0761 commented on src/main/java/domain/Name.java
> +//        그 외의 차이점이 있거나, 위의 코드를 사용해야 할 일이 있는지 궁금합니다. 물어보기
처음에 페어와 함께 고민하던 부분이었습니다.
다만, 앞서 말씀드린 것처럼 완성되지 않은 코드를 보여드리게 되어 죄송합니다.

질문의 의도는 다음과 같습니다.
위처럼 Pattern 객체를 만들어 matcher를 이용하는 것과, String.matches를 이용하는 것에 차이가 있는지 궁금해서 정리해서 물어보려고 했던 부분이었습니다.

직접 Pattern.matcher와 String.matches의 차이를 찾아서 해결할 수 있는 부분이라고 생각해서 주석은 삭제했습니다.
혹시 두 방법의 cost 차이 외에 다른 차이가 있다면 알려주시면 감사하겠습니다!!

2024-02-23 12:52 UTC, hjk0761 commented on src/main/java/util/CustomGenerator.java
> +public class CustomGenerator implements Generator{
해당 클래스에서 중괄호 사용이 빠진 부분을 확인해서 수정하였습니다!
다시 한 번 충분한 검토 이후에 PR을 보낼 수 있도록 하겠습니다.

2024-02-23 12:55 UTC, hjk0761 commented on src/main/java/util/CustomGenerator.java
> +public class CustomGenerator implements Generator{
이 부분에 대해 여쭤보고 싶은 부분이 있습니다!

말씀 주신 것처럼, CustomGenerator는 LadderGameTest와 LadderTest에서만 사용되는, 테스트만을 위한 객체입니다.
하지만 두 테스트 클래스에서 사용되는 만큼, 내부 클래스로 옮기면 두 클래스에서 동일한 코드를 가지게 되는 단점이 있습니다.
테스트가 존재하는 패키지인 test/java/domain에 테스트가 아닌 클래스를 생성해도 되는지 확신이 없어 질문 드리게 되었습니다.

이렇게 테스트만을 위한 클래스가 존재할 때에, 이를 어떻게 관리하는 것이 효율적인지 궁금합니다!
특히 지금처럼 두 테스트 클래스에서 사용된다면, 어떤 방법이 좋을지 궁금합니다!

2024-02-24 12:46 UTC, JunHoPark93 commented on src/main/java/controller/LadderController.java
> +
다음 단계에서 컨벤션 확인부탁드려요~

2024-02-24 12:46 UTC, JunHoPark93 commented on src/main/java/controller/LadderController.java
> +        }
잘 변경해주셨네요~
이정도면 충분한거같습니다. catch문 안에서 로그라도 한번 찍어주면 더 좋을거같아요. 
null반환을 지양에 대한 내용을 잘 말씀해주셨는데요, 기존에 정의된 getHeight()메서드는 호출부가 null처리를 무조건 할것이다 가정을 하고 만들어진것이기 때문에 다른곳에서 호출되면 문제가 생길수도있었을거에요.

2024-02-24 12:52 UTC, JunHoPark93 commented on src/main/java/domain/LadderGame.java
> +        }
1. 넵 잘생각해주셨습니다. 테스트를 위해서 운영코드를 손대는일은 없어야됩니다.
2. "출력과 관계되는 부분이라 단위 테스트가 필요 없는 부분인지에 대해 궁금해졌습니다." 라는 말을 제가 제대로 이해한건지는 모르겠지만, 단위테스트는 필요합니다. 제 생각으로 무빈이 private메서드로 나눠지면서 테스트를 못하는 상황에 대해서 이야기주신거같아요. 일차적으로 호출하는 public메서드를 통해서 검증을 할 수 있구요, 그럼에도불구하고 private메서드 기능자체가 비중이 크고 중요해보이다면 메서드 분리의 신호로 볼 수 있어요. getResult가 너무 많은 일을 하는건 아닐까요?

2024-02-24 12:52 UTC, JunHoPark93 commented on src/main/java/domain/Line.java
> +    }
반복문을 추출하여 명시적인 메서드로 분리해보자는 이야기였습니다.

2024-02-24 12:56 UTC, JunHoPark93 commented on src/main/java/domain/Name.java
> +        if (inputName.length() < 1 || inputName.length() > 5) {
많이 사용되는 메서드이기도하고 직관적으로 "문자열이 비어있는가?"를 알 수 있습니다. 또한 성능차이는 거의 없겠지만, 한번의 연산으로 비어있는지 알 수 있겠죠.

2024-02-24 12:59 UTC, JunHoPark93 commented on src/main/java/domain/Name.java
> +//        그 외의 차이점이 있거나, 위의 코드를 사용해야 할 일이 있는지 궁금합니다. 물어보기
Matcher사용하면 전문일치가 아닌 부분일치도 알수있을거에요

그리고.. cost차이가 어떻게 날까요? 이런부분을 정리해서 코멘트를 남겨주시면 더 좋을거같아요.

2024-02-24 13:02 UTC, JunHoPark93 commented on src/main/java/util/CustomGenerator.java
> +public class CustomGenerator implements Generator{
테스트만을 위한 클래스가 존재한다면 당연히 테스트 패키지에 위치해야하구요,
두 클래스에서 사용되면 공통클래스로 만들고 참조하면 되지 않을까요? 🤔

2024-02-24 13:03 UTC, JunHoPark93 approved these changes
안녕하세요 무빈~
피드백 반영하시느라 수고많으셨습니다.
다음 단계 진행전에 기존에 질문주신 부분들에 대해 추가적인 코멘트 남겼는데 꼭 참고부탁드릴게요.

2024-02-24 13:03 UTC, merged

2024-02-24 14:56 UTC, hjk0761 commented on src/main/java/domain/LadderGame.java
> +        }
기존의 LineString, LadderString 으로 분리되어 있던 기능을 하나로 합치며 리팩토링하게 되었는데, 접근 제어자를 private로 설정하여서 테스트가 힘들어진 부분에 대한 고민이었습니다.

말씀 주신 것처럼 단위 테스트는 필요하고, 테스트가 필요한데 어렵다면 메서드를 분리하는 방향이 올바른 것 같습니다!
추후 리팩토링에서 분리하도록 해보겠습니다. 감사합니다!

2024-02-24 15:02 UTC, hjk0761 commented on src/main/java/domain/Name.java
> +//        그 외의 차이점이 있거나, 위의 코드를 사용해야 할 일이 있는지 궁금합니다. 물어보기
cost 차이에 대한 부분은 개인적으로 찾아보았습니다.

String.matches를 사용할 때에 내부적으로 Pattern 인스턴스를 생성하기 때문에, 반복적으로 사용되는 상황에선 Pattern 객체로 만들어 관리하는 것이 더 효율적인 방법이라고 알 수 있었습니다!

2024-02-24 15:09 UTC, hjk0761 commented on src/main/java/util/CustomGenerator.java
> +public class CustomGenerator implements Generator{
테스트 패키지에는 오직 테스트만을 수행하는 클래스만 존재해야 한다고 생각했었는데, 테스트를 위한 클래스 또한 해당 위치에 존재하는 것이 역시 당연한 거였군요.
다시 생각해보면, 왜 고민했는지 생각이 드는 질문이었던 것 같습니다!
친절히 답변 주셔서 감사드립니다!