[사다리 게임] 이지 미션 제출합니다.
woowacourse/java-ladder pull request #3
Opened 2019-05-15 12:46 UTC by skygl

2019-05-15 21:50 UTC, pobiconan requested changes
전체적인 객체 설계와 객체에 대한 단위 테스트 구현 💯 
객체 설계가 지금도 좋지만 객체지향의 맛을 좀 더 깊이 있게 느껴보기 위해 좀 더 작은 단위의 객체를 추출해 보면 좋겠네요.

2019-05-15 21:50 UTC, pobiconan commented on src/main/java/calculator/Calculator.java
> +        List<Integer> nums = split(s);
숫자 값 하나를 Positive와 같은 객체로 추상화해 구현해 본다.

2019-05-15 21:50 UTC, pobiconan commented on src/main/java/ladder/controller/LadderGame.java
> +
불필요한 공백 라인

2019-05-15 21:50 UTC, pobiconan commented on src/main/java/ladder/domain/Player.java
> +        this.name = name.trim();
name이 null에 대한 체크도 추가하는 것이 어떨까?

2019-05-15 21:50 UTC, pobiconan commented on src/main/java/ladder/domain/Player.java
> +        this.position = position;
position 값에 대한 유효성 체크는 하지 않아도 괜찮은가?

2019-05-15 21:50 UTC, pobiconan commented on src/main/java/ladder/domain/Player.java
> +        position += line.getDirection(position).getValue();
상태를 가지는 객체의 데이터를 꺼내려(get)하지 말고 객체에 메시지를 보내라는 원칙에 따라 구현할 수 없을까?

2019-05-15 21:50 UTC, pobiconan commented on src/main/java/ladder/domain/Line.java
> +    Direction getDirection(int position) {
`int move(int position)`과 같은 구조로 구현하는 것은 어떨까?

2019-05-15 21:50 UTC, pobiconan commented on src/main/java/ladder/domain/Line.java
> +        return Collections.indexOfSubList(points, Arrays.asList(true, true)) != -1;
`true, true`, `true, false`와 같이 2개의 값이 쌍으로 구현되는 경우가 많다.
이 2개의 값을 가지는 객체를 추가해 구현할 경우 현재의 구현이 어떻게 달라질까?

2019-05-15 21:50 UTC, pobiconan commented on src/main/java/ladder/domain/Line.java
> +        if (position != points.size() && points.get(position)) {
Collection에서 값을 꺼내는 구조로 구현하다보니 예외 처리등의 작업을 계속해야 한다.
if 조건절도 좀 더 깔끔하게 구현하면서 이 역할을 담당하는 객체를 추가함으로써 객체지향적인 구현이 가능하도록 구현해보면 어떨까?

2019-05-15 21:50 UTC, pobiconan commented on src/main/java/ladder/domain/Line.java
> +        if (isConsecutive()) {
값 할당보다 예외 처리를 먼저 하는 것이 좋지 않을까?

2019-05-15 21:50 UTC, pobiconan commented on src/main/java/ladder/controller/LadderGame.java
> +public class LadderGame {
사다리 타기를 실행하는 엔진 부분과 엔진의 실행 결과를 활용해 결과를 출력하는 부분을 분리해보면 어떨까?
즉, Ladder가 Player와 Reward의 의존관계를 완전히 분리할 수는 없을까?

2019-05-20 08:22 UTC, skygl commented
Player나 Reward, 그리고 결과값에 대해서 작게 클래스로 분리했고, Line이 저장하는 Boolean을 쌍으로 저장하도록 클래스를 만들어서 저장및 방향을 판단할 수 있도록 구현했습니다.
피드백을 받고 다시 구현하면서 세가지 궁금한 점이 있는데,
1. 출력을 담당하는 View (여기서는 OutputView.class) 에서 출력을 할 때 Player나 Reward와 같은 클래스를 직접 전달하는 것과 새로 DTO를 만들어서 전달하는 것 중 어떤게 더 낫나요?
2. Player와 Reward, Players와 Rewards는 서로 저장하는 데이터의 타입이나 유효성이 비슷한데, 제너릭을 사용하는 것과 비교했을 때 어떤 쪽이 더 나을까요?
3. List에 대해 final을 사용했을 때 set 함수와 같이 내용을 변경하는 것을 가능한데, 이게 가능해도 되는 건가요? 아니면 Collections.unmodifiableList와 같이 내용 변경도 불가능하게 만들어 주는 것이 좋나요??

2019-05-21 00:04 UTC, pobiconan commented
@skygl 
1. 상태를 변경하는 로직이 있는 객체는 DTO로 생성하는 것이 나을 것 같고요.
그렇지 않은 경우라면 바로 전달해도 된다고 생각해요.

2. 그 부분에 정답이 있을까요? generic을 통해 중복을 제거할 수도 있고, 별도의 클래스로 분리해도 되고요.
generic으로 도전해보고 본인이 판단했을 때 좋다고 생각하는 방향을 정하면 되지 않을까요?

3. List를 객체 외부에 노출한다면 Collections.unmodifiableList로 값을 변경 불가능하도록 구현할 것을 추천해요.

2019-05-21 00:09 UTC, pobiconan requested changes
전체적으로 코드 깔끔하게 구현 잘 했네요. 💯 
tuple과 generic 적용한 부분도 좋고요.
지금 상태보다 한 단계 개선할 점이 있는지 생각해보기 위해 피드백 하나 남겼어요. 
개선할 부분이 없으면 개선하지 않아도 되요.

2019-05-21 00:09 UTC, pobiconan commented on src/main/java/ladder/domain/Direction.java
> +        if (tuple.canMoveRight())
👍

2019-05-21 00:09 UTC, pobiconan commented on src/main/java/ladder/controller/LadderGameApplication.java
> +    public static void start() {
main() 메소드로 구현해도 되지 않을까?

2019-05-21 00:09 UTC, pobiconan commented on src/main/java/ladder/controller/LadderGameApplication.java
> +    public static void start() {
사다리 타기의 전체 흐름을 다음과 같은 구조로 구현해 보는 것은 어떨까?
main()은 MVC에서 Controller의 역할로 가능한 가볍게 구현해야 한다.
Controller 내에는 로직은 최대한 배제하고 Model과 View 사이의 연결 역할만 하도록 구현한다.

```java
public static void main(String[] args) throws Exception {
    Players players = InputView.createPlayers();
    Rewards rewards = InputView.createRewards();

    Ladder ladder = LadderFactory.createLadder(players.countOfPeople(), InputView.getHeight());
    OutputView.printLadder(players, ladder, rewards);

    MatchingResult matchingResult = ladder.play();
    LadderResult result = matchingResult.map(players, rewards);

    OutputView.printResult(result);
}
```

MatchingResult는 Map<Integer, Integer>에 대한 일급콜렉션 객체이다.
Map의 key는 시작 위치, values는 사다리를 실행한 결과 위치이다.

LadderResult는 위치 값만 가지고 있는 MatchingResult의 값을 이름과 결과로 매핑한 결과를 가지는 일급콜렉션 객체이다.

반드시 위와 같은 구조로 개발하지 않아도 된다.
단, 위 코드 힌트를 참고해 개선할 부분이 있으면 개선해 본다.

2019-05-27 01:51 UTC, pobiconan approved these changes
한 주가 늦어 끝났지만 전체적인 코드 품질은 많이 좋아졌네요. 💯 
사다리타기 미션 진행하느라 수고했어요.

2019-05-27 01:51 UTC, merged