[사다리 게임] 올레 미션 제출합니다.
woowacourse/java-ladder pull request #30
Opened 2019-05-17 11:26 UTC by jinwookh

2019-05-19 07:16 UTC, phs1116 requested changes
안녕하세요. 리뷰어 화투입니다.
전체적으로 테스트도 잘 작성하시고 구현에도 고민을 많이 하신 것 같아요. 👍 
다만 너무 도메인 로직이 응집도가 많이 떨어지는 것 같아요 같아요.
사다리 게임이라는 도메인에 대해서 결과를 구하는 부분은 OutputView가 가지고 있고,
그림을 그리는 부분과 결과를 구하는 부분이 main이 책임지고 있는 등 
특정 도메인이 자신의 책임에 맡게 다 가지고 있도록 수정해보면 좋을 것 같아요.
피드백 몇가지 추가했는데 참고 부탁드리구요. 궁금하신 점 있으시면 연락주세요!

2019-05-19 07:16 UTC, phs1116 commented on src/main/java/ladderGame/controller/LadderGame.java
> +    public static void main(String[] args) {
LadderGame가 generateDrawnLadder, showResultUntilUserQuits 두개의 책임을 모두 들고있지 않아도 될 것 같아요 :)
LadderGame은 각 객체를 파사드 해주는 역할만 가지고 나머지 로직들은 다 책임에 맡게 넘기는건 어떨까요?

2019-05-19 07:16 UTC, phs1116 commented on src/main/java/ladderGame/controller/LadderGame.java
> +        if (name.equals("all")) {
all,quit같은 값은 상수로 분리하는게 좋을 것 같습니다. :)

2019-05-19 07:16 UTC, phs1116 commented on src/main/java/ladderGame/dto/DrawnLadder.java
> +    public boolean equals(Object o) {
equals, hashCode 같은 코드는 가장 아래에 두는게 좋아요 :)

2019-05-19 07:16 UTC, phs1116 commented on src/main/java/ladderGame/model/input/PlayerNamesInput.java
> +        if (nameLength > 5 || nameLength < 1) {
매직넘버는 상수로 빼주세요 :)

2019-05-19 07:16 UTC, phs1116 commented on src/main/java/ladderGame/model/input/PlayerNamesInput.java
> +            throw new Exception("중복된 이름이 존재합니다.");
예외를 던질땐 최상위 예외인 Exception이 아닌 조금 더 구체화된 예외로 던져주는게 좋아요. :)

2019-05-19 07:16 UTC, phs1116 commented on src/main/java/ladderGame/view/OutputView.java
> +        int startPoint = playerNamesInput.getNames().indexOf(name);
어느 사용자가 어떤 상품을 받았는지에 대한 비즈니스 로직이 OutputView에 녹아있는 것 같아요.
LadderNavigator라는 객체도 그렇구요.
OutputView는 출력만을 위한 로직을 수행하고 도메인에서 사다리타기 게임의 결과를 구하도록 해보는건 어떨까요?

2019-05-19 07:16 UTC, phs1116 commented on src/main/java/ladderGame/model/input/ResultsInput.java
> +    private final List<String> results;
String이 아니라 Result나 Reward라는 객체로 만들고, 여기서 스스로 생성시 checkLength 하면 어떨까요?

2019-05-19 07:16 UTC, phs1116 commented on src/main/java/ladderGame/model/input/ResultsInput.java
> +    private final List<String> results;
String이 아니라 Result나 Reward라는 객체로 만들고, 여기서 스스로 생성시 checkLength 하면 어떨까요?

2019-05-19 07:16 UTC, phs1116 commented on src/main/java/ladderGame/model/ladder/LadderDrawer.java
> +    private final Random rand = new Random();
Random이라는 객체에 너무 강하게 의존하고 있는 것 같습니다.
그릴지 말지를 판단해주는 인터페이스를 만들고 약하게 의존을 가져가면 어떨까요?

2019-05-19 07:16 UTC, phs1116 commented on src/main/java/ladderGame/model/ladder/LadderDrawer.java
> +    public void draw(Ladder ladder, int numToDraw) {
요구사항과 구현이 다른 것 같아요. :)
요구사항은 선을 그을 갯수를 입력받는게 아닌 계층만 입력받고 선 갯수는 랜덤으로 생성되는데
현재는 로우 갯수만큼만 생성되는 것 같네요!

2019-05-19 07:16 UTC, phs1116 commented on src/main/java/ladderGame/dto/DrawnLadderRow.java
> +public class DrawnLadderRow {
Ladder, DrawnLadder, LadderRow, DrawnLadderRow 이렇게 두개씩 나눠진 이유가 잘 이해가 가질 않네요. :)
생성자든, 팩토리든 처음부터 그려진 사다리가 생성이 안되는 이유가 있을까요?

2019-05-20 06:39 UTC, jinwookh commented on src/main/java/ladderGame/controller/LadderGame.java
> +    public static void main(String[] args) {
넵 좀 더 고민해보겠습니다!

2019-05-20 07:59 UTC, jinwookh commented on src/main/java/ladderGame/model/ladder/LadderDrawer.java
> +    public void draw(Ladder ladder, int numToDraw) {
선 위치만 랜덤인 줄 알았습니다. 선 개수를 자의적으로 조정해서 보기 좋은 사다리를 만들려고 했습니다. 선 개수까지 랜덤 수를 받도록 수정할게요!

2019-05-20 11:13 UTC, jinwookh commented on src/main/java/ladderGame/model/input/PlayerNamesInput.java
> +            throw new Exception("중복된 이름이 존재합니다.");
피드백 감사합니다. 만약 위 상황에서 Exception이 아니라 구체화된 예외로 던진다면, 받는 메서드에서 개별적 Exception마다 따로 처리해야 하는 건가요?
위 상황에서는 NullPointerException, IllegalArgumentException이 나올 수 있습니다. 저는 개별적인 처리가 필요하지 않고, 예외는 동일하게 처리할 수 있다고 판단해서 Exception을 던졌습니다.

2019-05-20 12:11 UTC, jinwookh commented on src/main/java/ladderGame/dto/DrawnLadderRow.java
> +public class DrawnLadderRow {
처음부터 그려진 사다리를 생성하면,  Ladder class에서 사다리의 다리를 랜덤으로 그리는 역할까지 맡게 됩니다. 그렇게 하기보다 LadderFactory와 같은 class에 사다리를 그리는 역할을 맡도록 분산하는게 낫지 않을까요? 저도 명확한 기준을 모르기에, 화투님의 의견이 궁금합니다.

2019-05-23 13:45 UTC, jinwookh commented on src/main/java/ladderGame/controller/LadderGame.java
> +    public static void main(String[] args) {
Ladder를 그리고 생성하는 역할은 LadderFactory로 넘겼습니다.

2019-05-23 13:45 UTC, jinwookh commented on src/main/java/ladderGame/controller/LadderGame.java
> +        if (name.equals("all")) {
넵 지적 감사합니다!

2019-05-23 13:52 UTC, jinwookh commented on src/main/java/ladderGame/dto/DrawnLadder.java
> +    public boolean equals(Object o) {
넵!

2019-05-23 13:52 UTC, jinwookh commented on src/main/java/ladderGame/model/input/PlayerNamesInput.java
> +        if (nameLength > 5 || nameLength < 1) {
넵 상수처리했습니다.

2019-05-23 13:54 UTC, jinwookh commented on src/main/java/ladderGame/view/OutputView.java
> +        int startPoint = playerNamesInput.getNames().indexOf(name);
결과를 구하는 로직을 분리하여, OutputView에 결과 맵을 전달하는 방식으로 처리했습니다.

2019-05-23 13:55 UTC, jinwookh commented on src/main/java/ladderGame/model/input/ResultsInput.java
> +    private final List<String> results;
Result 객체를 생성하는 것으로 수정했어요!

2019-05-23 13:57 UTC, jinwookh commented on src/main/java/ladderGame/model/ladder/LadderDrawer.java
> +    private final Random rand = new Random();
화투님 말씀은 new 생성자를 쓰지 말라는 말씀이신가요?
현재 Math.random()을 쓰는 방식으로 수정했습니다.
의존성과 인터페이스 부분에 관하여 팁을 하나 더 주시면 감사하겠습니다!

2019-05-23 13:59 UTC, jinwookh commented on src/main/java/ladderGame/dto/DrawnLadderRow.java
> +public class DrawnLadderRow {
DrawnLadder 클래스가 개념적으로 혼란을 주는 것 같아서, 삭제했습니다. 그리고 화투님이 말씀하신대로 클래스 간 결합도를 낮추고 클래스 내 응집도를 높이려고 노력했습니다. 세심한 리뷰 한 번 더 요청드립니다!

2019-05-23 14:06 UTC, jinwookh commented on src/main/java/ladderGame/view/OutputView.java
> +        int startPoint = playerNamesInput.getNames().indexOf(name);
또한 InputView도 역할을 수정했습니다. 기존 InputView에서는 도메인 객체에 대한 예외를 검사하고 있었습니다.
기존에 InputView에서 도메인 객체 예외를 검사한 까닭은(예: 이름 길이 검사), 만약 예외가 생기면 사용자에게 다시 묻기 위함이었습니다. 하지만 InputView 는 입력을 전달하는 최소한의 역할만 해야 한다는 생각이 들었습니다. 그래서 사용자에게 다시 묻는 기능을 포기하고 도메인 예외 검사 로직을 InputView에서 빼고 다른 곳으로 옮겼습니다. 
여기에 대해서 화투님은 어떻게 생각하시는지 궁금합니다!

2019-05-23 16:01 UTC, phs1116 requested changes
안녕하세요. 리뷰어 화투입니다. 
피드백 반영을 위해 고민 많이하신것 같아요. :)
많이 고민한 흔적이 보여요!!
다만 몇가지 더 개선 할 수 있을 것 같아서 피드백 추가했어요.
한번 확인 부탁드리고 궁금한 점 있으시면 연락주세요!

2019-05-23 16:01 UTC, phs1116 commented on src/main/java/ladderGame/model/ladder/Point.java
> +    public void setTrue() {
Point형이 Boolean형이 아니라 setTrue라는 메서드명은 적합하지 않은 것 같습니다. :)

2019-05-23 16:01 UTC, phs1116 commented on src/main/java/ladderGame/model/ladder/Row.java
> +        points.get(column).setTrue();
setTrue같은 세터 메서드를 쓰지 않고 사다리를 그리는 방법은 없을까요?

2019-05-23 16:01 UTC, phs1116 commented on src/main/java/ladderGame/model/ladder/Row.java
> +    public boolean getPoint(int column) {
getPoint는 자바 컨벤션상 Point에 대한 getter 메서드로 보이는데 boolean이라는 명칭은 적합하지 않은 것 같아요. :)

2019-05-23 16:01 UTC, phs1116 commented on src/main/java/ladderGame/model/ladder/LadderFactory.java
> +        while (ladder.getTruePointNumber() < randomNum) {
사다리를 그리는 책임은 모두 생성자가 가질 수 있지 않을까요?
현재 ladder.draw 메서드는 결국 하나의 set 메서드에요. 
외부에서 내부 상태를 변경 할 수 있어서 어떤 사이드 이펙트가 발생할 지 몰라요. 
최대한 내부 상태를 다른 곳으로 변경할 수 없도록 해보시면 좋을 것 같아요. :)

2019-05-23 16:01 UTC, phs1116 commented on src/main/java/ladderGame/model/ladder/LadderFactory.java
> +            int randomRowNumber = (int) (Math.random() * rows);
그리고 현재 이 Factory는 너무 random에 의존적이에요. LadderFactory가 사다리를 제대로 생성을 하는지 테스트도 힘들어 보여요.
LadderFactory 테스트 코드를 짜보시는걸 추천드릴게요.

조금 더 팁을 드리자면 현재 선을 그을것인지 말것인지를 판단하는 객체를 생성자나 값으로 주입 받아 사용하는 방법이 있을거에요.
랜덤으로 돌려주는 객체를 주입받으면 사다리가 랜덤으로 생성될 것이고, 정해진 값을 돌려주는 객체를 만들면 원하는 모양의 사다리를 만들수도 있겠죠??

어떤 랜덤 row,column에 선을 그을지 말지로 작성하시면 테스트를 구현하시기 엄청 힘드실 것 같아요. 어떻게하면 사다리를 생성하는 것에 대한 테스트를 쉽게 할 수 있을지 고민 같이 해보세요. :)

2019-05-23 16:01 UTC, phs1116 commented on src/main/java/ladderGame/model/ladder/Point.java
> +    private boolean drawn;
각 라인 대한 Point는 항상 있겠죠.
직전 점이 그렸는지 안그렸는지는 사다리를 생성할때만 신경쓰고,
이동 할 때는 직전 객체 등 다른 객체에는 관심이 없고 현재 객체를 통해서만 파악 할 수 있지 않을까요?
예를들면 nextPosition이 LEFT, RIGTH, STOP등으로도 표현 가능 하겠네요. :)

2019-05-23 16:01 UTC, phs1116 commented on src/main/java/ladderGame/model/ladder/Row.java
> +        if (startIndex > 0 && points.get(startIndex - 1).isTrue()) {
Point 객체가 바로 -1로 이동할지 +1이동할지 돌려줄 수 있다면 이 로직도 상당히 간단해 질 것 같아요. :)

2019-06-05 09:54 UTC, jinwookh commented
안녕하세요, 화투 리뷰어님.
1. 피드백 해주신대로 사다리 클래스 내부에서 다리가 랜덤으로 그려진 상태로 완성되도록 구현했습니다. 그리고 랜덤으로 위치와 다리 개수를 정하는 부분을 RandomBridgeGenerator class로 따로 추출했습니다.
테스트할 때는 Mockito를 사용해서 RandomBridgeGenerator를 mock으로 대체했습니다.
제가 Mockito를 알맞게 사용하고 있는지 확인해주시면 감사하겠습니다!

2. 화투님이 Point에 left, right, straight 등의 정보를 담게 하고, boolean을 담게 하지 않도록 하라고 피드백을 남겼는데, 그 부분은 아직 구현하지 않았습니다. 다만 Point라는 객체가 담고 있는 의미가 불명확한 것 같아, Point 클래스의 이름을 BridgePoint라는 클래스명으로 바꿨습니다. BridgePoint 는 사다리 사이사이의 다리를 의미합니다. BridgePoint 가 true를 담고 있으면 다리가 있다는 의미이고, false를 담고 있으면 다리가 존재하지 않는다는 의미입니다. 이렇게 구현하면 연속한 다리를 만들지 못하게 하는 로직을 간단히 하는 장점이 있다고 생각합니다.
위 로직에 대한 화투님의 의견이 궁금합니다.

2번에서 얘기했듯이, 아직 피드백을 반영하지 않은 부분이 있습니다. 진행하기에 앞서 화투님의 의견을 듣고 싶어 리뷰요청을 먼저 보냅니다. 피드백 주시면 다시 반영하도록 하겠습니다! 감사합니다.

2019-06-08 10:03 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다.
피드백 반영하느라 고민 많이하신 흔적이 보이시네요 👍 
mockito를 활용하고자 하는 부분은 좋았으나 아직 mockito 까지는 하지 않아도 될 것 같아요.
그리고 사다리 선을 제네레이팅 하는 부분에 대해서는 조금 더 추상화를 해보면 좋을 것 같아
피드백 남겨드렸습니다. 참고 부탁드릴게요!

2019-06-08 10:03 UTC, phs1116 commented on src/main/java/ladderGame/model/ladder/BridgePoint.java
> +    public boolean isTrue() {
isTrue보다는 isDrawn이 더 적합하지 않을까요? :)

2019-06-08 10:03 UTC, phs1116 commented on src/main/java/ladderGame/model/ladder/BridgePoint.java
> +    public void setTrue() {
아래와 마찬가지로 set보다는 draw가 객체의 역할에 더 맞는 것 같습니다.
setTrue면  True라는 필드에 특정 값을 셋팅한다는 의미로도 보이거든요!

2019-06-08 10:03 UTC, phs1116 commented on src/test/java/ladderGame/model/ladder/LadderTest.java
> +        when(randomBridgeGenerator.generateRandomBridgeCount()).thenReturn(1);
이번 과제에선 mockito까지 굳이 사용하지 않아도 될 것 같습니다.
익명클래스나 테스트용 클래스를 사용해서 테스트해보면 어떨까요?

2019-06-08 10:03 UTC, phs1116 commented on src/main/java/ladderGame/model/ladder/RandomBridgeGenerator.java
> +public class RandomBridgeGenerator {
RandomBridgeGenerator를 BridgeGenerator라는 인터페이스를 선언하는게 더 좋지 않을까요?
아직도 랜덤으로 다리를 생성한다는 객체에 강하게 의존하고 있는 것 같아요.
테스트 시에는 TestBridgeGenerator 혹은 익명 클래스를 주입받고
실제 사용에는 BridgeGenerator를 구현한 RandomBridgeGenerator를 주입받도록 하면 어떨까요?

2019-06-08 10:03 UTC, phs1116 commented on src/main/java/ladderGame/model/ladder/BridgePoint.java
> +    private boolean drawn;
다시 수정하기엔 어렵겠지만 BridgePoint 상태 또한 불변하게 관리하도록 도전해보는것도 좋을 것 같습니다. :)

2019-06-09 01:46 UTC, jinwookh commented
안녕하세요, 리뷰어 화투님.
두 가지 부분을 수정했습니다.
1. Bridge 클래스를 삭제하고, Point 와 Direction 클래스를 추가했습니다.
Bridge 대신 Point 개념(사용자 위치)을 추가하여 Point가 Direction(오른쪽, 왼쪽, straight)을 포함하도록 구현했습니다.

2. Mock을 사용하지 않고 인터페이스를 통해 테스트 클래스를 구현했습니다.
랜덤으로 다리의 위치를 생성하지 않고, 랜덤으로 포인트의 Direction을 생성하도록 구현했습니다. DirectionGenerator 인터페이스를 만들어, 랜덤으로 Direction으로 생성하는 클래스와 특정 방향만 생성하는 테스트 클래스를 만들었습니다.
위와 같이 구현한 결과, Point를 생성 시에 Direction을 랜덤으로 정할 수 있어 Point의 Direction 상태를 불변으로 관리할 수 있었습니다.

읽어주셔서 감사합니다!

2019-06-09 15:26 UTC, phs1116 approved these changes
안녕하세요! 리뷰어 화투입니다.
전체적으로 상당히 많은 수정이 일어난 것 같네요.
정말 고생 많으셨습니다.
과제 머지할게요. 개발 하시느라 정말 수고 많으셨어요!!!

2019-06-09 15:27 UTC, merged

2019-06-10 01:30 UTC, jinwookh commented
> 안녕하세요! 리뷰어 화투입니다.
> 전체적으로 상당히 많은 수정이 일어난 것 같네요.
> 정말 고생 많으셨습니다.
> 과제 머지할게요. 개발 하시느라 정말 수고 많으셨어요!!!

그 동안 세심한 리뷰 감사드립니다!