[1단계 - 사다리 생성] 폭포(이성주) 미션 제출합니다.
woowacourse/java-ladder pull request #301
Opened 2024-02-22 08:08 UTC by BurningFalls

안녕하세요 폭포(이성주) 입니다. 사다리 미션 구현 완료하여 PR 보냅니다.

전체적인 구현 로직은 다음과 같습니다.

* `LadderController`에서 `ladderPlayers`와 `ladderSize`를 입력받기
* 입력값을 이용하여 `ladder` 생성 
* `ladder`는 `List<List<LadderPath>>` 구조로 생성 (`List<LadderPath>` -> `Line`)
* `LadderPath`가 `RIGHT`이면 해당 위치에서 오른쪽으로 경로가 연결되어 있음. `LadderPath`가 `LEFT`이면 해당 위치에서 왼쪽으로 경로가 연결되어 있음.
* 생성한 `ladder`를 출력
* 출력할때는 `List<Line>`을 `List<LineDto>`로 바꾸어 `LadderController`에서 `OutputView`로 전달
* `List<LineDto>`는 `LineStringFormatter`를 이용하여 출력

리뷰 부탁드립니다. 감사합니다.

2024-02-22 11:56 UTC, yxxnghwan requested changes
안녕하세요 폭포! 이번 미션 리뷰하게된 알렉스입니다😁

미션 잘 구현해주셨네요! 생각해볼만한 부분 코멘트 몇개 남겼습니다.
확인해주시고 이해가 안가는 코멘트나 질문이 있다면 언제든 DM 주셔도 좋습니다.💪

2024-02-22 11:56 UTC, yxxnghwan commented on src/main/java/ladder/Application.java
> +    public static void main(String[] args) throws IOException {
IOException이 View부터 시작해서 main메소드까지 throws하고 있네요! 입출력과 관련된 예외인데 입출력 관리하는 클래스에서 처리함은 어떠신가요?

2024-02-22 11:56 UTC, yxxnghwan commented on src/main/java/ladder/Application.java
> +        ladderController.printResult();
다른 입출력 로직은 `ladderController.init()`에 들어가 있는데, 이 메소드만 따로 존재하는 이유가 있을까요?
만약 이 로직도 init() 메소드 안으로 넣는다면 init이란 네이밍도 어색해질 것 같은데 좋은 이름 고민해보면 좋을 것 같아요🙂

2024-02-22 11:56 UTC, yxxnghwan commented on src/main/java/ladder/model/LadderSize.java
> +        if (!isNaturalNumber(height) || !isNaturalNumber(width)) {
메소드에 !를 붙여서 사용하고 있는데 메소드 자체를 Not등을 붙여 부정형으로 만드는건 어떠실까요?

2024-02-22 11:56 UTC, yxxnghwan commented on src/main/java/ladder/model/Ladder.java
> +    }
dto는 UI에 맞도록 만들어질 것 같은데, UI가 변경되면 dto도같이 변경되겠네요!
Ladder가 dto를 알고 있으면 UI가 변경될 때 ladder도 변경이 일어날 수 있지 않을까요?

2024-02-22 11:56 UTC, yxxnghwan commented on src/main/java/ladder/dto/LineDto.java
> +                .mapToObj(idx -> row.get(idx).equals(LadderPath.RIGHT))
LadderPath에 넣을 수 있어보이네요! 메소드 이름으로 의미도 더 잘 전달해줄 수 있을 것 같아요!

2024-02-22 11:56 UTC, yxxnghwan commented on src/test/java/ladder/model/LadderSizeTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
에러 메시지도 같이 검증하면 어떨까요?

2024-02-22 11:56 UTC, yxxnghwan commented on src/main/java/ladder/controller/LadderController.java
> +    }
메소드를 단순하게 연결만 하고 있는데 꼭 필요한 메소드 정의인가요?

2024-02-22 11:56 UTC, yxxnghwan commented on src/main/java/ladder/model/Line.java
> +                .filter(i -> row.get(i).equals(RIGHT))
객체에서 꺼내서 값을 보는 것보단 객체한테 물어보는 방식으로 하면 어떨까요?

2024-02-22 11:56 UTC, yxxnghwan commented on src/main/java/ladder/view/OutputView.java
> +            sb.append(LineStringFormatter.create(ld));
변수명에 약어를 쓰는 것보단 차라리 lineDto 라고 쓰면 어떨까요? 개인적으로 ld라는 네이밍을 보고 LineDto타입이라고 떠오르진 않았어요!

2024-02-22 11:56 UTC, yxxnghwan commented on src/test/java/ladder/model/PlayerTest.java
> +    }
두 테스트 케이스 하나로 합칠 수 있을 것 같아요! `@ParameterizedTest`에 대해서 알아볼까요?

2024-02-22 11:56 UTC, yxxnghwan commented on src/test/java/ladder/model/PlayerTest.java
> +    }
그리고 생성에 성공하는 테스트도 있으면 좋을 것 같아요!

2024-02-22 13:03 UTC, BurningFalls commented on src/main/java/ladder/Application.java
> +    public static void main(String[] args) throws IOException {
입력에 대한 예외를 처리하는 기능은 `InputView` 클래스에서 다뤄야할 역할이자 책임인 것 같네요. 밖으로 예외를 전달하지 않고 바로 `IOException`을 처리하도록 바꾸었습니다.

2024-02-22 13:12 UTC, BurningFalls commented on src/main/java/ladder/Application.java
> +        ladderController.printResult();
원래 의도는 `init`에서 사다리의 값을 초기화하고 `printResult`에서 사다리를 초기화하는 것이었습니다. 하지만 다시 생각해보니 전체적으로 메서드 네이밍이 어색하네요. 아래와 같이 바꾸어보았습니다.

* `makeLadder`: 사용자에게 입력을 받아 사다리를 생성
* `showLadder`: 사다리를 출력

사용자에게 입력을 받는 부분과 사다리를 생성하는 부분도 분리해야하는가에 대해 고민해보았습니다. 만약 그렇게 하면 `makeLadder` 메서드를 둘로 분리시키는 과정에서 `ladderSize` 변수를 파라미터로 전달하거나 인스턴스 변수로 선언해야하는 문제가 생겨버립니다. 따라서 굳이 분리시키지 않았습니다.

2024-02-22 13:17 UTC, BurningFalls commented on src/main/java/ladder/model/LadderSize.java
> +        if (!isNaturalNumber(height) || !isNaturalNumber(width)) {
`!`가 붙으면 코드를 읽는 사람이 해당 라인의 동작을 한번 더 역전시켜 생각해봐야 하는 단점이 존재하네요. 메서드 이름만으로 해당 라인의 의도를 명확하게 표시하는 것이 중요하다는 것을 복기할 수 있었습니다.

2024-02-22 13:46 UTC, BurningFalls commented on src/main/java/ladder/dto/LineDto.java
> +                .mapToObj(idx -> row.get(idx).equals(LadderPath.RIGHT))
`LadderPath.RIGHT`인지 확인하는 기능이기 때문에, `LadderPath` enum 클래스에 `isRightPath` 함수로 만들어서 사용할 수 있었네요. 객체에 대해 어떤 작업을 수행할때는 해당 작업을 객체가 해당하는 클래스의 메서드로 만들어 사용해서 가시성을 높일 수 있는지 체크하면서 구현해야할 것 같습니다.

2024-02-22 14:39 UTC, BurningFalls commented on src/test/java/ladder/model/LadderSizeTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
한 클래스의 `validate`에서 여러 종류의 에러가 발생한다면, 생성자 생성에 실패했을때 정확히 어떤 에러가 발생해서 `IllegalArgumentException`이 발생한지 알수 없다는 사실을 알게 되었습니다.

`LadderSizeTest` 뿐만 아니라, 여러 조건을 검사하는 `LineTest`, `PlayerTest`에도 `hasMessage`를 통해 에러 메시지를 검증했습니다.

2024-02-22 14:47 UTC, BurningFalls commented on src/main/java/ladder/controller/LadderController.java
> +    }
입력값을 받아서 추가로 변환 작업을 거쳐야 할 경우를 대비한 것과 너무 라인이 길어지 않기 위한 것 때문에 분리해놓았습니다. 지금으로서는 분리할 이유가 없기 때문에 다시 합쳤습니다.

2024-02-22 14:52 UTC, BurningFalls commented on src/main/java/ladder/model/Line.java
> +                .filter(i -> row.get(i).equals(RIGHT))
위에서 말씀해주셨던대로 `LadderPath`에 `isLeftPath`와 `isRightPath` 메서드를 만들어서 값을 확인했습니다.

2024-02-22 14:58 UTC, BurningFalls commented on src/main/java/ladder/view/OutputView.java
> +            sb.append(LineStringFormatter.create(ld));
리팩터링 과정에서 놓친 부분이었네요. 약어를 사용하지 않고 `lineDto`로 바꾸었습니다.

2024-02-22 15:09 UTC, BurningFalls commented on src/test/java/ladder/model/PlayerTest.java
> +    }
`@ParameterizedTest`에 대해서 인지하고 있었으나, 5보다 큰 경우와 1보다 작은 경우를 체크하는 기능을 서로 다른 기능으로 인지하고 TDD를 진행하여 이런 식으로 구현되었습니다.

* 비슷한 기능의 테스트 코드를 묶어서 양을 줄이는 것 vs 세부 기능별로 테스트 코드를 나눠서 두는 것

두 비슷한 기능을 병합할지는 코더 본인이 "비슷"에 대한 정의를 내리기 나름인가요 아니면 어떤 방법을 선택하는지에 대한 확실한 기준이 있는건가요?

2024-02-22 15:43 UTC, BurningFalls commented on src/main/java/ladder/model/Ladder.java
> +    }
저는 `UI`가 변경되면 `LineStringFormatter`가 변경되는 것이기 때문에 `dto`는 변경할 필요가 없을 것으로 예상하고 있습니다. 혹시 제가 잘못 알고 있는 부분이 있다면 자세한 설명을 부탁드려도 될까요?

2024-02-22 15:46 UTC, BurningFalls commented
안녕하세요, 빠른 리뷰 감사드립니다.

말씀해주신 부분들 인지하고 수정하였습니다. 
잘 이해가지 않는 부분, 궁금한 부분들에 대해서도 답변을 작성하였습니다.

확인해주시고 피드백 부탁드립니다! 감사합니다.

2024-02-23 13:27 UTC, yxxnghwan commented on src/main/java/ladder/Application.java
> +        ladderController.printResult();
파라미터로 전달하는 과정은 왜 문제라고 인식되었을까요?

2024-02-23 13:31 UTC, yxxnghwan commented on src/main/java/ladder/model/Ladder.java
> +    }
아하 표현을 위한 객체가 따로 존재해서 책임을 가져가는군요..!
만약 LineDto를 전달받는 곳에서 현재 존재하는 필드들 외에 추가적인 필드가 필요하다고 한다면 Ladder 클래스도 수정이 필요해질 것 같은데 이 부분 고민해보시면 좋을 것 같아요!

2024-02-23 13:35 UTC, yxxnghwan commented on src/test/java/ladder/model/PlayerTest.java
> +    }
확실한 기준은 존재하지 않습니다 🙂
각각의 방식에 따라 트레이드 오프가 있을거고 그걸 고민해서 본인만의 기준을 정립해나간다고 보시면 좋을 것 같아요.

2024-02-23 13:41 UTC, yxxnghwan approved these changes
안녕하세요 폭포! 빠르게 리뷰 반영해주셨네요!
1단계에서는 충분히 고민하신 것 같아서 2단계 넘어가도 괜찮을 것 같습니다!
사소한 코멘트 남겼는데 2단계에서 반영해주시면 될 것 같아요! 2단계도 화이팅입니다! 💪

2024-02-23 13:41 UTC, yxxnghwan commented on src/main/java/ladder/model/LadderSize.java
> +    }
한 메소드에서 height도 검증하고 width도 검증하네요! 한 메소드에서 하나의 역할만 하도록 하는건 어떠실까요?

2024-02-23 13:41 UTC, yxxnghwan commented on src/main/java/ladder/view/InputView.java
> +        }
해당 예외처리는 `br.readLine()` 때문에 필요한 것으로 보이네요!
별도의 입력받는 메소드를 분리해서 예외처리하면 어떨까요? 이 메소드 전체가 try로 묶일 필요는 없어보여서요!

2024-02-23 13:41 UTC, merged

2024-02-23 15:08 UTC, BurningFalls commented on src/main/java/ladder/Application.java
> +        ladderController.printResult();
아 제가 답변을 애매하게 적어놓은 부분이 있었네요.

메서드를 둘로 분리시키면 `ladderSize` 변수를 파라미터로 전달해야 하는데, 메서드 구현라인의 길이가 길지 않음에도 불구하고 그런 식으로 연결성이 존재하는 코드를 끊는 것은 오히려 가독성을 해친다고 생각했습니다.