[1단계 - 사다리 생성] 뽀로로(조경찬) 미션 제출합니다.
woowacourse/java-ladder pull request #319
Opened 2024-02-22 08:31 UTC by jcoding-play

2024-02-23 04:13 UTC, Hyunta requested changes
안녕하세요 뽀로로,
사다리 미션으로 만나게 되어 반갑습니다, 아서입니다 👋🏻

TDD 도 잘 진행해주셨고, 테스트 코드도 잘 짜주셨네요ㅎㅎ
메서드와 클래스도 적절히 분리해서 전반적으로 읽기 편했습니다.
관련해서 몇가지 커멘트 남겼는데 확인 부탁드립니다!

2024-02-23 04:13 UTC, Hyunta commented on src/test/java/ladder/domain/ladder/HeightTest.java
> +    }
TDD를 잘 시도하셨네요ㅎㅎ
혹시 사다리의 높이를 시작점으로 잡은 이유가 있을까요?

2024-02-23 04:13 UTC, Hyunta commented on src/test/java/ladder/domain/ladder/RungTest.java
> +        assertThat(values).contains(rung);
뽀로로는 테스트의 범위에 대한 기준을 어떻게 가져가시나요?
해당 테스트는 `Enum.values()` 에 대한 테스트처럼 보일 수도 있겠네요

2024-02-23 04:13 UTC, Hyunta commented on src/test/java/ladder/domain/ladder/LadderTest.java
>                  .isEqualTo(4);
입력한 변수 `playerCount`를 객체에서 추출한 값과 비교해줘도 되지 않을까요?

2024-02-23 04:13 UTC, Hyunta commented on src/test/java/ladder/mock/MockBooleanGenerator.java
> +}
추상화를 통한 TestDouble👍🏻👍🏻

2024-02-23 04:13 UTC, Hyunta commented on src/test/java/ladder/domain/ladder/LineTest.java
> +    }
한 눈에 테스트 내용이 들어와서 좋네요
가독성이 좋은 테스트👍🏻

2024-02-23 04:13 UTC, Hyunta commented on src/main/java/ladder/domain/ladder/Ladder.java
> +                .toList();
점진적인 리팩터링👍🏻

2024-02-23 04:13 UTC, Hyunta commented on src/main/java/ladder/controller/LadderController.java
> +        final LadderGenerator ladderGenerator = new LadderGenerator(booleanGenerator);
이 작업을 생성자에서 해주면 어떨까요?
LadderController가 `BooleanGenerator`는 `LadderGenerator` 를 생성하기 위한 수단으로만 사용되고 있기도 하고,
가독성 측면에서도 더 나아보입니다.

2024-02-23 04:13 UTC, Hyunta commented on src/main/java/ladder/controller/LadderController.java
> +    }
재시도 처리 추상화👍🏻

2024-02-23 04:13 UTC, Hyunta commented on src/main/java/ladder/domain/player/Players.java
> +    private static List<Player> createPlayers(final List<String> playerNames) {
static 선언해준 이유가 있을까요?

2024-02-23 04:13 UTC, Hyunta commented on src/main/java/ladder/domain/player/Player.java
> +    private static final Pattern NAME_VALID_FORMAT = Pattern.compile("[ㄱ-ㅎㅏ-ㅣ가-힣a-zA-Z0-9]+");
컴파일된 Pattern 사용👍🏻

2024-02-23 04:13 UTC, Hyunta commented on src/main/java/ladder/domain/ladder/LadderGenerator.java
> +        final int playerCount = players.countPlayers();
뽀로로가 해준 것처럼 players를 받는 방법과
player 갯수를 받는 방법이 있었을 것 같은데
전자를 선택한 이유가 있을까요?

2024-02-23 04:13 UTC, Hyunta commented on src/main/java/ladder/domain/ladder/LadderGenerator.java
> +        final int playerCount = players.countPlayers();
메서드에서 변수명을 굳이 반복해서 쓸 필요는 없어보여요, count 내지는 다른 용어로 바꾸는 것은 어떤가요?
```suggestion
    public Ladder generate(final Players players, final Height height) {
        final int playerCount = players.count();
```

2024-02-23 04:13 UTC, Hyunta commented on src/main/java/ladder/domain/ladder/Line.java
> +            rungs.add(rung);
두가지 고민을 해봤으면 좋겠습니다.
1. BooleanGenerator가 Rung까지 Line까지 들어올 필요가 있었을까?
2. BooleanGenerator가 False를 반환했다면 굳이 검증이 필요할까?

for 문 아래에 검증 로직이 개인적으로 복잡하다는 생각이 들어서 개선해보면 좋을 것 같습니다!

2024-02-23 04:13 UTC, Hyunta commented on src/main/java/ladder/domain/ladder/Line.java
> +        return Collections.unmodifiableList(rungs);
unmodifiableList👍🏻

2024-02-23 04:31 UTC, Hyunta commented
> 또 다른 방법으로는 단순히 Player의 클래스명을 Name으로 바꾸는 방법도 생각해보았습니다.
하지만 사다리 타기에 참여하는 참가자들이라고 생각했을 때 Name이라는 이름보다 Player라는 이름이 좋다 생각하여 이렇게 구현해보았어요!!
아서가 생각했을 때 어떤 방법이 좋다 느껴지는지 아서의 의견이 궁금해요!!

`사다리 게임` 이라는 문맥 속에서 `Name` 도 자연스럽고, `Player` 또한 자연스러운 것 같습니다. 그래서 취향의 차이인 것 같아요.
개인적으로 저는 게임안에 있는 플레이어의 속성 중에 이름을 쓰는 거야 라고 바라보는 관점이 향후 확장성을 고려해봤을 때 적절하다고 생각이 들어서 Player 쪽이 더 끌리네요. 위에서 남긴 커멘트에도 있긴 한데 `Name.getName()` 은 좋은 메서드 이름은 아니라고 생각됩니다. `Name` 이 반복되서 만약 Name 쪽으로 가면 이름에 대한 고민도 한번 해야겠네요. 저는 이런 상황에 보통 `Name.getValue()` 이런식으로 사용합니다.

> 필드값을 테스트하기 위한 좋은 방법

무분별한 getter를 줄이기 위한 시도는 좋은 시도라고 생각됩니다. 저는 `extracting` 기능을 사용해보지 않았어서 정확히 성능이 얼마나 느린지는 모르겠어요. 이 부분은 한번 뽀로로가 테스트 해봤으면 좋겠네요. RepeatedTest를 한 1000번 하고 getter를 사용할 때와 extracting 을 사용할 때 시간을 비교해보세요. 테스트 코드가 너무 많으면 build할 때도 비용이고 배포할 때마다 시간이 오래걸리는 것은 부담으로 다가올 문제라고 생각합니다. 유의미한 차이가 있다면 extracting을 사용하는 방식은 좋지 않을 것 같습니다.

> Rung 클래스 분리 & 네이밍

뽀로로가 말한 것처럼 True, False로만 놓을 수도 있지만 문맥을 모르는 상황에서 Rung EXIST, EMPTY는 되게 도움이 되는 정보라고 생각해요. 그냥 Boolean으로 줬을 떄보다 의도를 담을 수 있기 때문에 가독성 측면에서도 훨씬 좋고 이는 유지보수 비용을 줄일 수 있다고 생각합니다. 저는 가독성을 제일 중요한 가치로 생각해서 충분히 분리할만한 가치가 있다고 생각됩니다. 

개인적으로 Rung으로 의도를 충분히 드러낸다고 생각해요. (비록 저는 처음들어보는 단어라서 구글링을 해보긴했습니다😅)
현재 구조로는 Rung이 충분하지만 만약 나중에 해당 클래스에 기능이 계속 추가되면 리팩터링을 고려해볼 수 있을 것 같습니다.


> 이름에 대한 검증 로직 위치
지금 적절하게 검증을 해주고 있다고 생각합니다. 유효하지 않는 값들을 도메인에게 전달해주지 않는 취지도 좋습니다. 그러나 이름이 한글인지 영어인지 알 수 있는 것은 도메인에서 검증해줘야하는 비즈니스 로직 중 하나라는 생각이 더 강하게 듭니다.

> LadderGenerator 클래스 분리
저는 개인적으로 Ladder에서 생성자를 호출해서 사용할 것 같긴합니다. 정적 팩터리 메서드만 담고있는 로직이라 현재로서는 불필요해 보이긴해요.

2024-02-24 01:16 UTC, jcoding-play commented on src/test/java/ladder/domain/ladder/HeightTest.java
> +    }
```java
class HeightTest {

    @Test
    @DisplayName("사다리는 높이를 가진다.")
    void testConstruct() {
        Height height = new Height(1);
        assertThat(height.getHeight()).isEqualTo(1);
    }
```
처음에 작성한 테스트 코드는 다음과 같았어요!! 😀
하지만 페어와 얘기를 나눈 후 `1` 의 숫자 값도 중복이 아닐까?? 라는 의견을 나누었고, 이를 분리하여 사용하였습니다..!

근데 개인적으로 지금 생각해보니 `.isEqualTo()` 파라미터에서 사용하는 변수명이 `expected` 이니 예상되는 값인 `1`을 직접 넘겨주는 것이 옳바르다 느껴지네요!!

처음 작성했던 코드처럼 다시 수정해보았습니다!!

2024-02-24 02:11 UTC, gyungchan-jo commented on src/main/java/ladder/controller/LadderController.java
> +        final LadderGenerator ladderGenerator = new LadderGenerator(booleanGenerator);
너무 좋은 것 같아요!! 😀👍👍👍👍👍
확실히 가독성 측면에서 나아지는 것 같습니다!! 👍😍

감사합니다!! 😀

2024-02-24 02:18 UTC, jcoding-play commented on src/main/java/ladder/domain/player/Players.java
> +    private static List<Player> createPlayers(final List<String> playerNames) {
흠.... 부끄럽지만 리팩토링 과정에서 단축키를 이용하여 메서드를 분리할 때, 자동으로 `static` 이 선언된 것 같습니다.🥲🥲🥲
별다른 이유는 없었어요ㅠㅠ 

개인적으로 정적 메서드를 이용하는 것은 프로그램이 작동되는 동안 계속해서 메모리에 영향을 주기 때문에 `static` 을 사용하지 않도록 리팩토링 하였습니다!!

2024-02-24 02:49 UTC, gyungchan-jo commented on src/test/java/ladder/domain/ladder/RungTest.java
> +        assertThat(values).contains(rung);
> 뽀로로는 테스트의 범위에 대한 기준을 어떻게 가져가시나요?

아서가 물어본 질문의 의도에 맞는지 잘 모르겠지만, 저는 `README.md` 에 분리한 작은 기능 단위 별로 테스트를 진행하고 있어요!

> 해당 테스트는 Enum.values() 에 대한 테스트처럼 보일 수도 있겠네요

Rung Enum에 대한 테스트는 페어와 어떻게 테스트를 작성해야할 지 고민을 했던 것이 기억나네요ㅠㅠ 🥲 
저도 다시 보니 아서의 말대로 `Enum.values()` 에 대한 기능을 테스트하는 것 같이 느껴지는거 같아요! 🥲🥲

더 나은 테스트 코드가 있을까 고민하다가, 다음과 같이 작성해보았어요!! 🧐
```java
class RungTest {

    @Test
    @DisplayName("발판은 상태(존재한다, 존재하지 않는다)를 가진다.")
    void testRung() {
        Rung[] rungs = Rung.values();
        assertThat(rungs).containsExactly(Rung.EXIST, Rung.EMPTY);
    }
```
크게 달라진 점은 없지만ㅠㅠㅠ `containsExactly`에서 `Rung.EXIST`, `Rung.EMPTY`를 명시적으로 사용한다는 점에서 이전 테스트 코드보다 좋다 느껴졌어요!!

하지만 아직까지도 `Enum.values()`를 사용하기도 해서, 혹시 아서가 생각할 때 더 나은 방법이 있는지 궁금해요! 🧐🧐🧐

2024-02-24 02:50 UTC, gyungchan-jo commented on src/test/java/ladder/domain/ladder/LadderTest.java
>                  .isEqualTo(4);
제가 작성한 `Ladder` 클래스는 생성자에서 `playerCount`, `height`, `booleanGenerator` 를 사용하지만, 이는 `List<Line>`을 생성하는데만 필요하고 따로 `Ladder` 클래스의 멤버 변수로 사용하지 않아요!!😀
```java
public class Ladder {
    private final List<Line> lines;

    public Ladder(final int playerCount, final int height, final BooleanGenerator booleanGenerator) {
        this.lines = generateLines(playerCount, height, booleanGenerator);
    }

    private List<Line> generateLines(int playerCount, int height, BooleanGenerator booleanGenerator) {
        return Stream.generate(() -> new Line(playerCount, booleanGenerator))
                .limit(height)
                .toList();
    }

    public List<Line> getLines() {
        return Collections.unmodifiableList(lines);
    }
}
```
그래서 입력한 변수 `playerCount` 를 객체에서 추출한 값과 비교할 수 없는 것 같아요! 😀

혹시 제가 아서의 질문을 이해 못한 것일 수 있는데, 제가 잘못 이해한거라면 다시 한번 질문 부탁드립니다!! 🥲🥲🥲

2024-02-24 02:51 UTC, jcoding-play commented on src/main/java/ladder/domain/ladder/LadderGenerator.java
> +        final int playerCount = players.countPlayers();
그렇네요!! 👍👍 `countPlayers` -> `count` 로 메서드명 수정하였습니다.

---

>뽀로로가 해준 것처럼 players를 받는 방법과
player 갯수를 받는 방법이 있었을 것 같은데
전자를 선택한 이유가 있을까요?

제가 전자를 선택한 이유에 대해 2가지를 설명할 수 있을 거 같아요!! 🧐

1. 가독성
```java
public class LadderController {
    ....

    public void run() {
        final Players players = retryOnException(this::readPlayers);
        final Height height = retryOnException(this::readLadderHeight);

        final int playerCount = players.count();
        final int ladderHeight = height.getHeight();
        final Ladder ladder = ladderGenerator.generate(playerCount, ladderHeight);

        printLadder(players, ladder);
    }
```
위와 같이 아서가 말씀해준 다른 방법에 대한 코드를 작성해보았어요! 😀

이 방식도 충분히 좋다 느껴지지만, 실제적으로 `playerCount`와 `ladderHeight`를 사용하는 곳이 중복되지도 않고, 한번만 사용하므로 `controller`에서는 단순히 포장된 `Players`와 `Height`를 객체 그대로 전달하는 것이 가독성 측면에서 좋다 느껴졌어요!! 😀

2. LadderGenerator 클래스 역할
```java
public class LadderGenerator {
    ...

    public Ladder generate(final int playerCount, final int ladderHeight) {
        return new Ladder(playerCount, ladderHeight, booleanGenerator);
    }
```
`LadderGenerate`의 `generate` 메서드에서 단순히 플레이어의 수와 사다리 높이를 전달받으면, `generate` 메서드는 다음과 같이 바로 `Ladder` 클래스를 새롭게 생성하고 종료되게 됩니다.🥲
그러면, `LadderGenerator`의 역할이 더욱 크게 의미가 없어지는 것 같아 전자를 선택하였습니다!! 😀

아서가 생각했을 때, 어떤 방법이 더 좋은 거 같나요?? 🧐
아니면 더 나은 방법에 대한 아이디어가 있나요?? 아서의 생각이 궁금해요~~!! 🧐🧐🧐

2024-02-24 16:40 UTC, jcoding-play commented on src/main/java/ladder/domain/ladder/Line.java
> +            rungs.add(rung);
아서가 말해준 내용을 바탕으로 리팩토링을 진행해보았어요!! 👍

개인적으로 해당 로직에 대해 리팩토링을 해봐야겠다는 생각을 하고 있었는데, 아서의 힌트를 통해 리팩토링을 진행할 수 있었어요!! 👍👍
감사해요!! 😍

`Ladder` 객체에서 `List<Boolean>`을 생성하고 이를 `Line` 객체에서 검증하도록 구현하였습니다.
`Line` 객체는 만약 연결되어 있는 발판이 있다면, 연결된 발판들을 끊도록 리팩토링을 해보았습니다!!

변경된 로직에 대한 아서의 생각이 궁금해요!! 🧐🧐🧐

2024-02-24 17:54 UTC, jcoding-play commented
`unmodifiableList👍🏻`처럼 좋았던 부분들을 말해주시고, static을 선언한 이유를 물어봐주시는 것을 보면서 꼼꼼하게 제 코드를 봐주셨다는 느낌이 강하게 들어 너무나 감사했습니다 🥲🥲🥲🥲

아직 많이 부족하다 생각하여, 매운맛으로 피드백 주시면 더욱 열심히 해보겠습니다!! 😍

---

> Name.getName() 은 좋은 메서드 이름은 아니라고 생각됩니다. Name 이 반복되서 만약 Name 쪽으로 가면 이름에 대한 고민도 한번 해야겠네요. 저는 이런 상황에 보통 Name.getValue() 이런식으로 사용합니다.

너무나 좋은 방식인 거 같아요!! 👍👍👍 
이번 미션에서도 `Height` 객체에서 `getHeight` 라고 메서드를 사용하고 있기 때문에 이를 `getValue` 로 수정하였습니다!! 👍

---

>무분별한 getter를 줄이기 위한 시도는 좋은 시도라고 생각됩니다. 저는 extracting 기능을 사용해보지 않았어서 정확히 성능이 얼마나 느린지는 모르겠어요. 이 부분은 한번 뽀로로가 테스트 해봤으면 좋겠네요. RepeatedTest를 한 1000번 하고 getter를 사용할 때와 extracting 을 사용할 때 시간을 비교해보세요. 테스트 코드가 너무 많으면 build할 때도 비용이고 배포할 때마다 시간이 오래걸리는 것은 부담으로 다가올 문제라고 생각합니다. 유의미한 차이가 있다면 extracting을 사용하는 방식은 좋지 않을 것 같습니다.

해당 부분을 테스트하기 위해 `test` 패키지 안에 `TimeTest` 클래스를 작성하여 이를 테스트해보았습니다. 🧐
여러 번 반복하여 평균적인 속도를 비교했을 때, 유의미한 차이가 없다는 것을 깨달았어요!! 👍

그래서 개인적으로 선택한 방법은 `사다리 높이`와 같이 필드값이 같다면 동일한 객체라고 판단될 수 있는 경우 equals and hashCode를 사용!! 
`사람의 이름` 같은 경우는 중복된 사람 이름이 존재할 수 있으니 이와 같은 경우는 equals and hashCode를 사용하는 것이 아니라 extracting 메서드를 이용하여 필드값을 테스트하기로 결정해보았습니다. 😀

`TimeTest` 클래스는 아서도 제가 어떤식으로 테스트를 진행하였는지 보고, 더 좋은 테스트 방식이 있는지 물어보기 위해 추가하였어요!! 👍
다음 미션을 시작하기 전에 지우겠습니다!! 👍

---

>개인적으로 Rung으로 의도를 충분히 드러낸다고 생각해요. (비록 저는 처음들어보는 단어라서 구글링을 해보긴했습니다😅)
현재 구조로는 Rung이 충분하지만 만약 나중에 해당 클래스에 기능이 계속 추가되면 리팩터링을 고려해볼 수 있을 것 같습니다.

저도 페어와 알아보니 실제 사다리의 발판을 Rung 이라고 표현하더라고요!! 😀
그래서 저도 처음 보니 단어였지만, Rung 이라는 단어를 사용하게 되었습니다..!! 🥲🥲🥲

지금 생각해보니, 굳이 실제 단어를 사용하기보다 다른 사람들이 이해하기 쉬운 단어(예를 들면, `Bridge` or `Stick`)를 사용하는 것이 더 옳았겠다 생각이 들기도 하네요..ㅠㅠ 🥲 

좋은 의견 감사합니다!! 👍👍

---

>그러나 이름이 한글인지 영어인지 알 수 있는 것은 도메인에서 검증해줘야하는 비즈니스 로직 중 하나라는 생각이 더 강하게 듭니다.

아서의 생각이 궁금했는데, 너무 감사해요!! 👍👍👍

---

>저는 개인적으로 Ladder에서 생성자를 호출해서 사용할 것 같긴합니다. 정적 팩터리 메서드만 담고있는 로직이라 현재로서는 불필요해 보이긴해요.

저도 좀 과하다는 느낌이 들기도 하였습니다.ㅠㅠ 🥲
일단 `controller` 에서 `LadderGenerator`를 생성자에서 생성하도록 리팩토링하여 이번 미션에서는 그대로 `LadderGenerator`를 사용해보도록 하겠습니다.!! 혹시나 미션을 계속 진행하면서 `LadderGenerator` 의 역할이 부족하다 느껴지면 그땐 과감히 지우도록 할게요!! 
좋은 의견 감사해요!! 😀

2024-02-25 11:40 UTC, Hyunta commented on src/test/java/ladder/domain/ladder/RungTest.java
> +        assertThat(values).contains(rung);
`Enum.values()` 를 사용하는 것만으로 나쁘다고 했던 것은 아니고 두가지 의미를 전달하려고 했습니다.
1. `@ParameterizedTest` 와 중복되어 사용할 필요는 없다
2. `Enum.values()` 는 Java에서 제공하는 기능인데 테스트가 필요할까?

2번과 이어져서 테스트의 범위를 어떻게 잡는지 본인만의 기준이 있는지 물어보게 되었습니다ㅎㅎ
저는 너무 당연한 기능에 대해서 테스트하는 것을 지양합니다. 대표적으로 getter, size 처럼 Java에서 제공하는 메서드에 대한 테스트는 할 필요가 없다고 생각됩니다.

테스트에 목적에 대해서도 생각해볼 수 있을 것 같네요.
```
class RungTest {

    @Test
    @DisplayName("발판은 상태(존재한다, 존재하지 않는다)를 가진다.")
    void testRung() {
        Rung[] rungs = Rung.values();
        assertThat(rungs).containsExactly(Rung.EXIST, Rung.EMPTY);
    }
```
해당 테스트의 목적은 무엇일까요?
테스트를 구동하는 사람이 봤을 때 EXIST, EMPTY 라는 상태를 가지고 있다는것을 드러내기 위함일까요?
Enum이라는 열거형 타입을 이용했다는 것 부터 이미 충분히 EXIST, EMPTY 가 들어있다는 것을 파악할 수 있습니다.
이는 Java에서 비슷한 상수를 다룰 때 사용할 수 있는 틀을 제공해준 것이죠.

(꼭 수용하지 않으셔도 됩니다, 반란군이 되어보세요ㅎㅎ)
제 생각을 공유 드리면 해당 테스트를 만들지 않을 것 같아요.
우선 유지보수의 관점에서 좋아보지 않아요. 만약 Rung에 상태가 추가되면 테스트까지 수정을 해줘야합니다.
그리고 위에서 말한 것처럼 Enum은 Java에서 제공하는 기능이고 코드를 읽는 사람을 충분히 배려하고 있습니다.
따로 테스트코드가 없더라고 Rung 클래스를 통해서 어떤 역할인지 한눈에 파악할 수 있습니다.
그래서 Rung Enum의 value를 확인하는 테스트는 불필요하다고 생각해요.

2024-02-25 11:42 UTC, Hyunta commented on src/test/java/ladder/domain/ladder/LadderTest.java
>                  .isEqualTo(4);
아 제가 말을 모호하게 했네요...😅
제 말은 `.isEqualTo(4)` 를 `isEqualTo(playerCount)` 로 비교해도 되지 않을까 하는 말이었습니다.
suggestion으로 남겨드릴걸 그랬네요ㅎㅎ

2024-02-25 11:53 UTC, Hyunta commented on src/main/java/ladder/domain/ladder/LadderGenerator.java
> +        final int playerCount = players.countPlayers();
뽀로로의 생각을 들려주셔서 감사합니다, 충분히 일리있는 주장이라고 생각해요. 👍🏻
그런데 사고 확장을 위해서 반박하는 입장을 드려볼텐데 잘 고민해보시고, 
이해가 안되면 언제든지 DM 바랍니다!

1. 가독성 측면

> 실제적으로 playerCount와 ladderHeight를 사용하는 곳이 중복되지도 않고, 한번만 사용하므로 controller에서는 단순히 포장된 Players와 Height를 객체 그대로 전달하는 것이 가독성 측면에서 좋다 느껴졌어요!! 

우선 중복으로 사용하지 않고 한번만 사용하는 부분은 변수 선언을 하지 않고 값을 바로 넘겨줌으로 해결할 수 있을 것 같아요. 그럼 포장하는 비용이 들지 않습니다. 

`Players`를 전달했을 때는 외부에서는 `Ladder`가 생성될 때 `Players` 라는 객체에서 뭔가를 하는구나 하고 유추할 수 밖에 없습니다. 그런데 인원수를 count해서 넘겨주면 `아~ 사람의 인원수만 알면 되는구나` 한눈에 파악가능하죠. 그럼 가독성 측면에서도 더 좋은 거 아닐까요?

2. LadderGenerator 클래스의 역할

> 그러면, LadderGenerator의 역할이 더욱 크게 의미가 없어지는 것 같아 전자를 선택하였습니다!! 😀

그럼 더 좋은거 아닌가요? 애초에 필요없었던 객체였는데 의미 부여를 하기 위해서 더 어려운 방식을 선택할 필요는 없을 것 같은데요.
Ladder의 생성자를 바로 이용해줘서 생성할 때 거치는 객체를 줄여도 되서 더 좋을 것 같은데요?

---

혹시 몰라서 한번 더 말씀드립니다.
적용 안하셔도 됩니다! 저는 뽀로로가 작성한 방식도 마음에 들어요ㅎㅎ
단지 이런 입장이 있을수도 있는데 어떻게 지켜나갈 것인지?
본인의 생각을 고수할 것인지? 받아들일 것인지 한번 고민해보시길 바랍니다!

2024-02-25 12:00 UTC, Hyunta commented on src/main/java/ladder/domain/ladder/Line.java
> +            rungs.add(rung);
저는 변경된 로직이 가독성이 더 좋아보입니다 😁👍🏻

다만 메서드 이름을 조금 개선해보면 어떨까 싶어요

classifyRungExist -> 연속된 True or Rung 을 제거한다.
isConnected -> 연속된 값이 True or Rung 이다

이런 의미로 바꾸면 어떨까 싶네요.

2024-02-25 12:15 UTC, Hyunta approved these changes
안녕하세요 뽀로로,
열심히 리팩터링하고 학습해가는 열정이 느껴져서 보기 좋습니다!
피드백 잘 반영해주신 것 같네요.
1단계 내용에 모두 충족하는 것 같아서 이만 머지하도록 하겠습니다.
고생하셨어요👍🏻

2024-02-25 12:15 UTC, Hyunta commented on src/main/java/ladder/domain/ladder/Line.java
> +    }
위 커멘트에서 남겼는데
메서드 이름을 다시 고민해보면 좋을 것 같아요!

2024-02-25 12:15 UTC, Hyunta commented on src/test/java/ladder/domain/time/TimeTest.java
> +public class TimeTest {
이 정도로 구성했으면 충분히 테스트 속도를 검증하기에 적당한 것 같습니다.
저도 횟수를 10만건으로 늘려서 돌려봣을 때 한 40ms(0.04초) 정도 차이가 나네요.

예상했던 것보다 유의미한 차이가 없었네요ㅎㅎ
느린건 사실이었지만 저정도의 차이는 무시할 수 있을 것 같아요.

실제로 그런 통계데이터를 얻었다는 것도 중요한데, 주장에 대한 근거를 얻은게 큰 무기가 될 듯 합니다.
`Reflections 써서 extracting 쓰면 느리데` 라는 주장에 
`내가 직접 10만번씩 돌려봤는데 0.04초 정도밖에 안나던데` 라는 데이터는 반박할 때 좀 폭력적이거든요.
앞으로도 이렇게 테스트해보는 습관을 가지시면 좋을 것 같습니다💪🏻

2024-02-25 12:15 UTC, merged

2024-02-26 09:52 UTC, jcoding-play commented on src/main/java/ladder/domain/ladder/LadderGenerator.java
> +        final int playerCount = players.countPlayers();
너무 좋은 피드백인거 같아요ㅠㅠㅠ 👍👍👍
확실히 아서의 입장을 들어보니 사고 확장이 된다는 느낌이 들었어요!!! 😀

2단계를 진행하면서 끊임없이 고민하고, 더 나은 방향으로 리팩토링 해보겠습니다!! 
너무 감사해요!! 😀

2024-02-26 09:53 UTC, jcoding-play commented on src/main/java/ladder/domain/ladder/Line.java
> +            rungs.add(rung);
확실히 메서드명을 가지고 해당 메서드가 무슨 일을 하는지 정확하게 판단하기 어려운 것 같아요!! 😀
고민하고 메서드명을 수정해볼게요!! 
ㅎㅎㅎ 감사합니다!! 👍