[1단계 - 사다리 생성] 제우스(신재우) 미션 제출합니다.
woowacourse/java-ladder pull request #323
Opened 2024-02-22 08:47 UTC by zeus6768

안녕하세요 호돌! 🐯 

우테코 6기 웹 백엔드 과정의 제우스입니다. 

1단계 미션 리뷰 요청드립니다. 

이번 미션에서 처음 TDD를 경험하는 것이라 어려울 때가 많았는데, 그 과정에서 많이 배울 수 있었습니다. 

페어와 함께 고민했던 부분을 정리하여 질문드립니다! 

### 질문

#### 1. View에서 `객체를 생성하여 반환` vs `원시 타입과 Collection 등 자바에서 제공하는 자료형만을 반환`

둘 중 무엇이 더 적절한지에 대해 알고 싶습니다. 예를 들어 저와 페어는 다음과 같이 구현했습니다. 

```java
// InputView.java
public static Height inputHeight() {
    System.out.println("\n최대 사다리 높이는 몇 개인가요?");
    return new Height(Integer.parseInt(readLine()));
}
```

이렇게 구현한 이유는, 높이가 될 자연수를 입력받는 기능과 높이 객체 `Height`를 생성하는 기능은 본 프로젝트에서 항상 함께 쓰여야 하기 때문입니다. 즉, 더 이상 분리할 수 없는 기능이라고 생각했기 때문입니다. 

만약 분리한다면 클래스 `InputView`의 메서드는 항상 동일해서, 다음과 같아질 것이라고 생각합니다. 

```java
public static int inputInteger(String message) {
    return Integer.parseInt(input(message));
}

public static String input(String message) {
    System.out.printf(message);
    return readLine();
}

...
```

그러나 `InputView`가 언제 어디서든 동일하게 기능하고 어떤 프로젝트로 옮겨도 사용할 수 있게끔 자바에서 제공하는 자료형만을 반환하도록 구현해야 한다는 동료들의 주장도 있습니다. 

3. 매우 기술적으로 사용된 매직넘버도 상수로 분리해주어야 하는지에 대해 페어와 결론이 나지 않아 질문드립니다. 예를 들어 본 미션에서 저와 페어는 `LadderLevel`이라는 클래스를 만들었습니다. `LadderLevel` 객체는 가로줄이 위치할 수 있는 사다리의 한 층을 의미합니다. 이때 `LadderLevel`을 생성하고 초기화하는 과정에서 아래와 같은 코드가 생겼습니다. 여기 `size - 1`, `index + 1`과 같은 코드가 있는데 해당 연산은 가로줄이 놓일 위치를 표현하기 위한 연산으로, 코드 자체로 볼 때 의미를 이해할 수 있고 영어로는 해당 값의 의미를 표현하는데 큰 어려움이 있다고 느꼈습니다.  

```java
IntStream.range(0, size - 1).forEach(index -> setLines(lineGenerator, index));
```

```java
if (direction == RIGHT) {
    ladderLevel.set(index, RIGHT);
    ladderLevel.set(index + 1, LEFT);
}
```

2024-02-23 08:40 UTC, kimhodol requested changes
안녕하세요 제우스 👋 

사다리 1단계 미션 구현 잘 해주셨어요 👍 

코멘트 확인 부탁드릴게요 🙇 

---

> 1. View에서 객체를 생성하여 반환 vs 원시 타입과 Collection 등 자바에서 제공하는 자료형만을 반환 ?

좋은 질문인데요, 사실 정답이 없는 문제라고 생각합니다 ㅋㅋ 다만 객체를 생성해서 반환한다면 같은 입력을 받더라도 이것이 어떤 것을 위해 입력을 받는 것이고, 전후처리같은 로직들을 담을 수 있는게 장점인 것 같아요. 뷰 로직이 간소화되는 것도 좋지만, 지금 단계에서는 각각의 역할과 책임을 명확하게 하는 연습을 하는 것을 권장합니다 :)


> 2. 매우 기술적으로 사용된 매직넘버도 상수로 분리해주어야 하는지?

사람마다 다르겠지만, 개인적으로는 초기값이라던지 한도 등 어떤 도메인적 의미를 담고 있지 않는 숫자가 아니라면 저는 상수로 분리하지 않습니다 :)

2024-02-23 08:40 UTC, kimhodol commented on gradlew.bat
> +@rem Setup the command ladderLevel
[의견] 프로젝트 전체에서 단어 변환을 하다 실수가 일어난 것 같은데, 확인 부탁드릴게요.

2024-02-23 08:40 UTC, kimhodol commented on src/main/java/ladder/controller/Controller.java
> +    }
[질문] 재시도를 받는 로직은 컨트롤러가 아닌 다른 곳에서 수행을 하는 것이 자연스럽다 느끼는데, 어떻게 생각하세요?

2024-02-23 08:40 UTC, kimhodol commented on src/main/java/ladder/domain/Height.java
> +    }
👍

2024-02-23 08:40 UTC, kimhodol commented on src/main/java/ladder/domain/Ladder.java
> +    }
[의견] 사용하는 부분에서 이를 읽었을 때 `Ladder.stream`이 `Stream<LadderLevel>`을 반환하는 것은 예상치 못한 코드로 보여요. 그냥 getter로 사용하는게 어떨까요?

2024-02-23 08:40 UTC, kimhodol commented on src/main/java/ladder/domain/LadderLevel.java
> +    }
[의견] 마찬가지로 `LadderLevel.stream`이 `Stream<Direction>`을 반환하는 것은 예상치 못한 코드인것 같아요.

2024-02-23 08:40 UTC, woonjangahn commented on src/main/java/ladder/view/InputView.java
> +        return SCANNER.nextLine().replaceAll(" ", "");
[의견] 정규표현식을 사용하지 않는다면 `String.replace`를 사용하는 것이 성능상으로 이점을 가져갈 수 있어요.

2024-02-23 08:40 UTC, kimhodol commented on src/test/java/ladder/domain/LadderLevelTest.java
> +    }
[의견] `예외를 던지지 않는다`만을 검증하기보단, 클래스의 내부값들을 검증하면 어떨까요?

2024-02-23 08:40 UTC, kimhodol commented on src/test/java/ladder/domain/LadderLevelTest.java
> +    @DisplayName("가로줄 검증")
[의견] 테스트보다는 구현체에 있어야 더 자연스러운 주석인 것 같아요. 그리고 우테코에서는 되도록 주석 사용을 지양하고 더 표현력있는 코드로 설명을 하는 연습을 해보는게 어떨까요?

2024-02-23 08:40 UTC, woonjangahn commented on src/test/java/ladder/domain/LadderLevelTest.java
> +        LadderLevel ladderLevel = new LadderLevel(100, new LineGenerator());
[의견] 랜덤에 의존하는 클래스에 의존하지 않고, 이를 추상화해서 예측 가능한 객체를 만들어 테스트에 적용하면 더 좋을 것 같아요.

2024-02-23 08:40 UTC, woonjangahn commented on src/test/java/ladder/domain/LadderLevelTest.java
> +        List<Integer> expected = rightIndices.stream().mapToInt(index -> index + 1).boxed().toList();
```suggestion
        List<Integer> expected = rightIndices.stream()
            .mapToInt(index -> index + 1)
            .boxed()
            .toList();
```

[의견] 메소드 체이닝을 할 때는 되도록 줄바꿈을 해주면 조금 더 명확하게 과정을 이해할 수 있어요.

2024-02-25 06:50 UTC, zeus6768 commented on gradlew.bat
> +@rem Setup the command ladderLevel
정말 그렇네요 😭  감사합니다!!

2024-02-25 06:55 UTC, zeus6768 commented on src/main/java/ladder/domain/Ladder.java
> +    }
getter를 지양하라는 말을 듣고 이런 방법은 어떨까? 하고 사용해봤는데 제가 생각해도 getter를 사용하는 게 더 자연스러운 것 같습니다... 반영하겠습니다!

2024-02-25 06:56 UTC, zeus6768 commented on src/main/java/ladder/domain/LadderLevel.java
> +    }
마찬가지로 반영하겠습니다!

2024-02-25 07:01 UTC, zeus6768 commented on src/main/java/ladder/view/InputView.java
> +        return SCANNER.nextLine().replaceAll(" ", "");
replace와 replaceAll의 차이점에 대해 알게 되었습니다 👍 감사합니다!

2024-02-25 07:15 UTC, zeus6768 commented on src/test/java/ladder/domain/LadderLevelTest.java
> +    @DisplayName("가로줄 검증")
제가 제 코드를 어려워하며 작성한 주석인데, 생각이 짧았던 것 같습니다 😭

반영하겠습니다!

2024-02-25 07:35 UTC, zeus6768 commented on src/test/java/ladder/domain/LadderLevelTest.java
> +        LadderLevel ladderLevel = new LadderLevel(100, new LineGenerator());
좋은 의견 감사합니다! 반영하겠습니다 😄

2024-02-25 09:10 UTC, zeus6768 commented on src/test/java/ladder/domain/LadderLevelTest.java
> +    @DisplayName("가로줄 검증")
제가 구현하면서 어려운 부분을 적어놨는데, 역시 주석은 없는 게 더 좋은 것 같아요. 

반영하겠습니다!

2024-02-25 09:26 UTC, zeus6768 commented on src/main/java/ladder/controller/Controller.java
> +    }
`InputView`의 메서드를 사용하는 곳은 컨트롤러이므로, 컨트롤러에서 뷰를 다시 실행하는 게 자연스럽다고 생각해 위처럼 구현했습니다. 

호돌은 입력의 책임이 `InputView`에 있으므로 재입력도 `InputView`에서 수행하는 게 더 적절하다고 생각해서 질문주신 게 맞을까요?

그렇게 이해하고 코드를 수정해봤습니다. 확인해주시면 감사하겠습니다~!

2024-02-25 09:28 UTC, zeus6768 commented on src/test/java/ladder/domain/LadderLevelTest.java
> +    }
피드백 반영한 코드에서 `toList()` 메서드로 변환 후 크기를 검증하는 방법으로 변경해봤는데, 이런 방식으로 검증하는 것을 의미하신 게 맞을까요?

2024-02-25 09:29 UTC, zeus6768 commented on src/test/java/ladder/domain/LadderLevelTest.java
> +        List<Integer> expected = rightIndices.stream().mapToInt(index -> index + 1).boxed().toList();
좋은 의견 감사합니다 😄  반영했습니다!

2024-02-25 10:03 UTC, zeus6768 commented
리뷰 반영해서 추카 커밋 남겼습니다! 

그 과정에서 떠오른 추가 질문이 있어요. 

```java
// LadderLevelTest.java
DisplayName("가로줄로 가득 찬 사다리 층이 생성된다.")
@Test
void ladderLevelIntegrityTest() {
    LadderLevel ladderLevel = LadderLevelBuilder.builder()
            .size(100)
            .directionSelector(() -> RIGHT)
            .build();

    List<LadderDirection> ladderDirections = ladderLevel.toLadderDirectionList();

    assertThat(ladderDirections).doesNotContain(NONE);
    assertThat(ladderDirections).contains(RIGHT, LEFT);
}
```

위 코드에서, `ladderDirections` 리스트에 방향 RIGHT가`i`번째 인덱스에 존재한다면, `i+1` 인덱스에는 LEFT가 존재해야 한다는 테스트를 작성하고 싶습니다. 

반복문 안에 assertThat을 실행하는 방법을 생각해봤는데, 자연스럽지 못한 것 같습니다. 

혹시 조언을 해주실 수 있을까요?!

2024-02-26 16:55 UTC, kimhodol approved these changes
안녕하세요 제우스 👋 

코드가 많이 좋아졌네요 💯 

코멘트 확인해주시고 다음 단계에서 반영해주세요 🙇

2024-02-26 16:55 UTC, woonjangahn commented on src/main/java/ladder/domain/Ladder.java
> +                (__) -> ladder.add(LadderLevelBuilder.builder()
```suggestion
                __ -> ladder.add(LadderLevelBuilder.builder()
```

2024-02-26 16:55 UTC, kimhodol commented on src/main/java/ladder/domain/LadderLevelBuilder.java
> +        IntStream.range(0, size).forEach((__) -> ladderLevel.add(LadderDirection.NONE));
```suggestion
        IntStream.range(0, size).forEach(__ -> ladderLevel.add(LadderDirection.NONE));
```

2024-02-26 16:55 UTC, kimhodol commented on src/main/java/ladder/view/InputView.java
> +public class InputView {
[의견] `static`한 메소드로만 이루어진 유틸성 클래스라는 것을 나타내기 위해 `private` 생성자를 만들어두면 좋을 것 같아요.

2024-02-26 16:55 UTC, kimhodol commented on src/main/java/ladder/view/ResultView.java
> +public class ResultView {
[의견] `static`한 메소드로만 이루어진 유틸성 클래스라는 것을 나타내기 위해 `private` 생성자를 만들어두면 좋을 것 같아요.

2024-02-26 16:55 UTC, kimhodol commented on src/main/java/ladder/domain/LadderLevel.java
> +    public List<LadderDirection> toLadderDirectionList() {
[의견] 변환보다는 값을 가져오는 것이다보니 `toLadderDirectionList`보다는 `getLadderDirections`가 더 자연스러울 것 같아요. 자료구조를 메소드명에 굳이 드러내지 않아도 될 것 같습니다 :)

2024-02-26 16:55 UTC, kimhodol commented on src/main/java/ladder/domain/Ladder.java
> +    }
[의견] 변환보다는 값을 가져오는 것이다보니 `toLadderLevelList `보다는 `getLadderLevels`가 더 자연스러울 것 같아요. 자료구조를 메소드명에 굳이 드러내지 않아도 될 것 같습니다 :)

2024-02-26 16:55 UTC, kimhodol commented on src/main/java/ladder/domain/LadderLevelBuilder.java
> +public class LadderLevelBuilder {
빌더 패턴을 사용해주셨네요 👍 이를 적용했을 때 어떤 이점이 있었나요?

2024-02-26 16:55 UTC, kimhodol commented on src/main/java/ladder/domain/Players.java
> +    }
[의견] 사용처를 보니 `Player`의 `name`을 loop 하기 위해 사용하는 것 같은데, `name`의 `List`만 반환해주는것도 가능하지 않을까요? `names()` 이런 느낌으로요.

2024-02-26 16:55 UTC, kimhodol commented on src/main/java/ladder/domain/LadderDirectionSelector.java
> +}
👍

2024-02-26 16:57 UTC, merged

2024-02-26 17:04 UTC, kimhodol commented on src/main/java/ladder/controller/Controller.java
> +    }
정답이 없는 문제겠지만, `재입력`이라는 것을 굳이 컨트롤러가 알 필요가 없지 않나해서 질문드렸습니다 ㅋㅋ 입력을 받는 주체가 재입력을 받을지 안받을지를 결정하고 컨트롤러에게는 결과물만 넘겨주는게 자연스럽다 생각해서요.

2024-02-27 05:23 UTC, zeus6768 commented on src/main/java/ladder/controller/Controller.java
> +    }
말씀대로 컨트롤러에게는 결과물만 넘겨주면 된다는 관점이 더 명확한 것 같아요 🚀 

팀원들과도 오래 고민한 부분이었는데, 좋은 의견 감사합니다!

2024-02-27 05:37 UTC, zeus6768 commented on src/main/java/ladder/view/InputView.java
> +public class InputView {
좋은 의견 감사합니다! 😄

2024-02-27 06:09 UTC, zeus6768 commented on src/main/java/ladder/domain/LadderLevelBuilder.java
> +public class LadderLevelBuilder {
가장 큰 이점은 `LadderLevel` 객체의 복잡한 생성 로직을 분리할 수 있다는 것이었습니다. 

코드가 짧다면 객체를 생성하기 위한 코드와 사용하기 위한 코드가 한 곳에 있어도 괜찮다고 생각합니다. 하지만 `LadderLevel`은 생성 로직이 복잡하고 길어서, 객체를 사용하기 위한 코드(여기선 getter)와 함께 존재하는 것이 적절하지 않다고 판단했습니다. 

`LadderLevelBuilder`라는 이름은 오직 생성 역할만 수행한다고 쉽게 예상할 수 있으므로, 가독성이 개선되었다고 느꼈습니다.

2024-02-27 06:12 UTC, zeus6768 commented on src/main/java/ladder/domain/Players.java
> +    }
좋은 의견 감사합니다!! 반영할게요 😄