[2단계 - 사다리 게임] 초코칩(권기호) 미션 제출합니다.
woowacourse/java-ladder pull request #335
Opened 2024-02-25 08:31 UTC by Chocochip101

# 사다리 게임
안녕하세요, 리뷰어님. 6기 백엔드 초코칩입니다. 이번 미션에서는 사다리를 구현했습니다. 
## 부탁
### [커뮤니케이션 비용을 줄이기 위한 Pn 룰](https://blog.banksalad.com/tech/banksalad-code-review-culture/)
PR 내용을 보시기 전에 저와 리뷰어님의 커뮤니케이션 비용을 줄이기 위해 Pn 룰을 부탁드리고 싶습니다. Pn룰을 통해 리뷰어님이 저에게 꼭 고쳤으면 하는 리뷰와 그렇지 않은 리뷰를 범위로 나누어 더욱 전달이 효과적으로 이루어질 것 같습니다. 

- [P1]: 꼭 반영해주세요 (Request changes)
- [P2]: 적극적으로 고려해주세요 (Request changes)
- [P3]: 웬만하면 반영해 주세요 (Comment)
- [P4]: 반영해도 좋고 넘어가도 좋습니다 (Approve)
- [P5]: 그냥 사소한 의견입니다 (Approve)
- [질문]: 의견에 대한 질문입니다. (Question)

### 커밋 단위
해당 미션의 주제는 TDD였습니다. 저와 페어 모두 TDD에 대한 개념과 구현이 처음이다보니, TDD 연습을 위해 기능 단위가 아닌, `test` -> `refactor` -> `feat`의 단위로 커밋하려고 노력했습니다. 해당 방식이 TDD에 맞게 한 커밋인지 봐주셨으면 합니다!

# 기능 요구사항(step2)

## 입출력

- [x] 입력한 결과가 0개일 경우, 재입력 받는다.
- [x] 결과는 쉼표(,)를 기준으로 구분한다.
- [x] 결과 이름의 앞뒤 공백은 제거한다.
- [x] 결과를 보고 싶은 사람의 이름을 입력받는다.
- [x] 이름의 앞뒤 공백은 제거한다.
- [x] 입력한 사람에 대한 결과를 출력한다.
- [x] `all`일 경우 모든 사람의 결과를 출력한다.
- [x] 입력값이 잘못되었을 경우, 사용자로부터 재입력받는다.
- [x] 에러 메세지를 구체적으로 작성한다.
- [x] `InputView`, `OutputView`, `BufferedReader`를 싱글톤으로 관리한다.
- [x] 사다리의 결과도 함께 출력한다.
- [x] 사용자의 이름으로 `all`을 입력 받을 수 없다.

## 결과

- [x] 사다리의 도착 결과를 입력받는다.
- [x] 플레이어의 결과는 플레이어 입력 순서대로 유지한다.

## 사다리 게임

- [x] 결과를 계속 입력받는다.
- [x] 출발지부터 도착지까지의 결과를 계산한다.
- [x] 결과 개수와 플레이어 수는 일치한다.
- [x] 입력한 사람이 존재하지 않을 경우, 예외처리한다.
- [x] 사다리의 개수를 2개 이상으로 제한한다.
- [x] 플레이어, 결과 자료를 포장한다.
- [x] 사다리의 높이의 최대를 제한한다.

## 질문
- 저의 상수 클래스 분리 기준은 3곳 이상에서 참조할 경우, 다른 클래스로 분리합니다. 너무 많은 클래스 분리로 오히려 가독성이 떨어지기에`적어도 3곳 정도는 참조해야 공통 상수 클래스로 분리할만하지 않나?`라는 생각이 있습니다. 이번 미션 이전까지는 에러 메세지의 분리를 고려하지 않았으나, 한 두 곳 정도 참조하기 시작하여 고민하고 있습니다. 현구막은 어떤 기준이 있는지 궁금합니다.

- 이번 구현주에 가장 까다로웠던 부분은 `all`에 대한 응답과 결과를 찾고 싶은 사용자 이름에 대한 응답을 동시에 처리해야 하는 부분이었습니다. 문제점은 아래와 같습니다.
  - 분기 처리(`all` 또는 사용자 이름)를 해야 하기에 인덴트가 깊어진다.
  - 인덴트를 줄이기 위해 하나의 함수로 반환하자니, `all` 자료형(`Enum`)과 이름 자료형(`Player` 또는 `String`)이 다르다.
  - 사용자 이름을 잘못 입력할 경우, 다시 입력 받아야한다.

이 부분을 해결하기 위해 세 가지 정도의 해결법을 고민했습니다.
1. `all`의 자료형인 `Enum` 타입과 이름을 갖는 새로운 클래스를 만든다.

```java
class UserResult {
    ReservedWord command;
    String name;
}

public enum ReservedWords {
    ALL("all"), NONE(null);
    ....
}
```

2. `all`의 자료형인 `Enum`과 Player를 인터페이스를 구현 받게 한다.
```java
public enum ReservedWords implements Nameable { ... }
public enum Player implements Nameable { ... }
```

3. Function 메서드를 사용해 인덴트를 최대한 줄인다.

1번의 문제점은 이름을 입력한 겨우 그것을 나타낼 `enum` 타입을 만들어야 하고, 그것이 추후 NPE를 발생하게 할 수 있다는 문제점이 있습니다. 2번 같은 경우, Nameable로 반환하게 하여 일관성있게 다룰 수 있겠지만 연관이 없는 `ReservedWords`을 강제로 구현받게 하는 것이 어색하다고 느껴졌습니다. 결국 3번 방법은 선택해 `BooleanSupplier`를 통해 인덴트를 줄여 구현했습니다. 하지만 아래와 같은 junk code 느낌의 코드가 생긴 것 같아 최선이라는 생각이 들지 않습니다.

```java
    private void repeatUntil(BooleanSupplier condition) {
        while (!condition.getAsBoolean()) {
        }
    }
```

혹시 현구막은 더 괜찮은 방법이 있는지 궁금합니다! 긴 글 읽어주셔서 감사합니다 :)

2024-02-26 09:34 UTC, Hyeon9mak requested changes
안녕하세요 초코칩! 리뷰가 늦었어요 🙏 
우선적으로 간단한 코멘트와 함께 질문에 대한 답변을 작성했습니다.

#### 클래스 분리 기준

상수 뿐만 아니라 모든 클래스를 통틀어서 제 기준을 말씀드리면
저는 "이런 프로젝트 특성상 이렇게 분리해두면 유지보수 순간에 편하겠다." 를 기준으로 잡습니다.

에러 메세지를 한꺼번에 변경하는 일이 잦은 환경(프로젝트)일 때
에러 메세지를 별도로 모아둔 상수 클래스를 만들어서 관리한다면
한 눈에 에러 메세지들을 살펴보기도 편하고, 리팩터링 후 PR 을 올렸을 때 file changes 수도 획기적으로 줄어들겠네요.

반대로 각 비즈니스 로직별로 변경이 잦은 프로젝트라면
비즈니스 로직이 수행되는 영역마다 중복된 에러 메세지를 퍼뜨려놓는게
오히려 한 눈에 에러 메세지도 읽으면서 관리하기 편할 수 있겠네요.

"3곳 이상에서 참조한다." 는 "중복 코드는 제거해야한다." 라는 개발자의 습관 중 하나 때문인거 같아요.
습관을 뛰어넘어 어떤 방법이 나와 동료에게 유지보수에 유리할지 고민해보는 것도 재밌겠네요.

#### 응답 동시 처리

질문을 잘 이해하지 못했어요. 🙏 
개인별 결과 조회와 전체 결과 조회를 하나의 메서드로 해결하려다가 생긴 고민일까요?

만약 맞다면, 서로 완전히 다른 별개의 요구사항을 꼭 하나의 코드로 해결하려해서 어려워진 문제는 아닐까 싶어요.
서로 다른 요구사항을 하나의 코드로 해결하려할 때 꼭 문제가 복잡해지는 것 같아요.

domain 상위 레벨에서 문자열을 `all` 명령어 혹은 `개인` 명령어로 분류하고,
domain 레벨에서 명령어 별로 서로 다른 입/출력을 가진 메서드를 수행하토록 하면 어떨까요?
잘 고민해보면 OCP 원칙을 지키는 방법이 될거 같아요.

궁금하신 점 언제든지 추가 코멘트나 채널에 질문 남겨주세요!

2024-02-26 09:34 UTC, Hyeon9mak commented on README.md
> +    - [x] 포인트보다 많은 경우의 예외 처리
😉 👍

2024-02-26 09:34 UTC, Hyeon9mak commented on src/main/java/laddergame/LadderGame.java
>      }
P5.
완성도가 높기 때문에 추가로 하나 과제를 하나 던져볼게요.
현재 `LadderGame` 이 controller 의 역할과 비즈니스 제어 역할을 모두 담당하고 있는 걸로 보여요.
controller 와 비즈니스 제어 역할을 분리하여 controller 가 정말 순수하게 model - domain 간 소통만 담당하도록 리팩터링 해볼 수 있을까요?
나중에 view 와 controller 변경될 때, domain 패키지는 아예 열어볼 필요도 없을 정도가 되면 좋겠네요!

2024-02-26 09:34 UTC, Hyeon9mak commented on src/main/java/laddergame/domain/Direction.java
> +    private final int movement;
enum 을 이용한 상수관리 👍

2024-02-26 09:34 UTC, Hyeon9mak commented on src/main/java/laddergame/domain/Height.java
> +    private static final String INVALID_HEIGHT_RANGE = "적절한 높이 범위가 아닙니다.";
P2
잘못된 입력을 알려주는 것은 👍 
더 나아가서 다음 행동을 어떻게 해야할지 알려주는 것도 좋겠어요. (9 이하의 숫자를 입력해야한다던지)
제 경험을 하나 공유합니다 ㅎㅎ

- https://hyeon9mak.github.io/why-should-throw-detail-error-message/
- https://hyeon9mak.github.io/writing-helpful-error-messages/

2024-02-26 09:34 UTC, Hyeon9mak commented on src/main/java/laddergame/domain/Ladder.java
> +    }
P3: `Players` 에게 참여자 수를 반환해줄 수 있냐고 물어보는 건 어떨까요?

2024-02-26 09:34 UTC, Hyeon9mak commented on src/main/java/laddergame/domain/Line.java
> +    }
P3
역시나 points 에게 마지막 지점인지 물어볼 수 있겠네요!
points 에게 0이 시작지점인지 물어봐도 좋겠어요~

2024-02-26 09:34 UTC, Hyeon9mak commented on src/main/java/laddergame/domain/Line.java
> +    }
이렇게 객체에게 질문을 할 때 어떤 장점이 생길까요?

2024-02-26 09:34 UTC, Hyeon9mak commented on src/main/java/laddergame/util/ReservedWords.java
> +        this.word = word;
P2
결국 사용자로부터의 "입력"을 "명령"으로 치환하는 영역인 것 같은데요,
'util 이라는 명칭의 만능 패키지를 만들 필요가 있을까?' 라는 생각이 들어요.
"입력"을 "명령" 혹은 VO 로 치환해주는 건 누군가가 이미 진행중이지 않나요? 🤔

2024-02-26 09:34 UTC, Hyeon9mak commented on src/main/java/laddergame/view/InputView.java
> +    private static final InputView instance = new InputView();
질문.
객체를 캐싱해주셨군요~ `InputView` 자체가 모든 입력 메서드를 static 으로 갖는 것 대비 어떤 장점이 있을까요?

2024-02-26 09:34 UTC, Hyeon9mak commented on src/main/java/laddergame/view/OutputView.java
> +    private static final String ERROR_PREFIX = System.lineSeparator() + "[ERROR] ";
`System.lineSeparator()` 을 이용한 개행 활용 👍

2024-02-26 09:45 UTC, Chocochip101 commented on src/main/java/laddergame/view/InputView.java
> +    private static final InputView instance = new InputView();
static으로 정의하면 JVM 내에 static(method) 영역에 덤프됩니다. 추후에 `InputView`에 상수화해야할 문자열들이 많아지면, OOM이 발생할 수 있습니다. 반면에 싱글톤(객체 캐싱)으로 관리하게 되면, 하나의 객체가 생성됨이 보장되어 무분별한 객체가 Heap 영역에 생기지 않게 됩니다.

2024-02-26 09:47 UTC, Chocochip101 commented on src/main/java/laddergame/domain/Height.java
> +    private static final String INVALID_HEIGHT_RANGE = "적절한 높이 범위가 아닙니다.";
경험 공유 감사합니다. 사용자 입장에서 답답하게 느껴질 수도 있겠네요. 참고해서 수정해보겠습니다.

2024-02-26 10:02 UTC, Chocochip101 commented on src/main/java/laddergame/domain/Line.java
> +    }
관련해서 `디미터의 법치`이 생각나네요. 객체의 데이터를 조회해서 로직을 수행하는 것이 아닌, 메시지를 전달할 수 있도록 변경하여 객체간 메시지를 주고받는 방식으로 자율성을 높여 서로 협력할 수 있도록 할 수 있습니다.

2024-02-26 10:20 UTC, Chocochip101 commented on src/main/java/laddergame/LadderGame.java
>      }
`LadderGame` 클래스를 사용자 입력 및 출력과 관련된 작업을 담당하는 Controller 클래스와 비즈니스 로직을 처리하고 `Ladder`, `PlayersResults` 등 도메인 객체를 조작하고 제어하는 Service 클래스로 분리할 수 있습니다. Controller에서 Service를 주입받아 사용하면, Controller는 도메인 로직에 대한 세부 내용을 알 필요가 없게 됩니다.

2024-02-26 10:40 UTC, Chocochip101 commented on src/main/java/laddergame/util/ReservedWords.java
> +        this.word = word;
"입력"을 "명령"으로 치환하는 영역은 `InputView`와 `LadderGame`에서 맡고 있어서, view나 domain 패키지에 두는 것이 적합해보입니다. `ReservedWords`내의 로직이 사용자 입력의 로직과 관련되니, view에 더 가깝다고 볼 수 있어서 view 패키지에 두도록 결정했습니다.

2024-02-27 02:28 UTC, solarsalt commented on src/main/java/laddergame/LadderGameService.java
> +public class LadderGameService {
P4.
이 클래스는 무엇을 담당하나요?🧐 

제가 클래스 이름과 갖고있는 메소드 이름을 봤을 땐,
사다리게임에 필요한 **거의 모든 것을 서비스**해주는 역할로 이해되었어요.

혹시 제가 이해한 역할로 만드신 의도가 아니라면, 
아니면 '거의 모든 것을 서비스해준다' 가 역할로 적합하지 않다고 느껴지신다면, 
역할을 좀더 구체적으로 부여해주는 것도 시간이 되신다면 고민해보셔요~ :)

2024-02-27 09:39 UTC, Hyeon9mak requested changes
안녕하세요 초코칩!
미션 진행 속도가 너무 빨라서 고민될 정도인데... 😄 👍 

`"all"` 에 대한 검증 로직에서 초코칩의 생각도 궁금하고,
마침 솔라가 좋은 코멘트를 남겨주셔서 request changes 한번 더 남길게요.

궁금하신 점 언제든지 추가 코멘트 남겨주세요.

2024-02-27 09:39 UTC, Hyeon9mak commented on src/main/java/laddergame/domain/Line.java
>          }
> 관련해서 디미터의 법치이 생각나네요. 객체의 데이터를 조회해서 로직을 수행하는 것이 아닌, 메시지를 전달할 수 있도록 변경하여 객체간 메시지를 주고받는 방식으로 자율성을 높여 서로 협력할 수 있도록 할 수 있습니다.

서로 협력한다는 의미를 잘 이해하지 못했어요. 조금 더 풀어서 설명해주실 수 있을까요?
가령 대상 객체에게 메세지를 보내면, 대상 객체의 코드를 변경해도 대상 객체를 의존하는 쪽에는 아무런 영향이 없겠어요.

2024-02-27 09:39 UTC, Hyeon9mak commented on src/main/java/laddergame/domain/Height.java
> +    private static final String INVALID_HEIGHT_RANGE = "사다리 높이는 반드시 1 이상, 9 이하로 이루어져야 합니다. 입력된 사다리 높이는 %s 입니다.";
👍 명확하게 제약사항과 잘못된 입력을 안내해주네요 👍

2024-02-27 09:39 UTC, Hyeon9mak commented on src/main/java/laddergame/LadderGameController.java
> +
controller 에서는 정말 순수하게 어떤 값이 오고가는지가 한눈에 보이네요 👍

2024-02-27 09:39 UTC, Hyeon9mak commented on src/main/java/laddergame/LadderGameService.java
> +public class LadderGameService {
P1
`Service` 라는 이름은 항상 만능으로 사용되는 것 같아요.
현재 `LadderGameService` 가 어떤 기능들을 담당하고 있나요?
혹시 사다리 게임 그 자체를 나타내나요? 그렇다면 그 이름을 사용하는 건 어떨까요?
개발자를 뛰어넘어 모든 사람들이 이해하고 있는 지식(=상식)을 이용하는 것이 진짜 객체지향이겠네요 👀

2024-02-27 09:39 UTC, Hyeon9mak commented on src/main/java/laddergame/domain/Players.java
> +                .orElseThrow(() -> new IllegalArgumentException(String.format(PLAYER_NOT_FOUND_ERROR, name)));
P5
역시나 Player 에게 물어봐도 되겠네요 😄

2024-02-27 09:39 UTC, Hyeon9mak commented on src/main/java/laddergame/domain/Player.java
> +
P2
앗 이런... domain 패키지가 view 패키지에 의존하고 있네요.
추후 명령어 입력 방식을 콘솔에서 아닌 웹 이미지 버튼 클릭으로 변경할 때 view 뿐만 아니라 domain 패키지 내부도 함께 영향을 받겠어요.

웹 버튼 클릭으로 상상하여 비교해보건데... 사용자 입력 내용이 "all" 명령어에 해당되는지 정도는 view 에서 확인해줄 수 있지 않을까요? 🤔 
초코칩은 어떻게 생각하시나요?

2024-03-03 11:39 UTC, Chocochip101 commented on src/main/java/laddergame/LadderGameService.java
> +public class LadderGameService {
사다리 게임 자체를 표현하고 싶었지만,`LadderGame`으로 클래스명을 짓기에는 도메인 느낌이 강하고 인스턴스 변수를 갖고 있지 않아 어색하게 느껴져서 `LadderGameService`를 사용했습니다. 

하지만 매인 비즈니즈 로직은 `Ladder`에서 생성할 때 이미 사다리가 완성되기 때문에 `LadderGameService`가 부적절하게 느껴지네요. 사다리게임에 필요한 거의 모든 것을 준비해준다는 클래스명을 담기 위해 `LadderGameBuilder`로 수정했습니다.

2024-03-03 11:55 UTC, Chocochip101 commented on src/main/java/laddergame/domain/Line.java
>          }
협력이라는 단어를 통해 **객체끼리 메시지를 통해 요청과 응답을 주고 받는 것**을 강조하고 싶었습니다. 조회해서 로직을 수행하지 않고, 직접적으로 메서드를 호출하는 방식으로 객체들이 서로 자율(독립)적으로 존재할 수 있습니다. 이는 언급해주신대로 하나의 객체를 수정할 때 다른 객체에 미치는 영향을 최소화하며, 낮은 결합도를 유지할 수 있습니다. 또한 객체들이 메시지를 통해 요청, 응답하므로  `getter`로부터 데이터를 노출하는 것을 방지해 캡슐화에도 도움이 될 수 있습니다.

2024-03-03 12:15 UTC, Chocochip101 commented on src/main/java/laddergame/domain/Player.java
> +
언급해주신대로 domain이 view에 의존하고 있어, view 로직이 바뀌면 domain 로직이 바뀌게 되어 결합도가 높아지게 됩니다. 저 또한 이것이 부적절하다고 생각하여 명령어 처리와 관련하여 고민해보았습니다. "all"과 관련된 로직을 두 부분으로 나눌 수 있을 것 같습니다.
1. 사용자 입력에 명령어가 포함되는지
2. 사용자 입력이 어떤 명령인지 구분하여 실행하는 것

1번의 경우는 view와 직접적으로 연관된 로직이기에 말씀해주신 것처럼 view에서 처리하는 것이 맞다고 판단하여, InputView 클래스에서 처리하게 했습니다. 

2번의 경우에는 비즈니즈 로직이라 생각합니다. 사용자의 의도에 따라 어떤 명령인지를 구분하는 부분이므로, 이를 Service와 같은 비즈니스 로직을 처리하는 부분에서 담당할 수 있습니다. 하지만 현재 메인 비즈니즈 로직을 처리하는 것이 도메인이므로 위 언급처럼 결합도가 높아집니다. 따라서 저는 이를 Controller에서 처리하게끔 했습니다.

2024-03-03 23:38 UTC, Hyeon9mak requested changes
안녕하세요 초코칩! 연휴 잘 보내셨나요? 😄 👍 
남겨주신 코멘트들과 피드백 반영내용 잘 확인했습니다 💯 

간단한 코멘트와 함께 마지막으로 request changes 를 남기려고 해요.
천천히 읽어보시고 반영 여부를 결정해주시면 되겠습니다!
다음 리뷰 요청 때 추가로 질문이 없으시면 approve 하도록 하겠습니다 👍 
마지막까지 화이팅~

2024-03-03 23:38 UTC, Hyeon9mak commented on src/main/java/laddergame/domain/Line.java
>          }
초코칩이 말하는 협력이란 객체끼리 내부 멤버변수를 노출하지 않고 메서드를 통해 메세지를 주고 받는 것 그 자체군요!
자세하게 설명 해주신 덕분에 이해했어요 😄 👍

2024-03-03 23:38 UTC, Hyeon9mak commented on src/main/java/laddergame/domain/Players.java
> +    }
👍

2024-03-03 23:38 UTC, Hyeon9mak commented on src/main/java/laddergame/view/ReservedWords.java
> +    }
👍 👍 
view 에서 "all" 이라는 문자열이 `전체 사용자들의 결과를 조회하는 명령어` 라는 걸 판별해주면
추후 "all" 대신 "everyone", 더 나아가 버튼 이미지 경로로 변경되어도 다른 곳은 영향이 없겠네요 👍

2024-03-03 23:38 UTC, Hyeon9mak commented on src/main/java/laddergame/LadderGameController.java
> +    }
P4 👍 
if 문에서 전체조회와 관련된 로직을 수행하므로, `isIncluded` 보다 조금 더 적나라한 메세지로 물어봐도 좋겠어요! 👍

2024-03-03 23:38 UTC, Hyeon9mak commented on src/main/java/laddergame/LadderGameBuilder.java
> +    }
> 사다리게임에 필요한 거의 모든 것을 준비해준다는 클래스명을 담기 위해 LadderGameBuilder로 수정했습니다.

P4
👍 클래스 이름을 읽고 나니 get 메서드들의 행동이 머리속에 더욱 잘 그려지네요.
그런데... 준비를 해주는거라면 메서드들의 이름도 get 대신 다른 걸로 바꾸어볼 수 있겠어요 💭

2024-03-04 00:59 UTC, solarsalt commented on src/main/java/laddergame/LadderGameService.java
> +public class LadderGameService {
@Chocochip101  cc @Hyeon9mak 

> 사다리 게임 자체를 표현하고 싶었지만,LadderGame으로 클래스명을 짓기에는 도메인 느낌이 강하고 인스턴스 변수를 갖고 있지 않아 어색하게 느껴져서 LadderGameService를 사용했습니다.

P5. 어떤 이유로 도메인 느낌을 강하게 받으셨는지를 언급해주시지 않아서 알 수 없지만, '사다리 게임 자체를 표현하고 싶었다'다면, 저는 LadderGame도 좋은 이름이 될 수 있을 것 같아요. 
레벨1에서 도메인, 모델, 뷰, 컨트롤러 같은 단어들로 다른 크루들과 열심히 토론하시고 탐구하고 계시는 것을 잘 알고 있지만 :)
(레벨1에서 집중해야할 부분이 맞고, 너무 잘해주고 있어요! 👍 👍 👍 👍 )

때로는 멋진 용어들은 머릿속에서 지우고, '만든 사람의 의도를 잘 드러내는 이름인가? 처음 본 사람도 이해하기 쉬운가?'에만 집중해도 어느새 읽기 좋은 코드에 가까워 지고, 자연스럽게 객체 분리와 뷰와 모델의 분리로 가는 지름길이 나타나기도 한답니다. 
클래스 네이밍에서 너무 M/V/C와 객체지향 용어들에 얽매이지는 않으시는 것도 또 다른 방법입니다. 저는 개인적으로 MVC나 객체지향 용어는 추상적인 레이어와 컨셉을 설명하기 위한 단어라고 생각해서, 클래스 네이밍은 좀 더 개발자의 자유도를 발휘하고 창작의도를 담을 수 있다고 생각해요.


> 사다리게임에 필요한 거의 모든 것을 준비해준다는 클래스명을 담기 위해 LadderGameBuilder로 수정했습니다.

P5. 
1. '이 클래스 혹은 객체는 어떤 일을 해요? 무슨 역할 이에요?' 라는 질문에, 
'거의 모든 일을 해요.', '이것도 하고, 저것도 담당해요', '모든 걸 해결해줘요.' 라고 대답하게 된다면...높은 확률로 객체를 더 분리할 수 있거나, 객체의 역할을 다시한번 고민해봐야하는 시그널 일 때가 많아요! 
간단하면서도, 어떤 상황에서도 객체지향 설계의 나침반이 되어주는 질문이니, 활용해보세요.
여기서 말해주신 '거의 모든 것을 준비해준다' 상태가 여전히 괜찮은 것 일까요? 아마도 다음 미션에서도 '거의 모든 것을 준비해주는' 객체는 또 등장할 지도 몰라요~ 지금은 넘어가고, 다음에 이런 객체가 또 등장하면 그 때 고민해 보셔도 좋습니다.

2. 'XXBuilder'라는 이름은, 특히 java 언어에서 [Builder](https://refactoring.guru/design-patterns/builder) 패턴을 사용한 것을 떠올리기 쉬울 수 있어요~ 
초코칩의 작명의도를 들었으니, 저는 오해하지 않았지만 같은 언어를 공유하는 처음보는 동료들은 오해할 수도 있겠어요. 
자매품으로 getXX, setXX 도 getter나 setter 를 떠올리기 쉬운 이름이라서, 이름 지을때 유의하게 되는 작명이기도 합니다. 앞으로 이름을 지으실 땐, 이런 부분도 고려해보셔요 :)

2024-03-04 01:49 UTC, Chocochip101 commented on src/main/java/laddergame/LadderGameController.java
> +    }
단어가 예약어인지 판단하는 것을 강조하기 위해 `isReserved`로 수정했습니다.

2024-03-04 01:51 UTC, Chocochip101 commented on src/main/java/laddergame/LadderGameBuilder.java
> +    }
getter와 오해할 수도 있어, 도메인을 생성해준다는 의미에서 create~로 수정했습니다. 마찬가지로 controller 내부에도 get~형태의 getter가 아닌 메서드들이 존재하여 메서드명을 수정했습니다.

2024-03-04 02:08 UTC, Chocochip101 commented on src/main/java/laddergame/LadderGameService.java
> +public class LadderGameService {
클래스명이 `LadderGame`이면 사다리 게임의 **인스턴스 변수를 통해** 게임을 조작하기 때문에 도메인 로직이라 생각했던 것 같습니다. 현재 `LadderGameBuilder`에는 인스턴스 변수가 없어서 '`LadderGame`이 어색하지 않나?'라는 생각을 했던 것 같고, 그 원인은 이전에 만들었던 코드들의 습관이었던 같네요.

다시 생각해보니 사다리 게임에서 게임 자체가 서비스(Game == Service)이기 때문에 LadderGame의 클래스명도 충분히 납득 가능합니다.

> 어떤 이유로 도메인 느낌을 강하게 받으셨는지를 언급해주시지 않아서 알 수 없지만, 


ANS.
1. 초반에 TDD에 매몰되어 '테스트를 만족시키기 위해 일단 돌아가는 쓰레기를 만들자'라는 생각에 객체의 책임 부여가 제대로 되지 않은 것 같습니다. 그로 인해 '모든 것을 해주는' 클래스가 생성된 것 같습니다. 이를 보완하기 위해 다음 미션에서 책임 주도 설계를 적용해보고자 합니다. 명확한 책임을 클래스에 부여해보도록 하겠습니다.

2. Builder 페턴을 클래스 내 생성자의 매개변수가 많을 때 중복되는 생성자 코드를 줄이기 위헤 사용하는 것으로 알고 있습니다. 때문에 생성자나 메서드명에만 XXBuilder를 쓰지 않는다면 괜찮다고 생각했는데, 오해할 수도 있겠군요 🧐 다음부터 주의하겠습니다.

2024-03-04 10:48 UTC, Hyeon9mak approved these changes
초코칩! 미션 마지막까지 고생 많으셨습니다 👍 
요구사항도 모두 충족되었고 피드백도 잘 반영해주셔서 바로 approve 하겠습니다~
다음 미션도 화이팅입니다 💪

2024-03-04 10:48 UTC, Hyeon9mak commented on src/main/java/laddergame/LadderGameBuilder.java
> +    }
👍 

P4
리사 코멘트처럼 java 언어에서 `XXXbudiler` 라는 명칭은 `XXX` 객체의 인스턴스를 생성하는데 도움을 주는 클래스처럼 인식되는 것 같아요.
개발자끼리 공통으로 디자인 패턴을 학습하고 소통하는 것처럼, java 언어에서 자주 활용되는 네이밍을 기억해두고 그것들을 잘 회피하거나 활용하는 것도 중요하겠습니다. 😄 👍

2024-03-04 10:48 UTC, merged