[사다리 게임] 김고래 미션 제출합니다.
woowacourse/java-ladder pull request #34
Opened 2019-05-18 01:09 UTC by ep1stas1s

2019-05-18 08:48 UTC, pobiconan requested changes
전체적인 객체 설계, 클린코드 구현, 테스트 코드 구현 💯 
단, LadderGame의 구조가 너무 복잡해서인지 테스트하기 너무 어려운 점이 있어 보이네요.
좀 더 테스트하기 쉬운 구조로 개선할 방법이 있는지 찾아보면 좋겠어요.

2019-05-18 08:48 UTC, pobiconan commented on src/main/java/calculator/CustomSeparator.java
> +        if(separator.length() != 1){
separator.isEmpty() 활용해 구현 가능함

2019-05-18 08:48 UTC, pobiconan commented on src/main/java/calculator/StringCalculator.java
> +    private void isNegative(int i) {
Positive 객체를 추가하고 생성자에서 음수에 대한 예외처리도 구현해 보는 연습을 하면 어떨까?

2019-05-18 08:48 UTC, pobiconan commented on src/main/java/ladder/controller/LadderController.java
> +        List<Player> players = addPlayer(unrefinedNames);
일급 콜렉션 원칙을 적용해 본다.

2019-05-18 08:48 UTC, pobiconan commented on src/main/java/ladder/controller/LadderController.java
> +        List<Prize> prizes = addPrize(unrefinedPrizes);
일급 콜렉션 원칙을 적용해 본다.

2019-05-18 08:48 UTC, pobiconan commented on src/main/java/ladder/controller/LadderController.java
> +        LadderGame ladderGame = new LadderGame(ladder, players, prizes);
GameResult result = ladder.play(gamePlayers, playerRewards)와 같이 구현하는 것은 어떨까?
현재 구현과 어떤 점이 달라질까?

2019-05-18 08:48 UTC, pobiconan commented on src/main/java/ladder/domain/Direction.java
> +                .filter(direction -> direction.getDirection() == directionIntValue)
상태를 가지는 객체의 데이터를 꺼내려(get)하지 말고 객체에 메시지를 보내라는 원칙에 따라 구현한다.

2019-05-18 08:48 UTC, pobiconan commented on src/main/java/ladder/domain/Ladder.java
> +    public Ladder(List<Line> lines) {
2개의 생성자가 있다.
둘 중 하나가 테스트 목적으로 생성한 생성자라면 생성자 하나로 구현 가능한 방법이 없는지 찾아본다.

2019-05-18 08:48 UTC, pobiconan commented on src/main/java/ladder/domain/Ladder.java
> +        return lines;
List를 외부에 공개하는 경우 외부에서 수정/삭제할 위험성이 있다.
따라서 외부에 공개할 때는 수정하지 못하도록 java.util.Collections.unmodifiableList() 사용해 반환할 것을 추천한다.

2019-05-18 08:48 UTC, pobiconan commented on src/main/java/ladder/domain/LadderGame.java
> +        if (direction == Direction.RIGHT) {
상태를 가지는 객체의 데이터를 꺼내려(get)하지 말고 객체에 메시지를 보내라는 원칙에 따라 구현한다.
`direction.isRight()`나 `direction.move()로 구현 가능한지 검토해 본다.

2019-05-18 08:48 UTC, pobiconan commented on src/main/java/ladder/domain/Line.java
> +    private Direction[] points;
배열을 써야하는 특별한 이유가 없다면 List Collection을 활용해 구현한다.

2019-05-18 08:48 UTC, pobiconan commented on src/test/java/ladder/domain/PlayerTest.java
> +    }
`" "`와 같이 space가 들어가 있는 경우는 어떻게 하면 좋을까?

2019-05-18 08:48 UTC, pobiconan commented on src/test/java/ladder/domain/LadderGameResultTest.java
> +        assertThat(ladderGameResult.getNameToPrize().get(new Player("pobi")))
결과 값을 얻기 위해 dot(.)을 너무 중첩으로 사용하고 있다.
`ladderGameResult.getPrize("pobi")`와 같은 구조가 가능하도록 지원하면 어떨까?

2019-05-18 08:48 UTC, pobiconan commented on src/test/java/ladder/domain/LadderGameResultTest.java
> +                new Line(new Direction[]{Direction.STRAIGHT, Direction.STRAIGHT, Direction.RIGHT, Direction.LEFT, Direction.STRAIGHT}));
최종 결과를 확인하기 위해 테스트 데이터를 초기화하는 과정이 너무 복잡하다.
여기서 힌트를 얻어 LadderGame의 구조를 좀 더 단순화해서 구현할 방법이 있는지 찾아본다.

2019-05-20 11:48 UTC, ep1stas1s commented
고칠 것이 많기도 하고, 미련없이 날리라는 강의에 감명 받아 새롭게 시작하였습니다. 피드백 주신 사항을 기반으로 설계하여 시작하니, 처음에 비해 속도가 확연히 빨라진 것을 느낄 수 있었습니다! 
바쁘신 와중에도 피드백주셔서 항상 감사합니다:+1:
- 객체화, 일급 컬렉션 사용
- 매개변수 간소화
- Collections.unmodifiableList() : getter 사용시 Collection을 수정하지 못하도록 적용
- 객체에 message를 전달하여 처리
- 배열보단 Collection을 활용
- 지나친 dot(.) chain을 줄이기 위해 객체에 message를 전달하는 형태로 dot을 최소화
- Test 간소화

2019-05-21 01:02 UTC, pobiconan requested changes
그 동안 리뷰요청과 피드백도 없었는데 전체적인 객체설계와 코드 깔끔하게 구현 잘 했네요. 💯 
단, 사다리 타기의 이동 로직과 같은 기능은 상태 데이터를 가지는 Line과 같은 객체가 담당하도록 구현하면 좀 더 객체지향적인 구현이 가능할 것 같아요.
소소한 피드백 몇 개 남겨 봅니다.

2019-05-21 01:02 UTC, pobiconan commented on src/main/java/calculator/Positive.java
> +public class Positive {
👍

2019-05-21 01:02 UTC, pobiconan commented on src/main/java/calculator/PositiveNumbers.java
> +public class PositiveNumbers {
오호. 여기에 일급 콜렉션을 적용했군요. 👍

2019-05-21 01:02 UTC, pobiconan commented on src/main/java/ladder/controller/LadderController.java
> +    public static void main(String[] args) {
main() 메소드의 구조 좋네요.

2019-05-21 01:02 UTC, pobiconan commented on src/main/java/ladder/domain/ladder/Direction.java
> +                .filter(direction -> direction.getDirection() == directionIntValue)
상태를 가지는 객체의 데이터를 꺼내려(get)하지 말고 객체에 메시지를 보내라는 원칙에 따라 구현한다.
`direction.match(directionIntValue)`와 같이 구현은 어떨까?

2019-05-21 01:02 UTC, pobiconan commented on src/main/java/ladder/domain/ladder/Direction.java
> +    public static Direction valueOf(int directionIntValue) {
변수 이름에 type을 사용하지 않을 것을 추천

2019-05-21 01:02 UTC, pobiconan commented on src/main/java/ladder/domain/ladder/Ladder.java
> +    private List<Line> lines;
final로 구현

2019-05-21 01:02 UTC, pobiconan commented on src/main/java/ladder/domain/ladder/Line.java
> +    }
move()와 같은 메소드를 이곳에 구현하면 어떨까?

2019-05-21 06:41 UTC, pobiconan approved these changes
구현한 기능을 모두 삭제하고 처음부터 다시 시작하는 열정까지..
사다리타기 기능 구현하느라 수고했어요. 💯 
이 미션을 통해 객체지향 설계와 TDD의 맛을 조금은 느낄 수 있었기를 기대합니다.

2019-05-21 06:41 UTC, merged