[2단계 - 사다리 게임] 리브(김민주) 미션 제출합니다.
woowacourse/java-ladder pull request #340
Opened 2024-02-26 08:49 UTC by Minjoo522

안녕하세요, 오리. 리브입니다! 😊

우선, 지난 번 리뷰에서 코멘트 주신 부분들을 개선해 보았습니다‼️

### `LadderGameMachine`을 `Application`과 동일한 패키지로 이동했습니다.
말씀 주신 것처럼 `controller`라는 패키지 네이밍은 MVC 패턴으로 개발하며 습관적으로 사용해오던 것이었습니다.
좋은 피드백 주셔서 감사합니다. 😸
 
### `ArrayList`의 `initialCapacity`를 설정 했을 때, 하지 않았을 때 차이점
`ArrayList` 생성시 `initialCapacity`를 설정하지 않으면 아래와 같이 `DEFAULT_CAPACITY`로 10칸짜리 Object가 생성됩니다.
```java
private static final int DEFAULT_CAPACITY = 10;

public ArrayList() {
        this.elementData = DEFAULTCAPACITY_EMPTY_ELEMENTDATA;
}
```
`initialCapacity`를 설정하면 크기가 정해진 Object가 생성됩니다.
`initialCapacity`가 정해져 있지 않으면 `DEFAULT_CAPACITY`가 채워진 후에는 `add()`가 호출될 때 반복적으로 저장 공간을 재할당 하게 됩니다.

```java
private void add(E e, Object[] elementData, int s) {
        if (s == elementData.length)
            elementData = grow(); // 현재 저장된 아이템의 개수가 저장 공간과 동일해지면 저장 공간 재할당
        elementData[s] = e;
        size = s + 1;
}
```

정확한 `initialCapacity` 할당하면 재할당 비용을 피할 수 있는 방법이 될 수 있다고 생각합니다.
아래 코드에서 `List<StepStatus> stepStatuses` 크기는 명확하기 때문에 미리 할당해 두면 `ArrayList`의 크기가 큰 경우,
계속 재할당하지 않아도 되는 이점이 있을 것으로 생각됩니다.

```java
private List<StepStatus> createStepStatuses(Supplier<Boolean> generator, final int userCount) {
    final int totalSteps = userCount - 1;
    final List<StepStatus> stepStatuses = new ArrayList<>(totalSteps);
    for (int i = 0; i < totalSteps; i++) {
        stepStatuses.add(generateStepStatus(generator, stepStatuses, i));
    }
    return stepStatuses;
}
```

---

그리고, 2 단계를 구현하면서 궁금했던 부분은 다음과 같습니다.

## 논리 부정 연산자 사용 관련
논리 부정 연산자를 제어문에 사용하는 경우 가독성이 떨어진다고 생각하여,
다음과 같이 변수로 추출해 주었습니다.
함수로 추출하기에 너무 과한 분리라고 생각하여 변수로 추출하였는데, 오리는 어떻게 하는 걸 선호하시는지 궁금합니다. ☺️ 
```java
public void validateRequestName(String requestName, UserNames userNames) {
    boolean isNotAll = !requestName.equals("all");
    boolean isNotExist = !userNames.isExist(requestName);
    if (isNotAll && isNotExist) {
        throw new IllegalArgumentException("존재하지 않는 참여자입니다.");
    }
}
```

## TDD 관련
2단계를 진행하면서 이미 만들어진 코드에 새로운 기능을 덧붙이면서 TDD를 하는 것이 쉽지 않았습니다.
테스트 코드를 만들고 기능을 추가하다보면 그 기능을 위한 다른 기능이 필요해지는 경우가 많았습니다.
또한, 새로운 기능을 위해 기존 코드를 변경해야 하는 일도 많았습니다.
이럴 때는 기존 설계가 부족한 것인지, 아니면 TDD를 조금 융통적으로 적용해야 하는 것인지, 아니면 다른 방법이 있는지 궁금합니다.

2024-02-26 12:27 UTC, jinyoungchoi95 requested changes
안녕하세요 리브 😄

2단계도 깔끔하게 잘 구현해주셨네요. 몇가지 코멘트 남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-02-26 12:27 UTC, jinyoungchoi95 commented on src/main/java/ladder/domain/RequestName.java
> +        }
> 논리 부정 연산자를 제어문에 사용하는 경우 가독성이 떨어진다고 생각하여,
> 다음과 같이 변수로 추출해 주었습니다.
> 함수로 추출하기에 너무 과한 분리라고 생각하여 변수로 추출하였는데, 오리는 어떻게 하는 걸 선호하시는지 궁금합니다. ☺️

자바의 특성상 어쩔수없이 부정표현이 `!`로 밖에 안되어 생기는 문제인데요. 지금 방법도 저는 충분히 나쁘지는 않다고 생각해요. 정답은 없는 것이고 표현하기에 따라서 달라지는 부분이니까요.

이외에도 방법은 여러가지가 있을 것 같은데요.
```java
if (isNotAll(requestName) && isNotExist(requestName) {
    throw new IllegalArgumentException();
}
```
와 같이 private 메소드로써 표현을 하거나

```java
if (requestName.equals("all") || userNames.isExist(requestName)) {
    return;
}
throw new IllegalArgumentException("존재하지 않는 참여자입니다.");
```
로 논리 연산을 역으로 사용하는 방법도 있을 것 같아요. 사실 정답은 없는 부분이고 개인적으로는 변수추출보다는 행위로 의미를 더 명확하게 전달할 수 있는 메소드로 빼는 것을 선호하긴합니다 :) (지금도 그렇게 과하지 않고 좋은 방법인것 같습니다)

2024-02-26 12:27 UTC, jinyoungchoi95 commented on docs/README.md
> 2단계를 진행하면서 이미 만들어진 코드에 새로운 기능을 덧붙이면서 TDD를 하는 것이 쉽지 않았습니다.
> 테스트 코드를 만들고 기능을 추가하다보면 그 기능을 위한 다른 기능이 필요해지는 경우가 많았습니다.
> 또한, 새로운 기능을 위해 기존 코드를 변경해야 하는 일도 많았습니다.
> 이럴 때는 기존 설계가 부족한 것인지, 아니면 TDD를 조금 융통적으로 적용해야 하는 것인지, 아니면 다른 방법이 있는지 궁금합니다.

처음 TDD를 해보신 미션이다보니 쉽지않은게 당연한게 아닐까해요. 옛날부터 축척되어온 방법론을 처음 적용하자마자 완벽하게 적용하기란 쉽지 않으니까요.

새로운 요구사항이 발생했을 때 기존 구조가 변경해야하거나 생각치못한 기능이 계속 추가되는건 어쩔 수 없지 않을까요? 생각보다 모든 요구사항은 돌발적이고 완벽하게 나중을 대처하기 위한 코드는 없기때문에 기존의 설계에 대한 부족함을 크게 고민하지 않으셔도 될 것 같아요.

다만, 오버프로그래밍을 하지말자라는 이야기이지 확장가능한 코드를 만드는 것과는 별개이긴해요. 너무 다른 구현체에 의존되어있지는 않은지, 추상화 단계를 어떻게 설계해야하는지는 미션을 진행하면서 다양한 케이스에서 학습해보시면 리브만의 주관이 생기지 않을까 합니다.

TDD를 융통적으로 적용해야하느냐에 대해서는 TDD의 본질이 무엇인가를 고민해보셨으면 좋겠어요. 과연 테스트를 먼저 짜기만 하는게 TDD의 본질일까요? TDD는 일정한 패턴을 지닌 코딩 기법이 아닌 무언가를 위한 "방법론"에 불과해요. TDD 사이클에서 가장 핵심이 되는 파트가 어디부분인지, TDD가 왜 하필 테스트를 먼저 짜는가를 이야기하게 되었는지 근본을 한번 고민해보시면 좋을 것 같네요 😄

2024-02-26 12:27 UTC, jinyoungchoi95 commented on src/main/java/ladder/domain/UserNames.java
> +    }
`order`가 -1 혹은 `userNames` 크기보다 큰 값이 들어오면 의도치 않은 에러를 발생시키겠네요.

2024-02-26 12:27 UTC, jinyoungchoi95 commented on src/main/java/ladder/domain/UserNames.java
> +    public UserName findByOrder(final int order) {
리브는 `find`라는 이름과 `get`이라는 이름을 정의하는 차이가 무엇인가요?

2024-02-26 12:27 UTC, jinyoungchoi95 commented on src/test/java/ladder/domain/GameResultsTest.java
> +        assertThat(destinations).containsExactly("3000", "꽝");
`findAll`을 테스트하고자하는 것으로 보이는데 현재상태만 봐서는 무엇을 테스트하려고하는지 직관적이지가 않아요. 테스트하고자하는 대상(actual)을 분리하고 assert에서 어떻게 값을 정제하여 잘 테스트할 수 있을지 고민해보면 좋을 것 같아요.

2024-02-26 12:27 UTC, jinyoungchoi95 commented on src/main/java/ladder/domain/Line.java
>      private List<StepStatus> createStepStatuses(Supplier<Boolean> generator, final int userCount) {
`generator`가 무엇을 생성하는 generator인지 명확하면 좋았을 것 같네요 :)

2024-02-26 12:27 UTC, jinyoungchoi95 commented on src/main/java/ladder/domain/GameResult.java
> +public class GameResult {
(반영하지 않으셔도 됩니다.) 단순히 게임 결과보다는 유저의 위치를 의미하는 `UserDestination`이 어떨까요?

2024-02-26 12:27 UTC, jinyoungchoi95 commented on src/main/java/ladder/domain/GameResult.java
> +    }
사용하는 곳 모두가 `getDestination().value()`를 호출하는데 `Destination` 타입을 반환할 이유가 있을까요?

(만약 이유가 있다면) 해당 클래스는 Record여도 되지 않을까요?

2024-02-26 12:27 UTC, jinyoungchoi95 commented on src/main/java/ladder/domain/GameResults.java
> +    private static List<GameResult> generateGameResults(
```suggestion
    private List<GameResult> generateGameResults(
```

2024-02-26 12:27 UTC, jinyoungchoi95 commented on src/main/java/ladder/domain/GameResults.java
> +        List<Destination> finalDestinations = new ArrayList<>(destinations);
`destinations`를 어짜피 그대로 사용하지 않는데 새로운 List를 생성할 필요가 있을까요?

2024-02-26 12:27 UTC, jinyoungchoi95 commented on src/main/java/ladder/domain/GameResults.java
> +            List<Destination> destinations) {
생성할 때 `Destinations`를 사용해도 되지 않을까요? `Destinations`가 단순 껍데기만 존재하는 일급 컬랙션인 상태여서 swap로직도 `Destinations`에 있어도 될 것 같아요.

2024-02-26 12:27 UTC, jinyoungchoi95 commented on src/main/java/ladder/domain/GameResults.java
> +                .filter(result -> result.getUserName().isSame(requestName))
`UserName`을 getter로 가져와서 로직을 처리하는 것이 아니라 `GameReult`가 처리할 수 있도록 메시지를 보내는 형태로 변경해주세요.

2024-02-26 12:27 UTC, jinyoungchoi95 commented on src/main/java/ladder/LadderGameMachine.java
> +    private UserNames initNames() {
init이라는 단어는 initialize, 초기화하다라는 의미에요. 여기는 최초 생성 혹은 입력을 하는 곳이니 초기화라는 단어와는 의미가 다르지 않을까요?

2024-02-26 12:27 UTC, jinyoungchoi95 commented on src/main/java/ladder/domain/RequestName.java
> +        boolean isNotAll = !requestName.equals("all");
"all"은 매직리터럴로 두기에는 의미를 가진 상수로 표현되면 좋을 것 같아요.

2024-02-27 06:05 UTC, Minjoo522 commented on src/main/java/ladder/domain/RequestName.java
> +        }
밑의 방법은 생각도 못했었는데 알려주셔서 감사합니다! ☺️

2024-02-27 06:14 UTC, Minjoo522 commented on src/main/java/ladder/domain/UserNames.java
> +    }
유효하지 않은 값이 들어오면 예외를 던지도록 변경하였습니다! 😊

2024-02-27 06:15 UTC, Minjoo522 commented on src/main/java/ladder/domain/UserNames.java
> +    public UserName findByOrder(final int order) {
`get`은 보통 자바에서 `getter` 메소드에서 사용된다고 알고 있습니다.
그래서 메소드 내부에서 특별한 로직이 없이 값을 리턴할 때는 `get`을 사용하고,
특정 값을 찾는다거나 값 중 일부만 리턴하는 경우 `get`이 아닌 다른 이름을 정의해서 사용하고 있습니다. 😊
`GameResults`의 `findAll` 메소드의 경우 그대로 값을 리턴하지만 `findByUserName`처럼 사용자로부터 요청 받은 결과를 찾을 때 사용하므로 네이밍을 비슷하게 사용해 주어야 호출 시 명확한 의도를 전달할 수 있다고 생각해 `find`를 사용하였습니다.

2024-02-27 06:39 UTC, Minjoo522 commented on src/test/java/ladder/domain/GameResultsTest.java
> +        assertThat(destinations).containsExactly("3000", "꽝");
`findAll`은 `GameResult`를 생성하고 필드에 저장된 `List<UserDestination>`를 리턴하는 메소드로,
다음과 같이 리턴된 `List<UserDestination>`에 값들이 제대로 저장되었고 모두 반환하는지 확인할 수 있도록 테스트 코드를 변경해보았습니다.

```java
@DisplayName("게임의 최종 결과를 모두 반환한다.")
@Test
void findAll() {
    assertThat(gameResults.findAll()).extracting("UserName").containsExactly("a", "b");
    assertThat(gameResults.findAll()).extracting("Destination").containsExactly("3000", "꽝");
}
```

2024-02-27 06:40 UTC, Minjoo522 commented on src/main/java/ladder/domain/Line.java
>      private List<StepStatus> createStepStatuses(Supplier<Boolean> generator, final int userCount) {
파라미터명을 `StepGenerator`로 변경하였습니다. 😊

2024-02-27 06:41 UTC, Minjoo522 commented on src/main/java/ladder/domain/GameResult.java
> +public class GameResult {
`UserDestination`으로 변경하였습니다.
변경하고 보니 의미가 더 명확하게 전달되는 것 같아요. 😆
감사합니다!

2024-02-27 06:42 UTC, Minjoo522 commented on src/main/java/ladder/domain/GameResult.java
> +    }
호출하는 곳에서 `getDestination().value()`를 호출하지 않고 `getDestination()`만 호출해서 사용할 수 있도록 `String` 타입을 반환하도록 변경하였습니다. 😊

2024-02-27 06:42 UTC, Minjoo522 commented on src/main/java/ladder/domain/GameResults.java
> +    private static List<GameResult> generateGameResults(
감사합니다! ☺️

2024-02-27 06:44 UTC, Minjoo522 commented on src/main/java/ladder/domain/GameResults.java
> +        List<Destination> finalDestinations = new ArrayList<>(destinations);
이 부분은 아래에서 List<Destination> 내부 값들을 swap하게 되는데, 파라미터로 들어온 destinations를 변경하는 것은 좋지 않다고 생각하여 새로운 List를 생성하여 새로 생성된 리스트를 swap해서 사용하도록 구현했습니다.

Swap 로직을 `Destinations`으로 옮기면서 아래 코드는 사라지게 되었습니다!
`List<Destination> finalDestinations = new ArrayList<>(destinations);`

2024-02-27 06:53 UTC, Minjoo522 commented on src/main/java/ladder/domain/GameResults.java
> +                .filter(result -> result.getUserName().isSame(requestName))
`isSameName` 메서드를 추가하여 메시지를 보내는 형태로 변경하였습니다!

2024-02-27 06:54 UTC, Minjoo522 commented on src/main/java/ladder/LadderGameMachine.java
> +    private UserNames initNames() {
감사합니다!
`register~`로 변경해 보았습니다. 😊

2024-02-27 06:54 UTC, Minjoo522 commented on src/main/java/ladder/domain/RequestName.java
> +        boolean isNotAll = !requestName.equals("all");
감사합니다!
상수로 변경하였습니다 ☺️

2024-02-27 07:00 UTC, Minjoo522 commented on src/main/java/ladder/domain/GameResults.java
> +            List<Destination> destinations) {
`Destinations`의 `swapDestinations`로 이동하였습니다!
해당 구현을 이동하면서 파라미터로 `Destinations`를 받는 것으로 변경하게 되었습니다.

그리고, `swapDestinations` 메소드에서 `Destinations`의 인스턴스를 새로 생성하여 리턴하도록 하였습니다.
`Destinations`에도 `UserNames`와 동일하게 `findByOrder` 메소드를 만들어 `GameResults`에서 게임 결과들을 생성할 때 `List`에 직접 `get`을 사용하지 않도록 변경하였습니다.

이 코드를 변경하면서`List<Destination>`을 리턴하는 게 나을지 아니면 지금처럼 새로운 `Destinations`를 생성해 리턴하는 게 나을지 고민 되었습니다. `Destinations`를 생성해 리턴하면 `Destinations`의 메서드들을 이용할 수 있다는 장점이 있지만, 현재는 사실상 `List`의 `get` 역할을 하는 `findByOrder` 메소드밖에 없기 때문에 고민되었습니다.
혹시 오리는 어떤 방식이 더 효율적이라고 생각하시는지 궁금합니다. 😊

`Destinations`
```java
public Destinations swapDestinations(final List<Integer> stepPositions) {
    List<Destination> swappedDestinations = new ArrayList<>(destinations);
    for (int position : stepPositions) {
        Collections.swap(swappedDestinations, position, position + 1);
    }
    return new Destinations(swappedDestinations);
}

public Destination findByOrder(final int order) {
    if (order < 0 || order >= destinations.size()) {
        throw new IndexOutOfBoundsException("유효하지 않은 값입니다.");
    }
    return destinations.get(order);
}
```

`GameResults`
```java
private List<UserDestination> generateGameResults(
        UserNames userNames,
        final List<Integer> stepPositions,
        Destinations destinations) {
    Destinations swappedDestinations = destinations.swapDestinations(stepPositions);
    return IntStream.range(0, userNames.getUserCount())
            .mapToObj(i -> new UserDestination(userNames.findByOrder(i), swappedDestinations.findByOrder(i)))
            .toList();
}
```

2024-02-27 07:27 UTC, Minjoo522 commented on docs/README.md
제가 TDD에 대해서 오해를 하고 있었던 것 같습니다. 😂
그동안 익숙하지 않아서 `TDD는 어렵다`라는 생각에 사로잡혀 있어서 TDD의 장점을 구체적으로 생각해보지 못했던 것 같습니다.
오리의 댓글을 보고 처음으로 제대로 `TDD로 하면서 장점은 없었나?`를 고민하게 되었습니다. 감사합니다. ☺️

어쩌면 설계가 변경되는 상황은 TDD로 하지 않았더라도 많았을 것 같고,
오히려 TDD를 하면서 초반에 기능 요구 사항을 정리하며 러프하게 하였던 설계를 구체화할 수 있었습니다.
`테스트 코드를 만들고 기능을 추가하다보면 그 기능을 위한 다른 기능이 필요해지는 경우`를 다르게 생각하면 설계를 구체화하는 과정이었던 것 같습니다. 😅

2024-02-27 07:37 UTC, Minjoo522 commented
안녕하세요, 오리!
빠르게 리뷰 해주셔서 감사합니다. 😊
코멘트 주신 내용 반영하였습니다. ☺️

2024-02-27 11:25 UTC, jinyoungchoi95 commented on src/main/java/ladder/domain/UserNames.java
> +    public UserName findByOrder(final int order) {
보통 `get`은 항상 값이 나오기를 기대하는 경우에 사용해요. 그래서 무언가 `Optional`한 값이 아니라면 무조건 값이 나오길 바라고, get을 호출했는데 값이 없는 경우에는 항상 값이 나오는 논리를 벗어나기 때문에 예외가 발생하는 것을 기대해요.

반대로 `find`는 있을수도 있고 없을 수도 있는 `Optional`한 반환값을 기대하고 사용해요. 물론 `Optional`을 반환한다고 그게 무조건 find를 쓰는 네이밍이라는 규칙이 있다거나 그런건 아닙니다. (관습을 쓰지말라고하는데 관습을을 자꾸 이야기하게 되네요. 관습적으로 쓰라고 말씀드리는 이야기는 아니고 이러한 네이밍들을 빈번히 사용하고 있다 정도로만 알고 넘어가셔도 좋을 것 같아요.)

https://stackoverflow.com/questions/2141818/method-names-for-getting-data
https://hyewoncc.github.io/optional-and-method-naming/ (spring과 관련된 내용을 제외하고 참고해주세요)

2024-02-27 11:27 UTC, jinyoungchoi95 commented on src/test/java/ladder/domain/GameResultsTest.java
> +        assertThat(destinations).containsExactly("3000", "꽝");
1. 검증하고자하는 값은 한번만 선언하여 아래에서 사용하는 것이 무엇을 테스트하는지 알 수 있어요.
2. 위의 assert문이 실패하면 아래를 결과를 알 수 없기 때문에 assertAll을 사용하는 것이 좋습니다.
```java
List<UserDestination> actual = gameResults.findAll()
assertAll(
    () -> assertThat(actual).extracting("UserName").containsExactly("a", "b")
// ...
);
```

2024-02-27 11:37 UTC, jinyoungchoi95 commented on src/main/java/ladder/domain/GameResults.java
> +            List<Destination> destinations) {
저는 지금 방법도 충분히 좋다라고 생각해요 :) 일급컬랙션을 만드는 이유는 컬랙션을 한번 래핑함으로써 필요한 기능만 제공할 수 있다는데에 의의가 있고, `findByOrder`에서 유효하지 않은 값을 컨트롤함으로써 필요한 기능을 잘 추가되어 사용하고 있는 것 같아요 😄

2024-02-27 11:40 UTC, jinyoungchoi95 requested changes
안녕하세요 리브 😄

미션 충분히 잘 마무리하신 것 같아 머지하려하는데 추가 코멘트에 궁금하신게 있을까하여 request change 드립니다. 확인 후 다시 리뷰요청 주세요.

감사합니다 🙇‍♂️

2024-02-28 11:39 UTC, Minjoo522 commented on src/test/java/ladder/domain/GameResultsTest.java
> +        assertThat(destinations).containsExactly("3000", "꽝");
감사합니다! 바로 반영하였습니다.

2024-02-28 12:11 UTC, Minjoo522 commented
안녕하세요, 오리 😊
리브입니다. 리뷰 감사합니다. ☺️

`assertAll`을 알고는 있었는데 그 동안 사용해 본 적이 없어서 유용성을 처음 알게 되었습니다.
알려 주신 바와 같이 테스트 코드에 적용하였습니다. 😆

메소드 이름도 `all`을 입력 받아서 가져오는 코드고 `findByUserName`과 비슷한 이름을 지어주었었지만,
오히려 다른 역할을 하거나 `GameResults`의 값 그대로가 아닌 다른 값을 리턴한다는 오해를 불러일으킬 여지가 있을 수 있다고 생각이 바뀌어 메소드명을 변경해 주었습니다. 😊

2024-02-28 13:04 UTC, jinyoungchoi95 approved these changes
안녕하세요 리브 😄

2단계 요구사항과 필요한 학습을 충분히 하신 것 같아 머지하겠습니다. 사다리 미션 기간동안 주고받았던 피드백이 앞으로 진행할 미션과 학습에 많은 도움이 되길 바랍니다 😄 

감사합니다 🙇‍♂️

2024-02-28 13:04 UTC, merged