[2단계 - 사다리 게임] 아루(이동훈) 미션 제출합니다.
woowacourse/java-ladder pull request #341
Opened 2024-02-26 09:27 UTC by donghoony

안녕하세요 스티치, 2단계 미션을 제출합니다! 주말은 잘 지내셨나요?

저번에 주셨던 리뷰 내용을 보고 반성했습니다. 프리코스 때 주어졌던 조건에서 헤매고 있었구나, 아직 프리코스에 살고 있었구나, 하고 요구사항에 존재하지 않는 재입력 관련 구현 사항들을 과감하게 삭제했습니다. 괜히 제가 필수 요구사항이 아닌 부분을 너무 신경쓰이게 한 것 같아 죄송하네요 😶

이번 2단계에서는 최대한 TDD 사이클을 지키고자 해당 사이클 단위로 커밋을 진행했고, 혹시나 빠진 테스트가 존재한다면 추가로 커밋하는 과정을 반복했습니다. 1단계에서의 페어 프로그래밍에서는 TDD를 엄격하게 지키지 않았지만, 첫 번째 리뷰를 받고 나서 다시 완전히 엎고 TDD를 진행하는 과정에서 불필요한 코드를 작성하지 않는 장점을 알게 되었어요. 해당 부분이 1단계 리뷰 이후에 추가됐던 사항들입니다.

초반 커밋들은 1단계의 리뷰들에 대한 반영 사항들이고, 구현할 때 잘 읽히는 방향으로 최대한 작성하고자 했습니다. 
사다리를 타는 방식은 `LadderIndexConverter`를 사용했습니다. 각 행을 읽으면서, `true`를 만나면 사다리를 잇는 두 열의 매핑 인덱스를 바꾸는 식으로 빠르게 계산할 수 있었어요. 하지만 실제로 사용될 때에는 매번 한 바퀴를 돌아서 성능 자체는 좋지 않은 듯합니다.

전체적인 패키지 구성도 변경하고자 했습니다. `Dto`는 도메인과 다른 패키지로 관리하도록 하고, `View`에서는 원시값을 사용하며, 이를 게임 흐름을 담당하는 `LadderGame`에서 열어서 주기로 했습니다.

각 객체가 자신의 일만을 하는지, 과도한 추상화나 불필요한 구현 사항은 없는지 확인해주시면 감사하겠습니다! 최대한 담백하게 작성하고 싶었는데, 기존에 있는 코드에 요구사항을 추가하는 것은 쉽지 않았던 부분이었습니다. 시간이 많이 남은 만큼, 계속해서 리뷰를 주고받으면서 개선하고 싶은 마음이예요. 잘 부탁드립니다 😊

2024-02-27 09:48 UTC, lxxjn0 requested changes
아루, 2단계 미션 구현하시느라 수고하셨습니다 👍🏼 

아루의 말대로 새롭게 TDD를 하시면서 적절히 구현하신 덕인지 불필요하게 존재하는 코드도 없어보이고 나름의 적절한 책임과 역할에 맞게 객체가 잘 분리되어 있는 것 같습니다!!

그리고 제가 보기엔 어느정도 클래스 분리를 잘 해두신 것 같은데 이번 미션의 코드가 복잡한 탓인지 조금 더 코드를 확인해봐야 할 것 같아요. 우선 간략한 부분들에 대해 피드백 드리고 추가로 더 리뷰 진행하면서 같이 알아봐도 좋을 것 같습니다.

여쭤보신 질문 중 LadderIndexConverter의 경우 리뷰 중에 답변을 작성해두었고 나머지 두 질문에 대해 간단하게 답변을 달아보겠습니다.

1. 사실 이 부분은 도메인을 어떻게 규정하느냐에 따라 다를 것 같아요. 누군가는 사다리를 이름과 결과 모두 포함한 범위로 둘 수도 있고 누군가는 단순히 사다리 자체만 두고 싶을 수도 있고요. 이건 아루의 선택의 문제라서 어떤 선택을 하던 상관이 없을 것 같습니다.
3. 이 부분도 마찬가지이긴 한데 전 지금처럼 구분해두는 것이 좋을 것 같다고 생각합니다. 단순히 코드상의 유사성을 가지고 있다는 것 뿐이지 비즈니스 상에서는 전혀 의미가 다른 두 영역이라고 생각합니다. 만약 두 코드를 합쳤는데 추후 이름에 대한 어떠한 비즈니스라던지, 결과에 대한 비즈니스가 따로 생긴다면 그땐 오히려 코드의 변경 작업이 더 커질 것 같습니다. 비즈니스에서의 관심사에 대해 도메인을 분리한다고 생각을 해주시면 좋을 것 같습니다.

2024-02-27 09:48 UTC, lxxjn0 commented on src/main/java/domain/ladder/Ladder.java
>  public class Ladder {
읽기 좋은 코드를 작성하는 방법 중 하나는 코드의 흐름에 맞게 배치하는 것입니다. 해당 클래스를 읽어보면 생성자의 `validateHasSameSize` 라는 메서드를 처음 찾게 됩니다. 그러나 해당 메서드는 클래스의 가장 마지막에 위치하기에 읽는 사람은 코드를 끝까지 훑어보아야지 해당 메서드를 찾을 수 있습니다.

이처럼 코드를 작성할 때 읽는 순서대로 코드를 배열한다면 더 가독성이 좋은 코드를 작성할 수 있습니다 :)

2024-02-27 09:48 UTC, lxxjn0 commented on src/main/java/view/InputView.java
> +    public List<String> readTokens() {
[질문] 해당 메서드의 이름을 바꾼 이유가 무엇일까요? 하는 역할은 기존과 마찬가지로 이름을 받아서 나누고 리스트로 반환하는 것으로 보여서요.

2024-02-27 09:48 UTC, lxxjn0 commented on src/main/java/view/InputView.java
> +    public List<String> readTokens() {
코드를 추가로 더 읽다보니 결과에 대한 값도 동일한 메서드로 받아오는 것으로 보이네요. 그렇다면 해당 메서드 내부의 변수명이나 구분자 상수 등을 적절한 이름으로 바꾸는 것이 어떨까요?

2024-02-27 09:48 UTC, lxxjn0 commented on src/main/java/domain/result/Results.java
> +    }
사소한 부분까지 꼼꼼하게 예외처리를 하였네요 👍🏼

2024-02-27 09:48 UTC, lxxjn0 commented on src/main/java/game/LadderGame.java
> +        if (playerName.equals("all")) {
"all"은 전체를 의미하는 값으로 보이는데 적절한 상수로 뽑는건 어떨까요?

2024-02-27 09:48 UTC, lxxjn0 commented on src/main/java/domain/ladder/LadderIndexConverter.java
> +public class LadderIndexConverter {
클래스 명은 converter인데 실제로는 결과 값을 저장하고 있는 객체인 것 같네요. 이름을 적절하게 한번 바꿔보는 것은 어떨까요?

2024-02-27 09:48 UTC, lxxjn0 commented on src/main/java/domain/ladder/Ladder.java
>      }
[질문] 해당 메서드의 반환값을 Map으로 하신 이유가 있을까요? 실제로는 resultIndex라는 리스트와 똑같은 Map을 반환하는 것으로 보여서요.

2024-02-27 10:33 UTC, donghoony commented on src/main/java/domain/ladder/Ladder.java
>  public class Ladder {
public - private 순서로 배치하려고 했는데, 이것도 어쩌면 컨벤션의 일부겠네요. 다음 미션부터는 페어와 적용해보겠습니다 👍🏼

2024-02-27 10:34 UTC, donghoony commented on src/main/java/view/InputView.java
> +    public List<String> readTokens() {
맞습니다, 결과를 함께 받아오면서 메서드명을 수정하게 되었어요. 다만 미처 내부를 확인하지 못했네요. 수정하겠습니다

2024-02-27 10:49 UTC, donghoony commented on src/main/java/domain/ladder/Ladder.java
>      }
너무 깊게 생각했네요. 해당 `List<Integer>`를 넘기도록 수정하겠습니다

2024-02-28 05:15 UTC, donghoony commented on src/main/java/game/LadderGame.java
> +        if (playerName.equals("all")) {
상수로 뽑고, 들어오는 `playerName`이 `null`일 가능성을 대비해 상수에서 비교하도록 변경합니다.

2024-02-28 05:23 UTC, donghoony commented on src/main/java/domain/ladder/LadderIndexConverter.java
> +public class LadderIndexConverter {
각 플레이어의 결과 인덱스를 저장하고 있으므로, `LadderResultIndexMapper`로 변경합니다!

2024-02-28 06:04 UTC, donghoony commented
안녕하세요 스티치! 말씀해주신 리뷰 사항을 수정하여 다시 요청드립니다 😊 점점 개선되어가고 있는 코드가 보여서 기쁘네요!

이번 수정사항에서는 `Map`을 삭제하고, 매핑하는 인덱스를 `List<Integer>`로 반환하도록 하였습니다. 하지만 이렇게 되니 아래와 같은 클래스 구조가 만들어졌어요.

`Ladder` 안에 `LadderResultIndexMapper`, 그 안에 `List<Integer>`. 이 리스트의 연산이 유의미하다고 생각해서 일급 컬렉션처럼 만들면 좋겠다는 생각을 해 보았어요. 하지만 실제 사용하는 클래스 안에 - 클래스 또 내부에 - 일급 컬렉션이 존재하는 설계가 이 상황에서 최선인지 궁금합니다. `Ladder`에서 해당 매핑 인덱스를 가져오기 위해서 저 하위 클래스까지 내려갔다 올라오는 것이 효율적인지에 대한 생각, 보다 나은 방법이 있을 것 같은데 잘 떠오르지 않아 답답한 마음이 들어요.

코드가 복잡하다는 이야기는 제 로직에 대한 설명이 부족한 것이라고도 할 수 있을 것 같습니다 😢 코드를 작성하면서 든 생각과, 비즈니스 로직 이해에 도움을 드릴 몇가지 도메인의 역할을 아래에 적어두겠습니다.

### 사다리 타기
우선 저는 결과를 계산할 때, 한 번에 모든 결과를 계산한 뒤에 꺼내오는 것이 효율적이라고 생각했어요. 사다리를 탈 때 가로줄을 만날 때마다 변경되는 것은 가로줄에 걸친 두 세로줄에 해당하는 사람의 결과가 됩니다. 따라서 해당 결과를 Swap하는 방식으로 구현했어요.
```
(기존 위에서 내려가는 Swap 방식)
A     B     C
|-----|     |      B     A     C
|     |-----|  ->  |     |-----|  ->  B     C     A 
1     2     3      1     2     3      1     2     3

(아래에서 올라오는 Swap 방식)   
A     B     C      A     B     C      A     B     C
|-----|     |      |-----|     |      3     1     2 
|     |-----|  ->  1     3     2  -> 
1     2     3      

(실제 매핑되는 사람-결과는 같지만, 사람의 인덱스로 결과에 접근할 수 있다는 이점이 있습니다)
```

하지만 사다리의 맨 윗 줄부터 Swap을 시작한다면, *각 결과에 대한 사람 인덱스* 가 매핑됩니다. 즉, `i`번째 인덱스에는 `i`번째 결과에 해당하는 사람의 인덱스가 들어가게 됩니다. 이렇게 작성하니 요구사항에서 원하는 *사람 이름으로 결과 찾기* 에 불편함이 생겼어요. 

이 문제를 거꾸로 생각해서 사다리의 맨 아랫줄부터 위로 올라오면서 순서를 바꿔주니 *각 사람에 대한 결과 인덱스* 가 매핑돼 요구사항에 응하는 구현이 되었습니다. 확실히 생각만 하고 코드를 짜서 이에 대한 배경이 없으면 이해하기 까다로웠을 것 같습니다. 복잡한 구현을 풀어낼 때, 따로 문서에 적어둬서 처음 보는 사람들도 이해하기 쉽도록 돕는 편이 좋겠습니다. 실제로 컨벤션 너머, 구현 사항을 추가로 명세하는 것이 도움이 될까요? 이런 문서 작성도 컨벤션일까요? 🤔🤔🤔

### 도메인
- `LadderRow`: 사다리 게임에서의 가장 작은 도메인 단위를 맡습니다. 사람의 수보다 1 적은 칸 (세로줄 사이의 공백)을 맡고 있으며, 외부에서 주어지는 `true/false`에 대해서 각 공간을 채울지, 말지 결정합니다. 단, `true`가 오더라도 이전에 채워져있다면 채우지 않습니다 (각 가로줄에 대한 유효성 검증)

- `LadderResultIndexMapper`: 위에서 설명한 **사다리 타기**의 구현을 맡습니다. 한 줄에 대한 Swap 연산을 담당하며, 추후 `Ladder`에 해당 인덱스를 전달합니다.

현재는 여러 번 사다리의 결과가 바뀌는 것을 고려하지 않았습니다. 만약 추후에 해당 기능이 필요로 한다면, `LadderResultIndexMapper`에서 매핑 인덱스를 초기화해야 합니다.
- 이와 같은 **추후 요구사항에 대한 대응 방안**이 떠오른다면 과거에는 해당 확장성을 고려해 구현했었습니다. 최근에는 생각이 많이 바뀌어 Trade-off를 많이 생각하게 되었어요. 이를 구현하지 않더라도 이런 미래의 To-do(?)들은 따로 적어두는 것이 좋을까요, 아니면 해당 요구사항이 실제로 들어오지 않았으니 고민하지 않는 것이 좋을까요?

이상입니다! 추가로 생각해봄직 한 내용이 있다면 자유롭게 말씀해주시면 고민해보겠습니다. 고맙습니다 😎

2024-02-29 08:19 UTC, lxxjn0 requested changes
아루, 피드백 반영하시느라 수고 많으셨습니다!!

작성해주신 코드 상에서는 더 이상 수정할만한 부분은 없는 것 같습니다!! 그러나 아루 개인적으로 아직 도메인에 대한 설계와 코드에 대한 아쉬움이 있으신 것 같아요. 리뷰를 남기기에는 변경된 코드에 대한 리뷰 작성만 진행되다보니 전체 코드에 대한 피드백을 드리기가 어렵습니다.

제가 전체 코드를 추가로 더 확인해보고 한번 생각해봄직한 부분에 대해서 코멘트를 추가로 남기기 위해서 MR은 아직 Request changes로 남겨두겠습니다! 추가적인 설명에 대해서는 DM으로 다시 연락드릴게요!!

2024-03-01 07:31 UTC, donghoony commented
안녕하세요 스티치! 세 번째 모래성을 쌓는 기분이라 힘들기도 하면서, 매번 다른 느낌이라 즐겁게 짰습니다 🏃🏻‍♂️ 다소 무모한 부탁이었지만 흔쾌히 제 생각을 펼칠 수 있도록 해 주셔서 고맙습니다, 이전 코드와도 비교해서 볼 수 있게 되는 장점이 있겠네요!

도메인 부분의 지식을 어느 정도 담으니 TDD를 할 때 수월했습니다. 이번 커밋에서는 따로 사이클별 커밋은 하지 않았지만, 테스트가 통과하는 최소 단위로 커밋하기 위해 노력했어요. 물론 TDD를 최대한 지키면서 진행했습니다. 도메인에 대한 지식이 앞선 몇 번의 시도로 있었기 때문에 `In-Out` 형식으로 많이 진행했던 것 같습니다 🙂

추가로 질문드릴 사항은 아래에 적겠습니다. 정말 고맙습니다 ! 

---

#### 일급 컬렉션의 필드명은 클래스명과 같아도 될까?
`Players`에서 가지는 `List<Player>`의 네이밍을 어떻게 해야할 지 고민이 되었습니다. 클래스와 필드명이 같으면 `getter`와 같은 부분에서 코드상의 중복 `Players.players()`등이 나타날 수 있고, 이를 지양하기 위해 웬만하면 다르게 짓는 듯했어요.

하지만 일급 컬렉션은 실제 `Collection`을 숨기고, 필요한 메서드와 기능을 열어 두는 것으로 이해했습니다. 따라서 해당 컬렉션을 밖으로 뽑을 일이 없으며, 같은 맥락에서 `getter`를 사용하는 것은 무리가 될 것이라고 보았어요. 필요하다면 요구사항에서 원하는 대로 정제해서 꺼내주는 것도 하나의 역할이라고 보았습니다. 필드명과 클래스명이 같아도 괜찮을까요?

---

#### 원시값은 꼭 포장해야 할까?
이번에는 인덱스를 표현하는 `Index`를 포장해 보다 안전한 연산을 하도록 했습니다. 다만 기존에 포장했던 `LadderHeight`을 포장하는 것이 옳은지에 대한 의문이 들어 이번에는 포장하지 않았습니다.
원시값 포장을 하는 이유를 생각해 보고, 이에 따른 포장에 대한 타당성을 생각해 보았어요.
- **타입 안전성** : 사다리 게임에서의 사다리 높이는 정수라는 고정 요구사항이 존재해 무의미하다고 판단했습니다.
- **역할 부여 (로직 수행 및 검증)** : 사다리를 만들 때의 단순 반복을 위한 대상이므로, 역할을 부여하는 것은 클래스를 분리하는 코스트에 비해 얻는 것이 크지 않다고 보았습니다.

위와 같은 장점을 온전히 가져갈 수 없을 것 같아 해당 부분을 포장하지 않기로 결정했어요. 자연스러운 생각의 흐름일까요?

---

#### 포장한 원시값은 어느 scope(context)까지만 쓰여야 할까?
`Index`를 어느 범위까지 써야 할까에 대한 고민도 있었습니다. 도메인의 내부 상황을 어디까지 알아야 하는가, 도메인 지식을 누구에게까지 요구해야 하는가로 귀결되는 문제라고 느꼈습니다. 패키지 구조도 `Ladder` 내부에 있는 `Index`였기 때문에, 결국 `LadderGame`에서는 원시값으로 사용하고 `Ladder` 내부에서만 `Index`를 사용하기로 했습니다. 게임의 흐름을 담당하는 곳까지 이 클래스를 사용하는 것도 무리가 없다고 보여지나요? (실제로 사용하기에는 꺼려질 것 같은데, 확실한 감이 오질 않습니다)

---

#### 일급 컬렉션에서 사용되는 도메인의 생성자 접근제어자를 `default`로 두어도 될까? (ex. `Players`에서 가지는 `Player`를 외부에서 생성하지 못하도록)
요즘 `default` 접근제어자를 통한 도메인 간 정보 교환이 원활하게 하는 것에 흥미를 보이고 있습니다. 같은 패키지 내에서는 자유롭게 도메인 정보를 오고가도록 하는 것인데요(패키지를 잘 나눈다는 가정이 필요하겠죠 👀), 실제로 이런 것을 자주 쓰는지, 혹은 의도를 가지고 `default` 생성자를 사용하는 일이 많은지 궁금합니다. 저는 실제 한 명의 `Player`를 외부에서 사용하지 못하도록 기본 접근제어자 생성자를 만들고, 같은 패키지의 `Players`에서 이를 활용하도록 했어요. 

---

#### `Ladder`는 `Players`, `Results`를 모르지만, 요구사항에서는 `Player`와 `Result`의 개수가 같아야 한다. 이를 검증하는 것은 `Ladder`인가?

이 부분은 아직 답이 나오지 않았고, 아무리 생각해도 `Ladder`에게 책임이 생기는 순간 의존성이 생기는 듯했어요. `Ladder`는 아니다! 라고 생각해 나온 결론이 `LadderGame`의 역할이 아닐까? 라는 생각이었습니다. 그래서 해당 부분은 게임 흐름을 담당하는 `LadderGame`에 검증 메서드를 하나 추가해 두었습니다. 이 부분의 생각 흐름도 자연스러운지 궁금해요.

조금 더 작게작게 생각하는 방법을 알게 되니 도메인 측면에서 많은 생각할거리가 나와서 뿌듯합니다. 더 좋은 방법이 있는지 궁금해지네요!

---

#### TDD를 적용하면서 생긴 생성자, 결국 테스트 코드에서만 작동한다?
`Line`을 생성하기 위해서는 생성자로 `Direction` 배열을 받고, 최초에는 이를 활용해서 테스트를 만들었습니다. 추가 요구사항인 **랜덤으로 한 줄 만들기**에서는 랜덤값을 주는 메서드를 외부에서 받아, 해당 값이 `true/false`에 따라 한 줄을 만들어야 했어요.
이렇게 요구사항을 지키기 위해서 TDD를 적용하다 보니, 기존 `Line`을 만드는 생성자가 테스트만을 위한 코드가 되어 버렸습니다. 해당 부분을 사용하는 테스트가 많다 보니, 생성자를 제거하는 것에도 무리가 있었어요. 솔직히 말해서, 외부에서 `Line` 값을 넣어줌으로써 얻는 테스트 이점이 너무 커, 프로덕션 코드에서의 변경이 손이 안 가기도 했습니다. 보통 이런 경우에는 *사용하지 않는 메서드* 니 삭제하는 편인가요? 🙄


처음부터 다시 작성하는 거라 리뷰를 요청드리는 것이 조심스럽습니다. 이전의 코드보다는 성능은 조금 떨어지겠지만, 각자의 일을 하고 있다고 생각해서 조금 나아진 듯해요. 읽히는 것도 자연스러웠으면 좋겠습니다. 잘 부탁드립니다 😊

2024-03-02 07:31 UTC, lxxjn0 approved these changes
아루, 사다리 타기 미션 진행하시느라 수고 많으셨습니다 👍🏼 

이번 미션은 여기서 마무리하는 걸로 할게요! 추가적인 피드백은 제가 DM으로 말씀드린 방향으로 진행하도록 하겠습니다!! 수고 많으셨습니다 :)

2024-03-02 07:31 UTC, merged