[2단계 - 사다리 게임] 짱수(장혁수) 미션 제출합니다.
woowacourse/java-ladder pull request #344
Opened 2024-02-26 11:19 UTC by zangsu

2024-02-27 12:35 UTC, summerlunaa requested changes
짱수 안녕하세요~

2단계도 잘 구현해주셨네요 👏 

몇가지 리뷰 남겼으니 확인부탁드립니다!

2024-02-27 12:35 UTC, summerlunaa commented on src/main/java/LadderGameController.java
> +        QUIT("종료");
> 요구사항에 존재하지 않는 기능 추가 :  "제 기준에서의 좋은 방향"을 위해 기능을 추가하는 것이 문제가 되지는 않을지 고민

제시된 요구사항을 모두 충족하는 선에서의 기능 추가는 얼마든지 가능하다고 생각합니다~
종료 조건을 추가한 건 좋은 방향으로 보여요 👍 

다만 제가 몇 가지 케이스를 테스트해보니 조금 불편한 부분이 있더라구요. 의도된건가요? (단순 궁금)
- `결과를 보고 싶은 사람은?`에서
   - 결과를 잘못 입력하면 바로 종료됨 (메뉴는 잘못 입력해도 종료되지 않더라구요)
   - all을 대문자로(ALL) 입력하면 종료됨

> View 와 Controller 만을 위해 존재하는 enum

입력을 위해 컨트롤러에서만 사용하는 enum이라면 여기 있어도 어색하진 않아 보여요. 다만 저였으면 클래스 마지막에 뒀을 것 같긴해요(클래스 마지막에 두는 경우만 봤었음). 주로 어디 위치시키는지는 잘 모르겠네요 🤔

2024-02-27 12:35 UTC, summerlunaa commented on src/main/java/LadderGameController.java
> +            }
**프로그래밍 요구 사항**
- indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.

일반적인 상황에서는 문제삼지 않았겠지만 요구 사항에 명시된 부분이기 때문에 수정해봅시다~

2024-02-27 12:35 UTC, summerlunaa commented on src/main/java/LadderGameController.java
> +        if ("all".equals(input)) {
대소문자 구분없이 비교하면 더 좋겠네요 👍

2024-02-27 12:35 UTC, summerlunaa commented on src/main/java/domain/GameResult.java
> +        }
꼼꼼한 예외 체크 좋습니다 👍 
다만 이 검증들이 LadderGame이 아니라 GameResult에 존재하는 이유가 있을까요?
사다리 생성까지 완료했는데 결과를 보려니 에러가 나는게 약간 어색하게 느껴져서요

2024-02-27 12:35 UTC, summerlunaa commented on src/main/java/domain/LadderGame.java
> +        return gameResult;
결과를 한 번만 계산하도록 하셨군요 💯

2024-02-27 12:35 UTC, summerlunaa commented on src/main/java/domain/ladder/Ladder.java
> +        List<Integer> list = new ArrayList<>();
의미있는 이름으로 변경해볼까요?

2024-02-27 12:35 UTC, summerlunaa commented on src/main/java/domain/ladder/Ladder.java
> +                .forEach((bridgeIndex) -> Collections.swap(list, bridgeIndex, bridgeIndex + 1));
다리가 연결된 곳의 index를 swap해서 결과를 찾는군요 오호 👍

2024-02-27 12:35 UTC, summerlunaa commented on src/main/java/domain/player/Name.java
> +    }
equals&hashCode 오버라이딩을 통한 동등성 보장 👍

2024-02-27 12:35 UTC, summerlunaa commented on src/main/java/domain/result/Prizes.java
> +                .map(prize -> prize.getPrizeName())
```suggestion
                .map(Prize::getPrizeName)
```

2024-02-27 12:35 UTC, summerlunaa commented on src/test/java/domain/GameResultTest.java
> +                        DEFAULT_LADDER_SIZE_OF_THREE));
조건이 문제인지 실제 로직이 문제인지를 확인하기 위해 조건에 대한 검증도 넣었군요 오호 이런 방법도 있군요

2024-02-27 12:35 UTC, summerlunaa commented on src/test/java/domain/GameResultTest.java
> +    @DisplayName("정상적으로 사다리게임이 생성된다.")
GameResultTest에서 사다리게임 생성 테스트를 진행하는 게 어색하네요 🤔

2024-02-27 12:35 UTC, summerlunaa commented on src/test/java/domain/GameResultTest.java
> +                    .isEqualTo(new Prize("5000"));
하나의 테스트에서 assertThat을 여러번 쓰면 어떤 문제가 발생할까요?
첫 줄에서 실패하면 두 번째 줄 이후로의 결과는 알 수 있을까요?

2024-02-27 12:35 UTC, summerlunaa commented on src/test/java/domain/GameResultTest.java
> 테스트 메서드 이름은 어느만큼 정확해야 하는가?

메서드명으로 테스트의 역할을 자세히 나타내는 데에는 한계가 있는 것 같아요. 그래서 DisplayName을 사용한다고 생각하구요.
저라면 `constructFailWithNameOver6`처럼 경계값을 적어주진 않을 것 같아요. 경계값이 바뀔 때마다 메서드명까지 신경써줘야 하니 더 관리가 힘들 것 같아요 🫠

> TDD를 활용한다면 Top-down VS Bottom-up??

도메인을 잘 이해하고 있다면 Bottom-up이 좋겠지만 그렇지 않은 상황에서는 Top-down 방식으로 갈 수 밖에 없죠. 사실 현실에서도 이런 상황이 왕왕 있구요;
현재로서는 Top-down 방식으로 진행하려면 `큰 TDD 사이클 안에 작은 TDD 사이클`을 가져가는 방법이 좋다고 저도 생각해요.
Name은 5글자를 넘으면 안 되고 어쩌고.. 하는 테스트를 짜기 전에 GameResultTest부터 만드는 거죠. 그리고 GameResult를 만드는 과정에서 Ladder를 나눠야겠다 싶을 때가 오면 Ladder 클래스를 분리하면서 LadderTest를 작성하는 방식으루요.

레벨2에 가면 ATDD, classist, mockist 등의 키워드들을 공부하면서 더 깊게 생각해볼 수 있을 거예용 (https://velog.io/@jhp1115/ATDD%EC%97%90%EC%84%9C-TDD-2%EC%A3%BC%EC%B0%A8)
지금은 이런게 있다~ 정도로 보고 넘어가시죠!

2024-02-29 11:07 UTC, zangsu reviewed
리뷰 반영했습니다!!

2024-02-29 11:07 UTC, zangsu commented on src/main/java/domain/GameResult.java
> +        }
우선, 해당 예외는 `LadderGame`에서 존재하는 것이 올바르다고 생각해 검증 위치를 옮겨주었습니다. 
동시에, 아래에 언급해 주신 `GameResultTest`에서 사다리 게임의 생성 테스트가 진행되었던 부분도 함께 리팩토링 진행해 주었습니다.

---
그런데, 혹시나 "사다리가 생성된 이후 예외가 발생하여 다시 이름부터 입력받아야 하는 상황"에 대한 피드백이 포함되어 있는 것 같아 이 부분에 대한 의견도 함께 작성해 두겠습니다.

저는 예외 처리 역시 해당 객체의 책임에 대해서만 진행을 해 주는 것이 가장 이상적이라고 생각했습니다.

"이름과 결과의 원소 개수가 같아야 한다" 라는 제약조건은 `Names`, 또는 `Prizes`의 책임이 아니라고 생각했어요. 이 제약사항들은 `Names`가 "사다리게임에 관여" 하게 되었기 때문에 생겨난 것이라고 느껴졌거든요.
또한, 반대로 사다리 게임이 아니라면 `Prizes`가 꼭 `Names`의 원소 개수와 동일한 개수의 원소를 가져야 할 필요가 있을까? 라고 생각을 해 본다면 저는 아니라고 답을 할 것 같았습니다.

물론, 파랑이 말씀하신 것 처럼 사다리 생성까지 완료가 되었는데 "이름과 결과의 개수가 같지 않기 때문에" 다시 처음부터 입력을 받아야 하는 상황이 자연스럽게 느껴지지는 않아요.
이 부분이 이번 어플리케이션에서 구현해야 할 중요한 부분은 아니라고 느껴지기 때문에 오랜 시간을 들여 고민을 해 보지는 않았지만, 어쩌면 빌더 패턴을 사용해 사다리 생성을 단계적으로 나누어서 진행해 줄 수도 있을 것 같다는 생각도 드네요. 

아직까지는 해당 검증들이 다른 객체로 이동해야 할 납득할만한 이유를 찾지는 못했기 때문에 이 모습 그대로 유지할 것 같습니다...!

2024-02-29 11:07 UTC, zangsu commented on src/main/java/domain/ladder/Ladder.java
> +                .forEach((bridgeIndex) -> Collections.swap(list, bridgeIndex, bridgeIndex + 1));
물론 아직 OOP를 고민할 단계가 아니긴 하지만, 너무 마음에 걸려서 가볍게 질문 드려봐요...!

이 부분을 구현하면서 "객체들간의 관계가 잘 나타나지 않나?", "성능을 위해서 가독성이 많이 나빠지진 않았나?" 등등의 고민이 들었는데요.
description에서도 작성해 둔 것 처럼, 객체들간의 관계가 가장 잘 나타나려면 `Player` 역할이 사다리를 통해 움직이는 것이 가장 이상적이라 느껴졌고, 해당 프로그램이 "좋은 성능"이라는 기준이 그렇게 중요한 기준도 아니라고 생각했거든요.

혹시 파랑은 이 부분의 코드가 괜찮으셨을까요??

2024-02-29 11:07 UTC, zangsu commented on src/test/java/domain/GameResultTest.java
두 질문 모두 어느 정도는 결론을 내려 둔 상태이지만, 제 결론에 대한 확신을 얻고 싶어 여쭤본 질문들인데요!!
다행히 제가 생각했던 결론과 같은 답을 얻게 되어서 오늘은 마음 편하게 잠들 수 있을 것 같습니다 ㅎㅎㅎ

올려주신 링크도 가볍게 훑어보면서 호기심을 조금은 해소할 수 있었던 것 같습니다 :D 
감사합니다!! 🙇‍♂️

2024-02-29 11:07 UTC, zangsu commented on src/test/java/domain/GameResultTest.java
> +                    .isEqualTo(new Prize("5000"));
아하, JUnit의 `assertAll()`이 있었네요!!!
곧바로 수정 후 커밋했습니다!!!

2024-02-29 11:07 UTC, zangsu commented on src/main/java/LadderGameController.java
> +        if ("all".equals(input)) {
해당 내용 리팩토링 완료하였습니다!

2024-02-29 11:07 UTC, zangsu commented on src/main/java/LadderGameController.java
> +            }
앗, 놓친 부분이 있었군요... 😞 
해당 부분 수정해 보았습니다.

그런데, 기능이 더 많아짐에 따라 입력 메뉴의 종류가 늘어난다면 현재 리팩토링한 방법만으로 요구사항을 준수하기 어려울 것 같아요.
그런 순간이 온다면 enum `Menu`에서 각각이 수행할 `LadderGameController`의 메서드를 `Runnable`, 또는 `Consumer` 등 필요한 함수형 인터페이스로 가지도록 할 것 같네요.

2024-02-29 11:07 UTC, zangsu commented on src/test/java/domain/GameResultTest.java
> +                    .isEqualTo(new Prize("5000"));
로직을 수정하면서 해당 부분을 다시 `@ParameterizedTest`로 리팩토링 하였습니다!

2024-02-29 11:07 UTC, zangsu commented on src/test/java/domain/GameResultTest.java
> +    @DisplayName("정상적으로 사다리게임이 생성된다.")
구조 변경으로 `GameResultTest` 역시 삭제되었습니다.

2024-02-29 11:07 UTC, zangsu commented on src/main/java/domain/ladder/Ladder.java
> +        List<Integer> list = new ArrayList<>();
네이밍은 정말 어려운 것 같습니다..ㅎㅎ
구조가 변경되면서 많은 메서드들이 바뀌었는데요. 사라진 메서드도, 새로 생긴 메서드도 존재합니다.
최대한 직관적인 네이밍을 하려 노력하였는데, 아직 조금 부족한 것 같아요. 한번만 더 확인 해 주시면 감사하겠습니다!!

2024-02-29 11:07 UTC, zangsu commented on src/main/java/LadderGameController.java
> +        QUIT("종료");
>- 결과를 보고 싶은 사람은?에서
>    - 결과를 잘못 입력하면 바로 종료됨 (메뉴는 잘못 입력해도 종료되지 않더라구요)
>    - all을 대문자로(ALL) 입력하면 종료됨

두 케이스 모두 제가 미처 생각하지 못하고 놓쳤던 부분이라서 예외 처리를 해 주었습니다. 
추가적으로, 다음 조건들을 처리해 주었습니다.
- 이름으로 "all", "ALL" 등의 이름을 사용할 수 없다.
- 중복된 이름을 사용할 수 없다.

---
enum의 위치는 일단 이대로 두겠습니다!

2024-02-29 12:41 UTC, summerlunaa commented on src/main/java/domain/GameResult.java
> +        }
"사다리가 생성된 이후 예외가 발생하여 다시 이름부터 입력받아야 하는 상황"에 대한 피드백은 아니었습니다 😅
시스템 내부에서 LadderGame은 문제 없이 생성되었는데, GameResult에서 이름, 결과 개수에 대한 검증을 진행하고 에러를 던지는 게 어색해서 리뷰드렸어요. 수정된 코드 확인해보니 검증 로직들이 LadderGame으로 옮겨갔네요! 역할이 잘 맞는 것 같습니다.
자세한 설명도 감사합니다ㅎㅎㅎ 👍

2024-02-29 13:13 UTC, summerlunaa requested changes
짱수 안녕하세요~

이제 더 이상 크게 수정할 부분은 없어 보여요~ 리뷰도 다 잘 반영해주셨고 리뷰 안 드린 부분도 깔끔하게 리팩토링해주셨네요 👍 

다만 리팩토링하면서 추가된 검증에 대한 테스트가 빠져있어서 RC 드립니다 🥲 리팩토링도 TDD 방식으로 진행해주세요~~

2024-02-29 13:13 UTC, summerlunaa commented on src/main/java/domain/LadderGame.java
> +        }
리팩토링도 TDD 방식으로 진행하셨나요~? 추가된 검증에 대한 테스트가 빠져 있어요.

2024-02-29 13:13 UTC, summerlunaa commented on src/main/java/domain/ladder/Ladder.java
> +    private final List<Bridges> bridges;
다시보니 Bridges의 List인데 이름이 Bridges인 것도 조금 어색하네요ㅎㅎ

2024-02-29 13:15 UTC, summerlunaa commented on src/main/java/domain/ladder/Ladder.java
> +                .forEach((bridgeIndex) -> Collections.swap(list, bridgeIndex, bridgeIndex + 1));
넵 저는 쉽게 이해되는 코드였습니다 👍  
이번에 리팩토링하면서 moveAllMovableIndex를 Bridges로 옮기셨는데 이 부분도 적절해보이구요.
유지보수를 생각했을때 성능의 차이가 크지 않다면 가독성을 높이는 게 더 좋다고 생각해요.

2024-03-02 06:49 UTC, zangsu commented on src/main/java/domain/LadderGame.java
> +        }
정신없이 리팩토링을 진행하다 보니, 문득 생각난 추가해야 할 기능들에 대해 TDD 방식을 적용하지 않았던 것 같아요.
구현을 하던 도중에 '아차!'하는 생각이 들었지만 이미 기능 구현이 마무리 되는 단계에서 갑자기 TDD로 돌아가는 것 또한 의미가 없을 것 같아 그대로 진행했었는데요.
귀신같이 TDD를 신경쓰지 않으니 테스트가 누락되었네요...ㅎㅎ
TDD가 현재 구현하고자 하는 기능에 대한 문서의 역할과, 구현이 완료된 기능에 대한 검증의 역할을 동시에 해 줄 수 있다는 것을 다시 한번 기억하고 넘어갑니다...!

2024-03-02 06:50 UTC, zangsu commented on src/main/java/domain/ladder/Ladder.java
> +    private final List<Bridges> bridges;
동의합니다.
해당 역할에 대해 아래와 같은 기준을 적용하여 네이밍을 수정해 보았습니다!

- List<Bridge> 형태가 "여러개의 Bridge" 라는 의미로 동작해야 할 때는 bridges 라는 네이밍을 사용
- List<Bridge> 형태가 한 층으로 동작해야 할 때는 line 이라는 네이밍을 사용

2024-03-02 13:38 UTC, summerlunaa commented on src/main/java/domain/LadderGame.java
> +        }
이번 경험을 통해 TDD의 필요성을 다시 느끼셨으니 오히려 좋습니다 ㅎㅎ 👍

2024-03-02 13:42 UTC, summerlunaa approved these changes
짱수 안녕하세요~~

이제 정말 완벽한 코드가 되었습니다ㅎㅎ 마지막 테스트 추가까지 수고하셨습니다. TDD의 필요성을 체감하는 계기가 되었길 바라며~~ 이만 머지하겠습니다. 

두 번째 미션 사다리 게임도 너무 수고하셨습니다 👏 👍

2024-03-02 13:42 UTC, summerlunaa commented on src/test/java/domain/player/NamesTest.java
> +        assertThatThrownBy(() -> new Names(List.of("파랑", "파랑")));
파랑 🐳 파랑 🐳 누락된 테스트들이 모두 추가되었네요~! 확인했습니다 👍

2024-03-02 13:43 UTC, merged