[사다리 게임] 아지가 미션 제출합니다.
woowacourse/java-ladder pull request #35
Opened 2019-05-18 01:20 UTC by wiseoldster

TDD가 초반에 무슨 테스트를 해야하는지 결정하는 데 시간이 엄청 많이 걸려 속도가 너무 느려서 초반엔 불만이 많았습니다. 테스트를 위한 구조를 설계하는 과정이 미숙하기도 하여서 많은 고민을 해본 미션이었습니다. 설계에 시간을 많이 보내니 설계하는 과정간 도메인에 대한 이해가 쌓였는지 설계가 어느정도 틀이 잡힌 뒤에는 빠른 속도로 코드를 작성 할 수 있었습니다. 설계의 중요성에 대해 몸으로 많이 배운 미션이었습니다.

2019-05-18 09:00 UTC, pobiconan requested changes
전체적인 객체 설계, 클린코드 구현, 테스트 코드 구현 💯
단, LadderGame의 구조가 너무 복잡해서인지 테스트하기 너무 어려운 점이 있어 보이네요.
좀 더 테스트하기 쉬운 구조로 개선할 방법이 있는지 찾아보면 좋겠어요.
바로 앞에 준 피드백과 같은 피드백이네요.

2019-05-18 09:00 UTC, pobiconan commented on src/main/java/ladder/LadderGameApplication.java
> +        String[] names = InputView.getNames();
특별한 이유가 있지 않는 경우 배열보다는 List Collection 사용할 것을 추천한다.

2019-05-18 09:00 UTC, pobiconan commented on src/main/java/ladder/LadderGameApplication.java
> +        String[] drawResults = InputView.getDrawResults();
일급 콜렉션 원칙을 적용해 구현해 본다.

2019-05-18 09:00 UTC, pobiconan commented on src/main/java/ladder/LadderGameApplication.java
> +        LadderGame ladderGame = new LadderGame(names, drawResults, new LadderGenerator().makeLadder(names.length, countOfLines));
GameResult result = ladder.play(gamePlayers, playerRewards)와 같이 구현하는 것은 어떨까?
현재 구현과 어떤 점이 달라질까?

2019-05-18 09:00 UTC, pobiconan commented on src/main/java/ladder/domain/DrawResult.java
> +
불필요하게 공백 라인을 만들지 않는다.
공백 라인을 뛰우는 것도 코드상에 문맥이 달라지는 부분에 의도를 가지고 뛰우면 좋겠다.

2019-05-18 09:00 UTC, pobiconan commented on src/main/java/ladder/domain/LadderGame.java
> +    private GameResult gameResult;
인스턴스 변수가 너무 많다. 인스턴스 변수를 줄여본다.
중복되는 인스턴스 변수는 없는지 검토해 본다.

2019-05-18 09:00 UTC, pobiconan commented on src/main/java/ladder/domain/Line.java
> +    Record drawLine(Record record) {
이 메소드 복잡도가 너무 높은 것 같다.
좀 더 단순하게 구현할 방법이 없을까?

2019-05-18 09:00 UTC, pobiconan commented on src/main/java/ladder/domain/Line.java
> +public class Line {
수업 중 다룬 Point와 같이 더 작은 단위의 객체를 추가해 도전해 보면 어떨까?

2019-05-18 09:00 UTC, pobiconan commented on src/main/java/ladder/domain/Line.java
> +    private static final String DEFAULT_BAR = "|";
UI 관련 코드인데 굳이 상수로 구현하기 보다 이런 코드는 toString()에 하드코딩하는 것이 더 좋지 않을까?

2019-05-18 09:00 UTC, pobiconan commented on src/main/java/ladder/domain/Record.java
> +        return indices;
List를 외부에 공개하는 경우 외부에서 수정/삭제할 위험성이 있다.
따라서 외부에 공개할 때는 수정하지 못하도록 java.util.Collections.unmodifiableList() 사용해 반환할 것을 추천한다.

2019-05-18 09:00 UTC, pobiconan commented on src/test/java/ladder/domain/GameResultTest.java
> +
불필요하게 공백 라인을 만들지 않는다.
공백 라인을 뛰우는 것도 코드상에 문맥이 달라지는 부분에 의도를 가지고 뛰우면 좋겠다.

2019-05-18 09:00 UTC, pobiconan commented on src/test/java/ladder/domain/LadderGameTest.java
> +        ladderGame.play();
LadderGame 테스트를 위해 데이터 초기화 과정이 너무 복잡하다.
여기서 힌트를 얻어 LadderGame의 구조를 좀 더 개선해 볼 방법이 없는지 고민해 보면 좋겠다.

2019-05-18 09:03 UTC, wiseoldster commented on src/main/java/ladder/domain/Line.java
> +    private static final String DEFAULT_BAR = "|";
toString에는 하드코딩이 허용 되는군요!

2019-05-20 07:29 UTC, wiseoldster commented on src/test/java/ladder/domain/LadderGameTest.java
> +        ladderGame.play();
커스텀 레더를 만들어 테스트 하기 위해 생성자에서 랜덤한 부분을 분리하기 위해 LadderGenerator를 활용해 분리했습니다. 
사다리 생성자를 오버로딩하거나  LadderGenerator에 커스텀 래더를 만드는 메소드를 추가하는 것은 정답이 아닐 것 같은데 조금 더 직설적인 힌트를 받을 수 있을까요?

2019-05-20 07:49 UTC, pobiconan requested changes
전체적인 구조는 이전에 비해 상당히 많이 개선됐네요. 💯 
더 개선할 부분이 있을지 생각해 봤으면 하는 바람으로 피드백 하나 남겨봅니다.

2019-05-20 07:49 UTC, pobiconan commented on src/main/java/ladder/LadderGameApplication.java
>      public static void main(String[] args) {
사다리 타기의 전체 흐름을 다음과 같은 구조로 구현해 보는 것은 어떨까?
main()은 MVC에서 Controller의 역할로 가능한 가볍게 구현해야 한다.
Controller 내에는 로직은 최대한 배제하고 Model과 View 사이의 연결 역할만 하도록 구현한다.

```java
public static void main(String[] args) throws Exception {
    Players players = InputView.createPlayers();
    Rewards rewards = InputView.createRewards();

    Ladder ladder = LadderFactory.createLadder(players.countOfPeople(), InputView.getHeight());
    OutputView.printLadder(players, ladder, rewards);

    MatchingResult matchingResult = ladder.play();
    LadderResult result = matchingResult.map(players, rewards);

    OutputView.printResult(result);
}
```

MatchingResult는 Map<Integer, Integer>에 대한 일급콜렉션 객체이다.
Map의 key는 시작 위치, values는 사다리를 실행한 결과 위치이다.

LadderResult는 위치 값만 가지고 있는 MatchingResult의 값을 이름과 결과로 매핑한 결과를 가지는 일급콜렉션 객체이다.

반드시 위와 같은 구조로 개발하지 않아도 된다.
단, 위 코드 힌트를 참고해 개선할 부분이 있으면 개선해 본다.

2019-05-20 07:59 UTC, wiseoldster commented on src/main/java/ladder/LadderGameApplication.java
>      public static void main(String[] args) {
MVC 패턴에서 View에서 Domain의 인스턴스를 생성해도 되나요?

2019-05-20 08:57 UTC, wiseoldster commented on src/main/java/ladder/LadderGameApplication.java
>      public static void main(String[] args) {
MatchingResult 대신 List<Integer>에 대한 Record를 사용해도 될까요?

2019-05-20 08:58 UTC, wiseoldster commented on src/main/java/ladder/LadderGameApplication.java
>      public static void main(String[] args) {
또 Ladder 안에 숨겨도 되지 않을까요?

2019-05-21 00:17 UTC, pobiconan approved these changes
마지막 피드백이 약간 무리할 수도 있었는데 자신의 스타일을 유지하면 구현 잘 했네요. 💯 
이번 미션을 통해 객체지향 설계와 TDD의 맛을 느꼈기를 기대해 봅니다.

2019-05-21 00:17 UTC, merged

2019-05-26 04:07 UTC, wiseoldster commented on src/test/java/ladder/domain/GameResultTest.java
> +
참조++

2019-05-26 04:07 UTC, wiseoldster commented on src/main/java/ladder/domain/Record.java
> +        return indices;
참조++