[2단계 - 사다리 게임] 시소(신지송) 미션 제출합니다.
woowacourse/java-ladder pull request #350
Opened 2024-02-27 08:22 UTC by shin-jisong

웨지 안녕하세요! 🥔 또 다시 BE 6기 시소입니다. 😊
이번에는 일급 컬렉션과 원시값 포장에 대한 개념 혼동으로 스스로 더 명확하게 이해하는 시간을 진행하였습니다.
웨지의 도움 덕분에 조금은 가까워진 것 같아 감사합니다. 👏
잘 부탁드리며, 좋은 하루 보내시길 바랍니다! ☘️

**이번 미션을 진행하면서**
어디까지 클래스를 분리할지에 대한 고민을 진행하며
step1과 비교하여 추가된 클래스는 LadderResult 클래스와 Prizes 클래스입니다.
각 설명은 README.md에 작성해 두었습니다!

**코드를 작성할 때 신경 쓴 점**
ladderResult 클래스의 경우에는 필드값에서도 알 수 있다시피 출발 지점과 사다리를 끝낸 후 마지막 지점을 알 수 있습니다.
이름과 Prize를 Map으로 저장할까의 고민이 있었으나
Name의 경우 Participants에 저장되어 있고, Prize의 경우 Prizes에서 저장하는 정보들이므로
중복 저장을 방지하고 또 각자의 독립성을 유지하고자 LadderResult는 오직 사다리 처음과 끝만을 저장하도록 구현하였습니다.
또한 해당 클래스에서 모든 유저들은 각 층마다 이동 가능한 위치를 계산하여 끝에 도달하면 이동을 멈추는 구조로 작성하였습니다.

**질문 드릴 것들**
- 생성자로 객체를 보내는 것이 적절한가?
각 객체가 생성할 때에 다른 객체의 정보가 필요한 경우가 있습니다.
getter를 통해 값을 보내는 것이 적절한가, 객체 자체를 보내서 메시지를 주고받을 수 있게 하냐의 고민이 있었습니다.
예를 들어 Prizes 클래스를 참고하면 participantsSize를 통하여 검증을 하여야 하는데
메시지를 주고받는 방식을 채택할 경우 input에서 검증을 진행하여야 합니다.
직접 값을 보낼 경우 getter를 사용하여야 하고, 객체가 스스로 검증하게 해 주려면 객체를 보내야 합니다.
각 방식 중 어느것이 가장 적절하다고 생각하시는지 궁금합니다!

- getter 사용 지양의 문제?
저는 각 객체에서는 다른 객체의 getter를 사용하지 않기 위해서 메시지를 주고받는 형식을 채택하였습니다.
예를 들어 participants에서 해당 이름이 List<Name>에 있는지 확인하는 로직을 짜려고 할 때 해당 이름이랑 같은지 묻는 isSameName 함수를 도입하였습니다.
하지만 일부 크루들의 의견은, 이미 Participants가 갖고 있는 정보이며 값을 조회하는 로직에서 getter를 사용하지 않으려고 다른 함수를 도입하는 것은 불필요하다는 의견이었습니다!

2024-02-27 16:14 UTC, sihyung92 requested changes
안녕하세요 시소! 리뷰어 웨지입니다!

리뷰가 너무 길어지는 것 같아 중간 결산을 했습니다 🙇‍♂️ 반영후 요청주시면 이어서 보겠습니다!
[Q&A]
- 생성자로 객체 보내는 것에 대해
  - 저는 객체로 받는 게 좋다고 생각합니다! 대신 Participants가 먼저 생성되어야 하는 로직이 되므로, 이런 순서 (생애주기 라고도 합니다) 가 적절한지에 대한 고려는 필요합니다

- getter 사용 지양의 문제?
   - 질문이 정확히 이해되진 않았습니다만, pariticipants에서 isSameName 같은 경우 Name.equals 로도 표현이 가능하니, 그쪽으로 리팩토링 하는 것을 권장드립니다! 또한 getter를 지양하는 코딩을 하기위해 노력하다보면 객체지향적인 코딩에 가까워지는게 있습니다. getter를 사용하는 걸 피할 필요는 없지만 정보를 가지고 있는 객체가 직접 행동을 수행하는 방향으로 코드를 짜려고 연습해보는 걸 권장드립니다! 혹시 제대로 답변이 안 되었다면 말씀주셔요.

리뷰 중 이해 안되는 내용이 있으시다면 언제든 DM주세요~! 기다리겠습니다!

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/domain/Ladder.java
> +    Height height;
접근제어자가와 final이 없습니당!!

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/controller/LadderGame.java
> +import java.util.stream.IntStream;
미처 정리되지 않은 import가 있습니당!!

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/domain/LadderResult.java
> +    private void canMove(Ladder ladder, int floor, int i) {
메서드명은 canMove, 마치 boolean을 반환할거 같은 메서드명인데 실제로는 상태에 대한 제어 (필드값을 변경) 하고 있어서 혼동을 줄 수 있습니다!
move() 처럼 명확히 상태를 변경한다는 네이밍이 좋다고 생각해요.

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/exception/domain/PrizesExceptionMessage.java
> +public enum PrizesExceptionMessage {
https://github.com/woowacourse/java-ladder/pull/271#discussion_r1501360566
혹시 step1의 리뷰를 놓치셨을까봐 옮깁니다!
일단 메시지 enum을 활용하시는 방안으로 선택하셨을까요?

https://github.com/woowacourse/java-ladder/pull/271#discussion_r1499392532
원본 리뷰에서 각 파일이라고 언급 한 부분으로 인해 분리되었다는 느낌도 있는데요, 
여기서 각 파일은 실제로 excetpion을 throw 하는 부분에서 해당 메시지를 직접 던지는 걸 의도했습니다! (설명이 모호해 죄송합니다)

그래서 제가 권장하는 방안은 2가지 인데요,
1. 예외를 던지는 클래스에서 직접 메시지 관리
2. 커스텀 예외 생성 후 메시지 관리 

현재 방식은 기존의 Message가 모여있던 enum인 "예외 메시지가 한 곳에 몰려있어 전체 예외메시지를 파악하기 편하다" (큰 장점은 아니라고 생각합니다) 의 장점도 잃어버려서, 
클래스에서 예외 메시지를 확인하려면 enum을 확인하러 와야하는 불편함만 남았다고 생각합니다

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/controller/LadderGame.java
> +        LadderResult ladderResult = new LadderResult(ladder, participants.getParticipantsCount());
controller가 도메인의 역할을 수행하는 부분이라는 생각이 드는데요,
"사다리 결과 보기"는 도메인의 핵심기능인데 
컨트롤러에서 Result를 직접 생성한다면, 뷰와 컨트롤러가 늘어날 때마다 이런 Result 생성방식을 복제해주어야 합니다.
게임을 진행하고 결과를 출력해주는 flow는 도메인쪽에 있어야 한다고 생각해요.

LadderGame 과 LadderController의 역할을 분리하거나, 
Ladder가 Result를 생산하는 책임을 가지거나
하는 식의 역할 분리가 있었으면 합니다.

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/view/OutputView.java
> +        IntStream.range(0, participants.getParticipantsCount())
for문 대신 IntStream을 선호하시는거 같습니다. 혹시 이유가 있을까요?

스트림 생성비용과 가독성을 같이 생각해보면 스트림을 사용하는데서 오는 이득이 적을거 같습니다.
대부분의 개발자는 for loop에 매우 익숙하기 때문에, for loop로 충분한 상황에서 stream이 지원하는 함수형 기능들을 제대로 활용하는 것이 아닌데 stream을 사용하는 건 현업에서 리뷰의 대상이 될 확률이 매우 높습니다 🥲

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/domain/LadderResult.java
> +                .collect(Collectors.toMap(i -> i, i -> i));
Function 구현체엔 identity()라고 하는, 인자를 그대로 제공하는 메서드를 제공합니다
```suggestion
        this.firstAndLastPosition = IntStream.range(0, participantsCount)
                .boxed()
                .collect(Collectors.toMap(Function.identity(),Function.identity()));
```

static import를 활용하면 더욱 축약할 수 있습니다
```suggestion
    private void initPosition(Ladder ladder, int participantsCount) {
        this.firstAndLastPosition = IntStream.range(0, participantsCount)
                .boxed()
                .collect(toMap(identity(), identity()));
    }
```

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/domain/Line.java
>      private final List<StepPoint> stepPoints = new ArrayList<>();
초기화가 두 곳으로 분리되어 있는데, 생성자 쪽에 몰려있으면 초기화 로직을 한눈에 파악할 수 있을거 같습니다.
```suggestion
    private final List<StepPoint> stepPoints;

    public Line(int numberOfCell, StepGenerator stepGenerator) {
        List<StepPoint> stepPoints = new ArrayList<>();
        stepPoints.add(stepGenerator.generate());
        for (int cellIndex = 1; cellIndex < numberOfCell; cellIndex++) {
            stepPoints.add(makeOnePoint(cellIndex, stepGenerator));
        }
        
        this.stepPoints = stepPoints;
    }

```

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/domain/Line.java
> +    public static final int ONE_STEP = 1;
google 자바 컨벤션에선 static 블록과 member 변수들 간에 한칸 띄워줄 것을 권장합니다!

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/domain/LadderResult.java
> +    private Map<Integer, Integer> firstAndLastPosition;
position은 원시값으로 도메인 내에서 다뤄지고 있네요. 원시값 랩핑을 해볼까요?

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/domain/LadderResult.java
> +    private void initPosition(Ladder ladder, int participantsCount) {
ladder는 활용하고 있지 않은 메서드이므로, ladder 인자가 제거되어도 좋겠습니다

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/domain/LadderResult.java
> +        calculatePosition(floor + 1, ladder, participantsCount);
재귀 코드는 가독성이 좋지 않아 도메인 구성에서 잘 활용되지 않습니다. 
알고리즘적인 해법으로만 해소가 가능할 경우에 주로 사용하므로 가능하다면 재귀 없이 해소해봐도 좋을거 같습니다.
해당 클래스 내부적으로 알고리즘 문제풀이 같은 느낌이 많이 드는데요 (원시값 사용, 재귀 코드)

Ladder가 canMoveLeft() / canMoveRight() 등 position이 어떤 방향으로 움직일 줄 안다는 정보를 가지고 있는데 이걸 public 메서드로 제공하고 다른 객체가 연산을 해야될 이유가 있는가? 하는 생각도 듭니다.

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/domain/LadderResult.java
> +public class LadderResult {
리뷰가 여러개였는데, 해당 객체가 일일이 리뷰를 반영하여 수정되는 것 보다 아래처럼 리팩토링 되었으면 좋겠습니다.
1. Position을 계산하는 로직은 Ladder 쪽에 있기를 희망합니다. (혹은 Ladder 게임을 진행시킨다는 느낌이 연상되는 네이밍의 객체) 
    -  LadderResult에선 '연산이 끝난 결과 자료구조'가 연상됩니다. 이 연상에 맞게 불변한 결과 자료구조 객체로 구현되었으면 합니다   
2. point를 상징하는 Integer 값은 원시값 랩핑을 하고, 그에 맞는 불변식(0보다 작을 수 없음 등) 을 설정해주셨으면 합니다

여기에 대한 논의는 환영입니다! 리팩토링 전 논의를 원하시면 따로 DM 주세요.

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/domain/Height.java
> +    private final int height;
여기도 개행이 있으면 더 읽기 좋을 것 같습니다

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/domain/Height.java
그리고 원시값 랩핑이 된 객체를 꼭 1개의 도메인 객체 안 쪽에서만 한정해서 사용할 필요는 없습니다. 도메인 내에서 동일한 의미를 상징하는 값이 있다면, 랩핑 객체를 최대한 활용하는 게 좋습니다.

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/domain/Ladder.java
> +    public boolean isFinish(int floor) {
직전 리뷰는 여기를 위한 리뷰입니다. int floor 대신 Height floor로 받아보는 건 어떨까요?
```java
    public boolean isFinish(Height floor) {
        return height.equals(floor);
    }
```

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/domain/Ladder.java
> +        return height.isEnd(floor);
원시값 랩핑 객체는 도메인 객체 보다는 원시값에 맞게 행동해주는 게 좋습니다. 
.isEnd() 보다는 마치 숫자를 비교하듯이, 
랩핑을 안 했으면 `height == floor` 로 구현을 했을테니 그 관점에 맞추어 
`height.isEqualTo(floor)` 로 구현되는 편이 좋습니다. (객체간 == 비교는 불가하기 때문입니다)

(height.minus(floor) / height.biggerThan(floor) 등 원시값 연산에 걸맞는 메서드들은 아주 좋습니다)

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/domain/Height.java
원시값 랩핑은 equals와 hashcode 구현은 필수적이고, toString 또한 거의 필수적입니다.
왜 그럴지 직전 리뷰와 빗대어 생각해보셔요.

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/domain/Name.java
>  public class Name {
해당 객체도 원시값 랩핑 객체이니 equals, hashcode, toString을 구현해주셔요.

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/domain/Name.java
> +    public static final String EXIT = "종료";
이거는 Console View에 종속적인 로직 같아요.
xml view나 json view, binary view에서도 종료를 상징하는 값이 "종료" 라는 네이밍으로 도착할까요?

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/domain/Prizes.java
> +    List<String> prizes;
접근제어자와 final이 설정되지 않았습니다!

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/domain/Prizes.java
> +    List<String> prizes;
그리고 원시값에 해당합니다! 
미션 요구사항이 모든 원시값을 랩핑하는 것이니 만큼 랩핑해주세요

2024-02-27 16:14 UTC, sihyung92 commented on src/main/java/controller/LadderGame.java
> +        ladder = makeLadder();
모두 run 로컬 변수 내부에서 활용되는 로컬 변수들인데, LadderGame의 상태까지 올라갈 필요가 없어보입니다! 
메서드도 이에맞춰 리팩토링 해주셔요 🙇‍♂️
```java
        Participants participants = recruitParticipants();
        Prizes prizes = decidePrizes(participants);
        Ladder ladder = makeLadder(participants);
```

2024-02-28 09:17 UTC, shin-jisong commented
세심한 리뷰 남겨 주셔서 감사합니다!
제안해 주신 방향 중 의견이 있는 것은 코멘트를 달아 두었고,
반영할 부분은 반영하여 다시 리뷰 드립니다.

LadderGameController와 LadderGame을 분리하면서 getter를 사용해야 할 경우가 있어서 불변 리스트로 return해 주었습니다만,
더 괜찮은 방향이 있다면 조언 주시면 좋겠습니다.

추가적으로, domain의 객체가 많아져서 따로 패지키를 분리하면 좋겠다는 생각이 들었는데 방대한 시스템은 아닐 뿐더러 같은 주제를 공유하는 프로젝트이기에 나누는 것이 불필요한가? 라는 의문이 있습니다.

2024-02-28 09:24 UTC, shin-jisong commented on src/main/java/domain/Height.java
해당 값들은 더 이상 기존과 달리 상태만으로 비교될 수 없으므로
포장된 채로 값을 비교할 수 있는 함수들을 구현해야 한다는 판단이 있었습니다!
추가 조언 있으시면 말씀 주세요. ㅎㅎ

2024-02-28 09:24 UTC, shin-jisong commented on src/main/java/domain/Ladder.java
> +    public boolean isFinish(int floor) {
해당 값을 사용하려고 하였는데 Height 객체 자체가 Ladder를 위하여 구현된 것이어서
validate를 진행하여 불필요한 validate를 진행하는 것을 확인하였습니다!
이동 과정에서는 0인 위치를 가질 수 있는데 해당 부분에서도 예외가 발생합니다
이렇게 되면 더 이상의 활용이 불가능한데, 혹시 포장할 필요가 없는 값이라 판단하시는지 궁금합니다

2024-02-28 09:24 UTC, shin-jisong commented on src/main/java/domain/Name.java
> +    public static final String EXIT = "종료";
저희의 구현은 Console View에서만 실행될 예정이므로 다른 View를 고려할 필요가 없다 생각하였습니다!

2024-02-28 09:24 UTC, shin-jisong commented on src/main/java/exception/domain/PrizesExceptionMessage.java
> +public enum PrizesExceptionMessage {
step2에서 더욱 많은 클래스가 생긴다면 모아볼 수 있고 재활용 가능성도 있을 것 같아서 해당 방향을 유지하였으나
웨지가 주신 의견을 참고하여 각 클래스에서 직접 관리하는 방향으로 변경하였습니다!

2024-02-28 09:24 UTC, shin-jisong commented on src/main/java/controller/LadderGame.java
> +        LadderResult ladderResult = new LadderResult(ladder, participants.getParticipantsCount());
해당 클래스를 살펴본 결과 Controller의 역할을 잃은 것이 맞다고 생각하여 LadderGame과 LadderGameController를 분리하였습니다 :)

2024-02-28 09:24 UTC, shin-jisong commented on src/main/java/view/OutputView.java
> +        IntStream.range(0, participants.getParticipantsCount())
stream의 경우, 저에게는 가독성이 더 좋아 보이는 경우도 있었고 멀티코어를 대상으로 하여 성능이 더 좋다는 판단도 있었습니다!
하지만 주신 리뷰를 보고 일부 코드에서는 오히려 가독성이 떨어지고 성능 또한 저하된다고 판단하여 수정하였습니다

2024-02-28 10:41 UTC, sihyung92 commented on src/main/java/domain/Name.java
> +    public static final String EXIT = "종료";
아하 그렇다면 MVC 패턴을 활용한 의미가 퇴색되지 않을까요?
MVC는 도메인은 덜 변하고, 뷰는 자주 변하므로 뷰의 변경으로부터 도메인을 보호하기 위한 패턴입니다. 
'뷰의 변경'이란 말은 단순히 뷰의 코드 수정도 있지만, 뷰를 plugin 처럼 다른 종류의 view도 갈아낄 수 있음을 시사합니다.

MVC 패턴을 지켜야하는 미션은 아니므로 꼭 분리할 필요는 없지만, console view 에서만 쓰일거라면 Controller 계층의 복잡성은 포기하고 바로 도메인과 view가 소통하는게 더 읽기 좋은 코드가 될거같습니다

2024-02-28 12:05 UTC, sihyung92 requested changes
안녕하세요 시소! 웨지입니다!

LadderResult 코드가 읽기 좋아졌습니다! 👍 고심하시고 코드를 리팩토링해주신 것 같습니다.
여러 긴 리뷰를 남겼는데, 확인해주시고 다시 요청주세요!

Q&A
Q. 객체 분리 중 getter를 사용하는 케이스가 생겨난 부분. 
A. 만약 getter를 사용하지 않았으면 분리가 불가능 했을텐데, getter를 사용하지 않아서 얻는 이득과 분리해서 얻을 수 있던 이득을 비교해보세요! 개발에서 대부분의 개념은 trade off입니다. 완벽한 것은 없으니 상황에 맞춰 유리하게 판단해야합니다!

Q. domain이 점점 많아져요
A. 네 저는 그러면 패키지를 분리해 정리해보는 것도 추천해드립니다! 당장은 시스템이 방대하지 않지만, 평소에 패키지에 대해 신경쓰지 않다가 갑자기 방대한 코드를 만났을 때 패키징에 대한 노하우가 저절로 생겨나진 않습니다! 미리 조금씩 연습한다는 느낌으로, 본인이 느끼기에 적합하다고 느끼는 패키지를 구성해보셔요!

궁금한건 질문 및 DM 주셔요! 감사합니다.

2024-02-28 12:05 UTC, sihyung92 commented on src/main/java/domain/Ladder.java
> +        if ((isFinish(floor))) {
괄호가 두 개 씩 있네용!
```suggestion
        if (isFinish(floor)) {
```

2024-02-28 12:05 UTC, sihyung92 commented on src/main/java/domain/Ladder.java
> +    public boolean isFinish(int floor) {
아하! 말씀하시는 부분 확인했습니다! 
저라면 이렇게 해볼거같아요!

1. Height는 0에서 100까지 가능합니다. (자주 쓰일거 같아 ZERO도 캐싱해둡니다)
```java
...
public static final Height ZERO = new Height(0);    
public static final int MIN_OF_HEIGHT = 0;
...
```

2. Ladder도 인자로 Height를 받습니다. 사다리를 만들 때 0 Height에 대한 validation을 추가합니다. 
```java
    public Ladder(Height floor, int participantsCount, StepGenerator stepGenerator) {
       // NPE를 방지하는 습관 - Null 이 아닌 것(상수 등)을 항상 앞으로 둡니다
       // 가독성이 떨어져 실제였다면 검증 코드는 메서드 분리를 했습니다
        if (Height.ZERO.equals(floor)) {
            throw new IllegalArgumentException("높이가 0인 사다리는 불가능합니다.");
        }
        int stepPointCount = participantsCount - 1;
        this.height = floor;
        lines = Stream.generate(() -> new Line(stepPointCount, stepGenerator))
            .limit(0)
            .toList();
    }
```
3. isFinish() 등은 Height를 타입으로 받아 비교하도록 수정합니다. 
```java
  public boolean isFinish(Height height) {
    return this.height.equals(height);
  }
```
4. 도메인 용어는 통일되는게 좋으므로 floor와 height로 나뉘어 쓰이는 용어를 더 적합해 보이는 용어만 남기고 통일합니다

이렇게 0에 해당하는 Height를 만들기 위해 노력하는 이유는, 0 또한 시스템에서 활용되는 값인데 다른 개발자들은 Height라는 개념의 불변식을 Height 안에서 찾으려고 할 것이기 때문입니다!
-> 'height는 몇 까지 가능하지? 아 Height 객체가 있네? 아 1~100이구나! 오키오키' (0 높이 코드를 고려 못할 가능성이 높고 버그로 이어짐)

그런데 실제로는 Height 0값이 시스템에서 가능하다면, 그것은 객체의 세부규칙에 해당합니다 (루프를 돌때는 0값이 허용되기도 함) 
모든 객체는 기억해야 할 세부규칙이 추가될수록 유지보수가 어려워지기 때문에 가능한 단순하게 만드는 것이 중요합니다.

그렇게 개념을 정리하고 났다면, 그 다음으로 봐야할 것은 말씀해주신 요구사항입니다. 
0 높이를 가진 사다리가 생성되는 것을 validation 해야 한다면, 이것은 높이가 아닌 사다리의 불변식이라는 생각이 듭니다. 그래서 0 높이 사다리가 생성되는 것을 방지하는 코드를 사다리 쪽에 추가해주었습니다.

원시값 랩핑 객체를 생성하고 코드 내에서 활용된다면, 가능한 최대한 원시값 랩핑 객체끼리 연산을 진행하는 것이 좋습니다. 그런 객체를 만든 철학(코드 내의 원시값을 줄여 모호함과 버그가능성을 줄임)이 주는 이점이 분명하기 때문입니다.

2024-02-28 12:05 UTC, sihyung92 commented on src/main/java/domain/LadderResult.java
> +    }
이 부분은 map 객체의 자료구조 이점을 활용하지 못하고 있습니다!

map은 시간 복잡도가 O(1)인데, map을 list화 하여 O(n) 복잡도로 만들었습니다. (시간복잡도 개념을 아시나요? 모르신다면 두고, Map 자료구조에 대해서만 학습해보세요! list에 비해 탐색에서 엄청난 성능 이득이 있습니다.)

다음처럼 해보는건 어떨까요?
```suggestion
    public int getOneResult(int firstPositionValue) {
        return firstAndLastPosition.get(new Position(firstPositionValue)).getPosition();
    }
```

---
달리는 이렇게도 가능합니다. (이쪽이 제 취향)
```suggestion
    public Position getOneResult(Position first) {
           return firstAndLastPosition.get(first);
    }
```

2024-02-28 12:05 UTC, sihyung92 commented on src/main/java/domain/LadderResult.java
> +    public LadderResult(Ladder ladder, int participantsCount) {
훨씬 코드 가독성이 높아졌습니다! 좋은 리팩토링 이었다고 생각합니다. 수고가 많으셨을 것 같습니다.

2024-02-28 12:05 UTC, sihyung92 commented on src/main/java/domain/LadderResult.java
> +        for (int floor = 0; !ladder.isFinish(floor); floor++) {
부정연산자는 가독성을 떨어뜨린다는 의견이 있어, 저는 이런 경우 반대 메서드를 하나 더 만듭니다.
(뭔가 진행중임을 뜻하는 것도 좋은거 같은데 이것저것 붙여봐도 찰떡같지 않아 notFinish로 만족했습니다)
```suggestion
        for (int floor = 0; ladder.notFinish(floor); floor++) {
```

```java
public class Ladder {
...
   public boolean notFinish(Floor floor) {
       return !isFinish(floor);
   }
...
}
```

2024-02-28 12:05 UTC, sihyung92 commented on src/main/java/view/OutputView.java
> +        IntStream.range(0, participants.getParticipantsCount())
스트림에 대해 학습을 진행하신 것 같군요!! 👍 다만 말씀해주신 멀티코어에 대한 부분은 '병렬 스트림'(ParallelStream)에만 해당하는 것 같습니다! 
스트림은 생성비용도 있어 모던자바인액션 등의 책에서 주장하는 것 같이 성능이 잘 안 나오는 경우도 있습니다! (사실 스트림에서 말하는 성능적 이득을 보려면 몇십만 단위의 컬렉션이 필요합니다!)

개발하다보면 이렇게 의견이 엇갈릴 때가 있는데요! (for문이 낫다 VS 스트림이 낫다) 양 주장은 모두 일리가 있기 때문에 주장만 하면 평행선을 달리게됩니다!
이럴 땐 직접 벤치마크를 실행해보는 것만이 해법입니다! (아니면 황희정승 전략도 있습니다! 너도 맞고 나도 옳다. 그냥 아무렇게나 하겠다. -> 전 이거 많이 씁니다!!)

한번 저도 호기심이 들어 벤치마크를 진행해봤습니다! 
Stream Generate를 사용해 Ladder를 구현하신 부분이 있어 그 부분을 검증해 봤습니다.
(Height 100개 validation은 잠시 해제하였습니다)

코드는 아래처럼 작성했습니다.
```java
    @ParameterizedTest
    @ValueSource(ints = {100,10_000,1_000_000})
    @DisplayName("사다리 벤치마크")
    void benchmark(int height) {
        LocalDateTime before = LocalDateTime.now();
        for (int i = 0; i < height; i++) {
            new Ladder(height, 3, new RandomStepGenerator());
        }

        LocalDateTime after = LocalDateTime.now();
        Duration duration = Duration.between(before, after);
        System.out.println(duration.toMillis() + " mils");
    }
```
결과는 100개일때 4mils, 10000개일때 2892mils, 백만개 일때는 3분이 지나도 실행이 끝나지 않아 임의로 종료했습니다! (최소 2.892초x100 이므로 4분 넘게 걸렸을거라 생각합니다!)

아래처럼 리팩토링하고 다시 진행해봤습니다! 코드의 역할은 동일합니다.
```java
    public Ladder(int floor, int participantsCount, StepGenerator stepGenerator) {
        int stepPointCount = participantsCount - 1;
        height = new Height(floor);
        List<Line> list = new ArrayList<>();
        for (int i = 0; i < floor; i++) {
            list.add(new Line(stepPointCount, stepGenerator));
        }
        lines = list;
    }
```
결과는 100개일때 2mils, 10000개일 때 2798mils, 백만개일땐 너무 오래걸려서 그냥 껐습니다!

백만개 결과를 보기 어려우므로 step을 좁혀서 다시 테스트 했습니다.
결과 : 
for문 - 100개 : 2mils, 1000개 : 37mils, 10000개 : 2741mils, 20000개 : 10341 mils
Stream - 100개 : 14mils, 1000개 : 46mils, 10000개 : 2788mils, 20000개 : 10541mils

아주 작은 수 일때는 for문이 앞서지만 개수가 증가할수록 Stream이 우위를 보이는 구조는 신선했네요!! 더 많아지면 어떨까 싶지만 우테코 크루들의 몫으로 남겨두겠습니다!

그런데 Height 제약을 100개로 두셨으니 사실 뭐로해도 상관없고, 이럴 땐 저는 가독성 좋은 구조를 무조건 추천합니다!
성능은 문제가 될 때만 문제인데 100개로 인한 생성이 비효율적이어도 14mils는 0.001초 이므로 문제가 될 확률이 희박합니다!

2024-02-28 12:05 UTC, sihyung92 commented on src/main/java/controller/LadderGameController.java
> +        if (name.equals(EXIT)) {
NPE를 방지하는 규칙 중 null이 아닌 것을 앞세우라는 규칙이 있습니다!
```suggestion
        if (EXIT.equals(name)) {
```
만약 EXIT를 상수화 안 했다면 `"종료".equals(name)` 의 형태였을 건데, 처음엔 낯설지만 java에서 NPE가 주는 고통은 정말 끔찍하므로 피할 수 있는 모든 방법을 동원하는게 좋습니다!!

2024-02-28 12:05 UTC, sihyung92 commented on src/main/java/controller/LadderGameController.java
> +    }
이건 View에서 진행되어야 하는 검증이라고 생각합니다! controller는 가급적 비즈니스를 가지지 않는 것이 유리합니다! (비즈니스 로직을 찾기 위해 봐야하는 곳이 많아짐)

2024-02-28 12:05 UTC, sihyung92 commented on src/main/java/domain/Participants.java
> +                .getAsInt();
노란줄이 있고 확인해보시면 present체크, 즉 null 일 때는 오류가 발생되는 코드임을 경고하고 있습니다!
그리고 이 로직은 name이 없을 확률이 높은데, 그럴 땐 getAsInt가 정의한 NoSuchElemtentException이 발생하게됩니다! (메서드를 들어가거나 javaDocs를 통해 확인가능함)
이러면 유저는 예측하지 못한 예외메시지를 보게될테니 별도의 예외처리가 필요하겠죠!
orElseThrow나, Optional을 학습해 활용해보시는 것도 좋습니다!

2024-02-28 12:05 UTC, sihyung92 commented on src/main/java/domain/Participants.java
> +        return Collections.unmodifiableList(names);
인텔리제이가 회색으로 표시해주지 않던가요? 인텔리제이가 해주는 도움은 대부분 좋은 프렉티스입니다!
names를 할당하실 때 final로, 그리고 Stream.toList를 이용해주셨는데, toList 내부 구현을 들어가보시면 불변리스트를 반환합니다! 그러므로 이미 names는 불변리스트여서 해당 조치는 필요가 없는 코드이므로 인텔리제이가 필요없음을 표시해주는 중입니다.
인텔리제이의 warn이나 회색표시등은 꼭 체크해주세요!

2024-02-29 08:20 UTC, shin-jisong commented on src/main/java/view/OutputView.java
> +        IntStream.range(0, participants.getParticipantsCount())
둘의 성능 차이가 그리 크지는 않군요!stream이 더 좋을 거라 유추하였는데

2024-02-29 08:23 UTC, shin-jisong commented on src/main/java/domain/Ladder.java
> +    public boolean isFinish(int floor) {
지금껏 height에 대한 검증은 height에서만 진행하여야 된다는 생각을 하였는데
주신 예시 코드 덕분에

2024-02-29 08:24 UTC, shin-jisong commented on src/main/java/domain/Name.java
> +    public static final String EXIT = "종료";
지금껏 이해를 잘못하고 있었네요! 감사합니다 ㅎㅎ

2024-02-29 08:25 UTC, shin-jisong commented on src/main/java/domain/LadderResult.java
> +    }
아래 구조가 더 깔끔한 것 같아 변경하였으나 getter 사용이 일부 증가하여 고민하였습니다
다만 트레이드 오프임을 인지하고 꼭 필요한 로직이라고 판단한 바 그대로 진행하였습니다!
Height내에 내부 로직을 만들어 진행할 수 있는 건 그렇게 진행하였습니다

2024-02-29 08:29 UTC, shin-jisong commented
주신 의견들을 새롭게 학습하고 반영하였습니다!
많은 고심을 거쳐 리팩토링하였는데 확실히 마음에 드는 코드가 되어 뿌듯합니다 ㅎㅎ
지금껏 getter를 아예 쓰지 않아야겠다는 생각에 오히려 코드가 이상해진 경우가 있는 것 같은데
웨지의 트레이드 오프라는 설명 덕분에 두개를 비교하고 채택할 수 있는 인사이트를 얻은 것 같습니다
각 객체들이 역할을 잘 나눌 수 있도록 또 많은 고민을 거쳤습니다! 늘 상세히 리뷰해 주셔서 감사합니다 ㅎㅎ

2024-03-01 03:13 UTC, sihyung92 requested changes
안녕하세요 시소~
리뷰 반영 잘 해주셨네요 👍👍👍
추가 리뷰 확인해주시고 다시 요청주셔요!
연휴 잘 보내시고용~~

2024-03-01 03:13 UTC, sihyung92 commented on src/main/java/domain/LadderGame.java
> +
두 줄 개행이 있네용!

2024-03-01 03:13 UTC, sihyung92 commented on src/main/java/domain/ladder/Line.java
>      public Line(int numberOfCell, StepGenerator stepGenerator) {
stepPointCount 로도 표현할 수 있겠어요 ㅎ (사용처에서 할당하는 변수명이나 멤버 변수 명을 봤을 때)

2024-03-01 03:13 UTC, sihyung92 commented on src/main/java/domain/participants/Name.java
> +        if (name.equals(InputView.EXIT)) {
DM 주셨던 부분이 여기군요!

첫 리뷰와 비교해보니 좀 더 적합한 리뷰가 있었겠네요 (Name의 책임이 아니라고 생각)
원본 리뷰 : https://github.com/woowacourse/java-ladder/pull/350#discussion_r1504502930

**일단 중요한건 domain 패키지가 view 패키지에 의존하지 않게 하는 것입니다.**
(즉 domain 패키지 내의 어떤 객체도 `import view.XXX` 가 없어야 함)
나중에 누가 domain 패키지만 가져다가 아무 view나 붙여서 쓰고싶다 했을때 view.InputView 클래스도 같이 가져가야 하니까요!

어쨌든 그러면 "종료" 라는 예외 검증은 어디서 할것인가? 지금처럼 도메인에서 지원해줄 방법이 없을까? 좀 고민을 해봤는데요, 

제 의견은 inputView 쪽이 가장 적절하다고 생각됩니다.
1. 참가자 이름이 "종료"이면 안 된다는 건 '참가자명'인 도메인 개념에 빗대어보면 연상하기 어려움
2. domain 패키지 내에서 종료를 지원해줄 수 없을지 생각해보면 쉽지 않음
    - 종료 도메인을 만들어 어쩌고.. 불가능하진 않지만 복잡도가 너무 늘어남
    - 종료 도메인이 있으면 각 종류의 View마다 종료 검증 메서드를 반복 구현하는 수고가 덜겠지만 늘어나는 복잡도와 비교해보면 별로다 싶음
3. InputView 쪽에서 해당 validation을 수행해 종료 시그널을 주고(throw 등으로) 컨트롤러에서 받아서 종료하면 될까 싶음

현재 구현해주신 controller 단에서 처리하는 것도 괜찮은거 같아요

2024-03-01 03:13 UTC, sihyung92 commented on src/main/java/domain/LadderGame.java
>          Map<String, String> result = new LinkedHashMap<>();
Map하면 가장 흔하게 생각나는 HashMap 대신 LinkedHashMap 구현체를 결정하신 이유가 있나요? ㅎ

2024-03-01 03:13 UTC, sihyung92 commented on src/main/java/domain/ladder/Height.java
> +    }
원시값 랩핑은 불변의 속성도 가져가면 더욱 좋은데요, 
불변은 코딩하기 불편하게 만드는 제약이지만 그 제약이 가져다주는 장점들이 있습니다 (불변의 효능은 인터넷에 많으니 심심하시면 찾아보세요)

final을 유지하면서 moveUp 메서드를 유지하는 방법은 다음과 같습니다
```suggestion
    public Height moveUp() {
        return new Height(height + 1);
    }
```

2024-03-04 05:39 UTC, shin-jisong commented on src/main/java/domain/participants/Name.java
> +        if (name.equals(InputView.EXIT)) {
생각해 보니 종료를 사용하면 안 되는 것은 view에 한정적인 코드라고 생각되어 view로 위치를 수정하였습니다! 감사합니다!

2024-03-04 05:39 UTC, shin-jisong commented on src/main/java/domain/LadderGame.java
>          Map<String, String> result = new LinkedHashMap<>();
해당 경우에 순서를 유지해 주는 것이 중요하여 LinkedHashMap으로 구현하였습니다!

2024-03-04 05:47 UTC, shin-jisong commented on src/main/java/domain/ladder/Height.java
> +    }
해당 코드를 작성할 때 원시값 랩핑이기에 불변 속성을 유지하는 것이 좋을 것 같은데

2024-03-04 12:25 UTC, sihyung92 approved these changes
안녕하세요 시소! 리뷰어 웨지입니다!
리뷰 잘 반영해주셔서 머지할게요~!
미션 진행하느라 수고 많으셨습니다. 
새로운 미션도 화이팅입니다!

2024-03-04 12:25 UTC, sihyung92 commented on src/main/java/domain/ladder/Height.java
> +    public Height moveUp() {
네네 처음에 상태로 구현한 부분에 대한 이유에 대해 이해했습니다!

사실 불변이라든지, 방어적 복사라든지, 가독성을 위한 객체 분리 라든지.. 컴퓨팅 자원 효율 개념에서 보면 부조리한 것이 많습니다. 그러나 그런 비효율을 감소하고 주는 이점이 분명하기에 사용됩니다.

이처럼 대부분의 개발 개념에는 일장일단이 있습니다. 
보안을 키우면 복잡성과 CPU 사용량이 늘어나고, 간단하게 만들면 확장이 어려워지고.. 
그래서 중요한 것이 어떤 개념을 배웠을 때 '이게 왜 필요한지' 질문해 보는 부분이라고 생각합니다.
why에 대해 이해하고 나면 나중에 장단을 따질 때 많은 도움이 되더라구요.

완전히 반대되는 팁으로는 이해가 잘 안 되면 일단 대충 '글쿤' 하고 넘어가는 것도 있습니다 ㅎ 
개발 공부는 분야가 너무 넓고 모든 것을 학습할 순 없습니다. 뭐든 잘 이해하고 넘어가는 것도 좋지만, 잘 안 될 땐 자책하지 않고 넘어가는 것도 중요하다고 생각해요.

2024-03-04 12:25 UTC, sihyung92 commented on src/main/java/view/InputView.java
> +        if (participantNames.stream().anyMatch(name -> name.equals(InputView.EXIT))) {
항상 상수를 앞쪽에 두기!
```suggestion
        if (participantNames.stream().anyMatch(name -> InputView.EXIT.equals(name))) {
```
null element가 포함되어 있다면 NPE가 날 수 있어요.
```java
    public static void main(String[] args) {
        List<String> nulls = List.of(null, null, null);
        validateUnavailableName(nulls); // NPE
    }
```

2024-03-04 12:26 UTC, merged