[사다리 타기 - 2단계] 리건 미션 제출합니다!
woowacourse/java-ladder pull request #351
Opened 2024-02-27 08:23 UTC by hangillee

안녕하세요, 미르! 👋
1단계를 일찍 Merge 해주신 덕분에 여유로운 우테코 생활을 보냈습니다.
새로운 생활에 적응하기 살짝 힘들었는데, 잠시 돌아볼 시간이 생겼어요!

이번 2단계 구현에서는 새로운 시도를 많이 해봤습니다.
제가 시도한 여러 구현 방법에 대한 미르의 의견이 궁금합니다!

### **알고리즘을 활용한 어려운 구현 vs 한눈에 보기 쉬운 간단한 구현**

저는 사다리 타기를 하면서 가로 라인을 이동하는 로직을 알고리즘을 활용해 구현했습니다. 어떻게 구현하면 좋을지 고민하던 중, 크루의 아이디어를 듣고 해당 아이디어를 구체화해봤습니다. 과정은 다음과 같습니다. (해당 아이디어는 BFS에서 힌트를 얻었습니다.)

1. 전체 사다리에서 이동할 수 있는 가로 라인의 **오른쪽** 인덱스들을 하나의 리스트에 추가해둡니다.
2. 해당 이동 가능한 인덱스들을 기반으로 사람 리스트에 Swap 연산을 진행합니다.
3. 최종적으로 사람 리스트는 사다리 타기를 모두 완료한 후의 위치로 재배치되었습니다.

그런데, 이렇게 구현하고 보니, 다른 크루들에게 구현 방식을 소개하는게 또 다른 문제가 됐습니다. 문제를 해결하기 위해 알고리즘을 썼는데, 협업에는 별로 도움이 되지 못한 상황이 벌어지게 되어 의문이 생겼습니다.

미르는 개발할 때 적절한 알고리즘이 떠오르더라도 더 간단한 방법을 찾아내는지, 아니면 그냥 알고리즘을 활용하는지 궁금합니다! 저는 빠르게 문제를 해결할 수 있기 때문에 일단은 알고리즘을 활용하는 방향으로 미션을 진행했습니다. 저는 제 코드를 이해할 수 있고, 설명도 할 수 있는데, 다른 크루들은 너무 어려운 방법을 활용한게 아니냐는 의견을 주어 조금 고민됩니다.

### **매개 변수의 개수를 줄이기 위한 DTO 성격의 도메인 모음 객체를 사용해도 괜찮은가?**

이번 미션에서는 정말 많은 수의 도메인을 구현했습니다. 그만큼 제가 필요하다고 생각하는 역할이 많았고, 자연스레 컨트롤러는 의존하게 되는 도메인이 많아졌습니다. 메소드들은 여러 도메인들의 협력을 통해 결과를 도출하는데, 파라미터가 3개 이상으로 많아지는 상황이 발생해 DTO 성격을 띄는 도메인을 모아두는 하나의 도메인을 만들었습니다. 이런 식으로 구현해도 괜찮은지, 아니면 잘못된 방식인지 확신이 들지 않습니다.

무언가 마음에 걸리는 걸 보면 좋지 않은 방식인 것 같은 느낌이 드는데, 정확히 어떤 부분에서 문제가 되는지는 아직까진 잘 모르겠습니다. 도움을 주신다면 정말 감사하겠습니다. 😢

2단계 코드 리뷰도 잘 부탁드립니다!

2024-02-27 13:56 UTC, ddu0422 requested changes
안녕하세요 리건 ! 미르입니다 :)
2단계 미션도 빠르게 구현해주셨네요.
몇 가지 코멘트 남겼습니다.
확인부탁드려요~~ 😄 

## 답변

> 매개 변수의 개수를 줄이기 위한 DTO 성격의 도메인 모음 객체를 사용해도 괜찮은가?

위 객체가 LadderComponents일까요?
정확히 어떤 객체인지는 모르겠네요.
알려주시면 확인 후 다음 리뷰에서 코멘트 남겨드릴게요~

> DTO 성격을 띄는 도메인을 모아두는 하나의 도메인을 만들었습니다.

DTO와 DTO 성격을 띄는 도메인(객체)은 어떤 차이가 있을까요?

2024-02-27 13:56 UTC, ddu0422 commented on src/main/java/domain/Line.java
> +    private final PointGenerator generator;
생성자로 넘겨준다고 하여 전부 필드로 선언해야할까요?

2024-02-27 13:56 UTC, ddu0422 commented on src/main/java/domain/Mover.java
> +            Collections.swap(allNames, nextMovableIndex, nextMovableIndex + 1);
`movableIndex`가 정확히 어떤 역할을 하는지 해당 메서드만 보고 알기 어렵네요.
`movableIndex`를 해석하기가 오래 걸리 수 있다고 생각합니다.
위 메서드가 리건이 이야기한 1번에 해당하겠네요 :)

swap 자체는 이해하기 어렵지 않을 것 같아요.
사다리를 내려오며 이름이 바뀌는 부분은 충분히 상상이 가능하지 않을까요?

> 개발할 때 적절한 알고리즘이 떠오르더라도 더 간단한 방법을 찾아내는지, 아니면 그냥 알고리즘을 활용하는지 궁금합니다! 저는 빠르게 문제를 해결할 수 있기 때문에 일단은 알고리즘을 활용하는 방향으로 미션을 진행했습니다. 저는 제 코드를 이해할 수 있고, 설명도 할 수 있는데, 다른 크루들은 너무 어려운 방법을 활용한게 아니냐는 의견을 주어 조금 고민됩니다.

특별한 상황에선 혼자 일을 할 수도 있지만, 대부분의 상황에선 `협업을 합니다.`
또한 내가 작성한 코드는 내가 아닌 `동료들이 많이 읽게 됩니다.`
협업에서 가장 중요한 내용은 무엇일까요?

2024-02-27 13:56 UTC, ddu0422 commented on src/main/java/domain/Name.java
> +    public Name(final String value) {
final을 붙인 특별한 이유가 있을까요?

2024-02-27 13:56 UTC, ddu0422 commented on src/main/java/controller/LadderGame.java
> +        if (target.equals("all")) {
만약 target이 NULL이라면 어떤 결과가 나올까요?

2024-02-27 13:56 UTC, ddu0422 commented on src/main/java/domain/Names.java
> +    private static final String INVALID_NAMES = "이름은 " + MIN_NAMES_COUNT + "개 이상의 중복되지 않은 값이어야 합니다.";
👍🏻 👍🏻

2024-02-27 13:56 UTC, ddu0422 commented on src/main/java/domain/RandomPointGenerator.java
> +    }
현재는 true, false지만 조건이 많아진다면 어떻게 될까요?
`(ex. 1인 경우 -> WOOWABROS, 2인 경우 -> KAKAO, 3인 경우 -> NAVER)`

if 문을 제거할 수는 없을까요?

2024-02-27 13:56 UTC, ddu0422 commented on src/main/java/domain/Result.java
> +        }
2가지의 역할이 될 수도 있지 않을까요?

2024-02-27 13:56 UTC, ddu0422 commented on src/main/java/domain/Results.java
> +    }
빈 배열인 경우 어떤 결과가 나올까요?

2024-02-27 13:56 UTC, ddu0422 commented on src/main/java/view/ResultMessage.java
> +        if (Point.isMovable(point)) {
View와 Domain이 강결합되어 있는 형태가 아닐까요?

2024-02-27 13:56 UTC, ddu0422 commented on src/test/java/domain/MoverTest.java
> +    @DisplayName("Lines, Names 객체와 함께 협력하여 사다리 이동 결과를 반환한다.")
`Lines, Names 객체와 함께 협력`하는 내용이 정말 테스트함에 있어 중요한 내용일까요?

2024-02-27 13:56 UTC, ddu0422 commented on src/test/java/domain/ResultTest.java
> +    }
5글자를 넘은 테스트와 5글자를 넘지 않는 테스트를 분리하는건 어떨까요?
TDD를 진행할 때 더 작은 단위로 진행해보는건 어떨까요?

2024-02-27 13:56 UTC, ddu0422 commented on src/test/java/domain/ResultsTest.java
> +        Results results = new Results(Arrays.asList("꽝", "5000", "꽝", "3000"), 4);
중복된 내용이 반복되네요.
Test Code도 리팩토링해보는건 어떨까요?

2024-02-28 01:58 UTC, hangillee commented on src/main/java/domain/Line.java
> +    private final PointGenerator generator;
`PointGenerator`가 클래스 전체적으로 사용되진 않으니 굳이 필드일 필요는 없어도 될 것 같습니다. Spring 프로젝트를 진행하면서 의존성 주입을 활용할 때, 관성적으로 필드에 적어두던 것이 여기서도 나온 것 같습니다. 좋지 못한 습관인 것 같네요...😢

2024-02-28 02:02 UTC, hangillee commented on src/main/java/domain/Mover.java
> +            Collections.swap(allNames, nextMovableIndex, nextMovableIndex + 1);
저는 협업에서는 명쾌한 소통, 이를 위한 다른 사람이 읽기 쉬운 코드, 부가적인 설명 없이도 이해할 수 있는 코드가 중요하다고 생각합니다. 머리로는 이해가 되는데, 더 나은 방법이 있음에도 돌아가야하는지에 대해 알게 모르게 거부감이 있었던 것 같습니다. 알고리즘 자체는 어렵지 않다고 하시니 변수 이름과 메소드 이름을 리팩토링하여 이해하기 쉽도록 고쳐보겠습니다!

2024-02-28 02:15 UTC, hangillee commented on src/main/java/domain/Name.java
> +    public Name(final String value) {
매개 변수로 넘어온 변수는 다른 객체와의 협업을 통해 외부로부터 들어온 것이므로 재할당이 불가능하게 하려고 붙였습니다.

외부 객체의 입장에서는 본인이 보낸 변수가 엉뚱한 변수로 대체되지 않고, 원하는 동작과 그에 대한 결과를 얻길 바랄 것입니다. 저는 어떤 한 객체가 다른 객체의 내부 구현을 모르더라도 서로 협력했을 때, 예상하는 결과를 제대로 얻어야 좋은 객체지향 프로그래밍이라고 생각합니다. 

예를 들어, 외부에서 `Name` 객체에 이름의 값으로서 저장하길 원하는 문자열을 생성자로 전달할텐데, 갑자기 생성자 마음대로 전혀 다른 엉뚱한 문자열을 `value`에 재할당 한 후, 초기화한다면 내부 구현을 모르는 외부 객체 입장에서는 날벼락이나 다름 없다고 생각합니다. 그래서 저는 습관적으로 `final`을 붙이려고 노력했습니다.

물론, 가독성 측면에서는 조금 떨어지더라도 믿을 수 있는 코드가 된다고 생각합니다.

2024-02-28 02:16 UTC, hangillee commented on src/main/java/controller/LadderGame.java
> +        if (target.equals("all")) {
놓친 부분인 것 같습니다. System.in이 활용되는 부분이어서 테스트 하지 않아도 괜찮다고 생각했는데 아니었네요... 고쳐보겠습니다!

2024-02-28 02:18 UTC, hangillee commented on src/main/java/domain/Results.java
> +    }
이 부분도 테스트가 통과되었다고 생각하고 간과한 부분인 것 같습니다. 고쳐보겠습니다!

2024-02-28 02:20 UTC, hangillee commented on src/test/java/domain/MoverTest.java
> +    @DisplayName("Lines, Names 객체와 함께 협력하여 사다리 이동 결과를 반환한다.")
다시 읽어보니 중요한 내용은 아닌 것 같습니다. 테스트 이름도 결국 코드고, 가독성 측면에서 너무 복잡하면 안되겠네요! 간략화해보겠습니다!

2024-02-28 02:21 UTC, hangillee commented on src/test/java/domain/ResultTest.java
> +    }
경계값 테스트라서 둘은 같은 단위가 아닐까라는 생각을 했는데 더 작게 나눌 수도 있겠네요. 분리해보도록 하겠습니다!

2024-02-28 02:21 UTC, hangillee commented on src/test/java/domain/ResultsTest.java
> +        Results results = new Results(Arrays.asList("꽝", "5000", "꽝", "3000"), 4);
놓친 부분이네요. 테스트 코드도 다시 한번 쭉 리팩토링해보겠습니다!

2024-02-28 12:39 UTC, hangillee commented
> 위 객체가 LadderComponents일까요?
정확히 어떤 객체인지는 모르겠네요.
알려주시면 확인 후 다음 리뷰에서 코멘트 남겨드릴게요~

일단 조금 더 리팩토링하면서 `Ladder`와 `LadderDto`로 해당 객체를 분리했습니다.
* `Ladder`는 `Names`, `Lines`, `Results`의 사다리 게임에서 필요한 사다리의 구성 요소들(참가자 이름들, 사다리 선들, 결과들)을 상태로 가지는 객체입니다.
* `LadderDto`는 `Ladder`로부터 원시값들을 가지는 `List` 컬렉션을 넘겨 받아 View에 전달합니다.

이번 리뷰 요청에서 궁금한 점은 다음과 같습니다!

1. `Ladder`와 같이 다른 도메인들을 상태로 가지는 도메인을 설계상 필요하다고 생각되면 구현하는게 괜찮은지, 아니면 나쁜 구현 방법인지 궁금합니다!
2. 강한 결합을 해제하는 방법으로 DTO를 선택했는데, 오히려 코드가 더 복잡해지는 것 같습니다. 그래도 이게 올바른 방향성인지 궁금합니다!
3. `List<List<Boolean>>`과 같이 읽기 힘든 컬렉션을 사용하지 않고자 일급 컬렉션을 도입했는데, 오히려 View에 넘기려고 다시 풀어헤쳐버렸습니다. (`List<List<Boolean>>`은 `List<Point>`나 `Lines`로 대체할 수 있습니다.) 결합도를 올바른 방향으로 낮춘게 맞는지 잘 모르겠습니다... 방향성을 제시해주실 수 있으신가요..?

p.s.
> 현재는 true, false지만 조건이 많아진다면 어떻게 될까요?
(ex. 1인 경우 -> WOOWABROS, 2인 경우 -> KAKAO, 3인 경우 -> NAVER)

이 피드백의 경우에는 if를 다른 도메인으로 옮기는 정도로 해결했습니다. 그런데, 정확히 어떤 걸 물어보신 건지 감을 잡기 어렵습니다. 제가 이해하기로는 `true`, `false`가 아니라 1, 2, 3의 여러 이동 방향 선택지가 생기는 걸로 이해했는데, 이러면 요구 사항이 완전히 바뀌기 때문에 애초에 도메인에 변경이 생길 수 밖에 없는 상황이 아닌지 의문이 들었습니다. 질문을 잘 이해하지 못해서 죄송합니다..ㅠㅠ

2024-02-28 12:51 UTC, ddu0422 commented on src/main/java/domain/Name.java
> +    public Name(final String value) {
1. 재할당이 불가능 -> 매개변수에 재할당이 불가능한 내용이죠.
2. 외부에서 바라봤을 때 정상적인 값이란 어떤걸까요?
값을 넣은 그대로 나오기만을 기대해야할까요?
Name이 지니는 value 필드는 변경되어 저장될 수도 있지 않을까요?

2024-02-28 12:52 UTC, ddu0422 commented on src/main/java/controller/LadderGame.java
> +        if (target.equals("all")) {
Hint) `target.equals("all")` vs `"all".equals(target)`

2024-02-28 13:11 UTC, ddu0422 requested changes
안녕하세요 리건! 미르입니다 :)
시간이 조금 남아 같이 고민하고 싶은 부분 코멘트 남겼습니다 ㅎㅎ
확인해주시면 감사하겠습니다 🙏🏻

## 답변

> Ladder와 같이 다른 도메인들을 상태로 가지는 도메인을 설계상 필요하다고 생각되면 구현하는게 괜찮은지, 아니면 나쁜 구현 방법인지 궁금합니다!

1. 도메인 설계상 필요하다고 느낀 부분은 어떤점 때문일까요?
2. 나쁜 구현 방법이라고 생각하신 부분은 어떤점 때문일까요?

> 강한 결합을 해제하는 방법으로 DTO를 선택했는데, 오히려 코드가 더 복잡해지는 것 같습니다. 그래도 이게 올바른 방향성인지 궁금합니다!

1. 강결합을 왜 해제해야할까요?
2. 이중 List 때문에 복잡하다고 느끼셨을까요? 그에 대한 힌트는 코멘트 남겼습니다.
만약 다른 부분 때문에 복잡하다고 느끼셨으면 코멘트 남겨주세요 :)

2024-02-28 13:11 UTC, ddu0422 commented on src/main/java/domain/Point.java
> +        return UNMOVABLE;
> 이 피드백의 경우에는 if를 다른 도메인으로 옮기는 정도로 해결했습니다. 그런데, 정확히 어떤 걸 물어보신 건지 감을 잡기 어렵습니다. 제가 이해하기로는 true, false가 아니라 1, 2, 3의 여러 이동 방향 선택지가 생기는 걸로 이해했는데, 이러면 요구 사항이 완전히 바뀌기 때문에 애초에 도메인에 변경이 생길 수 밖에 없는 상황이 아닌지 의문이 들었습니다. 질문을 잘 이해하지 못해서 죄송합니다..ㅠㅠ

이해하지 못해서 죄송할 건 없습니다..
너무 추상적인 내용으로 리뷰를 드렸네요.
고민정도로 해주시고 넘어가시면 될 것 같아요 ㅎㅎ 

선택) Enum의 values()를 활용하여 if 문을 제거해보면 어떨까요?

2024-02-28 13:11 UTC, ddu0422 commented on src/main/java/controller/LadderDto.java
> +    }
> List<List<Boolean>>과 같이 읽기 힘든 컬렉션을 사용하지 않고자 일급 컬렉션을 도입했는데, 오히려 View에 넘기려고 다시 풀어헤쳐버렸습니다. (List<List<Boolean>>은 List<Point>나 Lines로 대체할 수 있습니다.) 결합도를 올바른 방향으로 낮춘게 맞는지 잘 모르겠습니다... 방향성을 제시해주실 수 있으신가요..?

`List<List<Boolean>>` 안에 있는 `List<Boolean>`도 객체로 만들면 되지 않을까요?

2024-02-28 13:11 UTC, ddu0422 commented on src/main/java/domain/Ladder.java
> +    }
domain에서 view에 반환하는 내용을 만든 이유가 있을까요?

2024-02-29 08:22 UTC, hangillee commented
안녕하세요, 미르!
미르의 피드백 덕분에 정말 알아가는 것이 많은 미션인 것 같습니다.

이번 버전의 코드 리뷰도 잘 부탁드립니다!

> 1. 도메인 설계상 필요하다고 느낀 부분은 어떤점 때문일까요?
>
사람의 이름을 모아둔 `Names`, 사다리 역할을 하는 `Lines`, 결과를 모아둔 `Results`간에 협력이 필요했기 때문입니다. 서로 협력을 해서 사다리 게임의 실행 결과를 얻어내야 하는데, 많은 수(제 경우에는 3개입니다.)의 도메인들이 메소드의 매개 변수로 옮겨다니는게 과연 좋은 코드일까, 하나로 묶어서 각 메소드별로 필요한 도메인만 꺼내 쓸 수는 없을까라는 생각에 도메인을 모아둔 도메인이 필요하다고 느꼈습니다.

> 2. 나쁜 구현 방법이라고 생각하신 부분은 어떤점 때문일까요?
> 
그런데, 결국 이렇게 구현하면 불필요하게 여러 도메인에 의존하는 큰 도메인이 생기고, 유지보수에 있어 좋지 못할 것 같다는 생각이 들었습니다. 단순히 하나의 도메인만 수정해도, 덩치 큰 도메인도 부가적으로 수정해야하는 것 자체가 낭비도 심하고 나쁜 구현 방법인 것 같습니다. 그리고 해당 도메인의 역할을 생각해보면 애매하다는 것도 좋지 않은 점이라고 생각합니다. 그냥 코드 이곳 저곳에 있는 메소드들에 도메인을 뿌려주는 역할 밖에 없습니다. 그래서 저는 이 구현 방법을 버리고 다시 Controller 하나와 메소드 분리를 통해 기존의 로직이 깨지지 않는 선에서 리팩토링 했습니다.

> 1. 강결합을 왜 해제해야할까요?
>
일단, 가장 큰 이유는 개방-폐쇄 원칙(확장에는 열려있고, 수정에는 닫혀있어야 한다.)을 무너뜨리게 되고, 유지보수하기 어려워집니다. 객체 간의 결합이 강하면 사소한 수정이라도 연쇄적인 추가 수정을 일으킵니다. 꼬리에 꼬리를 무는 코드 수정을 하다보면 실수를 저지르기 쉬워지고 잘 돌아가던 프로그램도 사소한 수정 하나에 먹통이 되어버릴 수 있기 때문에 강결합을 느슨하게 해야합니다.

그런데, 제가 도메인을 설계하고 개발하다보면 가장 좋은 결합도라고 할 수 있는 자료 결합도(Data Coupling)은 거의 불가능하다고 느끼게 됩니다. 객체에게 메시지를 던져서 원하는 결과를 얻는 과정에서 결국 그 객체가 제공하는 `public` 메소드를 알아야 하고, 값들만 주고 받아서는 한계가 있다고 느꼈습니다. 미르는 보통 어떤 경우까지를 강결합이라고 생각하시나요?

> 2. 이중 List 때문에 복잡하다고 느끼셨을까요? 그에 대한 힌트는 코멘트 남겼습니다.
>    만약 다른 부분 때문에 복잡하다고 느끼셨으면 코멘트 남겨주세요 :)
>
맞습니다. 이중 List를 포함해 도메인들이 Controller 사이에서 옮겨다니게 구현했던 것 때문에 복잡하게 느꼈던 것 같습니다. 하지만 이 구현 방식은 리팩토링해서 바꾸기로 결정해 다소 해결된 부분입니다!

좋은 피드백 정말 감사합니다! 미르의 조언을 통해 많은 내용들을 학습할 수 있었습니다.

**한가지 더 드리고 싶은 질문이 있습니다!**

단순히 도메인이 가지고 있는 상태를 원시 값 형태로 전달하는 것도 강결합으로 봐야하는지 의문입니다. 예를 들어, 제 코드에서 `ResultView` 클래스의 `printLines` 메소드는 `List<List<Boolean>>` 타입으로 전달하던 사다리의 값을 이중 리스트 때문에 너무 복잡하다고 느껴져서 다시 `List<Line>`을 전달받도록 바꿨습니다. (사다리의 값은 옆으로 이동할 가로 라인이 있느냐 없느냐를 저장합니다.)

이 경우에 View가 `Line` 도메인을 알게 되지만 강결합이라고는 생각이 들지 않습니다. 단순히, `List<Boolean>`을 전달 받기 위해 `getMovableLinePoints()`을 활용할 뿐이기 때문에 값이 변경되거나, 도메인에 영향이 가지 않습니다. 이 메소드가`Line`이 제공하는 일종의 API라고 본다면 이렇게 활용하는 것도 괜찮지 않을까라는게 제 생각입니다. 미르는 어떻게 생각하시나요? 제가 잘못된 생각을 가지고 있는 건지, 더 나은 방법이 있는 건지 조언을 구하고 싶습니다.

2024-03-01 05:31 UTC, ddu0422 approved these changes
안녕하세요 리건! 미르입니다 :)
사다리 미션 구현하시느라 고생하셨어요. 🥇 
잘 구현해주셔서 미션은 여기서 마무리할게요!
다음 미션도 지금처럼 잘해주시리라 믿습니다 👍🏻 

## 답변

> View가 Line 도메인을 알게 되지만 강결합이라고는 생각이 들지 않습니다. 단순히, List<Boolean>을 전달 받기 위해 getMovableLinePoints()을 활용할 뿐이기 때문에 값이 변경되거나, 도메인에 영향이 가지 않습니다.

위와 같이 생각하는 방법도 괜찮다고 생각합니다.
미션을 진행하다보면 지금 세운 기준도 변경될 수 있으니 우테코 생활을 하시면서 찾아보는 재미를 느끼셨으면 합니다 ㅎ_ㅎ

2024-03-01 05:31 UTC, ddu0422 commented on src/main/java/domain/Point.java
> +                .orElseThrow(IllegalArgumentException::new);
👍🏻 👍🏻

2024-03-01 05:32 UTC, merged