[2단계 - 사다리 게임] 초롱(정회성) 미션 제출합니다
woowacourse/java-ladder pull request #360
Opened 2024-02-27 15:02 UTC by HoeSeong123

안녕하세요 영이! 두 번째 리뷰도 잘 부탁드립니다!

일급 컬렉션과 원시값 래핑이 아직 익숙하지 않아서 미션을 진행하는 동안 여러번 머리가 굳었습니다..
그래서 시간이 조금 오래 걸리기는 했지만 그래도 열심히 코드를 작성해봤습니다!

2단계 미션에서는 영이가 1단계 리뷰에서 피드백을 주셨던 의도를 드러내는 것과 적절한 메서드의 분리에 대해서 고민을 많이 하면서 진행해보았습니다.

미션을 진행하면서 질문할 사항도 많았었는데 따로 적어놓지 않아서 기억이 잘 나지 않네요...
다음에는 생각나는 대로 미리 작성해놔야겠습니다😭😭
추후에 질문할 사항이 생각나면 바로바로 질문드리겠습니다😁

## 주요 변경 부분
---
주요 변경 부분은 다음과 같습니다.
### interface 제거
저번 리뷰에서 영이가 얘기해주셨던 것처럼 저도 interface의 필요성을 느끼지 못했었습니다.
하지만 랜덤성에 대한 테스트를 어떻게 진행해야 할 지 감이 잘 오지 않아 자주 사용했었던 interface를 사용했었습니다.

2단계 미션을 진행하면서도 이 부분에 대해서 정말 많이 고민을 해보았습니다.
그리고 내린 결론은 `LineGenerator`를 이용하는 방법입니다.
`LineGenerator`를 이용하여 `List<Line>`을 만들고 이를 `Ladder`에게 할당하는 방식을 사용하였습니다.
이렇게 작성하니 `연속되어 연결되는 경우`에 대한 테스트도 진행할 수 있었고, 다른 테스트를 진행할 때도 제가 원하는 대로 사다리를 만들 수 있다는 장점이 있었습니다.

2024-02-28 15:38 UTC, choijy1705 requested changes
안녕하세요 초롱
2단계 잘 진행해주셨네요👍
몇가지 코멘트 남겼으니 확인해보시고 반영부탁드립니다🙏

2024-02-28 15:38 UTC, choijy1705 commented on src/main/java/ladderGame/model/LadderGenerator.java
> +public class LadderGenerator {
생성자들로 처리할 수 있는 로직들을 따로 모아두고 있네요
처음 보는 사람들은 이해하기 어렵지 않을까요?🤔

2024-02-28 15:38 UTC, choijy1705 commented on src/main/java/ladderGame/model/LadderGenerator.java
> +        if (new Random().nextBoolean()) {
random 으로 생성되는 값을 메서드 안에서 생성하면 
테스트 하기가 어렵지 않을까요??

2024-02-28 15:38 UTC, choijy1705 commented on src/main/java/ladderGame/model/Line.java
> +    }
테스트를 위한 생성자는 바람직할까요??

2024-02-28 15:38 UTC, choijy1705 commented on src/main/java/ladderGame/model/Line.java
> +        return left.equals(ConnectionStatus.CONNECTION) && left.equals(right);
enum 은 == 비교해주세요

2024-02-28 15:38 UTC, choijy1705 commented on src/main/java/ladderGame/model/Line.java
> +                .anyMatch(i -> isContinuouslyConnected(connectionStatuses.get(i), connectionStatuses.get(i + 1)));
100자 line을 넘지않도록 작성해주세요 
인텔리제이의 희미한 수직선을 의미합니다!

2024-02-28 15:38 UTC, choijy1705 commented on src/main/java/ladderGame/model/Name.java
> +    }
player 는 name을 필드로 가지고 있는데
name을 생성할대 players를 필요로하는 상황은
모순적인 상황이 아닐까요?
지금은 문제가 없을 수 있지만 나중에 순환참조의 문제에 직면할 수 있을거 같네요

2024-02-28 15:38 UTC, choijy1705 commented on src/main/java/ladderGame/model/Name.java
> +    }
```suggestion
    public boolean isAll() {
        return "all".equals(name);
    }
```
가능성은 없겠지만 항상 equals비교할때는 항상 상수가 먼저오도록 작성해주세요
그리고 all은 상수로 빼면 좋을것 같네요

2024-02-28 15:38 UTC, choijy1705 commented on src/main/java/ladderGame/model/Players.java
> +                .toList();
평범하지 않은 코드인것 같네요 🤔
for문 혹은 IntStream을 활용하는게 어떨까요?

2024-02-28 15:38 UTC, choijy1705 commented on src/main/java/ladderGame/model/Players.java
> +        return positions;
stream 활용하기 좋아보이네요

2024-02-28 15:38 UTC, choijy1705 commented on src/main/java/ladderGame/model/Players.java
> +        return false;
얘도 stream

2024-02-28 15:38 UTC, choijy1705 commented on src/main/java/ladderGame/model/Prize.java
> +            throw new IllegalArgumentException(EXCEPTION_MESSAGE_UNDEFINED_MESSAGE);
에러 메세지를 상수처리하면 어떤 이점과 단점이 있을지 고민해보면 좋겠네요

2024-02-28 15:38 UTC, choijy1705 commented on src/test/java/ladderGame/model/LineTest.java
> +        assertThatThrownBy(() -> new Line(ConnectionStatus.CONNECTION, ConnectionStatus.CONNECTION, ConnectionStatus.DISCONNECTION))
딱봐도 100자가 넘을것 같은데 적절히 개행 부탁드립니다!!

2024-02-28 15:38 UTC, choijy1705 commented on src/test/java/ladderGame/model/NameTest.java
> +    @DisplayName("이름에 영문과 숫자 외에 입력이 들어가는 경우 예외처리 된다.")
한글은 왜 막나요??

2024-02-28 15:38 UTC, choijy1705 commented on src/test/java/ladderGame/model/NameTest.java
> +    }
생성자의 정상 생성을 굳이 테스트할 필요가 있을까요?

2024-02-28 15:38 UTC, choijy1705 commented on src/test/java/ladderGame/model/LadderTest.java
> +                new Line(ConnectionStatus.CONNECTION, ConnectionStatus.DISCONNECTION, ConnectionStatus.CONNECTION),
테스트를 위한 생성자 
나중에 문제가 생기지는 않을지 한번 고민해보면 좋을것 같네요!

2024-02-29 00:44 UTC, HoeSeong123 commented on src/main/java/ladderGame/model/Line.java
> +    }
사실 이 부분은 테스트를 위해서 만들었던 것은 아닙니다..😅
원래는 생성자 오버로딩을 통해 범용성을 늘릴 수 있다는 생각으로 작성을 했었습니다.
그런데 생각해보니 테스트 코드에서만 사용되고 비즈니스 로직에서는 전혀 사용되지 않고 있는데 범용성을 위해 만들었다는 말이 어불성설인 것 같네요😥

2024-02-29 06:09 UTC, HoeSeong123 commented on src/main/java/ladderGame/model/LadderGenerator.java
> +public class LadderGenerator {
맞습니다. 해당 클래스의 로직들은 원래 `Ladder`와 `Line` 클래스의 생성자에서 처리하던 로직들입니다.
하지만 그렇게 하니 `Line`이 만들어지는 과정에 random으로 생성되는 값이 포함되어 테스트를 하기 어려웠습니다.

그래서 적용했던 방법이 interface 분리였습니다.
random으로 값을 생성하는 부분을 `BooleanGenerator`라는 별도의 interface로 분리하여 비즈니스 로직에서는 `randomBooleanGenerator`라는 클래스로 인터페이스를 상속하여 랜덤하게 값을 생성하도록 하였고,
테스트를 진행할 때는 `fixedBooleanGenerator`라는 클래스로 인터페이스를 상속하여 지정한 값을 생성하도록 하였습니다.

하지만 이렇게 했을 때의 여러 단점이 있었습니다.
1. 영이의 피드백대로 실제 애플리케이션과 동작을 다르게 하는 테스트를 위한 코드가 있다면 나중에 요구사항에 변경 사항이 생겨도 테스트는 계속 성공하기 때문에 쉽게 놓칠수 있다.
2. `Line` 클래스에서 `BooleanGenerator`라는 불필요한 멤버 변수를 가지게 된다.
3. Line 한 줄에 대한 테스트는 진행할 수 있지만 Ladder 전체에 대한 테스트는 진행하기 어렵다.

그래서 별도의 `LadderGenerator`를 만들어서 아예 사다리를 만든 후에 넘겨주는 방식으로 변경하였습니다.
이렇게 변경하니 위의 단점을 거의 해결할 수 있었습니다.
다만, 로직에 의해 사다리가 규칙(한 줄에 라인이 겹치면 안된다)을 지키며 생성되는지에 대한 테스트를 진행할 수 없다는 단점이 발생하였습니다.
이를 해결하기 위해 `Line` 클래스에서 한 줄에 라인이 겹쳐있는지를 검증하는 메서드를 추가하였습니다.

그리고 영이가 피드백주신 이해하기 어려울 수 있다는 부분에 대해서 정말 많은 고민을 해보았습니다.
제 생각은 어렵지 않을 것 같다, 또는 생성자에서 처리하는 것과 크게 다르지 않다 입니다.

우선 앞서 말씀드렸다시피 위 로직들은 생성자에서 처리하던 로직들을 그대로 가져온 로직입니다.
클래스명, 변수명, 메서드명에서 거의 변화가 없이 가져왔기 때문에 만약 해당 메서드명과 로직을 보고도 이해가 잘 되지 않는다면 생성자에서 처리했어도 비슷했을 것이라는 것이 제 생각입니다.

만약 정말 그렇다면 `LadderGenerator`를 생성해서 발생한 어려움이라기 보다는 제 로직 자체에 대한 문제라고 생각합니다.

따라서 이에 대해 궁금한 부분이 있는데 이는 밑에서 같이 질문드리겠습니다😅😅

2024-02-29 06:15 UTC, HoeSeong123 commented on src/main/java/ladderGame/model/LadderGenerator.java
> +        if (new Random().nextBoolean()) {
사실 바로 이 부분 때문에 `interface`도 시도해보고 `LadderGenerator`도 시도해본 것입니다.
두 방법을 제외하고 랜덤으로 생성되는 값을 외부에서 주입할 수 있는 방법에 대해 정말 많이 고민하고 찾아보았지만 도저히 모르겠습니다...😭

만약 영이라면 어떤 방법을 사용하시나요..
이 부분이 크루들마다도 적용 방법이 모두 달라서 리뷰어분들의 의견도 궁금합니다.

2024-02-29 06:19 UTC, HoeSeong123 commented on src/main/java/ladderGame/model/Name.java
> +    }
생각해보니 그렇네요.
완전히 놓치고 있던 부분입니다😓

2024-02-29 06:21 UTC, HoeSeong123 commented on src/main/java/ladderGame/model/Players.java
> +                .toList();
1씩 증가시키는 방법을 모르겠어서 인터넷을 뒤져 코드를 찾아왔는데 IntStream이 더 일반적으로 사용되는 방법이군요..
감사합니다!!

2024-02-29 06:49 UTC, HoeSeong123 commented on src/main/java/ladderGame/model/Prize.java
> +            throw new IllegalArgumentException(EXCEPTION_MESSAGE_UNDEFINED_MESSAGE);
문자열이나 메세지 등은 상수처리 하는 것이 당연하다고 생각되어 한 번도 생각해 본 적이 없었습니다.
영이의 피드백을 보고 에러 메세지를 상수처리 했을 때의 이점과 단점에 대해서 고민해보았습니다.

제가 생각한 이점은 관리가 쉽다는 점입니다.
특히 에러 메세지가 중복되는 경우 이 이점은 더욱 극대화 된다고 생각합니다.
또한 상수처리한 변수명의 컨벤션을 정한다면 어디서 에러 메세지가 사용되었는지 찾기도 쉽다고 생각합니다.

하지만 만약 에러 메세지가 중복되지 않는다면 위 이점들은 더이상 이점으로 작용하지 않게 된다고 생각합니다.
에러 메세지를 찾는 것 같은 경우도 메세지 자체에서 컨벤션을 정한다면 해결할 수 있는 문제라는 것을 알게 되었습니다.

항상 하드 코딩되지 않게 모든 상수와 문자열을 상수처리 해야 한다고 생각했는데 이와 같은 경우는 하드코딩으로 보는 것도 적절하지 않다는 생각이 드네요.

당연하다고 생각했던 것에 대해 다시 한 번 생각해보게 해주어서 감사합니다😀

2024-02-29 06:55 UTC, HoeSeong123 commented on src/test/java/ladderGame/model/NameTest.java
> +    @DisplayName("이름에 영문과 숫자 외에 입력이 들어가는 경우 예외처리 된다.")
해당 부분은 고민을 많이 하다가 출력에 대한 요구사항이 없었기에 완전히 제 개인적인 불편함으로 추가하게 되었습니다.

영문과 숫자의 경우 콘솔창에서 1칸을 차지하는 반면에 한글의 경우 2칸을 차지한다는 것을 알게 되었습니다.
따라서 이름 목록을 출력할 때 각 이름별로 6칸의 공간을 차지하도록 구현하였는데 한글을 작성하게 되는 경우 한 글자에 2칸을 차지해서 모든 이름들이 밀려서 출력되었습니다.

사실 절대 필요한 부분은 아니지만 개인적으로 너무 보기 불편하여 한글을 제한하였습니다..😥
같은 이유로 `Prize`를 입력받을 때에도 꽝 또는 숫자만 입력할 수 있도록 구현하였습니다.

한글은 2글자 까지만 입력할 수 있도록 조건을 추가할까도 생각해보았지만 한글과 영어가 섞이는 경우 등 너무 많은 경우의 수가 발생하게 될 것 같아 그냥 한글 자체를 제한시켰습니다.

혹시 별다른 요구사항이 없더라도 제가 개인적으로 요구사항을 설정하면 안되는 걸까요?😅

2024-02-29 06:59 UTC, HoeSeong123 commented on src/test/java/ladderGame/model/NameTest.java
> +    }
사실 저번 피드백에서도 생성자 테스트에 대한 피드백을 받았어서 이 부분을 정말 많이 고민을 했었습니다.

만약 Name에 별다른 검증 메서드가 없다면 정상 생성에 대한 테스트를 진행할 필요가 없다고 생각합니다.
하지만 만약 검증 메서드가 있다면 당연히 정상적으로 생성이 되지 않는 경우를 테스트 해야겠지만 정상적으로 생성이 되는 경우에 대해서도 테스트를 진행해야 한다고 판단하였습니다.

그래야 조건을 모두 만족하면 정상적으로 생성이 되는지 알 수 있다고 생각하기 때문입니다.

2024-02-29 07:37 UTC, HoeSeong123 commented on src/test/java/ladderGame/model/LadderTest.java
> +                new Line(ConnectionStatus.CONNECTION, ConnectionStatus.DISCONNECTION, ConnectionStatus.CONNECTION),
테스트를 위한 생성자를 만들었을 때 생길 수 있는 문제점은 혼동을 일으킬 수 있다는 점일 것 같습니다.
도메인 클래스를 비즈니스 요구사항을 담아내는 설계도라고 하면, 코드만 보아도 비즈니스 로직을 이해할 수 있어야 하는데 이를 방해한다고 생각합니다.
이런 결론을 도출하기까지 많은 크루들에게 물어봤었습니다.
그러면서 동시에 이런 의문이 생겼습니다.

저는 해당 생성자를 이용하여 테스트를 진행하였을 때 `List.of()`라는 것을 사용하지 않아도 되기 때문에 편리하고, 코드도 더 자연스럽게 보인다고 생각했었습니다.
하지만 테스트를 위한 생성자를 만들었을 때 위와 같은 문제가 발생한다면 해당 생성자의 접근 제어자를 `public`이 아닌 `default`로 설정한다면 비즈니스 로직에서 사용될 일이 없어 위의 문제가 발생하지도 않고, 테스트 코드도 자연스럽게 작성할 수 있다는 이점을 같이 적용할 수 있을 것 같다는 생각이 들었습니다.

조금 쓸데없는 고민 같기는 하지만 이에 대한 영이의 생각이 궁금합니다!😁😁

2024-02-29 07:54 UTC, HoeSeong123 commented on src/main/java/ladderGame/model/Line.java
> +                .anyMatch(i -> isContinuouslyConnected(connectionStatuses.get(i), connectionStatuses.get(i + 1)));
```java
private static final String EXCEPTION_MESSAGE_LESS_THAN_MINIMUM = "참여자의 이름은 두 개 이상이어야 합니다.";
``` 
이런 상수처리된 코드 같은 경우 100자 line을 넘는 경우가 꽤 있는 것 같은데 이런 것도 수정해야 하나요?

2024-02-29 08:42 UTC, HoeSeong123 commented on src/test/java/ladderGame/model/LadderTest.java
> +                new Line(ConnectionStatus.CONNECTION, ConnectionStatus.DISCONNECTION, ConnectionStatus.CONNECTION),
테스트를 위한 생성자를 제거하고 코드를 작성해보았습니다.
그런데 생성자를 사용하였을 때와 아닐 때를 비교하니 차이가 조금 많이 난다고 생각하였습니다.

생성자 사용 X
```java
Ladder ladder = new Ladder(
        new Line(List.of(ConnectionStatus.CONNECTION, ConnectionStatus.DISCONNECTION, ConnectionStatus.CONNECTION)),
        new Line(List.of(ConnectionStatus.DISCONNECTION, ConnectionStatus.DISCONNECTION, ConnectionStatus.CONNECTION)),
        new Line(List.of(ConnectionStatus.CONNECTION, ConnectionStatus.DISCONNECTION, ConnectionStatus.CONNECTION)),
        new Line(List.of(ConnectionStatus.DISCONNECTION, ConnectionStatus.CONNECTION, ConnectionStatus.DISCONNECTION)),
        new Line(List.of(ConnectionStatus.DISCONNECTION, ConnectionStatus.DISCONNECTION, ConnectionStatus.CONNECTION))
);

생성자 사용
```java
Ladder ladder = new Ladder(
        new Line(ConnectionStatus.CONNECTION, ConnectionStatus.DISCONNECTION, ConnectionStatus.CONNECTION),
        new Line(ConnectionStatus.DISCONNECTION, ConnectionStatus.DISCONNECTION, ConnectionStatus.CONNECTION),
        new Line(ConnectionStatus.CONNECTION, ConnectionStatus.DISCONNECTION, ConnectionStatus.CONNECTION),
        new Line(ConnectionStatus.DISCONNECTION, ConnectionStatus.CONNECTION, ConnectionStatus.DISCONNECTION),
        new Line(ConnectionStatus.DISCONNECTION, ConnectionStatus.DISCONNECTION, ConnectionStatus.CONNECTION)
);

두 코드를 비교했을 때 `List.of()`를 사용하지 않는 쪽이 더 자연스럽고 코드도 아주 조금이기는 하지만 짧아진다는 장점을 얻었다고 생각합니다.

2024-02-29 13:23 UTC, choijy1705 requested changes
초롱 피드백 잘 반영해주셨습니다👍
몇가지 추가 코멘트 남겼습니다
확인 부탁드려요!

2024-02-29 13:23 UTC, choijy1705 commented on src/main/java/ladderGame/model/Command.java
> +        if(!command.equals("all")) {
!"all".eqauls(command)
npe가 자주나는 부분입니다.
습관적으로 상수를 앞으로 작성하면 좋습니다

2024-02-29 13:23 UTC, choijy1705 commented on src/main/java/ladderGame/model/Command.java
> +        if(!command.equals("all")) {
상수를 선언하고 사용하고 있지 않기도 하네요😭

2024-02-29 13:23 UTC, choijy1705 commented on src/main/java/ladderGame/model/LadderGenerator.java
> +        if (new Random().nextBoolean()) {
자동차 미션을 떠올려보면 좋을것 같네요!
랜덤값은 보통 상위 레벨에서 파라미터로 전달하고 실제 사용하는 쪽에서는 그 값이 랜덤인지 모르도록 처리하는 방법을 쓰지 않았나요??

2024-02-29 13:23 UTC, choijy1705 commented on src/main/java/ladderGame/model/Line.java
> +                    return isConnectedTwice(connectionStatuses.get(i), connectionStatuses.get(i + 1));
굳이 {}를 활용하지않아도 될것 같네요

2024-02-29 13:23 UTC, choijy1705 commented on src/main/java/ladderGame/model/Player.java
> +    public boolean hasName(Name name) {
hasName은 조금 어색하지 않나요??

2024-02-29 13:23 UTC, choijy1705 commented on src/main/java/ladderGame/model/Player.java
> +        position = line.descend(position);
```suggestion
        this.position = line.descend(position);
```

2024-02-29 13:23 UTC, choijy1705 commented on src/main/java/ladderGame/model/Players.java
> +        players = IntStream.range(0, names.size())
```suggestion
        this.players = IntStream.range(0, names.size())
```

2024-02-29 13:23 UTC, choijy1705 commented on src/test/java/ladderGame/model/LadderTest.java
> +                new Line(ConnectionStatus.CONNECTION, ConnectionStatus.DISCONNECTION, ConnectionStatus.CONNECTION),
우선 코드가 이쁜 문제는 애플리케이션이 더 중요할것 같습니다
적절히 변수를 분리하여서 한번에 ladder를 생성할 필요도 없을것 같고요

테스트를 위한 코드를 애플리케이션에 남겨두면 다른 사람이 나중에 무분별하게 사용할 수 있습니다
그렇다면 원치 않은 동작을 일으키기 쉽고
나중에 여러 사람과 작업한다고 생각했을때 한사람 한사람씩 테스트를 위한 코드를 넣는다면
테스트를 위한 메서드 생성자들이 넘쳐날 것 같아요😭

2024-02-29 13:23 UTC, choijy1705 commented on src/test/java/ladderGame/model/NameTest.java
> +    @DisplayName("이름에 영문과 숫자 외에 입력이 들어가는 경우 예외처리 된다.")
요구사항을 적절히 추가하는건 괜찮습니다
다른 크루들은 그런 제약이 없는데 초롱은 제약을 둬서 
궁금하여 질문하였습니다😄

2024-02-29 13:23 UTC, choijy1705 commented on src/main/java/ladderGame/model/LadderGenerator.java
> +        if (new Random().nextBoolean()) {
![image](https://github.com/woowacourse/java-ladder/assets/63634505/e708db35-8d79-4391-a3b9-c9992e313354)

random으로 아무런 값을 만들어도되는 list(makeConnections)를 만들고 (테스트가 필요하지 않는)
위 list를 주입하여 원하는 line이 생성되도록 생각해봤습니다
이렇게 짰을때 line을 생성하는데 테스트는 어려울까요??

2024-02-29 13:35 UTC, HoeSeong123 commented on src/main/java/ladderGame/model/Command.java
> +        if(!command.equals("all")) {
헉.....완전 기초적인 실수를 했네요...
집에 가고 싶다는 일념만 가득했던 것 같습니다............
다음부터는 한 번 더 확인하고 리뷰 요청 드릴게요😱😱😭😭😭😭

2024-02-29 13:41 UTC, HoeSeong123 commented on src/main/java/ladderGame/model/LadderGenerator.java
> +        if (new Random().nextBoolean()) {
Line 을 만들 때 무조건 랜덤한 값을 생성함과 동시에 만들어야 한다고 생각했었는데
영이가 알려준 방법은 일단 조건 상관없이 랜덤한 값으로 리스트를 만든 후에, 조건을 따져가며 그 리스트에서 값을 꺼내오는 방식이군요....

정말 전혀 생각해보지 못한 방법입니다.
이렇게 다시 한 번 영이와 저의 차이를 실감하게 됩니다..

랜덤한 값만 관련되면 뇌가 굳는 것 같은 기분이에요..
정말 감사합니다 영이!!!!
참고해서 코드 수정해보겠습니다😆😆😆

2024-02-29 13:42 UTC, HoeSeong123 commented on src/main/java/ladderGame/model/Line.java
> +                    return isConnectedTwice(connectionStatuses.get(i), connectionStatuses.get(i + 1));
아 람다식에서 줄바꿈을 하면 무조건적으로 {}를 활용해야 하는 줄 알고 있었습니다😅😅

2024-02-29 13:43 UTC, HoeSeong123 commented on src/main/java/ladderGame/model/Player.java
> +    public boolean hasName(Name name) {
듣고보니 그런 것 같아요.
hasName은 오히려 `Players` 클래스에서 사용되어야 할 것 같은 메서드명이네요.
다시 한 번 고민해보겠습니다!

2024-02-29 13:48 UTC, HoeSeong123 commented on src/test/java/ladderGame/model/LadderTest.java
> +                new Line(ConnectionStatus.CONNECTION, ConnectionStatus.DISCONNECTION, ConnectionStatus.CONNECTION),
확실히 제가 협업의 시선에서는 생각하지 않았던 것 같네요..

코드가 이뻐보이고 자연스럽게 읽히는 것도 좋지만 최우선적으로 중요한 것은 비즈니스 로직이라는 것을 간과했습니다.
확실히 여러 명이 함께 사용하는 코드라고 생각했을 때 각자만의 기준이 있을 것이고 모두가 저처럼 이쁜 테스트 코드 작성을 위한 생성자를 만든다고 생각해보니 정말 끔찍하네요..🤮

2024-03-01 02:52 UTC, choijy1705 approved these changes
초롱 정말 빠르게 반영해주셨네요!
이번 미션은 여기서 머지해도 될 것 같아요👍
다음 단계도 화이팅입니다
추가 코멘트 남겼는데 궁금한점 있으면 편하게 DM 주세요

2024-03-01 02:52 UTC, choijy1705 commented on src/main/java/ladderGame/model/Command.java
> +        if(!COMMAND_ALL.equals(command)) {
all인지 체크하는 로직이 validate에서 체크하고 return해주면 
더 깔끔할것 같네요!

2024-03-01 02:52 UTC, choijy1705 commented on src/main/java/ladderGame/model/RandomConnectionGenerator.java
> +        Random random = new Random();
random은 매번 생성하기보다 static으로 빼놔도 좋을것 같네요!

2024-03-01 02:52 UTC, choijy1705 commented on src/test/java/ladderGame/model/RandomConnectionGeneratorTest.java
> +}
```suggestion
}

```

2024-03-01 02:52 UTC, choijy1705 commented on src/test/java/ladderGame/model/PlayerTest.java
> +}
```suggestion
    @Test
    @DisplayName("Line의 연결 여부에 따라 위치를 변경한다.")
    void descendLine() {
        // given
        Line line = new Line(
                List.of(
                        ConnectionStatus.CONNECTION,
                        ConnectionStatus.DISCONNECTION,
                        ConnectionStatus.CONNECTION
                ));


        Player player1 = new Player("pobi", 0);
        Player player2 = new Player("crong", 1);

       // when
        player1.move(line);
        player2.move(line);

        // then
        assertThat(player1.getPosition()).isEqualTo(1);
        assertThat(player2.getPosition()).isEqualTo(0);
    }
}
```
given-when-then 을 명시해주면 다른 사람들이 더 쉽게 이해할 수 있을것 같아요!

2024-03-01 02:52 UTC, choijy1705 commented on src/test/java/ladderGame/model/LineTest.java
> -        }, 5);
👍
뭔가 속이 시원해지는 느낌이네요

2024-03-01 02:52 UTC, merged

2024-03-01 03:06 UTC, HoeSeong123 commented on src/test/java/ladderGame/model/RandomConnectionGeneratorTest.java
> +}
아 노트북에서는 설정을 해놨었는데 데스크탑에서 설정을 깜빡했네요😅

2024-03-01 03:08 UTC, HoeSeong123 commented on src/test/java/ladderGame/model/LineTest.java
> -        }, 5);
격하게 동의합니다 ㅎㅎ
처음엔 당연히 저게 맞다고 생각했었는데 영이와 의견을 주고받으면서 수정에 수정을 거듭하고 다시 보니 굉장히 이상해보이는 코드네요😂
너무 좋은 피드백을 주셔서 거듭 감사드립니다 영이!!!🥰