[2단계 - 사다리 게임 실행] 콜리(김건우) 미션 제출합니다
woowacourse/java-ladder pull request #364
Opened 2024-02-28 06:18 UTC by coli-geonwoo

안녕하세요 썬 😄 

조금 늦게 구현을 완료하여 늦은 리뷰요청 드리는 점 양해부탁드립니다.
이번 미션에서 TDD를 지키며 test를 검증이 아닌 설계를 위한 기반으로
활용하는 연습이 제게는 아직 어색하게 느껴지는 것 같아요 😅 

2단계에서는 **사다리 게임을 추상화**하기 위해 노력했어요. 이 추상화된 생각을 먼저 말씀드리는 게 좋을 것 같아 간단히 말씀드려 볼게요! 

처음에는 사다리를 player(참여자)와 result(실행 결과)를 잇는 게임이라고 생각했어요. 그래서 2단계 초반에는 Name과 Result 각 객체를 따로 설계해주었습니다.
```
   player
     |
     |
  result
```
그런데 player와 result는 서로 닮은 점이 많았어요. 
1) 출력 형식이 같았으며(indent) 2) 
검증로직(1-5이하의 영문자여야 한다는 점)도 같았습니다.

그래서 사다리를 게임을 각 Element를 매핑하는 로직으로 추상화했습니다.
이는 LadderGame의 멤버변수가 Map<Element, Element> gameResults로 정의하게 된 생각의 기반이기도 합니다.
```
   Element1   Element2'
     |                |
     |                |
  Element1'    Element2'
```

2단계 구현사안은 다음과 같습니다.

## 2단계 구현사항

### [domain]

- ladder/RowLine - 좌우 Connection에 따라 이동하는 move 구현
- ladder/Ladder - RowLine 배열 단위로 이동을 수행하는 move 구현
- gameelements/Element - 사다리의 출발/도착 노드를 Element로 추상화한 객체(이전의 Name)
- gameelementsElements - Element의 일급 컬렉션 객체
- LadderGame - 사다리 게임 결과(상위 노드-하위노드 맵핑 결과)를 인스턴스 변수로 가지는 객체
- LadderGame - 상위 노드의 이름을 조회하여 결과를 반환하는 기능 구현

### [view]

- view/ResultView - 하위노드 출력기능 구현
- view/ResultView - 플레이어 이름에 따라 결과 출력기능 구현

### [test]

- TrueFalseConnectionGenerator : `연결-비연결`을 반복하여 생성하는 generator
- LadderGameTest : input 값에 따라 사다리 게임 결과 테스트

## 2단계 개선사안
- 컨벤션!! 코드 컨벤션 2번 확인하기(이번에는 컨벤션 위반 피드백이 없길 기대합니다 😢 )

2024-02-28 17:02 UTC, syoun602 requested changes
안녕하세요 콜리~!

2단계 잘 구현해주셨네요 👍
좀 더 고민해볼만한 부분들 코멘트 남겨두었으니 확인 부탁드려요~
궁금한 점이 있다면 언제든 DM 주셔도 됩니다!

2024-02-28 17:02 UTC, syoun602 commented on src/main/java/laddergame/constants/ReservedElementName.java
> +    private ReservedElementName(){
```suggestion
    private ReservedElementName() {
```

2024-02-28 17:02 UTC, syoun602 commented on src/main/java/laddergame/constants/ReservedElementName.java
> +    public static final List<String> reservedNames = new ArrayList<>(List.of("all"));
이름에 대한 예약어를 설정하셨군요 👍
근데 `new ArrayList<>`로 따로 감싸신 이유가 궁금합니다 🤔
또한, 이름에 대한 예약어라면 `Element` 클래스의 상수로 넣는건 어떤가요?

2024-02-28 17:02 UTC, syoun602 commented on src/main/java/laddergame/domain/gameelements/Elements.java
> +    }
인텔리제이에서 `Collections.unmodifiableList(elements);`에 대해 경고를 띄우고 있습니다.
`Stream.java`에 `toList()`를 한번 살펴볼까요~?

2024-02-28 17:02 UTC, syoun602 commented on src/main/java/laddergame/controller/LadderGameController.java
> +        Elements people = retryUntilNoError(() -> new Elements(InputView.readNames()));
엇 `NumberFormatException`나 `,`로 끝나는 입력에 대한 처리만 하는 줄 알았는데 제가 코드를 오해했네요 😢
넵 저도 도메인 스스로 생성에 대한 검증을 가져가는게 중요하다고 생각합니다 👍

2024-02-28 17:02 UTC, syoun602 commented on src/main/java/laddergame/controller/LadderGameController.java
> +    }
해당 검증은 컨트롤러의 책임일까요?

2024-02-28 17:02 UTC, syoun602 commented on src/main/java/laddergame/domain/LadderGame.java
> +    private final Map<Element, Element> playerGameResult;
비슷한 역할로 인해 추상화를 시도해보신 것은 좋은 것 같습니다.
하지만 `Element`라는 단어로 현재 구현하신 사다리 게임을 잘 표현하지 못하는 것 같아요.
PlayerGameResult에 Element to Element가 이해하기 좋은 코드일 지 고민해봅시다. 😢

차라리 `Name`을 추상화하고 `Player`, `Result`로 나누거나
`Name`이라는 객체를 재사용하도록 `Players`, `Prizes`로 나눠볼 수 있을 것 같아요.
실제 요구사항에는 없지만 콜리가 정의하신대로 PlayerName = PrizeName는 같을 수 있어도
`Players` = `Prizes`가 정말 동일한 객체일까요?
`Prizes`가 있었다면 상품 개수가 플레이어 수와 같지 않다면 예외를 던지는 검증을 해볼 수 있었을 것 같아요.

2024-02-28 17:02 UTC, syoun602 commented on src/main/java/laddergame/domain/LadderGame.java
> +    public Element findPlayerResult(Element playerName) {
메서드 파라미터와 리턴 타입만 봐서는 그냥 상품 객체를 넣어볼 수도 있겠네요.

2024-02-28 17:02 UTC, syoun602 commented on src/main/java/laddergame/domain/connectiongenerator/ConnectionGenerator.java
> +    List<Connection> generate(int connectionNumber);
개인적으로는 파라미터에 number나 count라는 단어로도 충분해보입니다!

2024-02-28 17:02 UTC, syoun602 commented on src/main/java/laddergame/domain/connectiongenerator/RandomConnectionGenerator.java
> +    private static final Random random = new Random();
👍

2024-02-28 17:02 UTC, syoun602 commented on src/main/java/laddergame/domain/gameelements/Element.java
> +
줄바꿈 👀

2024-02-28 17:02 UTC, syoun602 commented on src/main/java/laddergame/domain/gameelements/Element.java
> +    public boolean equals(Object obj) {
eq&hc와 tostring👍
다만 `toString()`을 view에서 사용하는게 맞을지 고민해봅시다!

`hint: 이펙티브 자바 아이템 12. toString을 항상 재정의하라`

2024-02-28 17:02 UTC, syoun602 commented on src/main/java/laddergame/domain/ladder/Ladder.java
> +    public List<Integer> move(int peopleNumber) {
Ladder가 움직이나요? 🤔

2024-02-28 17:02 UTC, syoun602 commented on src/main/java/laddergame/domain/ladder/RowLine.java
> +        if (checkLeftPosition(playerPosition - 1)) {
```suggestion
    private int moveByConnection(int playerPosition) {
        if (checkLeftPosition(playerPosition - 1)) {
```

2024-02-28 17:02 UTC, syoun602 commented on src/main/java/laddergame/domain/ladder/RowLine.java
> +                && connections.get(rightPosition) == CONNECTED;
`connection.isConnected()`와 같은 함수로 좀 더 객체지향적인 코드를 작성해보아요

2024-02-28 17:02 UTC, syoun602 commented on src/main/java/laddergame/view/MessageResolver.java
>  public class MessageResolver {
개인적일 수 있으나 저는 `ResultView` 하나로도 충분하다고 생각합니다.
차라리 ResultView 하나로 코드의 응집도를 높이고, 불필요한 분리를 방지해 간결하게 가져갈 수 있을 것 같아서요.
현재는 오히려 관리 포인트나 코드 복잡도가 더 늘어나보입니다. 
이번에 Element를 변경할 때도 두 클래스 모두 변경해야하는 번거로움이 있지 않았나요?

+) 적용하지 않으셔도 됩니다. 지금은 도메인, OOP, Test에 대한 고민이 더 중요할 것 같아서요. 생각만 남겨주세요 :)

2024-02-28 17:02 UTC, syoun602 commented on src/main/java/laddergame/view/ResultView.java
> +        System.out.println(resolveElementMessage(lowerElements));
StringBuilder를 활용해봅시다 👀

2024-02-28 17:02 UTC, syoun602 commented on src/test/java/laddergame/domain/LadderGameTest.java
> +    void ladderGameResultTest() {
테스트 코드도 유지보수 대상이라고 생각해주세요. 😢
특히 테스트 코드는 요구사항에 대한 문서라고 볼 수 있기 때문에 
일반적으로 단순하고 명확해야 합니다 (프로덕션 코드보다 더 읽기 쉬워야 해요). 
이때 for, if와 같은 로직이 들어간다면 더더욱 알아보기 힘들어지죠. 
현재라면 추후 비즈니스 코드에 변경이 생겼을 때 이 테스트를 고치고 싶다는 생각이 들 것 같지 않습니다 😭

또한, 현재 테스트 코드는 하나의 테스트가 아닌 것 같아요.

2024-02-29 17:25 UTC, coli-geonwoo commented on src/main/java/laddergame/constants/ReservedElementName.java
> +    private ReservedElementName(){
썬.. 😢  머리 숙여 죄송합니다.. 컨벤션은 예의라 생각하게 되어 많이 신경을 썼는데도 아직 익숙치 않네요. 컨벤션을 빨리 익히고 스스로 어색함을 느껴볼 수 있도록 노력해보겠습니다!

2024-02-29 17:29 UTC, coli-geonwoo commented on src/main/java/laddergame/constants/ReservedElementName.java
> +    public static final List<String> reservedNames = new ArrayList<>(List.of("all"));
- ArrayList로 감싼 이유
- 예약어가 all의외의 단어들도 포함되도록 확장될 수 있다고 생각했습니다.

이 부분을 고민해봤는데 지금은 따로 클래스를 만들어서 관리할만큼의 사이즈는 아니라는 썬의 의견에 설득되었습니다. 그러나, 조금 다른 의견이 있다면 예약어에 대한 검증은 Name이 아니라 Player들로 가는게 더 올바른 방향인 것 같습니다! Prize명으로는 all이 와도 괜찮다고 생각했어요!

이 의도를 담아 리팩터링한 코드에서는 Players에서 예약어 all에 대한 검증을 해주고 있습니다!

2024-02-29 17:30 UTC, coli-geonwoo commented on src/main/java/laddergame/domain/gameelements/Elements.java
> +    }
상수화에 대한 경고라 훅 넘어갔는데 Stream.toList()에서 이미 불변리스트를 반환해주고 있군요 🤔

2024-02-29 17:32 UTC, coli-geonwoo commented on src/main/java/laddergame/controller/LadderGameController.java
> +    }
위의 코드는 책임 주체를 정확히 찾지 못해서 컨트롤러에 삽입했던 것 같아요.
그러나, 썬의 제안대로 Players와 Prizes를 구분하였더니 각 일급컬렉션이 다른 책임, 즉 다른 역할들을 수행하고 있다는 사실을 더 명확히 알게 된 것 같아요!

Prizes 객체에 검증책임을 이전해주었습니다!

2024-02-29 17:35 UTC, coli-geonwoo commented on src/main/java/laddergame/domain/LadderGame.java
> +    private final Map<Element, Element> playerGameResult;
알고리즘의 노드연결(그래프) 문제로 추상화를 해보려 했는데, 말씀하신대로 장점보다 단점이 많은 것 같아요.

그렇게 판단한 이유는
1. 너무 뭉뚱그린 추상화로 각 객체 간의 다른 책임이 생략되어 있다.
=> Prizes의 길이가 Players에 종속되는 책임이 생략됨

3. 같은 노드로 표현됨으로써  Player-Prize가 동등한 위치를 지니게 된 점
=>LadderGame의 결과값인 Map<Element-Element>는 Map<Prize -Player>가 되어도 상관없다.

추상화는 코드 단순화에 좋은 아이디어지만, 오히려 너무 추상화된 개념은 각 객체의 책임과 역할을 엉뚱한 곳으로 이전시킬 수 있다는 점을 배운 것 같아요 😄

2024-02-29 17:36 UTC, coli-geonwoo commented on src/main/java/laddergame/domain/connectiongenerator/ConnectionGenerator.java
> +    List<Connection> generate(int connectionNumber);
generator를 만들고, 메서드명으로 generate를 설정하지 않다니!! 반영해주었습니다!

2024-02-29 17:43 UTC, coli-geonwoo commented on src/main/java/laddergame/domain/gameelements/Element.java
> +    public boolean equals(Object obj) {
println할 때 toString이 자동으로 호출되는 군요..  객체를 ResultView에서 출력하니 toString은 빼주어도 좋을 것 같습니다!

hint 주신 글도 읽어보았는데 toString을 객체 내에서 정의하는 의의는 `객체간 메세지를 간결하고 유용한 것을 선별하여 제공한다는 것`에 있다는 사실도 알아갑니다!

2024-02-29 17:44 UTC, coli-geonwoo commented on src/main/java/laddergame/domain/ladder/Ladder.java
> +    public List<Integer> move(int peopleNumber) {
메서드 명이 잘 생각이 나진 않지만 그래도 괜찮다 생각한 getResultIndex로 rename해주었습니다 🤔

2024-02-29 17:48 UTC, coli-geonwoo commented on src/main/java/laddergame/view/ResultView.java
> +        System.out.println(resolveElementMessage(lowerElements));
각 메세지간의 줄바꿈을 포함하기 위해 StringJoiner로 리팩터링 해주었습니다.

2024-02-29 17:52 UTC, coli-geonwoo commented on src/test/java/laddergame/domain/LadderGameTest.java
> +    void ladderGameResultTest() {
리팩터링 한 사안들입니다.

피드백1. test 가 지닌 책임이 너무 많다. => 책임 분리
     - test/RowLineTest : 연결 행(connections) 단위 이동 책임 테스트
    - test/LadderTest : List<RowLine> 단위 이동 책임 테스트
    - test/LadderGameTest : Player- Prize 매핑 결과 책임 테스트

피드백2. 비즈니스 코드에 변경 시 유지보수 => 파라미터 생성 메서드와 테스트 메서드 이원화
: ParameterizedTest의 @MethodSource 기능을 통해 테스트 케이스 생성 과정과 테스트 과정을 이원화하여 더 명확히 테스트 흐름이 보이도록 노력했습니다.

2024-02-29 18:05 UTC, coli-geonwoo commented on src/main/java/laddergame/view/MessageResolver.java
>  public class MessageResolver {
개인적으로는 MessageResolver가 있는 것이 좋다는 생각인데, 썬을 설득해보고 싶다는 욕심이 생겼습니다.

주장1. MessageResolver는 TDD에 더 잘 어울리는 클래스이다.
- 썬의 피드백을 듣고 ResultView에 메세지 구성 + 출력화면 구성 기능을 통합하여 보았는데 메세지 구성 기능이 모두 private화되면서 UITest를 진행해볼 수 없다는 문제가 있었어요! 출력캡처를 통한 방법도 있겠지만 단위 테스트를 위해서는 현재 ResultView처럼 한 메서드에 메세지를 조합하여 출력하는 것이 아닌 단위별로 메세지 출력메서드를 만들어야 한다는 점이 있었습니다. MessageResolver의 각 요소마다의 메세지 구성 검증이 TDD를 하는데 조금 더 좋은 방식일 수도 있지 않을지 여쭙고 싶어요!

-주장2. 관리포인트의 이원화를 통한 유지보수성의 향상
- MessageResolver는 메세지를 ResultView에 넘겨주고 ResultView는 받은 메세지를 적절한 위치에 조합하여 출력만 해주고 있는 객체입니다. 적절한 비유일진 모르겠지만 축구선수를 교체하는 건 MessageResolver에서, 포메이션을 변경하는 건 ResultView에서 담당하고 있어요! 그렇기에 수정하고 싶은 부분에 따라 한 객체만 수정해도 될 것 같다는 생각이 들어요! 메세지 구성을 변경하고 싶다면 MessageResolver만을, 메세지 출력 위치를 변경하고 싶다면 ResultView에서 결과화면을 수정하는 식으로 관리 포인트가 이원화됨으로써 오히려 리팩터링 의도에 따라 더 빠른 접근이 가능하지 않을까 하는 장점도 떠올려보았습니다!

주장3. 요소의 확장성
현재는 Players, Ladder, Prizes / 게임결과들 로 요소들이 한정되어 있지만 그 요소가 확장된다면 메세지를 구성하는 메서드와 출력하는 메서드가 한 클래스에 너무 많이 모일 수 있다는 생각이 들었어요! 응집성은 높아지겠지만 요소 확장에 따라 너무 많은 책임을 한 클래스에서 담당하게 하는 것은 아닐까에 대한 생각도 있었습니다. 그러나, 사다리 게임의 위에 서술한 4가지 요소 외로 확장될 가능성은 크지 않아 보여서 현재 사이즈에서는 하나의 클래스로 관리하는 것이 더욱 편하다는 썬의 의견도 이해가 되었습니다!

썬MessageResolver로의 분리를 통해 썬이 느꼈던 코드 복잡도가 늘어난 부분들에 대한 자세한 묘사가 있으면 객체 분리의 단점에 대한 이해가 더 쉬울 것 같아요!
-

2024-02-29 18:10 UTC, coli-geonwoo commented
안녕하세요 썬 😄 먼저 늦은 시간까지 리뷰해주심에 너무나 감사드립니다. 말로는 다 표현드리지 못하지만 피드백 하나하나마다 제가 바라보는 세상이 넓어지고 있다는 사실을 느껴요. 저도 썬처럼 넓고 깊은 생각을 하는 개발자고 되고 싶습니다.

2단계 1차 리팩터링인 만큼 아직 PR보다는 수정할 부분들에 대한 피드백을 천천히 남겨주셨으면 좋겠어요! 주말을 활용해 월요일까지는 2차 리팩터링을 해서 썬에게 더 많은 생각을 공유받고 싶어요 😶 

2단계 1차 `개선사안과 고민하고 있는 점`은 다음과 같습니다.

## 2단계 - 1차 리팩터링 개선사안

- gameelements/Elements : 책임에 따라 Players와 Prizes로 분할
- gameelements/Players : 예약어 검증 책임 수행 (ReservedElementName 클래스에서 책임 이전)
- gameelements/Prizes : Players와 동일길이 검증 책임 수행(controller에서 책임 이전)
- ConnectionGenerator : 메소드명 변경 getConnections > generate
- ladder/Connection : connection.isConnected()를 통해 연결정보를 메세지로 전달
- Stream.toList와 중복된 상수화(unmodifiableList) 제거
- view/ResultView : StringJoiner를 통한 메세지 구성
- test/LadderGameTest : 테스트 단순화 및 책임 분할
    - test/RowLineTest : 연결 행(connections) 단위 이동 책임 테스트
    - test/LadderTest : List<RowLine> 단위 이동 책임 테스트
    - test/LadderGameTest : Player- Prize 매핑 결과 책임 테스트

## 고민하고 있는 점

1. `인덱스에 의존하는 코드의 한계가 있지 않을까?`
    - Ladder에서 반환하는 ResutIndex는 [0, playerNumber) 연속 index가 사다리를 타고 내려온 index값들이다.
    - LadderGame에는 이 index를 기준으로 Player들의 이름과 Prize를 매칭시킨다.
    - 객체의 고유한 식별자가 아닌 index에 의존한 코드가 좋은 코드일까?


2. `index 원시값 포장`
    - index를 int로 활용함으로써 그 의미가 코드 내에서 잘 드러나지 않는 부분들이 있는 것 같다.
    - Position을 통해 Position.moveLeft()와 같은 메서드로 더 뚜렷한 의의를 나타낼 수 있지 않을까?
    - 그러나, Wrapping을 해도 index 이상의 의미를 지니기 힘든데, 장점이 더 많은 리팩터링일까?


3. `LadderGame은 멤버변수로 Ladder, Players, Prizes를 지녀야 할까?`
    - LadderGame은 생성자에서 결과값 Mapping을 초기화한다.
    - 게임 결과인 Map이외에는 멤버변수를 가지지 않기에 반복되는 매개변수를 지닌 메서드를 선언해주어야 했다.
    - 그렇다보니 코드가 복잡해지는 듯한 느낌을 받았다.
    - 그러나, LadderGame에 결과값만을 넣은 이유는 다음과 같다.
        - LadderGame의 책임은 Player-Prize 매핑의 사다리 게임의 결과산출이다.
        - Map 안에 Player와 Prize 정보가 이미 내포되어 있다.
        - 불필요한 멤버변수는 의존관계를 늘릴 우려가 있다.


크루들 중에는 LadderGame이 Game이기 위해서는 Players, Ladder, Prizes를 멤버변수로 지니고 메서드를 통해 결과를 반환하는 식의 설계가 더 어울린다는 의견이 있었는데 이에 대한
썬의 의견이 궁금합니다!

2024-03-02 12:12 UTC, syoun602 requested changes
안녕하세요 콜리 ~

우선 리뷰가 조금 늦어져서 죄송해요 😭
코드가 한층 더 보기 좋아진 것 같아요 👍🏻 원하신다면 리팩토링을 진행해보고 리뷰 요청주셔도 됩니다 !
질문에 대한 답변은 리뷰에 남겨두었으니 편하게 반영해주세요~

2024-03-02 12:12 UTC, syoun602 commented on README.md
> +1. `인덱스에 의존하는 코드의 한계가 있지 않을까?`
넵 저도 동의하는 바입니다~
인덱스를 사용하면 직접적인 데이터 접근으로 인해 접근하는 객체에 대한 내부 구현에 의존하게 되는데, 이러면 객체지향의 핵심 중 하나인 캡슐화에 위반되죠. 버그 발생 가능성이 높아지기도 하고요.
차라리 객체 간의 상호작용을 활용하는 방식으로 변경해봐도 좋습니다 😊

2024-03-02 12:12 UTC, syoun602 commented on README.md
> +2. `index 원시값 포장`
모든 원시값 포장에 대한 요구사항도 있으니 포장을 해본 뒤, 어떻게 활용해볼 지 고민해보면 좋겠네요 :)

2024-03-02 12:12 UTC, syoun602 commented on README.md
> +3. `LadderGame은 멤버변수로 Ladder, Players, Prizes를 지녀야 할까?`
저도 게임이라면 플레이어, 사다리, 상품을 들고 있도록 구현해볼 것 같아요.
하지만, 설계에 정답이 있는 것은 아니니 내 판단에 대한 근거를 가지고 구현하는게 더 중요하다고 생각합니다~!

2024-03-02 12:12 UTC, syoun602 commented on src/main/java/laddergame/controller/LadderGameController.java
> +        int peopleNumber = people.getPlayerNames().size();
플레이어에 count()나 size()와 같은 메서드를 만들어보는건 어떨까요?

2024-03-02 12:12 UTC, syoun602 commented on src/main/java/laddergame/domain/gameelements/Players.java
> +public class Players {
깔끔한 클래스네요 👍🏻

2024-03-02 12:12 UTC, syoun602 commented on src/main/java/laddergame/domain/gameelements/Players.java
> +    }
`Players.getPlayerNames()`는 이름이 좀 중복되는거 같지 않으신가요~?

2024-03-02 12:12 UTC, syoun602 commented on src/test/java/laddergame/domain/LadderGameTest.java
> +    @MethodSource
method source 활용 👍🏻

2024-03-02 12:12 UTC, syoun602 commented on src/test/java/laddergame/domain/gameelements/PrizesTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
hasMessage와 같은 메서드를 이용해 메시지도 함께 확인해볼 수 있습니다~

2024-03-02 12:12 UTC, syoun602 commented on src/main/java/laddergame/constants/ReservedElementName.java
> +    public static final List<String> reservedNames = new ArrayList<>(List.of("all"));
런타임에 예약어에 대한 설정이 변경된다는 말씀이신가요?? 그게 아니라면,
`names = List.of("", "");` 만 작성해도 될 것 같아서 코멘트 드렸습니다~!

2024-03-02 12:12 UTC, syoun602 commented on src/main/java/laddergame/domain/gameelements/Element.java
> +    public boolean equals(Object obj) {
코멘트를 드린 의도는 `toString()`은 view에서 이용하거나 사용자를 위한 메시지를 정의하기보다는 개발자의 디버깅의 용도로 사용해야 한다 입니다! 아래도 한번 읽어보시면 좋겠네요!
https://stackoverflow.com/questions/4762406/tostring-for-debugging-or-for-humans

2024-03-02 12:12 UTC, syoun602 commented on src/main/java/laddergame/domain/ladder/Ladder.java
> +    public List<Integer> move(int peopleNumber) {
현재 같은 경우라면 `getResult`도 괜찮아보입니다 !
인덱스를 사용하지 않도록 리팩토링 해본다면 더 좋은 이름이 나올 수도 있겠네요 😊

2024-03-02 12:12 UTC, syoun602 commented on src/main/java/laddergame/view/MessageResolver.java
>  public class MessageResolver {
말씀드렸다시피 개인적인 부분이니 편하신 방향으로 설계하셔도 좋습니다. 😊
저라면, 다음과 같은 기준으로 나누진 않았을 것 같네요.
1. 도메인에 대해서만 테스트 코드를 작성한다. (생성 및 주요 비즈니스 로직)
2. UI 요구사항이 변경될 여지가 적다. 따라서 view에 대한 복잡도를 늘리고 싶지 않다.

다만, tdd를 위해 message resolver를 만드는 것은 조금 어색한 감이 있습니다! TDD가 왜 요구사항에 있을까요?
프로그램이 복잡할 수록 도메인을 어떻게 나누어야 할지 더 어렵습니다. 세부적인 구현만 생각하면 생각이 좁아질 수도 있고, 도메인 설계를 잘해 많은 도메인을 구상하더라도 막상 한 번에 구현하려고 하면 머리가 복잡해져 힘들고요. 이때 TDD를 이용한다면 도메인 설계가 아직 미숙하더라도 객체 간의 협력 구조를 명확하게 설계하고 유지할 수 있습니다.

따라서 view를 위해 테스트를 짜기보다는 도메인을 중점으로 TDD를 이용해 객체 간 메세지를 더 잘 이해하고 사용하는게 더 도움이 될 것 같아요.

2024-03-03 17:41 UTC, coli-geonwoo commented on README.md
> +2. `index 원시값 포장`
Position을 통해 index 값을 포장해주었습니다.  그런데 원시값 포장에 대한 장단점 트레이드오프에 대한 판단이 아직 모호한 것 같아요 🤔  리팩터링한 코드에 대한 썬의 의견이 궁금합니다!

제가 생각한 원시값 포장 시의 장단점입니다!

장점
- 더  가독성있는 코드
- 더 안전한 코드 :  index 변동에 따른 잘못된 매핑을 방지할 수 있다는 점
- OOP 스럽다 : 원시값이 아닌 객체간 메시지를 통한 소통에서 협력이라는 문맥이 더 잘 드러난 느낌

단점
 -객체간 의존관계가 많아진 것 같은 느낌 > 객체가 많아지고 서로간의 상호작용이 많아짐

2024-03-03 17:42 UTC, coli-geonwoo commented on src/main/java/laddergame/domain/gameelements/Players.java
> +public class Players {
감사합니당 🥲

2024-03-03 17:42 UTC, coli-geonwoo commented on src/main/java/laddergame/controller/LadderGameController.java
> +        int peopleNumber = people.getPlayerNames().size();
저도 반복되는 코드라 거슬렸는데 메서드화를 하면 더 깔끔히 관리해줄 수 있을 것 같습니다!

2024-03-03 17:43 UTC, coli-geonwoo commented on src/test/java/laddergame/domain/gameelements/PrizesTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
정확한 오류가 발생했는지 확인할 수 있겠네요 👏

2024-03-03 17:43 UTC, coli-geonwoo commented on README.md
> +1. `인덱스에 의존하는 코드의 한계가 있지 않을까?`
많이 부족하지만 시도해보았습니다!!

2024-03-03 17:50 UTC, coli-geonwoo commented on src/main/java/laddergame/view/MessageResolver.java
>  public class MessageResolver {
`TDD를 이용한다면 도메인 설계가 아직 미숙하더라도 객체 간의 협력 구조를 명확하게 설계하고 유지` 이 말씀이 정말 핵심인 것 같아요. TDD를 '검증'이 아닌 '설계'의 방식으로 활용하는 것이 아직 어려운 것 같습니다.

그 어려운 감정을 조금 더 세밀히 들여다보면 이런 것 같아요.

-TDD 구현을 하다보면 in-out 방식으로 접근하는 경우가 많다.
LadderGame이라는 큰 객체부터 테스트를 접근하면 Ladder에 대한 객체와 Player, Prize 등등 다양한 객체 협력자가 필요하다는 것을 떠올린다. 그렇기에 가장 쉬운 Name과 같은 작은 객체부터 접근하게 되는 것 같다. 그러나 협력이라는 문맥에서 자연스레 책임을 분배하고 메시지를 중심으로 객체를 설계하기 위한 TDD가 오히려, 내 머리 속에서는 작은 객체(만만한 객체)부터 상태를 중심으로 정의하려는 경우가 많다.

=> 어떻게 해야 out-in 방식으로 설계가 가능할까

- 주요 로직의 공개여부에 대한 고민
일례로 rowLine의 경우 연결상태를 외부에서 주입하지 않고 연결상태를 private으로 안에서 만들어 주어도 된다. 그러나, 테스트를 위해선 외부에 메시지를 전해줄 수 있어야 한다. 그럼 테스트를 위해서 ConnectionGenerator라는 interface를 만들어준 것은 아닐까? 이 모델에서 generator가 정말 외부에 선언되어야 할 객체일까? 라는 고민이 있었다.

TDD를 건강한 설계방식으로 사용하기 위해서 썬은 어떤 방법을 활용 혹은 어떻게 접근하시나요..?

2024-03-03 17:52 UTC, coli-geonwoo commented on src/main/java/laddergame/domain/ladder/Ladder.java
> +    public List<Integer> move(int peopleNumber) {
리팩토링 과정에서 메서드 시그니처가 void getResult(Players players) 로 바뀌게 되었습니다. players라는 수신자에게 사다리가 전하는 메시지임으로 climb이 적당하다 생각하여 rename해주었습니다.

2024-03-03 17:53 UTC, coli-geonwoo commented on src/main/java/laddergame/domain/gameelements/Element.java
> +    public boolean equals(Object obj) {
아, 제가 코멘트의 의도를 오도했네요 💦  toString()의 용도를 정확히 알고 객체의 책임으로 toString()을 재정의할 때는 많은 고려가 필요하다는 것을 알아갑니다!

2024-03-03 17:57 UTC, coli-geonwoo commented
안녕하세요 썬 😄 

정성스러운 피드백 언제나 감사드립니다! 최근 [객체지향의 사실과 오해]를 읽고 있는데 썬이 해주신 피드백이 제가 생각한 것 이상의 의미들을 담고 있다는 사실을 이해하고 있어요!

객체간 메시지 전달을 통해 협력관계를 구축하도록 index의존 로직들을 아예 들어냈습니다.

2차 개선사안은 다음과 같습니다.
### 2단계 - 2차 리팩터링 개선사안
- gameelements
  - Position : player index 원시값 포장
  - Player
    - 사다리를 타는 책임을 가진 Player 객체 생성
    - 예약어 검증 책임을 Players로부터 이전
  - Prize : 사다리 게임에서 위치와 이름 정보를 가진 Prize 객체 생성
  - Players : List<Player> 일급컬렉션으로 리팩터링
  - Prizes : List<Prize> 일급컬렉션으로 리팩터링


- Ladder : 메소드명 변경(getReusltIndex > climb) 
  - Players가 사다리 연결을 따라 Position을 변경


- LadderGame 
  - Ladder / Players / Prizes 멤버변수 추가
  - 생성자에 복잡한 로직 playGame() 메서드로 분리
  - index 의존 로직을 객체 간 메시지 전달로 리팩터링
  - Player Position과 일치하는 Position을 가진 Prize 매핑
- 불필요한 toString() 삭제
- test 코드 최적화

썬에게 좋은 코드와 와닿길 간절히 기대합니다 😂

2024-03-04 06:12 UTC, kang-hyungu reviewed
콜리, 몇 가지 추가 코멘트 남겼어요
수정해보시고 궁금한 점 있으면 코치 사무실로 찾아오세요.

2024-03-04 06:12 UTC, kang-hyungu commented on src/main/java/laddergame/controller/LadderGameController.java
>  public class LadderGameController {
LadderGameController <== 컨트롤러라 이름 붙인 이유가 무엇인가요?

2024-03-04 06:12 UTC, kang-hyungu commented on src/main/java/laddergame/domain/LadderGame.java
> +        playerGameResult = new LinkedHashMap<>();
일관성을 지킬 것.
this를 붙이세요.

2024-03-04 06:12 UTC, kang-hyungu commented on src/main/java/laddergame/domain/LadderGame.java
> +        if(playerGameResult.isEmpty()){
```suggestion
        if (playerGameResult.isEmpty()) {
```
커밋 전에 린트로 검사하는 습관을 가집시다.

2024-03-04 06:12 UTC, kang-hyungu commented on src/main/java/laddergame/domain/LadderGame.java
> +                .filter(prize -> prize.getPosition().isSame(playerPosition))
```suggestion
                .filter(prize -> prize.isSamePosition(playerPosition)) // 적절한 메서드명으로 바꿀 것
```

객체지향 생활체조
4. 한 줄에 점을 하나만 찍는다.

2024-03-04 06:12 UTC, kang-hyungu commented on src/main/java/laddergame/domain/LadderGame.java
> +        return players.getPlayers()
players 객체에게 이름을 찾아달라고 맡기세요
findPrizeByPosition 메서드도 players 객체 내부에서 처리 가능해보이네요

객체지향 생활체조
9. getter/setter/property를 쓰지 않는다.

2024-03-04 06:12 UTC, kang-hyungu commented on src/main/java/laddergame/domain/gameelements/Name.java
> +            throw new IllegalArgumentException("게임 요소의 이름은 5자 이내의 영숫자로 구성되어야 합니다.");
게임 조건이 바껴서 5를 수정해야 한다면 현재 라인의 텍스트와 6번째 줄의 정규표현식 조건을 수정해야겠네요.
수정할 때 놓치기 쉬울텐데요, 상수로 추출해보면 어떨까요

2024-03-04 06:12 UTC, kang-hyungu commented on src/main/java/laddergame/domain/gameelements/Player.java
> +    private static final Name RESERVED_NAME = new Name("all");
```suggestion
    private static final Name RESERVED_NAME = Name.all();
```

이럴 때 정적 팩터리 메서드를 사용하는걸 추천합니다.
문자열을 객체 외부가 아닌 내부에서 관리해야 수정 범위를 줄일 수 있어요

2024-03-04 06:12 UTC, kang-hyungu commented on src/main/java/laddergame/domain/gameelements/Players.java
> +            throw new IllegalArgumentException("게임 참여자의 수는 1이상 100이하만 가능합니다.");
문자열의 숫자도 변경 대상입니다.

2024-03-04 06:12 UTC, kang-hyungu commented on src/main/java/laddergame/domain/gameelements/Position.java
> +    public int left() {
left라고 쓰니까 혼란스럽네요. 왼쪽으로 이동하는걸 뜻하는줄 알았는데 좌표를 반환하네요.
leftPosition 같이 좀더 의미를 주는게 어떨까요?

2024-03-04 06:12 UTC, kang-hyungu commented on src/main/java/laddergame/domain/ladder/Connection.java
>      NOTCONNECTED(false);
```suggestion
    NOT_CONNECTED(false);
```

2024-03-04 11:36 UTC, coli-geonwoo commented on src/main/java/laddergame/controller/LadderGameController.java
>  public class LadderGameController {
MVC 패턴에서 domain 객체들과 view를 연결해주는 역할을 하고 있기 때문입니다. 그러나, 이번 미션에서 controller의 역할이 필수적인지에 대해서는 조금 의문이 들었던 것은 사실이에요. 게임에 대한 흐름이 단편화되어 있어 단순히 domain과 view를 연결해주는 기능 너머의 게임 흐름을 '제어'하는 역할로서 controller가 존재하지는 않는다는 느낌을 받았습니다 🤔  

그럼에도 controller 객체를 놔둔 이유는 "줄을 한 줄 더 추가해줘", "사다리를 다시 만들어줘" 처럼 게임의 제어가 필요한 기능의 확장 가능성이 있다고 생각했어요! 

정리하자면, 현재 LadderGameController에서는 domain과 view를 잇는 역할 이상을 담당하지 않기에 Main에서 모아주어도 충분하다고 생각했으나, 충분히 controller에 부합하는 기능에 대한 확장이 가능하다고 생각하여 controller 객체를 만들어주었습니다 😄

2024-03-04 11:36 UTC, coli-geonwoo commented on src/main/java/laddergame/domain/LadderGame.java
> +        if(playerGameResult.isEmpty()){
컨벤션과 관련된 반복적인 피드백.. 많이 신경쓰겠습니다🥲

2024-03-04 11:38 UTC, coli-geonwoo commented on src/main/java/laddergame/domain/LadderGame.java
> +        return players.getPlayers()
이 피드백이 많은 도움이 되었습니다. Prizes와 Players 일급컬렉션에서 탐색에 대한 책임을 모두 이전하니 LadderGame 객체가 수행하는 역할이 훨씬 명확해진 느낌이에요!

2024-03-04 11:38 UTC, coli-geonwoo commented on src/main/java/laddergame/domain/gameelements/Name.java
> +            throw new IllegalArgumentException("게임 요소의 이름은 5자 이내의 영숫자로 구성되어야 합니다.");
ELEMENT_NAME_RULE이라는 하나의 덩어리로 이름 명명규칙을 관리하다보니 길이 + 영숫자 규칙이 하나로 뭉친 느낌이네요! 따로 분리하여 상수화해주겠습니다!!

2024-03-04 11:39 UTC, coli-geonwoo commented on src/main/java/laddergame/domain/gameelements/Player.java
> +    private static final Name RESERVED_NAME = new Name("all");
반영해주었습니다!!

2024-03-04 11:40 UTC, coli-geonwoo commented on src/main/java/laddergame/domain/gameelements/Position.java
> +    public int left() {
Position.left()에서 position이 자명하게 드러나리라 생각했는데 움직인다는 의미로 충분히 오해할 수 있겠네요! 더 명확한 의미전달이 가능한 메서드명인 것 같습니다!!

2024-03-04 13:17 UTC, syoun602 requested changes
안녕하세요 콜리~

말씀하신대로 인덱스를 최대한 사용하지 않는 코드로 리팩토링하고 나니 
구조적으로도 그렇고 훨씬 코드가 단조롭고 이해하기 좋네요 💯
구구가 말씀하신 것도 잘 반영하셨습니다 👍

다만 테스트가 부족합니다 😢 구현할때 뿐만 아니라 리팩토링 시에도 테스트를 작성해주세요!
Position 움직임과 같은 부분은 주요 비즈니스 로직일 것 같아요. 또한, 커밋 전에 테스트 코드를
한번씩 돌려주는 습관을 들인다면 지금과 같이 로직이 정상 동작하지 않는 상황을 사전에 방지할 수 있습니다. 
현재 동작하지 않는 로직들이 있는데 전체적으로 한번 확인해주세요~!

2024-03-04 13:17 UTC, syoun602 commented on src/main/java/laddergame/controller/LadderGameController.java
> +    private static boolean printPlayerResults(LadderGame ladderGame) {
`print`라는 메서드명이 boolean을 반환할거라고 예측하기는 힘들 것 같아요 😢

2024-03-04 13:17 UTC, syoun602 commented on src/main/java/laddergame/domain/LadderGame.java
> +
불필요한 공백으로 보입니다~!

2024-03-04 13:17 UTC, syoun602 commented on src/main/java/laddergame/domain/LadderGame.java
> +        ladder.climb(players);
👍

2024-03-04 13:17 UTC, syoun602 commented on src/main/java/laddergame/domain/ladder/RowLine.java
> +        if (checkLeftPosition(playerPosition.leftPosition())) {
check는 void 메서드일 것 같은데, 차라리 `shouldMoveLeft()`나 `canMoveLeft()`와 같이 boolean 반환을 명시해줍시다

2024-03-04 13:17 UTC, syoun602 commented on src/main/java/laddergame/domain/gameelements/Name.java
> +    private static final String ELEMENT_NAME_RULE = "[ㄱ-ㅎ가-힣a-zA-Z0-9]";
[2e9f9b8](https://github.com/woowacourse/java-ladder/pull/364/commits/2e9f9b875935b3ba194bd3c67990f50e461cdcb2)
이 커밋 이후로 이름 검증이 제대로 동작하지 않는 것 같아요 👀

2024-03-04 13:17 UTC, syoun602 commented on src/test/java/laddergame/domain/gameelements/PlayerTest.java
> +        assertEquals(testPlayer2.getPlayerPosition(), expectedPosition2);
특별히 assertThat과 assertEquals를 섞어서 쓰시는 기준이 있으신가요?
또한, 현재와 같이 두가지 이상의 assert문이 있다면 assertAll을 이용해주세요 😊

+) position에 equals 재정의가 되어 있지 않는데, 테스트가 통과할까요?

2024-03-04 13:17 UTC, syoun602 commented on src/main/java/laddergame/domain/gameelements/Prizes.java
> +                .filter(prize -> prize.getPosition().isSame(playerPosition))
position 비교에 대한 검증도 prize에게 넘겨볼 수 있겠네요
```suggestion
                .filter(prize -> prize.isSamePosition(playerPosition))
```

2024-03-04 13:17 UTC, syoun602 commented on src/main/java/laddergame/domain/gameelements/Players.java
> +                .filter(player -> player.getName().equals(playerName))
여기도 비교에 대한 책임을 player에게 넘겨봅시다

2024-03-04 13:17 UTC, syoun602 commented on src/main/java/laddergame/domain/gameelements/Players.java
> +                .findFirst()
굳이 첫번째 요소를 반환할 필요가 없다면 `findAny`를 사용해보는건 어떨까요?
findAny와 findFirst의 차이에 대해 한번 알아봅시다~

2024-03-04 13:17 UTC, syoun602 commented on README.md
> +2. `index 원시값 포장`
말씀하신대로라면 원시값을 포장하는 의미가 충분하지 않나요? 🤔
객체간 상호작용이 많아졌다면 그만큼 SRP, OCP를 잘 지키고 있다는 것 같아요.

2024-03-04 13:17 UTC, syoun602 commented on src/main/java/laddergame/view/MessageResolver.java
>  public class MessageResolver {
처음부터 너무 완벽한 설계를 하는 것에 매몰되지 않고 말씀하신 방식 두가지를 적절하게 이용해봅시다 😊
저도 어느정도 가닥이 잡히면 top down으로 작성을 하다가도 생각이 나지 않는다면 가장 작은 객체부터 만듭니다.
말씀하신대로 interface를 굳이 만들 필요가 없을 수도 있겠지만, 중요한 것은 코드 신뢰도를 높이기 위한 testable한 코드를 작성하는 것이라고 생각합니다.

2024-03-04 17:17 UTC, coli-geonwoo commented on src/main/java/laddergame/domain/gameelements/Players.java
> +                .findFirst()
findFirst는 순차적으로 값을 탐색하여 시간적인 비용이 많이 들지만 findAny는 Predicate에 일치하는 값을 무작위로 반환하는 군요! findAny가 더 효율적일 것 같아요 😶

2024-03-04 17:18 UTC, coli-geonwoo commented on src/main/java/laddergame/domain/gameelements/Prizes.java
> +                .filter(prize -> prize.getPosition().isSame(playerPosition))
비교 책임 이전에 대한 반영이 안되어 있었네요!! 옮기니 훨씬 깔끔해지고 객체간 역할 분배도 더 명확해진 것 같습니다!

2024-03-04 17:20 UTC, coli-geonwoo commented on src/test/java/laddergame/domain/gameelements/PlayerTest.java
> +        assertEquals(testPlayer2.getPlayerPosition(), expectedPosition2);
Position에 isSame 메서드를 만들면서 중복되는 기능인 equals를 삭제해주는 리팩터링이 있었는데 그 과정에서 테스트가 깨졌네요.. TDD를 초기 구현과정에서만 적극적으로 활용했는데 리팩터링 과정에서도 의식적으로 계속 염두해두겠습니다!!

2024-03-04 17:20 UTC, coli-geonwoo commented on src/main/java/laddergame/domain/gameelements/Name.java
> +    private static final String ELEMENT_NAME_RULE = "[ㄱ-ㅎ가-힣a-zA-Z0-9]";
서로 다른 오류 메시지를 던지도록 메서드를 분리하다보니 hasMessage에서 불통을 받은 것 같습니다 😢

2024-03-04 17:20 UTC, coli-geonwoo commented on src/main/java/laddergame/domain/ladder/RowLine.java
> +        if (checkLeftPosition(playerPosition.leftPosition())) {
더 예측가능한 메서드명이네요!

2024-03-04 17:21 UTC, coli-geonwoo commented on src/main/java/laddergame/controller/LadderGameController.java
> +    private static boolean printPlayerResults(LadderGame ladderGame) {
retryUnitlNoError 가 Supplier를 받다보니 억지로 반환값을 넣으려 한 것 같아요! 예측가능한 메서드로 리팩터링 해주었습니다!!

2024-03-04 17:34 UTC, coli-geonwoo commented
안녕하세요 썬 😄 

우선 test나 메인로직에 대한 사전검증 없이 pr 드린 것에 대해 죄송하다는 말씀 드립니다. 😭  그럼에도 어제의 제 상황을 말씀드리자면 index를 걷어내는 과정에서 거의 모든 로직을 밀어내고 리팩터링하는 과정에서 TDD 원칙을 잘 지켜내지 못했던 것 같습니다.. 어쩌면 객체의 내부구현을 메시지 안에 담으면서 스스로 지게된 책임이기도 하네요 😓  TDD 원칙을 지키면서 초기 구현 과정 이후에도 리팩터링까지 순간마다 테스트를 "의식"하며 제 컴포트존을 벗어나려 많이 노력해보겠습니다 

많이 부족한 코드에도 매번 꼼꼼히 검토해주심에 너무나 감사드립니다.

2단계 3차 리팩터링 개선사안은 다음과 같습니다!

### 2단계 - 3차 리팩터링 개선사안
- RowLine : 예측가능한 메서드명으로 rename(checkRightPosition > canMoveRightPosition)
- LadderController : printPlayerResult를 예측가능한 메서드 getPlayerName으로 변경
- Prize : Position을 통한 비교검증 책임 이전 (Prizes > Prize)
- Player : 이름을 통한 비교검증 책임 이전 (Players > Player)
- test : 전반적인 오류 fix
- test : assertAll로 복수검증 감싸기

2024-03-06 04:06 UTC, syoun602 approved these changes
안녕하세요 콜리~

사다리 게임 구현하시느라 수고 많으셨습니다! 
전체적으로 크게 리팩토링을 하게 되면 놓치게 되는 것들도 있고
멘탈이 흔들리는 순간들이 어쩔 수 없이 있는 것 같아요 😭
그럼에도 불구하고 더 좋은 코드를 작성하기 위해 리팩토링을 진행한 점이
인상 깊었습니다. 💯 잘 구현해주시기도 했구요!

콜리와 이런 저런 얘기를 해볼 수 있어서 재밌었습니다.
이번 미션은 여기서 마무리하고 머지하겠습니다~
사다리 게임에서 얻어가신 것을 잘 습득해서 추후 미션에서도 의식적인 연습을 해보시죠!

2024-03-06 04:06 UTC, merged