[2단계 - 사다리 게임] 카고(정민호) 미션 제출합니다.
woowacourse/java-ladder pull request #367
Opened 2024-02-28 09:54 UTC by devhoya97

파랑 안녕하세요 :)

이번에 미션을 구현하면서 들었던 고민들을 공유드리겠습니다!!

### 정적 팩토리 메서드?
Players는 정적 팩토리 메서드를 스스로 갖고 있도록 설계했는데, Ladder와 Floor는 각각 정적 팩토리 메서드를 수행해주는 Factory 클래스를 만들어보았습니다. 그 이유는 다음과 같습니다.
  - Ladder와 Floor의 핵심 역할은 사다리 타기를 시작할 위치를 매개변수로 받아 결과 위치를 반환하는 것이라 생각해요. 그런데 Ladder와 Floor는 객체 생성을 위해 전략을 알아야 합니다. 전략을 바탕으로 객체를 생성하는 것은 비교적 복잡하다고 느껴서 객체를 생성하는데 집중한 나머지 핵심 역할이 퇴색된다고 느껴져서 Factory 클래스로 분리했습니다.
  - 반면 Players는 생성에 전략이 필요없으므로 Factory 클래스를 따로 두지 않았어요.
  - 정적 팩토리 메서드에 대해 처음 써봐서, 위 방향이 파랑 입장에서 합리적으로 보이는지 궁금해요!

### GameResult 레코드의 사용  
view에게 `이름 - 결과` 를 전달하기 위해 Map을 쓸까 GameResult와 같은 객체를 만들까 고민했는데, 개인적으로 iteration을 돌 때 List가 편하다고 생각해서 GameResult라는 객체를 만들고, List<GameResult>를 전달하도록 했어요. 그러다보니 또 List<GameResult>를 멤버 변수로 갖는 GameResults 객체를 만들어야하나? 고민도 됐어요. 파랑은 어떤 방향성이 더 합리적으로 보이나요 ?!

### 객체지향과 클린코드
이번 미션을 구현하고, 리팩토링하면서 `객체지향 프로그래밍, 읽기 좋은 코드, 유지보수하기 좋은 코드, 테스트하기 좋은 코드`라는 관점에서 코드를 개선하는 것에 초점을 두었는데, 위 관점들에서 파랑이 제 코드를 보았을 때 부족한 부분이 어디인지 궁금해요!
 
부족한 부분 마구마구 지적 해주세요! 감사합니닷 :)

2024-02-28 17:33 UTC, summerlunaa requested changes
카고 안녕하세요! 파랑입니다 🐳

2단계도 열심히 구현해주셨군요 👍  리뷰 남겼으니 확인부탁드립니다~~

2024-02-28 17:33 UTC, summerlunaa commented on src/main/java/domain/LadderGame.java
> +    public List<GameResult> matchResult(final String playerName, final String selectAll) {
전체를 선택했는지 알기위해 playerName과 selectAll이 같은지 비교하는 건 조금 어색하네요.
차라리 selectAll을 boolean으로 받는 게 더 직관적일 것 같아요.

2024-02-28 17:33 UTC, summerlunaa commented on src/main/java/domain/MatchingItems.java
> +    private List<String> items;
```suggestion
    private final List<String> items;
```

2024-02-28 17:33 UTC, summerlunaa commented on src/main/java/domain/MatchingItems.java
> +    }
MatchingItems에서 playerCount를 함께 받는 게 저는 조금 어색해보이는데요, 사실상 playerCount에 items 개수에 맞춰 값을 넣으면 실제 참여자 수와 상관 없이 쉽게 객체 생성이 가능해서요🤔 players와 items를 함께 갖고 있는 곳에서 두 개가 같은지 검증해주는 건 어떨까요?

2024-02-28 17:33 UTC, summerlunaa commented on src/main/java/domain/ladder/Floor.java
> +    private final List<Bridge> bridges;
이름이 Bridges에서 Floor로 바뀌었군요! 층이라는 의미인가요?

2024-02-28 17:33 UTC, summerlunaa commented on src/main/java/domain/ladder/Floor.java
> +    }
호오.. 이해하기 쉽지 않았습니다. 로직을 지금보다 훨씬 간단하게 만들 수 있을 것 같아요. 

힌트) 
왼쪽으로 갈 수 있나요? true -> return startPosition - 1
오른쪽으로 갈 수 있나요? true -> return startPosition + 1
둘다 아니면 -> return startPosition

2024-02-28 17:33 UTC, summerlunaa commented on src/main/java/domain/ladder/Floor.java
> +    }
추가로 moveFrom 메서드를 호출하면 다음 위치가 나오는데 메서드명만 봐서는 그 기능이 잘 연상되지 않네요. `move`라는 단어가 실제로 객체의 위치를 움직인다는 느낌을 주는 것 같아요. 실제로는 다음 위치만 찾아주는데 말이죠. 어떻게 생각하세요?

2024-02-28 17:33 UTC, summerlunaa commented on src/main/java/domain/ladder/FloorFactory.java
> +public class FloorFactory {
> Ladder와 Floor의 핵심 역할은 사다리 타기를 시작할 위치를 매개변수로 받아 결과 위치를 반환하는 것이라 생각해요. 그런데 Ladder와 Floor는 객체 생성을 위해 전략을 알아야 합니다. 전략을 바탕으로 객체를 생성하는 것은 비교적 복잡하다고 느껴서 객체를 생성하는데 집중한 나머지 핵심 역할이 퇴색된다고 느껴져서 Factory 클래스로 분리했습니다.

이런 기준을 가지고 Factory 클래스를 분리하셨군요! Bridge 생성 같은 복잡한 로직이 있는 경우에는 이렇게 분리하는 것도 좋은 방법이라 생각합니다. 특히나 카고의 설명처럼 전략까지 사용하는 경우라면 더더욱이요. 하지만 이렇게 Factory 클래스를 분리했을 때의 단점도 생각해보셨을까요? 👀

2024-02-28 17:33 UTC, summerlunaa commented on src/main/java/domain/ladder/Height.java
> +package domain.ladder;
패키지를 나눠주셔서 도메인을 한 눈에 보기 좋네요 👍

2024-02-28 17:33 UTC, summerlunaa commented on src/main/java/domain/GameResult.java
> +public record GameResult(String name, String matchingItem) {
원시값을 포장해보는 건 어떨까요?

2024-02-28 17:33 UTC, summerlunaa commented on src/main/java/domain/ladder/Width.java
> +    }
Width 객체를 생성하려면 반드시 Players까지 만들어야겠네요 🤔

2024-02-28 17:33 UTC, summerlunaa commented on src/main/java/domain/player/Player.java
> +    private Position position;
Player가 position을 들고 있게 만든 이유가 궁금합니다!

2024-02-28 17:33 UTC, summerlunaa commented on src/main/java/domain/player/Position.java
> +    }
오호 값이 변할 때마다 새로운 객체를 생성하는 방법으로 불변하게 만드셨군요

2024-02-28 17:33 UTC, summerlunaa commented on src/main/java/domain/LadderGame.java
> +    private final Ladder ladder;
> view에게 이름 - 결과 를 전달하기 위해 Map을 쓸까 GameResult와 같은 객체를 만들까 고민했는데, 개인적으로 iteration을 돌 때 List가 편하다고 생각해서 GameResult라는 객체를 만들고, List를 전달하도록 했어요. 그러다보니 또 List를 멤버 변수로 갖는 GameResults 객체를 만들어야하나? 고민도 됐어요. 파랑은 어떤 방향성이 더 합리적으로 보이나요 ?!

대체 어디까지 객체를 만들어야 하나 참 고민되는 포인트죵ㅎㅎ 사람마다 기준이 다를 수 있어서 어려운 것 같아요.
저는 개인적으로 원시값이 그냥 돌아다니는 게 꼴 뵈기 싫더라구요(?) 이 값이 어떤걸 뜻하는지 확실히 알기도 어렵고 의도하지 않은 값이 들어갈까봐 불안한 마음도 들구요. 그래서 저라면 이름, 결과를 값객체로 포장하고 Map을 사용할 것 같은데요...! 
카고는 어떤가요? 답이 있는 부분은 아니니 의견 나눠보면 좋을 것 같아요ㅎㅎ.

2024-02-28 17:33 UTC, summerlunaa commented on src/main/java/domain/player/Players.java
> +    public static Players createInOrderPoisition(final List<String> names) {
오타가 👀

2024-02-28 17:33 UTC, summerlunaa commented on src/main/java/domain/player/Players.java
> +        }
우선 참가자의 이름이 겹치면 안 된다는 조건이 없더라구요. 참자가의 이름을 중복으로 넣고 조회하면 어떻게 되는지 테스트 해볼까요?

2024-02-28 17:33 UTC, summerlunaa commented on src/test/java/domain/LadderGameTest.java
> +        final List<Player> rawPlayers = players.getPlayers();
여기가 when 아닐까요!?

2024-02-28 17:33 UTC, summerlunaa commented on src/test/java/domain/LadderGameTest.java
> +        final List<GameResult> gameResults = ladderGame.matchResult("all", "all");
개인별 결과가 아니라 전체 결과에 대한 테스트 아닌가요?

2024-02-28 17:33 UTC, summerlunaa commented on src/test/java/domain/player/PlayerTest.java
> +    @DisplayName("참가자 이름이 1글자 이상 5글자 이하이면 참가자 객체가 잘 생성된다..")
생성된다.. 아련하네요.. ⭐️

2024-02-28 17:33 UTC, summerlunaa commented on src/test/java/domain/player/PlayerTest.java
> +    void invalidNameLength() {
실수로 TDD 사이클을 지키지 못하셨군요ㅋㅋㅋㅋㅋ 실수로 복붙도 하신 것 같습니다..

2024-02-29 06:54 UTC, devhoya97 commented on src/main/java/domain/LadderGame.java
> +    public List<GameResult> matchResult(final String playerName, final String selectAll) {
그렇네요..!
domain 객체가 "all"이라는 입력이 들어왔는지 판단하는게 좀 이상하게 느껴져서 Main 메서드(컨트롤러 역할)에서 판단하도록 변경했어요.
그렇게 Main 메서드가 "all"이 들어왔는지 아닌지를 이미 판단했으니, LadderGame에게 boolean을 넘겨줄 필요 없이, 개인별 결과를 가져오는 메서드와 전체 결과를 가져오는 메서드를 분리해봤어요! 
같은 맥락으로 OutputView의 메서드들도 개인별 결과를 출력하는 메서드와 전체 결과를 출력하는 메서드를 분리했고, Main 메서드에서 선택적으로 호출하다보니 domain과 view의 부담을 줄일 수 있었습니다!

2024-02-29 06:58 UTC, devhoya97 commented on src/main/java/domain/MatchingItems.java
> +    private List<String> items;
왜 혼자볼 땐 놓치는 걸까요 ㅠㅠ 감사합니다!!

2024-02-29 07:22 UTC, devhoya97 commented on src/main/java/domain/MatchingItems.java
> +    }
파랑의 의견에 동의해서 코드를 리팩토링했습니다!

그런데 아래와 같은 문제가 생겼어요!
<img width="610" alt="image" src="https://github.com/woowacourse/java-ladder/assets/146502065/8e082a9c-3ca0-44fe-9ac2-6290566cb7ad">
제가 의도했던 것은 실행 결과를 입력하자마자 문제가 있다는 걸 파악할 수 있으니 최대 사다리 높이를 받기 전에 오류 메시지를 출력해주고 싶었어요. 그런데 제 설계상 LadderGame은 사다리까지 만든 후에야 객체를 생성하기 때문에 사다리 높이까지 받아야만 오류가 발생한 시점을 파악할 수 있습니다...!

참가자와 실행 결과만으로 LadderGame을 먼저 생성해두고, Ladder는 LadderGame의 `play()`메서드를 호출할 때 매개변수로 넘겨주면 해결할 수 있을 것 같은데 좋은 방법이 맞을까요?! 생각해보니 이렇게하면 LadderGame이 Ladder를 굳이 멤버변수로 들고있지 않아도 되는 장점도 있어보이구요.

아니면 이전 리뷰에서 논의했던 맥락과 유사하게, MatchingItems를 생성할 때 이미 검증이 완료된 Player 객체를 넘겨주는 방법도 있을 것 같아요. 그런데 이 방법은 `MatchingItems에서 playerCount를 함께 받는 게 저는 조금 어색해보이는데요, ` 라는 의문을 해결할 순 없을 것 같기도 하구요.

파랑의 생각이 궁금해요 !!

2024-02-29 07:29 UTC, devhoya97 commented on src/main/java/domain/ladder/Floor.java
> +    private final List<Bridge> bridges;
맞습니다! 사다리를 다루려고 하는데 Bridges라는 이름이 Players의 위치를 1번 이동시키는 역할을 하는지(즉 사다리 한 층의 역할), 여러번 이동시키는 역할을 하는지 제가 코딩하면서도 자꾸 헷갈리더라구요. 

사다리는 높이에 해당하는 만큼의 층 수를 가지고 있다! 라고 생각하니 헷갈리지 않아서 Floor라는 네이밍을 사용했어요. 어떤가요 ?!

2024-02-29 08:14 UTC, devhoya97 commented on src/main/java/domain/ladder/Floor.java
> +    }
그렇네요 ㅎㅎ.. 포지션이 범위를 넘어서는 값을 갖지 않는 것에 집중하다보니 오히려 코드가 복잡해졌네요. 파랑이 준 힌트대로 리팩토링해보았습니다..! 

> 추가로 moveFrom 메서드를 호출하면 다음 위치가 나오는데 메서드명만 봐서는 그 기능이 잘 연상되지 않네요. move라는 단어가 실제로 객체의 위치를 움직인다는 느낌을 주는 것 같아요.

위 의견에도 동의합니다! 위 메서드를 호출하려는 대상에게 `메서드의 반환값을 보고 알아서 원하는 동작을 처리해라` 라는 의도를 전달하기 위해선 더 적절한 메서드명이 필요할 것 같아요.

`calculateResultPosition` 라는 이름으로 변경하였습니다 ..!

2024-02-29 08:24 UTC, devhoya97 commented on src/main/java/domain/ladder/FloorFactory.java
> +public class FloorFactory {
음 .. 코딩할 당시 단점까지는 생각해보지 못했던 것 같아요.

지금 곰곰이 생각해보면 아래와 같은 단점들이 있을 것 같아요. 혹시 더 핵심적인 단점이 있을까요?
- 클래스 파일을 따로 둬서 파일을 추가적으로 열어봐야 한다.
- 유지보수가 필요한 지점이 한 곳에서 두 곳으로 나뉜다.
- 객체를 필요로하는 입장에서, 두 클래스에 의존성이 생긴다.

2024-02-29 09:58 UTC, devhoya97 commented on src/main/java/domain/player/Player.java
> +    private Position position;
사다리 전체를 타기 위해선 `사다리의 한 층`을 타는 행위를 여러번 반복해야 한다는 점이 이번 미션의 핵심이라고 이해했습니다.

`Player`는 입력된 순서대로 초기 `Position`을 가지며,
`사다리의 한 층`을 탈 때마다 `Player`의 `Position`은 변화할 수 있습니다.

따라서 `Player`가 `Position` 객체를 들고 있으면 N층으로 구성된 사다리를 탈지라도
한 층을 탈 때마다 `Position`값을 변경해줌으로써 (N-1)층의 사다리를 타는 문제로 바꿀 수 있고, 
이를 반복하면 되므로 `사다리 타기`라는 큰 문제를 `한 층 타기`라는 작은 문제로 만들 수 있다고 생각했습니다!

2024-02-29 10:04 UTC, devhoya97 commented on src/main/java/domain/player/Position.java
> +    }
넵! 네오가 공부 자료로 나눠준 공부 자료중에 `실수를 피할 수 있는 코드` 라는 파트에 값이 변할 때마다 새로운 객체를 생성하는 방법이 있었는데요.

외부에서 Position 객체를 생성한 뒤 그 객체를 활용해 사다리 타기를 진행했다면, 외부에서 Position 객체의 참조를 아직 가지고 있어서 Position 값을 변경시킬 때 의도치 않은 오류가 발생할 수 있다고 생각했습니다.

근데 설계하다보니 위 메서드들은 테스트코드에서만 사용하고 있어서... 삭제할 듯 싶습니다 ㅎㅎ;

2024-03-01 16:53 UTC, devhoya97 commented on src/main/java/domain/GameResult.java
> +public record GameResult(String name, String matchingItem) {
이 부분에 대해서 고민하고 개선하는 데에만 5시간정도 쓴 것 같습니다 ㅎㅎ...
(우선 미션 예시에서 사용하는 `실행 결과`와 제가 이름 붙여준 `MatchingItem`이라는 이름이 자꾸 헷갈려서 Result라는 이름으로 변경했습니다!)

우선 원시값 포장과 일급 컬렉션의 관계를 view와 연결지어서 많이 고민했어요. 이전에 파랑이 조언해줬던 `검증된 매개변수 타입 사용`과 연관지어 내려본 결론은 다음과 같습니다.
- view는 `List<String> names`가 아니라 `Names names`와 같은 일급 컬렉션을 매개변수로 받아야 한다.
  - 왜냐하면 `List<String> names`를 매개변수로 받았을 때, Name 객체로 인정받지 못한 엉뚱한 `String타입 원시값`이 매개변수로 넘어와도 view는 이 사실을 알 수 없기 때문이다.
  - 따라서 실수를 방지할 수 없는 코드가 된다.
  - 좋은 코드는 실수를 방지하기 위해 어느정도 제약이 있는 코드이다. 
  - 따라서 view는 검증된 일급컬렉션이나 포장된 객체를 매개변수로 받아야 한다.

- 하지만 view는 결국 출력을 위해 `List<String>`의 형태를 필요로 한다.
  - 따라서 view에게 넘겨줄 일급컬렉션은 자신이 멤버변수로 가지고 있는 (예를 들어)`List<Name>`을 `List<String>`으로 변환하여 반환해주는 메서드를 갖추어야 한다.

위와 같이 생각을 정리하고, Name과 Result를 record 타입으로 포장했어요. 그리고 Names와 Results라는 일급컬렉션을 만드려고 하는데 문제가 발생했습니다.

기존 제 코드에서는 Player가 Name과 Position을 갖고, `List<Player>`를 갖는 Players라는 일급컬렉션이 존재했어요. 이 구조에서는 Names라는 일급컬렉션을 따로 만들어 관리하기보다는 Players가 참가자 이름에 대한 `List<String>`을 만들어줄 책임이 있어보였는데, 그렇게 구현해버리면 제가 내린 결론 상 참가자의 이름을 출력하기 위해 view에게 Players 객체를 넘겨줘야하는 상황이 되어버렸어요. 하지만 Players는 Player의 Position을 변경할 수 있는 메서드를 갖고 있기에 그러고 싶지 않았습니다.

이 부분에서 정말 많이 고민했는데, 제가 내린 결론은 `Players가 두 개의 멤버변수를 가지므로 일급컬렉션이 아니기 때문에 문제가 발생한 것이다.` + `객체는 가능하면 멤버변수를 하나만 가지고 있는 것이 좋으며, 이를 List로 다루고 싶으면 일급컬렉션으로 다루는 것이 좋다.` 였어요.

그렇게 두 개의 멤버변수를 갖는 Player 객체는 날려버리고 PlayerName이라는 객체로 새출발하기 위한 대공사에 들어갔고, 이 대공사는 TDD를 지키지 못했답니다 ㅎㅎ... 최대한 객체가 하나의 멤버변수만 갖도록 리팩토링하다보니 Name과 Position을 함께 갖는 객체는 필요하지 않더라구요. 

공사를 끝마치고 또 아래와 같은 생각이 들었습니다.
- PlayerNames, Results, GameResults 라는 일급컬렉션을 view에게 안심하고 넘길 수 있었던 이유는 일급컬렉션이 포장하고 있는 객체가 불변객체이기 때문이다.
- 불변객체가 아닌 객체를 포장하는 일급컬렉션은 view에게 전달할 수 없다.
  - 아직 DTO에 대해선 들어보기만 했고 써본적도 없지만, 이 때 필요한 것이 DTO일 것이다.

제가 생각한 흐름에 혹시 이상한 점이 있을까요? 이 글을 보고 조언해주고 싶은 내용이 있다면, 조언 부탁드립니다!!!

2024-03-01 17:12 UTC, devhoya97 commented on src/main/java/domain/ladder/Width.java
> +    }
맞아요. 현재 개선한 구조상으로는 `PlayerNames`를 만들어야만 `Width` 객체를 생성할 수 있어요.

여기서 Width는 ladder 패키지에 속한 것으로 알 수 있듯이 오직 사다리의 너비를 위한 객체에요. 그리고 사다리의 너비는 참가자가 몇 명인지 알기 전까지는 정할 수 없다고 생각했어요.

그래서 흐름상 `PlayerNames 객체 생성 -> Width 객체 생성` + `Height 객체 생성` 을 거쳐야만 `Ladder 객체 생성` 단계에 오는 것이 자연스럽다고 생각했고, Width 객체 생성을 위해 PlayerNames가 꼭 필요한 것은 오히려 프로그램에게 적절한 제약을 걸어주는 역할을 한다고 생각했어요!

혹시 파랑의 의견은 어떤가요?!

2024-03-01 17:16 UTC, devhoya97 commented on src/main/java/domain/player/Player.java
> +    private Position position;
답변을 단 순서가 조금 뒤죽박죽이라 죄송해요 ㅎㅎ.. 처음엔 위와 같이 생각했지만 결과적으로는 Player 객체와 Position 객체는 사라졌답니당

2024-03-01 17:21 UTC, devhoya97 commented on src/main/java/domain/LadderGame.java
> +    private final Ladder ladder;
저는 위에 있는 코멘트들을 반영하는 리팩토링을 진행하면서, 결국 `List<GameResult>`를 관리하는 `GameResults` 객체를 만들긴 했어요!

그런데 파랑의 의견을 듣고나니 Map을 사용하면 저처럼 두 개의 객체를 만들 필요 없이 하나의 객체만으로도 구현이 가능할 것 같네요! 다음 미션에서는 같은 상황이 왔을 때 Map을 한 번 사용해봐야겠어요!!

2024-03-01 17:23 UTC, devhoya97 commented on src/main/java/domain/player/Players.java
> +    public static Players createInOrderPoisition(final List<String> names) {
분명 조심한다고 했는데 ㅎㅎㅎㅎ.. 앞으로 제출 전에 더 꼼꼼하게 살펴봐야겠어요 !

2024-03-01 17:30 UTC, devhoya97 commented on src/main/java/domain/player/Players.java
> +        }
그렇네요.

참가자의 이름으로 개별 결과를 확인해주는 기능이 요구사항에 있는데, 이름이 중복되면 이 요구사항을 만족하기가 쉽지 않으므로 참가자의 이름이 겹치면 안된다는 조건을 추가하는게 합리적인 것 같아요! 

위 기능 추가해보았습니당

2024-03-01 17:33 UTC, devhoya97 commented on src/test/java/domain/LadderGameTest.java
> +        final List<Player> rawPlayers = players.getPlayers();
헉 리팩토링을 막 하다보니 테스트코드에서 실수가 엄청 많았네요..!

다음부터 리팩토링이 끝나면 영향받았던 테스트코드를 Push하기 전에 쭉 검토해봐야겠어요.
잔실수 줄이겠습니다!!🥹

2024-03-01 17:34 UTC, devhoya97 commented on src/test/java/domain/LadderGameTest.java
> +        final List<GameResult> gameResults = ladderGame.matchResult("all", "all");
요기두... 잔실수 줄이겠습니닷..! 🙇‍♂️

2024-03-01 17:49 UTC, devhoya97 commented on src/test/java/domain/player/PlayerTest.java
> +    @DisplayName("참가자 이름이 1글자 이상 5글자 이하이면 참가자 객체가 잘 생성된다..")
ㅋㅋㅋㅋㅋㅋ웃픈 실수입니다😅

2024-03-01 17:49 UTC, devhoya97 commented on src/test/java/domain/player/PlayerTest.java
> +    void invalidNameLength() {
ㅠㅠㅠ맞습니다 복붙해놓고 급하게 제출해버렸네요 흑
개선하겠습니다!!

2024-03-02 11:34 UTC, summerlunaa commented on src/main/java/domain/ladder/Floor.java
> +    private final List<Bridge> bridges;
Bridges라는 이름보다는 직관적이고 의미를 잘 나타내는 이름인 것 같아요 👍

2024-03-02 11:39 UTC, summerlunaa commented on src/main/java/domain/ladder/FloorFactory.java
> +public class FloorFactory {
단점도 함께 생각해보시란 의미에서 질문드렸습니다. 단점들을 잘 정리해주셨네요.
이번에 FloorFactory로 분리해주신 것처럼, 정리해주신 단점들보다 장점이 크게 느껴질때 Factory 클래스를 사용하시면 될 것 같습니다!

2024-03-02 13:34 UTC, summerlunaa approved these changes
카고 안녕하세요~~

리뷰도 다 잘 반영해주셨고 리팩토링까지 잘 해주셨군요!
리팩토링하면서 고민한 흔적들이 많이 보였습니다. 고민 적어주신 부분에는 답변을 달아드렸는데요, 요거까지 반영할 수도 있겠지만 요구사항을 모두 충족하셨으므로ㅎㅎ 여기서 머지하도록 하겠습니다.

답글은 계속 확인해볼테니 궁금한 점은 계속 스레드로 남겨주셔도 좋아요! 두 번째 미션 사다리 게임도 너무 수고하셨습니다 👏 👍

2024-03-02 13:34 UTC, summerlunaa commented on src/main/java/LadderMain.java
> +    public static void printGameResultUtilSelectAll(final GameResults gameResults) {
```suggestion
    public static void printGameResultUntilSelectAll(final GameResults gameResults) {
```
맞나요? 👀

2024-03-02 13:34 UTC, summerlunaa commented on src/main/java/LadderMain.java
> +        return new LadderGame(playerNames, results, ladder);
클래스명과 메서드명들이 이전보다 훨씬 직관적으로 바뀌어서 이해하기 쉬워졌어요!! 💯

2024-03-02 13:34 UTC, summerlunaa commented on src/main/java/domain/ladder/Floor.java
> +        return startPosition;
깔끔합니다 👍

2024-03-02 13:34 UTC, summerlunaa commented on src/main/java/domain/GameResult.java
> +public record GameResult(String name, String matchingItem) {
하나의 질문에 굉장히 많은 고민들을 하셨군요 🥹 

카고가 만든 `PlayerNames` 클래스를 확인해보니 설명해주신대로 `getValues` 메서드를 사용해서 `List<String>`을 반환해주셨네요. 이걸 보고 두 가지 의견이 떠올랐는데요,

1. 사용자가 `getValues` 메서드를 사용할 때 `List<String>`이 나올지 `List<PlayerName>`이 나올지 알 수 없다.
`getValues`, 혹은 `getNames`와 같은 이름을 가진 메서드를 사용할때 사용자가 `List<String>`이 나올지 `List<PlayerName>`이 나올지 알 수 있을까요? 혹은 `List<PlayerName>`이 필요한 경우가 있다면 어떻게 될까요?
`getStringValues`와 `getValues` 등으로 메서드를 구분하는 방법도 있겠지만 글쎄요 좋은 방법인지는 잘 모르겠네요 😅

2. 불변을 보장하고 의미를 부여하는 값객체와 일급컬렉션을 최대한으로 활용해야 한다.
이왕 불변을 보장하고 의미를 부여하는 값객체와 일급컬렉션을 만들었다면, 진짜 원시값이 필요한 순간이 오기 전까지는 최대한 이를 활용하는 게 좋을 것 같아요. 물론 현재는 `OutputView`에 일급컬렉션인 `PlayerNames`를 넘기고 있지만 `getValues` 메서드가 만들어진 이상 쉽게 원시값을 꺼내서 사용할 수 있겠다는 생각이 들더라구요!

물론 정반대의 생각도 함께 들었습니다.

1. 말씀하신대로 DTO를 사용하지 않는 현재 상황에서는 값객체나 일급컬렉션을 DTO처럼 사용할 수 있어요. 불변이라는 점에서 안전해보이구요. 이런 의도라면, 즉 DTO의 역할도 함께 하고 있는 걸로 본다면 카고의 말대로 원시값으로 변환하여 반환해주는 메서드가 있는 것도 충분히 납득이 됩니다.

2. 원시값을 꺼낼 일이 많아서 사용처마다 getter를 남발하는 메서드 체이닝이 계속 일어난다면,,, 가독성과 코드 퀄리티를 위해서라도 그냥 원시값 변환 메서드를 만들 것 같긴합니다ㅋㅋ

요정도로 저의 생각을 정리해보았는데 도움이 되었으면 좋겠네요. 원시값 포장부터 시작해서 DTO의 필요성으로 이어지는 생각의 흐름이 굉장히 좋았습니다!!! 💯  도메인과 뷰가 점점 복잡해질수록 DTO의 필요성을 더 체감하실거예요 ㅎㅎ

2024-03-02 13:34 UTC, summerlunaa commented on src/main/java/domain/ladder/Width.java
> +    }
`PlayerNames 객체 생성 -> Width 객체 생성`의 흐름이 반드시 필요하다면 PlayerNames가 Width 객체를 생성해주는 방식은 어떨까요?

2024-03-02 13:34 UTC, summerlunaa commented on src/main/java/domain/GameResult.java
> +public record GameResult(String name, String matchingItem) {
> 이 대공사는 TDD를 지키지 못했답니다 ㅎㅎ

아쉬운 포인트군요 🥹 TDD가 익숙하지 않으면 리팩토링시에, 특히나 리팩토링의 범위가 크다면 TDD로 진행하기 쉽지 않죠. 
TDD를 공부하는 단계인만큼 의식적으로 TDD를 지켜보면 더 도움이 될 것 같습니다 👍

2024-03-02 13:34 UTC, summerlunaa commented on src/main/java/domain/MatchingItems.java
> +    }
> 참가자와 실행 결과만으로 LadderGame을 먼저 생성해두고, Ladder는 LadderGame의 play()메서드를 호출할 때 매개변수로 넘겨주면 해결할 수 있을 것 같은데 좋은 방법이 맞을까요?!

요구사항에 따라 구현도 달라질 수 있을 것 같아요. 하나의 게임에서 여러 사다리를 생성하여 결과를 확인할 수 있으며 사다리가 일회용이라면 말씀해주신 것처럼 구현할 수도 있겠지만 지금 상황에서는 LadderGame이 Ladder를 가지고 있는 게 더 자연스러워 보이긴 하네요.

구조 변경이 사다리게임 서비스 이용에 불편을 끼친다면 그대로 두어도 괜찮을 것 같습니다!! 기본적인 입력에 대한 검증을 수행하는 InputValidator를 추가할 수도 있을 것 같은데 이건 너무 오바인 것 같습니다 ㅋㅅㅋ

2024-03-02 13:35 UTC, merged

2024-03-04 08:08 UTC, devhoya97 commented on src/main/java/domain/MatchingItems.java
> +    }
넵 서비스 이용에 불편을 끼치지 않는 것이 중요하겠네요!
다음 미션부터는 서비스 이용에 불편을 끼치지 않으면서도 검증 책임을 적절하게 위임할 수 있도록 구조를 설계해야겠어요...!

2024-03-04 08:21 UTC, devhoya97 commented on src/main/java/domain/GameResult.java
> +public record GameResult(String name, String matchingItem) {
> 사용자가 getValues 메서드를 사용할 때 List<String>이 나올지 List<PlayerName>이 나올지 알 수 없다.

맞습니다. 그 부분에서도 고민을 했는데 답을 찾지 못하고, List<PlayerName>이 필요한 상황이 아직 없으니까 일단 넘어가자 생각했던 것 같아요. 이 부분은 파랑의 말처럼 DTO를 사용하면 해결될 수 있을 것 같네요!!

***

> 불변을 보장하고 의미를 부여하는 값객체와 일급컬렉션을 최대한으로 활용해야 한다.

`값객체와 일급컬렉션을 언제까지 유지해야 할까?`도 궁금했던 포인트인데, 유지할 수 있는 한 최대한 유지하는게 좋겠네요!

***

> TDD를 공부하는 단계인만큼 의식적으로 TDD를 지켜보면 더 도움이 될 것 같습니다 👍

맞아요. 지금은 최선의 결과 코드를 내는 것보다 오히려 그 과정에서 배워나가는 것에 집중해야하는데, 그러지 못했던 것 같아요. TDD도 마찬가지로 앞으로는 좀 더 미션의 의도에 맞게 학습하는 것에 집중해볼게요 !!

2024-03-04 08:32 UTC, devhoya97 commented on src/main/java/domain/ladder/Width.java
> +    }
현재는 List<PlayerName>의 길이를 알아야 생성할 수 있는 객체가 Width 하나 뿐이니 파랑이 제안해주신 방식도 좋아보여요! 

그런데 예를 들어 List<PlayerName>의 길이를 알아야 생성할 수 있는 객체가 여러개라면, PlayerNames의 코드 안에 다른 객체들을 생성해주는 메서드들이 늘어나게 되고 객체의 역할이 퇴색될수도 있을 것 같다는 생각도 함께 들어요. 어떤 속성이 정말 여러 군데에서 사용할 필요가 있다면 PlayerNames의 count처럼 메서드만 제공하는 것이 나을테고, 지금과 같이 연관된 객체가 하나라면 PlayerNames가 Width 객체를 생성하는 방식도 좋을 것 같네요!!

2024-03-04 08:34 UTC, devhoya97 commented on src/main/java/LadderMain.java
> +    public static void printGameResultUtilSelectAll(final GameResults gameResults) {
헉 맞습니다 이런 실수도 했네요 😅

2024-03-04 08:37 UTC, devhoya97 commented on src/main/java/LadderMain.java
> +        return new LadderGame(playerNames, results, ladder);
사다리를 타는 메서드가 너무 복잡해서 이해하는데 쉽지 않았다는 피드백을 듣고 나서부터, `어떻게 네이밍해야 파랑이 읽기 쉬울까?` 를 생각하다보니 더 좋은 이름들이 떠올랐던 것 같아요! 네이밍은 항상 읽는 사람 입장에서 지어야겠어요 😁

2024-03-04 08:40 UTC, devhoya97 commented
파랑 덕분에 제게 필요했던 고민을 오랜시간 할 수 있었습니다!!! 미션임에도 불구하고 즐거운 시간이었어용 ㅎㅎㅎ 

부족한 점들이 많았을텐데 정성껏 봐주셔서 진심으로 감사드립니다!! 🥹🙇‍♂️