[사다리 게임] 코니 미션 제출 합니다.
woowacourse/java-ladder pull request #37
Opened 2019-05-18 04:22 UTC by choihz

더 작은 객체로 쪼개는 것에 대해 많은 시도를 했는데 제대로 이뤄지지 않아서, 우선은 제가 할 수 있는 범위 내에서 미션을 진행했습니다. 객체 지향 설계에 대해 주말에 더 고민해 보겠습니다!

2019-05-19 07:36 UTC, phs1116 requested changes
안녕하세요. 리뷰어 화투입니다. :)
전체적으로 객체들을 책임 별로 잘 분히하려고 노력하신점이 보여요 👍 
객체를 쪼갠다는것에 중점을 두지 마시고 
책임을 적합한 객체가 가지도록 하는 것에 집중하는게 좋을 것 같아요!
피드백 몇 개 추가했고 궁금하신 점 있으시면 언제든지 연락주세요. :)

2019-05-19 07:36 UTC, phs1116 commented on src/main/java/ladder/utils/ValidatorUtils.java
> +public class ValidatorUtils {
ValidatorUtils이라는 이름으로 전체 밸리데이션 로직을 묶지 말고 각각의 도메인 객체가 가지도록 하면 어떨까요?
현재 여기에 해당하는 내용들은 비즈니스 정책이지 유틸성 내용들은 아닌 것 같아서요 :)
예를들어 checkNames같은 경우는 Player 객체와 Players 일급 컬렉션을 생성해서 내부에서 검증을 가지도록 하는 등 할수있겠네요 :)

2019-05-19 07:36 UTC, phs1116 commented on src/main/java/calculator/StringCalculator.java
> +    private int getSum(String[] tokens) {
get은 관례상 내부의 객체를 반환하는 용어니까 그냥 sum으로 표현해도 될 것 같아요. :)

2019-05-19 07:36 UTC, phs1116 commented on src/main/java/calculator/StringCalculator.java
> +        if (isNull(input) || input.isEmpty()) return 0;
isNull같은 경우는 Objects.isNull이라는 자바 기본 메서드가 있어요. :)

2019-05-19 07:36 UTC, phs1116 commented on src/main/java/calculator/StringCalculator.java
> +        if (Integer.parseInt(token) < 0) {
매직넘버 상수로 빼주세요!

2019-05-19 07:36 UTC, phs1116 commented on src/main/java/ladder/Application.java
> +        List<String> names = InputView.inputNames();
names, items를 별도 객체로 래핑해보면 어떨까요?

2019-05-19 07:36 UTC, phs1116 commented on src/main/java/ladder/domain/Ladder.java
> +    public List<Integer> play() {
메서드 시그니쳐만 보면 play의 반환값에 대한게 무엇인지 눈에 들어오지 않는 것 같아요.
LadderResult를 여기서 생성해서 반환해주면 어떨까요?

2019-05-19 07:36 UTC, phs1116 commented on src/main/java/ladder/domain/LadderGenerator.java
> +public class LadderGenerator implements LadderBuilder {
LadderGenerator가 LineGenerator의 구현체에 너무 강하게 의존하고 있어 OCP(개방-폐쇠 법칙)과 DIP(의존성 역전 연칙)에 위바되는 것 같아요. 
느슨하게 의존하도록 수정해보면 어떨까요? :)

2019-05-19 07:36 UTC, phs1116 commented on src/main/java/ladder/domain/LineGenerator.java
> +public class LineGenerator implements LineBuilder {
LadderBuilder -> LadderGenerator, LineBuilder -> LineGenerator
보통 형용사 같은 '기능'을 나타내는 인터페이스일 경우에는 전혀 다른 이름으로 사용되기도 하는데요 
구현체들 또한 너무 추상화된 이름이라 역할이 어떤 제네러이터인지 명확하게 보이지 않는 것 같습니다. :)

2019-05-19 07:36 UTC, phs1116 commented on src/main/java/ladder/Application.java
> +    private void printResult(List<String> names, List<String> finalResult) {
플레이어 - 상품에 대해서 조금 더 추상화해보면 어떨까요?
그냥 우승자만 던져주면 상품만 가져올 수 있도록이요. :)
결과를 구하는 부분에 대해서 인덱스로 찾는 등 추상화가 되어있지 않아 코드를 보기 어려운 점이 있어요!

2019-05-20 09:24 UTC, choihz commented
꼼꼼한 피드백 감사합니다! 최대한 반영하여 수정하기 위해 노력했어요. 그런데 인터페이스 이름에 대해 설명해 주신 부분을 제가 잘 이해하지 못하여 이 부분은 수정하지 못했고, LadderGenerator와 LineGenerator의 의존성에 대해서도 좀 더 고민이 필요할 것 같아 이번에는 수정하지 못했습니다.

2019-05-20 10:14 UTC, phs1116 requested changes
안녕하세요. 리뷰어 화투입니다!
피드백 잘 반영해주셔서 감사합니다! :)
질문주신 사항에 대해 답변과 피드백 몇 개 추가했어요. :)
참고 부탁드리고 궁금하신 점 있으시면 연락주세요!

2019-05-20 10:14 UTC, phs1116 commented on src/main/java/ladder/domain/LadderGenerator.java
> +public class LadderGenerator implements LadderBuilder {
LadderGeneartor가 LineGenerator에게 강하게 의존하고 있어서 LineGenerator의 로직만 바꾸고 싶을 경우에는 아에 새로운 클래스를 만들어야합니다.
다만 LineGenerator를 생성자로 주입받아 사용한다면, 코드의 변경은 없지만 확장에는 유연하게 되겠죠? :)

2019-05-20 10:14 UTC, phs1116 commented on src/main/java/ladder/domain/MockLadderGenerator.java
> +public class MockLadderGenerator implements LadderBuilder {
위에 말씀하신대로 주입하는 형태로 수정한다면
MockLadderGenerator를 만들 필요 없이
LadderGenerator에 MockLineGenerator을 주입하는 형태가 될수 있을거에요.
현재 코드는 대부분 중복인데 MockLineGenerator를 사용하는부분만 변경되어있으니까요. :)

2019-05-20 10:14 UTC, phs1116 commented on src/main/java/ladder/Application.java
> +        } while (!participant.toString().equals("all"));
all은 상수로 뺄 수 있을 것 같네요 :)

2019-05-20 10:14 UTC, phs1116 commented on src/main/java/ladder/view/OutputView.java
> +        if (participant.toString().equals("all")) {
all은 상수로 뺼 수 있을것 같네요.
all의 분기에 대한 책임이 main이랑 번갈아서 가져갈 필요가 있을까요?

2019-05-20 10:14 UTC, phs1116 commented on src/main/java/ladder/view/OutputView.java
> +        System.out.println(finalResult.get(players.indexOf(participant)));
finalResult.get(players.indexOf(participant)
추상화가 되어있지 않아 이해하기 어려울 수 있는 점이 있습니다.
LadderResult.findRewardByPlayer(player)처럼 조금 더 추상화 할 수 있지 않을까요? :)

2019-05-20 10:14 UTC, phs1116 commented on src/main/java/ladder/view/OutputView.java
> +    private static String LineStructure(Line line, int index) {
메서드 시그니쳐의 기본 컨벤션은 동사형 + 카멜케이스에요. 
수정 부탁드릴게요 :)

2019-05-20 10:14 UTC, phs1116 commented on src/main/java/ladder/domain/LineGenerator.java
> +public class LineGenerator implements LineBuilder {
단순하게 어떤식으로 구체화된 클래스인지 명확하게 하면 더 좋아서 말씀드렸어요. :)
랜덤을 사용한 LineBuilder니까 RandomLineBuilder 처럼요!

2019-05-20 10:14 UTC, phs1116 commented on src/main/java/ladder/domain/Ladder.java
> +        if (index == 0) {
line.isConnected로 너무 많은 로직이 들어가있는 것 같아요.
Line내에서 추상화 할 수 있지 않을까요?

2019-05-21 05:06 UTC, choihz commented
피드백 최대한 반영하려 노력했습니다! 다만 LadderGeneartor와 LineGeneartor를 수정하긴 했는데 리뷰어님이 의도하신 대로 제가 잘 수정한 것인지 잘 모르겠어요. 인터페이스를 매개변수로 받게 하여 MockLadderGenerator를 없애고 중복 코드가 개선되었지만 여전히 둘의 의존성은 그대로인 것 같아서요.
 그리고 컨트롤러에 all이 들어가는 것은 분기에 대한 책임을 나눠 가졌다기보다는 이름을 계속 입력받기 위해서 사용한 것입니다. 혹시 더 좋은 방법이 생각나신다면 알려주세요 😄

2019-05-21 10:58 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다. :)
전체적으로 피드백 잘 반영해주셔서 감사합니다. 👍 
질문 주신 사항에서 의존이란건 어느정도 생길 수밖에 없는데요, 
대신 강하게 의존하는게 아니라 인터페이스를 통해 느슨하게 의존하는 구조를 생각해보면 된다고 보시면 될 것 같아요!
조금 더 개선할 수 있을 것 같아서 피드백 추가했는데 확인 부탁드립니다.
궁금하신 점 있으시면 연락주세요. :)

2019-05-21 10:58 UTC, phs1116 commented on src/main/java/ladder/domain/LadderResult.java
> +public class LadderResult {
LadderResult라는 객체가 FinalResult와 Players를 필드를 가지는게 객체의 역할상 더 자연스럽지 않을까요?
게임의 결과로 LadderResult라는 객체가 반환되고, 여기서 어떤 사용자가 어떤 아이템을 반환하는지 알려주는 책임을 가지는게 더 적합해보여서요!

2019-05-21 10:58 UTC, phs1116 commented on src/main/java/ladder/domain/Line.java
> +        if (isConnected(index - 1)) return index - 1;
Point 부분이 너무 추상화 되어있지 않다보니 해당 로직이 조금 복잡해 보이는 것 같아요.
어떤 index에 대해서 해당 Point가 왼쪽으로 연결되어있는지, 오른쪽으로 연결되어있는지로 표현할 수 있지 않을까요?
어차피 특정 포인트에 대한 방향은 한방향밖에 없으니까요. :)
```
public class Point {
      private Direction direction
}
```
같이 표현 할 수 있을 것 같네요. :)

2019-05-23 10:49 UTC, phs1116 approved these changes
안녕하세요. 리뷰어 화투입니다.
피드백 잘 반영해주셔서 감사합니다. :)
이번 단계 머지할게요! 
한주동안 사다리 게임 구현하시느라 수고 많으셨습니다. :)

2019-05-23 10:49 UTC, phs1116 commented on src/main/java/ladder/Application.java
> +        OutputView.printPlayers(players);
players, ladder, items가 응집력있게 하나의 객체로 표현될 수도 있을 것 같네요. :)

2019-05-23 10:50 UTC, merged