[미션 2단계 - 사다리 게임 실행] 도비(김도엽) 미션 제출합니다.
woowacourse/java-ladder pull request #371
Opened 2024-02-28 11:02 UTC by Dobby-Kim

2024-02-28 16:42 UTC, jinyoungchoi95 requested changes
안녕하세요 도비 😄

몇가지 피드백 코멘트로 남겨두었으니 확인부탁드려요 :)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-02-28 16:42 UTC, jinyoungchoi95 commented on src/main/java/view/InputView.java
> VIew 객체의 정체성에 대한 고민
> InputView와 OutputView가 모두 정적 메서드를 사용하는 클래스로 작성이 되었는데, 인스턴스를 생성하지도 않고 컨트롤러에서 정적으로 import 되어 사용된다면 이 view라고 불리는 클래스들이 정적 util 클래스와 차이점이 무엇인가에 대한 고민이 생겼습니다!
간단한 콘솔게임이라 view의 역할이 약해서 그런 것 같기도 하고 경우에 따라 다르기에 답은 정해져있지 않겠지만 전역적으로 사용되는 util에 속하지 않았다면 정적 메서드를 가진 클래스로 사용을 지양해야 하는지 의문이 들었습니다!
또한, 작성된 InputView 정도의 클래스는 Util로 분류되어도 되지 않나 싶어 이에 대한 인사이트를 얻고 싶습니다!

정적 메소드를 가진 클래스의 정의가 util이 아닌 util이 정적 메소드를 가진다라고 생각하시면 편할 것 같아요.

그렇다면 말씀하신대로 간단한 콘솔게임의 구현이라 View 클래스들을 굳이 인스턴스로 정의할 필요없이 껍데기만으로 출력을 하고 있어도 되는거죠. util은 말그대로 도움을 주는 support 클래스로 주로 사용하기 때문에 다른 클래스 사용에 도움을 주는게 아닌 화면 출력을 하는 View는 util로 정의되기는 어려워보여요.

2024-02-28 16:42 UTC, jinyoungchoi95 commented on src/main/java/controller/GameController.java
> GameBoard 클래스의 역할에 관한 고민
> GameBoard 클래스는 사다리 게임에 필요한 기본적인 객체(Players, Ladder, PrizeNames) 를 주입받아 생성됩니다. 그리고, 그 인스턴스들에게 필요한 정보에 대한 조회를 요구하여 Controller로 반환하도록 하는 역할을 가지도록 하였습니다.
미션을 진행하다 보니, GameBoard가 마치 Controller과 같은 역할을 하는 클래스처럼 느껴져, GameBoard를 잘못 설계했나 싶은 고민이 생겼었습니다
물론 많은 고려사항이 있겠지만, 도메인 객체로 설계된 클래스가 이 GameBoard 정도의 책임과 역할을 가지고 있어도 되는지 오리의 의견을 들려주시면 감사하겠습니다!

GameBoard에 대한 고민을 하기 전에 Controller에 대한 이야기를 먼저 해보면, 과연 이 클래스 네이밍이 적절할까요?

MVC패턴에서의 혹은 spring에서의 controller는 현재 만들어주신 `GameController`와는 정의된 역할이 달라요. 그리고 현재는 "자바만을 사용해서 돌아가는" 콘솔 프로그래밍을 만드는 것이 목적이기 때문에 2레벨에서 사용하게 될 패턴의 관습적인 네이밍은 사용하지 않으셔도 되어요.

그럼 이제 패턴을 다 빼고, `GameController`라는 네이밍을 볼까요? 컨트롤러라는 네이밍은 해석하면 조작기, 즉 흔히 이야기하는 조이스틱으로 해석돼요. 조이스틱이 화면을 들고 있고 게임을 실행할 엔진이 있고 게임을 실행하지 않듯이 지금 이 모든 실행 로직은 `GameBoard`라는 네이밍의 클래스가 실행하는게 더 적절해보이지 않나요?

이야기해드린 관점에서 `GameController`의 존재의의를 다시한번 고민해보시고 수정하거나 궁금한점이 더 있으면 코멘트 달아주세요 :)

2024-02-28 16:42 UTC, jinyoungchoi95 commented on README.md
> +all
<img width="216" alt="스크린샷 2024-02-29 오전 1 09 30" src="https://github.com/woowacourse/java-ladder/assets/69106910/3619a693-2937-4103-94f9-ff04135b5b5d">

결과가 제대로 안나오네요 👀

2024-02-28 16:42 UTC, jinyoungchoi95 commented on src/main/java/domain/Name.java
> +public abstract class Name {
abstract class를 통해서 `PlayerName`이나 `PrizeName`이 상속된다라고 했을 때 메소드 재정의(override)하면 캡슐화가 깨지는 것 아닌가요?

2024-02-28 16:42 UTC, jinyoungchoi95 commented on src/main/java/domain/player/PlayerName.java
> +    }
1. "all"은 화면단의 요구인데 화면의 기능 요구사항이 "all print"로 바뀌면 도메인 코드의 변경점이 생기겠네요.
2. 아래 테스트코드가 동작할까요?
```java
    @Test
    void test() {
        PlayerName name = new PlayerName("all");
        assertTrue(name.isAll());
    }
```

2024-02-28 16:42 UTC, jinyoungchoi95 commented on src/main/java/domain/player/Player.java
> +public record Player(PlayerName playerName) {
`String name`을 `PlayerName`으로 래핑하고 있고, 그걸 `Player`가 또 래핑하고 있어요. `Player`는 현재 필요한 클래스일까요? 그냥 `Player`가 `String name`을 가지고 validation도 `Player`가 해도되지 않을까요?

2024-02-28 16:42 UTC, jinyoungchoi95 commented on src/main/java/domain/ladder/attirbute/Direction.java
> +    DOWN("|      ");
화면의 출력 요구사항이 `-------`로 더 길게 출력을 요구하면 도메인 코드에 변경점이 발생하겠네요.

2024-02-28 16:42 UTC, jinyoungchoi95 commented on src/main/java/domain/ladder/Ladder.java
> +        return moveCoordinateToResultPoint(x, y);
```suggestion
        if (currentDirection.equals(Direction.RIGHT)) {
            return moveCoordinateToResultPoint(x + 1, y + 1);
        }
        if (currentDirection.equals(Direction.LEFT)) {
            return moveCoordinateToResultPoint(x - 1, y + 1);
        }
        return moveCoordinateToResultPoint(x, y + 1);
```
현재의 경우에는 무엇이 더해졌는지 기억한 다음 46라인 리턴문을 보아야하기 때문에 읽는데 어려움이 있을 수도 있어 위와 같이 표현되는게 어떨까해요.

2024-02-28 16:42 UTC, jinyoungchoi95 commented on src/main/java/domain/prize/PrizeNames.java
> +            throw new IllegalArgumentException("상품의 개수가 플레이어 수와 일치하지 않습니다.");
테스트가 추가되면 좋을 것 같네요 :)

2024-02-28 16:42 UTC, jinyoungchoi95 commented on src/main/java/domain/player/Players.java
> +                                  .toList();
혹시 indent 설정이 어떻게 되어있을까요? 제가 설정한 우테코 docs의 코드스타일로는 indent가 이렇게 포맷팅되고 있지 않아서요.

2024-02-28 16:42 UTC, jinyoungchoi95 commented on src/main/java/domain/player/Players.java
> +                                              .equals(targetPlayerPlayerName))
player가 `PlayerName`을 받아 이름이 같은지 검증하도록 메시지를 전달하게 변경하면 좋을 것 같네요 :)

2024-02-28 16:42 UTC, jinyoungchoi95 commented on src/main/java/util/InputRetryHelper.java
> +        throw new IllegalStateException("Utility class");
👍

2024-02-28 16:42 UTC, jinyoungchoi95 commented on src/main/java/util/InputRetryHelper.java
> +            }
메소드 indent가 2를 넘어가고 있네요.

2024-02-28 16:42 UTC, jinyoungchoi95 commented on src/main/java/domain/GameBoard.java
> +                      .get(value);
getter로 로직을 호출하지말고 `Players`가 index를 받아 name을 받아오도록 할 수 있지 않을까요?

2024-02-28 16:42 UTC, jinyoungchoi95 commented on src/main/java/domain/GameBoard.java
> +        return results;
stream에서 종단연산으로 forEach를 사용하는 것은 안티패턴이에요.

> Terminal operations, such as Stream.forEach or IntStream.sum, may traverse the stream to produce a result or a side-effect. After the terminal operation is performed, the stream pipeline is considered consumed, and can no longer be used; if you need to traverse the same data source again, you must return to the data source to get a new stream. In almost all cases, terminal operations are eager, completing their traversal of the data source and processing of the pipeline before returning. Only the terminal operations iterator() and spliterator() are not; these are provided as an "escape hatch" to enable arbitrary client-controlled pipeline traversals in the event that the existing operations are not sufficient to the task.

https://docs.oracle.com/javase/8/docs/api/java/util/stream/package-summary.html
https://homoefficio.github.io/2016/06/26/for-loop-%EB%A5%BC-Stream-forEach-%EB%A1%9C-%EB%B0%94%EA%BE%B8%EC%A7%80-%EB%A7%90%EC%95%84%EC%95%BC-%ED%95%A0-3%EA%B0%80%EC%A7%80-%EC%9D%B4%EC%9C%A0/

stream 문법을 더 적절하게 사용해보는건 어떨까요?

2024-02-29 02:06 UTC, Dobby-Kim commented on src/main/java/domain/player/PlayerName.java
> +    }
> 1. "all"은 화면단의 요구인데 화면의 기능 요구사항이 "all print"로 바뀌면 도메인 코드의 변경점이 생기겠네요.

이 부분은 원래 GameController 자체에서 판단하는 기능을 가지도록 했습니다.
고민을 해보다가 입력된 이름을 판별하는 역할을 PlayerName이 맡는 것이 맞는 것 같다고 생각해서 PlayerName 클래스로 넣었습니다!

> 2\. 아래 테스트코드가 동작할까요?
toString() 메서드를 오버라이딩하여 코드 작성을 진행하였었는데, 불필요하다고 생각하여 getValue() 메서드가 원래의 toString()의 역할을 하도록 변경하였습니다!

리팩토링을 진행하면서 수정점이 적용이 안된 부분을 확인하지 못했습니다..! 리팩토링을 할 때 test도 함께 유지보수를 했었는데 더 신경써보도록 하겠습니다 :)

2024-02-29 02:40 UTC, Dobby-Kim commented on src/main/java/domain/player/Player.java
> +public record Player(PlayerName playerName) {
맞습니다! 이 부분이 상당히 많은 고민이 되는 부분이었습니다.
2가지 부분에서 궁금한 점이 발생했었습니다.

1.  원래의 설계는 `Player`가 `PlayerName`과  `PrizeName`을 소유시킬 생각이었습니다.
```java
public record Player(PlayerName playerName, PrizeName prizeName){
...
}
```
그러나 기존 작성된 코드의 로직 순서가
> `PlayerName` 입력받아 생성 -> `Player`생성 -> `GameBoard`가 `Player`별 `PrizeName` 판단 -> `Player`에게 `PrizeName` 배정
인 상태에서, `Player` 생성시에 `PlayerName`과 `PrizeName`을 동시에 주는 의존성 주입이 순서상 성립하지 않아 단순히 생성시에 `PlayerName`만 가지고 있는 클래스가 되었습니다.

객체 생성 시에 배정받지 못한`PrizeName` field를 가지고 추후에 결과를 배정받아야되는 `Player`의 경우에는 setter와 같이 외부에서 인스턴스 필드를 업데이트하는 방법을 사용해도 괜찮을까요? 아니면 지양해야될까요?
혹은 다른 방법이 있다면 인사이트를 얻고 싶습니다!

2. 원시 타입을 어느 깊이까지 래핑해야 하는지에 대한 고민
> name은 입력된 String을 사용할 수 있는 이름인지를 판단한 후에 인스턴스에서 사용될 field로 주입되어야 하지 않을까?
라는 결론을 가지고 사용자 입력을 `PlayerName`에서 검증 및 생성을 한 후에 `player`로 주입하는 것으로 결정하였습니다.

그러고 나서, 1번의 고민의 결과로 `player`가 `PlayerName` 필드만 가지게 된 상황이 되었습니다.
`Player`가 record 클래스로  `PlayerName`만 가지게 되자 말씀해주신 고민이 생겼습니다.

`Player`와 일급컬렉션인 `Players`가 도메인 로직을 지니고 있는 현재 상황에서 **`Player`에 주입되어야하는 `PlayerName` 필드가 원시 타입인 `String`이어도 되는가**에 대해 생각하게 되었고, 그렇다면 원시타입의 랩핑은 어떤 기준으로 이루어져야하는가에 대해 질문 드리고 싶었습니다!

2024-02-29 02:45 UTC, Dobby-Kim commented on src/main/java/domain/ladder/attirbute/Direction.java
> +    DOWN("|      ");
코드 메서드와 로직을 간결하게 유지해보려고 이렇게 수정을 진행했는데 이 부분을 간과했던 것 같습니다!

기존에는 EnumMap에 symbol들을 매핑하여 OutputView에서 인스턴스 필드로 가지고 있게 작성했었었는데, 원래의 방법이 도메인 코드와 view를 분리하는 관점에서 더 옳았던 걸까요?

2024-02-29 03:06 UTC, Dobby-Kim commented on src/main/java/domain/player/Players.java
> +                                  .toList();
chain method align 설정이 조금 달랐던 것 같습니다!
수정하여 적용하였습니다 :)

2024-02-29 08:42 UTC, Dobby-Kim commented on src/main/java/domain/player/PlayerName.java
> +    }
> 1. "all"은 화면단의 요구인데 화면의 기능 요구사항이 "all print"로 바뀌면 도메인 코드의 변경점이 생기겠네요.

리팩토링을 진행해보다가 고민되는 부분이 생겨서 오리의 의견을 듣고 싶습니다!

저는 기능 요구 사항의 `개인별 이름을 입력하면 개인별 결과를 출력하고, "all"을 입력하면 전체 참여자의 실행 결과를 출력한다.`와 출력 예시를 보고 `all이라면 모든 플레이어의 이름과 결과를 출력하고 프로그램을 종료한다.`를 요구된 기능으로 상정하고 이를 도메인 로직이라고 생각하여 기능 구현을 진행해왔습니다.

그래서 `all`의 처리를 도메인 로직단에서 처리해야된다고 생각하며 코드를 작성하려고 하는데, 오리께서는 어떤 것을 기준으로 화면단의 요구로 분류하셨는지 의견을 듣고 싶습니다!

2024-03-01 08:18 UTC, jinyoungchoi95 commented on src/main/java/domain/player/PlayerName.java
> +    }
모든 사용자에 대한 처리를 하는 것을 도메인이 가지고 있는 것이 아닌 `all` 그 자체를 `PlayerName`이 가지고 처리하고 있기 때문이에요. 모든 사용자에 처리는 말씀하신대로 도메인 로직단에서 처리하는 것이 맞지만 그것이 화면의 요구사항인 `all`을 도메인이 그대로 들고 있는 순간 말씀드린 화면 요구가 변경되었을 때 도메인의 여파가 생기기 때문에 말씀드린 것이었어요.

2024-03-01 08:21 UTC, jinyoungchoi95 commented on src/main/java/domain/ladder/attirbute/Direction.java
> +    DOWN("|      ");
네 출력을 위한 enum을 도메인과 별개로 view에 넣어두는 것은 큰 문제가 없어보여요.

> 핵심 로직을 구현하는 코드와 UI를 담당하는 로직을 구분한다.
> UI 로직을 InputView, ResultView와 같은 클래스를 추가해 분리한다.

는 앞으로 미션을 하시면서도 간결성을 보는 것이 아닌 도메인 로직과 ui 로직의 분리를 1순위로 두시는 것이 좋을 것 같아요.

2024-03-01 08:36 UTC, jinyoungchoi95 commented on src/main/java/domain/player/Player.java
> +public record Player(PlayerName playerName) {
> 객체 생성 시에 배정받지 못한PrizeName field를 가지고 추후에 결과를 배정받아야되는 Player의 경우에는 setter와 같이 외부에서 인스턴스 필드를 업데이트하는 방법을 사용해도 괜찮을까요? 아니면 지양해야될까요?

외부에서 인스턴스 필드를 업데이트하는 것을 사용하는 것에 대해서 고민하시는 부분이 불변성 때문인 것 같은데요.

사다리 게임을 생각해보았을 때 `Player`는 게임이 끝나고 `Prize`를 선택을 받는데, 이건 `Player`가 계속해서 가지고 다니는 정보라기보다는 한판의 결과에 불과하다고 생각한다면 `GameBoard`에서 한판의 게임을 실행할 때 `Player`와 `Prize`를 감싼 결과의 의미를 담은 클래스를 만들어 반환하면 고민하시던 부분이 해결되지 않을까 싶네요.


> Player와 일급컬렉션인 Players가 도메인 로직을 지니고 있는 현재 상황에서 Player에 주입되어야하는 PlayerName 필드가 원시 타입인 String이어도 되는가에 대해 생각하게 되었고, 그렇다면 원시타입의 랩핑은 어떤 기준으로 이루어져야하는가에 대해 질문 드리고 싶었습니다!

`원시타입을 써야겠다 -> 여기랑 여기는 무조건 원시 타입을 써야지`보다는 클래스 설계를 하고 만들어가면서 `이 클래스가 원시타입으로써 사용이 되네`가 떠올라야해요.

저는 이런 타입은 무조건 원시타입으로 만들어야겠다라는 기준을 잡지는 않아요. 만들면서 그 값에 대해서 필요한 비즈니스 로직이 있고 별도의 도메인으로 분리되어야한다고 생각하면 그때 분리를 하는거죠.

예를들어 지금 `Player`를 설계하는 입장에서 요구사항을 보면,
```
player는 1~5자의 공백을 제외한 이름을 가진다
```
여기서 `Player`는 이름에 대한 요구사항만 가지고 있고, 이미 이름만을 위한 도메인 객체에요. 여기서 `Name`으로 래핑을 하는건 설계의 관점이 아니라 영어 단어의 관점에서 플레이어, 이름이 떠올라 무의미한 래핑을 두번하는것이나 다름이 없는거죠. 거기에서 `Player`가 이름 이외의 도메인 로직을 처리하게 된다면 그때가서는 `Name`을 분리해볼까하는 고민을 시작하는 것이 과한 설계를 막는 방법일 것 같네요 :)

2024-03-01 08:47 UTC, jinyoungchoi95 requested changes
안녕하세요 도비 😄

사다리에서 학습과 미션을 충분히 진행하신 것 같아 이만 머지하려고합니다. 추가로 남겨둔 코멘트들에서 궁금하신점이 더 있으실까 하여 request change 드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-03-01 08:47 UTC, jinyoungchoi95 commented on src/main/java/domain/GameBoard.java
> +            return e.getMessage();
예외가 발생한다면 `e.getMessage()`로 메시지를 그냥 반환하기보다는 핸들링을 하려면 의미있는 값을 보내거나 상위에서 예외를 더 적절하게 사용할 수 있도록 catch를 하지 않는 것이 어떨까 싶네요.

`searchOnePlayerResult`에서 GameResult를 리턴값으로 받기를 기대하고 있는데 예외의 메시지가 반환되는 것은 적절하지 않아보여요.

2024-03-04 16:37 UTC, jinyoungchoi95 approved these changes
안녕하세요 도비 😄

사다리 미션 기간동안 주고받았던 피드백과 공부하셨던 내용들이 앞으로 진행할 미션과 학습에 많은 도움이 되길 바랍니다 😄 

감사합니다 🙇‍♂️

2024-03-04 16:37 UTC, jinyoungchoi95 commented on src/test/java/domain/GameBoardTest.java
> +        void setUp() {
`setUp` 👍 

`setUp`을 사용하는 방법도 현재는 충분히 좋다고 생각해요. given when을 setup에 두셔서 추가적으로 말씀드리면 `@Nested`를 통해서 계층형으로 만들면 given과 when이 좀 더 잘 구분된 테스트코드를 만들어낼 수 있습니다 :)

2024-03-04 16:37 UTC, merged