[2단계 - 사다리 생성] 호티(윤주호) 미션 제출합니다.
woowacourse/java-ladder pull request #378
Opened 2024-02-28 15:11 UTC by Ho-Tea

또 뵙네요 **찰리**!! (🍫..ㅎ)
1단계 미션에서 말씀해주신 `의도하지 않은 객체 사용 가능성`을 줄이고, 가독성있게 네이밍에 신경써서 2단계 미션을 구현해 보았습니다!!

이번 2단계에서 새롭게 도전한 것들은 아래와 같습니다!
### `Positon`, `CachedPosition`
- `Position` 객체는 `Participants`와 `Results`에서 반복적으로 사용되어 미리 인스턴스를 캐싱하여 성능향상을 도모해보았습니다!
-  우선 자주 사용되는 `Positon`의 최대수는 20개로 생각해서 `0~20`까지의 `Positon`객체만 미리 생성해두었습니다!
``` java
// Position 예시
   0      1     2     3
    |-----|     |-----|
    |     |-----|     |
    |-----|     |     |
    |     |-----|     |
    |-----|     |-----|
   0      1     2     3
```

### `Participants`, `Results`
- `Participants`
  - `Participant`를 `key` | `Position` 값을 `value`
- `Results`
  - `Position` 값을 `key` | `Result`값을 `value`로 설정해놓았습니다.
``` java
// pobi-0  honux-1 crong-2   jk-3
//꽝-0    5000-1  꽝-2    3000-3
pobi  honux crong   jk
    |-----|     |-----|
    |     |-----|     |
    |-----|     |     |
    |     |-----|     |
    |-----|     |-----|
꽝    5000  꽝    3000
```
### 헷갈리는 부분!
- 결과를 보고싶은 사람의 입력으로 `all` 이 들어오면 게임 전체 출력 후 종료하는 로직이 존재하였는데 해당 로직을 `Controller`에서 처리하게 됩니다.
- 이러한 프로그램의 실행과 종료에 관여하는 부분은 `Controller`에서 맡아 구성해야한다고 생각되어 위치시켰는데 괜찮은 방법인지 궁금합니다!
  - 만약 컨트롤러에 위치시키지 않는다면 컨트롤러의 특성을 띈 도메인을 따로 생성하여 도메인에서 처리하게끔 유지시켜야한다고 생각합니다
  - 도메인에서 처리를 한다면 컨트롤러의 코드는 간소화 되지만 컨트롤러에 성격을 띈 도메인은 좋지 않은 방향이라고도 생각이 들어 질문 드립니다!

2024-02-29 00:31 UTC, Gomding requested changes
안녕하세요 호티!
2단계에서도 고민과 함께 구현해주셨군요 👍 

질문에 대한 답변과 몇가지 코멘트 남겼어요!
궁금한 점 있으면 언제든 DM 남겨주세요 🙏

2024-02-29 00:31 UTC, Gomding commented on README.md
>  - 참가자들의 이름 입력
> 1. 함수형 인터페이스를 사용해 구현하는 방법
>     - 장점 : Ladder의 인자로 함수형 인터페이스를 받을 수 있어 클래스 형식이 제한되지 않아 자유롭다.
> 2. 커스텀 인테페이스를 상속해 구현하는 방법
>     - 장점 : 전략패턴을 사용해 새로운 인터페이스를 생성 후 구현하여 캡슐화의 이점을 도모 할 수 있다.
> 
> 이 두가지를 굉장히 고민했었는데 Ladder가 클래스 형식에 구애받지 않고 함수형 인터페이스만을 인자로 받기만 한다면 사다리를 생성할 수 있게끔 구현하고 싶어 FunctionalInterface를 사용하기로 결정했었습니다!
> 지금 생각해 보면 또 클래스 형식의 제한이 없는 것이 단점이 될 수도 있겠다.라는 생각이 들기도 합니다!
> 
> 제가 생각하는 장점과 단점은 위와 같긴 하지만 혹시 제가 잘못알고 있는 부분이 있다면 따끔하게 말씀 부탁드릴게요!

장단점에 대해 잘 고민해주셨네요!
두 방식을 어떻게 활용할지도 앞으로 계속 고민해볼 수 있겠어요! 😃

2024-02-29 00:31 UTC, Gomding commented on src/main/java/controller/LadderController.java
> +        outputView.printAllParticipantsResult(ladderGame.matchAllResults());
> 헷갈리는 부분!
> 결과를 보고싶은 사람의 입력으로 all 이 들어오면 게임 전체 출력 후 종료하는 로직이 존재하였는데 해당 로직을 Controller에서 처리하게 됩니다.
> 이러한 프로그램의 실행과 종료에 관여하는 부분은 Controller에서 맡아 구성해야한다고 생각되어 위치시켰는데 괜찮은 방법인지 궁금합니다!
> 만약 컨트롤러에 위치시키지 않는다면 컨트롤러의 특성을 띈 도메인을 따로 생성하여 도메인에서 처리하게끔 유지시켜야한다고 생각합니다
> 도메인에서 처리를 한다면 컨트롤러의 코드는 간소화 되지만 컨트롤러에 성격을 띈 도메인은 좋지 않은 방향이라고도 생각이 들어 질문 드립니다!

프로그램의 실행과 종료라는 관점으로 고민할 수 있겠지만
view에서 입력한 명령어에 대해 누가 처리할 것인가라는 관점도 보이는군요 😃 

저는 현재처럼 Controller 에서 제어하는것이 좋아보입니다 😄 
말씀대로 도메인의 역할은 아니라고 생각해요!

2024-02-29 00:31 UTC, Gomding commented on src/main/java/model/participant/Participants.java
> +    public static final String ENTIRE = "all";
all은 view에 연관이 있는 값이 아닐까요? 🤔 
현재는 view의 명령어 정책이 변경된다면 model이 영향받겠군요!

view와 관련된 값이 model에 있어도 괜찮을까요!
중요한 비즈니스 로직들이 모여있는 곳은 최대한 외부사항과 격리되면 좋다고 생각해요!
view라는 비교적 변경이 자주 일어나는곳에 의해 model이 변경되는 것은 좋지 않다는 의미죠 😃

2024-02-29 00:31 UTC, Gomding commented on src/main/java/model/participant/Participants.java
> +    private final Map<Participant, Position> participants;
해당 부분은 Map으로 구현해주신 이유가 궁금해요!

Participant 객체가 Position을 가지는 방법도 있어보여서요 😃

2024-02-29 00:31 UTC, Gomding commented on src/main/java/model/position/CachedPosition.java
> +    private static final Map<Integer, Position> positions = new HashMap<>();
Position 객체를 미리 생성해두고 재사용 👍 👍 👍 

해당 부분은 Position 클래스 내에서 구현해줘도 괜찮지않을까요? 🤔 
Position 내부에 있다면 캐싱된 값을 사용한다는걸 바로 눈치챌 수 있다는 장점이 있어요!

2024-02-29 00:31 UTC, Gomding commented on src/main/java/model/result/Rewards.java
> +public class Rewards {
Reward 라는 이름이 사다리 게임에 어울리는지 고민이 됐어요!
한글로는 `보수` 또는 `보상` 이라는 뜻이 될 것같은데
사다리 게임의 결과는 `꽝` `벌칙` 과 같이 부정적인 결과도 존재하죠 😃 

더 적절한 이름은 없을까요 🤔

2024-02-29 00:31 UTC, Gomding commented on src/main/java/view/InputView.java
> +        System.out.println(System.lineSeparator() + INPUT_LADDER_HEIGHT);
System.lineSeparator 사용 👍

2024-02-29 00:31 UTC, Gomding commented on src/test/java/model/ladder/LadderGameTest.java
> +    @DisplayName("전체 참가자들의 결과를 알 수 있다.")
테스트 이해를 돕기위해 친절한 주석 사용 💯 💯 💯 💯  

들여쓰기만 조절해주면 더 보기좋겠어요 😄

2024-02-29 00:31 UTC, Gomding commented on src/main/java/controller/LadderController.java
> +        Results results = new Results(inputView.inputResults());
버그가 있어요!

참가자 수 만큼 Result를 입력하지 않아도 정상처리 되는군요 😱 
이후 Result가 없는 참가자의 결과를 보려고 하면 알수없는 예외가 발생하면서 서비스가 종료되고있어요!

![image](https://github.com/woowacourse/java-ladder/assets/57378410/bc65838f-64f8-4c71-8d5c-41a4ae764907)

2024-02-29 02:02 UTC, Ho-Tea commented on src/main/java/model/participant/Participants.java
> +    public static final String ENTIRE = "all";
`all` 이 `Participants`를 의미한다고 생각해서 위와같이 구성했었는데
말씀과 같이 `view`의 명령어 정책이 변경된다면 `model`이 영향을 받고,
현재는 전체를 출력하는 명령어 입력이 `all`이지만 추후에 변경이 충분히 일어날 수 있을 것 같습니다!

반영했습니다! 😊

2024-02-29 02:36 UTC, Ho-Tea commented on src/main/java/model/participant/Participants.java
> +    private final Map<Participant, Position> participants;
`Participants`는 일급컬렉션으로 구성하며, `Participant`와 `Position`이 서로에 대해서 모르게 하여 객체간의 독립성을 높여 결합도를 떨어뜨리고 싶어 위와 같이 구성했습니다!

``` java
// LadderGame
public Result matchResult(Participant participant) {
        return results.getResult(ladder.getEndPositionBy(participants.getPosition(participant)));
    }

// Participants
public Position getPosition(Participant participant) {
        if (participants.containsKey(participant)) {
            return participants.get(participant);
        }
        throw new IllegalArgumentException("존재하지 않는 참가자 입니다.");
    }
```
- 현재는 `LadderGame` -> `Participants에서 메서드 호출` 이러한 순서로 접근하게 되는데,
- `Participant`의 필드로 `Position`이 존재하게 된다면 사다리 게임이 실행될 때,
`LadderGame` -> `Participants에서 메서드 호출` -> `Participant에서 메서드 호출` 이러한 순서로 접근하게 됩니다.


추후에 `Position`에 대한 변경사항이 일어났을 때 현재는 `Participants`의 수정만이 필요하지만,
`Participant`가 `Position`을 갖게 된다면 `Participants` 뿐만아니라 `Participant`의 수정도 필요하다고 생각되어 

**`Participant` 객체가 `Position`을 갖지 않도록 구성했습니다!**

2024-02-29 02:59 UTC, Ho-Tea commented on src/main/java/model/result/Rewards.java
> +public class Rewards {
사실 `Rewards`라는 클래스명과 `ParticipantsResult`라는 클래스명 두개를 굉장히 고민했었는데,
찰리 말씀대로 `Rewards`라는 클래스명보다는 조금 길더라도 직관적인 `ParticipantsResult`로 클래스명 수정했습니다!
(`ParticipantsResult`라는 클래스명은 괜찮을까요..!)

2024-02-29 03:08 UTC, Ho-Tea commented on src/main/java/controller/LadderController.java
> +        Results results = new Results(inputView.inputResults());
꼼꼼하게 예외 상황을 체크하지 못한 것 같습니다...😥
앞으로는  발생할 수 있는 예외상황에 대해 더 고민해보고 구현하겠습니다..!
해당 부분은 바로 수정하겠습니다!

2024-02-29 04:46 UTC, Ho-Tea commented on src/main/java/model/position/CachedPosition.java
> +    private static final Map<Integer, Position> positions = new HashMap<>();
`cache`라는 개념을 `Position` 내부에 위치시키는 것 좋은 것 같습니다!
외부에서는 `Position`값을 캐시에서 가져오는지 새로 생성해서 가져오는지 관심이 없을 것 같아 굳이 `CachedPosition`은 필요하지 않을 것 같아요
감사합니다!

2024-02-29 06:57 UTC, Ho-Tea commented
리뷰해주신 부분들 중에 수정이 필요한 부분은 모두 반영했습니다! 👍
추가적으로 예외가 발생시 예외가 발생하는 지점에서 부터 다시 입력받는 로직도 추가해 보았습니다!

### 새로운 궁금증 🧐

``` java
public class LadderGame {
    private final Ladder ladder;
    private final Participants participants;
    private final Results results;

    ...

    public Result matchResult(Participant participant) {
        return results.getResult(ladder.getEndPositionBy(participants.getPosition(participant)));
    }

    public ParticipantsResult matchAllResults() {
        Map<Participant, Result> rewards = new LinkedHashMap<>();
        for (Participant participant : participants.getParticipants()) {
            rewards.put(participant, results.getResult(
                    ladder.getEndPositionBy(participants.getPosition(participant)))
            );
        }
        return new ParticipantsResult(rewards);
    }
    ...
```
- 해당 `LadderGame` 클래스는 단순하게 `Ladder`와 `Participants`, `Results`를 필드로 담고 있는 객체입니다.
- 이 객체가 하는 일은 필드를 활용하여 각 참가자가 어떤 결과를 가지게 되는지를 반환하는 역할을 하고 있습니다
- 이렇게 `LadderGame`이 하는일은 단순하게 필드로 가지고 있는 객체의 메서드들을 호출하여 다시 인자로 넣어주는 역할만 하고 있는데,
`LadderGame`과 같이 도메인들을 담고있는 새로운 도메인의 구성이 괜찮은 구성인지 찰리의 의견이 궁금합니다!!

**저의 생각**
- `LadderGame` 객체를 통해서 `Controller`를 봤을 때 더 가독성이 높아지는 효과를 얻을 수 있었고,
- `LadderGame`객체가 필드로 가지고있는 객체에 접근하여 수정을 하거나 등의 행동은 없고, 내부 구현을 알지 않아도 되므로 결합도가 올라가지 않아 괜찮은 구성이라고 생각이 됩니다.

2024-02-29 11:33 UTC, Gomding commented on src/main/java/model/participant/Participants.java
> +    private final Map<Participant, Position> participants;
좋은 관점이네요 👍👍👍 

한 단계 더 들어가보면..!!

그럼 Participant 가 Position을 갖게된다면 어떤 장점이 있을까요? 🤔 

객체간의 독립성을 높이는것이 항상 좋다면 모든 객체가 독립적으로 있는것이 좋겠죠..!
그럼에도 우리는 객체끼리 협력하도록 하고
어떤 객체는 다른 객체를 가지고있기도 하죠 ㅎㅎ

어떤 경우에 독립적이어야 하고
어떤 경우에 의존해야하는지 더 명확하게 정의내려볼 수 있겠네요 😃

2024-02-29 11:42 UTC, Gomding commented on src/main/java/model/position/Position.java
> +    private static final Map<Integer, Position> positions = new HashMap<>();
캐시를 Position 안으로 옮겨주셨군요👍 

추가로 상수의 위치도 맞춰주면 화룡점정이겠네요 🐉 

+) 상수의 이름 컨벤션도 맞춰주세요!

++) 상수 이름에는 캐시라는 것을 나타내도 되겠군요 😉 

+++) 비슷한 개념으로는 java의 Integer 객체가 있습니다

아래 테스트를 실행해보시면 -128 ~ 127은 캐시된 객체를 반환하기에
같은 객체를 사용한다는 것을 검증해볼 수 있어요

그 외는 새로 만들기 때문에 다른 객체로 판단하고 있네요 😄 
```java
        assertThat(Integer.valueOf("-128") == Integer.valueOf("-128")).isTrue();
        assertThat(Integer.valueOf("127") == Integer.valueOf("127")).isTrue();
        assertThat(Integer.valueOf("-129") == Integer.valueOf("-129")).isFalse();
        assertThat(Integer.valueOf("128") == Integer.valueOf("128")).isFalse();
```

2024-02-29 11:42 UTC, Gomding commented on src/main/java/model/result/Rewards.java
> +public class Rewards {
저는 좋습니다 😃

2024-02-29 12:14 UTC, Gomding requested changes
안녕하세요 호티!
깔끔하게 리뷰 반영해주셨네요 👍 

몇 가지 더 의견나눠보고 싶은 부분이 있어서 댓글과 코멘트 남겼어요 😄 

궁금한 점 있으면 DM 남겨주세요 🙇

2024-02-29 12:14 UTC, Gomding commented on src/main/java/model/ladder/LadderGame.java
> +public class LadderGame {
> - 해당 LadderGame 클래스는 단순하게 Ladder와 Participants, Results를 필드로 담고 있는 객체입니다.
> - 이 객체가 하는 일은 필드를 활용하여 각 참가자가 어떤 결과를 가지게 되는지를 반환하는 역할을 하고 있습니다
> - 이렇게 LadderGame이 하는일은 단순하게 필드로 가지고 있는 객체의 메서드들을 호출하여 다시 인자로 넣어주는 역할만 하고 있는데,
> - LadderGame과 같이 도메인들을 담고있는 새로운 도메인의 구성이 괜찮은 구성인지 찰리의 의견이 궁금합니다!!
> 
> 저의 생각
> 
> - LadderGame 객체를 통해서 Controller를 봤을 때 더 가독성이 높아지는 효과를 얻을 수 있었고,
> - LadderGame객체가 필드로 가지고있는 객체에 접근하여 수정을 하거나 등의 행동은 없고, 내부 구현을 알지 않아도 되므로 결합도가 올라가지 않아 괜찮은 구성이라고 생각이 됩니다.

`LadderGame 같은 다른 도메인들을 가지는 객체를 구현해도 되는가?` 로 이해했는데 맞을까요?

저는 당연하다고 생각합니다!
LadderGame이 없다면 갈곳 없는 객체들의 협력관계가 Controller 로 침범하겠군요 😱 
LadderGame이 Controller 에 도메인 객체들의 협력관계가 넘어가지 않게 막아주고 있다고 생각해보면 어떨까요? 😄 

LadderGame은 중요한 도메인 객체 역할을 하고있다고 생각합니다 👍

2024-02-29 12:14 UTC, Gomding commented on src/main/java/model/ladder/LadderGame.java
> +        return results.getResult(ladder.getEndPositionBy(participants.getPosition(participant)));
ladder.getEndPositionBy 메서드를 호출할 때 마다 매번 결과를 얻기위해 사다리를 등반하고 있군요 🤔 

사용자가 입력창에서 all을 누르기 전에는 계속 결과를 요청할 수 있는데
매번 등반하기는 아쉽군요 🧗 

한 번 등반하면 결과를 저장해놓거나
모든 결과를 미리 생성해놓고 
재사용하면 어떨까요!

2024-02-29 12:14 UTC, Gomding commented on src/main/java/model/result/Results.java
> +            throw new IllegalArgumentException("결과의 개수와 참가자의 수가 다릅니다.");
저는 예외 발생 시 적절한 액션을 취할 수 있도록 추가 정보를 전달하는것이 좋다고 생각해요!

아래 글을 참고해보면 좋겠어요~
- https://hyeon9mak.github.io/writing-helpful-error-messages/

2024-02-29 12:14 UTC, Gomding commented on src/main/java/model/participant/Participants.java
> +        return participants.keySet().stream().toList();
Stream 생성비용이 불필요하게 발생하겠군요 🤔 
List로 변환할 때 꼭 Stream 생성이 필요했을까요..!

2024-02-29 12:14 UTC, Gomding commented on src/main/java/model/ladder/LadderRow.java
> +        if (position.same(0)) {
두 번 등장하는 0이라는 매직넘버가 어떤것인지 상수로 표현해볼 수 있겠어요 😄

2024-02-29 12:14 UTC, Gomding commented on src/main/java/model/result/Results.java
> +        return results.values().stream().toList();
여기도 동일하게 stream 생성 비용이 발생하는 군요 😄

2024-02-29 12:14 UTC, Gomding commented on src/main/java/model/result/Results.java
> +        this.results = new LinkedHashMap<>();
LinkedHashMap 은 순서를 위해 사용한 구현체였을까요? 😃

2024-03-02 08:51 UTC, Ho-Tea commented on src/main/java/model/result/Results.java
> +            throw new IllegalArgumentException("결과의 개수와 참가자의 수가 다릅니다.");
너무 좋은 기술 블로그 감사합니다!
많은 도움이 되었습니다..!
블로그 참고해서 예외 메세지 형식 전부 수정, 반영했습니다!

2024-03-02 08:58 UTC, Ho-Tea commented on src/main/java/model/participant/Participants.java
> +        return participants.keySet().stream().toList();
가독성 향상의 이유와 제가 약한 부분이라고 생각해 모든 로직을 구성할 때 `stream으로 표현할 수 있지 않을까?` 라는 생각을 가지고 있어 습관적으로 `Stream`을 사용하였습니다
해당 경우에서는 비교적 비용이 크게 발생하는 `Stream`을 굳이 사용할 필요가 없다고 생각됩니다!
해당 부분 수정하였습니다!

2024-03-02 09:00 UTC, Ho-Tea commented on src/main/java/model/result/Results.java
> +        return results.values().stream().toList();
해당 부분도 수정, 반영하였습니다!

2024-03-02 09:06 UTC, Ho-Tea commented on src/main/java/model/ladder/LadderRow.java
> +        if (position.same(0)) {
맞습니다!
다른 개발자가 해당 코드를 바라봤을 때 `0`보다는 조금 더 직관적이게 받아들일 수 있게 표현하는게 맞을 것 같습니다
수정하였습니다!

2024-03-02 09:14 UTC, Ho-Tea commented on src/main/java/model/result/Results.java
> +        this.results = new LinkedHashMap<>();
`LinkedHashMap`을 사용한 이유로 저는 `실행결과`와 `사다리`를 출력할 때 입력된 순서와 동일하게 출력이 이루어져야 한다고 생각해 사용하였습니다!
해당 부분을 `HashMap`으로 바꿔 구성해도 출력할 때 `Position`을 이용하여 출력하면 입력순서와 동일하게 출력이 될 수 있지만, 
해당 경우에는 `HashMap` 대신에 `LinkedHashMap`을 사용해 순서를 재구성해주는 로직을 제거하여 구성할 수 있었습니다!

2024-03-02 09:20 UTC, Ho-Tea commented on src/main/java/model/ladder/LadderGame.java
> +        return results.getResult(ladder.getEndPositionBy(participants.getPosition(participant)));
맞는 말씀입니다..!
제가 처음 저 로직을 구성할 때 생각했던 것은 기존 사다리 게임에서 사용자 하나를 선택할 때 마다 해당 사용자가 순차적으로 어느 행과 열을 거쳐 결과로 도달하는지를 보여주기에 저렇게 결과를 저장하지 않고 메서드를 연쇄적으로 호출한 것 같습니다.
추후에 어느 행과 열을 거쳐 결과에 도달하는지에 대해 필요하게 된다면 그 과정또한 저장하여 재사용하면 좋을 것 같습니다!

수정하였습니다!

2024-03-02 10:10 UTC, Ho-Tea commented on src/main/java/model/ladder/LadderGame.java
> +        return results.getResult(ladder.getEndPositionBy(participants.getPosition(participant)));
우선 게임 결과를 재사용할 수 있게끔 재구성한 `LadderGame` 입니다
``` java
public class LadderGame {
    private final Ladder ladder;
    private final ParticipantsResult participantsResult;

    public LadderGame(Ladder ladder, Participants participants, Results results) {
        this.ladder = ladder;
        this.participantsResult = match(participants, results);
    }

    private ParticipantsResult match(Participants participants, Results results) {
        Map<Participant, Result> rewards = new LinkedHashMap<>();
        for (Participant participant : participants.getParticipants()) {
            rewards.put(participant, results.getResult(
                    ladder.getEndPositionBy(participants.getPosition(participant)))
            );
        }
        return new ParticipantsResult(rewards);
    }

    public Ladder getLadder() {
        return ladder;
    }

    public List<Participant> getParticipants() {
        return new ArrayList<>(participantsResult.getParticipantsResult().keySet());
    }

    public List<Result> getResults() {
        return new ArrayList<>(participantsResult.getParticipantsResult().values());
    }
```
- 찰리가 저번 리뷰에 남겨주신 `의도하지 않은 객체 사용 가능성`을 염두해 처음 생성할 때 바로 `ParticipantsResult`가 유의미한 값을 가질 수 있게끔 초기화 하였습니다.

## 여기서 궁금증이 생겼습니다! 🧐

메서드가 사용되는 곳은 오직 `OutputView`에서 출력을 할때만 사용됩니다
이 때 반환형을 `List<Participant>`와 `Participants` 두개 중 어떠한 것을 반환해야할지 고민이 되었습니다.

``` java
// LadderGame

// List<Participant>를 반환하는 형식
public List<Participant> getParticipants() {
        return new ArrayList<>(participantsResult.getParticipantsResult().keySet());
    }

// Participants를 반환하는 형식
public Participants getParticipants() {
        return new Participants(participantsResult.getParticipantsResult().keySet());
    }
```

- 사용되는 곳은 출력에만 관여되는 부분 뿐이라 객체로 재포장하지 않고 `List<Participant>`로 반환해도 무방할 것 같다는 생각이 들어 `List`를 반환하는 형식으로 구성했습니다!

만약 다른 도메인에서 해당 메서드(`getParticipants()`)를 호출한 후 
`Participants`에 추가적인 로직이 필요하다면 `Participants`를 반환하는 것이 맞다는 생각이 들었습니다. 

하지만 해당 경우에는 `getParticipants()`를 통해서 `Participants`를 반환하게 된다면 다시 `Participants.getParticipants()`를 호출해 `List<Participant>`형태로 변환해야해서 무의미한 과정이라고 생각이 됩니다...!
위와 같은 이유로 `List<Participant>`로 구성하였는데 `List<Participant>`로 반환해도 무방할까요..! 찰리의 의견이 궁금합니다!!

2024-03-02 12:26 UTC, Ho-Tea commented on src/main/java/model/ladder/LadderGame.java
> +public class LadderGame {
`LadderGame이 Controller 에 도메인 객체들의 협력관계가 넘어가지 않게 막아주고 있다` 너무 좋은 말 인것같습니다!
말씀 감사합니다!!

2024-03-02 12:32 UTC, Ho-Tea commented on src/main/java/model/position/Position.java
> +    private static final Map<Integer, Position> positions = new HashMap<>();
`Integer`객체는 캐시된 객체 이외에 객체에 대해서 검증할때는 다른 객체로 판단하는군요!
찰리 덕분에 캐싱에 대해서 더 공부해 볼 수 있었습니다 감사합니다🥹
말씀해주신 부분 반영했습니다!!

2024-03-03 12:23 UTC, Ho-Tea commented on src/main/java/model/participant/Participants.java
> +    private final Map<Participant, Position> participants;
**`Participant`가 `Position`을 갖게된다면 제가 작성한 코드를 제 3자가 봤을 때,
`Participants`가 `Position`을 가지고 있을 때 보다 도메인 로직을 이해하는데 더 순조로울 것 같습니다.**

더 구체적으로 말씀드리자면, `Participant` 가 `Position`을 가지고 있다면,
`LadderGame`에서 특정 `Participant`의 사다리 결과를 알고자 할 때 **구체적인 어떤 로직**
(= 현재는 `Position`이라는 객체를 통해서 결과를 도출해 내는 로직을 의미)을 통해서  
사다리 결과를 도출해내는지 알지 않아도 되고,
단순히 메서드를 호출하면 사다리 결과를 알 수 있다는 점을 통해 제 3자가 도메인 로직을 이해하는데 더 순조로울 것 같습니다
(가독성 향상)

``` java
// 현재 LadderGame -> Participants 가 Position을 갖는 경우
    private ParticipantsResult match(Participants participants, Results results) {
        Map<Participant, Result> matched = new LinkedHashMap<>();
        for (Participant participant : participants.getParticipants()) {
            Position position = ladder.getFinishPositionBy(participants.getPosition(participant));
            matched.put(participant, results.getResult(position));
        }
        return new ParticipantsResult(matched);
    }
```

``` java
// LadderGame -> Participant 가 Position을 갖는 경우
    private ParticipantsResult match(Participants participants, Results results) {
        Map<Participant, Result> matched = new LinkedHashMap<>();
        for (Participant participant : participants.getParticipants()) {
            matched.put(participant, results.getResult(ladder.result(participant)));
        }
        return new ParticipantsResult(matched);
    }
```

이것 이외에도 `Participant`가 `Position`을 갖게 되었을 때 얻을 수 있는 이점으로는 캡슐화를 통해 얻는 이점과 같은 방향임을 생각해 볼 수 있을 것 같습니다!

### 저의 생각! 🧐
- 객체를 독립적으로 유지했을 때의 장점과 객체를 의존관계에 두었을때 얻을 수 있는 장점 모두 존재한다고 생각합니다.
- 사실 객체가 어떠한 경우에 독립적이여야하고 어떠한 경우에 의존해야 하는지에 대한 명확한 기준을 제가 아직은 내리기 어렵지만, 
그 기준을 내리는 근거와 이유로는 한 객체가 어떠한 역할과 책임을 가지고 있는지를 판단하는 것에 따라서 구분된다고 생각합니다!
- 결국 도메인을 분리하고 해당 도메인에 어떠한 역할과 책임을 줄 것인지에 대한 판단과 결정을 더 연습해야 할 것 같습니다..!

2024-03-04 10:00 UTC, Gomding commented on src/main/java/model/participant/Participants.java
> +    private final Map<Participant, Position> participants;
해당 코멘트는 `이런 관점이 있다`이니 호티의 방식이 틀렸다는 말이 아닙니다!!! 😃 
당연히 반영할 필요도 없구요~!

객체간의 의존관계를 어떻게 할지 생각해볼 때
객체의 관점에서 바라보는 방법도 있을것같아요
- 사다리 게임의 참가자(Participant) 자신이 위치를 아는것이 자연스러운가? 아니면 부자연스러운가?
- 결과(Result)는 자신의 위치를 아는것이 자연스러운가? 부자연스러운가?

사다리 게임에서는 참가자나 결과가 사다리게임을 세팅할 때 위치가 고정되어 움직이지 않기때문에
어떻게 생각하냐에 따라 구현방식이 달라질것같아요

또 다른 관점에서 보자면
Position으로 검색이 가능하게 해주세요 라고 했을 때 현재 Map이라는 자료형이 유효할지도 고민해볼 수 있겠네요 😃

2024-03-04 10:08 UTC, Gomding commented on src/main/java/model/ladder/LadderGame.java
> +        return results.getResult(ladder.getEndPositionBy(participants.getPosition(participant)));
저는 호티와 동일하게 List<Participant> 로 반환해줘도 된다고 생각해요~!
Participants 로 감싸서 주면 크게 의미가 없다고 생각해요!

이때 메서드 이름은 조금 변경해주면 좋겠어요!

List<Participant> 라는 타입으로 반환해주는 메서드이니 `toList` 와 같은 이름으로 지어준다면
사용하는 곳에서 어떤 타입으로 반환되는지 메서드 내부를 살펴보지않아도 알 수 있다는 장점이 있어요!

```java
public List<Participant> toList() {
    return new ArrayList<>(participantsResult.getParticipantsResult().keySet());
}

// 사용 시
participants.toList();
```

2024-03-04 10:09 UTC, Gomding commented on src/main/java/model/participant/Participants.java
> +        return participants.keySet().stream().toList();
좋은 생각이네요 👍 
Stream의 생성비용을 제거하는것 좋습니다~

2024-03-04 10:30 UTC, Gomding approved these changes
안녕하세요 호티! 🙇 
다양한 의견과 함께 코드를 많이 변경해봤네요!
꼼꼼한 테스트도 너무 좋았습니다 💯 

몇가지 코멘트 남기면서 사다리 게임은 이만 merge 하겠습니다 🙏 
다음 미션도 파이팅입니다 🔥

2024-03-04 10:30 UTC, Gomding commented on src/main/java/model/participant/Participants.java
> +        return new ArrayList<>(participants.keySet());
Stream 사용은 없애주셨지만 약간 아쉬운 부분이 있어요!
불변 컬렉션으로 반환하는 것이 어떤것인지 + 어떤 장점이 있는지 알아보면 좋겠어요 😃 

- [방어적 복사와 Unmodifiable Collection](https://tecoble.techcourse.co.kr/post/2021-04-26-defensive-copy-vs-unmodifiable/)
- [UnmodifiableList은 만능이 아니다. / 방어적 복사](https://www.blog.ecsimsw.com/entry/unmodifiableList%EC%9D%80-%EB%A7%8C%EB%8A%A5%EC%9D%B4-%EC%95%84%EB%8B%88%EB%8B%A4)

2024-03-04 10:30 UTC, Gomding commented on src/main/java/view/OutputView.java
> +import model.result.Results;
view에서 model에 대한 의존을 끊어보는건 어떻게 생각하시나요? 😄 

현재는 view에서 model 패키지의 객체들을 직접 참조하고 있는데요!
사실 view는 변화가 많은 부분이라 자칫하면 model에게 영향이 갈 수도 있어요

또는 view에서 model 객체 내부의 값을 수정해버렸을때.. 또 다른 문제로 이어질수도 있죠

사다리게임이라는 작은 서비스 + 호티가 view와 model은 모두 작성하고 있어 현재는 크게 문제될 것은 없어보여요.
하지만 다른 개발자가 참가한다면 어떤일이 생길지 예상할 수 없죠 ㅎㅎ..

물론 분리했을 때 생기는 단점도 있을거에요!

사다리게임 미션에서는 view에서 model을 참조하도록 했지만
다음 미션에서는 둘을 분리해보는 것도 도전해보고
어떤 장단점이 있는지 확인해보면 좋겠어요!

2024-03-04 10:30 UTC, Gomding commented on src/main/java/model/result/Result.java
> +    static final String NOT_ALLOWED_NULL_EMPTY_RESULT = "결과의 이름이 없거나 공백으로만 이루어져 있는 경우 결과 생성이 불가합니다.";
해당 상수는 위치를 생성자 위로 배치해도 되겠어요 🤔

2024-03-04 10:30 UTC, Gomding commented on src/main/java/model/result/Result.java
> +    }
위 생성자를 record에서는 이렇게 표현이 가능하군요 😃 

```java
    public Result {
        validateResultNullAndBlank(name);
    }
```

2024-03-04 10:30 UTC, merged