[2단계 - 사다리 게임 실행] 테드(김규) 미션 제출합니다.
woowacourse/java-ladder pull request #388
Opened 2024-02-29 07:41 UTC by Kimprodp

안녕하세요, 피케이😊

사다리 게임의 2단계 사다리 실행 미션 진행하여 리뷰 요청 드립니다.

1단계에서 코멘트 주신 부분 반영하여 작업했습니다.

다음은 작업하면서 생긴 코멘트와 이전 PR의 코멘트에 대한 답변입니다.

- **Getter**의 기준 : 메서드 순서 정렬을 하다 보니, 단순히 변수를 `returen`하는 **Getter**외에 변수의 `size`를 반환하거나 변수가 `List`일 경우  특정 인덱스 값을 반환하는 메서드의 내부 로직은 단순하기에 메서드의 위치를 **Getter**와 함께 두어야 하는지 고민했습니다. 고민한 결과 테스트에 포함되는지 여부를 기준으로 판단하여 위치하기로 했습니다. 일반적인 **Getter**는 테스트에 포함되지 않으니 테스트에 포함되었다면, 중요도가 있는 메서드기에 **Getter**로 분류하지 않았습니다. 피케이의 생각은 어떠신가요?
- **접근제어자**에 대한 생각 : 저는 `private`보다 좁은 범위의 접근제어자를 잘 사용하지 않았습니다. 이번 미션을 진행하면서 `Line` 클래스의 특성 상 제공되는 API가 많기 때문에 어디서나 생성해서 쓰이지 못하도록 하고 싶었습니다. `Line`의 API 중 정보를 얻는 기능에 대해서만 공개로 제공하고, `Line`을 생성하고 값을 설정하는 부분은 `LineGenerator`를 통해서만 할 수 있도록 했습니다. 아직 익숙하지 않아 저만의 특정한 컨벤션은 미션을 진행하며 다양한 접근제어자를 활용해 보면서 점차 기준을 세워야 할 것 같습니다. 피케이의 접근제어자에 대한 컨벤션은 어떻게 되나요?

2024-03-01 21:20 UTC, pkeugine requested changes
안녕하세요 테드!
정말 많은 작업을 해주셨네요. step 1 때도 그랬지만 이번엔 그 때보다도 더 테스트가 잘 만들어져 있다는 생각을 했습니다.
그런데 한 편으로는 테스트 외에도 너무 많은걸 만들려고 하지 않았나 하는 생각도 들었어요.

리뷰 남겨봤는데 한 번 읽어보시고 이해 안되는게 있다면 언제든지 DM 주세요. 리뷰의 양이 조금 많은데 다 처리하지 못할 것 같다 싶으면 그것도 언제든지 얘기해주세요. 우선순위를 정해서 진행해보아요!

2024-03-01 21:20 UTC, pkeugine commented on README.md
> +  - [x] 저장된 결과가 없을 경우 예외를 발생시킨다.
요구사항 관리 볼 때마다 놀랍네요!

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/contorller/LadderController.java
> +    }
`initializeGame` 메서드가 ladderGame 이라는 필드를 초기화하고 끝난다면 생성자에서 바로 해줘도 좋을 것 같아요.
그리고 생성자 관련 로직에서는 `this` 를 붙이는거 어떤가요?

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/game/GameExecutor.java
> +public class GameExecutor {
`GameExecutor` 라는 클래스를 별도로 만든 이유가 있나요?

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/game/GameExecutor.java
> +        validateConsistentSize(users, ladder, prizes);
`validateResource` 도 아래의 `validateConsistentSize` 처럼 무엇을 검증하는지 알려주면 좋겠네요.

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/game/GameExecutor.java
> +    }
테드가 만들어주신 구조로 봤을 때 `GameExecutor` 클래스에서는
1. `validateGameEnvironment` 메서드를 먼저 실행하고
2. 그 뒤에 `execute` 메서드를 실행해야해요.

그렇다면 이 두 메서드를 분리해서 외부에서 각각 순서대로 실행시키도록 하지 않고 아예 `execute` 가 `validateGameEnvironment` 를 하도록 만드는건 어떨까요?

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/game/GameExecutor.java
> +        }
바로 위의 검증에서는 GameResource 에서 가져오는 '사용자', '사다리' 상수를 사용하는데 밑에서는 사용하지 않네요. 예외 메시지도 추출되어 있지 않구요 🤔

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/game/GameExecutor.java
> +    }
저번 step 에서 테드의 메서드 순서 컨벤션에 대해 얘기해봤었죠.
private 메서드들끼리도 순서를 정해서 나열해보는건 어떨까요?
다른 곳들은 나름 정리가 된 것 같은데 GameExecutor 쪽은 섞여있는 것 같아요

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/game/GameResource.java
> +    private Ladder ladder;
```suggestion
    private static final String SYSTEM_ERROR_ALREADY_EXIST = "[ERROR] 게임 리소스에 %s가(이) 이미 존재하는 경우 변경할 수 없습니다.";
    private static final String SYSTEM_ERROR_ADD_NULL = "[ERROR] 게임 리소스에 추가할 %s가(이) 존재하지 않습니다.";

    private Users users;
    private Ladder ladder;
```
매의 눈 🦅

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/game/GameResult.java
> +    private final HashMap<User, Prize> result;
```suggestion
    private final Map<User, Prize> result;
```
인터페이스를 적극 활용해보아요!

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/game/GameResult.java
> +            throw new IllegalArgumentException("[ERROR] 저장하려는 당첨품이 존재하지 않습니다.");
에러 메시지를 상수화 하는 조건이 궁금해요. 다른 클래스는 보면 에러 메시지를 상수화 하고, 더 나아가 `사용자`, `당첨품` 과 같은 이름도 상수화 했어요. 그런데 여기는 그대로 로직 안에 들어가 있네요.

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/game/GameResult.java
> +    }
테드가 이번 step 에서 작성하신 로직을 보면 일관성이 조금 없다는 생각이 들어요.
1. `validate` 메서드를 재사용 하기 위해 검증 대상을 Object 타입으로 파라미터에서 받는 클래스도 있어요. 그런데 여기는 도메인마다 하나씩 메서드를 만들어주셨네요. 그 이유가 궁금해요.
2. not null 을 검증하는 메서드의 이름이 여기는 `validateNotEmptyXXX` 형태인데, 다른 곳에는 `validateNull` 이라는 이름도 있어요.
3. null 임을 검증하는 메서드의 이름은 다른 클래스에서 위의 두개와는 또 다른 표현인 `validateAlreadyExist` 라는 이름을 가질 때도 있어요. 그런데 `GameResult` 에서는 그 이름의 메서드가 map 안에 prize 가 있는지 검증해요.

이러면 메서드를 분리해서 이름을 붙이고 재사용성을 고려하는 이점이 있을까요? 매번 다르게 쓰이는 이름이라 무엇을 검증하는지 바로 파악하기 힘들어요. 그리고 다른 사람은 어디에 재사용 가능한 메서드가 있고, 어디에 각각의 도메인마다 메서드가 존재하는지 매번 확인해야해요.

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/resource/direction/Direction.java
> +    NEUTRAL;
방향이라는 enum 을 만든김에 그... 방향을 맞춰보면 어떨까요? :)
```suggestion
public enum Direction {

    LEFT,
    NEUTRAL,
    RIGHT
```

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/resource/direction/Direction.java
> +    }
1. `getRightOrNeutral` 이라는 이름에 '둘 중 하나를 랜덤으로 가져올거야' 라는 의미를 포함시키면 좋겠어요.
2. RIGHT, NEUTRAL 이라는 값을 가진 배열을 상수화 할 이유가 없다고 생각이 드는데 테드는 어떤가요? 이미 그 둘이 스스로를 잘 표현해요.
3. `RandomLineGenerator` 라는 클래스가 있으니 random 한 요소는 그 쪽에서 관리하는게 더 직관적이지 않을까요?

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/resource/ladder/Ladder.java
> +import ladder.domain.resource.line.Line;
domain 내에서 resource 라는 분류를 시도해본 것 좋네요! 👍 
패키지 분리리를 어떻게 하면 관리하기 편할지 고민해보는 것도 좋을 것 같아요.
저라면 game-resource 로 구분하진 않을 것 같아요 🤔 왜냐하면 game 패키지 내의 로직이 resource 와 강하게 결합되어 있어서 사실상 함께 쓰이기 때문이에요.

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/resource/ladder/Ladder.java
> +        return lines.get(DEFAULT_INDEX).getSize();
이건 제 개인적인 생각인데
사다리 너비를 구하는 로직에서 사용되는 임의의 숫자 '0' 이 이름이 필요할까요? 바뀔 일도 거의 없을 거 같아서 저라면 그냥 0 을 바로 넣어줬을거에요. 더 나아가 `DEFAULT_INDEX` 라는 이름은 그 의미를 단번에 이해하기엔 조금 보편적인 이름이라는 생각도 들고요.
하지만 이건 저와 반대하는 의견도 꽤 있는 편이라 참고용으로만 봐주세요!

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/resource/ladder/Ladder.java
> +    }
> 고민한 결과 테스트에 포함되는지 여부를 기준으로 판단하여 위치하기로 했습니다. 일반적인 Getter는 테스트에 포함되지 않으니 테스트에 포함되었다면, 중요도가 있는 메서드기에 Getter로 분류하지 않았습니다.

우선 가장 먼저 '테스트는 프로덕션 코드에 영향을 주어선 안된다' 는 생각이 들어요. 물론 테스트 해봐야겠다는 생각이 드는 로직이라면 분명 그건 단순한 getter 가 아닌 비즈니스 로직에 더 가까울 가능성이 높겠죠. 하지만 그것과는 별개로 테스트는 메서드의 순서에도 영향을 주어선 안된다고 생각해요.

그리고 그 기준이 조금은 복잡하고, 팀원들끼리 의견이 다를만한 기준이에요. 누군가는 테스트가 필요하지 않다고 생각하는 비즈니스 로직일 수도 있고, 테스트가 누락되었을 수도 있으니까요. 그리고 팀원들이 다 동의한다고 하더라도 시간이 지나면서 안 지켜질 가능성이 굉장히 높아보이는 기준이에요.

> 피케이의 생각은 어떤가요

코드/기준은 명확하고, 쉽고, 직관적이면서 통일성을 가진게 좋은 코드라고 생각해요. 그게 유지보수와 직결되는 요소니까요. 그냥 `필드 값을 바로 빼오는 메서드` 라면 getter, 그렇지 않다면 getter 가 아닌 것으로 구분하면 직관적일 것 같아요. 당연히 그런 메서드는 getter 가 아니니까 꼭 getter 와 함께 둘 필요 없구요. 그렇기 때문에 저는 `get` 이라는 표현은 `getter` 외에는 절대 사용하지 않아요. `set` 도 그렇구요. 테드도 한 번 이 컨벤션을 적용해보는건 어떨까요? 이건 근데 반대하시는 분들도 있어요. `get` 외에는 적절한 단어가 없을 때도 있다는 이유에서요.

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/resource/ladder/Ladder.java
> +    }
파라미터명을 필드명과 동일하게 사용하는건 지양해주세요. 헷갈리기 딱 좋은 방식이거든요!

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/resource/ladder/LadderGenerator.java
> +            lineGenerator.insertDirectionIntoLine(line, width);
line 이 direction 을 갖게 되는 행위를 lineGenerator 가 아닌 line 이 직접 하게 해보죠!

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/resource/ladder/LadderGenerator.java
> +    }
이건 Ladder 쪽에서 하는게 더 좋지 않을까요? 지금 구조상 LadderGenerator 를 사용해야지만 Ladder 를 만들 수 있지만 Ladder 쪽에 있어야 다른 생성 방식에 쉽게 대응할 수 있을 것 같아요.

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/resource/line/Line.java
> +    }
> 저는 private보다 좁은 범위의 접근제어자를 잘 사용하지 않았습니다.

private 보다 '좁은' 범위의 접근제어자라면 어떤 것을 말하시는걸까요? package-private 은 private 보다 범위가 '넓다'고 느껴져서요! '좁다'는게 어떤 의미에서 좁은건지 궁금해요. package-private 메서드를 테스트에서 호출할 수 있어서일까요?

> 이번 미션을 진행하면서 Line 클래스의 특성 상 제공되는 API가 많기 때문에 어디서나 생성해서 쓰이지 못하도록 하고 싶었습니다. Line의 API 중 정보를 얻는 기능에 대해서만 공개로 제공하고, Line을 생성하고 값을 설정하는 부분은 LineGenerator를 통해서만 할 수 있도록 했습니다.

좋은 시도입니다. 그런데 package-private 접근제한자에는 한 가지 함정이 있어요. 같은 패키지에 있는 public 한 클래스의 public 한 메서드에서 노출시킬 수 있다는 점이에요. private 한 메서드에서만 사용될 수 있다면 진정한 의미의 'package-private' 이 될 것 같은데 말이죠 🤔 그래서 테드의 코드에서도 `RandomLineGenerator` 때문에 사실상 public 생성자를 열어둔 것과 다를바 없는 방식으로 사용돼요 : 
```java
public class RandomLineGenerator implements LineGenerator {

    @Override
    public Line generateLine() {
        return new Line();
    }
```
 그냥 Generator 를 거쳐간다는 과정만 추가되었을 뿐이에요. 그렇다면 그냥 생성자를 public 하게 열어두는 것이 좋지 않을까 싶네요.

또한, Line 의 `addDirection` 을 package-private 처리 했지만 이 역시 `RandomLineGenerator` 의 `insertDirectionIntoLine` -> `setDirection` 메서드로 인해 외부에서 실행할 수 있어요. 그러면 이건 구조에 대해 다시 한 번 생각해봐야한다는 신호가 될 수 있어요. `public 으로 열고 그 자체를 호출하는 것과 다를바 없다` 는 말은 다시 말해 `로직을 다른 곳에 배치해서 불필요한 과정이 하나 추가되었다` 는 의미가 될 수 있거든요.

`addDirection 메서드는 그래도 RandomLineGenerator 에서 메서드 호출 전후로 로직이 있지 않나?` 라는 반론이 있을 수 있어요. 그런데 Line 을 메서드 파라미터로 받고 있어요. 파라미터로 받은 객체를 수정하기보단 이왕이면 Direction list 를 반환해서 Line 에 넣어주는게 '테스트하기 좋은 구조' 이기도 하고, 외부에서 그 값을 변경하는 것을 볼 수 있기 때문에 더 직관적이지 않을까 싶어요!

> 아직 익숙하지 않아 저만의 특정한 컨벤션은 미션을 진행하며 다양한 접근제어자를 활용해 보면서 점차 기준을 세워야 할 것 같습니다. 피케이의 접근제어자에 대한 컨벤션은 어떻게 되나요?

일단 package-private 을 프로덕션 코드에서는 사실상 사용하지 않아요. 클래스 단위로도 사용하지 않고, 메서드 단위로도 사용하지 않아요. 앞서 제가 말한 그 이유 때문이에요. package-private 은 사용 방식상 허점이 있어서, 결국 다른 public 한 클래스가 열어주면 외부에서 사용할 수 있거든요. 이런 요소 때문에 제가 작성한 구조를 다시 고민해보는 시간을 갖게 되더라구요.

그리고 코드는 패키지가 변경될 때가 은근 자주 있어요. 그럴 때마다 package-private 이 발목을 크게 붙잡을 수 있어요. 오히려 유지보수 할 때 엄청 귀찮아지는거죠.

하지만 그럼에도 사용했던 적이 있어요. 라이브러리를 작성할 때 사용했는데요, class 를 package-private 으로 나타냈어요. 개발자가 직접 사용할 클래스는 public, 그리고 그 public 한 클래스 내에서 사용되는 클래스를 package-private 하게 한거에요. 그런데 이러면 앞서 말한 허점이 그대로 적용될 수 있죠? 그래서 개발자에게 반환할 클래스는 public 하게 두고, 정말 개발자가 만질 일이 없는 (만져서는 안되는) 클래스를 package-private 으로 뒀어요. 라이브러리를 사용할 때 개발자가 몰라도 되고, 신경 쓸 필요가 전혀 없는 클래스들이요! 예를 들어 우리가 assertJ 라는 테스트 라이브러리를 쓸 때 `assertThat` 의 사용법만 알면 되지 그 구현 자체를 알 필요는 없죠. 하지만 assertJ 라이브러리 개발자는 유지보수성을 위해 객체지향적으로 개발을 해야해요. 그러면 클래스 수가 늘어날 수 밖에 없는데요. `assertThat` 만 알면 되는 개발자로부가 내부 구현에 필요한 클래스를 호출하지 못하게 하면서 클래스 분리를 할 수 있어요. 이렇게 저는 라이브러리 만들 때 사용했습니다 ㅋㅋㅋ

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/resource/line/Line.java
> +        directionsInfo.add(direction);
Line 객체가 생성될 때 비어있는 리스트를 필드로 가진 다음 매번 `addDirection` 을 호출해서 채워주는 구조보다 외부에서 원하는 Direction list 를 생성자에 바로 넣어주는게 더 유연한 구조인 것 같은데 테드는 어떻게 생각하시나요?

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/domain/resource/line/RandomLineGenerator.java
> +public class RandomLineGenerator implements LineGenerator {
다른 코멘트에도 남기긴 했는데 `RandomLineGenerator` 가 막상 랜덤하게 Line 을 만드는 로직이 없는 것 같아요.
다른 클래스에게 그 역할을 위임하기도 하고, 위임할 때 사용하는 로직 그 어디에도 'random' 하다는 내용이 없어요.

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/view/Formatter.java
> +    private static final String NEW_LINE = "\n";
`System.lineSeparator()` 를 사용하면 애플리케이션을 실행하는 유저의 OS 에서 사용하는 line separator 를 사용할 수 있어요 :)

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/view/Formatter.java
> +    private static final int MAX_LENGTH = 5;
이번 step 으로 오면서 프로젝트에 필드/상태가 없는 클래스가 꽤 많아졌어요. 그런데 그런 클래스의 인스턴스를 생성하고 사용하고 계시는데 이런 결정을 한 이유가 있을까요?

1. 이런 클래스를 static 한 유틸 클래스로 사용하면 좋을 것 같아요. InputView, OutputView 두 개 정도는 객체를 생성해서 controller 에 넣어줘도 괜찮다고 생각해요. 그건 mvc 구조를 학습하기 위해 내린 판단이라고 볼 수 있거든요. 하지만 나머지는 그렇지 않아요.
2. 만약 static 한 유틸 클래스로 만드는 것 외에 다른 방식을 찾으신다면
    * singleton 으로 만들어서 사용할 방법을 고민해보거나
    * 각각 올바른 객체에 로직을 분배합시다 (Formatter 외 다른 상태없는 도메인 클래스도 분배 가능할 것 같아요)

2024-03-01 21:20 UTC, pkeugine commented on src/main/java/ladder/view/OutputView.java
> +    private final Formatter formatter = new Formatter();
생성자를 사용하지 않은 이유가 있나요? 특히 다른 곳에서는 이런 경우에 직접 default 생성자를 선언해서 초기화를 해주셔서요.

2024-03-01 21:20 UTC, pkeugine commented on src/test/java/ladder/domain/game/GameExecutorTest.java
> +    GameResult gameResult;
테스트에서는 접근제한자를 넣지 않은 이유가 있나요?

2024-03-01 21:20 UTC, pkeugine commented on src/test/java/ladder/domain/game/GameExecutorTest.java
> +        HashMap<User, Prize> result = gameResult.getAllResult();
```suggestion
        Map<User, Prize> result = gameResult.getAllResult();
```

2024-03-01 21:20 UTC, pkeugine commented on src/test/java/ladder/domain/game/GameResourceTest.java
> +    @Test
step 1 때도 느꼈지만 테스트 정말 꼼꼼하게 작성하시네요!!!! 👍

2024-03-01 21:20 UTC, pkeugine commented on src/test/java/ladder/domain/game/ResourceGenerator.java
> +public class ResourceGenerator {
ResourceGenerator 라면 game 패키지보단 resource 패키지가 더 어울릴 것 같아요.
intelliJ 와 github 를 오가며 리뷰하는데 무의식중에 github 에서 resource 패키지만 보면서 '왜 없지 그 사이에 새로운 commit push 하셨나' 하는 생각을 계속 했어요 😂

2024-03-01 21:20 UTC, pkeugine commented on src/test/java/ladder/domain/game/ResourceGenerator.java
> +    public static Users generateUsersWithCount(int count) {
```suggestion
    public static Users generateUsers(int count) {
```
꼭 적지 않아도 되는 내용은 과감하게 없애도 메서드가 어떻게 행동할지 이해할 수 있을 것 같아요!

2024-03-01 21:20 UTC, pkeugine commented on src/test/java/ladder/domain/game/ResourceGenerator.java
> +    }
여기선 오히려 height 가 2 인게 이름에서 드러났으면 하는 생각이에요...!

2024-03-01 21:20 UTC, pkeugine commented on src/test/java/ladder/domain/resource/line/RandomLineGeneratorTest.java
> +    void insertDirectionIntoLine_afterLeftDirection_expectedRightOrNeutral() {//수정 필요
불필요한 주석은 최대한 빼주세요!

2024-03-03 12:49 UTC, Kimprodp commented on src/main/java/ladder/domain/game/GameExecutor.java
> +public class GameExecutor {
원래는 게임의 전체적인 로직을 담당하는 `LadderGame`과 실행 로직만을 지니는 `GameExecutor`로 기능을 분리하려 했으나, 하다보니 과하게 분리된 감이 있는 것 같네요. 오히려 로직이 더 복잡해지고 가독성이 떨어지는 것 같아 `LadderGame `클래스에서 게임 실행하는 로직까지 수행하는 것으로 변경했습니다.

2024-03-03 12:50 UTC, Kimprodp commented on src/main/java/ladder/domain/game/GameExecutor.java
> +    }
외부에서는 실행 메서드만 호출하면 내부적으로 환경 검증을 진행하고 게임 로직을 실행하도록 변경했습니다!

2024-03-03 12:51 UTC, Kimprodp commented on src/main/java/ladder/domain/game/GameExecutor.java
> +        }
예외 메시지는 상수화 하지 않는 것으로 통일 하는게 좋다고 판단되어 모두 동일하게 변경하였습니다!

2024-03-03 12:51 UTC, Kimprodp commented on src/main/java/ladder/domain/game/GameExecutor.java
> +    }
private 메서들 끼리도 순서가 정해지도록 전체적으로 다시 확인해서 수정했습니다.

2024-03-03 12:53 UTC, Kimprodp commented on src/main/java/ladder/domain/game/GameResult.java
> +            throw new IllegalArgumentException("[ERROR] 저장하려는 당첨품이 존재하지 않습니다.");
동일한 구조를 지니는 검증 로직을 여러개 만들 필요가 없을 것 같아서 재사용되는 메서드는 메시지를 상수화 시키면서 구현해보려 했는데 통일성 없게 구현하다 보니 가독성만 떨어지는 것 같네요. 우선은 에러메시지 자체는 상수화 하는 것 보단 로직에 바로 표현되는 것이 더 가독성이 좋다고 판단되어 모든 에러메시지는 상수화 하지 않는 것으로 통일했습니다!

2024-03-03 12:54 UTC, Kimprodp commented on src/main/java/ladder/domain/game/GameResult.java
> +    }
로직에서 사용되는 메서드명도 역할이 비슷한 경우 네이밍을 맞출 수 있도록 변경했습니다.

2024-03-03 12:55 UTC, Kimprodp commented on src/main/java/ladder/domain/resource/direction/Direction.java
> +    }
`RandomLineGenerator`에서 `Direction`을 가져와서 랜덤으로 선택될 수 있도록 변경했습니다.

2024-03-03 12:56 UTC, Kimprodp commented on src/main/java/ladder/domain/resource/ladder/Ladder.java
> +import ladder.domain.resource.line.Line;
game과 resource의 결합도가 강하여 패키지를 우선은 분리해서 가는 것으로 변경했습니다.

2024-03-03 12:57 UTC, Kimprodp commented on src/main/java/ladder/domain/resource/ladder/Ladder.java
> +        return lines.get(DEFAULT_INDEX).getSize();
인덱스 값 0은 상수화 메시지로 표현하는 것 보다 그 자체로 더 가독성이 있다고 판단되어 상수화 하지 않는 것으로 변경했습니다.

2024-03-03 13:00 UTC, Kimprodp commented on src/main/java/ladder/domain/resource/ladder/Ladder.java
> +    }
getter에 대한 기준 "필드 값을 바로 빼오는 메서드 라면 getter, 그렇지 않다면 getter 가 아닌 것으로 구분" 명확하고 간단해서 해당 컨벤션을 적용하여 메서드의 위치를 조정했습니다. get 이라는 표현은 getter 외에서는 사용하지 않는 것이 좋아보이지만 대체할 수 있는 단어가 생각나지 않을때는 어쩔 수 없이 사용하게 되는 것 같아 아쉽네요..

2024-03-03 13:00 UTC, Kimprodp commented on src/main/java/ladder/domain/resource/ladder/Ladder.java
> +    }
파라미터명과 동일하게 사용되는 모든 필드명을 수정했습니다.😊

2024-03-03 13:02 UTC, Kimprodp commented on src/main/java/ladder/domain/resource/ladder/LadderGenerator.java
> +            lineGenerator.insertDirectionIntoLine(line, width);
밑의 코멘트 에서 말씀 주신 "외부에서 원하는 Direction list 를 생성자에 바로 넣어주는게 더 유연한 구조인 것 같다." 이 부분이 저도 맞다고 판단되어` List<Direciotn>`을 `Line`의 생성자에 넣어 생성하는 것으로 변경했습니다!
`Line`의 생성자에서는 필드에 등록 전 방향 로직에 대한 검증을 수행하고 저장 합니다.

2024-03-03 13:03 UTC, Kimprodp commented on src/main/java/ladder/domain/resource/ladder/LadderGenerator.java
> +    }
`Ladder`가 가진 값을 `LadderGenerator`에서 검증하는 건 잘못된 판단 이였던 것 같습니다. `Ladder`에서 자체적으로 검증하도록 변경했습니다.

2024-03-03 13:06 UTC, Kimprodp commented on src/main/java/ladder/domain/resource/line/Line.java
> +    }
`default `패키지를 `private`보다 좁다고 표현한 것은 제가 헷갈렸던 것 같습니다. 설명해주신 부분을 잘 읽어보니 패키지로 접근 제한을 해도 결국에는 다 노출될 수 밖에 없는 구조로 구현했던 것 같습니다. 이번에 `LineGenerator`와 `Line `클래스를 리팩터링 하면서 접근 제한자에 대한 부분도 `public`으로 변경했습니다. 피케이의 생각을 경험과 함께 너무나 자세하게 설명해주셔서 이해가 잘 되었습니다. 정말 감사해요!😁

2024-03-03 13:07 UTC, Kimprodp commented on src/main/java/ladder/domain/resource/line/Line.java
> +        directionsInfo.add(direction);
위에서 말씀 드린 것처럼 피드백 주신 구조로 변경했습니다!

2024-03-03 13:08 UTC, Kimprodp commented on src/main/java/ladder/domain/resource/line/RandomLineGenerator.java
> +public class RandomLineGenerator implements LineGenerator {
`RandomLineGenerator`에서 `Direction`을 가져와서 랜덤으로 선택될 수 있도록 변경했습니다.

2024-03-03 13:08 UTC, Kimprodp commented on src/main/java/ladder/view/Formatter.java
> +    private static final String NEW_LINE = "\n";
OS 별로 Line Separator를 사용할 수 있다는 건 몰랐네요. 감사합니다!

2024-03-03 13:11 UTC, Kimprodp commented on src/main/java/ladder/view/Formatter.java
> +    private static final int MAX_LENGTH = 5;
현재 구현하는 프로그램이 그렇게 크지 않아 static을 사용하여도 메모리에 지장이 없겠지만, 사용하지 않도록 습관을 들이기 위해서 최대한 지양하고 있습니다. 그런데 필드가 없는 클래스의 인스턴스를 계속 생성하는 것도 좋아 보이진 않네요. 말씀해주신 static 외에 싱글톤으로 만들어서 적용해보았습니다.

2024-03-03 13:13 UTC, Kimprodp commented on src/main/java/ladder/view/OutputView.java
> +    private final Formatter formatter = new Formatter();
생성자 초기화와 필드 초기화가 섞여있어 통일성이 떨어졌던 것 같네요. 초기화 순서가 필요 없는 필드에 대해서는 필드 초기화 하는 것으로 통일하였습니다.

2024-03-03 13:18 UTC, Kimprodp commented on src/test/java/ladder/domain/game/GameExecutorTest.java
> +    GameResult gameResult;
`Junit5 `부터는 접근 제한자를 넣지 않아도 되기 때문에 기본적으로 `package-private` 를 사용하는 것으로 알고 있습니다.
오히려 `public`이나 다른 접근 제한자를 사용한다면 의도가 있어야 한다고 생각되어 테스트에서는 `package-private` 접근 제한자를 설정했습니다.

2024-03-03 13:21 UTC, Kimprodp commented
꼼꼼하게 피드백 주신 덕분에 부족한 부분을 인지하고 채워갈 수 있었습니다. 피케이 늦은 시간인데도 정말 자세히 봐주시고 질문에 답변도 잘 해주셔서 너무 감사해요.😊 코멘트에 대한 부분은 모두 반영 후 답글 달았습니다. 다시 한번 리뷰 요청드립니다!

2024-03-04 16:48 UTC, pkeugine commented on src/main/java/ladder/domain/line/Line.java
> +    }
메서드에서 null 을 반환하는 것은 최대한 지양하면 좋을 것 같아요. null 을 활용해서 로직을 처리하다보면 NPE 를 발생시킬 가능성이 높거든요!

2024-03-04 16:48 UTC, pkeugine commented on src/main/java/ladder/domain/resource/ladder/Ladder.java
> +    }
제 개인적인 생각으로는 `getSize()` -> `size()`  처럼 get 을 사용하지 않고 메서드명을 정하는것도 괜찮아보여요.

2024-03-04 17:15 UTC, pkeugine approved these changes
안녕하세요 테드!
리뷰가 많아서 꽤 복잡했을텐데 다 반영하시다니 👍 👍 👍 👍
새로 커밋한 내용 봤는데, 딱히 리뷰 남길 점이 없었어요.
이번 미션 고생하셨고, 다음 미션 파이팅입니다 😃

2024-03-04 17:15 UTC, merged

2024-03-04 22:32 UTC, Kimprodp commented on src/main/java/ladder/domain/resource/ladder/Ladder.java
> +    }
값을 가져오는 메서드를 사용할때 너무 get이라는 단어에만 꽂혀있어서 그런 방식의 네이밍은 생각 못했네요..ㅎㅎ 의견 감사합니다!

2024-03-04 22:33 UTC, Kimprodp commented on src/main/java/ladder/domain/line/Line.java
> +    }
다음부턴 null을 반환하지 않고 구현할 수 있도록 해보겠습니다!