[사다리 타기 - 2단계] 폴라(장유진) 미션 제출합니다.
woowacourse/java-ladder pull request #394
Opened 2024-02-29 13:23 UTC by jinchiim

안녕하세요 제이!
2단계를 가지고 돌아온 폴라입니다!

저번 1단계에 개인적으로 **아쉬웠던 부분**들을 이번에 개선해보고,
전체적으로 **직관적이고 흐름이 잘 보이는 코드**를 작성해보고 싶어 최대한 처음 보는 사람의 시선으로 생각해보려고 했어요!
그렇지만 역시 어렵네요🫣

또, 몇가지 **새로운 점**들도 시도해보았는데요!

작성하며 몇가지 궁금한 점도 생겨 작성해보았습니다!

이번에도 좋은 의견 부탁드립니다! ✍🏻 감사합니다! <br>

## 1. `Controller`를 두개로 분리하면 어떨까

개인적으로 
- **사다리를 만들고 만들어진 사다리를 보여주는 Controller** 
- **사다리의 결과를 매핑하고, 결과를 찾아주는 흐름을 가진 Controller**

이 두가지를 분리하고 싶었습니다.

`Controller`라고 한다면 하나의 `Controller`를 기대하게 될 것 같다는 걱정이 있기도 했습니다.

그러나 `LadderResult`라는 `Map<Integer,Integer>`을 가진 도메인을, 사다리를 만드는 `GameController`에서 가지기 보다는
그와 관련된 역할을 가진 다른 하나의 `ResultController`가 가지는 것이
흐름적이 면에서 더 이해가 가고 편하지 않을지 생각하게 되었습니다...<br>
![image](https://github.com/woowacourse/java-ladder/assets/105053478/c4623f28-568a-408f-95af-804d07e276b1)

새로운 시도라서 제이는 어떻게 생각하시는지 궁금합니다! 👀
<br>

### 1-1. `Controller`에서의 중복 로직을 삭제하기 위해 상속을 사용해도 괜찮을까요?
---

이어지는 질문인데요,
개인적으로 아쉬웠던 부분은 해당 코드의 반복 이었습니다.
```java
    private <T> T repeatUntilValid(Supplier<T> function) {
        try {
            return function.get();
        } catch (IllegalArgumentException e) {
            outputView.printError(e);
            return repeatUntilValid(function);
        }
    }
```
이 `method`가 두가지의 `Controller` 모두 가지고 있었는데요!
고작 하나의 `method`라고 생각이 들면서도, 뭔가 같은 역할의 `method`를 두개 만든 것만 같아 거슬리게 느껴졌습니다.

그래서 해당 부분을 **상속을 사용해서** 제거하면 어떨지 고민하게 되었습니다.
특히 `Controller`라는 상위 클래스 아래에 두가지가 포함될 수 있을 것 같기도 하고 큰 비즈니스 로직이 아니기 때문에 상속을 사용해도 괜찮지 않을까? 라는 생각이 들었으나

다만 한편으로는 **단지 중복 제거라는 이유 하나로 사용해도 될지에 대해 생각하게 되었습니다.**
이에 대해 제이의 의견이 궁금해요! 👀

## 2.  Dto에 `method`를 만들어도 괜찮을까요?

우선 기존에 값들은 `Controller` 내부에서는 `Dto`의 형태로 돌아다니는 걸 원했습니다.
 
`Collections.unModifiable()`을 해줘도, 내부에서 `add`하는 `method`가 생성될 수 있고, 도메인과 Controller나 View 간의 강한 결합이 생기는걸 원치 않았기 때문인데요.

다만 이로 인해서 결과를 매핑하는 `LadderResult`에서 `Step`을 확인하기 위해서는

```java
madeLines.get(startIdx).line().get(position).getBuildStatus()
```
이와 같은 형태를 이루어야 했습니다!
물론 저 `get()`들은 해당 `dto`에서만 사용하는 것은 아니었지만, 
그럼에도 가독성 측면에서 너무 떨어진다고 판단했습니다.

이를 위해서 `dto` 내부에
```java
public record MadeLadderDto(List<MadeLineDto> madeLines) {

    public boolean checkLineStepStatus(int linePosition, int stepPosition) {
        return madeLines.get(linePosition).findPositionStepStatus(stepPosition);
    }
}
```
와 같이 `LineStepStatus`를 `boolean`값으로 가져오는 `method`를 생성해주었는데요.
단순히 가졍호는 값이 `boolean` 이기 때문에 문제가 없다 여겨지면서도 값만 전달해주는 `dto` 내부에서 해당 `method`를 구현하게
되어버린 것이 조금 아쉬웠습니다.

그런데 이 아쉬움이 단순히 **`dto`는 `method`를 만들지 않은 것이 좋아!** 에서
비롯된 것인지 확신이 서질 않아 제이님의 의견을 듣고 싶습니다! 👀
<br>

## 3. 전달해주는 인자 값 이름을 다르게

```java
// GamePrize
    public GamePrizes(List<String> gamePrizeInput, int participantCount) {
        validate(gamePrizeInput, participantCount);
        this.prizes = gamePrizeInput;
    }

// LadderGameController
       private GamePrizes readyPrizes(int participantCount) {
        List<String> inputPrizes = inputView.getPrizes();
        return new GamePrizes(inputPrizes, participantCount);
    }
```
이전에는 `method`에서 전달해주는 인자 값과 받는 인자 값을 순서보다는 이름으로 알 수 있게
이름을 통일하는 편이었습니다!

다만 이게 오히려 흐름을 방해하고 해당 `method`가 어떻게 보면
각가 하나의 역할을 해주고 있는 상황에서 넘겨주는 객체에 의해 변수의 이름이 정해지면 안되지 않을까? 에 대한
의문이 들었는데요.

```java
// GamePrize
    public GamePrizes(List<String> gamePrizeInput, int availablePrizeCount) {
        validate(gamePrizeInput, availablePrizeCount);
        this.prizes = gamePrizeInput;
    }

// LadderGameController
       private GamePrizes readyPrizes(int participantCount) {
        List<String> inputPrizes = inputView.getPrizes();
        return new GamePrizes(inputPrizes, participantCount);
    }
```
그래서 위와 같이 `GamePrize`에서는 해당 값이 무엇인지 알 수 있도록 `availablePrizeCount`로
변경해보았습니다.

개인적으로는 오히려 가독성이 좋아졌다고 생각했는데, 이에 대해 제이님의 의견이 궁금해요! 👀
<br>

## 4. `0`까지 상수화 해주는게 좋을까?

저번 구현에서는 `0`을 전부 상수화 해주었는데요.
이유는 다음과 같았습니다.

우선 개발자의 시선, 큰 그림에서 봤을 때 당연히 **처음부터 끝까지** 돌리니
`0`부터 시작하는게 당연하게 느껴지지만 한편으로는 위에서 말씀드린 것 처럼 `method`하나를 하나의 역할로 봤을때
`처음` 이라는 단어 자체가 어떤 위치의 의미를 담고 있지 않나 라는 생각이 문득 들어 상수화를 시켜준 것이었습니다.

다만 이로 인해 어떠한 이름의 상수로 변경해줘도
`0`보다 더 직관적이라는 느낌은 전혀 들지 않았어요. 🥲 이에 대해 제이의 의견이 궁금합니다! 👀

<br>

오늘도 너무 다량의 질문을 쌓아서 왔네요,,,!
저번 리뷰도 좋은 의견 많이 주셔서 감사했습니다. 이번에도 잘 부탁드립니다! 감사합니다! 🥰

2024-03-01 10:20 UTC, JunHoPark93 requested changes
안녕하세요 폴라~
2단계 구현하느라 고생많으셨어요.
질문주신 부분들에 대한 코멘트 남겨두었는데 확인해보시고 의견 및 반영부탁드려요~

2024-03-01 10:20 UTC, JunHoPark93 commented on src/main/java/ladder/controller/LadderResultController.java
> +public class LadderResultController {
> 개인적으로
> 
> 사다리를 만들고 만들어진 사다리를 보여주는 Controller
> 사다리의 결과를 매핑하고, 결과를 찾아주는 흐름을 가진 Controller
> 이 두가지를 분리하고 싶었습니다.
> 
> Controller라고 한다면 하나의 Controller를 기대하게 될 것 같다는 걱정이 있기도 했습니다.
> 
> 그러나 LadderResult라는 Map<Integer,Integer>을 가진 도메인을, 사다리를 만드는 GameController에서 가지기 보다는
> 그와 관련된 역할을 가진 다른 하나의 ResultController가 가지는 것이
> 흐름적이 면에서 더 이해가 가고 편하지 않을지 생각하게 되었습니다...

컨트롤러가 굳이 2개가 필요할까 라는 생각이 드는데요, 사다리를 그려주는 역할과 결과를 만들어주는 역할을 따로 분리한다면 굳이 컨트롤러를 2개 만들 필요는 없을거같아요.
화면에 보여주는 역할은 view가 모두 담당하고있기 때문에 결과를 만들고 view에 넘겨주면 되지 않을까요?

더군다나 ladderGameController.run()으로 새로운 컨트롤러를 만드는 구조가 어색해보입니다.

구조를 많이 바꿔야하는데 폴라 의견은 어떠신가요?

2024-03-01 10:20 UTC, JunHoPark93 commented on src/main/java/ladder/controller/LadderGameController.java
> +    private <T> T repeatUntilValid(Supplier<T> function) {
> 이 method가 두가지의 Controller 모두 가지고 있었는데요!
> 고작 하나의 method라고 생각이 들면서도, 뭔가 같은 역할의 method를 두개 만든 것만 같아 거슬리게 느껴졌습니다.
> 
> 그래서 해당 부분을 상속을 사용해서 제거하면 어떨지 고민하게 되었습니다.
> 특히 Controller라는 상위 클래스 아래에 두가지가 포함될 수 있을 것 같기도 하고 큰 비즈니스 로직이 아니기 때문에 상속을 사용해도 괜찮지 않을까? 라는 생각이 들었으나
> 
> 다만 한편으로는 단지 중복 제거라는 이유 하나로 사용해도 될지에 대해 생각하게 되었습니다.
> 이에 대해 제이의 의견이 궁금해요! 👀

현재 구조에서 변경을 하려면 GameController나 ResultController의 공통기능이 이 메서드인거같은데요, RepeatableController로 묶어서 extends구조로 가져가도 될거같아요. 
다만 중복을 제거하는 방법이 상속만 있는게 아니기 때문에, 중복제거 이유하나만으로 extends구조로 가져가기에는 조금 부족해보이긴합니다.

2024-03-01 10:20 UTC, JunHoPark93 commented on src/main/java/ladder/controller/LadderGameController.java
> +    private <T> T repeatUntilValid(Supplier<T> function) {
제가 추천하는 방향은 (여유가 있으시다면) extends구조로 만들어보거나 공통클래스로 추출하거나 하는 방향으로 중복을 제거해보고 어떤 장/단점이 있는지 정리해보면 좋을거같아요~

이렇게 말씀드리는이유는 "그럴것이다" 추측보다 실제로 해보면 기억에 더 잘남기때문이에요!

2024-03-01 10:20 UTC, JunHoPark93 commented on src/main/java/ladder/domain/dto/MadeLadderDto.java
> +public record MadeLadderDto(List<MadeLineDto> madeLines) {
> Dto에 method를 만들어도 괜찮을까요?

본래 역할은 없는게 맞지만 편의상 만드는 경우도 있긴합니다. 개인적으로 로직이 데이터를 전달하는데에 국한된 로직이라면 허용해도 된다고 생각해요. (예를 들어, 불필요한 필드를 제외하고 convert를 하는등의..) 다만 해당 로직이 도메인 로직이라면 dto안에 있으면 안되겠죠.

정의해주신 로직은 어떤 부분에 해당하는 로직일까요?

2024-03-01 10:20 UTC, JunHoPark93 commented on src/main/java/ladder/domain/prize/GamePrizes.java
> +    public GamePrizes(List<String> gamePrizesInput, int availablePrizeCount) {
3번째 질문주신 부분인거같아요~
인자를 명시적인 이름으로 수정했다 라는 부분으로 이해했는데 맞을까요? 

당연히 가독성 측면에서는 맞고, 해당 변수들이 코드내에 돌아다닌다면 이름이 통일되어야 헷갈리지 않을테니 바꿔주신 이름으로 지금처럼 모두 유지를 해주시면 될거같아요.

혹시 이 질문이 아니었다면 다시 부연설명 부탁드려요~

2024-03-01 10:20 UTC, JunHoPark93 commented on src/main/java/ladder/controller/LadderResultController.java
> +    private static final String KEEP_CHECK = "Y";
> 저번 구현에서는 0을 전부 상수화 해주었는데요.
> 이유는 다음과 같았습니다.
> 
> 우선 개발자의 시선, 큰 그림에서 봤을 때 당연히 처음부터 끝까지 돌리니
> 0부터 시작하는게 당연하게 느껴지지만 한편으로는 위에서 말씀드린 것 처럼 method하나를 하나의 역할로 봤을때
> 처음 이라는 단어 자체가 어떤 위치의 의미를 담고 있지 않나 라는 생각이 문득 들어 상수화를 시켜준 것이었습니다.
> 다만 이로 인해 어떠한 이름의 상수로 변경해줘도
> 0보다 더 직관적이라는 느낌은 전혀 들지 않았어요. 🥲 이에 대해 제이의 의견이 궁금합니다! 👀

혹시 어느 부분이었을까요?
말씀하신대로 숫자 그대로의 의미가 제일 전달이 잘된다고하면 ZERO라고 짓는 경우도 있긴해요. 다만 이경우에는 상수화의 여러 이점중 하나인 명시적인 의미전달 측면보다는 유지보수성 측면이 더 가깝다고 볼 수 있겠네요.
상수화를 했을때 해당 값이 코드내에 여러군데에서 사용이 된다면 일괄로 관리할 수 있기 때문에 모든 숫자를 상수로 관리하는게 더 좋습니다. 실제로도 숫자값때문에 장애가 나기도하구요.

혹시 더 궁금하신게 있으면 코멘트 남겨주세요~

2024-03-01 10:20 UTC, JunHoPark93 commented on src/main/java/ladder/domain/prize/GamePrizes.java
> +    private static final int MAXIMUM_PRIZE_LENGTH = 5;
개행 하나 있으면 좋을거같아요

2024-03-01 10:20 UTC, JunHoPark93 commented on src/main/java/ladder/domain/prize/GamePrizes.java
> +    }
depth를 1로 유지하는 요구사항이 있는데 어떻게 개선하면 좋을까요?

2024-03-01 10:20 UTC, JunHoPark93 commented on src/main/java/ladder/domain/participant/Participants.java
> +        return index;
검증메서드를 따로 정의하여 메서드 크기를 최대한 작게 만들어보면 어떨까요? 다른 부분들도 개선할 부분이 있는지 찾아보면 좋을거같아요~

2024-03-02 16:29 UTC, jinchiim commented on src/main/java/ladder/controller/LadderResultController.java
> +public class LadderResultController {
당시에는 2가지로 나누는게 좋다고 생각했는데,
돌이켜 보면  2단계에서는 `Controller` 중심으로 구현하면서 `TDD`를 행하기 힘들어지니 또 너무 많은 생각을 하게 된건 아닌가 싶어요.

말씀하신 대로 3가지 모두 행해보고 느껴보는 것도 좋은 것 같아 합쳐보았습니다!

개인적으로도 역할의 분리는 여러 시도 중 하나였다고 생각하면서도 run() 에서 Controller를 넘겨주는 일이
많이 어색했는데요. (특히 이번에 처음 보더라도 읽히는 코드를 중점으로 두면서)

구조를 많이 바꿔도 해보길 잘했다는 생각이 듭니다! 의견 감사합니다!

2024-03-02 17:08 UTC, jinchiim commented on src/main/java/ladder/controller/LadderGameController.java
> +    private <T> T repeatUntilValid(Supplier<T> function) {
말씀하신 두가지 모두 해보았습니다!
사실 말씀하신 **공통 클래스**가 `interface`를 뜻하시는 건지 `Static`을 뜻하시는 건지 조금 고민했지만
**중복을 제거하는 방법**으로는 `static`이 더 가까운 것 같아 이 방법으로 2가지 모두 구현해보았습니다!

마무리는 `Controller`를 합친 코드로 올리고 싶어 순서를

1. `상속`
2. `static` 클래스 (static import, import )
3. Controller 하나로 합치기

로 갔는데요. 헷갈리실 것 같아 순서대로 ✅ 표시를 `Commit message`에 달아놨습니다!

말씀하신 두가지 방법을 구현하면서 느낀점들을 간략히 말씀드리자면

### 1. 상속

중복으로 사용하는 필드들도 줄일 수 있고, 부모 객체가 있다는 걸 확인할 수 있으니 두가지의 `Controller`가
같은 역할(도메인에게 시키는)을 하겠구나 예측이 가능하더라구요.
다만, 그럼에도 `method`의 이름이 직관적이지 않으면 결국 부모객체로 향하게 된다는 점이 아쉬웠습니다.

### 2. static Class / method 사용

개인적으로 **static import**를 사용한 method가 가장 혼란스럽다고 느꼈습니다.
`method`이름이 정말 명확한게 아니고서야 **갑자기 툭 튀어나온 느낌**을 많이 받았습니다.

다만, 오늘 같이 얘기를 나누던 중, `Exception Handler`라는 클래스 이름으로 사용하는 분을 보게 되었는데
이렇게 하는 경우 클래스 이름을 같이 붙여 `static import`가 아닌 `import`로 가져온다면,
의미가 명확해질 수 있겠다고 생각하게 되었습니다. 🤔

제가 잘 이해한게 맞나 궁금하네요! 좋은 의견 감사합니다 제이!

2024-03-02 17:11 UTC, jinchiim commented on src/main/java/ladder/domain/dto/MadeLadderDto.java
> +public record MadeLadderDto(List<MadeLineDto> madeLines) {
단순히 `get.get.get....` 되는 부분을 `dto` 내부에서, 서로 통신하여 가져오는 방식으로 `method`를 만든 것이라서
해당 로직은 데이터 전달에 국한된 로직에 가까운 것 같습니다!

실제로 가져오는 값도 내부에 담겨진 `boolean` 값 하나이기도 하고요!

2024-03-02 17:14 UTC, jinchiim commented on src/main/java/ladder/domain/prize/GamePrizes.java
> +    public GamePrizes(List<String> gamePrizesInput, int availablePrizeCount) {
명시적인 이름으로 수정했지만 통일은 되어있지 않습니다!

예를 들어, `GamePrize`의 개수는, 이전에 입력된 사람 수에 따라서 결정되게 되는데요.
그럴 경우에 `Controller`에서는 `participantCount` 라는 이름과 같은 식으로 가지지만 이 변수 이름 그대로 `GamePrizes`에 
들어갈경우 괜히 어색하게 느껴지더라고요. 😢

해당 객체가 왜 사람의 수를 가지게 되는가? 라는 의문도 들 것 같았습니다.

다만 통일이 되지 않는 부분에서 오히려 혼란을 야기하지 않을까 의문이 들어 여쭤보게 되었습니다!

2024-03-02 17:17 UTC, jinchiim commented on src/main/java/ladder/controller/LadderResultController.java
> +    private static final String KEEP_CHECK = "Y";
해당 부분의 예시는 `Line` 쪽에서 보실 수 있습니다!

```java
public class Line {

    private static final int STEP_START_INDEX_NUMBER = 0;

...

    public boolean isStepDuplicatedWithBeforeStep(int nowPosition) {
        validateNotNegativePosition(nowPosition);

        if (nowPosition > STEP_START_INDEX_NUMBER) {
            Step step = steps.get(nowPosition - 1);
            return step.getBuildStatus();
        }
        return DEFAULT_NO_DUPLICATED_STEP;
    }
```

해당 `class`에서 실험삼아 한번 해보았었습니다!
유지 보수성 측면이 크다면 오히려 모두 통일 된 의미있는 값은 아니라서 (단순히 처음부터 끝까지 돌리는 for문에서 사용해서)
가독성도 떨어지니 없는 편이 낫겠네요ㅜ 좋은 의견 감사합니다!

2024-03-02 17:19 UTC, jinchiim commented on src/main/java/ladder/domain/prize/GamePrizes.java
> +    }
해당 부분을 놓친 것 같네요 😱
수정 했습니다! 감사합니다!

2024-03-02 17:20 UTC, jinchiim commented on src/main/java/ladder/domain/participant/Participants.java
> +        return index;
감사합니다!

다른 부분들도 찾아봤는데, 제가 미숙해서 그런지 더이상 찾을 수 없어 해당 부분만 수정해보았습니다!

2024-03-04 11:25 UTC, JunHoPark93 commented on src/main/java/ladder/controller/util/RepeatUtil.java
> +    }
불필요한 생성을 막아보셨네요 👍🏼

2024-03-04 11:25 UTC, JunHoPark93 commented on src/main/java/ladder/controller/LadderGameController.java
> +            showResult(participants, gamePrizes, madeLadder);
조건에 따라 ladderMapper 객체를 생성할 필요가 없어지겠네요~

2024-03-04 11:25 UTC, JunHoPark93 commented on src/main/java/ladder/domain/ladder/Line.java
> +        if (nowPosition > 0) {
다시 숫자로 돌아갔네요! 연유가 있으셨을까요?

2024-03-04 11:25 UTC, JunHoPark93 commented on src/main/java/ladder/controller/LadderGameController.java
> +    private <T> T repeatUntilValid(Supplier<T> function) {
보기 편하게 잘 나눠주셨네요 👍🏼

1. 상속쓰셨을때 (commit hash c39da7fe) 공통으로 가질 수 있는 인스턴스변수들을 더 올려봐도될거같아요. outputview만 올라가니 입력에 대한 로직들을 보기가 힘든거같아요. 

2. 저는 static import하면 코드가 짧아져서 선호하긴합니다. 모르겠으면 들어가서보긴하는데 취향차이일수있겠네요.

2024-03-04 11:25 UTC, JunHoPark93 commented on src/main/java/ladder/domain/dto/MadeLadderDto.java
> +public record MadeLadderDto(List<MadeLineDto> madeLines) {
잘 판단해주셨습니다!

2024-03-04 11:27 UTC, JunHoPark93 commented on src/main/java/ladder/domain/prize/GamePrizes.java
> +    public GamePrizes(List<String> gamePrizesInput, int availablePrizeCount) {
그 말씀이시군요 코드가 레이어에 따라 나뉘면서 인자들이 적합한 이름으로 바뀌어도 괜찮다고 생각합니다.
물론 통일되는게 제일 좋겠지만 적합하지 않다면 바꿔도 좋습니다. 클라이언트에 종속된 이름의 인자를 도메인까지 들고들어가는게 더 맞지 않아보이니까요

2024-03-04 11:30 UTC, JunHoPark93 approved these changes
안녕하세요 폴라~
피드백 반영하느라 고생많으셨습니다.
고민을 정말 많이 하신게 보이네요. 추가적인 코멘트는 달아두었는데 혹시 더 궁금한거있으시면 말씀주세요.
다음 미션도 화이팅입니다!

2024-03-04 11:30 UTC, JunHoPark93 commented on src/main/java/ladder/domain/ladder/Line.java
> +        if (nowPosition > 0) {
https://github.com/woowacourse/java-ladder/pull/394#discussion_r1510007770

이 코멘트랑 연관이 있는거같네요. 점점 더 큰 프로젝트를 만들어보시면서 생각이 바뀌실수도있으니 지금 이대로도 좋습니다

2024-03-04 11:30 UTC, merged

2024-03-05 15:31 UTC, jinchiim commented on src/main/java/ladder/controller/LadderGameController.java
> +            showResult(participants, gamePrizes, madeLadder);
그렇네요!!
사용하지 않는 객체가 생길 수 있으니, 안에서 만들었으면 좋았을  것 같습니다..!
감사합니다! 🥹