[2단계 - 사다리 게임 실행] 제리(김민정) 미션 제출합니다.
woowacourse/java-ladder pull request #409
Opened 2024-03-02 04:15 UTC by mzeong

2024-03-02 11:32 UTC, seovalue requested changes
안녕하세요 제리~
2단계 잘 수행해주셨네요ㅎㅎ
몇가지 코멘트 남겼는데 한번 확인하신 뒤 다시 리뷰 요청 주세요~! 👍

2024-03-02 11:32 UTC, seovalue commented on README.md
> +- [x] 참여할 사람 이름을 입력받는다.
👍

2024-03-02 11:32 UTC, seovalue commented on src/main/java/ladder/controller/LadderController.java
> +        while (ladderGame.isInProgress()) {
null로 isInProgress를 관리해주신 이유가 궁금해요. null은 의도치 않게도 들어갈 수 있다고 생각해서요 여쭈어용~

2024-03-02 11:32 UTC, seovalue commented on src/main/java/ladder/domain/LadderGame.java
> +    public Map<Player, ResultItem> execute(String target) {
execute라는 네이밍을 해주신 이유가 궁금해요!

2024-03-02 11:32 UTC, seovalue commented on src/main/java/ladder/controller/LadderController.java
> +    private Map<Player, ResultItem> executeLadderGameWithRetry(LadderGame ladderGame) {
메서드 순서가 위에서부터 실행되는 순서이면 가독성이 좋을 것 같아요~

2024-03-02 11:32 UTC, seovalue commented on src/main/java/ladder/domain/Direction.java
> +    DOWN(index -> index);
LEFT일 경우 decrease, RIGHT일 경우 increase, DOWN일 경우 유지인 것이 직관적으로 와닿지 않는 것 같아요!

2024-03-02 11:32 UTC, seovalue commented on src/main/java/ladder/domain/Ladder.java
> +    public Ladder(int heightValue, Line... lines) {
테스트용 생성자인데, 15line의 생성자로 대체할순 없을까요?

2024-03-02 11:32 UTC, seovalue commented on src/main/java/ladder/domain/Index.java
> +public class Index {
Index라고 네이밍해주신 이유가 궁금해요~

2024-03-02 11:32 UTC, seovalue commented on src/main/java/ladder/domain/Ladder.java
> +    public List<List<Direction>> getRawLadder() {
반환값을 감싸보는 것은 어떨까요?

2024-03-02 11:32 UTC, seovalue commented on src/main/java/ladder/domain/Result.java
> +    private final LinkedHashMap<Player, ResultItem> matches;
결과값에 대해서 map으로 관리하는 것 좋은 것 같아요 👍

2024-03-02 11:32 UTC, seovalue commented on src/main/java/ladder/domain/ResultItems.java
> +    public ResultItems(int personCount, String... strings) {
이것도 테스트용 생성자인 것 같아요!
테스트용 코드에 대해서 어떻게 생각하시는지 궁금해요!

2024-03-02 11:32 UTC, seovalue commented on src/main/java/ladder/util/RandomLadderGenerator.java
> +        return random.nextInt(size - 2) + 1;
-2 + 1과 같은 값은 이름을 주어서 관리해보는 것은 어떨까요?

2024-03-02 11:32 UTC, seovalue commented on src/test/java/ladder/domain/LadderGameTest.java
> +         */
주석으로 그림이 있으니깐 이해하기가 더 좋네용

2024-03-02 14:38 UTC, mzeong commented on src/main/java/ladder/util/RandomLadderGenerator.java
> +        return random.nextInt(size - 2) + 1;
이해하기 어려운 코드 같아 메서드로 분리했지만 여전히 부족하다고 느껴져 고민이었어요!! 조앤의 제안대로 상수를 사용하니 전보다 이해하기 쉬운 코드가 된 것 같아요 👍

2024-03-03 03:47 UTC, mzeong commented on src/main/java/ladder/controller/LadderController.java
> +        while (ladderGame.isInProgress()) {
아래의 LadderGame의 climb 메서드를 통해서만 Result의 Value가 갱신되는데,
생성된 사다리는 이동이 보장되고, 참여자 수와 결과 항목의 수가 일치함도 보장되므로 null이 의도치 않게 들어가는 경우는 고려하지 않았어요 😓

```java
private void climb(Player player) {
    if (result.hasNullValueForKey(player)) {
        Index playerIndex = players.findIndexOfPlayer(player);
        Index resultItemIndex = ladder.climb(playerIndex);
        ResultItem resultItem = resultItems.get(resultItemIndex);
        result.put(player, resultItem);
    }
}
```

<br>

저는 모든 참가자의 실행 결과를 제공했을 때를 종료 조건으로 하고 싶었어요 (all을 입력했을 때도 종료하지만, pobi, honux, crong, jk를 각각 입력했을 때도 모든 실행 결과를 제공했다고 판단해 종료)

이를 위해 ‘실행 결과 미제공’을 의미하는 초기값이 필요했고, null로 초기화를 했어요 (ResultItem가 글자수를 제외하고는 제한이 없어 다른 적절한 초기값을 찾지 못했습니다)

map의 크기로 종료를 판단하는 방법도 생각하였는데, all에 대한 실행 결과가 이름 입력 순으로 나오게 하기 위해
Result 생성 시 참여자의 이름을 map에 추가하는 과정이 필요해 선택하지 못했습니다.

<br>

어떤 상황에서 null이 의도치 않게 들어갈 수 있을까요? Result의 put 메서드에서 ResultItem이 null일 경우 예외를 발생시키는 것만으로 null이 의도치 않게 들어가는 상황에 충분히 대비했다고 볼 수 있을까요?

2024-03-03 03:51 UTC, mzeong commented on src/main/java/ladder/domain/LadderGame.java
> +    public Map<Player, ResultItem> execute(String target) {
사다리 게임을 '실행'하는 행위라는 의미를 담아 execute라고 네이밍 했습니다!

2024-03-03 05:31 UTC, mzeong commented on src/main/java/ladder/domain/Index.java
> +public class Index {
사다리를 타기 위해 Players, ResultItems의 인덱스가 필요하였고, 
이를 원시값 포장할 때 Index 이름 그대로 명명해서 '리스트에서 특정 요소의 위치'라는 의미를 담는 것이 가장 의미 전달이 잘 될 것이라 판단했습니다!

2024-03-03 06:01 UTC, mzeong commented on src/main/java/ladder/domain/Direction.java
> +    DOWN(index -> index);
좀 더 직관적으로 전달하고자 아래와 같이 네이밍을 수정하였습니다! 혹시 이전보다 전달이 잘 되나요?

```java
BACKWARD(Index::decrease),
FORWARD(Index::increase),
STAY(Index::maintain);
```

2024-03-03 07:47 UTC, mzeong commented on src/main/java/ladder/domain/Ladder.java
> +    public Ladder(int heightValue, Line... lines) {
아래에도 동일한 주제에 대한 리뷰를 남겨주셔서 이곳에 함께 코멘트를 남겨요! 😄

클래스가 많아질수록 객체 생성을 위해 List.of를 반복적으로 호출해야 하니 가독성도 떨어지고, 테스트 코드를 작성하기가 번거로웠습니다 이에 가변 인자 생성자를 사용해 가독성과 테스트 코드 작성의 편의성을 높이고자 했습니다!
생성자의 매개변수 타입이 변경될 가능성이 낮으며, 혹 변경되더라도 수정이 적을 것이라 예상해 유지보수성에도 영향을 미치지 않을 것이라 판단했습니다

테스트용 코드를 지양해야 함을 인지하고 있지만 이 경우에는 장점이 더 크다고 생각했습니다

2024-03-04 01:46 UTC, seovalue commented on src/main/java/ladder/controller/LadderController.java
> +        while (ladderGame.isInProgress()) {
Result에 추가로 상태를 나타내는 field를 둘 수도 있지 않을까요?ㅎㅎ
null이라는 값을 어떻게 생각하시는지 궁금해요~ 
만약 로직의 누락이 있어 특정 플레이어의 결과값이 들어가지 않게 오류가 난다면, 그 플레이어를 조회했을 때엔 항상 null이 될 수도 있기도 하고요.

2024-03-04 01:50 UTC, seovalue commented on src/main/java/ladder/domain/Ladder.java
> +    public Ladder(int heightValue, Line... lines) {
제 생각에는, 이런 식으로 해보면 어떨까 해요!
Test 패키지에만 Util이 있어서, 

```java
    Ladder makeLadder(int height, Line... lines) {
        return new Ladder(height, Arrays.asList(lines));
    }
```
이렇게 테스트에서만 필요한 부분을 감싸서 호출할 수 있도록요.

2024-03-04 01:51 UTC, seovalue approved these changes
안녕하세요, 제리!
수정해주신 부분은 주로 네이밍 위주라 남겨주신 코멘트에 대한 답변 위주로 남겨두었어요~
요구사항은 모두 만족해서 이번 단계는 머지할게요!
고생 많으셨어요ㅎㅎ

2024-03-04 01:51 UTC, merged

2024-03-06 14:00 UTC, mzeong commented on src/main/java/ladder/controller/LadderController.java
> +        while (ladderGame.isInProgress()) {
null을 참조 변수가 어떠한 객체도 가리키지 않음을 나타내는 값 정도로 생각했어요.

그러나 null 사용은 아래와 같은 문제가 발생할 수 있으므로
- NullPointerException으로 인한 예기치 않은 종료 발생
- null 여부를 체크하기 위해 불필요한 코드 작성
- null 처리의 전파

조앤의 조언처럼 수정하여 null 사용을 피하는 것이 더 좋은 방향이라는 것을 알게 되었습니다 😄

2024-03-06 14:07 UTC, mzeong commented on src/main/java/ladder/domain/Ladder.java
> +    public Ladder(int heightValue, Line... lines) {
다음 미션인 블랙잭을 진행하면서도 동일하게 테스트를 작성할 때 생성이 번거로운 문제에 마주했어요! 
이번에는 조앤의 피드백을 참고하여 test 패키지 내에 코드를 작성하고 있습니다 ☺️