[사다리 게임] 티버 미션 제출합니다.
woowacourse/java-ladder pull request #42
Opened 2019-05-19 03:51 UTC by yjll1019

TDD로 코드를 작성하는게 익숙하지 않아서 처음에는 시간이 많이 소요됐지만,
조금 익숙해지니 제가 원하는 클래스의 기능을 정확하고 빠르게 구현할 수 있었습니다.
제가 작성한 코드를 볼 때마다 마음에 들지 않는 부분이 생기고, 다른 구현 방법이 생각나서 
여러 번 코드를 수정하느라 과제 제출 시간이 많이 늦어졌습니다.
많은 지적 부탁드립니다. 감사합니다!

2019-05-22 08:56 UTC, woowahan-pjs requested changes
꼼꼼한 Commit과 README.md 파일이 아주 인상적이었어요. 🥇  
수차례 코드를 수정하고 고민한 흔적이 남아있어 리뷰에 많은 신경을 썼습니다.
고민해보면 좋을 것 같은 의견은 남겨놓았으니 충분히 고민하고 도전해보시고,
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.

2019-05-22 08:56 UTC, woowahan-pjs commented on src/main/java/calculator/domain/Calculator.java
> +		return Arrays.stream(values).mapToInt(value -> Integer.parseInt(value)).sum();
Stream API를 사용할 때 한 줄에 점을 하나만 찍으면 다른 개발자도 읽기 좋은 코드가 될 수 있습니다. 심지어 IntelliJ IDEA를 사용한다면 타입 힌트도 볼 수 있어요. 👍 

![](https://www.jetbrains.com/idea/whatsnew/img/2018.2/JavaTypeHints.png)

2019-05-22 08:56 UTC, woowahan-pjs commented on src/main/java/calculator/domain/Calculator.java
> +	private static final String REGEX_OF_NUMBER = "[0-9]+";
이미 매직넘버의 단점을 알고 상수의 필요성을 알고 있네요! 👍 여기에 첨언을 한다면 `String`을 패턴 매칭을 위해 `Pattern`으로 바꾸는 것은 꽤나 비싼 행위입니다. `matches()`의 내부 동작을 살펴보고 미리 `Pattern`으로 만들어 사용하는 것은 어떨까요?

2019-05-22 08:56 UTC, woowahan-pjs commented on src/main/java/calculator/util/StringSeparator.java
> +public class StringSeparator {
`StringSeparator`를 만들어 책임 분리 👍

2019-05-22 08:56 UTC, woowahan-pjs commented on src/main/java/calculator/util/StringSeparator.java
> +		Matcher m = pattern.matcher(input.replaceAll("\\\\n", "\n"));
`input.replaceAll("\\\\n", "\n")`가 왜 필요한지 메서드 분리를 통해 설명하면 다른 개발자도 쉽게 이해할 수 있을 것 같아요. 👍

2019-05-22 08:56 UTC, woowahan-pjs commented on src/main/java/ladder/LadderGameApp.java
> +			StringSplitUtils.splitString(InputView.inputNames()).forEach(name -> players.add(new Player(name)));
Java Stream API를 써보면 어떨까요?

2019-05-22 08:56 UTC, woowahan-pjs commented on src/main/java/ladder/LadderGameApp.java
> +			return getLadderGameInformation();
캡틴께서 "반복문 대신 재귀 함수로 구현할 수 있다."라고 알려주셨어요. 하지만 재귀를 사용하면 어떤 위험이 있을까요? 만약 재귀를 사용하지 않는다면 어떻게 문제를 해결할 수 있을까요?

2019-05-22 08:56 UTC, woowahan-pjs commented on src/main/java/ladder/domain/Ladder.java
> +		this.lines = lines;
`lines`에 대한 주솟값을 그대로 받아 사용하면 어떤 문제가 발생할까요?

2019-05-22 08:56 UTC, woowahan-pjs commented on src/main/java/ladder/domain/Ladder.java
> +	public static Ladder generateLadder(int countOfPerson, String ladderHegiht) {
`generateLadder()`와 같은 메서드를 정적 팩토리 메서드라고 부른답니다. 👍 아래의 글을 읽고 일급 컬렉션을 내 것으로 확실히 완성시켜보세요.
https://www.slipp.net/wiki/pages/viewpage.action?pageId=30771479

2019-05-22 08:56 UTC, woowahan-pjs commented on src/main/java/ladder/domain/Ladder.java
> +	public Ladder(List<Line> lines) {
`generateLadder()`라는 훌륭한 정적 팩토리 메서드가 있으니 public이 아닌 private으로 바꾸면 어떨까요?

2019-05-22 08:56 UTC, woowahan-pjs commented on src/main/java/ladder/domain/LadderGameInformation.java
> +	private final List<Player> players;
일급 컬렉션이란 무엇이며, 어떤 장점이 있을까요? 아래의 글을 읽고 일급 컬렉션 만들기에 도전해보세요!
https://jojoldu.tistory.com/412

2019-05-22 08:56 UTC, woowahan-pjs commented on src/main/java/ladder/domain/UserOutput.java
> +public enum UserOutput {
`UserOutput`은 MVC 패턴 중 Model에 해당하는지, View에 해당하는지 고민해보면 좋겠어요. 필요하다면 View를 위한 메시지와 에러 메시지를 별도의 클래스로 분리하면 좋겠네요.

2019-05-22 08:56 UTC, woowahan-pjs commented on src/main/java/ladder/util/StringSplitUtils.java
> +			throw new NullPointerException(UserOutput.VIOLATE_PLAYER_NAME.getOutputMessage());
`input`은 `null`일 수도 있지만 빈 문자열일 수도 있습니다. 빈 문자열인 경우 `NullPointerException`이 발생하는 것이 맞을까요? 같이 고민해봐요.

2019-05-22 08:56 UTC, woowahan-pjs commented on src/test/java/ladder/domain/LadderGameInformationTest.java
> +		this.players.removeAll(Arrays.asList(new Player("pobi"), new Player("jason"),
필요에 따라 `remove()`를 호출하는 것보다 `add()`를 호출하는 것이 더 읽기 편할 것 같은데 어떻게 생각하세요?

2019-05-22 08:56 UTC, woowahan-pjs commented on src/test/java/ladder/domain/PointTest.java
> +		assertThrows(IllegalArgumentException.class, () -> new Point(true, true));
`new Point(true, true)`, `new Point(false, true)` 등과 같이 자주 만드는 인스턴스는 상수로 관리해 볼 수도 있어요.

2019-05-22 08:56 UTC, woowahan-pjs commented on src/main/java/ladder/domain/Ladder.java
> +	public static Ladder generateLadder(int countOfPerson, String ladderHegiht) {
`ladderHegiht`가 `int`가 아닌 `String`인 이유가 궁금해요!

2019-05-22 08:56 UTC, woowahan-pjs commented on README.md
> +* 참가자의 이름에 따라 결과 반환하기
꼼꼼한 README.md 파일 💯

2019-05-22 08:56 UTC, woowahan-pjs commented on src/main/java/ladder/domain/LadderGameInformation.java
> +		return Collections.unmodifiableList(rewards);
`Collections.unmodifiableList()` 👍

2019-05-22 08:56 UTC, woowahan-pjs commented on src/main/java/ladder/domain/Player.java
> +	public boolean equals(Object o) {
`equals()` & `hashCode()` 👍

2019-05-22 08:56 UTC, woowahan-pjs commented on src/main/java/ladder/domain/Player.java
> +	public int hashCode() {
`equals()` & `hashCode()` 👍

2019-05-22 08:56 UTC, woowahan-pjs commented on src/main/java/ladder/domain/Line.java
> +			points.add(Point.next(points.get(i - 1).canGoRight()));
`next()`가 정적 메서드가 아닌 멤버 메서드라면 어떤 일이 발생할까요? 객체 지향 프로그래밍의 정수를 제대로 느껴보세요. 👍

2019-05-24 07:02 UTC, yjll1019 commented on src/main/java/calculator/domain/Calculator.java
> +	private static final String REGEX_OF_NUMBER = "[0-9]+";
네! 이전 코드와 같이 패턴을 매칭할 경우 매 번 Pattern 객체를 생성하고 그 결과를 반환하는 것을 확인했습니다. 
정규식을 검사할 때마다 Pattern 객체가 생성되는 것을 방지하기 위해서 인스턴스 변수로 Pattern객체를 두어 패턴을 매칭하도록 수정했습니다.

2019-05-24 07:02 UTC, yjll1019 commented on src/main/java/calculator/domain/Calculator.java
> +		return Arrays.stream(values).mapToInt(value -> Integer.parseInt(value)).sum();
네! 수정했습니다!

2019-05-24 07:02 UTC, yjll1019 commented on src/main/java/calculator/util/StringSeparator.java
> +		Matcher m = pattern.matcher(input.replaceAll("\\\\n", "\n"));
네! 메소드 분리를 통해 다른 개발자가 좀 더 쉽게 이해하도록 했습니다!

2019-05-24 07:02 UTC, yjll1019 commented on src/main/java/ladder/LadderGameApp.java
> +			return getLadderGameInformation();
1. 재귀를 사용하면 어떤 위험이 있을까요?
- 조건문이 존재하지 않는 경우, 무한 반복에 빠져 스택에 계속 데이터가 쌓이기 때문에 결국 stackoverflow error가 발생하게 됩니다.
2. 재귀를 사용하지 않는다면 어떻게 문제를 해결할 수 있을까요?
- 반복문을 통해서 해결 할 수 있다고 생각합니다.

또, 재귀 함수는 반복문에 비해서 매개변수 복사, 종료 후 복귀할 주소 저장 등의 추가로 데이터가 필요하고 수행 시간이 더 오래 걸리기 때문에 크게 복잡한 코드가 아니라면 반복문 사용이 더 효율적이라는 것을 이번 기회에 알게 되었습니다!

2019-05-24 07:02 UTC, yjll1019 commented on src/main/java/ladder/LadderGameApp.java
> +			StringSplitUtils.splitString(InputView.inputNames()).forEach(name -> players.add(new Player(name)));
네! Java Stream API를 사용해 불필요한 인스턴스 변수를 없애고, 코드를 좀 더 간결하게 구현 할 수 있었습니다!

2019-05-24 07:02 UTC, yjll1019 commented on src/main/java/ladder/domain/Ladder.java
> +	public Ladder(List<Line> lines) {
네~ 수정했습니다!

2019-05-24 07:02 UTC, yjll1019 commented on src/main/java/ladder/domain/Ladder.java
> +		this.lines = lines;
주솟값을 그대로 받아 사용 할 경우 메소드의 인자로 전달된 lines의 원시값이 훼손될 수 있다고 생각합니다. 
따라서 제가 생각했을 때 해결 방안은 
1. 메소드의 인자로 전달된 원시값을 수정하지 못하도록 final 키워드를 붙인다.
2. 생성자에서 new ArrayList<>(lines); 로 새로운 List형 객체를 만들어 Ladder 객체의 인스턴스 변수를 초기화한다. 

인데요. 제가 생각한 방법이 올바른 방법인지 잘 모르겠습니다.
그 외로 LineDTO를 만드는 것도 하나의 방법이 될 수 있을까요?

2019-05-24 07:02 UTC, yjll1019 commented on src/main/java/ladder/domain/Ladder.java
> +	public static Ladder generateLadder(int countOfPerson, String ladderHegiht) {
네! 좋은 자료 감사합니다!

2019-05-24 07:02 UTC, yjll1019 commented on src/main/java/ladder/domain/Ladder.java
> +	public static Ladder generateLadder(int countOfPerson, String ladderHegiht) {
처음에는 정규식 검사를 위해서 String타입으로 사다리의 높이를 받았습니다.
생각해보니 사다리의 높이가 String으로 사용되는 경우는 정규식 검사할 때 1번 뿐이라서 
Integer타입으로 변경했습니다!

2019-05-24 07:02 UTC, yjll1019 commented on src/main/java/ladder/domain/LadderGameInformation.java
> +	private final List<Player> players;
먼저 좋은 자료 공유해주셔서 감사합니다!

1. 일급 컬렉션이란?
: Collection을 Wrapping하면서 그 외 다른 변수가 없는 상태입니다. 

2. 일급 컬렉션 사용 시 장점은?
+ Collection의 불변성을 보장합니다.
+ 상태(값)와 행위(로직)을 한 곳에서 관리할 수 있습니다.
+ Collection에 이름이 생기기 때문에 Collection의 특징을 더 명확하게 표현 할 수 있습니다.
+ 비즈니스에 종속적인 자료구조를 가집니다.

2019-05-24 07:02 UTC, yjll1019 commented on src/test/java/ladder/domain/LadderGameInformationTest.java
> +		this.players.removeAll(Arrays.asList(new Player("pobi"), new Player("jason"),
네! 수정했습니다~!

2019-05-24 07:02 UTC, yjll1019 commented on src/test/java/ladder/domain/PointTest.java
> +		assertThrows(IllegalArgumentException.class, () -> new Point(true, true));
네! 테스트 코드에서 인스턴스를 상수로 변경하는 것을 생각하지 못하고 있었는데, 상수로 작성하니 좀 더 보기 좋은 코드가 되었습니다~~!

2019-05-24 07:04 UTC, yjll1019 commented on src/main/java/ladder/domain/UserOutput.java
> +public enum UserOutput {
UserOutput클래스에서 사용자에게 보여주기 위한 출력문을 변수를 선언하고,
ExceptionOutput클래스를 생성하여 예외 발생 시 출력을 위한 변수를 생성하였습니다!

2019-05-24 07:11 UTC, yjll1019 commented on src/main/java/ladder/util/StringSplitUtils.java
> +			throw new NullPointerException(UserOutput.VIOLATE_PLAYER_NAME.getOutputMessage());
찾아보았을 때, NullPointerException이 발생하는 경우는 밑의 5가지의 상황일 때 입니다.
- null object의 인스턴스 메소드를 호출할 때
- null 필드를 수정/접근하려고 할 때
- 빈 배열 객체에 길이 속성을 가져올 때
- 배열의 null인 슬롯에 수정/접근하려고 할 때
- Throwable 값처럼 null을 던질 때

말씀해주신 것처럼 입력된 `input` 이 빈 문자열일 때 NullPointerException을 반환하게 된다면, 
NullPointerException을 의도와 맞지 않게 사용하게 됩니다.
또, 예외가 발생하고 해결할 때 오해를 불러 일으킬 수 있다고 생각하여 빈문자열일 때의 예외처리를 추가로 구현했습니다!

2019-05-28 23:43 UTC, woowahan-pjs commented on src/main/java/calculator/domain/Calculator.java
> +	private static final String REGEX_OF_NUMBER = "[0-9]+";
👍

2019-05-28 23:43 UTC, woowahan-pjs commented on src/main/java/ladder/LadderGameApp.java
> +			return getLadderGameInformation();
👍

2019-05-28 23:47 UTC, woowahan-pjs commented on src/main/java/ladder/domain/Ladder.java
> +		this.lines = lines;
두 가지 모두 방법이 될 수 있어요. 첨언을 하면 `Collections.unmodifiableList()`라는 것도 있답니다. 아래의 글을 읽고 얕은 복사와 깊은 복사에 대해 공부해보세요.
https://isooo.github.io/java/2019/01/11/shallowCopy-vs-deepCopy.html

2019-05-28 23:47 UTC, woowahan-pjs commented on src/main/java/ladder/domain/LadderGameInformation.java
> +	private final List<Player> players;
👍

2019-05-28 23:47 UTC, woowahan-pjs commented on src/main/java/ladder/domain/UserOutput.java
> +public enum UserOutput {
👍

2019-05-28 23:48 UTC, woowahan-pjs commented on src/main/java/ladder/util/StringSplitUtils.java
> +			throw new NullPointerException(UserOutput.VIOLATE_PLAYER_NAME.getOutputMessage());
👍

2019-05-29 00:16 UTC, woowahan-pjs requested changes
세세한 Commit 덕분에 코드가 변하는 과정을 지켜보며 즐겁게 리뷰를 했어요. 💯 
구현 코드가 변하면서 테스트 코드도 함께 변하는 과정이 정말 멋졌어요. 🥇 
간단한 생각거리를 남겼으니 코드에 반영해주셔도 좋습니다.
다음 리뷰 요청 때는 Merge 하도록 하겠습니다.

2019-05-29 00:16 UTC, woowahan-pjs commented on src/test/java/ladder/domain/LadderGameInformationTest.java
> +		List<Player> players = new ArrayList<>(Arrays.asList(new Player("pobi"), new Player("jason")));
고마워요. 👍

2019-05-29 00:16 UTC, woowahan-pjs commented on src/main/java/ladder/domain/Direction.java
> +	public static int valueOf(Direction direction) {
`valueOf()`의 용도가 궁금해요! 제가 코드를 보았을 때 `getDirection()`으로 충분할 것 같은데 어떻게 생각하세요? 같이 고민해봐요.

2019-05-29 00:16 UTC, woowahan-pjs commented on src/main/java/ladder/domain/Players.java
> +public class Players {
일급 컬렉션 💯

2019-05-29 00:16 UTC, woowahan-pjs commented on src/main/java/ladder/domain/Direction.java
> +	public static int valueOf(Direction direction) {
`valueOf()`의 용도가 궁금해요! 제가 코드를 보았을 때 `getDirection()`으로 충분할 것 같은데 어떻게 생각하세요? 같이 고민해봐요.

2019-05-29 00:16 UTC, woowahan-pjs commented on src/main/java/ladder/domain/Rewards.java
> +public class Rewards {
일급 컬렉션 💯

2019-05-29 00:24 UTC, woowahan-pjs commented on src/main/java/ladder/domain/Point.java
> +public class Point {
리뷰하다 재밌어서 더 남겨봐요. 👍 

- `Point` 인스턴스가 만들어지는 경우의 수는 몇 가지 일까요?
- 미리 생성하여 필요할 때마다 사용해볼 수 있을까요?
- 위의 방식은 어떤 장점이 있을까요?

2019-05-29 00:27 UTC, woowahan-pjs commented on src/main/java/ladder/domain/Point.java
> +public class Point {
리뷰하다 재밌어서 더 남겨봐요. 👍

- Point 인스턴스가 만들어지는 경우의 수는 몇 가지 일까요?
- 미리 생성하여 필요할 때마다 사용해 볼 수 있을까요?
- 위의 방식은 어떤 장점이 있을까요?

2019-05-29 05:56 UTC, yjll1019 commented on src/main/java/ladder/domain/Direction.java
> +	public static int valueOf(Direction direction) {
네! 수정했습니다! 제가 너무 어렵게 생각했던 것 같네요ㅠㅠ 감사합니다

2019-05-29 05:56 UTC, yjll1019 commented on src/main/java/ladder/domain/Point.java
> +public class Point {
1. Point 인스턴스가 만들어지는 경우의 수는 몇 가지 일까요?
: (true,true)를 제외한 (true, false), (false, true), (true, false) 총 3가지 입니다.
2.  미리 생성하여 필요할 때마다 사용해 볼 수 있을까요?
: 넵
3. 위의 방식은 어떤 장점이 있을까요?
 : 같은 값을 가지는 인스턴스가 필요할 때마다 생기지 않고, 하나의 인스턴스를  참조하여 공유할 수 있습니다. 따라서 프로그램 실행 시 사용되는 메모리를 줄일 수 있다고 생각합니다!

2019-05-29 05:56 UTC, yjll1019 commented on src/main/java/ladder/domain/Point.java
> +	public Point valueOf(boolean leftPosition, boolean currentPosition) {
코치님께 여쭤보고 싶은 부분이 있는데요!
테스트 코드를 위해서 현재 valueOf 메소드의 접근제어자를 public으로 선언했는데요.
private으로 변경할 경우 테스트 코드는 어떻게 작성해야 좋을까요?..
Point 객체를 생성할 수 있는 곳(생성자와  static final Point)은 모두 private으로 지정해서 테스트 하기가 어려움이 따르는 것 같은데 차라리 static으로 생성한 Point 객체를 public으로 선언하는게 더 좋을까요?

2019-05-29 05:57 UTC, yjll1019 commented
코치님 자세한 피드백 너무 감사드려요.
혹시 재밌는 부분이나 수정할 부분 있으면 머지하지마시고 알려주세요...
퀘스트 깨는 기분 들어서 재밌어요^________^

2019-05-29 06:42 UTC, woowahan-pjs commented on src/main/java/ladder/domain/Point.java
> +public class Point {
👍

2019-05-29 06:43 UTC, woowahan-pjs commented on src/main/java/ladder/domain/Point.java
> +	public Point valueOf(boolean leftPosition, boolean currentPosition) {
테스트를 위해 메서드를 public으로 바꿔야 할 때는 아래의 글이 도움 될 거예요.
https://www.slipp.net/questions/253

2019-05-29 07:11 UTC, woowahan-pjs requested changes
테스트를 위한 메서드에 대해 고민해보고 Merge 하도록 해요!

2019-05-29 07:11 UTC, woowahan-pjs commented on src/main/java/ladder/domain/Point.java
> +		if (leftPosition && currentPosition) {
코드 중복!

2019-05-29 07:11 UTC, woowahan-pjs commented on src/main/java/ladder/domain/Point.java
> +		if (leftPosition && currentPosition) {
코드 중복!

2019-06-08 02:34 UTC, yjll1019 commented on src/main/java/ladder/domain/Point.java
> +		if (leftPosition && currentPosition) {
네! 수정했습니다~!

2019-06-08 06:21 UTC, yjll1019 commented
Jason 코치님 안녕하세요! 리뷰 요청이 너무 늦어서 죄송합니다ㅠㅠ
test 를 위한 메서드에 대해 주신 문서를 보고 생각해봤는데요.

처음에는 private 메서드에 대한 테스트를 이 메서드를 호출하는 public메서드를 테스트할 수 있지 않을까 생각했습니다. 하지만 현재 사다리 게임에서 다리 사이의 선(Point)을 생성하는 기능은 핵심 기능이 아닐까 생각했고, Point를 생성하는 기능에 대한 테스트 메서드 없이 프로그램을 완료하기엔 스스로 불만족스러웠습니다.

그리고 Point클래스의 역할에 대해서 다시 생각해봤는데요. 제가 처음에 Point클래스를 생성한 이유는 사다리의 다리에서 다른 다리로 넘어가기 위해 양 옆으로 이동할 수 있는지 여부를 나타내기 위해서였습니다. 하지만 수정 전의 코드를 보았을 때 메서드의 인자로 받은 Point클래스의 상태(양 옆 true/false)에 따라서 새로운 Point인스턴스를 반환하는 역할 또한 Point클래스가 가지고 있었고, 이 부분은 Point클래스의 역할이 아니라고 생각되어 PointGenerator 클래스를 새로 생성했습니다.

PointGenerator 클래스를 새로 생성하면서 수정 전의 접근제어자가 private이었던 거의 모든 필드 또는 메소드들이 public 으로 변경되었습니다. 이 부분에 대해서 여전히 아쉽지만 수정 전보다 테스트 메서드를 각 클래스의 역할에 맞게 작성할 수 있어서 만족스러웠습니다!

제가 좋은 방향으로 리팩토링을 했는지 고민이 되는데요. 코치님께서 조언해주시면 감사하겠습니다!

2019-06-11 02:27 UTC, woowahan-pjs approved these changes
축하합니다! 101개의 Commit이 작성되었어요. 🥇 
`Point`에 대한 테스트 코드를 고민하다 단일 책임 원칙(single responsibility principle)까지 온 것 같아요.
어쩌면 `Point`에 `PointGenerator`가 생긴 것처럼,
`Ladder#createLadder(int, int)`, `Line#generateLine(int)`에도 Generator가 필요할지 몰라요.
질문에 대한 답으로 아래의 글이 도움 되면 좋겠어요.

- http://codingnuri.com/seven-virtues-of-good-object

수많은 피드백을 반영하고자 대단히 고생 많으셨습니다. 💯 
이만 Merge 하겠습니다.

2019-06-11 02:27 UTC, merged