[사다리 게임] 해리 미션 제출합니다.
woowacourse/java-ladder pull request #47
Opened 2019-05-20 04:32 UTC by LeeYounghyeon

페어를 끝내고 이해가 되지 않는 부분을 이해하고자 혼자 다시 구현해보았습니다. LadderGameSolo 피드백 해주시면 감사하겠습니다!

2019-05-24 02:35 UTC, woowahan-pjs requested changes
기본적으로 지켜야 할 프로그래밍 원칙을 잘 지켜주셨어요. 👍 
아래 두 가지 사항을 중점으로 고민해보고 개선을 하면 좋을 것 같아요.

- MVC 패턴을 쓰는 이유
- 일급 컬렉션을 써야할 이유

그 외에도 몇 가지 의견을 남겨놓았으니 충분히 고민하고 도전해보세요!
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/view/InputView.java
> +    private static final String REGEX_NAME = "^([a-zA-Zㄱ-ㅎ가-힣0-9]{1,5}){1}(,[a-zA-Zㄱ-ㅎ가-힣0-9]{1,5}){1,}$";
이미 매직넘버의 단점을 알고 상수의 필요성을 알고 있네요! 👍 여기에 첨언을 한다면 `String`을 패턴 매칭을 위해 `Pattern`으로 바꾸는 것은 꽤나 비싼 행위입니다. 미리 `Pattern`으로 만들어 사용하는 것은 어떨까요?

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/Main.java
> +        gameView.run();
`GameView`의 `run()`은 View보다는 Controller의 기능을 하는 것 같아요. MVC 패턴은 어떤 장점이 있어 사용할까요? View와 Model 사이에 Controller가 있는 이유를 알아보면 좋을 것 같아요.

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/constant/MessageContants.java
> +    public static final String DELIMITER_COMMA = ",";
Model에서도 사용하는 값이네요.

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/constant/MessageContants.java
> +public class MessageContants {
`MessageContants`가 아닌 `MessageConstants`가 아닐지 조심스럽게 추측해 봅니다.

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/constant/MessageContants.java
> +public class MessageContants {
View에서 사용하는 메시지를 한곳에 잘 모아놓은 것 같아요. 👍 글로벌 서비스를 위한 다국어 지원, 여러 개의 데이터베이스 연결 등의 요구 사항을 충족하기 위해 종종 사용하는 방법이기도 합니다. Controller와 Model에서 같이 사용하지 않도록 조심하면 되겠어요.

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/domain/Direction.java
> +    public boolean equals(Object o) {
`equals()` & `hashCode()` 👍

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/domain/Direction.java
> +    public int hashCode() {
`equals()` & `hashCode()` 👍

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/domain/Ladder.java
> +    private List<Line> lines;
놀라워요! 이미 일급 컬렉션의 개념을 알고 계신 것 같아요. 👍 아래의 글을 읽고 일급 컬렉션을 내 것으로 확실히 완성시켜보세요.
https://jojoldu.tistory.com/412

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/domain/Ladder.java
> +        return lines;
`lines`에 대한 주솟값을 그대로 외부에 전달하면 어떤 문제가 발생할까요?

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/domain/Line.java
> +        return directions;
마찬가지로 `directions`에 대한 주솟값을 그대로 외부에 전달하면 어떤 문제가 발생할까요?

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/domain/Position.java
> +public class Position {
VALUE OBJECT 👍

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/domain/Position.java
> +        return new Position(this.position + 1, max);
VALUE OBJECT는 불변이 특징입니다. 💯

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/view/GameView.java
> +    public void run() {
`GameView`가 로직의 흐름까지 제어하고 있어요. View의 짐을 덜어줍시다. 👍

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/view/InputView.java
> +            return inputName();
캡틴께서 "반복문 대신 재귀 함수로 구현할 수 있다."라고 알려주셨어요. 하지만 재귀를 사용하면 어떤 위험이 있을까요? 만약 재귀를 사용하지 않는다면 어떻게 문제를 해결할 수 있을까요?

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/stringAddCalculator/Calculator.java
> +        if ("".equals(input) || input == null) {
`NullPointerException`을 예방하는 방법 💯

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/stringAddCalculator/Calculator.java
> +        Matcher matcher = Pattern.compile("//(.)\n(.*)").matcher(input);
`"//(.)\n(.*)"`와 같은 매직넘버는 의미를 나타낼 수 있는 상수로 치환하여 코드의 가독성을 높여보는 것은 어떨까요?

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/domain/Member.java
> +        while (!position.isUnder()) {
아래의 글을 읽고 코드에 반영하면 어떨까요?
https://schneide.blog/2014/08/03/dont-ever-not-avoid-negative-logic

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/constant/MessageContants.java
> +    public static final String ERROR_DUPLICATE_NAME = "이름이 중복되었습니다.";
Model에서도 사용하는 값이네요.

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/domain/Ladder.java
> +        for (int i = 0; i < lines.size() - 1; i++) {
왜 `lines.size() - 1`이 필요한 지 메서드 분리를 통해 설명하면 어떨까요?

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/domain/Ladder.java
> +        if (lines.get(index).getDirections().get(i).move() != 0) {
`get()`을 계속 사용하는 것이 아닌 객체에 메시지를 던지도록 구조를 바꿔보면 어떨까요?

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/domain/Direction.java
> +    public Direction(boolean left, boolean right) {
"`left`와 `right`는 동시에 `true`일 수 없다."를 코드로 표현하면 어떨까요?

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/view/GameView.java
> +        List<Member> members = LadderGame.makeMembers(names, targetName, height);
`List<Member>`를 일급 컬렉션으로 만들어보면 어떨까요?

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/view/GameView.java
> +            String result = LadderGame.getResult(ladder, member, inputResult);
View가 Controller를 호출하여 흐름 제어하고 있는 것 같죠?

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/view/GameView.java
> +            int directionMoveResult = ladder.getLines().get(i).getDirections().get(directionIndex).move();
객체에 메시지를 던지도록!

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/domain/Ladder.java
> +    private void setBridge(int index, Random random, int i) {
`setBridge()`의 기능이 다소 복잡하네요. 의미를 설명할 수 있는 메서드로 한 번 더 분리하는 것이 좋아 보여요.

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/domain/Ladder.java
> +        lines.get(index + 1).getDirections().set(i, new Direction(right, false));
혹시 위의 코드는 아래의 코드를 의도한 것 아닐까요?

```java
lines.get(index).getDirections().set(i + 1, new Direction(right, false));
```

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/controller/LadderGame.java
> +        if (MessageContants.MESSAGE_ALL.equals(targetName)) {
NullPointerException을 예방하는 방법 💯

2019-05-24 02:35 UTC, woowahan-pjs commented on src/main/java/ladderGame/Main.java
> +public class Main {
사용하지 않는 `ladderGame` 패키지는 과감하게 지우는 것이 좋겠어요. 👍

2019-05-27 15:52 UTC, LeeYounghyeon commented on src/main/java/ladderGameSolo/domain/Ladder.java
> +        lines.get(index + 1).getDirections().set(i, new Direction(right, false));
이 부분은 lines의 값들은 사다리의 세로선이고 사다리의 첫 세로선의 우측에 다리가 연결되면 다음 세로선의 좌측에도 연결되는 것을 구현한 것입니다! 피드백 보면서 많은 고민을 하면서 수정해보았는데 부족한 느낌이 많이 듭니다ㅜㅜ

2019-05-27 15:52 UTC, LeeYounghyeon commented on src/main/java/ladderGameSolo/view/InputView.java
> +            return inputName();
재귀함수를 사용하면 스택오버 플로우가 날수있습니다! 아무리 고민해봐도 반복문 외에 다른 방법이 생각나지 않아서 저 부분만 반복문으로 구현해보았습니다. 이부분은 조금 더 고민해보겠습니다!

2019-05-27 15:52 UTC, LeeYounghyeon commented on src/main/java/ladderGameSolo/Main.java
> +        gameView.run();
자바단에서의 MVC패턴에 대해 많은 고민이 있었는데요! 레이싱카 피드백에서 컨트롤러에서 아웃뷰를 호출했다가  문제가 될수도 있다는 피드백을 받았습니다. 그래서 위 코드처럼 했는데 이것 또한 잘못된 해결책이라는 것을 알았고, 많은 고민을 하다가 메인에서 아웃뷰를 생성해 컨트롤러로 넘겨주는 방법을 선택하게 되었습니다. 그것 조차 맞는 해결책인지 모르겠습니다ㅜㅜ

2019-06-03 23:15 UTC, woowahan-pjs requested changes
MVC 패턴에 대한 고민이 많아 보입니다.
테스트 코드는 꾸준히 작성 부탁드립니다.
몇 가지 의견을 남겨놓았으니 충분히 고민하고 도전해보세요!

2019-06-03 23:15 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/domain/Direction.java
> +        }
`left`와 `right`는 동시에 `true`일 수 없다. 👍

2019-06-03 23:15 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/domain/Direction.java
> +            return -1;
매직넘버!

2019-06-03 23:15 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/domain/GameMember.java
> +public class GameMember {
일급 컬렉션 👍 복수 명사를 클래스명으로 사용하면 컬렉션임을 더 쉽게 표현할 수 있겠죠?

2019-06-03 23:15 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/domain/GameMember.java
> +        this.members = members;
`members`에 대한 주솟값을 그대로 받아 사용하면 어떤 문제가 발생할까요?

2019-06-03 23:15 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/controller/LadderGame.java
> +    public LadderGame(GameView gameView) {
`GameView`에 대한 의존성을 외부에서 주입받도록 만든 이유가 궁금해요.

2019-06-03 23:15 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/controller/LadderGame.java
> +        int height = InputView.inputHeight();
`height`는 클래스로 포장하여 사용해 볼 수 있겠어요.

2019-06-03 23:15 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/view/GameView.java
> +        int resultIndex = member.getResultIndex(ladder);
View는 Model의 주요 기능을 실행하는 것이 아닌 화면을 보여주는 데에 집중하면 어떨까요?

2019-06-03 23:15 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/controller/LadderGame.java
> +        gameView.printLadderInfo(names, inputResult, height, ladder);
`height`는 `Ladder` 안에서 구할 수 있겠죠?

2019-06-03 23:15 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/domain/Ladder.java
> +        for (int i = 0; i < getSettingLineSize(); i++) {
반복 문의 조건식 중 `getSettingLineSize()`에 대한 결과 값을 지역 변수에 담아 사용하는 것과 그렇지 않은 것은 어떤 차이가 있을까요?

2019-06-03 23:15 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/domain/Ladder.java
> +        if (lines.get(index).getDirectionByIndex(i).move() != 0) {
객체에 메시지를 던지도록!

2019-06-04 15:44 UTC, LeeYounghyeon commented on src/main/java/ladderGameSolo/domain/Ladder.java
> +        for (int i = 0; i < getSettingLineSize(); i++) {
getSettingLineSize가 주는 값이 계속 변할수 있습니다! 수정하겠습니다.

2019-06-04 15:47 UTC, LeeYounghyeon commented on src/main/java/ladderGameSolo/domain/Ladder.java
> +        for (int i = 0; i < getSettingLineSize(); i++) {
getSettingLineSize가 주는 값이 계속 변할수 있습니다! 수정하겠습니다.

2019-06-05 11:52 UTC, LeeYounghyeon commented on src/main/java/ladderGameSolo/domain/GameMember.java
> +        this.members = members;
객체 외부에서 객체 내부의 값을 마음대로 바꿀수 있습니다. 쉘로우 카피와 딥 카피에 대해서 공부 할 수 있었습니다!

2019-06-11 00:55 UTC, woowahan-pjs approved these changes
수많은 피드백을 반영하고자 대단히 고생 많으셨습니다. 💯 
좋은 개발자가 되기 위한 소중한 밑거름이 되었길 바랍니다.
이만 Merge 하겠습니다.

2019-06-11 00:55 UTC, woowahan-pjs commented on src/main/java/ladderGameSolo/view/InputView.java
> +public class InputView {
현재 `InputView`는 콘솔 화면과 상호 작용하는 기능과 입력된 값의 유효성을 검사하는 기능 두 가지로 나눌 수 있겠어요. 단일 책임 원칙(single responsibility principle)이라는 것을 찾아보고 아래의 질문에 답해보면 좋을 것 같아요.

- 객체 지향 프로그래밍에서 단일 책임 원칙(single responsibility principle)이란 무엇일까요?
- 그것을 하는 이유는 무엇일까요?
- 단일 책임 원칙을 `InputView`에는 어떻게 적용할 수 있을까요?

2019-06-11 00:55 UTC, merged