[사다리 게임] 루피 미션 제출합니다.
woowacourse/java-ladder pull request #5
Opened 2019-05-16 09:20 UTC by MrKwon

2019-05-17 01:11 UTC, MrKwon commented on src/main/java/ladder/domain/ladder/Floor.java
> +    int getFloor() {
사다리에 관련된 클래스들을 패키지로 묶고 패키지 내에서만 사용하는 메서드라서 접근 제어자를 디폴트로 했는데 괜찮을까요? public 으로 하는게 좋을까요?

2019-05-17 02:29 UTC, MrKwon commented on src/main/java/ladder/domain/ladder/Floor.java
> +    int getFloor() {
그리고 이렇게 관련된 클래스들을 묶어서 패키지로 만들어도 괜찮을까요??

2019-05-17 15:36 UTC, jihan805 requested changes
안녕하세요 리뷰를 담당하게 된 써머입니다. 
전체적인 객체 설계, 테스트 코드 작성 👍 몇가지 피드백 남겼으니 확인 부탁드릴게요.
궁금한 부분이 있으면 코멘트/dm 주세요!

2019-05-17 15:36 UTC, jihan805 commented on src/test/java/ladder/domain/HeightTest.java
> +}
HeightTest가 2개에요!
특별한 이유가 있을까요?

2019-05-17 15:36 UTC, jihan805 commented on src/main/java/ladder/view/OutputView.java
> +    }
toString을 Override 하였어요. .toString()을 제거하고 출력해볼까요?

2019-05-17 15:36 UTC, jihan805 commented on src/main/java/ladder/domain/ladder/Line.java
> +
Boolean이 의미하는 것은 사다리(Ladder) 한 줄(Line)에 "선이 있는지 없는지" 입니다.
이 역시 Point/Position 등과 같이 객체로 추출할 수 있지 않을까요?
조금 더 객체 지향적인 설계를 연습해보면 좋을 것 같아요. 
약간의 구조 변경으로 Test 클래스를 위해 작성한, public Line(List<Boolean> horizontal) 와 관련 메서드들이 없어질 수 있을 것 같아요!
한번 고민해볼까요?

2019-05-17 15:36 UTC, jihan805 commented on src/main/java/ladder/domain/ladder/Ladder.java
> +
Line 클래스와 같이 초기화는 생성자에서 함께 해도 좋을 것 같아요.

2019-05-17 15:36 UTC, jihan805 commented on src/main/java/ladder/domain/ladder/Height.java
> +        if (number <= 0) {
코드 전체적으로 의미를 나타낼 수 있는 숫자의 경우, 숫자 대신 상수를 활용하면 어떨까요?

2019-05-17 15:36 UTC, jihan805 commented on src/main/java/ladder/domain/ladder/Line.java
> +    private static final String HEADER_HORIZONTAL_LINE = "   ";
클래스 내 선언 순서는 아래와 같아요.
class A {
    상수(static final) 또는 클래스 변수
    인스턴스 변수
    생성자
    메소드
}
Line 클래스를 한번 살펴보면 어떨까요?

2019-05-17 15:36 UTC, jihan805 commented on src/main/java/ladder/controller/Main.java
> +    }
강의 중, 반복문 사용 대신 재귀 사용에 대해 위와 같은 형태의 예제에 대해 학습 했다고 알고있어요!
재귀를 사용할 경우 문제점에 대해서 고민해보면 어떨까요?

2019-05-17 15:36 UTC, jihan805 commented on src/main/java/ladder/domain/LadderGame.java
> +
전체적으로 필요한 클래스 추출 👍 
현재 LadderGame의 구조는 새로운 Ladder 생성하고, 결과를 출력하기 위해 all/이름 을 이용해 Ladder에 플레이어의 결과를 요청하고 있어요.

제 생각에 Ladder의 역할을 사다리를 Line을 만들어 사다리를 생성하고, 움직이는 역할이면 충분할 것 같아요.
GameResult등과 같이 게임 결과와 관련된 로직을 구현하는 클래스를 추가하면 어떨까요?

2019-05-17 15:36 UTC, jihan805 commented on src/main/java/ladder/domain/ladder/Line.java
> +        return bool ? HORIZONTAL_LINE : NO_HORIZONTAL_LINE;
메서드의 이름을 작성할때 줄여쓰지 않도록 해요!
추가로 bool과 같은 네이밍 보다는 비록 파라미터지만 어떤 파라미터인지 나타낼 수 있는 네이밍이 더 좋을 것 같아요!

2019-05-17 15:36 UTC, jihan805 commented on src/test/java/ladder/domain/LineTest.java
> +}
메서드간 공백에 신경쓰면 어떨까요?

전체적으로 꼼꼼하게 테스트 코드 작성하셨어요 👍 

하지만, 테스트 메서드의 이름만 보고 한눈에 이게 무슨 테스트인지 파악하기 어려웠어요!
테스트 코드 역시 이해하기 쉽게 실제 product 코드 처럼 작성하는 것이 좋아요! 네이밍도 마찬가지로요!
어떤 메서드를 어떤 상태에 대해 테스트 할 것이고, 그로 인해 기대하는 것이 무엇인지 담겨있도록 작성하면 좋을 것 같아요!

2019-05-18 13:39 UTC, MrKwon commented on src/test/java/ladder/domain/HeightTest.java
> +}
패키지 구조를 변경하면서 잘못 생성한 것 같습니다 ㅠ

2019-05-18 13:41 UTC, MrKwon commented on src/main/java/ladder/domain/ladder/Ladder.java
> +
반영하였습니다 !

2019-05-18 13:43 UTC, MrKwon commented on src/main/java/ladder/domain/ladder/Height.java
> +        if (number <= 0) {
이건 제가 놓친 부분입니다. 감사합니다 !

2019-05-18 13:45 UTC, MrKwon commented on src/main/java/ladder/domain/ladder/Line.java
> +    private static final String HEADER_HORIZONTAL_LINE = "   ";
어떤 public 메서드에서 사용된 private 메서드를 바로 아래에 배치하는 것이 좋다고 하셔서 그렇게 했는데 생성자에서 private 메서드를 사용해도 생성자를 먼저 모아둔 후 이후에 배치해는 것이 옳은 것인가요?

2019-05-18 13:52 UTC, MrKwon commented on src/main/java/ladder/controller/Main.java
> +    }
재귀가 깊어지면 StackOverflowError 가 발생하는 것으로 알고 있습니다. 그래서 재귀 호출을 중단해 줄 부분이 있는 것이 좋다고 알고 있는데, 위의 게임 같은 경우는 예외적인 케이스 입력이 StackOverflowError 가 발생할 정도로 입력을 많이 시도하지 않을 것으로 생각하여 재귀를 사용하였습니다 !

2019-05-18 13:58 UTC, MrKwon commented on src/test/java/ladder/domain/LineTest.java
> +}
감사합니다. 미션을 진행하면서 TDD 로 구현하는 것에 집중하다보니 이런 실수를 하게 된 것 같습니다. 이런 부분에 대해서 실수하지 않도록 주의를 기울여야 해야겠네요. 😂

2019-05-20 12:21 UTC, MrKwon commented
안녕하세요 써머님
먼저 정성스러운 피드백 감사드립니다.

피드백을 반영하여 여러 부분들을 수정해 보았습니다.
먼저 기존의 Line 을 Horizontal 로 바꾸고 그 안에 들어있는 가로 선들을 Point 클래스로 만들어 Boolean 값을 다루도록 하였습니다.
이렇게 변경하니 이와 관련된 다른 객체들의 메서드들을 더 단순하게 할 수 있었던 것 같습니다.
또한 기존의 Height 도 LadderHeight 로 바꾸고
원래는 playerNumber 로 처리하던 것들도 LadderWidth 로 변경하여 처리하도록 하였습니다.
마지막으로 OutputView 에서 처리할 일들을 객체에서 toString으로 가져오던 로직들도 피드백을 반영하여 getter 를 써서 가져와 OutputView 에서 보여주기 위한 처리를 하도록 바꾸어 보았습니다.

내일(5/21) 동원 예비군에 가게 되는데 피드백 남겨주시면서 일단 머지해주시면 예비군이 끝나고 난 후 피드백 반영해서 DM 이나 다시 피드백 요청하도록 하겠습니다 ! 감사합니다.

2019-05-20 14:59 UTC, jihan805 commented on src/main/java/ladder/domain/ladder/Horizontal.java
> +            horizontal.add(Point.first());
전체적으로 숫자 대신 상수를 활용하면 좋을 것 같아요.

2019-05-20 14:59 UTC, jihan805 commented on src/main/java/ladder/domain/ladder/Point.java
> +
Point 추출 👍 
private Boolean left, private Boolean right 는 방향을 나타내고 있어요!
Direction과 같은 클래스로 추출할 수 있을 것 같아요!

2019-05-20 14:59 UTC, jihan805 commented on src/main/java/ladder/domain/ladder/Line.java
> +    private static final String HEADER_HORIZONTAL_LINE = "   ";
넵 !  생성자는 예외입니다.

2019-05-20 15:10 UTC, jihan805 requested changes
안녕하세요 루피님 !
전체적으로 깔끔하게 잘 구현하셨습니다 👍 
아주 간단한 피드백 남겼으니 확인해주세요.
궁금한 부분이 있으면 코멘트/dm주세요 :)

2019-05-20 15:10 UTC, jihan805 commented on src/main/java/ladder/domain/ladder/Point.java
> +
정적 팩터리 메서드를 사용하셨어요!
이 역시 getLeft와 위치가 바뀐거같아요.

2019-05-20 15:10 UTC, jihan805 commented on src/main/java/ladder/domain/ladder/Ladder.java
> +        }
current.move(horizontal.get~)하는 대신
horizontal.move(current position)과 같이 구현해보면 어떨까요?

2019-05-23 14:13 UTC, MrKwon commented on src/main/java/ladder/domain/ladder/Horizontal.java
> +            horizontal.add(Point.first());
피드백 반영하였습니다 !
근데 이 부분은 의미가 있는 이름을 지을 수 있는 숫자만 상수로 정의하고 사용하는 것 아닌지 궁금합니다 !

2019-05-23 14:13 UTC, MrKwon commented on src/main/java/ladder/domain/ladder/Point.java
> +
피드백 반영하였습니다 !

2019-05-23 14:14 UTC, MrKwon commented on src/main/java/ladder/domain/ladder/Point.java
> +
정적 팩터리 메서드의 경우 생성자 바로 아래에 위치하는 것 인가요?

2019-05-23 14:23 UTC, MrKwon commented on src/main/java/ladder/domain/ladder/Ladder.java
> +        }
이 피드백은 이해가 되지 않는 부분이 있어 일단 반영하지 않고 리뷰 요청을 했습니다.
객체로 독립시키는 이유는 해당 객체에 관련된 데이터와 동작을 담기 위함으로 알고 있습니다.
Horizontal 객체는 사다리의 가로줄을 나타내는 객체이고
Position 은 사다리 게임의 진행에서 사다리를 거쳐 내려오는 점을 나타내는 객체인데
Horizontal 의 메서드로 move 를 하면 Position 과 관련된 동작을 Horizontal 에서 처리하는 느낌인데 제가 객체로 독립시키는 이유를 잘못 알고 있는 것 인가요?

2019-05-24 13:56 UTC, jihan805 approved these changes
안녕하세요 루피님!
전체적으로 피드백 반영 잘해주셔서 감사합니다 :)  
몇가지 코멘트 남겼으니 확인 부탁드릴게요!
머지 진행하겠습니다.

2019-05-24 13:56 UTC, jihan805 commented on src/main/java/ladder/domain/ladder/Horizontal.java
> +            horizontal.add(Point.first());
우선  if (i == FIRST_INDEX)  요기 부분은 첫번째 인지 판단하는 거니까  FIRST_INDEX라고 의미를 지어주면 더 명확할 것 같아요!
혹은 
for (int i = FIRST_INDEX; i < width.getLadderWidth(); i++) {
            addFirst(i);
            addMiddle(width, i);
            addLast(width, i);
        }
를 
 addFirst();
for() {
addMiddle();
}
addLast()
와 같이 해도 좋을 것 같습니다!

2019-05-24 13:56 UTC, jihan805 commented on src/main/java/ladder/domain/ladder/Point.java
> +
추가로 정적 팩터리 메서드에 대해 조금 더 자세히 찾아보면 어떨까요?
주로 생성자 대신 정적 팩토리 메서드를 사용합니다. 
 
```
private Point(Direction left, Direction right) {
        this.left = left;
        this.right = right;
    }
    private static Point of(Direction first, Direction second) {
        return new Point(first, second);
    }
static Point first() {
        return of(new Direction(false), RandomGenerator.get());
    }
```
first -> of 를 호출하는 대신 
```
 public static Point generateFirst() {
        return new Point(new Direction(false), RandomGenerator.get());
}
```
이렇게 사용하는 것이 더 깔끔하지 않을까요?

2019-05-24 13:56 UTC, jihan805 commented on src/main/java/ladder/domain/ladder/Ladder.java
> +        }
객체지향의 사실과 오해라는 책을 보면 객체와 실제 세계는 비슷한듯 다르다고 표현한 부분이 있습니다. (이 책 꼭 읽어보세요)
현실 세계라면 사다리는 가만히 있고, 위치가 변하는 것이 맞겠죠?
하지만 객체 세계에서는 각 객체가 주체가 되어 생각하는 것입니다. (객체가 서로 협업을 해요!)
Ladder(사다리)에서 moveToResult를 구현하였듯, 사다리의 한 줄도 움직일 수 있는지에 대한 정보를 List로 가지고 주체가 되어 움직임에 대한 판단을 통해 그 결과를 주도록이요!
객체 세계에서는 이렇게 각 객체를 중심으로 생각하면 어떨까요?

제가 해당 부분에 대해 피드백을 남긴 이유 역시, 사다리를 구성하기 위해 필요한 객체들을 정말 잘 추출하셨으니
그 객체들을 이용해(협업시켜) 사다리 실행의 결과도 구할 수 있기 때문입니다!

2019-05-24 13:56 UTC, jihan805 commented on src/test/java/ladder/domain/ladder/PointTest.java
> +}
이동에 대한 테스트 구현 👍 
추가로 생성에 대한 테스트도 작성하면 좋을 것 같아요!( 줄이 겹쳐지는 경우등에 대해)

2019-05-24 13:57 UTC, merged

2019-05-27 04:23 UTC, MrKwon commented on src/main/java/ladder/domain/ladder/Ladder.java
> +        }
감사합니다 고민해보고 피드백 반영해보겠습니다 !