[1단계 - 사다리 생성] 깃짱(조은기) 미션 제출합니다.
woowacourse/java-ladder pull request #53
Opened 2023-02-15 08:39 UTC by eunkeeee

안녕하세요!_!_!
사다리 게임 구현 완료했습니다

리뷰 감사합니다!

2023-02-17 03:22 UTC, jamie9504 requested changes
깃짱, 안녕하세요! 리뷰어 제이미입니다. 😄 

이번 미션도 고생하셨습니다 👏 👏 👏 👏 👏 

이번 미션은 TDD로 잘 구현하였는가, Test Code 기반의 리팩토링을 잘 하였는가를 중점적으로 보았는데요.
첫 커밋(https://github.com/woowacourse/java-ladder/pull/53/commits/0d9ba8b47722c667688cef919432a71907fa193f) 부터 Next를 누르며 코드리뷰를 했기 때문에, 추후 보강된 부분에 대해서 수정 코멘트를 남긴 경우가 조금 있습니다.
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/59511689/219540121-9ca60777-20f0-492c-bb5a-4f6fc62e4080.png">

우선 테스트 코드 기반으로 TDD 잘 진행해주신 것 같습니다.
추후 원시값 포장, 일급 컬렉션 사용, 내부 로직 수정 등의 리팩터링도 잘 진행된 것 같구요.

커밋할 때, 클래스명을 넣게 되면 나중에 커밋 단위가 커졌을 때는 넣지 못하니 통일성이 떨어지는 점 참고해주세요!

이것 저것 생각해보면서 성장하시면 좋겠다는 마음으로 의견을 묻는 코멘트들을 조금 남겼는데,
어떤 의미인지 설명이 부족하다 싶은 부분은 코멘트 남겨주시고 스킵하셨다가 리뷰요청 다시 주시면 추가 코멘트 남겨두겠습니다.

질문 주신 부분은 아래에 답변 달아둘게요. 😄 

> 저는 아래같이 코드를 작성하고 있는데, 테스트 코드에서 에러 메세지의 종류까지 테스트하고 싶은데, 어떻게 할 수 있을까요?
> 
> 여기에서 .withMessage() 메서드를 사용해 예외 메세지를 하드코딩 없이 그대로 테스트하고 싶은데, 어떻게 해야 할 지 뚜렷한 방법이 떠오르지를 않습니다.

- 예외 메시지를 테스트 하고 싶으신 이유가 궁금하네요.
- 하드코딩 하지 않고 테스트를 한다면 어떤 이점이 있다고 생각하실까요~?
- enum을 public으로 둔다 : `%d 이상 %d 이하의 자연수만 입력해 주세요.`를 실수로 `잘 입력하세요 ^^`로 수정했다고 가정해봅시다. 그렇게 되면 하드코딩을 하지 않고 실제 코드에서 쓰는 정보로 테스트를 하기 때문에 테스트가 잘 통과되겠죠? 그러면 테스트의 존재 가치가 있을지 고민이 되는 부분이네요!
- custom exception을 만들어 테스트 한다 : 마찬가지로, 그렇게 되면 exception이 터지는 여부에 대한 테스트만 되는거지, 실제 메시지에 대한 올바른 테스트가 맞을까요?
- 이 부분 깃짱의 추가 코멘트 주시면 또 답변드릴께요 :D

2023-02-17 03:22 UTC, jamie9504 commented on src/test/java/domain/FloorTest.java
> +        assertDoesNotThrow(() -> new Floor(personCount));
(참고) 해당 커밋에는 Floor 객체가 없는데, 이럴 경우엔 이 커밋을 코드로 받는다면, 정상적인 상태가 아니겠죠?
그런 경우 이 커밋으로 누군가 rollback을 하거나, 해당 커밋만 일부 브랜치로 옮기거나 했을 때는 어떤 문제가 있을까요?

학습을 위해서, 구분하기 위한 Commit이면 괜찮은 것 같아요.
학습용이 아니라면, 깨지지 않는 코드를 한 커밋으로 묶어야 한다고 생각해요. :)

https://github.com/woowacourse/java-ladder/pull/53/commits/35330c13f9b56d2a963e9e86687b11b6ec598131

---

Floor라는 객체는 왜 personCount를 받을까요?
어떤 객체인지 이름만으론 알기가 어렵네요.

참가자의 수를 나타내고 싶었다면,
참가자와 관련된 객체명을 사용하거나, 참가자와 관련된 이름의 파라미터를 사용해야 좋았을 것 같아요.

https://github.com/woowacourse/java-ladder/pull/53/commits/35330c13f9b56d2a963e9e86687b11b6ec598131

-> 아래 커밋에서 변경되었네요.
조금 더 직관적인 네이밍 👍 

그렇지만 `Line`이라는 이름만 들었을 때, 이 객체가 어떤 걸 의미하는지 처음 코드를 봤을 때도 한 눈에 이해할 수 있을까요?

https://github.com/woowacourse/java-ladder/pull/53/commits/ede682be94569216081281e38d8f38bb64d1bc80

2023-02-17 03:22 UTC, jamie9504 commented on src/test/java/domain/FloorTest.java
> +}
[공통] 마지막에 아래와 같은 아이콘이 뜨는 이유는, 파일 끝에 개행문자(newline)가 없기 때문인데요!
<img width="28" alt="image" src="https://user-images.githubusercontent.com/59511689/217802429-005fb47d-735c-41be-acac-4bc7a20c9006.png">

문제는 없지만, IntelliJ에서 개행문자를 추가해준다던가 설정을 해두면 보기 좋을 것 같아요 :)

https://github.com/woowacourse/java-ladder/pull/53/commits/35330c13f9b56d2a963e9e86687b11b6ec598131

2023-02-17 03:22 UTC, jamie9504 commented on src/test/java/domain/FloorTest.java
> +    @Nested
계층형으로 나누셨군요 👍 

모든 테스트에 `@DisplayName`을 적용하신다면, 이 부분에도 적용해주셨으면 좋았을 것 같아요.

https://github.com/woowacourse/java-ladder/pull/53/commits/340325b09bb8f627f2cf15d0b79d89ce4d44c278#

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/domain/Floor.java
> +    public Floor(int personCount, BooleanGenerator generator) {
한 줄 한 줄이라는 의미의 Floor인 것 같네요!

이 Floor가 과연 들어오는 int가 person의 count인지를 알 필요가 있을까요?

https://github.com/woowacourse/java-ladder/pull/53/commits/aa474b894c5875822aba8a0d8ad2b25e8d503251

-> 해당 commit에서 Floor > Line으로 변경되었네요!
마찬가지로 Line이 personNumber를 받고 있는데, 객체 이름이나 성격에서 요 두 가지가 어떻게 연관이 되어 있을지 바로 와닿지는 않는 것 같아요!

https://github.com/woowacourse/java-ladder/pull/53/commits/ede682be94569216081281e38d8f38bb64d1bc80

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/domain/Floor.java
> +        }
중간중간 코드도 프로그래밍 요구 사항을 신경쓰면 좋을 것 같아요.

> indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.
> 예를 들어 while문 안에 if문이 있으면 들여쓰기는 2이다.
> 힌트: indent(인덴트, 들여쓰기) depth를 줄이는 좋은 방법은 함수(또는 메서드)를 분리하면 된다.

https://github.com/woowacourse/java-ladder/pull/53/commits/aa474b894c5875822aba8a0d8ad2b25e8d503251#

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/domain/Name.java
> +        }
같은 예외를 처리하고 있는데, If문을 분리한 이유는 무엇일까요?

https://github.com/woowacourse/java-ladder/pull/53/commits/e85eb6dc04055952a6cf19c2e323e77763b7a557

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/view/InputView.java
> +    }
싱글턴을 사용한 이유는 무엇인가요?

https://github.com/woowacourse/java-ladder/pull/53/commits/1d8d36865b4d92e60060a8337e604c0ab15a84a5

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/view/InputView.java
> +        }
괄호가 중첩되면 때론 가독성이 좋지 않은 것 같아요.

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/view/InputView.java
> +        int size = Integer.parseInt(input);
parseInt시 예외가 발생할 수도 있겠죠?

https://github.com/woowacourse/java-ladder/pull/53/commits/c69df99fe6261aa404d618326c7a613ae1db48db

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/domain/Floor.java
> +import utils.booleanGenerator.BooleanGenerator;
자바 패키지 네이밍에 대해 알아보면 좋을 것 같아요.

utils 도메인 하위에 있는 이유는 무엇일까요? 해당 패키지의 클래스들은 범용적인가요?

https://github.com/woowacourse/java-ladder/pull/53/commits/85941608ff4a679f1373f197ec0cb7694ab24091

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/domain/Name.java
> +        NameValidator.validate(name);
검증 클래스를 Static으로 분리하는 이유는 무엇인가요?

https://github.com/woowacourse/java-ladder/pull/53/commits/81ec10c716fd17adcb35f45515ad8b0cbe6f1b33

-> 이 부분 해당 커밋에서 원시값을 포장한 객체로 바꾸셨네요 👍 

static 메서드로만 구성된 유틸성 클래스를 사용하셨을 때와, 원시값을 포장한 객체를 사용하셨을 때랑 어떤 부분이 다르게 느껴지셨을지 궁금하네요.

https://github.com/woowacourse/java-ladder/pull/53/commits/ede682be94569216081281e38d8f38bb64d1bc80

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/utils/validator/LadderSizeValidator.java
> +    }
IntRange인지 검증하는 로직이 맞나요?

https://github.com/woowacourse/java-ladder/pull/53/commits/cd6150ea53591b9cbb13d5d4e48c6e6d88127d34

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/utils/validator/LadderSizeValidator.java
> +    public static final int MIN_RANGE = 1;
public으로 선언된 상수, 변수는 외부에서 호출하기 때문인가요?

https://github.com/woowacourse/java-ladder/pull/53/commits/814a4ead25164e9837bb52f44798b65f6574cfa1

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/utils/validator/LadderSizeValidator.java
> +    private enum Message {
Message를 나눈 이유가 있을까요?, Enum으로 관리하는 이유가 있나요?

https://github.com/woowacourse/java-ladder/pull/53/commits/814a4ead25164e9837bb52f44798b65f6574cfa1

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/utils/validator/LadderSizeValidator.java
> +        public static final String BASE_MESSAGE = "[ERROR] %s";
해당 부분은 format이라 `_FORMAT`를 달아줘도 좋겠네요.
이름을 명확히 하면, 사용하는 측에서 한 번에 알기 좋습니다.

https://github.com/woowacourse/java-ladder/pull/53/commits/814a4ead25164e9837bb52f44798b65f6574cfa1

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/view/OutputView.java
> +        System.out.println("실행결과\n");
[공통] 개행 관련해서는 아래 항목들을 알아보면 좋을 것 같아요~

System.lineSeparator()
System.getProperty("line.separator")
String#format() - %n

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/domain/Floors.java
> +            floors.add(new Floor(personCount, new RandomBooleanGenerator()));
floors가 `RandomBooleanGenerator`를 생성하는 책임을 가지는 게 좋을까요?

https://github.com/woowacourse/java-ladder/pull/53/commits/65b2bbbfed31961a1b7b0c0d344a8327e8f8553a

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/view/OutputView.java
> +            StringBuilder result = new StringBuilder();
`result`보다 적합한 이름은 없을까요?
`result`만 봤을 땐, 무엇을 가지고 있을지 예측하기가 어려워요.

https://github.com/woowacourse/java-ladder/pull/53/commits/65b2bbbfed31961a1b7b0c0d344a8327e8f8553a

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/domain/Name.java
> +        validateLength(name);
`validateBlank`는 공란이 있는 경우를 검증하는 걸까요, 공란이 없는 경우를 검증하는 걸까요?

사람에 따라 약간 이름이 모호하다고 느낄 수도 있을 것 같아요!

또한, 이름이 null로 들어오게 되면 이건 괜찮은걸까요~?

https://github.com/woowacourse/java-ladder/pull/53/commits/c9abcd6d6d3bcddbd7b879b95e1e8e1b920a0b55

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/domain/Lines.java
> +
소소한 부분이지만 전반적으로 개행 방식을 통일해주는 것도 좋은 것 같아요.

https://github.com/woowacourse/java-ladder/pull/53/commits/ede682be94569216081281e38d8f38bb64d1bc80

-> 나중에 일괄로 바꿔준 부분이 있네요 👍 

https://github.com/woowacourse/java-ladder/pull/53/commits/524efaa54af63148dd736ad3b7374b85a582eeca

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/domain/Line.java
> +    }
PersonNumber를 여기서 생성하는 것이 좋을까요? (매번 같은 값을 생성함)

https://github.com/woowacourse/java-ladder/pull/53/commits/48f50eb56de657c50a74c2e4b946a243eecfa17c

-> 해당 commit에서 요 부분을 제거하셨네요!
Lines에 personNumber에 대한 검증이 사라져버렸는데,
personNumber에 음수나 0이 들어와도 Lines는 의도한 역할을 할 수 있는걸까요?

https://github.com/woowacourse/java-ladder/pull/53/commits/b2791818110ac759cd11b0298e4b29130fd26aeb

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/view/OutputView.java
> +    public void Lines(Lines lines) {
메서드명에 대한 컨벤션을 좀 더 알아볼까요?

https://github.com/woowacourse/java-ladder/pull/53/commits/689c9a3484c070216aa43edc7cc61839f70a4e6a

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/domain/Names.java
> +        for (String name : names.split(",")) {
","는 상수화를 해도 좋을 것 같아요.

매직넘버에 대해 공부해보아요!

https://github.com/woowacourse/java-ladder/pull/53/commits/b2791818110ac759cd11b0298e4b29130fd26aeb

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/domain/Names.java
> +        validate(this.names.size());
호출하는 메서드가 바로 아래에 있어야 보기가 좋다고 생각하시는데, 깃짱의 의견이 궁금하네요!

https://github.com/woowacourse/java-ladder/pull/53/commits/b2791818110ac759cd11b0298e4b29130fd26aeb

2023-02-17 03:22 UTC, jamie9504 commented on src/test/java/domain/NamesTest.java
> +    @DisplayName("사람의 수는 2명 이상 100명 이하이다.")
클래스는 Names인데, DisplayName은 사람의 수라고 적혀있어요.
용어를 하나로 통일하는 것도 좋겠죠?

https://github.com/woowacourse/java-ladder/pull/53/commits/978373f61e32ab358bf08df50f86a61f8429747a

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/controller/MainController.java
> +    private Map<ApplicationStatus, Supplier<ApplicationStatus>> gameGuide;
이럴 경우 중간에 개행을 한 번 해주면 조금 더 가독성이 좋아질 수 있어요. (final 여부 차이)

또한 gameGuide는 final이어도 되겠어요.

https://github.com/woowacourse/java-ladder/pull/53/commits/fd1e211169c1d13d73b856c217fced85f9ddc834

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/controller/MainController.java
> +    private Lines lines;
Controller가 상태값을 갖고 있게 되는데, 이러면 이 객체의 이름이 과연 Controller가 맞을까요?
한 게임에 대한 정보를 들고 있게 되어버리네요!
한 게임에 대한 정보를 담당해버리니, 메서드 명도 start, progress, printResult 느낌으로 가게 되었군요!

View 관리 + 한 게임에 대한 정보 두 개를 담당하는 클래스가 되어버리는데,
역할이 둘 이 되어버렸으니 나눠보는 것도 좋겠어요.

새 게임을 하려면 무조건 해당 Controller를 새로 생성해야 하는데, 
그렇다고 도메인으로 보자니 View에 대해 의존을 하고 있어서 분리를 해야 할 것 같은 느낌이에요.

https://github.com/woowacourse/java-ladder/pull/53/commits/fd1e211169c1d13d73b856c217fced85f9ddc834

2023-02-17 03:22 UTC, jamie9504 commented on src/main/java/controller/MainController.java
> +    }
이렇게 관리했을 때 장점이 무엇이 있나요?

https://github.com/woowacourse/java-ladder/pull/53/commits/fd1e211169c1d13d73b856c217fced85f9ddc834

2023-02-17 05:31 UTC, eunkeeee commented on src/main/java/controller/MainController.java
> +    }
@jamie9504 

제가 이 방식을 사용했던 이유는 

1. 제가 생각했을 때 가독성이 좀 더 좋다고 생각했습니다.
2. 현재 요구사항에는 없지만, 만약에 사용자의 입력에서 `IllegalArgumentException`이 발생했을 때 다시 입력을 받고자 한다면, 컨트롤러에서 예외를 처리하고 다음 단계에 대해서 수월하게 넘어갈 수 있다고 생각했습니다.

하지만 이 방식을 사용하니 단점도 많았습니다...
위에서 피드백 주신 것처럼, 

단계들이 메소드로 분리되는데, 서로 매개변수를 주고받을 수 없기 때문에 필드에 변수가 증가했습니다.

이것을 해결하기 위해서 제가 프리코스 때 생각했던 방식이
1. `LadderCondition`과 같은 클래스를 만들어 현재 `names`, `height`, `lines`과 같은 변수들을 관리하도록 했습니다. 
2. 불필요한 STATUS의 분리를 막기 위해서 최대한 크게 크게 상태를 나누도록 노력했습니다.

제이미의 생각에는 이 방식이 장점, 단점 중 어떤 것이 더 많다고 생각하시는지 궁금합니다...!

2023-02-17 05:31 UTC, eunkeeee commented on src/main/java/controller/MainController.java
> +    private Lines lines;
@jamie9504 

> Controller가 상태값을 갖고 있게 되는데, 이러면 이 객체의 이름이 과연 Controller가 맞을까요?

제가 생각했던 `Controller`는 `model`을 통해서 데이터를 가져오고 `View`를 통해 사용자에게 정보를 표시하는 역할입니다. 
모델이나 뷰에 대한 내용을 담고 있어야 한다는 점에서 `Controller`가 상태값을 가지는 것이 문제라고 생각하지 못했는데, 왜 문제가 되는지 조금 설명 부탁드려도 될까요???!

[아래](https://github.com/woowacourse/java-ladder/pull/53/files#r1109245939)에서 이유를 물어보셨던 그 `map`으로 Status를 관리하는 방식을 통해서 필드 변수가 생겼습니다. 아래에 더 자세히 남겨놓았어요!

> 한 게임에 대한 정보를 들고 있게 되어버리네요!
> 한 게임에 대한 정보를 담당해버리니, 메서드 명도 start, progress, printResult 느낌으로 가게 되었군요!

맞습니다...! 
제이미가 생각하는 컨트롤러는 어떤 정보를 담아야 하는지도 궁금해요!

2023-02-17 05:31 UTC, eunkeeee commented on src/main/java/domain/Name.java
> +        validateLength(name);
`validateBlank`는 이름 칸에 공백만 입력한 경우에 예외처리하는 메서드입니다.
이름이 모호하게 느껴질 수 있을 것 같네요... `validateBlankName` 같은 메서드명은 어떤가요...?!

`isEmpty()`는 문자열의 길이가 0인 경우에만 `true`를 리턴하지만,
여기서 사용된 `isBlank()`는 문자열이 비어 있거나(`null`), 빈 공백으로만 이루어져 있으면, `true`를 리턴하므로 `null`에 대한 처리도 괜찮을 것 같습니다!

2023-02-17 05:31 UTC, eunkeeee commented on src/main/java/domain/Names.java
> +        validate(this.names.size());
@jamie9504 

저도 호출하는 메서드가 바로 아래에 있는게 좋다고 생각하는데,
제 페어 제리 @Hyeonjae-K 가 `public` 메서드를 위로 정렬하는게 좋아서 이렇게 했습니다.
제이미는 호출하는 메서드를 바로 아래에 두시나요??

제가 생각하는 메서드 순서는...

생성자
주요 `public` 메서드 + 호출되는 `private` 메서드
`getter`

이런 식으로 정렬하고 있어요

2023-02-17 05:31 UTC, eunkeeee commented on src/main/java/view/InputView.java
> +    }
@jamie9504 
 
`InputView`에 대한 객체를 반복해서 생성하는 것이 어색하다고 생각했습니다

제 페어는 `view`에 관한 내용은 `static` 메서드로 작성했다고 했습니다. 

확장성을 고려한다면, `view`도 상속될 수 있다고 생각해서 질문하신건가요?

만약에 싱글턴 패턴을 적용하고 싶다면 이곳에서 `INPUT_VIEW`를 `enum` 객체를 만들어도 될까요?

2023-02-17 05:31 UTC, eunkeeee commented on src/main/java/view/OutputView.java
> +    public void Lines(Lines lines) {
@jamie9504 

앗 클래스 이름을 일괄적으로 변경하는 과정에서 잘못된 것 같습니다
`printLines`로 변경하는건 괜찮은가요?

2023-02-17 05:31 UTC, eunkeeee commented on src/main/java/view/OutputView.java
> +            StringBuilder result = new StringBuilder();
@jamie9504 

사다리의 모양을 나타내기 때문에 `ladderDisplay` 정도의 이름은 어떤가요?

2023-02-17 05:31 UTC, eunkeeee commented on src/test/java/domain/NamesTest.java
> +    @DisplayName("사람의 수는 2명 이상 100명 이하이다.")
@jamie9504 넵 `이름의 수`로 변경하는 것이 더 통일성 있을 것 같아요!

2023-02-17 10:18 UTC, Hyeonjae-K commented on src/main/java/domain/Names.java
> +        validate(this.names.size());
안녕하세요. 깃짱 페어 제리입니다.

제가 위와 같이 정렬하자고 의견을 낸 이유는 코드를 읽을 때 public으로 제공되는 메서드들의 로직을 한번에(순차적으로) 확인할 수 있다는 장점과 접근 제어자에 따라 분리하는 일관성이 있다고 생각했기 때문입니다.

하지만 메서드의 내부 로직을 확인할 때 모든 public 메서드를 확인하는 것 보다 필요한 메서드만 확인하는 것이 일반적이며 이럴 경우 호출하는 메서드가 바로 아래 있어야 한눈에 파악하기 용이한 것 같습니다.

2023-02-18 08:34 UTC, eunkeeee commented on src/test/java/domain/FloorTest.java
> +    @Nested
@jamie9504 
넵 좀 더 일관성있는 코드를 작성하도록 노력하겠습니다!
최종 코드에는 삭제된 코드인 것 같은데, 이런 부분에서 이렇게 작성하는 것에 대해 어떻게 생각하시나요?
다른 분들 보면 문장을 끊어가면서 `@DisplayName`을 작성하는 경우가 많은 것 같더라고요...!

```
@Nested
@DisplayName("참가자의 수")
class personCountTest {

        @DisplayName("는 2명 이상 100명 이하이다.")
        @ParameterizedTest
        @ValueSource(ints = {2, 100})
        void validPersonCountTest(int personCount) {
            assertDoesNotThrow(() -> new Floor(personCount, randomBooleanGenerator));
        }

        @DisplayName("가 1명 이하, 101명 이상이면 예외 처리한다.")
        @ParameterizedTest
        @ValueSource(ints = {0, 1, 101, 102})
        void invalidPersonCountTest(int personCount) {
            assertThatIllegalArgumentException()
                    .isThrownBy(() -> new Floor(personCount, randomBooleanGenerator));
        }
    }
```

2023-02-18 08:34 UTC, eunkeeee commented on src/test/java/domain/FloorTest.java
> +}
@jamie9504 

파일 끝에 `newLine`을 넣어두는 것이 컨벤션인가요..?! 몰랐네요 알려주셔서 감사합니다!!

2023-02-18 12:30 UTC, eunkeeee reviewed
제이미! 

이렇게 제 commit 로그까지 들어가서 40개 가까이 되는 커밋을 모두 살펴봐 주셔서 감사합니다!
너무 감동적이었어요ㅠㅠㅠㅠㅎㅎ

중간에 아무도 안 볼거라고 생각해서 컨벤션을 지키지 않은 부분도 많아서 좀 부끄럽기도 했지만요...! 제가 질문이 좀 엄청나게 많은데, 답해주시면 정말정말 감사하겠습니다...!

제이미 덕분에 정말 많이 배웠어요 감사해요!!!

2023-02-18 12:30 UTC, gitchannn commented on src/main/java/domain/Floor.java
> +    public Floor(int personCount, BooleanGenerator generator) {
@jamie9504 

네 저도 이부분에서 페어와 많이 고민했습니다...
저 역시 연관성이 떨어져서 이해하기 어렵다는 생각입니다.

제이미라면, `personNumber - 1`을 `lineNumber`와 같은 변수로 지정해 입력 받을 건가요??

2023-02-18 12:30 UTC, gitchannn commented on src/main/java/domain/Floor.java
> +        }
@jamie9504 

TDD 방식을 이해할 때에,

1. 실패하는 테스트 코드를 작성한다.
2. 테스트 코드를 성공하는 프로덕션 코드를 작성한다.
3. 프로덕션 코드를 리팩터링한다.

저는 요구 사항을 지키는 것을 리팩터링으로 생각해서 미뤄뒀는데, 커밋을 모두 공유한다고 생각하면 잘 지켜야겠네요! ㅎㅎㅎ 이렇게 다 보실 줄 몰랐어요... 같이 페어프로그래밍 하면서 실시간으로 피드백 받는 것 같아서 너무너무 감사해요....

2023-02-18 12:30 UTC, gitchannn commented on src/main/java/domain/Name.java
> +        }
@jamie9504 

위의 if문은 이름을 입력한 칸에 `null`이거나 ""같이 `공백인 경우`를 검증하기 위한 것이었고,
아래의 if문은 이름의 길이가 5칸을 초과하는 경우를 검증하기 위한 것이었습니다.
`name.length() < 1` 이 부분이 위의 if문과 좀 겹치는 내용인 것 같긴 합니다...

2023-02-18 12:30 UTC, gitchannn commented on src/main/java/view/InputView.java
> +        }
@jamie9504 

제이미라면 이런 경우 어떻게 하실건가요?

1. 새로운 객체를 받는다.
```
        for (String name : names.split(",")) {
            Name newName = new Name(name.trim());
            this.names.add(newName);
        }
```

2. trim, 새로운 객체 생성에 관한 부분을 메서드 분리한다.

2023-02-18 12:30 UTC, gitchannn commented on src/main/java/view/InputView.java
> +        int size = Integer.parseInt(input);
@jamie9504 

네 이 부분은 후에 예외 처리를 별도로 했습니다!

궁금한게 있는데, 다른 크루분은 `parseLong`을 사용하기도 한다고 하는데, 제이미 생각에는 `parseInt`를 `try, catch`문을 통해서 예외 처리하는 것이 최선이라고 생각하시나요?

2023-02-18 12:30 UTC, gitchannn commented on src/main/java/domain/Floor.java
> +import utils.booleanGenerator.BooleanGenerator;
@jamie9504 

흠... 랜덤 `boolean`을 받는다는 것이 범용적이라고 생각했었는데, 아직도 어디에 들어가는 것이 자연스러운지 잘 감이 오지 않는 것 같아요.

@Hyeonjae-K 생각은 어떤가요?

2023-02-18 12:30 UTC, gitchannn commented on src/main/java/domain/Name.java
> +        NameValidator.validate(name);
@jamie9504 

저는 프리코스 때까지는 검증이 필요한 입력값에 대해서는 거의 원시값 포장이란걸 하지 않았었습니다.

처음에는 `Validator`와 같이 유틸성 클래스를 `static` 메서드로 사용하다가, `static` 메서드를 너무 남발하는 것 같다는 생각이 들어서, `validator`의 인스턴스를 만들어 사용하기 시작했습니다.

그런데도 인스턴스를 만든다는 것 자체가 좀 어색하게 느껴져서, 원시값 포장에 대해서 생각해 보게 된 것 같습니다.

추가로 검증과 관련해서 질문 드리고 싶은게 있습니다!! (너무 많은가요...?ㅎ)

만약에 저희가 게임 닉네임을 중복되는 것은 입력할 수 없게 하는 프로그램을 만들고 싶다고 가정해 볼게요.
만약에 사용자가 중복되는 닉네임을 입력했을 때, 한 번 `중복되는 닉네임이 있습니다 다시 입력해 주세요`라고 표시한다면 사용자가 더 빠르게 이 닉네임을 사용할 수 없구나... 해서 알려져서 좋을 것 같고, 혹시나 사용자가 html(프론트엔드에서 입력받는다면)을 조작하거나, view를 조작해서, 또는 버그가 나서 view에서 표시를 못하게 되어 잘못된 정보를 입력하게 되면 비싼 DB에 심각한 비용이 추가될 수 있다고 가정해 본다면, 복구가 어려울 수 있으니 두 번 하는 것도 생각해볼 수 있을 것 같아요.

이런 경우에 제이미는 같은 내용의 코드를 `view`와 `domain`에서 총 두 번 반복하는 것에 대해서 어떻게 생각하시나요?

2023-02-18 12:30 UTC, gitchannn commented on src/main/java/utils/validator/LadderSizeValidator.java
> +    }
@jamie9504 

맞습니다....! 아닌가요....?!!

2023-02-18 12:30 UTC, gitchannn commented on src/main/java/utils/validator/LadderSizeValidator.java
> +    public static final int MIN_RANGE = 1;
@jamie9504 아니요 실수였던 것 같습니다...! 가끔 `Ctrl Alt C`로 했을 때 자동으로 `public`이 되는 경우가 있더라고요.. 조심해야겠습니다

2023-02-18 12:30 UTC, gitchannn commented on src/main/java/utils/validator/LadderSizeValidator.java
> +    private enum Message {
@jamie9504 

`Message`로 나눈건 클래스에 상수 필드가 너무 많아지면 지저분해 보여서였습니다!
`throw new IllegalArgumentException("자연수만 입력해 주세요.");`같이 하면 너무 하드코딩한 것 같이 생겨서 별도로 분리하는 습관을 들이게 되었는데, 제이미 생각에는 더 좋은 방법이 있나요?

2023-02-18 12:30 UTC, gitchannn commented on src/main/java/utils/validator/LadderSizeValidator.java
> +        public static final String BASE_MESSAGE = "[ERROR] %s";
@jamie9504 `_FORMAT`으로 수정하겠습니다!

2023-02-18 12:30 UTC, eunkeeee commented on src/main/java/view/OutputView.java
> +        System.out.println("실행결과\n");
@jamie9504 감사합니당...! 완전 유용한 정보...
[글](https://engineerinsight.tistory.com/entry/JAVA-%EC%A4%84%EB%B0%94%EA%BF%88%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC-%EC%B6%9C%EB%A0%A5-%ED%9B%84-%EC%A4%84%EB%B0%94%EA%BF%88%EC%97%90-n%EC%9D%84-%EC%93%B0%EB%A9%B4-%EC%95%88%EB%90%9C%EB%8B%A4%EA%B3%A0)도 하나 썼어요 헤헤

2023-02-18 12:30 UTC, eunkeeee commented on src/main/java/domain/Floors.java
> +            floors.add(new Floor(personCount, new RandomBooleanGenerator()));
@jamie9504 아니요... 제 생각에는 `Application`에서 시작되어서 주입받는 방식이 더 좋을 것 같네요...!
수정하겠습니다! 

+++ 제이미는 `Controller`와 `Application` 중 어디에서 주입받는 것이 맞다고 생각하나요?

2023-02-18 12:30 UTC, eunkeeee commented on src/main/java/domain/Lines.java
> +
@jamie9504 

개행이 정말 사소하다고 생각했는데 이제까지의 리뷰어 분들께서 개행에 대해 많이 언급해 주시는 것 같아요...! 그만큼 컨벤션에 맞지 않거나 일관성 없는 개행은 눈에 거슬리나 보네요...! 앞으로 각별히 조심해야겠어요 감사합니다!

2023-02-18 12:30 UTC, eunkeeee commented on src/main/java/domain/Line.java
> +    }
@jamie9504 

최종적인 코드에서 `lineNumber`를 받도록 수정하였고, 
`inputName`을 통해서 한 번 입력된 사람의 수를 검증하고, `Lines`에는 사람의 수 - 1 만큼의 수가 입력됩니다.
사용자로부터 직접 입력받는 경우는 없는 것 같아서 검증 과정을 별도로 하지 않았는데, 
테스트코드에서 음수나 0을 넣는다면 의도한 역할을 하기 어려울 것 같아요. 그치만 아직까지는 직접 입력할 일이 없을 것 같아 별도로 처리하지는 않았습니다.

2023-02-18 12:34 UTC, eunkeeee commented on src/test/java/domain/FloorTest.java
> +        assertDoesNotThrow(() -> new Floor(personCount));
@jamie9504 

> (참고) 해당 커밋에는 Floor 객체가 없는데, 이럴 경우엔 이 커밋을 코드로 받는다면, 정상적인 상태가 아니겠죠?
> 그런 경우 이 커밋으로 누군가 rollback을 하거나, 해당 커밋만 일부 브랜치로 옮기거나 했을 때는 어떤 문제가 있을까요?
> 
> 학습을 위해서, 구분하기 위한 Commit이면 괜찮은 것 같아요.
> 학습용이 아니라면, 깨지지 않는 코드를 한 커밋으로 묶어야 한다고 생각해요. :)

넵 저도 학습용으로, TDD 순서를 지켜서 작성했음을 나타내기 위해서 커밋을 따로 했습니다!
다른 개발자가 이상태로 commit을 보게 된다면 혼란스러울 거라는 것은 잘 알고 있습니다!!!

2023-02-18 19:49 UTC, jamie9504 requested changes
깃짱, 안녕하세요! 리뷰어 제이미입니다 😄 

감동받으셨다니 기쁘네요.

다들 주말에 열심히 PR을 올려주시는데,
무리하지는 않으시는 건지 조금 걱정이 됩니다. 😢 

피드백을 조금 남겨두었으니
수정하고 싶은 부분은 수정을 해주시고, 이 부분은 의도한 부분이다 하면 의견을 남겨주시면 좋을 것 같아요.

아래 코멘트 남겨주신 부분에 대한 답변을 적어둘게요.
좋은 주말 보내세요.

코멘트덕에, 깃짱이 예외 메시지를 테스트하고 싶은 부분에 대해서 이해했습니다.
요점은 A라는 상황에서 IAE("A")가 발생하고, B라는 상황에서 IAE("B")가 발생할 때,
각각의 상황에 맞는 예외가 발생했는지의 검증을 위해 예외 메시지를 검증하고 싶으신거군요.
또한, 예외 메시지를 빈번하게 변경할 수 있으므로 문구를 정확히 테스트하고 싶진 않으신거구요.

그래서 아래와 같은 케이스가 있을 수 있는 거군요.
1. product 코드를 테스트 코드에서 사용할 수 있게 바꾼다.
   (enum을 public으로 바꾸던...)
2. 커스텀 exception을 만들어 테스트한다.
3. `.withMessage()`에 하드코딩을 한다.

제가 생각한 결론부터 말씀드리자면, 이미 알고 계실 수 있지만.. 😄 
다 각각의 장/단점이 있고, 깃짱이 선택하는 부분이라는 것이에요!
간단하게 생각할 수 있는 장/단점을 적어둘께요, 여기에 깃짱이 생각하는 장/단점을 더해서 어떤 걸 선택하고 싶은지 고민해보고, 적용해보고, 그렇게 결정한 이유를 코멘트로 남겨주시면 좋을 것 같아요.

1. product 코드를 테스트 코드에서 사용할 수 있게 바꾼다.
    (예외 메시지를 상수화해서 protected로 열어두면 되긴 하겠죠?)
    - 장점 : 예외 메시지를 의존하므로, 변경이 되더라도 테스트가 용이하다.
    - 단점 : test 코드 때문에 product 코드의 접근제어자를 변경해야 한다.
2. 커스텀 exception을 만들어 테스트한다.
    - 장점 : exception 종류로 판별이 가능하다.
    - 단점 : 테스트 하려는 모든 예외 상황을 다 커스텀 Exception을 만들어야 한다. (도메인과 검증지점이 늘어난다면?)
3. `.withMessage()`에 하드코딩을 한다.
    - 장점 : 간결하다.
    - 단점 : 예외 메시지 바꿔줄 때마다 해당 코드를 수정해야 한다.

2023-02-18 19:49 UTC, jamie9504 commented on src/test/java/domain/FloorTest.java
> +        assertDoesNotThrow(() -> new Floor(personCount));
@eunkeeee 
알고 계신다면 좋습니다! 👍

2023-02-18 19:49 UTC, jamie9504 commented on src/test/java/domain/FloorTest.java
> +}
@eunkeeee 

이유는 POSIX와 관련이 있는데요!
자바컨벤션은 아니고 Git쪽에서 체크하는 부분입니다.

https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/
요 글을 참고해보시면 좋을 것 같아요~

2023-02-18 19:49 UTC, jamie9504 commented on src/test/java/domain/FloorTest.java
> +    @Nested
@eunkeeee 
어떻게 해도 알아볼 수 있으면 상관없습니다! 통일성만 가져가면 되죠!
저는 문장보단 끊어서 쓰는 편인 것 같아요.

``` java
@DisplayName("참가자의 수 : ")
@DisplayName("생성자 테스트 - 성공 - 2명 이상 100명 이하")
@DisplayName("생성자 테스트 - 예외 발생 - 1명 이하, 101명 이상")

@DisplayName("참가자의 수 : ")
@DisplayName("생성자 테스트 - 2명 이상 100명 이하 - 성공")
@DisplayName("생성자 테스트 - 1명 이하, 101명 이상 - 예외 발생")
```

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/domain/Floor.java
> +    public Floor(int personCount, BooleanGenerator generator) {
@eunkeeee 

Lines 객체 자체로는 person이 뭔지 모르는 상황이니까요!
`LinesCount`라던가, Lines 객체이니 중복을 제거해서 `count`로 받을 것 같긴 하네요!
객체가 알아야 하는 이름으로 지어주면 좋겠죠?

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/domain/Floor.java
> +        }
@eunkeeee 

프로그래밍 요구 사항은, 전반적으로 다 지키는 게 좋은 것 같아요!

왜냐하면 if-else + n depth + 축약 + 컨벤션 안지키기를 하다가 마지막에 리팩터링이라고 딱 한 번에 바꾼다고 생각하면 😢 
그건 연습이 되지 않으니까요!

이번 미션은 TDD를 잘 하고 있는지를 중점으로 보아야해서
특히나 모든 커밋을 다 돌아보았습니다 😄

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/domain/Name.java
> +        }
@eunkeeee 

앗, 내부에서 동일하게 `throw new IllegalArgumentException();`를 하고 있길래 여쭤본 부분이었어요.
동일한 처리를 하지만 역할을 나눠보고 싶었다면 변수로 이름을 명확히 해줬어도 좋을 것 같기도 하구요.

``` java
        boolean 이름_공백 = name.isBlank();
        boolean 이름_유효하지_않은_글자수 = name.length() < 1 || name.length() > 5
        if (이름_공백 || 이름_유효하지_않은_글자수) {
            throw new IllegalArgumentException();
        }
```

나중에 메서드를 분리할 수도 있으니까 미리 나눠놓는다!라면, 이건 분리할 때 나누면 된다고 생각했는데
깃짱의 의견이 궁금하네요 😄

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/view/InputView.java
> +    }
@eunkeeee 

View를 싱글턴으로 작성하던, Static 메서드로 작성하던, 다른 걸로 작성하던 크게 상관은 없는 것 같아요!
그냥 작성하실 때, 어떤 생각으로 작성하셨는지가 궁금했던 부분인거에요 😄 

여쭤봤을 때 그냥 그렇게 했다보단 자신의 주관이 있는 쪽이 더 즐겁다고 생각하거든요!

---

> 만약에 싱글턴 패턴을 적용하고 싶다면 이곳에서 INPUT_VIEW를 enum 객체를 만들어도 될까요?

요 부분은 INPUT_VIEW를 Enum 객체로 만드신다는 걸까요?

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/view/InputView.java
> +        }
@eunkeeee 

저라면, 간단한 로직이니까 새로운 객체로 분리만 할 것 같아요.
단, 어디까지 분리할지는 본인의 선택인 것 같아요.
전부 다 분리하는 게 능사는 아니니까요!

``` java
for (String splitInput : input.split(SPLIT_DELIMITER)) { // 변수명은 조금 고민되네요 ㅎㅎ split보단 divided가 나으려나..
    String trimmedInput = splitInput.trim();
    Name name = new Name(trimmedInput)
    this.names.add(name);
}
```

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/view/InputView.java
> +        int size = Integer.parseInt(input);
@eunkeeee 
`parseLong`을 사용할지 `parseInt`를 사용할지는 이 프로그램에서 어떤 수까지 받아줄 것인가의 문제라
요구사항 & 본인이 정의한 기능 명세에 따라 선택하면 된다고 생각하구요,

`NumberFormatException`을 발생하는 부분이라,
try-catch를 통해 예외처리를 어디선가는 해줘야 하는거니까요 😄 

깃짱이 생각한 다른 방식이 또 있을까요?

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/domain/Floor.java
> +import utils.booleanGenerator.BooleanGenerator;
@eunkeeee @Hyeonjae-K 

범용적이라고 생각하시면 utils 하위에 두셔도 상관은 없습니다!
다만, 이 프로그램에서 범용적으로 사용하지 않는다면 적절한 패키지에 위치하는 것이 좋다는 의미입니다.

해당 generator를 어디서 사용하고 있는지, 사용하는 곳이 얼마나 많은지를 확인해보면
범용적인지를 고민하기 좋을 것 같아요.

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/domain/Name.java
> +        NameValidator.validate(name);
@eunkeeee 

의견 좋았습니다 👍 

개발에 대해서는 항상 `개발에 정답은 없다. 모든 것은 일장일단이 있다.` 요런 말을 듣는 것 같은데요. 😄 
검증도 마찬가지인 것 같아요.
어디다가 둘 것인가, 얼마나 많이 둘 것인가에 따라 장/단점이 있고 현재 개발하는 프로그램에서 장점이 더 큰 방식을 취하면 된다고 생각하는데요.
제가 생각하는 간단한 장/단점은 아래와 같은데, 추가로 장/단점에 생각해보고 지금 사다리에서는 어떤 방식을 택하는 게 제일 유리할지 고민해보아요!

View와 Domain에 검증 로직이 있는 경우
- 장점 : 검증이 철저해짐 👍 
- 단점 : 중복 검증
    - 약간의 성능 하락
    - 코드 수정 지점이 n배
        - 만약 일부만 수정하면 올바르지 못한 프로그램이 됨

View에만 있는 경우
- 장점 : 앞에서 막아줘서 올바르지 않은 요청일 때 빠르게 사용자에게 던짐
- 단점 : 도메인이 완벽하지 않음
    - 타 개발자가 도메인을 잘못 사용할 수 있음
    - 다른 View를 사용할 경우 검증 누락 가능 & 누락하지 않더라도 코드 수정 지점이 n배 

Domain에만 있는 경우
- 장점 : domain이 완전함
- 단점 : View에서 막아주면 뒷단까지 오지 않았을 텐데, 로직에 따라 한참 뒤에 사용자에게 리턴될 수 있음
    - 예를 극단적으로 들면 10분을 sleep 후 domain을 생성한다면? 사용자가 잘못되었다는 응답을 받는 건 10분 후 !

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/utils/validator/LadderSizeValidator.java
> +    }
@eunkeeee 

IntRange인지 검증을 하는 것 뿐만 아니라 Int인지도 검증이 되는 부분 같은데요! 😄 
IntRange이면 해당 값이 number인데 minInt <= number <= maxInt 라는 느낌이고,
여기서는 String(ex. `aaa`)이 들어올 수도 있는거니까요!

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/utils/validator/LadderSizeValidator.java
> +    public static final int MIN_RANGE = 1;
@eunkeeee 

`Ctrl + Alt + C` (맥은 `Command + Option + C`)를 누를 때 `C`를 한 번 더 붙여서 누르시면
상수 생성시 기본 접근 제어자 설정이 가능합니다.
<img width="284" alt="image" src="https://user-images.githubusercontent.com/59511689/219882563-fdbb4490-f7fc-414b-91a9-3cfc9edb31fb.png">

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/utils/validator/LadderSizeValidator.java
> +    private enum Message {
@eunkeeee 

개인적으로 반복해서 사용하지 않는 예외메시지는 `throw new IllegalArgumentException("자연수만 입력해 주세요.");` 이런식으로 써도 문제가 없다고 생각하는데요.
해당 케이스에서 발생되는 예외이고, 이 메시지를 보통은 재활용하지 않으니까요. 매직넘버라고 보긴 어렵다고 생각했어요.
범용적으로 쓴다면 상수화할 수도 있겠지만요!

Enum의 특징과 장점이 무엇인지 고민해보는 것도 좋을 것 같아요.
단순히 상수가 많아져서 분리하기 위해 Enum을 쓰는게 좋은지, 좋지 않은지도 고민해보고 (정답은 없습니다) 한 번 더 코멘트 달아주세요!

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/view/OutputView.java
> +        System.out.println("실행결과\n");
@eunkeeee 

정리하는 습관 좋다고 생각합니다 👍

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/domain/Floors.java
> +            floors.add(new Floor(personCount, new RandomBooleanGenerator()));
@eunkeeee 

일단 `floors`가 요 책임을 갖게 되면, 객체 내부에 랜덤 요소가 들어가게 되고 테스트와 전략 교체도 어려워진다고 생각했어요.

`Controller`와 `Application` 중 깃짱이 생각하기에 BooleanGenerator 전략을 생성하는 것을 담당해야 하는 것 같다! 하는 곳에 넣어주면 된다고 생각합니다.

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/view/OutputView.java
> +            StringBuilder result = new StringBuilder();
@eunkeeee 

이름을 봤을 때 유추가 된다면, 어떤 이름이던 상관없습니다 😄 

메서드가 printLadder이기 때문에 `ladder`로 지어도 되고,
조금 더 의미를 담기 위한 접미어들을 붙이셔도 될 것 같아요 👍

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/domain/Name.java
> +        validateLength(name);
@eunkeeee 

validate - 검증하다 + blank - 공란 = 공란임을 검증하다 = 공란이 아닐 때 🎉 이라고 오해할 수도 있겠죠~?

검증 메서드 내에서는 name이 들어오던 String 다른 문자열이 들어오던 상관 없이 검증을 하고 있기에 Name은 붙여도 되고 안붙여도 될 것 같아요.
물론 예외메시지에 name이란 부분을 노출한다면 포함해야 좋겠지만요!

아예 `String emptyString = ""` 같은 값이 아닌,
`String nullString = null` 같은 값이 들어오면 NPE가 발생하겠죠?
Null은 메서드를 가지고 있지 않으니까요!
<img width="561" alt="image" src="https://user-images.githubusercontent.com/59511689/219882804-dd66f3f4-a63b-45fc-b2ae-4a238c9c0783.png">

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/domain/Lines.java
> +
@eunkeeee 

뭔가 글을 읽을 때, 한결같은 개행은 그냥 아 이렇구나 생각하기 쉽지만
ㅤ
개행을 두 칸을 쓰다가 한 칸을 쓰다가 반복하면 이게... 뭔가 이해는 안되는 건 아니지만
ㅤ
ㅤ
조금 보기가 껄끄러운 느낌이 드는 것 같긴 해요.
물론 읽는 데 문제가 되는 건 아니지만요 😄 
ㅤ
뭔가 의미가 있을 수도 있을 것 같은 느낌도 들구요!

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/domain/Line.java
> +    }
@eunkeeee 

도메인(=객체)은 어디서 가져다 써도 일관성을 유지해야 한다고 생각해요.
Line을 다른 개발자가 가져다 쓴다면 깃짱의 현재 개발의 의도를 알고 있을까요?

테스트 코드에서도 검증을 별도로 하지 않기 때문에,
아 이 Line은 음수를 넣어도 되는 객체인가보다 😄 하고 가져다 쓸 수도 있을텐데, 그게 요 Line을 적합하게 이용하는 게 맞을까요?

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/view/OutputView.java
> +    public void Lines(Lines lines) {
@eunkeeee 

메서드는 동사로 시작하는 게 좋죠 👍

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/domain/Names.java
> +        validate(this.names.size());
@eunkeeee @Hyeonjae-K 

요 글을 읽어봐도 좋을 것 같아요!
https://dodop-blog.tistory.com/277

덧붙이자면 `public` 메서드들에서 같은 `private` 메서드를 호출한다면 약간 뒤죽박죽이 될 수도 있긴 하겠지만...
(아래의 경우 어디다 선언할지 고민할 수도 있겠죠 ㅎㅎ)
전 일단 맨 처음 호출하는 부분 아래에 넣고 있긴 해요! 약간의 취향 차이일수도 있겠네요!
``` java
public methodA (privateZ 호출)
private methodZ  .... (1)
public methodB (privateZ 호출)
private methodZ  .... (2)
public methodC (privateZ 호출)
private methodZ  .... (3)
```

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/controller/MainController.java
> +    private Lines lines;
@eunkeeee 

> 제가 생각했던 Controller는 model을 통해서 데이터를 가져오고 View를 통해 사용자에게 정보를 표시하는 역할입니다.
> 모델이나 뷰에 대한 내용을 담고 있어야 한다는 점에서 Controller가 상태값을 가지는 것이 문제라고 생각하지 못했는데, 왜 문제가 되는지 조금 설명 부탁드려도 될까요???!

Controller는 Model이나 View를 제어하는 부분이라고 생각했기 때문에, 아래와 같은 상태값을 가지는 게 이상하다고 생각했습니다.

``` java
    private Map<ApplicationStatus, Supplier<ApplicationStatus>> gameGuide;
    private Names names;
    private Height height;
    private Lines lines;
```

위와 같은 상태 값을 가지는 순간 `View와 Model`을 조율한다의 책임과
사다리타기의 `gameGuide, names, height, lines`를 관리한다의 책임을 각각 갖게 되는 거니까요! 😄 

-> 요 커밋에서 수정하셨네요!

https://github.com/woowacourse/java-ladder/pull/53/commits/8d0d500e4b38ae7cfe79c16d75619597eefbae17

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/controller/MainController.java
> +    }
@eunkeeee 

> 제가 생각했을 때 가독성이 좀 더 좋다고 생각했습니다.
> 현재 요구사항에는 없지만, 만약에 사용자의 입력에서 IllegalArgumentException이 발생했을 때 다시 입력을 받고자 한다면, 컨트롤러에서 예외를 처리하고 다음 단계에 대해서 수월하게 넘어갈 수 있다고 생각했습니다.

1.  어떤 부분에서 가독성이 더 좋다고 느껴졌는지 궁금합니다!
2. 현재 요구사항에 없는 부분까지 미리 가정해서 이럴 수-있으니 이렇게-해놔야지는 오버엔지니어링을 부를 수 있다고 생각해요!

> 이것을 해결하기 위해서 제가 프리코스 때 생각했던 방식이
> LadderCondition과 같은 클래스를 만들어 현재 names, height, lines과 같은 변수들을 관리하도록 했습니다.
> 불필요한 STATUS의 분리를 막기 위해서 최대한 크게 크게 상태를 나누도록 노력했습니다.
> 제이미의 생각에는 이 방식이 장점, 단점 중 어떤 것이 더 많다고 생각하시는지 궁금합니다...!

요 부분은 혹시 샘플 코드를 받아볼 수 있을까요?
제가 새벽이라 그런지 머리 회전이 잘 안되는 것 같아요 😢

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/domain/Names.java
> +    private static final String COMMA = ",";
매직넘버의 상수화에 대해 알아보아요.

상수는 사용하는 용도로 이름을 지어주는 것이 좋다고 생각해요!
기호 그대로의 이름을 사용한다면, 상수화를 하는 의미가 크게 없는 것 같아요!
마치 `private static final int TWO = 2;` 이렇게 선언하지 않는 것처럼요.

https://github.com/woowacourse/java-ladder/pull/53/commits/44abd07602b21bdb37403b8ebe8b7b77bd094fbd

2023-02-18 19:49 UTC, jamie9504 commented on README.md
> +- [ ] 현재 사용하는 MVC 패턴의 `Controller`의 모습은 괜찮은 걸까? => 일단 `map`을 통해서 `gameGuide`를 받는 방식은, 다른 사람이 하는 것이 멋져 보여서 따라한 건데 내가 뚜렷한 장점에 대해 설명할 수 없으므로 적용하지 않기로 했다.
😄 👍 
적어도 사용한 코드에 대해선 이유가 있어야 좋다고 생각합니다!

https://github.com/woowacourse/java-ladder/pull/53/commits/53d824fc9a72b0f82c8e9749d345cc892f065dfa

2023-02-18 19:49 UTC, jamie9504 commented on src/main/java/domain/Height.java
> +        public static final String _FORMAT = "[ERROR] %s";
https://github.com/woowacourse/java-ladder/pull/53#discussion_r1108929409

요 의미는 접두어로 `_FORMAT`을 붙이면 좋을 것 같다는 의미였어요! 😄 
상수명이 `_FORMAT`이면 어떤 포맷인지 알기가 어렵겠죠?
다시 한 번 작업해볼까요?

https://github.com/woowacourse/java-ladder/pull/53/commits/ec1c2f409cba336d53f6a5530c075e6e519fcdc0

2023-02-19 03:12 UTC, eunkeeee commented on src/test/java/domain/FloorTest.java
> +    @Nested
@jamie9504 예시까지... 감사합니다!

2023-02-19 03:13 UTC, eunkeeee commented on src/main/java/domain/Floor.java
> +    public Floor(int personCount, BooleanGenerator generator) {
@jamie9504 

넵 지난번 공통 피드백 중에
`Car` 객체의 `move()` 메서드는 파라미터가 `randomNumber`인지 알 필요가 없다는 것과 비슷한 것 같네요!

2023-02-19 03:20 UTC, eunkeeee commented on src/main/java/domain/Name.java
> +        }
@jamie9504 

아하 이런 식으로 바꾸는 것을 말씀하시는 건가요...?

``` 
    private void validate(String name) {
        boolean isBlank = name.isBlank();
        boolean isInvalidLength = name.length() < MIN_LENGTH || name.length() > MAX_LENGTH;
        if (isBlank || isInvalidLength) {
            throw new IllegalArgumentException(Message.EXCEPTION_INVALID_NAME_LENGTH.message);
        }
    }
```
이런 식의 수정을 말하신 거면...! 저도 괜찮은 것 같아요
가독성도 좋은 것 같고, 굳이 글자수가 다른 것과 이름에 공백이 있는 것을 따로 예외 처리해서 메세지를 보여줄 이유도 없는 것 같다고 생각해요!

2023-02-19 03:23 UTC, eunkeeee commented on src/main/java/view/InputView.java
> +    }
@jamie9504 

네 맞습니다! 제가 `view`를 싱글턴으로 만든 이유는 같은 객체를 두 번 생성할 수 없도록 하기 위해서였어요!
그런데 이렇게 정적 팩토리 메서드 + 생성자 `private`으로 숨기기 방식은 아무래도 이 패턴을 사용하지 않는 사람들은 클래스의 앞부분이 좀 지저분하다고 느낄 수 있을 것 같아서, `enum` 객체는 그 자체로 생성자가 숨겨지기 때문에 

```
public enum InputView {

INPUTVIEW;

...
```
이런 식으로 작성하는 건 어떠냐고 질문한 거였습니다!

2023-02-19 03:26 UTC, eunkeeee commented on src/main/java/view/InputView.java
> +        }
@jamie9504 

지금은 이 부분이 일급 컬렉션 `Names`로 바뀌어서 사라졌지만...!
제이미의 방식이 제 중첩 괄호보다 더 보기도 좋고 이해하기도 쉬운 것 같아요!
다음부터는 좀 더 예쁘게 만들어 보겠습니다!

2023-02-19 03:29 UTC, eunkeeee commented on src/main/java/view/InputView.java
> +        int size = Integer.parseInt(input);
@jamie9504 

제가 생각했던 건... 

1. `String` 형태의 input을 정규 표현식으로 한 번 검증한다
정규 표현식에 능숙하지는 않아서 이걸로 자연수인지는 검증해 왔는데, 범위까지 검증할 수 있는지는 더 찾아봐야 알 것 같지만, 할 수 있다면 정규 표현식으로 `자연수이고, 2 이상 100 이하이다`를 모두 검증하고 `parseInt` 할 것 같아요.

2. 굳이 `NumberFormatException`으로 예외를 `catch`하지 않고, 상위 클래스인 `IllegalArgumentException`으로 퉁치기...? 혼란스러우려나요..?

2023-02-19 03:30 UTC, eunkeeee commented on src/main/java/domain/Floor.java
> +import utils.booleanGenerator.BooleanGenerator;
@jamie9504 현재 사용하는 곳에서 범용적이지는 않은 것 같습니다. (도메인에 스르륵 옮긴다...)

2023-02-19 03:35 UTC, eunkeeee commented on src/main/java/domain/Name.java
> +        NameValidator.validate(name);
@jamie9504 

제이미의 세 가지 경우의 수 전부 이마를 치며 공감했습니다ㅠㅠ

저는 안전 제일주의라 둘 다 검증이 있는 것이 좋다고 생각하는데, 대부분 View는 사용자와 만나는 지점이기 때문에 프론트엔드의 역할이 되기 때문에 어쩌면 JS로 하는 검증일 수도 있을 것 같아요...! 

`회사의 비용이 남아도는 곳까지 한다`를 원칙으로 하고, 제가 정말 돈이 없는 밥풀 뜯어먹는 회사라면, `Domain`에만 검증을 하고 나중에 `View`에도 검증 로직을 넣을 것 같아요. 당장 사용자에게 알려주는 것보다 회사의 존패에는 데이터베이스가 무사하냐가 더 중요할 것 같아요 

이상 저의 의견이었습니다.

2023-02-19 03:37 UTC, eunkeeee commented on src/main/java/utils/validator/LadderSizeValidator.java
> +    }
@jamie9504 

아하...! 그러면 `validateParseInt`....? 이런 이름이 적합하려나요...
네이밍은 너무 어렵습니다ㅠㅠㅠㅠ

2023-02-19 03:39 UTC, eunkeeee commented on src/main/java/utils/validator/LadderSizeValidator.java
> +    public static final int MIN_RANGE = 1;
@jamie9504 꺅 꿀팁 감사합니다!_!_!_!_!

2023-02-19 04:54 UTC, eunkeeee commented on src/main/java/utils/validator/LadderSizeValidator.java
> +    private enum Message {
@jamie9504 

저는 `Enum`을 사용할 때 최대한 공통된 것끼리 묶으려고 노력합니다
당장에 예외 메세지가 서로 같은지 비교할 일은 없지만, 후에 그런 일이 발생할 수도 있을지 모르고!

사용하는 큰 이유가 안전한 비교, 무제한 인스턴스 생성 방지, 상수의 깔끔해보이는 용도
이정도인데 예외 메세지는 상수로 처리했을 때 좀 지저분해 보이는 경우도 많고,
공통적으로 앞에 `[ERROR]`같은 문구를 붙여야 한다 했을 때, 아니면 중간에 `%d`로 변수를 추가해서 넣고 싶을 때 편하게 느껴졌어요!

2023-02-19 04:56 UTC, eunkeeee commented on src/main/java/domain/Floors.java
> +            floors.add(new Floor(personCount, new RandomBooleanGenerator()));
@jamie9504 

맞아요.. 제가 전에 읽었던 좋은 코드 나쁜 코드에서도 객체를 주입하는 시점에 대해서 이야기하는 내용이 있었는데, 망각해서 이런 코드가 나왔네요...! 나중에 다른 방식으로 `BooleanGenerator`를 `implement`하게 된다면 쉽게 교체하기 위해서는 저는 `Application`에서 `View`를 주입하는 시점에 같이 하는 것이 좋다고 생각해서 애플리케이션으로 변경했습니다!

2023-02-19 06:43 UTC, eunkeeee reviewed
최대한 피드백 반영해서 수정하려고 노력했습니다!_!_!
질문 정말 많은데 주말에도 꼼꼼히 피드백 달아주셔서 감사해요

2023-02-19 06:43 UTC, eunkeeee commented on src/main/java/controller/MainController.java
> +    private Lines lines;
@jamie9504 

네 이번 미션에서는 단순히 저 `map`형태의 `gameGuide`를 삭제하는 것만으로도 필드를 제거할 수 있었습니다.
그치만 만약에 이 안에서 `잘못된 입력을 할 경우 다시 입력받는다`와 같은 요구사항이 추가되어서,

이름 받기, 높이 받기, 사다리 생성을 각각 다른 메서드로 분리해서 각각 try, catch문을 적용한다면 공통적으로 필요한 `names`, `height`에 대한 변수는 어떻게 관리해야 할 지 좀 고민이 됩니다....!

2023-02-19 06:43 UTC, eunkeeee commented on src/main/java/controller/MainController.java
> +    }
@jamie9504 

> 어떤 부분에서 가독성이 더 좋다고 느껴졌는지 궁금합니다!

메서드 이외에도 다음 `State`에 대한 `Status`를 정의해서 게임의 상태를 좀 더 명확하게 할 수 있다.
_다음 할 일을 명확하게 알 수 있다_는 느낌이 저는 들었어요! 
물론 또 이 패턴을 처음 접하는 사람은 좀 당황스러울 것 같기도 합니다.

> 현재 요구사항에 없는 부분까지 미리 가정해서 이럴 수-있으니 이렇게-해놔야지는 오버엔지니어링을 부를 수 있다고 생각해요!

저도 이 부분 때문에 리팩터링 과정에서 다시 입력 받는 부분을 다 제거했습니다!

> 요 부분은 혹시 샘플 코드를 받아볼 수 있을까요?
> 제가 새벽이라 그런지 머리 회전이 잘 안되는 것 같아요 😢

[샘플 코드](https://github.com/woowacourse-precourse/java-bridge/pull/1207/files#diff-1dfdbc8d3a7d7196e50bdeb487fd139107f2e394cbcd162b1b69a466d1157206)에서 보시면, [간단한 설명](https://github.com/woowacourse-precourse/java-bridge/pull/1207#pullrequestreview-1304722681)도 달아놨어요!

2023-02-19 06:43 UTC, eunkeeee commented on src/main/java/domain/Height.java
> +        public static final String _FORMAT = "[ERROR] %s";
@jamie9504 

`_FORMAT_BASE_MESSAGE`로 수정했습니다!

2023-02-19 06:43 UTC, eunkeeee commented on src/main/java/domain/Names.java
> +    private static final String COMMA = ",";
@jamie9504 

ㅎㅎㅎㅎ 그러게요 `COMMA`로 상수 선언한건 의미가 없는 것 같아요
[매직 넘버의 상수화](https://javabom.tistory.com/28)가 이런 뜻이라면....!
저는 _스플릿하는 기준_이라는 의미에서 `SPLIT_STANDARD`로 바꿔봤는데... 괜찮은가요..?!

2023-02-19 06:43 UTC, eunkeeee commented on README.md
> +- [ ] 현재 사용하는 MVC 패턴의 `Controller`의 모습은 괜찮은 걸까? => 일단 `map`을 통해서 `gameGuide`를 받는 방식은, 다른 사람이 하는 것이 멋져 보여서 따라한 건데 내가 뚜렷한 장점에 대해 설명할 수 없으므로 적용하지 않기로 했다.
@jamie9504 

넵 이제까지는 남들 하는게 좋아보이면 빠르게 흡수하고 사용하는게 제 장점이라고 생각했는데, 페어프로그래밍과 꼼꼼한 리뷰 덕에 사용 이유가 있어야 사용하겠다고 마음이 좀 바뀌었어요! 정말 감사드립니다

2023-02-19 07:40 UTC, jamie9504 commented on README.md
> +# java-lines
.

2023-02-19 07:40 UTC, jamie9504 commented on src/main/java/view/InputView.java
> +    }
@eunkeeee 

// TODO

2023-02-19 07:40 UTC, jamie9504 commented on src/main/java/view/InputView.java
> +        int size = Integer.parseInt(input);
@eunkeeee 

// TODO

2023-02-19 07:40 UTC, jamie9504 commented on src/main/java/domain/Name.java
> +        NameValidator.validate(name);
@eunkeeee 

// TODO

2023-02-19 07:40 UTC, jamie9504 commented on src/main/java/utils/validator/LadderSizeValidator.java
> +    }
@eunkeeee 

// TODO

2023-02-19 07:40 UTC, jamie9504 commented on src/main/java/utils/validator/LadderSizeValidator.java
> +    private enum Message {
@eunkeeee 

// TODO

2023-02-19 07:40 UTC, jamie9504 commented on src/main/java/controller/MainController.java
> +    private Lines lines;
@eunkeeee 

// TODO

2023-02-19 07:41 UTC, jamie9504 commented on src/main/java/controller/MainController.java
> +    }
@eunkeeee 

// TODO

2023-02-19 07:49 UTC, jamie9504 commented on src/main/java/domain/Names.java
> +    private static final String COMMA = ",";
@eunkeeee 

// TODO

2023-02-19 07:51 UTC, jamie9504 commented on README.md
> +- [ ] 현재 사용하는 MVC 패턴의 `Controller`의 모습은 괜찮은 걸까? => 일단 `map`을 통해서 `gameGuide`를 받는 방식은, 다른 사람이 하는 것이 멋져 보여서 따라한 건데 내가 뚜렷한 장점에 대해 설명할 수 없으므로 적용하지 않기로 했다.
@eunkeeee 

남들 하는 게 좋아보여서 빠르게 흡수하고 사용하는 건 장점이라고 생각해요.
그렇지만 코드에 적용하기 전에 이걸 사용했을 때 장/단점이 무엇일지 고민해보고 장점이 크면 적용하면 좋을 것 같아요 😄

2023-02-19 07:56 UTC, jamie9504 commented on src/main/java/domain/Height.java
> +        public static final String _FORMAT = "[ERROR] %s";
@eunkeeee 

제가 새벽에....... 댓글을 달아놔서 정신이 잠깐 없었나봅니다 😢 

접미사로 부탁드려요! ex) `BASE_MESSAGE_FORMAT`

2023-02-19 13:38 UTC, jamie9504 commented on src/main/java/domain/Names.java
> +    private static final String COMMA = ",";
@eunkeeee 

// TODO

2023-02-19 14:37 UTC, jamie9504 requested changes
깃짱, 안녕하세요. 리뷰어 제이미에요 😄 

아마 다음 리뷰요청이 실제 피드백을 드릴 수 있는 마지막 리뷰요청일 것 같네요 😄 

코멘트에도 적어뒀는데, Enum에 대한 학습을 조금 더 해보면 좋을 것 같아요!!

피드백을 조금 남겨두었으니
수정하고 싶은 부분은 수정을 해주시고, 이 부분은 의도한 부분이다 하면 의견을 남겨주시면 좋을 것 같아요.

2023-02-19 14:37 UTC, jamie9504 commented on src/main/java/view/InputView.java
> +    }
@eunkeeee 

Enum을 쓰는 이유가 단순히 생성자와 정적팩터리 메서드를 지우기 위해서라면 추천하기 어려울 것 같아요.

싱글턴으로 코드를 짜는 것을 깔끔하게 보이려고만 Enum으로 처리한다면,
모든 싱글턴 객체는 다 Enum이 되어버리겠죠?

Enum이 나타난 배경과 특징을 알아볼까요?

또한 생성자와 정적 팩터리메서드 패턴을 사용하는 것은 지저분하다고 생각하지 않아요.
필요한 부분은 오히려 드러나있어야 그 부분에 대한 파악이 쉽겠죠?

2023-02-19 14:37 UTC, jamie9504 commented on src/main/java/view/InputView.java
> +        int size = Integer.parseInt(input);
@eunkeeee 

정규표현식으로 비교하는 건 비용이 크기도 하고,
정규표현식을 모른다면 코드를 이해하고 수정하는 데도 시간이 조금 걸리기도 하죠.

2이상 100이하의 자연수라면, 아래와 같은 순서로 검증하면 정규표현식이 굳이 필요하지 않을 것 같은데요.
1. parseInt나 parseLong으로 숫자화(자연수화)하고,
2. 값을 2와 100이랑 비교

또한, NumberFormatException으로 예외를 catch하면, 해당 exception만 잡힐거고
IllegalArgumentException으로 예외를 catch하면, NumberFormatException을 포함한 여러 exception을 잡을 수 있겠죠?

2023-02-19 14:37 UTC, jamie9504 commented on src/main/java/domain/Name.java
> +        NameValidator.validate(name);
@eunkeeee 

깃짱 나름의 원칙이 생겼군요! 😄 
이 원칙을 가져가되, 아마 페어나 팀원들과 의견이 다르다면 서로 어느정도까지 설득하고 수용해야 하는 부분이 있을거에요.
개발자마다 장/단점에 대해 생각하고, 선택하는 기준이 다를테니까요!

이번엔 깃짱이 생각하는 대로 구현해보면 될 것 같아요!

2023-02-19 14:37 UTC, jamie9504 commented on src/main/java/utils/validator/LadderSizeValidator.java
> +    }
@eunkeeee 

`validateInteger` 여도 될 것 같고, 뭐 이름은 지어주기 나름이죠 😄

2023-02-19 14:37 UTC, jamie9504 commented on src/main/java/utils/validator/LadderSizeValidator.java
> +    private enum Message {
@eunkeeee 

1. 안전한 비교 - 상수여도 가능, equals로 비교해도 무관
2. 무제한 인스턴스 생성 방지 - 상수여도 가능
3. 상수의 깔끔해보이는 용도 - 이 부분은 Enum으로 관리하는 게 더 깔끔한지는 잘 모르겠어요.
4. 문구를 통일할 때 편리함 - 이 부분도 상수여도 Format을 이용하면 가능하지 않을까요?

ExceptionMessage을 Enum으로 묶었을 때 다른 장점도 있을까요?

2023-02-19 14:37 UTC, jamie9504 commented on src/main/java/controller/MainController.java
> +    private Lines lines;
@eunkeeee 

다음과 같은 관리를 하면 안되는건가용 ?
이 부분이 아니라면, 어떤 부분을 얘기하시는지 이해를 잘 하지 못한 것 같아요!

```
실행_메서드() {
    이름 = 이름_받기_메서드()
    높이 = 높이_받기_메서드()
    사다리 = 사다리_생성_메서드(이름, 높이)
}

이름_받기_메서드() {
    try { 이름_받기 } catch (Exception e) { 예외_메시지 + 이름_받기_메서드() }
}

높이_받기_메서드() {
    try { 높이_받기 } catch (Exception e) { 예외_메시지 + 높이_받기_메서드() }
}

사다리_생성_메서드() {
    try { 사다리_생성 } catch (Exception e) { 예외_메시지 + 사다리_생성_메서드() }
}
```

2023-02-19 14:37 UTC, jamie9504 commented on src/main/java/controller/MainController.java
> +    }
@eunkeeee 

> 메서드 이외에도 다음 State에 대한 Status를 정의해서 게임의 상태를 좀 더 명확하게 할 수 있다.
> _다음 할 일을 명확하게 알 수 있다_는 느낌이 저는 들었어요!
> 물론 또 이 패턴을 처음 접하는 사람은 좀 당황스러울 것 같기도 합니다.

저는 이 부분은 메서드명을 적합하게 적고, 흐름대로 호출한다면 충분히 메서드로 호출을 알 수 있다고 생각합니다.
또한 게임의 상태를 알고 싶다면, 게임이라는 객체를 만들어서 그 객체에 위임해야하는 게 아닐까요?

``` java
    public void start() {
        inputName();
        inputHeight();
        createLines();
        printResult();
    }
```

> [샘플 코드](https://github.com/woowacourse-precourse/java-bridge/pull/1207/files#diff-1dfdbc8d3a7d7196e50bdeb487fd139107f2e394cbcd162b1b69a466d1157206)에서 보시면, [간단한 설명](https://github.com/woowacourse-precourse/java-bridge/pull/1207#pullrequestreview-1304722681)도 달아놨어요!

샘플 코드를 참고했습니다.
`게임 시도 횟수`, `사용자에게 표시할 도표`, `게임의 상태(성공/실패여부)`를 관리하는 `GameVariable` 객체가 있었군요!
(여기서 `사용자에게 표시할 도표`를 만들고 반환하는 로직은 뷰에 해당하는 로직이니 도메인이 갖는 부분이 조금 어색한다고 생각하긴 해요)

`LadderCondition`이란 이름이 적합할지 모르겠지만, `names`, `height`, `lines`과 같은 변수들을 관리하도록 하면
생성되는 순간 사다리를 만들게 되니, 생성이 된 순간 `APPLICATION_EXIT`인 느낌이겠네요.

이같은 방식으로 리팩터링해보는 것도 좋을 것 같습니다.

2023-02-19 14:37 UTC, jamie9504 commented on src/main/java/domain/Names.java
> +    private static final String COMMA = ",";
@eunkeeee 

스플릿_기준 이라는 상수도 괜찮을 것 같고, 접미사로 `구분자(DELIMITER)`를 넣어도 될 것 같아요.

https://github.com/woowacourse/java-ladder/pull/53/commits/84e280401bf715775a98bc1f85c8f9ad58e54dfc

2023-02-19 14:37 UTC, jamie9504 commented on README.md
> +- [ ] 현재 사용하는 MVC 패턴의 `Controller`의 모습은 괜찮은 걸까? => 일단 `map`을 통해서 `gameGuide`를 받는 방식은, 다른 사람이 하는 것이 멋져 보여서 따라한 건데 내가 뚜렷한 장점에 대해 설명할 수 없으므로 적용하지 않기로 했다.
@eunkeeee 

남들 하는 게 좋아보여서 빠르게 흡수하고 사용하는 건 장점이라고 생각해요.
그렇지만 코드에 적용하기 전에 이걸 사용했을 때 장/단점이 무엇일지 고민해보고 장점이 크면 적용하면 좋을 것 같아요 😄

2023-02-19 14:37 UTC, jamie9504 commented on src/main/java/domain/Height.java
> +        public static final String _FORMAT = "[ERROR] %s";
@eunkeeee 

제가 새벽에....... 댓글을 달아놔서 정신이 잠깐 없었나봅니다 😢 

접미사로 부탁드려요! ex) `BASE_MESSAGE_FORMAT`

https://github.com/woowacourse/java-ladder/pull/53/commits/983adeb59373875e508f20518a21e28b9a6a7f26

2023-02-19 14:37 UTC, jamie9504 commented on src/main/java/domain/Names.java
> +        return new ArrayList<>(names);
@eunkeeee 

요건 왜 새로운 ArrayList로 보내게 되었을까요?

https://github.com/woowacourse/java-ladder/pull/53/commits/5b86d7b9cdc10295cb5f9de67eb5be6d81231291

2023-02-19 14:37 UTC, jamie9504 commented on src/main/java/domain/Name.java
>          public static final String _FORMAT = "[ERROR] %s";
@eunkeeee 

사이에 개행을 넣어줄까요?

https://github.com/woowacourse/java-ladder/pull/53/commits/a530e0b5a05d713f9885d8b8b89152fd1136dbc6

2023-02-19 14:37 UTC, jamie9504 commented on src/main/java/Application.java
> +import domain.booleanGenerator.RandomBooleanGenerator;
@eunkeeee 

자바 패키지의 네이밍에 대해 알아볼까요?

https://github.com/woowacourse/java-ladder/pull/53/commits/def18b67d1353a4d46724b42cd925524d0e47b40

2023-02-19 15:03 UTC, eunkeeee reviewed
일요일 밤까지 꼼꼼한 코멘트 감사드려요!_!_!
최대한 수정해봤습니다!

2023-02-19 15:03 UTC, gitchannn commented on src/main/java/view/InputView.java
> +    }
@jamie9504 

아직 좀 읽기 이르다는 생각은 들지만, 이펙티브 자바의 아이템3에서 싱글턴을 생성하는 방법 중 하나로 열거 타입의 방식을 제시하고 있어서 한 번 생각해봤습니다!

`아직 잘은 이해할 수 없지만, 추가적으로 복잡한 직렬화 상황이나 리플렉션 공격에서도 제2 인스턴스가 생기는 것을 완벽하게 막아준다`라고 하네요! 

아직 이해할 수 없는 장점이니, 이제까지의 방법으로 가겠습니다!

2023-02-19 15:03 UTC, gitchannn commented on src/main/java/view/InputView.java
> +        int size = Integer.parseInt(input);
@jamie9504 

넵...! 
이제까지 사용한 방법이 제이미가 알려준 1,2 방법인 것 같아요!
저는 좀 더 명확하게 하기 위해서 `NumberFormatException`을 `catch`하는 것을 좋아합니다!

2023-02-19 15:03 UTC, gitchannn commented on src/main/java/domain/Name.java
> +        NameValidator.validate(name);
@jamie9504 

넵 이번 미션에서는 `원시값 포장`이 요구사항이었으니, `domain`에서의 검증을 원했다고 저는 해석합니다! 감사해용

2023-02-19 15:03 UTC, gitchannn commented on src/main/java/utils/validator/LadderSizeValidator.java
> +    private enum Message {
@jamie9504 

`Message`라는 클래스로 만들어서 다른 상수(이 경우에는 `MIN_RANGE`와 `MAX_RANGE`)와 명확하게 분리되어 보일 수 있다는 또다른 이점이 있습니다!

또 저는 예외 메세지를 테스트할 때에도 이점이 있다고 생각하는데, 예를 들어서 출력되는 예외 메세지가 모두 `다시 입력해 주세요`여야 한다는 요구사항을 가진 프로그램이 있다고 할 때에, 현재 발생된 예외에 대해서도 더 쉽게 비교할 수 있다고 생각했습니다. 출력했을 때에 `enum`에 인스턴스 이름으로 설정한 `EXCEPTION_RANGE`같은 값이 나올 테니깐요! 

앞에서 언급한 `사용하는 큰 이유가 안전한 비교, 무제한 인스턴스 생성 방지, 상수의 깔끔해보이는 용도`는 제가 평소에 `enum`을 사용하는 이유이고, 예외 메세지에서 사용하는 이유는 `상수로 처리했을 때 좀 지저분해 보이는 경우도 많고`인데, 이건 제이미가 보기에는 상수가 더 깔끔할 수도 있을 것 같네요...!

예외 메세지를 원시값 포장한 느낌도 드는 것 같아요...!

2023-02-19 15:03 UTC, gitchannn commented on src/main/java/domain/Names.java
> +        return new ArrayList<>(names);
@jamie9504 

`View`에서 원본 `names`의 주소값을 받아서 허튼짓(?)을 할까봐 새로운 주소에 복사해서 보냈습니다...! 이번 미션에서는 돌아보니 `getter`만 존재하기 때문에 별도로 필요하지 않았을 수도 있겠네요..!

2023-02-19 15:03 UTC, eunkeeee commented on src/main/java/Application.java
> +import domain.booleanGenerator.RandomBooleanGenerator;
@jamie9504 

이 부분을 짚으신게 맞는지 모르겠지만...! 모두 소문자로 하는게 컨벤션이라 `booleangenerator`로 변경했습니다.
한 단어로 하는게 좋다고 하는데 이번 이름은 줄이기는 좀 어려울 것 같아요

2023-02-20 03:19 UTC, jamie9504 requested changes
깃짱, 안녕하세요. 리뷰어 제이미입니다. 😄 

점심시간을 활용하여 코멘트를 조금 더 남겨봤어요.

피드백을 조금 남겨두었으니
수정하고 싶은 부분은 수정을 해주시고, 고민해볼 부분은 고민해보면 좋을 것 같아요. 😄 

오늘 미션 리뷰 요청 마감 전까지 재 리뷰 요청 주시면,
수정사항이나 코멘트에 대해 피드백 남겨두겠습니다.

그 이후에 리뷰 요청이 오거나, 따로 수정사항과 코멘트 없으시면 바로 머지할께요 😄

2023-02-20 03:19 UTC, jamie9504 commented on src/main/java/view/InputView.java
> +    }
@eunkeeee 

이펙티브 자바를 벌써 보셨군요!

일단 이펙티브 자바의 아이템3에서는 말씀하신 장점을 설명하고 있습니다.

저는 다음과 같이 현재 Enum을 통한 싱글턴을 아직 구현하지 않아도 된다고 생각했어요.

1. 일반 클래스로 싱글턴을 구현하는 것과 Enum으로 구현하는 것의 차이점을 알고 명확히 쓰고 있는가.
2. 해당 객체를 직렬화하고 있는가?
    - 하고 있다면 `readResolve()`를 사용할 순 없는가.
3. 리플렉션을 사용할만한 라이브러리, 프레임워크를 사용하고 있는가.

이 부분에 대해서 깃짱이 명확히 이런 장점이 있고 이런 부분을 위해서 이렇게 쓰고 있다라는 의견이 있다면 Enum으로 적용해도 좋을 것 같아요.
(적어도 페어를 설득할 정도의)

클래스의 앞부분이 지저분하다는 의견은 마땅히 필요한 생성자/정적팩터리메서드 선언이라서 객관적인 설득이 어려울 수 있을 것 같습니다.

2023-02-20 03:19 UTC, jamie9504 commented on src/main/java/utils/validator/LadderSizeValidator.java
> +    private enum Message {
@eunkeeee 

이 부분 제 의견을 조금 정리해서 얘기드려보자면,
`new Exception(예외메시지)`는 예외가 발생했을 때 개발자들이 참고하기 위한 메시지이고,
사다리 생성에서 깃짱이 작성한 예외 메시지는 사용자들이 참고해야 하는 View 성질의 메시지라고 생각했습니다.

`@toString`이 개발자들이 디버깅을 하는 용도로 사용하듯,
`new Exception(예외메시지)` 역시 개발자를 위한 부분이라고 생각했는데요.

즉, 요구사항과 관계 없이 어떤 상황에 대한 예외의 부가 설명(실패 관련 정보)정도라고 생각한 것 같아요.
실패 관련 정보다보니 한 클래스 내에선 반복적으로 사용할 일이 없고, 상수화나 enum화를 하는 것보단 메시지 그대로 넘기는 게 가독성이 좋다고 생각했습니다.
그래서 원시값으로 포장해야 할 이유를 느끼지 못한 것 같습니다.

물론 학습할 때 이 부분에 대해서는 충분히 exceptionMessage로 처리할 수 있고,
그렇기에 비교를 수월하게 하기 위해 상수나, enum으로 관리할 수도 있었을 것 같아요. 😄

2023-02-20 03:19 UTC, jamie9504 commented on src/main/java/domain/Names.java
> +        return new ArrayList<>(names);
@eunkeeee 
허튼짓에 대한 고찰을 한 번 해보는 것도 좋을 것 같아요 😄 

1. new ArrayList로 포장해보내기 vs unmodifiablelist로 포장해보내기
2. 위의 두 경우 내부의 name 주소는 그대로 가져가서, 허튼짓(?)을 할 수 있지 않을까

요런 부분이요!

2023-02-20 03:19 UTC, jamie9504 commented on src/main/java/Application.java
> +import domain.booleanGenerator.RandomBooleanGenerator;
@eunkeeee 

대/소문자에 대한 체크 ✅ 는 맞았구요.

패키지명이 `booleanGenerator`일 필요가 있는가에 대한 고민도 해보면 좋을 것 같아요!
예를 들어, `MainController.java` 컨트롤러가 `maincontroller`라는 패키지에 속하는 건 아닌 것처럼요!
패키지명이 명확히 해당 클래스만 가리킬 필요가 있는지의 고민이에요 😄

2023-02-20 05:20 UTC, eunkeeee commented on src/main/java/domain/Names.java
> +        return new ArrayList<>(names);
@jamie9504 

그렇네요...!

현재 `Names` 객체 내부의 `names` 의 `List<Name>` 에 대한 주소가 바뀔 뿐,
내부 요소들인 실제 `Name`은 원본의 주소가 그대로 전달되고 있네요...!

현재는 `Name`에서 `name` `String` 필드를 `final`로 관리하고 있어서 변경의 여지가 없겠지만, 만약에 이것조차 다른 클래스를 필드로 가지고 있는거라면, `getter`에서 다른 주소에 새로 클래스를 생성해서 보내는 방법도 있을 것 같아요..!

2023-02-20 05:20 UTC, eunkeeee commented on src/main/java/view/InputView.java
> +    }
@jamie9504 

알겠습니다!_!_! 

현재 2,3번은 아직 어려운 레벨이니 단계에 적절하게 장단점을 완전히 이해한 툴만 사용하라는 뜻이군요! 
다음 미션부터는 습관적으로 사용하면서 장단점에 대해 잘 모르던 부분들을 의식적으로 사용해볼게요!

2023-02-20 05:20 UTC, eunkeeee commented on src/main/java/utils/validator/LadderSizeValidator.java
> +    private enum Message {
@jamie9504 

아하...! 

`new Exception(예외메시지) 역시 개발자를 위한 부분이라고 생각했는데요.` 이 부분이 제가 한번도 생각해보지 못한 내용이었던 것 같습니다...! 그 자리에 남기는게 개발자끼리의 소통에는 더 좋을 것 같다는 것도 공감합니다!

저는 이제까지 제이미가 `깃짱이 작성한 예외 메시지는 사용자들이 참고해야 하는 View 성질의 메시지라고 생각했습니다.`라고 말해준 것처럼 주로 사용자에게 보여지는 메세지로 생각하고 작성해 왔어요.

감사합니당!

2023-02-20 05:20 UTC, eunkeeee commented on src/main/java/Application.java
> +import domain.booleanGenerator.RandomBooleanGenerator;
@jamie9504 

그렇네요...! 
`generator`로 수정했습니다...!

2023-02-20 08:43 UTC, jamie9504 approved these changes
고생하셨습니다.

이만 Approve하겠습니다 👍 

2단계도 화이팅입니다.

2023-02-20 08:43 UTC, merged

2023-02-20 09:25 UTC, jamie9504 commented on src/main/java/domain/Names.java
> +        return new ArrayList<>(names);
@eunkeeee 

그래서 DTO를 따로 만들기도 하는거죠 😄 👍

2023-02-20 10:55 UTC, wugawuga commented on src/main/java/domain/generator/TrueBooleanGenerator.java
> +}
true 만 반환하는 클래스를 만드신 이유가 테스트일 거라고 생각이 들어요.
그러면 클래스 위치가 테스트 쪽에 있어도 괜찮을 것 같은데 어떻게 생각하시나용?

2023-02-21 00:56 UTC, eunkeeee commented on src/main/java/domain/generator/TrueBooleanGenerator.java
> +}
@wugawuga 

클래스 자체를 테스트 패키지로 옮겨버리는 방법은 생각해본 적이 없네요....!
일단은, 만들어놓고 사용도 안한 상태라서, 사용하게 되면 생각해보겠습니다!

2023-02-21 09:59 UTC, Hyeonjae-K commented
이번 페어 진행하며 깃짱 덕분에 많이 배웠습니다 :)
종종 코드 훔쳐보러 올게요!!

from. 페어 제리