[1단계 - 사다리 생성] 도기(김동호) 미션 제출합니다.
woowacourse/java-ladder pull request #57
Opened 2023-02-15 10:23 UTC by kdkdhoho

안녕하세요! 서브웨이 🙇‍♂️
BE 5기 도기입니다. 사다리 미션 동안 잘 부탁드립니다 ☺️

# 소감
이번 미션으로 처음으로 TDD를 시도해보았어요. 처음 해보는 방식의 개발이다보니 재밌게 느껴졌습니다!
그리고 확실히 구현하려는 로직의 테스트 코드를 먼저 작성하니까`프로덕트 코드의 안정성의 증가`와 `전체 프로젝트의 안정성`을 몸소 느낄 수 있었습니다.
하지만, 확실히 `시간이 많이 걸리는 작업`이라는 것도 동시에 느꼈네요🤣

# 질문
- `TDD 방식으로 개발을 진행할 때의 커밋 단위`가 궁금합니다.
현재 크루들 사이에서 애기가 나오길, `test -> feat -> refactor` vs `TDD 한 사이클`이 주 쟁점입니다.
서브웨이는 어떤 단위로 TDD를 하시나요??
또한, 실패하는 테스트가 있으면 커밋을 해선 안된다고 들었는데 TDD의 경우 필연적으로 실패하는 테스트를 만들 수 밖에 없게 됩니다. 이때는 허용이 되나요?
이와 관련해서 너무 궁금해요 !!

2023-02-17 05:11 UTC, joseph415 requested changes
안녕하세요 도기! 미션 구현하느라 고생 많으셨습니다!

클래스 책임 분리, 작은단위 함수로 구현을 해주셨네요!  💯 
코드를 가독성도 좋아 리뷰하기 수월했던것 같습니다!

몇가지 코멘트 남겼습니다. 확인 부탁드려요!

2023-02-17 05:11 UTC, joseph415 commented on README.md
> +
입력, 출력 요구사항을 자세하게 남겨주셨는데요!..

현재 도메인 내부에 로직들이 전부 입력,출력 요구사항으로 들어가있고, 주요 객체 속성, 역할로 작성해주신 부분이 조금 빈약한 것 같습니다. (잘 보면, 도메인이 가지는 속성들만 나열한것 같아요)

도메인 비지니스 요구사항을 도메인 영역별로 남겨보는것은  어떻게 생각하시나요?! 

요구사항 작성도 문서화과정이라고 생각하는데, 나중에 합류할 팀원이나, 사다리 게임을 개발하지 않은 개발자가 해당 코드를 볼 때, 도메인별 요구사항이 구체적으로 나와있을 경우 스펙을 파악하는데 수월할거라 생각해요!

이렇게 작성하면, 하나의 커밋에 하나의 비지니스 요구사항 기능이 들어가 명확하게 구분이 될 수도 있다고도 생각합니다.

ex)
### 플레이어
- 각 플레이어는 5글자를 넘기면 안됨, 이때 빈입력값일 경우 에러
- 플레이어들은 13명을 넘길 수 없음
- ...

### 사다리 
- 이름의 길이가 늘어날 경우 사다리 폭도 늘어나야 함
- ...

도기 방식이 안좋다는건 아니고, 이렇게 작성하는것도 좋은 방향인것 같다 라는 의견을 드려요ㅎㅎ

2023-02-17 05:11 UTC, joseph415 commented on README.md
> +- 이때, 실패하는 테스트를 구현한 뒤 커밋을 할지, 아니면 전체 기능을 전부 구현한 뒤 커밋할 지 궁금합니다.
질문에 대한 답변을 여기에 남길게요ㅎㅎ

> test -> feat -> refactor vs TDD 한 사이클

리뷰하는 입장에서, 첫번째처럼 되어있으면 TDD로 잘 코드를 작성했는지는 파악할 수 있지만ㅎㅎ,, ( 해당 과제 커밋을 첫번째 처럼 잘 나눠주셔서 실제로 파악하기는 쉬웠습니다ㅎㅎ 감사해요ㅋㅋ)

제가 TDD로 개발했을 당시에는, TDD한 사이클을 커밋단위로 사용했습니다. 커밋이 불필요하게 많이 쌓이는 것을 방지하기 위해서 그렇게 했는데요, 하나의 커밋이 기능단위로 분리가 되어있어야 해당 커밋을 잘 이용할 수 있더라고요ㅎㅎ(채리픽을 한다던가 등등..) 다른 사람이 커밋을 파악하기도 쉽고요.

제 생각은 이런데, 도기생각은 어떤지 궁금합니다. 정답은 없으니까요ㅎㅎ

> 실패하는 테스트가 있으면 커밋을 해선 안된다고 들었는데 TDD의 경우 필연적으로 실패하는 테스트를 만들 수밖에 없게 됩니다. 이때는 허용이 되나요?

'test -> feat -> refactor 사이클로 개발했을 때' 라는 가정이 들어간거 같은데 그렇다면, Tdd 싸이클중 테스트를 동작하게 만드는 과정까지 test 커밋으로 남기면 될 것 같네요ㅎㅎ

2023-02-17 05:11 UTC, joseph415 commented on src/test/java/ladder/util/CustomLineStrategy.java
> +public class CustomLineStrategy implements LineStrategy {
인터페이스 활용해서 test 전용 객체 만드신것 👍

2023-02-17 05:11 UTC, joseph415 commented on src/main/java/ladder/domain/Player.java
> +    private final Name name;
원시값을 포장하는것이 기능 요구사항이긴 한데,  플레이어와 네임을 나뉘어서 플레이어가 하는 역할이 없는것 같습니다.

player가 name 이라는 원시값을 포장한 객체가 되야한다고 생각하는데, 도기 생각은 어떤가요?
Player객체가 하는 역할이 무엇인가요?!

2023-02-17 05:11 UTC, joseph415 commented on src/main/java/ladder/domain/Players.java
> +        String[] names = input.split(DELIMITER);
Players의 책임을 생각했을 때, 

```java 
String[] names = input.split(DELIMITER);
```

입력값을 쪼개는 역할을 하는데, 해당역할은 Input에서 해야하지 않은가 라는 생각이 드는데요!
입력값을 쪼개는 역할을 Players가 하게되니 입력에 대한 에러도 player에서 발생하고 Players가 가져야할 책임이 아닌것이 테스트로 작성된것 같아요

PlayersTest를 보면, 아래와 같은 테스트가 있는데 Players가 가져야할 테스트가 아닌것 같습니다.
```
@DisplayName("사용자 이름이 입력되면 콤마(,) 로 구분한다.")
```

제가 정답은 아니니,,ㅎㅎ 도기생각은 어떤가요?

2023-02-17 05:11 UTC, joseph415 commented on src/main/java/ladder/util/LineStrategy.java
> +package ladder.util;
해당 전략이 utils에 들어있는게 맞을까요?

utils클래스들은 도메인과 연관이 전혀없는 있어도 되고, 없어도 되는 사용자 편의를 주는 것들이 들어가야 합니다!
ex). StringUtils

LineStrategy는 도기가 생각했을 때, LineStrategy의 역할은 무엇인가요?!

2023-02-17 05:11 UTC, joseph415 commented on src/main/java/ladder/util/LineStrategy.java
> +public interface LineStrategy {
인터페이스 사용👍

2023-02-17 05:11 UTC, joseph415 commented on src/main/java/ladder/controller/LadderController.java
> +        ladderView.printResult(players.asString(), ladder.asString());
공백 라인없이 이렇게 작성되면 가독성이 떨어지는데, 공백라인을 적절하게 활용하셨으면 좋겠습니다.

2023-02-17 06:12 UTC, kdkdhoho commented on README.md
> +
저도 100% 동의합니다.
말씀을 듣고 스스로 돌아보니, `주요 객체들의 속성과 역할` 을 적어놓고는, 실제로는 속성만 적어 놓았구나 하는 생각이 강하게 드네요🥲
감사합니다 !!

2023-02-17 06:38 UTC, kdkdhoho commented on README.md
> +- 이때, 실패하는 테스트를 구현한 뒤 커밋을 할지, 아니면 전체 기능을 전부 구현한 뒤 커밋할 지 궁금합니다.
> 리뷰하는 입장에서, 첫 번째처럼 되어있으면 TDD로 잘 코드를 작성했는지는 파악할 수 있지만ㅎㅎ,, ( 해당 과제 커밋을 첫 번째처럼 잘 나눠주셔서 실제로 파악하기는 쉬웠습니다ㅎㅎ 감사해요ㅋㅋ)

파악하기 쉬우셨다니, TDD를 괜찮게 적용했구나는 생각이 드네요. 🙂
그리고 확실히 실무에서는 여러 사람이 많은 커밋을 하게 될 텐데, `test - feat - refactor` 단위로 커밋하면 커밋 로그를 볼 때 힘들겠다고 생각됩니다.
또한 TDD로 개발을 하는 것은 개발자 본인이 `불확실하거나 익숙하지 않은 도메인을 개발`할 때 `불안함을 해소하고 실수를 줄이기 위해` 한다고 생각하는데, 실무에서는 이를 커밋 로그로 나타낼 필요보다 하나의 기능을 올바르게 구현했음을 남기는 것이 적절하다고 생각됩니다. 

덕분에 TDD의 커밋 단위에 대해 생각을 정리할 수 있게 됐습니다. 감사해요😄

2023-02-17 06:46 UTC, kdkdhoho commented on src/main/java/ladder/domain/Player.java
> +    private final Name name;
저희도 `모든 원시 값과 문자열을 포장한다` 는 요구사항을 지키기 위해 이렇게 구현을 했습니다.
구현 후에도 Player가 getter밖에 없어 찝찝함을 느끼긴 했는데, `Player`가 `String name` 을 포장한 객체가 된다는 생각을 못했습니다.
덕분에 `원시값 포장이 무엇인지`에 대해 생각해 볼 필요성을 느꼈습니다. 감사합니다!

2023-02-17 08:48 UTC, kdkdhoho commented on src/main/java/ladder/domain/Players.java
> +        String[] names = input.split(DELIMITER);
저도 100% 동의합니다. 사실 `입력 요구사항`에도 `참여할 사람의 이름은 ','로 구분된다.`라고 적어두었음에도 불구하고 이 역할을 `Players` 에게 위임했네요.
바로 수정하겠습니다!

2023-02-17 08:54 UTC, kdkdhoho commented on src/main/java/ladder/util/LineStrategy.java
> +package ladder.util;
제가 생각했을 때 `LineStrategy`의 역할은, `프로덕트 코드와 테스트 코드에 적절히 다른 구현체를 사용하여 일종의 전략 패턴을 위한 인터페이스`라고 생각합니다.
`Strategy`를 왜 util 패키지에 위치시켰는지 생각해 보았는데, 명확한 기준이나 판단 없이 뭔가 util에 위치시켜야 될 것 같다는 느낌으로 했던 것 같아요.

말씀하신 util 클래스들이 무엇인지에 대해 생각해 보겠습니다. 그리고 앞으로 전략이 util에 속하는지, domain에 속하는지 등에 대해 한 번 더 고민하는 습관을 들여야겠어요!

2023-02-18 13:18 UTC, kdkdhoho commented
안녕하세요 써브웨이☺️ 편안한 주말 보내고 계신가요??
남겨주신 피드백 모두 적용해 보았습니다!

동시에 `Controller와 Service를 제거하고, main 메서드에서 프로그램이 실행되도록` 구조를 변경해 보았어요.
이유로는, 최근 크루들과 Controller와 Service의 필요성에 대해 이야기를 나누고 고민한 결과로, `아직은 작은 규모에 단일 환경의 콘솔 프로그램`인 데다가 `아직은 Controller가 여러 개 존재하지 않아도 되는 이유`입니다.
물론 단일 Controller와 비즈니스 로직을 처리하기 위해 Service 단을 두어도 틀렸다고는 생각하지 않습니다만, 한번 Controller와 Service 없이 해보고 싶다는 생각에 시도해 보았습니다.

그럼 이번 리뷰도 감사합니다😉

2023-02-19 18:00 UTC, joseph415 commented on src/main/java/ladder/domain/Player.java
> +    private final Name name;
물론, 도메인적인 표현이나, 비지니스 로직을 객체가 수행하도록 name을 포장해서 값 객체 (VO)로 사용할 수 도 있는데요ㅎㅎ
지금 봤을 때는, Player에 name 속성으로도 충분히 표현이 가능한것 같아서 의견드렸습니다!

2023-02-19 18:10 UTC, joseph415 commented on src/main/java/ladder/util/LineStrategy.java
> +package ladder.util;
아 제가 질문드린건 도메인적인 질문이였습니다ㅎㅎ **LineStrategy 전략은 Line을 만드는 중요한 비지니스 개념**라고 생각하는데요! 따라서, 해당 개념은 도메인 패키지안에 위치하는게 맞을 것 같아서 질문드렸어요!

전략패턴을 사용하는 이유도 비지니스 변경사항을 좀 더 유연하게 변경하기 위해 사용하는 패턴이구요. (만약 라인을 만드는 비지니스 개념이 Random이 아니라, 수동으로 변경될 때 전략을 바꾸기만하면됨)

따라서 과제를 들어가기 전에, 처음에 말씀드린 리뷰 (https://github.com/woowacourse/java-ladder/pull/57#discussion_r1109280202) 처럼 요구사항을 도메인 영역 별로 나뉘어 보고, 그 나뉜 도메인을 생각하면서 패키지를 구성해 나가면 객체지향적이고, 도메인 집약적으로 만들어질 거라 생각합니다!

2023-02-19 18:36 UTC, joseph415 approved these changes
안녕하세요 도기! 1단계 피드백 잘 반영해주셨네요 💯
코드가 정말 깔끔해진 것 같아요. 👍  1단계 코멘트에 추가 답변을 달았습니다. 확인 부탁드려요!
이번 단계는 여기서 merge 하겠습니다! 고생하셨습니다~!

2023-02-19 18:36 UTC, joseph415 commented on src/main/java/ladder/Application.java
> +
기존에도 코드 흐름을 읽기 편했는데, 매우 깔끔하게 변경됐네요👍

2023-02-19 18:36 UTC, joseph415 commented on src/main/java/ladder/domain/Players.java
> +    public List<Player> getPlayers() {
사용하지 않는 메서드가 있네요!

2023-02-19 18:36 UTC, joseph415 commented on src/main/java/ladder/view/InputView.java
> +        return input.split(",");
요것도 try catch 잡으면 어떤가해요ㅎ!

2023-02-19 18:36 UTC, merged