[1단계 - 사다리 생성] 주드(홍성민) 미션 제출합니다.
woowacourse/java-ladder pull request #61
Opened 2023-02-16 03:10 UTC by kevstevie

안녕하세요 웨지! 주드입니다.
tdd는 처음이라 힘들었네요.😅
boolean을 포장한 Line 객체의 일급컬렉션인 Floor, Floor의 일급컬렉션인 Ladder 형태로 설계하였습니다.
질문이 하나 있는데 제 설계는 예외처리를 도메인에서 하게 되는데 이런 경우 에러메시지를 도메인에서 결정합니다. 이런 경우 도메인이 뷰에 관여하고 있다! 라고 할 수 있을까요?

2023-02-16 09:59 UTC, sihyung92 requested changes
안녕하세요 주드! 어려운 미션인데 훌륭하게 구현하셨군요 👍 우주 최고의 의사결정기 사다리게임을 만들어주셔서 감사합니다.

질문 답변으로 시작할게요~

### 질문 답변

> 질문이 하나 있는데 제 설계는 예외처리를 도메인에서 하게 되는데 이런 경우 에러메시지를 도메인에서 결정합니다. 이런 경우 도메인이 뷰에 관여하고 있다! 라고 할 수 있을까요?

네 현재 구조에선 그렇죠! 그리고 도메인이 뷰에 관여하고 있는 건 주드의 아키텍처 결정사항입니다! 반대로 도메인이 뷰에 대해 알고 있고 뷰는 도메인이 모르게 하는 방식으로 구현해도 되겠죠. (굴러만 가면 뭐가 문제겠습니까?)
그런데 왜? 도메인은 뷰를 괴롭혀도 되고 뷰는 도메인을 괴롭히면 안 될까요?
주드 생각을 들려주세용~~

번외로, 도메인 에러메시지가 뷰를 타고 그대로 흘러나가는게 싫다면 어떻게 해야할까요? `hint :  예외 되던지기 / try catch`

### 추가 피드백
1. 커밋 로그를 살펴보니 line.a(), ladder.b() 같은 코드들이 보이더군요! 빠른 실패인 TDD의 철학을 위해 일단 실패하려고 하신 것 같아요 ㅎㅎ 
하지만 커밋은 원자적인 단위로 보셔야합니다~! 
좋은 커밋은 빌드를 깨뜨려서는 안 되며, 누구라도 해당 커밋으로 프로그램을 시작하거나 브랜치를 생성할 수 있는 것이 이상적입니다(저도 잘 안 지켜지긴 하는데요 ^^;) 
작게 커밋을 쪼개는 것이 좋지만 그게 미완성인 커밋을 해도 좋다는 의미는 아닙니다! 이런 점에서 TDD는 좋은 커밋을 만드는 데 강점이 있죠, 테스트 n개를 성공시킬 때마다 커밋으로 나누면 자연스럽게 원자적인 커밋이 쌓이니까요 :) 
다음 미션 부터는 "완성되었으면서" + "작은"  커밋을 만들기 위해 노력해보셔요~~! 

2. 포맷팅을 신경써주세요! 리뷰 중 포맷팅에 관련한 내용이 많은데요, (특히 무의미한 개행) 코드 실행엔 영향을 안 주니 별거 아닌거 같아도 가독성을 떨어뜨리고, 누군가 reformat을 돌렸을 때 기능 추가 없이 코드 변화를 일으켜 merge 충돌 가능성을 높입니다. PR을 만들기 전 전체 코드를 한번 점검하는 습관을 만들어 보셨으면 좋겠습니당!!

리뷰 반영 후 다음에 만나용~~~

2023-02-16 09:59 UTC, sihyung92 commented on src/test/java/ladder/domain/LadderTest.java
> +    private static List<Line> getFloorLines(int pos, Ladder ladder) {
사용되고 있지 않은 코드네요~!

2023-02-16 09:59 UTC, sihyung92 commented on src/test/java/ladder/domain/LadderTest.java
> +
두 줄 공백!

2023-02-16 09:59 UTC, sihyung92 commented on src/test/java/ladder/domain/LadderTest.java
> +        TestNumberGenerator testNumberGenerator = new TestNumberGenerator(List.of(1, 0, 0, 1, 1, 1));
테스트 메서드의 길이가 제법 길어지네요 ㅎㅎ given-when-then 스타일 테스트 작성에 대해 들어보셨나요? 
[마틴파울러의 블로그글](https://martinfowler.com/bliki/GivenWhenThen.html)
[선배의 발자취](https://tecoble.techcourse.co.kr/post/2020-04-24-one-test-must-check-one-scenario/)

한 가지의 기능을 해야하는 객체와 달리 테스트는 flow를 보여주어야 하고, 이 방법이 개발자마다 제각각이기에 테스트의 가독성이 하락합니다. 테스트 또한 유지보수 대상이므로 가독성을 신경써주어야 하는데, 이때 활용하기 좋은게 given-when-then 스타일이에요. 학습하고 적용해보실까요?

2023-02-16 09:59 UTC, sihyung92 commented on src/test/java/ladder/domain/LadderTest.java
> +                .extracting("isExist")
line의 isExist()라는 공개 메서드가 있는데 String literal을 통해 추출할 필요가 없습니다. 이렇게 문자열로 추출할 경우 변수명이 변경되었을 때 컴파일러가 감지하지 못 하고 런타임에 실패합니다. 
다른 방식으로 변경 해볼까요?

extracting으로 동작을 검증하는 코드가 여럿 보입니다~! 동일한 리뷰이므로 생략하겠습니다

2023-02-16 09:59 UTC, sihyung92 commented on src/main/java/ladder/domain/LineSource.java
> +    int odd;
Enum은 각 value가 단 한 개만 생성됨이 문법적으로 보장되는 static final "객체" 입니다. 다른 객체와 마찬가지로 캡슐화가 필요합니다~! `private final` 로 보호해주세요

2023-02-16 09:59 UTC, sihyung92 commented on src/main/java/ladder/domain/LineSource.java
> +    int odd;
ex) 누군가 로직 어딘가에 다음 코드를 삽입했다고 상상해보세용 
```
LineSource.MakeLine.odd = 10;
```

2023-02-16 09:59 UTC, sihyung92 commented on src/main/java/ladder/domain/Floor.java
> +
두 줄 공백이 보입니다!

2023-02-16 09:59 UTC, sihyung92 commented on src/main/java/ladder/controller/MainController.java
> +    public static void main(String[] args) {
main문은 root에 위치시켜주는 것이 좋습니다. 
자바는 main으로 시작해 main으로 끝나기 때문에, 객체 안에 main문이 있는 경우 어떤 객체에 main이 있을지 예측하기 어렵습니다. 대개의 경우 root 패키지에 main이 있기 때문에 root로 컨트롤러를 옮겨주시거나, "프로그램 시작"을 위한 class 를 만들어주세요! (어떤 걸 선택했는지 이유도 남겨주세용~~)

2023-02-16 09:59 UTC, sihyung92 commented on src/main/java/ladder/domain/Floor.java
> +    private final List<Line> lines = new ArrayList<>();
User의 경우 일급컬렉션인 Users를 만들어주셨는데 line은 컬렉션으로 할당하셨군요? :) 
일급 컬렉션을 생성하는 별도의 기준이 있으신가요?

2023-02-16 09:59 UTC, sihyung92 commented on src/main/java/ladder/view/OutputView.java
> +        if (Pattern.matches(KOREAN_MATCH_REGEX, hi)) {
가운데 정렬 맞추고 싶은 욕심을 불러 일으키네요 ^^;;;;; 하지만 이건 뷰 로직이라 패스하겠습니다 ㅎㅎ
<img width="418" alt="image" src="https://user-images.githubusercontent.com/51393021/219298615-c2dfe5cd-d841-469c-8102-6315339f1c14.png">

2023-02-16 09:59 UTC, sihyung92 commented on src/main/java/ladder/view/OutputView.java
> +    public static void printResult(Users users, Ladder ladder) {
메서드 분리를 잘 해주셔서 읽기 좋았습니다 👍

2023-02-16 09:59 UTC, sihyung92 commented on src/main/java/ladder/domain/Users.java
> +
메서드간의 개행 구분을 두는 기준이 있으신가요? 도메인 객체마다 다른 것 같아서 여쭙습니다 🙇🏻 개행도 코드를 읽는 흐름에 영향을 주기 때문에 "가독성"에 중요한 요소입니다~! 어느 정도 기준이 있으면 좋습니다.

2023-02-16 09:59 UTC, sihyung92 commented on src/main/java/ladder/domain/Users.java
> +        return users;
방어적 복사 개념에 대해 알고 계신가요?
```suggestion
        return Collections.unmodifiableList(users);
```
방어적 복사에 대해 학습해보시고 ArrayList로 선언된 기타 객체들에 대해서 "방어적 복사"로 반환해주세요!
(그대로 반환하면 어떤 문제가 있을까요?)

2023-02-16 09:59 UTC, sihyung92 commented on src/test/java/ladder/domain/FloorTest.java
> +        Floor floor = new Floor(3);
-1층을 넣으면 어떻게 되나요? :)

2023-02-16 09:59 UTC, sihyung92 commented on src/test/java/ladder/domain/FloorTest.java
> +    void makeFloorBySIze() {
I가 대문자입니다!! 🦅

2023-02-16 09:59 UTC, sihyung92 commented on src/main/java/ladder/domain/User.java
> +    private final String name;
"모든 원시값을 포장한다"는 요구조건이 있네요 :)

2023-02-16 09:59 UTC, sihyung92 commented on src/main/java/ladder/view/OutputView.java
> +
2줄 개행 🦅

2023-02-16 09:59 UTC, sihyung92 commented on src/main/java/ladder/domain/LineSource.java
> +        return Arrays.stream(LineSource.values())
해당 메서드는 자주 호출 될 것 같은데요, 그 때마다 스트림 생성비용 때문에 성능 부하가 있겠어요 :) 어떻게 해결할 수 있을까요? (keyword : 캐싱)

2023-02-16 09:59 UTC, sihyung92 commented on src/test/java/ladder/domain/FloorTest.java
> +
의미 없는 개행이 보이네요~~ 💪

2023-02-16 09:59 UTC, sihyung92 commented on src/test/java/ladder/domain/FloorTest.java
> +        List<Integer> list = new ArrayList<>(List.of(1, 0, 1));
"라인이 생긴다"는 1, "라인이 생기지 않는다"는 0인가요? 
floor를 만드는 사람 입장에서 해당 메서드 시그니처를 봐서는 floor의 결과를 예측하기 어렵습니다. 

1과 0 대신 의미가 있는 객체로 전달할 순 없을까요? 😊 (hint : enum || wrapper class || dto)

2023-02-16 09:59 UTC, sihyung92 commented on src/test/java/ladder/domain/LadderTest.java
> +    @DisplayName("1이상의 값으로 Ladder생성 시 사이즈 테스트")
테스트는 임계값으로 진행하는 게 좋습니다. 내용은 1 이상의 값인데 실제 테스트 값은 3으로, "1 이상"이 검증되지 않습니다.

2023-02-16 09:59 UTC, sihyung92 commented on src/test/java/ladder/domain/LadderTest.java
> +            assertThat(floor.getLines().size()).isEqualTo(2);
[디미터의 법칙](https://prohannah.tistory.com/204)을 아시나요? 최소지식원칙으로 이 원칙을 지키기 위한 규칙으로는 `한 개 이상의 .을 사용하지 마라` 라는 원칙이 제시됩니다. (== `getter를 남용하지마라` 와 연결되기도 하죠?)

Floor를 알면 getter를 반복하여 Line 내부값까지 볼 수 있습니다. 해당 테스트가 그 반증으로, 모든 세부정보가 노출되는 탓에 LadderTest는 Line 로직까지 모두 테스트를 해야하는 케이스가 되어 비슷한 테스트가 반복되고 있습니다! 

`Getter를 제거하고 메시지를 전달하는 방식으로 구성해볼까요?` 라고 하고싶은데요, 너무 큰 범위의 리팩토링이기 때문에 이 부분은 강제하지 않겠습니다 ^^; 
이번 미션에선 TDD에 집중하시고, 다른 크루들의 코드를 보며 어떤 코드가 테스트 하기 좋은 코드인지, 어떤 코드가 이해하기 쉬웠는지 느껴보셔요

2023-02-16 09:59 UTC, sihyung92 commented on src/test/java/ladder/domain/LineTest.java
> +    void makeTrue() {
1외의 값은 어떻게 되나요? :)

2023-02-16 09:59 UTC, sihyung92 commented on src/test/java/ladder/domain/UsersTest.java
> +        List<String> users = List.of("가나", "여섯자리이름");
아래 3개의 테스트는 각각 어떤 validaton으로 인해 성공했는지 알 수 없습니다.
"단일 유저만 가능하다" 는 정책이 추가되도 해당 테스트는 성공합니다~!
어떻게 해당 케이스가 "비정상 유저이름"으로 인해 발생한 오류인지 확인할 수 있을까요? :)

2023-02-16 09:59 UTC, sihyung92 commented on docs/README.md
> +- [ ] 이름과 사다리를 출력한다.
완료되었으니 체크✅ 부탁드립니다!

2023-02-16 09:59 UTC, sihyung92 commented on docs/README.md
> +# 기능 요구 사항
readme를 docs 하위로 빼신 이유가 있으실까요? 😊 

이 글을 읽는 사람은 미래의 주드나 다른 개발자 일텐데요, 이 개발자는 "기능명세서가 있다"는 정보가 없을수도(잊었을수도) 있습니다. 레포지토리에 진입하자마자 확인할 수 있도록 root에 두어도 좋고요, 아니라면 레포지토리 root README.md에 "상대경로 docs/README.md에 기능명세서가 있다" 는 방법도 좋죠.
 
현재 방식은 "기능 명세서가 있다"는 걸 알고있는 사람만 확인할 수 있는 글인거 같아요.

2023-02-16 09:59 UTC, sihyung92 commented on docs/README.md
> +  - [X] 이름이 다섯글자 이상이거나 공백이면 예외를 던진다.
윗 라인은 "다섯 글자 이하", 해당 라인은 "다섯 글자 이상" 이네요. 5일 때 어떻게 되나요?

2023-02-16 09:59 UTC, sihyung92 commented on docs/README.md
> +  - [X] 전략 패턴을 이용해 TestNumberGenerator를 만들어서 테스트
상위 개념에서 하위 개념으로 내려가는 것이 좋지 않을까요?
정리가 잘 된 글들의 공통적인 특징은 "잘 분류되어 있다"는 점인데요, 해당 명세서는 
Ladder > Floor > Line 으로 이어지는 도메인 개념의 흐름과는 달리 "사람의 이름 -> Line의 명세 -> 높이 -> 사람의 컬렉션 -> 사다리" 로 이어지고 있어 읽는 사람으로 하여금 해당 기능에 대한 멘탈 모델을 형성하기 어렵게 합니다.

"해당 미션을 유지보수하러 온 개발자가 이해하기 좋은 글"을 목표로 수정해볼까요?

2023-02-16 09:59 UTC, sihyung92 commented on src/test/java/ladder/domain/FloorTest.java
> +public class FloorTest {
코드 전체의 테스트 커버리지가 높네요!! :+1:

2023-02-16 09:59 UTC, sihyung92 commented on src/main/java/ladder/view/InputView.java
> +    private InputView() {
유틸 클래스의 인스턴스화 방어 👍

2023-02-16 09:59 UTC, sihyung92 commented on src/main/java/ladder/domain/Ladder.java
> +public class Ladder {
일급컬렉션의 정의는 [이동욱님 블로그](https://jojoldu.tistory.com/412)에 잘 나와있습니다! 거기에 보면 이런 내용이 있죠. 
> Collection을 Wrapping하면서, 그 외 다른 멤버 변수가 없는 상태를 일급 컬렉션이라 합니다.

하지만 Ladder 객체가 일급 컬렉션의 역할만 수행하는 작은 단위의 도메인인지 의문이 드네요! 일급 컬렉션 요구사항을 충족하고자 기계적 적용을 한 사례로 느껴집니다.

2단계에 접어들면 유저가 간 길도 따라가야하고, 결과도 알려주어야 하는데 Floor라는 객체만으로 가능할까요? 해당 사례에선 Floors 일급 컬렉션을 만들고 floor에 대해 반복되는 for문 로직들을 추상화했어야 하지 않을까 하는 의견입니다~!

여기에 대해 주드의 의견을 들려주세요!! 😊

2023-02-16 09:59 UTC, sihyung92 commented on src/main/java/ladder/domain/Ladder.java
> +
2줄개행~!

2023-02-17 12:52 UTC, kevstevie commented on src/main/java/ladder/domain/Floor.java
> +    private final List<Line> lines = new ArrayList<>();
저는 Floor를 line의 일급컬렉션으로 생각하고 만들었습니다. 각 line들을 생성하는 역할을 가지고 있는데 밑에 말씀하신 Ladder와 Floor의 관계처럼 기계적 적용의 사례가 될까요?

2023-02-17 12:53 UTC, kevstevie commented on src/main/java/ladder/domain/Users.java
> +        return users;
컬렉션 반환 메서드들 방어적 복사로 수정했습니다.. 참조값을 그대로 주면 원래 값도 수정되는 문제가 있었군요..

2023-02-17 12:56 UTC, kevstevie commented on src/test/java/ladder/domain/FloorTest.java
> +        Floor floor = new Floor(3);
Ladder 에서 받은 users로 width를 계산하고 floor에 size로 넘겨주게 되는데 users는 자체적인 검증으로 사이즈가 2이상이 되어서 검증 로직이 필요 없다고 생각했습니다. 이런 경우도 검증이 필요할까요🤔

2023-02-17 12:57 UTC, kevstevie commented on src/test/java/ladder/domain/FloorTest.java
> +        List<Integer> list = new ArrayList<>(List.of(1, 0, 1));
생성로직이 boolean을 통해 생성하게 바꾸었는데 List.of(true, false, true) 같은 경우도 의미를 전달하기 힘들까요?

2023-02-17 13:11 UTC, kevstevie commented on src/main/java/ladder/domain/Ladder.java
> +public class Ladder {
저는 Ladder 객체가 floor의 일급컬렉션 역할만 맡고 user가 position 필드를 가지면서 사다리 타는 로직을 구현할 생각이었습니다.
Ladder가 floors를 생성하는 로직만 갖고 있다면 일급컬렉션의 역할을 충분히 하지 않을까요?

2023-02-17 16:09 UTC, kevstevie commented on src/test/java/ladder/domain/LadderTest.java
> +            assertThat(floor.getLines().size()).isEqualTo(2);
이번 미션으로 열심히 배워보겠습니다..!😢

2023-02-17 16:48 UTC, kevstevie commented
완성했다는 기쁨에 그만.. 컨벤션이 엉망진창이었네요. 열심히 수정했습니다.

boolean을 포장하던 Line이라는 객체가 getter setter만 가질뿐 객체로서 맡는 역할이 없다고 생각해서 제거하고 boolean을 가지는 enum으로 대체했습니다. 
테스트를 반복하고 있다는 생각이 들긴 했었는데 만약 floor 테스트케이스에서 통과한 로직을 그대로 ladder에서 사용한다면 그 부분에 대해선 테스트를 작성하지 않아도 될까요?
테스트는 나름의 given when then을 지켰다고 생각하는데 차마 체크칠 수 없어서 남겨놓았습니다.. 지금은 게터가 뷰와 테스트에서만 사용되는데 게터없이 출력이나 검증할 방법이 있을까? 생각하면 잘 모르겠습니다.🤔

뷰와 도메인의 의존관계에 대해선 "뷰가 수정될 때마다 도메인을 수정하지 않기 위해!" 라고 알고 있습니다.
뷰가 더 자주 수정되기 때문에 관성적으로 도메인이 뷰를 의존하지 않게 설계해야 한다고 생각합니다.
도메인에서 예외 메시지를 결정하지 않으려면..? 사용자 정의 예외를 만들어서 던지고 enum 같은 클래스에 메시지를 정해놓는 방법은 어떨까요?

2023-02-18 05:19 UTC, sihyung92 approved these changes
안녕하세요 주드! 테스트 실패로 인해 Request Change를 드리려고 했는데 이 코멘트를 쓰는 순간 푸쉬해주셨더군요 😈 다음부턴 PR 전에 먼저 확인 부탁드리겠습니당! 

## 질문 답변

Q. 테스트를 반복하고 있다는 생각이 들긴 했었는데 만약 floor 테스트케이스에서 통과한 로직을 그대로 ladder에서 사용한다면 그 부분에 대해선 테스트를 작성하지 않아도 될까요?
테스트는 나름의 given when then을 지켰다고 생각하는데 차마 체크칠 수 없어서 남겨놓았습니다.. 지금은 게터가 뷰와 테스트에서만 사용되는데 게터없이 출력이나 검증할 방법이 있을까? 생각하면 잘 모르겠습니다.🤔

A. 네 현재 예컨데 Floor의 validation에 대한 테스트를 Ladder에서 실행할 필요는 없다고 생각합니다. 대신 Ladder만의 validation은 존재하는데, 이 부분은 확실하게 테스트 해주어야겠죠 :) 

given when then 스타일에 대한 리뷰는 BDD에 대한 소개와 아래 주석 스타일로 테스트 내부에서 행위를 구분해주는 스타일에 대한 소개였습니다! :) 
간단한 테스트인 경우엔 필요 없지만, 10 라인이 넘어가는 복잡한 테스트에선 유효한 것 같습니다. 
```
void 테스트한다() {
  // given
  테스트_픽스쳐_준비();
  // when
  테스트_대상_메서드_실행();
  // then
  결과_확인();
}
```

Q. 뷰와 도메인의 의존관계에 대해선 "뷰가 수정될 때마다 도메인을 수정하지 않기 위해!" 라고 알고 있습니다.
뷰가 더 자주 수정되기 때문에 관성적으로 도메인이 뷰를 의존하지 않게 설계해야 한다고 생각합니다.
도메인에서 예외 메시지를 결정하지 않으려면..? 사용자 정의 예외를 만들어서 던지고 enum 같은 클래스에 메시지를 정해놓는 방법은 어떨까요?

A. "화면에 노출되는 예외 메시지 바꿔주세요!!" 요구사항이 도메인까지 영향을 미치지 않게 하려면, 뷰 예외 메시지를 뷰 단에서 결정해야겠죠! 그러려면 뷰 입장에선 어떤 에러메시지를 표출할지 결정하기 위해 서로 다른 도메인 예외들을 구분할 방법이 필요해집니다. 이 중 하나가 사용자 정의 예외고요! 다만 enum에 메시지를 정해놓는 방법은 개인적으로 비추천합니다. 해당 enum이 수많은 예외 객체들과 의존하게 되고, 그 enum이 코드 충돌의 새로운 아이콘으로 급부상하거나 해당 enum을 제거하는 결정을 했을 때 수백개의 예외 객체를 수정해야할 수 있습니다.

수고하셨습니다 주드! 리뷰가 있긴 하지만 Request Change보다는 2단계에서 반영해보시는 방향으로 해보시죠 😊 2단계에서 뵐게요~~

2023-02-18 05:19 UTC, sihyung92 commented on src/main/java/ladder/domain/Ladder.java
> +public class Ladder {
아하! 저는 Ladder쪽에서 User를 가지고 사다리를 내려가게 하는 설계를 의식했습니다 ☺️
다시 읽어보니 "기계적 적용" 은 다소 공격적으로 느껴지는 리뷰였네요 🙇🏻 사죄합니다
저는 주로 일급 컬렉션은 VO의 복수형으로 네이밍 하는데요, 그러다보니 제 시각엔 Ladder가 무언가 더 역할이 있는걸로 기대됐네요 ㅎ 주드가 의도하신 부분 이해했습니다!

User가 position을 가지고 있다면 차후 유저의 Position과 Ladder의 Postion을 연결하는 프로세서가 필요해질텐데요, 요 부분에 대한 객체설계가 필요해지겠네요 😈 2단계 때 기대해보겠습니다!!

2023-02-18 05:19 UTC, sihyung92 commented on src/main/java/ladder/MainApplication.java
> +
a6845759 리비전 등을 보면 메서드 시작부분에서 첫 줄 개행을 의식적으로 해주시는 것 같습니다 :) 혹시 해당 컨벤션에 어떤 의미가 있을까요? 메서드 시작 후 개행은 잘 보지 못한 것 같아 참고차 여쭙니다!

2023-02-18 05:19 UTC, sihyung92 commented on src/main/java/ladder/MainApplication.java
> +        OutputView.printResult(users, ladder);
저는 위 로직을 봤을 때 아래처럼 읽혔어요 :)  
```
유저들을 받아 사다리를 입력받는다. (사다리 입력에 유저가 쓰이나?)
유저와 사다리의 결과를 출력한다. (사다리 행위 없이 생성시에 바로 결과가 나오는건가?) 
 ㄴ 코드 추적 20초 후.. (아 결과가 아니라 사다리를 그려주는거네?)
 ```
아래였으면 조금 더 자연스럽게 읽혔을 것 같아요. 
```suggestion
        Ladder ladder = createLadder(users);
        OutputView.printLadder(users, ladder);
```
이런 부분은 일종의 문학적인 감수성이고, 이건 사람마다 느끼는 게 다르기 때문에 참고만 하시라고 피드백 남깁니다! 하지만 **항상 독자 입장에서 신경써야 한다**는 건 좋은 코드의 핵심이기 때문에 요 마인드만 가져가셨으면 좋겠어요

2023-02-18 05:19 UTC, sihyung92 commented on src/main/java/ladder/domain/Floor.java
> +    private final List<Line> lines = new ArrayList<>();
요 답변은 Ladder쪽 답변과 동일할 것 같아 갈음하겠습니다 :)

2023-02-18 05:19 UTC, sihyung92 commented on src/test/java/ladder/domain/FloorTest.java
> +        Floor floor = new Floor(3);
넹! Floor를 public 접근제어자 객체로 열어둔 순간부터 어떤 방식으로든 사용될 수 있습니다. `Floor는 Users에서 넘겨준 데이터로 생성된다` 라는 것은 가능한 시나리오 중에 하나이고, 그것이 코드적으로 제약되지 않기 때문에 기타 케이스로 오용될 수 있습니다. 그러므로 검증이 필요합니다.

2023-02-18 05:19 UTC, sihyung92 commented on src/test/java/ladder/domain/FloorTest.java
> +        List<Integer> list = new ArrayList<>(List.of(1, 0, 1));
0과 1 보단 낫고, 원시값 랩핑 객체보단 보단 의미 전달력이 떨어집니다. 현업에선 굳이 이런 경우까지 랩핑하진 않지만, 모든 원시값을 포장하라는 요구사항이 있기 때문에 boolean을 랩핑해보시는 걸 권장합니다 :)

2023-02-18 05:19 UTC, sihyung92 commented on src/test/java/ladder/domain/LadderTest.java
> +            assertThat(floor.getLines().size()).isEqualTo(2);
응원합니다아~~ 🥳

2023-02-18 05:19 UTC, sihyung92 commented on src/test/java/ladder/domain/LadderTest.java
> +        List list = List.of(true, false, true);
제네릭클래스의 Raw 타입 사용이 보이네요! 왜 raw 타입은 사용하면 안 되는지는 effective java의 item 26에 잘 나와있습니다!

2023-02-18 05:19 UTC, sihyung92 commented on src/main/java/ladder/domain/generator/LineGenerator.java
> +public interface LineGenerator {
더이상 Line은 없는데 PointGenerator가 적절하지 않을까요? 😀

2023-02-18 05:19 UTC, sihyung92 commented on src/main/java/ladder/domain/Floor.java
> +import java.util.ArrayList;
더 이상 사용되지 않는 import네요! 
IDE에서 Optimize Import라는 옵션으로 사용하지 않는 import를 자동으로 제거할 수 있습니다.
로직 수정 없이 타인의 optimize로 인해 클래스가 수정될 수 있어 코드 충돌 가능성을 높이므로 항상 사용 않는 import를 제거하는 습관이 필요합니당!

2023-02-18 05:19 UTC, sihyung92 commented on src/main/java/ladder/domain/Floor.java
> +    private final List<Point> points;
Point의 경우 생성자에서도 Boolean으로, getter에서도 Boolean으로 반환되네요! Floor를 생성하는 개발자 입장에선 아래 코드에서 어떤 객체가 생길지 예상하기 어렵습니다.

```
new Floor(List.of(true,false)); // F1을 통해 메서드 시그니쳐를 확인해봐도 "values" 라는 인자명이라 예측이 안 됨
```

기왕 enum을 만드셨으니 다음과 같은 처리는 어떨까요?
```
new Floor(List.of(FIIELD,EMPTY)); // 차있는, 비어있는 Point라는 것으로 층이 생성될 것임이 예측됨
```

2023-02-18 05:20 UTC, merged

2023-02-18 16:29 UTC, kevstevie commented on src/main/java/ladder/MainApplication.java
> +        OutputView.printResult(users, ladder);
처음보는 사람도 한번에 이해할만한 코드! 명심해야 할 것 같습니다.