[1단계 - 사다리 생성] 키아라(김도희) 미션 제출합니다.
woowacourse/java-ladder pull request #64
Opened 2023-02-16 04:38 UTC by kiarakim

2023-02-17 12:20 UTC, bimppap requested changes
안녕하세요 키아라, 춘식입니다!
커밋로그를 보니 TDD로 꼼꼼하게 잘 진행해주셨고, 코드도 객체지향에 맞춰서 잘 짠 것 같네요.
자잘하게 코멘트 남겨봤어요. 확인 부탁드립니다!
궁금한 점은 편하게 DM으로 물어봐주세요 :)

2023-02-17 12:20 UTC, bimppap commented on docs/README.md
> +  - [x] 사람들은 2 ~ 10명이
명세가 미완성인 것 같습니다! 👀

2023-02-17 12:20 UTC, bimppap commented on src/main/java/domain/People.java
> +			.count();
casting 과 parsing 의 장단점은 뭐가 있을까요?

2023-02-17 12:20 UTC, bimppap commented on src/main/java/exception/Error.java
> +	TOO_MANY_PEOPLE("사람은 최대 10명 이어야 합니다"),
사다리에 참여하는 인원은 2-10명 사이라고 한번에 알려주는게 틀린 입력 횟수를 줄일 것 같지 않나요?

2023-02-17 12:20 UTC, bimppap commented on src/main/java/view/InputView.java
> +			throw new IllegalArgumentException("높이는 숫자를 입력해야 합니다");
다른 에러처럼 Error enum을 사용하지 않고 문자열을 직접 넣은 이유가 있나요?

2023-02-17 12:20 UTC, bimppap commented on src/main/java/view/InputView.java
> +public class InputView {
클래스 내 배치 순서는 아래와 같이 맞춰주면 가독성이 더 좋을 것 같습니다 :)
```
class A {
    상수(static final) 또는 클래스 변수
    인스턴스 변수
    생성자
    팩토리 메소드
    메소드
    기본 메소드 (equals, hashCode, toString)
}
```
다른 클래스들도 순서를 맞춰주면 좋을 것 같아요.

2023-02-17 12:20 UTC, bimppap commented on src/main/java/domain/Stool.java
> +			.get();
여기서는 그럴 일이 없겠지만, 여러 개를 찾는 경우에는 get 대신 orElseThrow를 쓰는게 에러 잡기에 더 좋습니다.

2023-02-17 12:20 UTC, bimppap commented on src/test/java/domain/LadderTest.java
> +	@DisplayName("한 라인에는 반드시 하나의 발판이 있어야 한다")
<img width="743" alt="image" src="https://user-images.githubusercontent.com/48675973/219639924-7b0fa293-0ec8-4c64-9bcd-58e082eefb4e.png">
🤔

2023-02-17 12:20 UTC, bimppap commented on src/test/java/domain/LadderTest.java
> +	@DisplayName("한 라인에는 반드시 하나의 발판이 있어야 한다")
<img width="299" alt="image" src="https://user-images.githubusercontent.com/48675973/219644805-a12a44dd-0dec-4951-bfb2-6dfbf7974492.png">
빈 발판도 발판으로 봐야 하기에 테스트명을 좀 더 구체화하면 어떨가 싶습니다!

2023-02-17 12:20 UTC, bimppap commented on src/test/java/domain/LadderTest.java
> +class LadderTest {
<img width="282" alt="image" src="https://user-images.githubusercontent.com/48675973/219646699-85ba11f9-3826-421a-ab37-0f5ca83d3d09.png">
통과하지 않는 테스트들이 있는데 확인 부탁드립니다!

2023-02-17 12:20 UTC, bimppap commented on src/test/java/domain/LadderTest.java
> +class LadderTest {
<img width="493" alt="image" src="https://user-images.githubusercontent.com/48675973/219647371-975e9083-3ace-4ef8-a099-757dd9802c53.png">
여담으로 인텔리제이IDE에서는 테스트 커버리지를 돌려 테스트된 범위를 확인할 수 있습니다.
꼼꼼히 짜주셨군요 👍

2023-02-17 12:20 UTC, bimppap commented on src/main/java/domain/Level.java
> +		this.level = initLine(participantsSize);
level = initLine(participantsSize); 와 this.level = initLine(participantsSize);의 차이는 무엇일까요?

2023-02-17 12:20 UTC, bimppap commented on src/main/java/domain/Person.java
> +	public Person(String name) {
어떤 도메인은 정적 팩토리 메서드를 쓰고 어떤 도메인은 쓰지 않던데 구별한 기준이 있는지 궁금합니다!

2023-02-17 12:20 UTC, bimppap commented on src/main/java/controller/LadderController.java
> +	private void repeat(Runnable repeatable) {
Functional Interface 👍

2023-02-17 12:20 UTC, bimppap commented on src/main/java/controller/LadderController.java
> +			.map(LadderController::getLevel)
this::getLevel 을 쓰면 getLevel을 static으로 두지 않아도 됩니다 :)

2023-02-17 12:20 UTC, bimppap commented on src/main/java/exception/Error.java
> +public enum Error {
에러 메세지를 enum화 시킨 이유가 궁금합니다. 어떤 장점이 있을까요?

2023-02-17 15:07 UTC, bimppap commented on src/main/java/view/OutputView.java
> +		return "     ";
이런 건 상수화해둡시다!

2023-02-18 12:06 UTC, kiarakim commented on src/main/java/view/InputView.java
> +			throw new IllegalArgumentException("높이는 숫자를 입력해야 합니다");
InputView 에서는 출력의 기능만 갖고 있다고 생각하여 마지막에 Enum 처리를 할 때 꼼꼼하게 확인하지 못한 결과 같습니다.
이 에러 부분도 수정하도록 하겠습니다. 감사합니다!

2023-02-18 12:13 UTC, kiarakim commented on src/main/java/view/InputView.java
> +public class InputView {
넵! 
Scanner를 사용하기 직전에 Scanner 객체를 생성하면 '아 지금 스캐너를 사용할 예정이구나'라고 생각할 수 있지 않을까라고 생각해 이렇게 작성해보았는데 역시나 순서대로 선언해주는 것이 좋겠군요. 클래스 내에서 Scanner를 여러군데에서 쓴다고 그때마다 생성하지 않으니까요. 감사합니다.

2023-02-18 12:16 UTC, kiarakim commented on src/main/java/controller/LadderController.java
> +			.map(LadderController::getLevel)
아 이런 방법이 있었군요
수정하겠습니다 감사합니다!

2023-02-18 12:29 UTC, kiarakim commented on src/main/java/exception/Error.java
> +public enum Error {
여기 저기 퍼져있는 에러 메세지를 한 곳에 기록해두고 관리하기 좋을 것 같다 생각하여 enum화 했습니다..!
Enum를 사용했을 때 
- 코드의 양이 줄고 
- 인스턴스 생성과 상속을 시도할 경우 컴파일 에러를 내며 
- 상태와 행위를 한곳에서 관리할 수 있다거나 
- 리팩토링 시 변경 범위가 최소화 된다
는 장점이 있지만 저는 이번 미션에서 Enum의 코드만 수정하면 내용의 추가나 삭제가 간편하는 이유로 사용했던 것 같아요.

2023-02-18 12:35 UTC, kiarakim commented on src/main/java/view/OutputView.java
> +		return "     ";
상수화를 해야하나 고민했는데 역시나 처음 생각이 맞았네요. 수정하겠습니다. 감사합니다.

2023-02-18 12:42 UTC, kiarakim commented on src/main/java/exception/Error.java
> +	TOO_MANY_PEOPLE("사람은 최대 10명 이어야 합니다"),
아 생각해보니 그렇네요!
수정하겠습니다 감사합니다ㅎㅎ

2023-02-18 13:11 UTC, kiarakim commented on docs/README.md
> +  - [x] 사람들은 2 ~ 10명이
수정하는 도중 글자가 누락된 것 같습니다..!! 수정하겠습니다. 감사합니다

2023-02-18 13:15 UTC, kiarakim commented on src/main/java/domain/Level.java
> +		this.level = initLine(participantsSize);
this.level의 경우 파라미터로 level과 같은 이름의 변수가 들어왔을 때 모호성을 없애기 위해 이 클래스의 level 을 지칭하는 의미로 this.를 붙여줍니다. 위 코드의 경우 파라미터로 같은 이름의 변수가 들어오지 않았기 때문에 this.는 빼주어도 될 것 같습니다. 감사합니다!

2023-02-18 13:26 UTC, kiarakim commented on src/main/java/domain/People.java
> +			.count();
casting은 자료형을 변환하는 연산입니다
서로 다른 자료형을 가진 데이터들을 연산하는 경우 바이트 크기가 더 작은 자료형을 가진 변수에 저장해야 할 때 강제 형변환으로 자료형을 맞춰 줌으로써 해결할 수 있습니다. 다만 일반적으로 작은 자료형에서 큰 자료형으로 변환하고 그 반대의 경우에는
int i = (int)3.5;
위와 같이 0.5 가 탈락되고 3만 저장되는 데이터의 손실이 있을 수 있습니다.

parsing은 문자열을 다른 자료형(정수, 실수, boolean)으로 변환하는 것을 의미합니다.
문자열로 들어온 "100"이라는 입력을 parseInt메소드를 사용해 정수 100으로 반환해 사용할 수 있습니다. 그러나 문자열이 유효한 숫자를 포함하지 않는다면 NumberFormatException이 쓰로우 되기 때문에 문자열을 int로 바꿀때에는 항상 try-catch문으로 코드를 감싸서 이 익셉션을 처리해야 합니다.

위 코드의 stream 연산은 long을 리턴하는데 이를 (int)로 캐스팅하여 데이터 손실 가능성이 있는지 고려해보았습니다. 그 결과 이미 names를 가져오기 전에 사람의 수가 2~10명인 것을 검증 했기에 따로 instanceOf를 사용하지 않고 캐스팅해도 된다 생각했습니다.

2023-02-18 13:38 UTC, kiarakim commented on src/main/java/domain/Stool.java
> +			.get();
아하 넵.
이번 기회에 orElseThrow에 대해 공부할 수 있었습니다. 감사합니다.

2023-02-18 13:53 UTC, kiarakim commented on src/main/java/domain/Person.java
> +	public Person(String name) {
돌이켜보니 특별한 기준 없이 사용했던 것 같습니다. 
그러나 이번 리뷰를 기회삼아 정적 팩토리 메서드를 어떨 때 사용해야 하고 이로 인해 얻을 수 있는 장점은 무엇인지에 대해 잘 숙지하도록 하겠습니다. 감사합니다!

2023-02-18 14:08 UTC, kiarakim commented on src/test/java/domain/LadderTest.java
> +class LadderTest {
아 Enum으로 바꿔주면서 앞에 "[ERROR] "글자를 추가해주었는데 테스트메세지에선 이 부분을 수정하지 못했나봅니다. 
테스트 커버리지..이런 기능이 있었군요. 하나 배워갑니다~ 감사합니다ㅎㅎ

2023-02-18 15:26 UTC, kiarakim commented on src/test/java/domain/LadderTest.java
> +	@DisplayName("한 라인에는 반드시 하나의 발판이 있어야 한다")
혹시 사다리의 한 열에 몰빵(?) 혹은 한 열에 아무 발판이 없는 것은 잘못 만들어진 것일까요? 저희는 '발판이 없는 것도 사다리다'라고 생각하여 구현했는데 멀리서 바라보니 아닌가 싶기도 해서 여쭤봅니다!
그리고 말씀해주신 
`빈 발판도 발판으로 봐야 하기에 테스트명을 좀 더 구체화하면 어떨까 싶습니다!`
이 피드백에 대한 뜻을 이해하지 못했습니다ㅠ 
하여 테스트 이름을 라인이 아니라 행으로 수정했는데 제가 잘못 이해한 것일까요...?

2023-02-19 09:36 UTC, bimppap commented on src/test/java/domain/LadderTest.java
> +	@DisplayName("한 라인에는 반드시 하나의 발판이 있어야 한다")
아... 제가 라인을 행이 아닌 열로 착각했군요ㅋㅋ; 넘어가셔도 좋습니다! 🥲 

여담으로 한 열에 발판이 몰빵되거나 아무 발판이 없는게 잘못 만들어진 건 아니지만, 보통 사다리 게임을 할 때 열이 비어있는 경우는 없으니까요. 여유가 있다면 해당 케이스도 막아보는 시도를 해봐도 좋을 것 같네요.

2023-02-19 09:43 UTC, bimppap approved these changes
안녕하세요 키아라!
리뷰 반영 잘 해주셨어요 👍 👍  코드가 훨씬 더 깔끔해진 것 같네요ㅎㅎ
이번 단계는 이만 머지하도록 하겠습니다! 
다음 단계도 파이팅입니다! 궁금한 점이 있다면 언제든지 DM 주세요 😉

2023-02-19 09:43 UTC, merged