[1단계 - 사다리 생성] 우르(김현우) 미션 제출합니다.
woowacourse/java-ladder pull request #66
Opened 2023-02-16 04:51 UTC by java-saeng

안녕하세요 완태!
저는 우테코 5기 우르라고 해요!
이번 사다리 리뷰 잘 부탁드립니다 :)

2023-02-16 17:37 UTC, wannte requested changes
안녕하세요, 우르! 이번 리뷰를 맡은 완태입니다.

커밋 로그를  하나씩 넘겨보면서 리뷰를 진행했는데요. 코드 하나 하나가 정말 깔끔하다는 인상을 받았습니다.

몇 가지 리뷰 남겼으니 확인하시고 재요청주세요. 모든 걸 꼭 반영할 필요는 없습니다.

2023-02-16 17:37 UTC, wannte commented on src/test/java/domain/LineTest.java
> +    }
테스트도 리팩터링해서 유지 보수하기 쉽도록 관리할 수 있을 것 같아요!

2023-02-16 17:37 UTC, wannte commented on src/test/java/domain/LadderTest.java
> +
Exception 이 발생 여부도 좋지만, 의도한 대로 객체가 잘 생성되었는지 검증할 수도 있을 것 같아요

2023-02-16 17:37 UTC, wannte commented on src/main/java/domain/Ladder.java
> +    private void validateHeightOf(List<Line> lines) {
메소드 명 좋네요 👍

2023-02-16 17:37 UTC, wannte commented on src/main/java/domain/Line.java
> +        this.bridges = copyOf(bridges);
👍

2023-02-16 17:37 UTC, wannte commented on src/main/java/view/InputView.java
> +    }
Wow.. 💯

2023-02-16 17:37 UTC, wannte commented on src/test/java/generator/LineGeneratorTest.java
> +        LineGenerator lineGenerator = new LineGenerator(() -> EXIST);
함수형의 활용이 좋네요 👍

2023-02-16 17:37 UTC, wannte commented on src/main/java/engine/LadderEngine.java
> +        LineGenerator lineGenerator = new LineGenerator(new RandomBridgeGenerator());
상태를 가지고 있지 않는 Generator 같은 경우에는 한 번만 생성하고 재활용하는 것은 어떨까요?

2023-02-16 17:37 UTC, wannte commented on src/main/java/view/InputView.java
> +    }
참가자 수, 이름 중복 X 요구 사항은, inputView 의 역할로 볼 수도 있지만, 게임 자체의 로직으로도 볼 수 있을 것 같은데요!

일급 컬렉션 등을 활용하여 도메인 로직에서 이를 검증하는 것은 어떨까요?

2023-02-16 17:37 UTC, wannte commented on src/main/java/domain/Bridge.java
> +    }
어떻게 보여줄지는, OutputView의 책임으로 넘겨주는 것은 어떨까요?

2023-02-16 17:37 UTC, wannte commented on src/main/java/generator/LineGenerator.java
> +    }
(weak opinion) bridge 들을 관리하는 객체를 둬보는 것은 어떨까요?

2023-02-17 08:17 UTC, java-saeng commented on src/main/java/engine/LadderEngine.java
> +        LineGenerator lineGenerator = new LineGenerator(new RandomBridgeGenerator());
makeLines가 한번만 호출되서 굳이 그렇게 사용하지 않아도 된다고 생각했었는데,
다시 생각해보니 exception이 발생해서 재입력 할 때마다 Generator가 생성되기 때문에 한 번만 생성하고 재활용하는게 좋을 것 같습니다~~

2023-02-17 08:17 UTC, java-saeng commented on src/main/java/domain/Ladder.java
> +    private void validateHeightOf(List<Line> lines) {
이 부분은 페어의 의견으로 작성된 메서드 네임입니다. 페어는 메서드명과 파라미터가 이어지는 것이 좋다고 하더라구요. 그래서 뒤에 전치사가 자주 있어요.

이 부분은 정말 개인적인거라 페어의 의견을 따랐었는데, 저는 이러한 메서드 네이밍을 처음봅니다. 대부분 프레임워크나 라이브러리에서만 봤었습니다.(ex String.valueof() )

저는 메서드 이름을 충분히 서술적으로 validateHeight로도 나타낼 수 있다고 생각하는데, 당연히 이 부분은 개인차이겠지요?

2023-02-17 08:17 UTC, java-saeng commented on src/main/java/view/InputView.java
> +    }
완태 말씀대로 참가자 수와 이름 중복 에 대한 요구 사항은 "게임" 자체의 로직으로도 볼 수 있습니다. 

저 또한 "게임" 자체의 로직으로도 보았습니다.

요구사항에는 재시작이 존재하진 않지만, 게임을 사용하는 입장에서 보면 이름을 모두 입력하고, 잘못 입력할 시에 바로 "재입력"이 되야한다고 생각하여 참가자 수, 이름 중복과 관련된 것은 InputView에서 처리를 했습니다.

즉, 각 참여자에 대한 이름 길이 제한은 정말 이름에 대한 도메인 규칙이라 생각이 들었고,
참가자 수, 이름 중복과 같은 경우는 Input에서 처리하는게 낫지 않을까? 라는 생각을 했어요.


근데 완태의 말씀을 듣고 다시 생각한 점이

"각 사람마다(ex 이름)  validation"은 Person 이라는 원시 값 포장 객체에서 처리를 하고,
"모든 사람들(참가자 수 제한, 이름 중복) validation"은 People 이라는 일급 컬렉션에서 처리를 하는게 좋지 않을까? 라는 생각이 드네요.,

2023-02-17 08:17 UTC, java-saeng commented on src/main/java/domain/Bridge.java
> +    }
제가 봐도 이 부분은 OutputView 에서 상수로 관리하면 더욱 좋을 것 같아요. 굳이 불필요한 객체를 생성하는걸까? 라는 생각이 들었습니다..!!

하지만 요구사항에 ENUM을 사용하라고 했어서, 요구사항을 만족시키기 위해서 사용했습니다. ENUM을 어디에 사용할지 페어와 생각해보고 나서 적용해보았습니다 !!

2023-02-17 08:17 UTC, java-saeng commented on src/main/java/generator/LineGenerator.java
> +    }
bridges 를 관리하는 Line 객체가 존재하는데

혹시 lines 을 관리하는 객체를 말씀하시는걸까요!?

만약 맞다면, 현재 상황에서는 lines에 대한 validation 만 존재하기 때문에 굳이 일급 컬렉션을 사용할 필요가 없다고 생각했습니다.

만약에 lines에 대한 상태와 행위를 처리해야할 일이 생긴다면 그 때 가서 다시 일급 컬렉션을 생성하여 lines를 관리하면 어떨까요??

2023-02-17 08:17 UTC, java-saeng commented on src/test/java/domain/LineTest.java
> +    }
제가 완태 말씀을 완벽히 이해한지는 잘 모르겠지만, 
exception throw 한 경우와 exception이 터지지 않는 경우를 나눠서 method extract 하였습니다,,!!

2023-02-17 08:17 UTC, java-saeng commented on src/test/java/domain/LadderTest.java
> +
그렇네요,, 좀 더 명확한 테스트가 가능하다면 제대로 생성됐는지 확인할 수 있는게 좋은 것 같아요 !!

2023-02-17 08:17 UTC, java-saeng commented on src/test/java/domain/LineTest.java
> +    }
뭔가 더 이쁘게 리팩터링 할 수 있을 것 같은데,, 혹시 저와 다른 생각을 하고 계셨다면 완태의 방식을 키워드로 얻을 수 있을까요?

2023-02-18 06:54 UTC, wannte commented on src/main/java/domain/Ladder.java
> +    private void validateHeightOf(List<Line> lines) {
```
validateHeightOf(lines);
```

이렇게 보면 읽기 편해서 남겼던 코멘트 같아요! (한 호흡에 읽혔던 것 같습니다.)

모두 좋은 네이밍이라 생각합니다.

2023-02-18 06:54 UTC, wannte commented on src/main/java/domain/Bridge.java
> +    }
Enum은 두고 display 로직만 분리해보는 것은 어떨까요?

현재는 콘솔에서 진행하는 게임이지만, 이후에 웹, 앱 등 다양한 곳에서 실행할 수 있는 요구 사항이 추가된다면 어떤 방식으로 진행할 수 있을 지 고민해보면 좋을 것 같아요!

2023-02-18 06:54 UTC, wannte commented on src/main/java/domain/Ladder.java
> +        this.people = people;
lines는 copyOf 를 사용, people은 직접 reference를 참조하도록 정의했는데, 어떤 차이로 진행했는지 궁금합니다.

2023-02-18 06:54 UTC, wannte commented on src/main/java/view/InputView.java
> +    }
> 즉, 각 참여자에 대한 이름 길이 제한은 정말 이름에 대한 도메인 규칙이라 생각이 들었고,
참가자 수, 이름 중복과 같은 경우는 Input에서 처리하는게 낫지 않을까? 라는 생각을 했어요.

만약 지켜지지 않는다면 게임 자체에 영향을 주는 요소는 도메인에서 처리하면 좋지 않을까 생각해요!
inputView를 새로 만들어야 하는 상황이 생겼고, 해당 validation을 누락한다면 장애가 날 수 있을 것 같아요.
도메인에서 진행하고 테스트 코드로 이를 방어하면 좋지 않을까 생각해요!
(view와 domain 에서 둘 다 검증을 할 수도 있다고 생각하는 편입니다. 위 로직은 domain validation은 필수적으로 진행해야 한다고 생각합니다.)

2023-02-18 06:54 UTC, wannte commented on src/main/java/domain/Bridge.java
> +    }
Enum은 두고 display 로직만 분리해보는 것은 어떨까요?

현재는 콘솔에서 진행하는 게임이지만, 이후에 웹, 앱 등 다양한 곳에서 실행할 수 있는 요구 사항이 추가된다면 어떤 방식으로 진행할 수 있을 지 고민해보면 좋을 것 같아요!

2023-02-18 07:04 UTC, wannte commented on src/main/java/engine/LadderEngine.java
> +            Line line = lineGenerator.generate(people.getParticipants().size());
```suggestion
            Line line = lineGenerator.generate(people.size());
```

people.size() 를 별도로 정의할 수도 있을 것 같아요

2023-02-18 07:04 UTC, wannte commented on src/test/java/domain/LineTest.java
> +    }
`@ParameterizdTest` `@MethodSource` 로 list를 받아서 테스트 해볼 수 있지 않을 까 생각했어요!

그런데 지금 와서 다시 보니 지금의 테스트 코드가 요구사항을 보여준다는 장점이 있는 것 같습니다!

method extract 는 취향 차이 같습니다!

2023-02-18 07:06 UTC, wannte approved these changes
안녕하세요 우르!

리뷰 반영한 부분 확인했습니다. 추가적으로 몇 가지 코멘트 남겼습니다. 확인 부탁드려요!

다음 단계 진행해주시면 되겠습니다. 👍

2023-02-18 07:06 UTC, merged