[사다리 게임] 희봉 미션 제출합니다.
woowacourse/java-ladder pull request #7
Opened 2019-05-17 03:31 UTC by heebong

사다리 게임 미션 제출합니다.

2019-05-18 09:15 UTC, phs1116 requested changes
안녕하세요. 리뷰를 맡게된 리뷰어 화투라고 합니다 :)
사다리게임 구현하시느라 정말 수고 많으셨습니다.
다만 너무 객체 고유의 로직이 전역객체로 분리되어있어 응집도가 낮은점, 테스트,
메서드 명명 등 몇가지 피드백 추가했는데요.
참고 부탁드리고 궁금하신 점 있으시면 연락주세요. :)

2019-05-18 09:15 UTC, phs1116 commented on src/main/java/ladder/domain/Ladder.java
> +    List<LadderLine> ladder;
캡슐화가 안되어있네요 :)
패키지 내에 공개해야할 이유가 없다면 접근제어자를 가장 낮게(private)으로 해주세요!

2019-05-18 09:15 UTC, phs1116 commented on src/main/java/ladder/domain/Rule.java
> +public class Rule {
Rule이라는 객체의 책임이 명확하지 않습니다.
여기서 가지고가고 있는 정책들은 각자의 객체가 책임을 가져가는게 좋을 것 같아요.
모든 객체들이 Rule이라는 객체와 결합도는 높은데, 각자의 객체에 대한 검증 및 변환 로직이 Rule에 있어서 응집도가 너무 낮아요.

각자의 로직들이 자신의 책임에 맞도록 응집도를 높이기 위해 ruleInputPlayerNames는 Player 객체가 ruleLadderDepthRange는 사다리가 가지는 등 Rule이라는 클래스를 없애고 스스로 책임을 가지도록 노력해보세요 :)

2019-05-18 09:15 UTC, phs1116 commented on src/main/java/ladder/domain/LadderResult.java
> +    Ladder ladder;
접근제어자에 유의해주세요!

2019-05-18 09:15 UTC, phs1116 commented on src/main/java/ladder/util/Const.java
> +public class Const {
Const 클래스에 있는 값들도 각자 책임에 맞는 객체가 가질 수 있게 수정하시는게 좋을 것 같습니다.

2019-05-18 09:15 UTC, phs1116 commented on src/main/java/ladder/util/Util.java
> +public class Util {
Util이라는 이름 자체가 너무 추상적인 것 같아요.
두 메서드간의 연관성도 없구요. 각자의 책임에 맞도록 클래스를 분리하시는게 좋을 것 같습니다.

2019-05-18 09:15 UTC, phs1116 commented on src/main/java/ladder/domain/LadderResult.java
> +    Map<String, String> result;
Map<String, String> result으로 되어있다보니 어떤식의 매핑인지에 대해서 이해하기가 어렵습니다.
Map<Player, Reward> 같은 형식으로 String을 래핑하여 좀 더 의미있게 표현 해보면 어떨까요?

2019-05-18 09:15 UTC, phs1116 commented on src/main/java/ladder/LadderApp.java
> +        String names = inputPlayerNames(InputView.inputPlayerNames());
LadderApp에서 뷰에 대한 책임을 너무 많이 가져가고 있는 것 같아요.
inputPlayerNames, InputRewards등에 있는 예외처리를 포함한 것들은 전부 다 input이 책임지면 되지 않을까요?

2019-05-18 09:15 UTC, phs1116 commented on src/main/java/ladder/domain/LadderLine.java
> +    private List<Boolean> setLineStates() {
자바 컨벤션에서 set이라는 메서드는 객체의 값에 설정하는 의미로 많이 사용되고 있어요.
Line을 만드는 코드인데 set이 아니라 명확한 이름으로 표현해보면 어떨까요?

2019-05-18 09:15 UTC, phs1116 commented on src/main/java/ladder/domain/LadderLine.java
> +    static boolean setNextState(boolean state) {
자바 컨벤션에서 set은 보통 void로 선언합니다. set의 역할 또한 위에 말씀드린것과 같구요!
조금 더 명확하게 이름을 표현하셔도 좋을 것 같아요!

2019-05-18 09:15 UTC, phs1116 commented on src/main/java/ladder/domain/LadderLine.java
> +    private String getStateShape(boolean lineState) {
getter는객체 내부의 값을 반환하는 역할을 합니다. 
객체의 상태에 따라 다른 형태(그림)을 반환하는거니 draw나 generate등 다르게 표현하시는게 더 좋을 것 같아요 :)

2019-05-18 09:15 UTC, phs1116 commented on src/main/java/ladder/domain/LadderLine.java
> +    public String toString() {
`이펙티브 자바 규칙 10 - toString은 항상 재정의하자(https://meaownworld.tistory.com/84)`
toString은 객체를 그리는 것이 아닌 객체의 상태를 전달하는 역할을 합니다.
그림을 그리기 위해서라면 다른 메서드를 정의하시는게 좋을 것 같아요.

2019-05-18 09:15 UTC, phs1116 commented on src/main/java/ladder/domain/LadderResult.java
> +    private Map<String, String> setResult(List<Player> players, List<String> rewards, int depth) {
밑의 setPlayers 등을 포함하여 setter의 역할이 아닌 것 같습니다. :) 메서드 작명에 주의해주세요.

2019-05-18 09:15 UTC, phs1116 commented on src/main/java/ladder/domain/LadderResult.java
> +    private String getResultOfAllName() {
getResultOfAllName는 작명으론 객체의 리스트를 돌려줄 것으로 보여요!
도메인은 값만을 가지고, 그리는 부분은 뷰가 가지고 있는게 맞는 것 같습니다. :)

2019-05-18 09:15 UTC, phs1116 commented on src/main/java/calculator/CalculatorConst.java
> +    public static final String FORMAT_SYMBOL = "//(.*)\\\\n(.*)";
사다리 게임의 Const처럼 각자의 객체가 책임지는게 좋을 것 같아요!

2019-05-18 09:15 UTC, phs1116 commented on src/main/java/calculator/Calculator.java
> +    public static List<Integer> getNumbers(String input) {
getter는 일반적으로 객체의 내부 값을 돌려줄 때 사용하는 이름입니다.
input을 List<Integer>로 변경한다는 의미가 담겨있지 않아요.
convert같은 이름 등 객체의 역할에 맞는 이름을 짓도록 해보시면 좋을 것 같습니다. :)

2019-05-18 09:15 UTC, phs1116 commented on src/test/java/ladder/domain/LadderResultTest.java
> +        LadderResult ladderResult = new LadderResult("pobi, crong, name", "꽝, 1000, 2000", 5);
테스트들이 전체적으로 '검증'에 대한 부분이 없는 것 같습니다.
단순 화면에 결과를 출력하는 걸로는 테스트가 자동화가 되지 않지요 :) 
원하는 결과대로 값이 반환되는지 검증부분을 추가해주세요!

2019-05-18 09:15 UTC, phs1116 commented on src/main/java/ladder/domain/LadderLine.java
> +        return Util.getRandomState();
random을 반환하는 객체에 너무 강하게 의존하도록 되어있어서 테스트하기 어려울 것 같아요!
첫주차 자동차 게임에서 했던 것 처럼 랜덤으로 반환하는 부분을 느슨하게 의존하도록 해보세요!  :)

2019-05-19 10:06 UTC, heebong commented on src/main/java/ladder/domain/Ladder.java
> +    List<LadderLine> ladder;
변경했습니다. 확인 부탁드립니다!

2019-05-19 10:07 UTC, heebong commented on src/main/java/ladder/domain/Rule.java
> +public class Rule {
Rule 클래스 삭제 후 각 클래스로 이동했습니다. 확인 부탁드립니다!

2019-05-19 10:07 UTC, heebong commented on src/main/java/ladder/domain/LadderResult.java
> +    Ladder ladder;
변경했습니다. 확인 부탁드립니다!

2019-05-19 10:08 UTC, heebong commented on src/main/java/ladder/util/Const.java
> +public class Const {
Const 클래스 삭제 후 각 클래스들로 이동했습니다. 확인 부탁드립니다!

2019-05-19 10:08 UTC, heebong commented on src/main/java/ladder/util/Util.java
> +public class Util {
Util 클래스 삭제했습니다. 확인 부탁드립니다!

2019-05-19 10:08 UTC, heebong commented on src/main/java/ladder/domain/LadderResult.java
> +    Map<String, String> result;
변경했습니다. 확인 부탁드립니다!

2019-05-19 10:09 UTC, heebong commented on src/main/java/ladder/LadderApp.java
> +        String names = inputPlayerNames(InputView.inputPlayerNames());
변경했습니다. 확인 부탁드립니다!

2019-05-19 10:09 UTC, heebong commented on src/main/java/ladder/domain/LadderLine.java
> +    private List<Boolean> setLineStates() {
변경했습니다. 확인 부탁드립니다!

2019-05-19 10:09 UTC, heebong commented on src/main/java/ladder/domain/LadderLine.java
> +    static boolean setNextState(boolean state) {
변경했습니다. 확인 부탁드립니다!

2019-05-19 10:09 UTC, heebong commented on src/main/java/ladder/domain/LadderLine.java
> +    private String getStateShape(boolean lineState) {
변경했습니다. 확인 부탁드립니다!

2019-05-19 10:10 UTC, heebong commented on src/main/java/ladder/domain/LadderLine.java
> +    public String toString() {
이름만을 가지는 Player, Item을 제외하고 toString은 삭제했습니다. 확인 부탁드립니다!

2019-05-19 10:10 UTC, heebong commented on src/main/java/ladder/domain/LadderResult.java
> +    private Map<String, String> setResult(List<Player> players, List<String> rewards, int depth) {
변경했습니다. 확인 부탁드립니다!

2019-05-19 10:16 UTC, heebong commented on src/main/java/calculator/CalculatorConst.java
> +    public static final String FORMAT_SYMBOL = "//(.*)\\\\n(.*)";
변경했습니다. 확인 부탁드립니다!

2019-05-19 10:16 UTC, heebong commented on src/main/java/calculator/Calculator.java
> +    public static List<Integer> getNumbers(String input) {
변경했습니다. 확인 부탁드립니다!

2019-05-19 10:17 UTC, heebong commented on src/test/java/ladder/domain/LadderResultTest.java
> +        LadderResult ladderResult = new LadderResult("pobi, crong, name", "꽝, 1000, 2000", 5);
변경했습니다. 확인 부탁드립니다

2019-05-19 10:18 UTC, heebong commented on src/main/java/ladder/domain/LadderLine.java
> +        return Util.getRandomState();
변경했습니다. 확인 부탁드립니다!

2019-05-21 06:54 UTC, phs1116 requested changes
안녕하세요. 리뷰어 화투입니다.
리뷰 늦게 드려서 죄송합니다.
추상화 엄청 잘 하신 것 같아요 👍 
피드백 몇가지 추가했는데 확인 부탁드릴게요. :)

2019-05-21 06:54 UTC, phs1116 commented on src/main/java/ladder/domain/Item.java
> +    public static Item newBuilder(String item) {
전체적으로 newBuilder라는 메서드 네임을 사용하셨는데, newBuilder의 이름의 의미가 '빌더 객체'를 생성하는 것으로 보여요
newInstance같은 이름이 더 적합할 것 같습니다.
혹은 굳이 static factory method를 쓸 이유가 없다면 생성자를 사용해도 될 것 같아요. :)

2019-05-21 06:54 UTC, phs1116 commented on src/main/java/ladder/domain/Line.java
> +    public static Line newBuilder() {
static factory method의 장점중 하나는 생성자랑 다르게 '이름을 정할 수 있다'입니다.
각각의 메서드가 어떤 의미로 생성을 하고있는지 표현해주시면 더욱 가독성있는 코드가 될 것 같아요. :)

2019-05-21 06:54 UTC, phs1116 commented on src/main/java/ladder/domain/Position.java
> +    private void makeThrow(boolean state, String message) {
Preconditions.checkArgument같은 의미로 사용하신 것 같아요.
Preconditions처럼 아파치 커먼스에 있는 기능을 쓰거나 별도 클래스로 빼도 될 것 같습니다. :)

2019-05-21 06:54 UTC, phs1116 commented on src/main/java/ladder/domain/Position.java
> +    private static boolean findRandCurrent() {
랜덤이라는 것에 너무 강하게 의존하고 있는 것 같아요. :)
랜덤이 아닌 다른 방식으로 Position을 생성 할 경우, 코드 자체를 변경 해야 될 것 같아요.
현재 여기에 선을 그을지 말지를 결정하는 객체에 대해서 별도 인터페이스를 정의하고 이를 사용함으로써 
생성 규칙과 의존을 느슨하게 가져가도록 해보면 어떨까요?

2019-05-21 06:54 UTC, phs1116 commented on src/main/java/ladder/domain/Position.java
> +        if (current) {
로직을 보니 current가 '오른쪽 방향으로 선이 있다'로 보이네요. :)
hasLeft, hasRigth로 표현하는게 더 직관적이지 않을까요?
더 나아간다면 항상 둘중 하나만 가지니까 enum Direction을 만들 수도 있을 것 같아요. :)
그리고 if문을 없애고 해당 enum에 책임을 넘겨보면 어떨까요?

2019-05-21 06:54 UTC, phs1116 commented on src/main/java/ladder/domain/Position.java
> +    public static Position add(boolean hasLeft, boolean current) {
밑에 말한대로 랜덤에 대해서 의존을 느슨하게 가져가면 테스트용 메서드가 여러개 생기지 않을 것 같네요!
현재 같은 기능을 가진 메서드나 생성자가 테스트용으로 한벌씩 있는 것 같아서요. ;)

2019-05-21 07:31 UTC, heebong commented on src/main/java/ladder/domain/Item.java
> +    public static Item newBuilder(String item) {
static factory method를 사용해보질 않아서 연습해본다는 생각으로 사용했었습니다. 다음 과제부터 static factory method를 쓸 이유가 없다면 일반 생성자로 하겠습니다!(이름은 newInstance로 바꿨습니다!)

2019-05-21 07:32 UTC, heebong commented on src/main/java/ladder/domain/Position.java
> +    private void makeThrow(boolean state, String message) {
별도의 클래스로 생성했습니다. 확인 부탁드립니다!

2019-05-21 07:42 UTC, heebong commented on src/main/java/ladder/domain/Line.java
> +    public static Line newBuilder() {
Line이면 이름을 makeLine으로 하면 좋을지.. 어떤게 더 좋을지 문의드립니다ㅠㅠ 일단 newInstance로 바꿨습니다.

2019-05-23 12:45 UTC, heebong commented on src/main/java/ladder/domain/Position.java
> +        if (current) {
Point 객체를 true와 false만 가지는 enum으로 변경했습니다. (move 함수는 여전히 가진채로..) 확인 부탁드립니다! (Position 클래스의 이름을 Point로 변경했습니다.)

2019-05-23 12:49 UTC, heebong commented on src/main/java/ladder/domain/Position.java
> +    public static Position add(boolean hasLeft, boolean current) {
이전 Point를 입력하면 임의로 다음 Point를 반환하는 기능을 가진 함수를 별도로 생성해 Line 클래스에선 그걸 사용해 다음 Point를 사용하도록 변경했습니다.  확인 부탁드립니다!

2019-05-23 15:38 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다.
피드백 반영 감사합니다. 많이 고민하신게 코드에서 보여요. 👍 
조금 더 개선 할 수 있을 것 같아서 피드백 몇가지 추가했어요.
참고 부탁드리구요. 궁금하신 점 있으시면 연락주세요. :)

2019-05-23 15:38 UTC, phs1116 commented on src/main/java/ladder/domain/Point.java
> +    TRUE(true),
Point가 TRUE, FALSE로 표현한것도 좋지만 조금 더 직관적으로 수정해보는것도 좋을 것 같아요. :)
Point가 방향을 가지도록 하면 어떨까요?
현재 표현에서 Point.TRUE,Point.FALSE로는 무슨 의미인지 명확하지가 않거든요.

Point객체가 다음에 이동할 방향을 RIGHT, LEFT, STOP같은 값을 가진다고 표현 할 수 있지 않을까요?
(Point.LEFT,Point.RIGHT 같은 경우는 객체의 이름과 맞지 않으니 좀 더 객체지향 적으로 고민해볼 수 있을 것 같아요!)

현재 점이 선이 그어져있는지 안그어져있는지로 객체의 상태를 가지니까 로직이 복잡해지는 것 같아요. :)
안그어져있다면 바로 직전 점까지 확인해야하니까요.

2019-05-23 15:38 UTC, phs1116 commented on src/main/java/ladder/domain/Point.java
> +        if (status) {
직전 점을 확인 안하고 현재 상태만으로 확인 할 수 있는 방법도 있지 않을까요? :)

2019-05-23 15:38 UTC, phs1116 commented on src/main/java/ladder/domain/Line.java
> +        return LineResult.newInstance(line.size()).move(this);
사다리를 이동하는 책임이 LineResult가 가지는게 맞을지 잘 모르겠어요. :)
LineResult의 책임은 뭘까요? 이름은 결과를 보여주는 책임으로 보이는데 사다리의 점들을 이동시키는 책임도 가질까요?

2019-05-23 15:38 UTC, phs1116 commented on src/main/java/ladder/domain/Line.java
> +            line.add(PointConfigure.generateRandom(line.get(i - 1)));
지금도 PointConfigure에 너무 강결합이 되어있어요!
새로운 객체를 생성할때 현재 코드에 작성되어있는 PointConfigure만 의존하게 되어 확장에 열려있지 않거든요 :)
현재 점에서 오른쪽으로 선을 이을지 말지를 결정하는 인터페이스를 만들어서, 이 구현체를 주입받아 사용하도록 해보면 어떨까요?
랜덤으로 구현한 객체면 랜덤으로 실행될 거고, 내가 원하는 값을 돌려주는 객체를 넘겨주면 테스트도 용이할 수도 있지 않을까요?

2019-05-24 00:45 UTC, heebong commented on src/main/java/ladder/domain/Line.java
> +        return LineResult.newInstance(line.size()).move(this);
Line class의 move 함수는 테스트 용도로 만들어져 실제 로직에서는 LineResult class의 move 함수만 사용하고 있습니다. (Line class의 move 함수는 LineTest class에서만 사용 되고있습니다.) Line의 move를 삭제하고 LineReuslt의 move 함수의 테스트 코드를 작성하였습니다. 확인 부탁드립니다!

2019-05-24 08:26 UTC, heebong commented on src/main/java/ladder/domain/Point.java
> +    TRUE(true),
Point 객체가 RIGHT, LEFT, STRAIGHT와 같이 현재 점의 방향을 나타내도록 변경했습니다. 확인 부탁드립니다!

2019-05-24 08:27 UTC, heebong commented on src/main/java/ladder/domain/Point.java
> +        if (status) {
Point 객체가 RIGHT, LEFT, STRAIGHT를 나타내게 되어 이전값 없이 이동을 하게 변경했습니다. 확인 부탁드립니다!

2019-05-24 09:40 UTC, heebong commented on src/main/java/ladder/domain/Line.java
> +            line.add(PointConfigure.generateRandom(line.get(i - 1)));
PointConfigure -> PointGenerate로 이름을 변경했고, PointGenerate를 인터페이스로 만들어 사용하는것으로 변경했습니다. Line class에서 클래스 필드에 PointGenerate가 있어 Point를 설정하는 부분을 변경하고자 하면 거기서 이름만 변경하면 됩니다.  확인 부탁드립니다!

2019-05-24 14:44 UTC, phs1116 approved these changes
안녕하세요! 리뷰어 화투입니다.
피드백 잘 반영해주셔서 감사합니다. :)
이번 단계 머지할게요!
객체지향 원칙에 대해서 피드백 한가지 추가했는데 한번 참고 부탁드릴게요. :)
개발하시느라 정말 수고 많으셨습니다.

2019-05-24 14:44 UTC, phs1116 commented on src/main/java/ladder/domain/Line.java
> +    private static final PointGenerate pointGenerate = PointGenerateFactory.getInstance().create(PointGenerateStatus.RANDOM);
직접 이렇게 사용하면 개방 폐쇠원칙(OCP)과 의존성 역전원칙(DIP)에 어긋나요. :)
SOLID원칙중 두개 보면서 수정해보세요!

2019-05-24 14:44 UTC, phs1116 commented on src/main/java/ladder/domain/Point.java
> +    LEFT(index -> index - 1 ),
👍

2019-05-24 14:44 UTC, merged