[1단계 - 사다리 생성] 에밀(김대희) 미션 제출 합니다.
woowacourse/java-ladder pull request #86
Opened 2023-02-16 06:36 UTC by CFalws

안녕하세요 파즈
미리 리뷰 감사합니다!

한 가지 궁금한 점이 있는데요

모든 원시값을 포장하라는 이번 요구사항에 의해 높이와 너비 모두 포장을 했습니다
하지만 실질적으로 이 값은 validation이 필요하기는 하지만 getter로 바로 값을 꺼내서 사다리를 만드는 데 사용했습니다.
즉, 상태를 가질 필요가 없다고 생각이 들었고 util성 클래스라고 생각이 들었습니다.

일단은 포장을 하긴 했는데 이렇게까지 해서 포장하는 것이 옳은 것일까요?

2023-02-17 07:48 UTC, Be-poz requested changes
안녕하세요 에밀 리뷰어 파즈입니다. 1단계 수고하셨습니다. 전체적으로 다 깔끔하게 짜셔서 코드 보는 재미가 있었습니다. 코멘트 몇 개 달아봤습니다. 제가 단 코멘트는 그렇게 변경이 반드시 되어야한다가 아니고 의견일 뿐이기 때문에 에밀이 읽고 생각해보시고 기존의 코드가 맞다 또는 다른 변경을 하겠다면 그렇게 하시면 됩니다. 본인만의 생각이 가장 중요하니까요.  

1. 이렇게까지 포장을 하는 것이 옳나요?
-> 일단 현재 미션의 요구사항이기 때문에 어찌됐든 포장은 해야합니다. 에밀이 생각하기에 이걸 포장할 정도는 아닌 것 같은데 포장을 해야하나?? 라고 생각이 드셨다면 이후 프로젝트를 진행할 때에 포장을 안하면 될 것 같습니다. 저는 Width, Height로 포장하면서 검증에 대한 로직과 매직넘버, 에러메세지 등을 하나의 큰 객체에 다 두는 것이 아닌 포장된 객체에 두면서 얻는 이점 또한 있다고는 생각합니다. 하지만 개인적으로는 조금 더 많은 비즈니스 로직이 있을 때에 포장을 할 것 같긴합니다 ㅎㅎ. 그리고 저는 Util 클래스라고는 또 생각하지는 않습니다. 어떻게보면 사다리를 구성하는 높이와 너비이기 때문에 Ladder라는 객체를 따로 만들어서 내부적으로 관리를 하면 했지 Util 의 측면으로 만들어서 단순히 메서드 호출만 하는 식으로 만들 것 같지는 않네요! 이건 단순히 개인의 의견일 뿐이니깐 요렇게도 생각하는 사람이 있구나~ 정도로만 받아들이시면 될 것 같습니다.  

피드백 반영 후 재 리뷰요청 기다리고 있겠습니다. 😎

2023-02-17 07:48 UTC, Be-poz commented on src/main/java/ladder/controller/LadderController.java
> +    }
해당 메서드의 위치가 ``printLadderResult`` 위에 위치하면 코드 가독성이 더 좋아질 것 같습니다.  
``run`` 메서드에서 printLadderResult``와 ``makeLadder``보다 ``enroll``이 먼저 호출되었기 때문에 그 순으로 위에서부터 위치하면 좋습니다. ``makeLadder`` 또한 마찬가지입니다.

2023-02-17 07:48 UTC, Be-poz commented on src/main/java/ladder/domain/Players.java
> +                .collect(collectingAndThen(toUnmodifiableList(), Players::new));
👍

2023-02-17 07:48 UTC, Be-poz commented on src/main/java/ladder/domain/Width.java
> +    private static final String WIDTH_ERROR_MESSAGE = "너비가 2이상이어야 한다.";
해당 요구사항은 따로 그냥 추가하신 걸까요 ?

2023-02-17 07:48 UTC, Be-poz commented on src/main/java/ladder/domain/RandomRowsGenerator.java
> +    }
해당 메서드가 가장 위에 위치하면 좋을 것 같습니다. 호출하는 메서드가 호출되는 메서드의 위에 위치하고, 보통 public이 private 위에 위치합니다.  아래 링크 참고하시면 좋을 것 같습니다.
https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html

2023-02-17 07:48 UTC, Be-poz commented on src/main/java/ladder/domain/RandomRowsGenerator.java
> +    private Row generateValidRow(int size) {
``size`` 보다는 width 라던가 더 구체적이면 좋을 것 같습니다. 어떤 size를 의미하는 것인지 모호한 것 같습니다.

2023-02-17 07:48 UTC, Be-poz commented on src/main/java/ladder/domain/Foothold.java
> +    Y(true, "-----"), N(false, "     ");
개행 해주시는게 좋을 것 같습니다!

2023-02-17 07:48 UTC, Be-poz commented on src/main/java/ladder/domain/Foothold.java
> +                .get();
``findAny()``가 Optional을 return 하는데 Optional.empty일 때에 대한 처리를 해주시는게 좋을 것 같습니다.  
논리적으로 Optional.empty 가 나오지 않을 것이라고 확신할 수 있어도 잡아주는 것이 확실할 것 같습니다.

2023-02-17 07:48 UTC, Be-poz commented on src/main/java/ladder/domain/Row.java
> +    }
``RandomGenerator``의 ``generateRow`` 메서드에서도 그렇고 ``List<Foothold>`` 타입의 변수명을 row라고 하는 것이 맞나 고민이 됩니다. row를 가지고 Row를 만든다는게 조금 말이 안맞는 것 같아서요.  
변수로 ``private final List<Foothold> row`` 도 그렇구요. 발판들의 집합이 Row라는 것이 차라리 맞지 않나 싶습니다. 어떻게 생각하시나요?

2023-02-17 07:48 UTC, Be-poz commented on src/main/java/ladder/domain/Row.java
> +        }
2 depth 네요! 연속스텝인지 검증 한다는 void 메서드로 한 번에 묶어주시면 될 것 같습니다.

2023-02-17 07:48 UTC, Be-poz commented on src/main/java/ladder/view/ResultView.java
> +    }
stream 의 메서드를 체이닝해서 사용할 때에는 ``.`` 의 위치가 동일해야 가독성이 좋습니다.  
```java
        state.stream()
             .map(this::generateRow)
             .forEach(System.out::println);
```
맥 사용 중이시라면 cmd + shift + L 누르면 코드 리포맷이 되니깐 사용하시면 편하실 것 같습니다. 
또는 개행을 위해 엔터를 치실 때에 cmd + shift + enter 로 개행하시면 바로바로 리포맷팅이 됩니다.
또는 intellij를 이용해서 git commit을 하신다면 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/45073750/219578892-b084abfb-2667-48af-9975-5c8f6c286fc6.png">

우측에 reformat code와 optimize imports 체크해두시면 더 편하게 이용하실 수 있습니다.

2023-02-17 07:48 UTC, Be-poz commented on src/main/java/ladder/domain/RandomRowsGenerator.java
> +    }
로직 개선이 조금 필요할 것 같습니다. 이론 상 무한반복이 가능하겠네요. width 2로 두고 돌려봤는데 Y,Y가 나와서 하나의 Row를 만드는데에도 4번 정도 연속으로 플로우를 타는 것을 경험했습니다.  
개인적인 생각이지만 첫 발판은 바로 ``random.nextBoolean`` 으로 채워두고 2번째 발판부터는 그 이전 발판이 Y이면 로직타지않고 스킵, N 일 때에만 다시 랜덤생성 이런식이면 좀 더 나을 수 있을 것 같네요.

2023-02-17 07:48 UTC, Be-poz commented on src/main/java/ladder/domain/Player.java
> +    private final String name;
이름에 대해서도 객체 따로 만들어서 포장하고, 동일한 이름 입력 시에 거부되게끔 한 번 변경해보시겠어요 ?

2023-02-18 05:24 UTC, CFalws commented on src/main/java/ladder/domain/Width.java
> +    private static final String WIDTH_ERROR_MESSAGE = "너비가 2이상이어야 한다.";
네 원래의 의도는 최소 2명은 참여할 수 있도록 하는 것이었는데 실제로는 사다리의 너비가 2 이상이도록 구현했네요.
1 이상이도록 변경해야할 것 같습니다.

2023-02-18 05:34 UTC, CFalws commented on src/main/java/ladder/domain/Row.java
> +    }
저도 List<Foothold>는 footholds 같은 이름이 더 어울린다고 생각하는데 현재 도메인에서는 List<Foothold>는 row를 구성한다는 (무의식적인)생각으로 이렇게 구현한 거 같습니다.

만약 정적 팩토리 메서드를 쓰지 않고 생성자를 쓰더라도 동일한 생각이실지 궁금합니다.
pubilc Row(List<Foothold> row)는 자연스럽다고 생각하실까요?

2023-02-19 14:03 UTC, CFalws commented on src/main/java/ladder/view/ResultView.java
> +    }
좋은 팁 감사합니다. 하고나니 가독성이 더 좋아졌어요!

2023-02-19 16:11 UTC, Be-poz commented on src/main/java/ladder/domain/Row.java
> +    }
후자여도 저는 footHolds 로 둘 것 같긴합니다!

2023-02-19 16:21 UTC, Be-poz approved these changes
피드백 반영한 것 잘 봤습니다 에밀! https://github.com/woowacourse/java-ladder/pull/86/commits/ddd0d19f6985876bb31fcc53779b8505d7fa58e2 이 커밋은 이름변경 부분은 따로 커밋이 빠져있으면 조금 더 좋았을 것 같긴합니다! 이것 외에는 모두 잘 변경해주신 것 같습니다!  
1단계는 이만 머지해도 괜찮을 것 같네요. 2단계 기다리고 있겠습니다. 화이팅!

2023-02-19 16:22 UTC, merged