[1단계 - 사다리 생성] 주노(최준호) 미션 제출합니다.
woowacourse/java-ladder pull request #90
Opened 2023-02-16 06:50 UTC by Choi-JJunho

토미 안녕하세요!
요구사항 중 Enum을 적용하라는 내용이 있었는데 Enum을 적용할 마땅한 부분을 찾지 못해 적용하지 못했습니다.ㅠㅠ
리뷰 잘부탁드립니다 🙇‍♂️

2023-02-16 12:13 UTC, seokhongkim requested changes
주노, 사다리 1단계 미션 잘 진행해주셨네요. 👍 
코드 보고 코멘트 조금 남겼습니다. 코멘트 확인 부탁드려요. :)

남긴 코멘트를 포함해서, 내일 아침에 같이 이야기 나누면 좋겠네요 ㅎㅎ

2023-02-16 12:13 UTC, seokhongkim commented on .gitmessage.txt
> +
이 템플릿은 주노의 페어 PC에서만 의미가 있을 것 같네요.
git 으로 버전 관리를 함께 해야 할 필요가 있을까요? 버전 관리가 필요하지 않다면, git 관리 대상에서 제외해보는 건 어떨까요?

2023-02-16 12:13 UTC, seokhongkim commented on src/main/java/ladder/controller/LadderGameController.java
> +        List<String> players = InputView.askPlayerNames();
`InputView`의 메서드를 static 으로 구현하신 이유가 있을까요?
static 메서드의 장점과 단점은 무엇이 있을까요?

2023-02-16 12:13 UTC, seokhongkim commented on src/main/java/ladder/controller/LadderGameController.java
> +        OutputView.showGameResult(game.getPlayerNames(), result);
`OutputView`에 대해서도 static 메서드를 사용하신 이유가 궁금하네요.

2023-02-16 12:13 UTC, seokhongkim commented on src/main/java/ladder/controller/LadderGameController.java
> +        List<Line> result = game.play(height);
`List<Line>`이 게임의 결과를 가지고 있나요? 사다리의 모양을 가지고 있는 걸까요? 🤔

2023-02-16 12:13 UTC, seokhongkim commented on src/main/java/ladder/domain/LadderGame.java
> +    public List<Line> play(int height) {
1. 게임을 진행하는데 사다리를 반환하는 것이 조금 어색하게 느껴지네요.
2. `Lines`를 만든 후 `List<Line>` 으로 타입을 변경해서 반환하는 이유가 있나요? 일급 컬렉션을 만든 후 코드에서 사용하지 않으신 이유가 궁금합니다. `Lines`의 역할은 무엇인가요?

2023-02-16 12:13 UTC, seokhongkim commented on src/main/java/ladder/domain/RandomGenerator.java
> +public interface RandomGenerator {
테스트를 위해 인터페이스를 만드신 것 같네요. 임의의 값을 테스트할 수 있도록 구현하신 것 좋습니다. 👍 

1. Generics 를 사용하신 이유, 인터페이스를 사용한 이유가 궁금합니다. Generics 는 왜 필요했는지, 상속을 이용하는 방법도 있을 것 같은데 인터페이스를 사용하면 어떤 장점이 있었는지 궁금하네요.
2. 이름이 `RandomGenerator`가 적절한가요? 이 인터페이스가 `난수를 생성`하는 것이 역할인지, `포인트`를 생성하는 것이 역할인지 궁금하네요. 구현체는 `임의의 포인트`를 생성하는 것으로 보이네요!

2023-02-16 12:13 UTC, seokhongkim commented on src/main/java/ladder/domain/RandomPointGenerator.java
> +    private static final Random random = new Random();
`Random`을 한 번만 만들어서 재사용하는 것 좋습니다. 👍

2023-02-16 12:13 UTC, seokhongkim commented on src/main/java/ladder/domain/RandomPointGenerator.java
> +    public Boolean generate(boolean before) {
이전 값이 true 인 경우 다음 값은 true 일 수 없다는 것은 난수 생성의 조건일까요? `Line` 또는 `Bars` 가 지켜야 하는 조건일까요?

2023-02-16 12:13 UTC, seokhongkim commented on src/main/java/ladder/domain/Name.java
> +    private static final int MAX_NAME_LENGTH = 5;
적절한 상수 사용, 밸리데이션 좋습니다. 👍

2023-02-16 12:13 UTC, seokhongkim commented on src/main/java/ladder/domain/Players.java
> +            throw new IllegalArgumentException("참가자는 1명이하일 수 없습니다.");
같은 내용을 전달한다면 부정문보다 긍정문이 이해하기 쉽습니다.
"참가자는 2명 이상이어야 합니다."와 같이 사용해보면 어떨까요? `2`라는 값은 상수를 사용하면 값을 변경할 때 예외 메시지도 함께 변경되겠네요!

2023-02-16 12:13 UTC, seokhongkim commented on src/main/java/ladder/domain/Name.java
> +            throw new IllegalArgumentException("참여자의 이름은 최대 " + MAX_NAME_LENGTH + "글자를 넘을 수 없습니다.");
예외 메시지에 입력으로 들어온 값이 무엇인지 포함해주면, 문제 상황이 발생했을 때 어떤 값으로 인해 예외가 발생했는지 찾기가 수월합니다.

2023-02-16 12:13 UTC, seokhongkim commented on src/main/java/ladder/view/OutputView.java
> +        List<Boolean> points = line.toUnmodifiableBars();
여기도 `Bars`를 사용하지 않고 `List<Boolean>`으로 변경하신 이유가 있을까요?

2023-02-16 12:13 UTC, seokhongkim commented on src/main/java/ladder/domain/Bars.java
> +            Boolean generate = randomGenerator.generate(flag);
`Boolean`을 사용하면 한 점이 다음 점과 연결되었는지 여부를 나타낼 수 있겠네요.
즉, 첫 번째 값이면 왼쪽 첫 번째 줄에서 두 번째 줄로 연결이 되었다는 것을 나타내겠군요. 그렇다면 두 번째 줄이 첫 번째 줄과 연결되었다는 사실을 알기 위해서는, 두 번째 줄에서 이동할 때 첫 번째 줄이 연결되었는지 여부를 확인해야겠네요.
이렇게 두 개의 값(첫 번째 줄, 두 번째 줄)을 확인하지 않고 두 번째 줄에 있을 때 두 번째 줄의 값만 보고 왼쪽/오른쪽/그대로 유지 여부를 알 수 있도록 구현할 방법이 있을까요?

2023-02-16 12:13 UTC, seokhongkim commented on src/test/java/ladder/domain/BarsTest.java
> +@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
테스트명이 깔끔하게 보이네요 👍

2023-02-16 12:13 UTC, seokhongkim commented on src/test/java/ladder/domain/BarsTest.java
> +        assertThat(bars.toUnmodifiableBars()).containsExactly(true, false, true, false, true);
```suggestion
        assertThat(bars.toUnmodifiableBars()).isEqualTo(expected);
```

똑같은 값으로 보이는데 리스트를 재사용하지 않으신 이유가 있을까요?

2023-02-16 12:13 UTC, seokhongkim commented on src/test/java/ladder/domain/BarsTest.java
> +    private class MockedPointGenerator implements RandomGenerator {
난수 생성하는 로직을 제어해서 테스트 작성하신 것 좋습니다. 👍

2023-02-16 22:41 UTC, Choi-JJunho commented on .gitmessage.txt
> +
미처 생각못했던 부분이였네요..!
.gitignore 설정을 통해 해당 파일을 제외했습니다!

2023-02-16 22:51 UTC, Choi-JJunho commented on src/main/java/ladder/controller/LadderGameController.java
> +        List<String> players = InputView.askPlayerNames();
우선 코드 작성관점에서 인스턴스 생성구문을 줄일 수 있다고 생각해서 간결한 코드가 되는 것을 기대하여 사용하였습니다.

``` java
// non static
InputView inputView = new InputView();
List<String> players = inputView.askPlayerNames();

// static
List<String> players = InputView.askPlayerNames();

```

추가로 static으로 선언함으로써 객체의 재생성을 하지 않아 무분별한 인스턴스 생성을 막음으로써 메모리의 사용량에 있어 이점이 있을것을 기대하고 사용하였습니다.

2023-02-16 22:51 UTC, Choi-JJunho commented on src/main/java/ladder/controller/LadderGameController.java
> +        OutputView.showGameResult(game.getPlayerNames(), result);
InputView에서 말씀드린 내용과 동일합니다!

2023-02-16 23:02 UTC, Choi-JJunho commented on src/main/java/ladder/domain/Players.java
> +            throw new IllegalArgumentException("참가자는 1명이하일 수 없습니다.");
예외메시지에 대한 내용도 긍정과 부정을 왔다갔다하면서 항상 고민이였는데 이번에는 생각해보지 못했었네요!
다음에는 페어와 컨벤션으로 이야기하고 시작하는 방식도 고려해볼 수 있을것 같네요😂

2023-02-16 23:13 UTC, Choi-JJunho commented on src/test/java/ladder/domain/BarsTest.java
> +        assertThat(bars.toUnmodifiableBars()).containsExactly(true, false, true, false, true);
적절한 메소드가 containsExactly밖에 생각나지 않아 해당 메소드를 사용하려고 했는데 list를 인자로 받을 수 없어 고민하다가 위와같이 작성했습니다.
isEqualTo로 비교가되는지 몰랐네요 😅

2023-02-16 23:19 UTC, Choi-JJunho commented on src/main/java/ladder/domain/RandomGenerator.java
> +public interface RandomGenerator {
로직 상에서 Random함수가 포함되어야 하는 것을 인지하고 `랜덤한 무언가를 생성한다.` 라는 이름을 먼저 채택했습니다.
이러한 이유에서 `랜덤한 무언가를 생성한다`를 확장하여 `랜덤한 숫자`, `랜덤한 포인트`, `랜덤한 무언가`를 생성하기 위한 공통 인터페이스로 만들게 되었습니다.

때문에 `RandomGenerator`가 반환할 수 있는 값이 Boolean 뿐만 아니라 Integer, String 등이 될 것을 고려하여 Generics 사용을 고려했습니다.

2023-02-18 13:38 UTC, Choi-JJunho commented
# 역할의 중복 분리

TDD와 원시값 Wrapping에 몰두한 나머지 전체 설계에 미흡한 부분이 있었습니다.
각 도메인의 책임에 대한 부분을 다시 생각해보며 리팩터링을 진행했습니다.

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/49794401/219867058-ad19a5a4-162b-4aa7-addf-8f92cbc9be84.png">

기존 구조에서 `Bars`객체와 `Line` 객체의 역할의 중복이 존재했습니다.
이에 `Line` 객체로 해당 내용을 병합하였습니다.

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/49794401/219868664-d2545412-5376-451e-b533-df101d2e1629.png">

추가로 `Point` Enum을 사용하여 boolean이 아닌 Point라는 Enum으로 상태값을 관리하도록 구성했습니다.

# 생성 책임 분리

## Players 객체 생성

기존에 `LadderGame` 내부에서 `Player`객체를 생성하는 행위를 상위 `Controller`에게 위임하였습니다.
이를 통해 `LadderGame`이 가지고 있던 역할이었던 `List<String> -> Players로 변환 및 생성`을 분리할 수 있었습니다.

## 랜덤값 생성

기존에 true값이 연속될 수 없다는 조건을 `RandomGenerator`에게 책임을 주었는데 이 책임을 `Line` 객체에게 위임하여 Random이라는 키워드를 유지할 수 있게 되었습니다.

2023-02-18 13:43 UTC, Choi-JJunho commented on src/main/java/ladder/controller/LadderGameController.java
> +        List<Line> result = game.play(height);
설계상으로는 모양을 가지고있는 것으로 설계했습니다.
`play`라는 명칭의 메소드가 반환값을 가지고 있는 것이 어색하여 해당 부분은 수정했습니다.

2023-02-18 14:19 UTC, Choi-JJunho commented on src/main/java/ladder/domain/RandomPointGenerator.java
> +    public Boolean generate(boolean before) {
확실히 해당 부분은 책임이 애매한것 같네요😅
해당 부분은 Line에게 위임하는 방식으로 수정했습니다!

2023-02-18 14:21 UTC, Choi-JJunho commented on src/main/java/ladder/domain/Bars.java
> +            Boolean generate = randomGenerator.generate(flag);
Line에게 생성 룰 책임을 위임하면서 생성과 동시에 index를 순회하는 방식으로 변경해보았습니다!

2023-02-19 00:17 UTC, seokhongkim approved these changes
주노, 1단계 미션 수고하셨습니다. 👍 
클래스가 가진 역할, 변경하신 내용을 그림으로 설명해주시니까 이해하는데 도움이 많이 됐네요.
코멘트 남긴 내용은 2단계 미션 진행할 때 함께 고민해보시면 좋겠습니다.
2단계 미션도 화이팅입니다!

2023-02-19 00:17 UTC, seokhongkim commented on src/main/java/ladder/controller/LadderGameController.java
> +        inputView = new InputView();
나중에 필요하면 외부에서 의존성을 주입받는 형태(`new LadderGameController(inputView, outputView)`)로 변경할 수도 있겠네요. :)

2023-02-19 00:17 UTC, seokhongkim commented on src/main/java/ladder/domain/RandomGenerator.java
> +public interface RandomGenerator {
확장성을 고려해서 인터페이스를 만드신 접근은 좋습니다. 👍 
개발을 하다보면 항상 확장성을 고려한 설계와 현재 구현에 최적화된 설계 사이에 트레이드 오프를 고려하여 적절한 지점을 선택해야 할텐데요. 어떤 기준으로 확장성을 고려해서 인터페이스를 사용할지, 그냥 구현 클래스만 만들지에 대해서도 고민해보셔도 좋겠습니다. :)

구현의 측면도 있지만, 데일리 때 이야기 나눈 것처럼 인터페이스 이름은 대체로 사용하는 클래스 관점에서 이름을 작성하는 것이 도움이 될 수 있다는 점을 고려해서 고민해보시면 좋겠습니다.

2023-02-19 00:17 UTC, seokhongkim commented on src/main/java/ladder/domain/Players.java
> +            throw new IllegalArgumentException("참가자는 1명이하일 수 없습니다.");
컨벤션을 함께 이야기하는 것 좋네요!

2023-02-19 00:17 UTC, seokhongkim commented on src/main/java/ladder/domain/Line.java
> +        if (width < 1) {
1도 상수로 관리할 수 있겠네요!
예외를 발생시킨 갑싱 무엇인지 예외에 포함시킨 것 좋습니다. 👍

2023-02-19 00:17 UTC, seokhongkim commented on src/main/java/ladder/domain/Lines.java
> +    private final List<Line> lines = new ArrayList<>();
`Name` 클래스에서는 값을 `value` 로 관리하는데, `Lines` 클래스에서는 값을 `lines` 로 만드신 이유가 있는지 궁금합니다. :)
어떤 기준으로 필드의 이름을 정하면 좋을까요?

2023-02-19 00:17 UTC, seokhongkim commented on src/main/java/ladder/view/OutputView.java
> +    private static final String HORIZON = "-----";
`HORIZON`, `NONE`의 길이, `String.format("%5s", name)`으로 포맷팅할 때 사용하는 이름의 길이가 서로 연관이 있는 것 같네요.
이름의 길이가 달라질 때 변경을 쉽게 할 수 있는 방법도 있을까요?

2023-02-19 00:17 UTC, seokhongkim commented on .gitignore
> +.gitmessage.txt
파일 마지막에 newline 이 없다고 깃헙에서 경고를 띄워주네요.
파일 마지막의 newline 은 왜 필요할까요? 항상 필요하다면 사람이 챙기지 않아도 되도록 설정할 수 있는 방법은 무엇이 있을까요?

2023-02-19 00:17 UTC, merged