[1단계 - 사다리 생성] 디투(박정훈) 미션 제출합니다.
woowacourse/java-ladder pull request #94
Opened 2023-02-16 07:01 UTC by shb03323

안녕하세요 배럴! 이번에 리뷰를 받게된 디투입니다.
리뷰 받게되어 영광입니다:) 잘 부탁드립니다😃

이번 미션 진행 동안 고민이 몇몇 있었습니다. 그리고 아직 해결되지 않는 고민에 대해 의견을 여쭙고 싶습니다.

1. 예외 처리를 할 때 사용자의 입력이 아닌 개발자의 실수로 난 에러까지도 예외 처리를 해야할까요? 지금 사다리 미션에서 Line(가로로 된 다리의 목록)을 생성할 때 `플레이어 수 -1`의 길이로 리스트가 생성되는데, 테스트 코드를 짜는 개발자가 실수로 규칙을 지키지 않았을 때를 대비한 예외 처리까지 진행하는지 궁금합니다.

2. view에 정보를 전달할 때 도메인 인스턴스 자체를 view의 메소드 인자로 넣어 메소드 안에서 getter를 사용하는 방향으로 구현하였습니다. 하지만 저는 이 방법이 옳다고 생각하지 않아서요... 저는 dto를 사용하여 필요한 정보만 넣으면 좋지 않을까 생각합니다. 하지만 코치님들께서는 "굳이 dto를 사용하지 않고 구현할 수 있다." 라고 말씀하십니다. dto를 사용하지 않는 방법으로는 1) controller에서 필요한 정보만 맵핑하여 새로운 List를 만드는 것. 2) view에 한번에 많은 정보를 전달하지 않는 것. 이라고 생각하는데, 1)의 경우 dto를 만들지 않았을 뿐 dto를 사용하는 것과 다른점이 없다고 생각합니다. 또, 2)의 경우에는 도메인 계층 구조 때문에 여러번의 view 호출을 하는 것이 옳다고 생각하지 않아서요... 혹시 제가 놓친 부분이 있을까요? 어떤 부분을 놓치고 있는지 궁금합니다.

부족한 코드 봐주셔서 감사합니다:) 좋은 밤 보내십시오😃

2023-02-17 06:20 UTC, knae11 requested changes
안녕하세요 디투~ 반가워요!
코멘트 조금 남겨보았습니다~

2023-02-17 06:20 UTC, knae11 commented on docs/README.md
> +## 기능 요구사항
Readme :+1:

Ladder, Block, Line 등의 용어를 사용하였는데요. 각각의 용어에 대한 정의를 README로 남겨보는 건 어때요?

2023-02-17 06:20 UTC, knae11 commented on src/main/java/ladder/domain/ladder/Block.java
> +        this.status = status;
오잉 status -> 0, 1 은 어떤 의미 인가요?

2023-02-17 06:20 UTC, knae11 commented on src/main/java/ladder/domain/ladder/Ladder.java
> +public class Ladder {
Ladder, Line 둘다 일급컬렉션을 목적으로 만든 것으로 생각되는데요. 지금 단순히 객체들을 리스트로 가지고 있다가 꺼내주는 역할만 하고 있는 것으로 보여요. 각각이 가지고 있는 역할은 무엇일까요?
https://tecoble.techcourse.co.kr/post/2020-05-08-First-Class-Collection/

2023-02-17 06:20 UTC, knae11 commented on src/main/java/ladder/controller/LadderGameController.java
> +        List<String> playersName = mapPlayersToPlayersName(players);
toPlayerNames 정도로만 해도 충분하지 않을까요? Players를 PlayersName에 매핑한다라는 비지니스 로직처럼 느껴져요.

2023-02-17 06:20 UTC, knae11 commented on src/main/java/ladder/view/InputView.java
> +    private static final Scanner scanner = new Scanner(System.in);
사용한 scanner에 대한 자원정리도 해주세요~

2023-02-17 06:20 UTC, knae11 commented on src/test/java/ladder/domain/TestBlockGenerator.java
> +        return blocks.remove(0);
뭔가 RandomBlockGenerator는 EXIST, EMPTY 중 하나를 랜덤하게 반환하고, TestBlockGenerator는 EXIST 또는 EMPTY를 반환할 것 같은데요. 로직 자체가 다르게 움직여서 조금 신기하네요!

2023-02-17 06:21 UTC, knae11 commented
1. 로직이 복잡해질수록 개발자도 실수하기 쉽다고 생각하는데요. 실수할 수 있는 것에 대한 대비책이 있다면 좋지 않을까요?
2. 2번 내용에 대해서는 저도 조금 답변이 궁금한데요. 도메인을 넘기지 않는다면  List, Map 등으로 필요한 정보를 정리해서 View에 보낼 수 있다고 생각하는데요. 이것을 dto를 만들지 않았을 뿐 dto 사용과 다른게 없다라고 얘기하는 부분이 모호하네요. dto를 만들지 않았다는 것은 dto를 사용하는거와 다른 것이긴 하니까요~?!  이런 방법이 아니라 다른 방법을 코치님들이 알려주신다면 저에게도 공유해주세요~ㅎㅎㅎ

2023-02-18 15:47 UTC, shb03323 commented on docs/README.md
> +## 기능 요구사항
말씀해주셔서 감사합니다. 도메인 별로 작성되어있지 않아 한 눈에 파악하기 어려웠다는걸 말씀해주신 덕분에 알게되었습니다!

2023-02-18 15:52 UTC, shb03323 commented on src/main/java/ladder/domain/ladder/Block.java
> +        this.status = status;
사다리 발판이 있고(1), 없고(0)를 숫자로 표현하였습니다. 코드를 작성할 당시에는 "enum에 다른 상태도 들어오지 않을까?"라는 생각으로 확장성을 고려해 `boolean` 대신 `int`로 타입을 지정했습니다. 다시 생각해보니 사다리 발판은 아무리 확장되어도 새로운 상태의 발판이 생길 것 같지 않습니다. 
사다리의 발판 상태를 `boolean`으로 바꾸었고, 변수 네이밍 또한 헷갈리지 않도록 수정하였습니다.

2023-02-19 07:27 UTC, shb03323 commented on src/main/java/ladder/domain/ladder/Ladder.java
> +public class Ladder {
이 부분에서 가장 많이 고민했습니다. 지금 1단계 미션에서는 "사다리 만들기"와 "사다리 출력하기"의 기능만 존재합니다. 또, 만들기에 관련된 메서드들은 객체를 따로 분리하여 설계하여서 Ladder와 Line 객체 안에는 출력을 제외한 기능이 필요하지 않다고 생각합니다! 추후 사다리 타기 게임을 진행하게 되면 Ladder와 Line에 조금 더 많은 역할이 생길 것 같습니다😀

이 부분에 대해 말씀해주신 이유가 LadderMaker와 LineMaker 객체를 Ladder와 Line에 각각 합치는 것에 대해 고려해보라는 말씀이실까요?😅😅 링크로 보내주신 블로그도 읽어보았지만 정말 이유를 모르겠어서요ㅠㅠㅠ 혹시 힌트 조금만 주실 수 있을까요?

+) 만약 객체 통합을 말씀하신 게 맞다면 제 생각은 이렇습니다. 우선 객체의 역할이 많을 것 같다고 생각합니다. "만들기"를 위해 지켜야할 조건이 1) 플레이어 수 - 1 만큼의 가로 줄 생성하기  2)랜덤으로 생성하기  3)가로 줄이 이어지지 않게 생성하기 4) 입력한 높이에 맞게 사다리 생성하기 입니다. 만약 하나의 객체에서 사다리를 생성한다면 이 모든 규칙들을 메서드로 정의해주어야하기 때문에 객체가 무거워질 것 같다고 생각합니다.
또, "만들기"에서만 필요한 NumberGenerator가 Ladder와 Line 객체에 인스턴스로 존재하게 됩니다. 이는 일급 컬렉션의 규칙을 깬다고 생각합니다!

2023-02-19 07:29 UTC, shb03323 commented on src/main/java/ladder/controller/LadderGameController.java
> +        List<String> playersName = mapPlayersToPlayersName(players);
stream의 메서드들에서도 toMap, toSet과 같이 사용하는데, 이름을 너무 길게 지은 것 같습니다. 오해의 소지가 없도록 수정했습니다!

2023-02-19 07:34 UTC, shb03323 commented on src/main/java/ladder/view/InputView.java
> +    private static final Scanner scanner = new Scanner(System.in);
기초적인 부분을 놓쳤네요... 말씀해주셔서 감사합니다:)

2023-02-19 07:44 UTC, shb03323 commented on src/test/java/ladder/domain/TestBlockGenerator.java
> +        return blocks.remove(0);
테스트를 위한 객체이기 때문에 개발자가 원하는 값을 넣을 수 있어야한다고 생각했습니다. 생성자를 통해 원하는 Line을 만들 수 있도록 했습니다!
혹시 로직이 너무 다르다면 동료 개발자에게 혼동을 줄 수 있을까요...?

2023-02-19 09:02 UTC, shb03323 commented
안녕하세요 배럴! 말씀해주신 코멘드 덕분에 실수한 부분에 대해서도 알았고, 무엇보다 코드 작성할때는 고려하지 못한 새로운 생각을 할 수 있었습니다. 꼼꼼하게 체크해주셔서 감사합니다😄

질문으로 "controller에서 필요한 정보만 맵핑하여 새로운 List를 만드는 것은 dto를 만들지 않았을 뿐 dto를 사용하는 것과 다른점이 없다고 생각합니다."라고 말했었는데, `새로운 클래스를 생성하는 것`과 `controller에서 List와 같은 형태를 반환하는 메소드를 생성하는 것`이 목적은 같지 않나?라는 생각으로 글을 작성했습니다.
지금은 본질에서 벗어난 고민을 했다는 생각에 조금 부끄럽네요ㅎㅎ..
코치님들은 dto를 사용할만큼 큰 서비스가 아니라고 하셨습니다. 모든 객체의 인스턴스 변수가 2개 이하인데 굳이 써야하나?로 느꼈습니다! 그래서 저도 dto를 사용하기보다 controller에서 List<List<Boolean>> 형태로 변환 후 view로 넘겨주었습니다.

일급 컬렉션 관련 언급해주신 부분에서 제 생각을 남겼는데, 답장해주시면 감사하겠습니다:)

남은 주말 행복하게 보내시길 바라겠습니다.:)

2023-02-19 11:20 UTC, knae11 commented on src/main/java/ladder/view/InputView.java
> +    private static final Scanner scanner = new Scanner(System.in);
메서드 안에서 호출하는 것은 조금 위험해보이는데요. height 이외에 다른 입력 메서드가 뒤에 생길 수도 있는데, 이런 경우라면 height 입력 메서드도 확인을 해야겠어요..!!

2023-02-19 11:20 UTC, knae11 commented on src/test/java/ladder/domain/TestBlockGenerator.java
> +        return blocks.remove(0);
저는 코드 자체만을 봤을 때는 generate 인데 blocks에서 제거하는 방식의 로직이 왜 들어가지 싶어서 혼란스럽긴 하네요!ㅎㅎㅎ 메서드 네이밍과 너무 다른 구현이라서요.

2023-02-19 11:39 UTC, knae11 commented on src/main/java/ladder/domain/ladder/Ladder.java
> +public class Ladder {
저는 생성의 역할을 담당하는 것도 일급컬렉션이 해야할 역할이라고 생각했는데요. Line 과 Ladder가 지금 왜 필요한지 궁금했어요. `List<Block>` 을 관리하는 것이 Line이 일급컬렉션으로 해야할 일이라면요. 지금 어떤 역할을 하고 있는 건가요?

2023-02-20 07:58 UTC, shb03323 commented
배럴 안녕하세요:)
객체 통합에 관해 페어와도 이야기해보았습니다. 같이 코드를 작성할때는 분리하는 것이 옳다고 저희 둘 다 생각했었는데, 제 페어도 같은 피드백을 받으셨더라구요! 그래서 페어와 왜 통합이 더 좋은 방법인지 토론해보았어요. `BlockGenerator`가 필드로 생기는 것을 막기 위해 객체를 분리했던게 아닐까? 이 객체가 없었다면 과면 객체 분리를 했을까? 라는 생각이 들었어요. 지금은 `BlockGenerator`가 들어가도 괜찮다는 생각입니다. 일급 컬렉션이라 하더라도 그 객체를 관리하기 위해 존재하는 필드이기 때문이죠.

하지만 여전히 확신이 들진 않아요... 과연 일급 컬렉션 안에 collection이 아닌 다른 필드가 들어가도 되는지에 대해서요... 일급 컬렉션 규칙에 대해 유연하게 대처를 해야하는지, 유연하면 안되는 것인지 궁금합니다.

또, controller -> Ladder -> Line 방향으로 BlockGenerator를 주입시키는데, 주입을 위해 거치는 객체가 많다고 생각합니다. 마땅히 다른 방법이 떠오르지도 않아서요... 혹시 이 문제를 해결하기 위해 공부해보아야 할 것이 있다면 추천해주시면 감사하겠습니다!

2023-02-20 10:13 UTC, knae11 commented
안녕하세요 :) 디투!
페어는 어떤 코멘트를 받았는지 궁금하네요! 뭐가 옳다 그르다는 아닌데요. 고민했던 제 생각을 적어볼게요~ :) 
- BlockGenerator가 꼭 생성자로만 받아야 할까요? generate 메서드를 만들고 해당 메서드에서 받을 수도 있지 않을까요?
    - List 컬렉션의 경우에도 `new ArrayList`로 초기화만 진행하고 `add` 나 `List.of`등의 정적 메서드를 통해서 내부 요소를 채워주는데요. 이런 개념으로 생각해 볼 수 있지 않을가 싶었어요.
    - 처음 구현한 것처럼 리스트 보관용으로만 사용한다고 하더라도, 수정 등의 API가 없어진다는 점에서 나름 객체의 존재 의미를 찾을 수도 있겠네요.
- 생성 로직이 무거워서 Maker 로 분리하여 역할을 위임했다면, Maker의 생성호출은 Line에서 관리 및 호출되어야 하지 않을까 생각했어요. 
- 말씀해주신대로 일급컬렉션의 규칙이 다른 필드가 들어가지 않는 것이라면, 규칙은 지켜져야 일급컬렉션이라고 할 수 있을 것 같네요! 
- 주입 방향에 걸쳐지는 객체가 많다는 것은 의존하고 있다는 의미처럼 느껴지기도 하는데요. 실제로 Controller -> Ladder -> Line 방향으로 의존하고 있기 때문에 제 생각에는 문제가 없을 것 같아요!

디투 덕분에 일급컬렉션의 의미에 대해서 좀 더 생각해보게 된 것 같아요. 고민하면서 느낀건 Collection이 범용적으로 만들어진 객체라면 일급컬렉션은 한번 감싸서 내가 원하는 방향으로 만든 객체인가 싶은 생각이 드네요! (https://jojoldu.tistory.com/412 이 글 읽고나서 좀 그런 생각이 들었어요) 더 공부해야할 것이라..면 저도 잘 모르겠는데요ㅠㅠ 코치님들 아닐까요?ㅋㅋㅋㅋㅋ 좋은 자료 있다면 저도 공유해주세요~ :)

2023-02-20 10:16 UTC, knae11 approved these changes
호호 제 생각을 코멘트 남겨보았습니다! 아니다 싶은 내용이나 좋은 공유자료 있으면 저에게도 공유 부탁드려요ㅎㅎㅎ 2단계 미션을 하면서 같이 좀 더 생각해보면 좋을 것 같습니다~~~
그러므로 1단계는 Merge 할게요!! 너무 고생하셨습니당~!!

2023-02-20 10:16 UTC, merged