[1단계 - 사다리 생성] 헙크(정현승) 미션 제출합니다.
woowacourse/java-ladder pull request #95
Opened 2023-02-16 07:01 UTC by HubCreator

안녕하세요 카일님! 헙크입니다.
이번 미션 리뷰를 맡아주셔서 영광입니다!!

이번 미션을 진행하면서 몇 가지 궁금증이 생겨 페어와 몇 가지 정리를 해보았습니다.

1. **검증의 반환타입에 대해서 컨벤션이 있는지 궁금합니다.** 
    
    ```java
    private int validate(String input) {
    		try {
    		    return Integer.parseInt(input);
    		} catch (NumberFormatException exception) {
    		    throw new IllegalArgumentException("숫자를 입력해야 합니다.", exception);
    		}
    }
    ```
    
    “숫자만 입력 가능하다”라는 검증 조건이 있다면, 개인적으로는 위와 같이 검증을 함과 동시에 문자열을 숫자로 변환하여 반환 받도록 구현했습니다. 하지만 페어와 얘기를 나누다보니 이 메서드에는 검증을 하는 책임과 문자를 숫자로 변환하는 책임(두 가지 책임)이 있기 때문에 메서드를 분리해야 한다는 생각이 들었습니다.
    
    하지만 한편으로는, 그렇게 로직을 분리한다면 `parseInt`를 두 번 해주어야 하고 괜히 불필요하게 코드가 길어지지 않나 생각이 되었습니다. 해당 메서드를 실행하는 비용이 그리 크진 않겠지만 이렇게 검증과 변환 로직을 분리하는 것이 좋을까요?
    
    ```java
    psvm {
    		String input = "1234";
    		validate(input);
    		int value = Integer.parseInt(input);
    
    		...
    }
    
    private void validate(String input) {
    		try {
    		    Integer.parseInt(input);
    		} catch (NumberFormatException exception) {
    		    throw new IllegalArgumentException("숫자를 입력해야 합니다.", exception);
    		}
    }
    ```
    
2. **사다리의 최대 높이(maxHeight)를 필드값으로 저장해야 하는가?**
    
    저희는 `maxHeight`을 사용자로부터 입력 받았지만, 이를 필드값으로 저장하지 않았습니다. 왜냐하면 `List<Line> lines`로 필드에서 사다리를 구성하였기에, 추후에 `height`가 필요하다면 `lines.size()`를 통해 파악할 수 있다고 판단했기 때문입니다. 이렇게 `maxHeight`을 변수로 저장하지 않고 컬렉션의 사이즈를 통해 값을 알아내는 방식이 안전할지 궁금합니다.
    
3. **도메인에서 도메인을 넘겨주는게 좋나요 기본값(원시값, 래퍼클래스)를 넘겨주는게 좋나여?**
    
    ```java
    public List<String> getNames() {
        return people.stream()
            .map(Person::getName)
            .collect(Collectors.toList());
    }
    ```
    
    저희는 도메인을 넘겨주어 상위에서 `getter`를 지저분하게 사용하기보다, `getter`에서 도메인 내부의 필드값을 반환하는 방식이 깔끔한 것 같아서 위와 같은 방법을 사용했습니다. 이런 방식을 사용했을 때 문제점이 있는지 궁금합니다.

2023-02-16 14:43 UTC, KIMSIYOUNG requested changes
안녕하세요.
전체적으로 구현은 잘 해주셨는데 각각의 클래스에 대한 테스트가 부족한 것 같아요. 
테스트를 조금 더 보완해보시면 좋을 것 같습니다.

2023-02-16 14:43 UTC, KIMSIYOUNG commented on docs/README.md
> +# 기능 목록
요구사항을 깔끔하게 잘 정리해주셨네요👏

2023-02-16 14:43 UTC, KIMSIYOUNG commented on src/main/java/view/LineType.java
> +public enum LineType {
뷰를 위한 로직도 깔끔하게 잘 정리해주셨네요👏

2023-02-16 14:43 UTC, KIMSIYOUNG commented on src/main/java/domain/Person.java
> +    public Person(String name) {
해당 부분에 대한 테스트가 없네요.

초기 커밋 이후에는 TDD가 제대로 잘 진행되지 않은 것 같아요! 

왜 잘 진행되지 않았는지 고민해보시면 좋을 것 같습니다.

2023-02-16 14:43 UTC, KIMSIYOUNG commented on src/main/java/domain/People.java
> +    public List<String> getNames() {
이렇게 제공했을 때의 장점은 무엇인가요? 현재는 뷰를 위해 편하게 제공하기 위한 기능으로 보여서요!

2023-02-16 14:43 UTC, KIMSIYOUNG commented on src/main/java/domain/BridgeGenerator.java
> +@FunctionalInterface
해당 어노테이션이 어떠한 역할을 하는지 아시나요?

2023-02-16 14:43 UTC, KIMSIYOUNG commented on src/main/java/domain/Ladder.java
> +    private final List<Line> lines;
상수와 변수 사이에는 한칸 띄워주세요!

2023-02-16 14:43 UTC, KIMSIYOUNG commented on src/main/java/domain/RandomBridgeGenerator.java
> +public class RandomBridgeGenerator implements BridgeGenerator {
Ladder 라는 객체가 있음에도 이러한 형태로 구현하신 이유가 있을까요?

2023-02-16 14:43 UTC, KIMSIYOUNG commented on src/main/java/domain/Line.java
> +    private void validateSequential(Boolean previousMovement, Boolean currentMovement) {
생성에 대한 역할이 분산되고 있는 것 같아요. (Line, RandomBridgeGenerator)

2023-02-16 14:43 UTC, KIMSIYOUNG commented on src/main/java/domain/People.java
> +    public People(List<Person> people) {
사람은 2명이상이어야 한다는 테스트도 없는 것 같아요.

2023-02-16 14:43 UTC, KIMSIYOUNG commented on src/main/java/domain/Ladder.java
> +        return lines.get(0).size();
현재의 요구사항을 만족하기 위해서, 필드로 꼭 저장하고 있을 필요는 없을 것 같아요. 

다만 직관적이진 않은 것 같네요🙂

2023-02-16 14:46 UTC, KIMSIYOUNG commented on src/main/java/view/InputView.java
> +    private void validateNumberFormat(String input) {
이러한 부분은 같이 수행해도 괜찮을 것 같아요. 검증과 변환이 같이된다고 볼 수도 있지만, 변환을 하는 과정에서 예외는 충분히 발생할 수 있으니까요!

다만 네이밍은 변환한다가 되어야겠죠?

2023-02-18 05:54 UTC, HubCreator commented on src/main/java/domain/Person.java
> +    public Person(String name) {
검증의 책임을 고민하다가 놓친 것 같습니다. 검증의 `name`의 길이를 제외한 검증은 `InputView`에서 책임이 있다고 판단했기에, 이 과정에서 뷰는 테스트하지 않아도 되지 않을까 생각했던 것 같습니다ㅠㅠ 그래도 `Person` 도메인에 대한 테스트를 놓친거는 실수였던 것 같습니다. 감사합니다!

2023-02-18 05:57 UTC, HubCreator commented on src/main/java/domain/BridgeGenerator.java
> +@FunctionalInterface
`@FunctionalInterface`는 인터페이스를 람다식의 타겟 타입으로 사용하기 위해 사용합니다. 해당 애노테이션을 사용함으로써, 컴파일 타임에 인터페이스 내의 추상 메서드를 오직 하나만 가질 수 있도록 체크할 수 있다고 알고 있습니다!

2023-02-18 06:02 UTC, HubCreator commented on src/main/java/domain/People.java
> +    public List<String> getNames() {
네 맞습니다! 호출부에서 `List<Person>`을 받는 것 보다 `List<String>`을 받는 것이 조금 더 편리하다고 생각하여서, 일급 컬렉션에서 값을 변환하여 반환하였습니다.

2023-02-18 06:02 UTC, HubCreator commented on src/main/java/domain/Ladder.java
> +    private final List<Line> lines;
넵!!

2023-02-18 14:57 UTC, HubCreator commented on src/main/java/domain/People.java
> +    public People(List<Person> people) {
넵!

2023-02-18 15:22 UTC, HubCreator commented on src/main/java/domain/RandomBridgeGenerator.java
> +public class RandomBridgeGenerator implements BridgeGenerator {
`Ladder` 클래스의 테스트가 조금 더 용이하지 않을까 싶어서 이런 형태로 구현했습니다. 당장은 사다리의 폭과 높이 정도만 테스트를 하므로 지장이 없지만, 추후에 제가 원하는 `Ladder`의 형태를 고정적으로 테스트하기 위해서는 전략패턴을 사용하는 것이 좋다고 판단했습니다.

2023-02-18 16:03 UTC, HubCreator commented on src/main/java/view/InputView.java
> +    private void validateNumberFormat(String input) {
`toNumber`로 메서드명을 수정하였습니다!

2023-02-18 16:10 UTC, HubCreator commented on src/main/java/domain/Line.java
> +    private void validateSequential(Boolean previousMovement, Boolean currentMovement) {
전략이 다르다고 보고 `Generator`에서 랜덤한 `movements`를 반환받아 `Line`의 필드값에 할당하였는데, 이 또한 역할이 분산되었다고 볼 수 있나요? 아니면 제가 이렇게 프로그래밍하고 설계한 방식이 옳지 않은 것인가요? 현재는 감이 잘 오지 않습니다.. 제가 어떤 부분을 놓치고 있는지 알려주시면 많은 도움 될 것 같습니다. 감사합니다!!

2023-02-19 11:50 UTC, KIMSIYOUNG commented on src/main/java/domain/Person.java
> +    public Person(String name) {
어떠한 기준으로 검증이 InputView에 있다고 생각하시나요? 기준이 궁금해요!

2023-02-19 11:51 UTC, KIMSIYOUNG commented on src/main/java/domain/People.java
> +    public List<String> getNames() {
호출부는 뷰이고, 기능을 제공하는 것은 도메인인 것 같아요. 

도메인이 뷰를 위해서 편의성 기능을 제공한다고 다르게 표현될 수 있을 것 같고 도메인이 뷰에 의존한다고도 표현할 수 있을 것 같습니다.

도메인이 직접적으로 뷰에 의존하지 않더라도 현재와 같은 구조도 의존성을 가지는 것 같아요.

도메인이 뷰에 의존하면 어떤 점이 좋지 않을까요?

2023-02-19 11:52 UTC, KIMSIYOUNG commented on src/main/java/domain/BridgeGenerator.java
> +@FunctionalInterface
맞습니다.

추가로 람다식으로만 사용하기 위한 인터페이스인 경우에 해당 어노테이션을 명시적으로 붙여주라고 가이드하고 있어요.
현재는 람다식으로만 사용하기 위함이 아니기 때문에 굳이 붙여주지 않아도 될 것 같아요.

2023-02-19 11:58 UTC, KIMSIYOUNG commented on src/main/java/view/InputView.java
> +    private void validateNumberFormat(String input) {
👏

2023-02-19 12:03 UTC, KIMSIYOUNG commented on src/main/java/domain/Line.java
> +    private void validateSequential(Boolean previousMovement, Boolean currentMovement) {
위의 코멘트와 같은 맥락으로 이야기해보면 좋을 것 같아요.

1. 역할은 분산되었다고 볼 수 있을 것 같아요. 사다리나 라인이 존재하지만 이들을 생성하는 로직 자체는 외부로 분리되었으니까요!
2. 다만 잘못된 방식이라고 볼 순 없을 것 같아요. 말씀하신대로 생성하는 부분이 복잡하고 형태가 다양해질 수 있다면 분리하여서 따로 관리하는 것도 좋은 방법인 것 같습니다. 실제로 객체 생성이 복잡한 경우 Factory 패턴으로 생성하는 케이스도 많이 있어요!

개인적인 의견으로 객체의 생성이 분리된다면, 생성 자체에 대해 분리한 곳에서 생성을 온전히 책임지는 것이 가독 및 유지보수에 용이할 것 같아요. 위에서 남긴 코멘트는 객체를 생성하는 곳과, 생성된 객체 모두 생성과 관련된 로직을 일부 가지고 있기 때문에 가독 및 유지보수가 어렵지 않을까해서 드린 코멘트였습니다.

2023-02-19 12:08 UTC, KIMSIYOUNG approved these changes
안녕하세요 헙크!
댓글 남겨주신 부분 대댓글 남겨두었습니다.
잘 구현해주셔서 1단계는 여기서 머지하겠습니다.
얘기 나누던 것들은 2단계에서 같이 더 이야기해보면 좋을 것 같습니다.

2023-02-19 12:08 UTC, KIMSIYOUNG commented on src/main/java/controller/LadderController.java
> +        List<Person> collect = inputView.readNames().stream()
이러한 책임은 Person을 관리하는 People에서 구현되어야 더 적절할 것 같아요.

2023-02-19 12:08 UTC, KIMSIYOUNG commented on src/main/java/domain/RandomGenerateStrategy.java
> +    public List<Boolean> generate(int count) {
실제로 인덱스 관련된 내용이 사다리게임에서는 꽤 복잡하게 얽히는 것 같아요.
이 부분은 어쩔 수 없지만, 변수나 네이밍을 통해서 조금 더 의미를 드러내보면 어떨까요?

2023-02-19 12:08 UTC, merged

2023-02-19 12:29 UTC, HubCreator commented on src/main/java/domain/Person.java
> +    public Person(String name) {
어느 객체에서 검증을 해야 할 책임이 있는가를 기준으로 생각했습니다. `Person`의 입장에서 객체 생성시 알 수 있는 정보는 사용자로부터 입력 받은 문자열 전체가 아닌, `InputView`에서 제대로 걸러준 이름 하나여야 한다고 생각했기 때문에, `Person`에서는 글자 수만 검증하였습니다. 그 외 `InputView`로부터 입력 받은 문자열을 쉼표로 구분하고 중복된 이름을 검증하는 것은 `Person`에 이름을 넘겨주기 이전에, 입력을 제대로 받지 못한 것이라고 생각했습니다. 따라서 이를 처리해야 할 책임은 `InputView`에 있다고 생각했습니다.

2023-02-19 12:45 UTC, HubCreator commented on src/main/java/domain/People.java
> +    public List<String> getNames() {
도메인의 생명주기보다 뷰의 생명주기가 더 짧을 것으로 예상됩니다. 뷰의 변경이 더 빈번할 것이고, 도메인이 뷰에 의존한다면 뷰의 구조가 바뀔 때마다 도메인에 영향을 미칠 것이기 때문에 좋지 않을 것입니다.

현재 제가 짠 코드에서는 `controller`에서 `People `도메인의 `getNames()`를 호출하고 있는데, 이 또한 도메인이 뷰에 의존한다고 볼 수 있나요??

만약 의존한다면 도메인의 `getter`에 방어적 복사를 사용하거나, `dto`를 도입함으로써 의존성을 끊어낼 수 있다고 알고 있습니다.

2023-02-19 12:46 UTC, HubCreator commented on src/main/java/domain/BridgeGenerator.java
> +@FunctionalInterface
제가 잘 몰랐습니다. 정말 감사합니다!!

2023-02-19 13:08 UTC, HubCreator commented on src/main/java/controller/LadderController.java
> +        List<Person> collect = inputView.readNames().stream()
제가 놓쳤습니다. 감사합니다!

2023-02-19 13:17 UTC, HubCreator commented on src/main/java/domain/RandomGenerateStrategy.java
> +    public List<Boolean> generate(int count) {
네넵! 반영해보겠습니다.

2023-02-19 13:54 UTC, HubCreator commented on src/main/java/domain/Line.java
> +    private void validateSequential(Boolean previousMovement, Boolean currentMovement) {
현재 저의 코드는 `Line`과 `Generator` 모두에서 생성과 관련된 로직을 일부 가지고 있네요. step2에서는 `Generator`에게 모두 위임한후, 그 결과를 그대로 `List<Boolean`>으로 받아 `Line`에게 주입하는 방식을 사용하면 조금 더 깔끔하지 않을까 생각이 됩니다. 팩터리 패턴에 대해서도 공부해보겠습니다. 감사합니다!

2023-02-22 06:24 UTC, HubCreator commented on src/main/java/domain/Person.java
> +    public Person(String name) {
제가 생각이 짧았습니다. step2 과제를 진행하면 할 수록 `People`에 검증 로직을 두는 것이 더 좋다고 생각했습니다. `People`은 `Person`의 `List`를 가지고 있기 때문에, `Person` 상위에서 처리해야 할 "이름 중복 검사", "사람 수 검사"를 진행하고, `InputView`에서는 사용자의 입력 포맷이 올바른지 정도만 검증을 진행하는 것이 좋다고 생각했습니다.

객체의 책임을 생각했을 때, 도메인에서 필요한 검증들을 해야 응집도도 높아지고 책임이 명확해지는 것 같았습니다. 또한 추후에 해당 도메인을 사용하는 곳에서는 공통적인 검증이 수행 될 수 있을 것 같습니다.